### ISSUE TITLE
和 react-use rehooks 的差异是？

### ISSUE THREAD

**Issue by afc163** [alibaba/hooks#1]
- https://github.com/streamich/react-use
- https://github.com/rehooks

何不直接依赖这些库，再加上我们自己特有的东西，避免重复造轮子。

**Comment by brickspert** [comment]
是不会重复造轮子的，周会讨论的也是沉淀别人没有的 hooks。
和这些库的关系，也是依赖它们。

**Comment by afc163** [comment]
useTitle 基本上就是重复的。

**Comment by brickspert** [comment]
@afc163  是的，这个是抄的 react-use 的，先尝试把架子搭起来，测试发布流程跑通。接下来这个 useTitle 应该会删掉的。😋
