### ISSUE TITLE
`useSet` must not mutate `set` if added value already exists in the set

### ISSUE THREAD

**Issue by nikolay-borzov** [alibaba/hooks#1007]
From the source code
```js
 add: (key: K) => {
  setSet((prevSet) => {
    const temp = new Set(prevSet);
    temp.add(key);
    return temp;
  });
},
```

Creating new set does not make sense when `prevSet.has(key) === true`. For example if we render list of names - it is not needed to re-render list if already added name is added again

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
