### ISSUE TITLE
useCountDown中targetDate使用moment不正确

### ISSUE THREAD

**Issue by xccjk** [alibaba/hooks#1010]
在useCountDown的targetDate中传入一个经过moment转换的时间戳，倒计时好像不生效
```
const [countdown, setTargetDate, formattedRes] = useCountDown({
    targetDate: moment(startTime).format('YYYY-MM-DD HH:mm:ss')
 })
```

**Comment by brickspert** [comment]
经测试，可以正常工作：https://codesandbox.io/s/basic-usage-forked-zrkul?file=/App.tsx

可以看下 `moment(startTime).format('YYYY-MM-DD HH:mm:ss')` 输出的内容是否符合预期
