### ISSUE TITLE
useAntdTable 不支持 4.x 的 antd

### ISSUE THREAD

**Issue by PeterChen1997** [alibaba/hooks#1016]
使用 table form 绑定时，官网的 demo 已经不兼容了，提示 create is deprecated

![image](https://user-images.githubusercontent.com/21072589/124902918-fbe5ab80-e015-11eb-9e31-e2205a162a26.png)
![image](https://user-images.githubusercontent.com/21072589/124902938-03a55000-e016-11eb-8980-c277253af271.png)

**Comment by brickspert** [comment]
v3 是用的 Form.create()

v4 的 demo 在这里：https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useAntdTable/demo/demo3.tsx

**Comment by PeterChen1997** [comment]
> v3 是用的 Form.create()
> 
> v4 的 demo 在这里：https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useAntdTable/demo/demo3.tsx

收到，感谢

官网上的标注有些不太明显，感觉在 demo 前说明下比较直观，如果需要的话我可以改改

**Comment by brickspert** [comment]
> > v3 是用的 Form.create()
> > v4 的 demo 在这里：https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useAntdTable/demo/demo3.tsx
> 
> 收到，感谢
> 
> 官网上的标注有些不太明显，感觉在 demo 前说明下比较直观，如果需要的话我可以改改

嗯，可以·~
