### ISSUE TITLE
useRequest 中的分页功能在切换 pageSize 时如果当前页码超出项目总数时页码不能自动变更

### ISSUE THREAD

**Issue by seoi2017** [alibaba/hooks#1018]
在使用useRequest中的分页功能时，假设当前有30项，每页20项，考虑如下情况：

1. 此时分页应该有两页，切换到第二页，显示第21至第30项
2. 切换pageSize至40项每页，此时总共只有一页
3. 发现问题：此种情况下，在再次切换分页前，页码中仅有的1并未处于活动状态，内部变量显示此时页码仍维持为2，但是此时已经没有第二页

经阅读源码，推测此问题是由`usePaginated.ts`代码文件中的`onChange`方法逻辑错误引起的。

```javascript
const onChange = useCallback(
  (c: number, p: number) => {
     let toCurrent = c <= 0 ? 1 : c;
     const toPageSize = p <= 0 ? 1 : p;

     const tempTotalPage = Math.ceil(total / toPageSize);
     if (toCurrent > tempTotalPage) {
        toCurrent = tempTotalPage;
     }
     runChangePaination({
        current: c,
        pageSize: p,
     });
   },
   [total, runChangePaination],
);
```

在上述代码段中，可以看到确实存在当更改pageSize后当前页码超出显示范围则自动变更页码的逻辑，但其中的`toCurrent`和`toPageSize`变量却并未应用，在应用时事实上采用了未经处理的`c`和`p`两个参量，这可能是导致上述问题出现的原因。

经手动修改后，发现问题得到解决，但尚未进行进一步测试。考虑到个人并未详细地通读相关代码和实现逻辑，因此请问这个问题是否是由于这一原因引起的？如若不是，那么上述问题发生的可能原因是什么？

**Comment by seoi2017** [comment]
另外，同时还需要进行另一处修改：

```javascript
     if (toCurrent > tempTotalPage) {
        toCurrent = tempTotalPage;
     }
```

需要改为

```javascript
     if (toCurrent > tempTotalPage) {
        toCurrent = Math.max(1, tempTotalPage);
     }
```

否则会出现当请求列表项目总数为0时页码变为0的问题。

**Comment by brickspert** [comment]
你的想法是对的，代码确实有点问题。可以来一个 PR，谢谢啦！

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
