### ISSUE TITLE
[useRequest] useRequest 在页面第一次渲染时会改变多次状态

### ISSUE THREAD

**Issue by Richard-Choooou** [alibaba/hooks#1020]
![image](https://user-images.githubusercontent.com/23492006/125049787-eafb6f80-e0d3-11eb-98c9-1f58a7cc6b84.png)

导致本该展示 loading 的效果变成了 “没有更多了”

**Comment by aQingYun** [comment]
+1
如果设置了loading加载的话 页面会空白短暂的时间后才显示加载中

**Comment by brickspert** [comment]
可以给个 demo 吗？

**Comment by aQingYun** [comment]
#921 跟这个issue类似 loading的状态 true->false->false->true->false 
我想请问一下 在第一个状态到第四个状态之前延时较长 请问有什么方法可以解决吗？

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/125074613-1a1fda00-e0f0-11eb-8e56-2ccb40a835e4.png)


我测试的官网的 demo，没有发现你说的情况啊。不可能 loading true 会变成 false 的吧。

**Comment by amile-wp** [comment]
貌似是出现在设置了loadingdelay的情况下
