### ISSUE TITLE
useUnmountedRef在React 18下会有问题

### ISSUE THREAD

**Issue by otakustay** [alibaba/hooks#1021]
参考代码：https://github.com/alibaba/hooks/blob/7b026c03dde61449b051bb63ba68507115227cda/packages/hooks/src/useUnmountedRef/index.ts

我用一个CodeSandbox说明这个问题：https://codesandbox.io/s/unmount-guard-in-strict-effect-5eneb?file=/src/App.js

简单来说，这个实现应该类似于：

```js
useEffect(
  () => {
    // 这一行不能省
    unmountedRef.current = false;
    return () => {
      unmountedRef.current = true;
    };
  },
  []
);

**Comment by brickspert** [comment]
感谢反馈，这类问题确实存在。

目前在使用 react-refresh 时就能复现出来问题，同时在未来的 concurrent 模式中也是会有问题的。之前写了一篇《[React Hooks 在 react-refresh 模块热替换（HMR）下的异常行为](https://zhuanlan.zhihu.com/p/371132201)》来描述这个问题。

这类问题我们已经意识到了，并且在 3.0 版本已经挨个评估修复了。

可以看这个 PR：https://github.com/alibaba/hooks/pull/991/files#diff-f81d0c70efa2f952d317a92d9165f3bc6ba6316cdab42b2a90747ebb9e7a730f

在 3.0 版本，我们会彻底修复这类问题。

再次感谢反馈，我们会尽快开发完成 3.0 版本~~ ღ( ´･ᴗ･` )比心
