### ISSUE TITLE
(2.10.7) typescript false positive on requestMethod

### ISSUE THREAD

**Issue by yckbilly1929** [alibaba/hooks#1023]
after updating to 2.10.7, there will be a false positive type error for custom request method, as shown below:

![Screenshot from 2021-07-10 10-55-03](https://user-images.githubusercontent.com/12884758/125149806-ba681400-e16d-11eb-9e5e-a09626d980f4.png)

```
Argument of type '(values: SubmitForm) => SubmitForm' is not assignable to parameter of type 'CombineService<DemoRes, [SubmitForm]>'.
  Type '(values: SubmitForm) => SubmitForm' is not assignable to type '(args_0: SubmitForm) => RequestService'.
    Type 'SubmitForm' is not assignable to type 'RequestService'.
      Property 'url' is missing in type 'SubmitForm' but required in type 'RequestServiceObject'.ts(2345)
types.d.ts(9, 14): 'url' is declared here.
(parameter) values: SubmitForm
```

in our case, url is not needed as the data fetching logic is put into another separate hook file (it may deal with different datasource and client side discovery)

or shall we put commonly used fields as optional?

_Originally posted by @yckbilly1929 in https://github.com/alibaba/hooks/issues/1011#issuecomment-877548084_

**Comment by brickspert** [comment]
I have fixed it in https://github.com/alibaba/hooks/commit/c2b4ccb14deb8b737498fc1c0fb505abd12d6da7

You can update to ahooks@2.10.8

Thank you for your feedback.
