### ISSUE TITLE
useReactive can't set formData to state

### ISSUE THREAD

**Issue by rimsila** [alibaba/hooks#1024]
```tsx

const state = useReactive({
logoFormData: undefined
})
const [logoForm, setLogoForm]= useState(undefined)

// I want upload later so I just save formData to state
   state.logoFormData = formData;
  setLogoForm(formData)
  
  // call api service
  - run api upload ==> runUpload(state.logoFormData) not working it become object like picture 1
  - run api upload ==> runUpload(logoForm)  working see picture 2
```

# picture1 useReactive
![Screen Shot 2021-07-11 at 2 19 01 PM](https://user-images.githubusercontent.com/51617383/125186351-2e7ce780-e254-11eb-9c45-45ad0c218e1b.png)

# picture 2 useState
![Screen Shot 2021-07-11 at 2 22 00 PM](https://user-images.githubusercontent.com/51617383/125186373-4ce2e300-e254-11eb-9692-5094fa6c9532.png)

**Comment by liuyib** [comment]
被这个 [PR](https://github.com/alibaba/hooks/pull/2079) 一并修复了，都是同一类问题。验证地址：https://codesandbox.io/s/ahooks-issue-1024-lcfctl?file=/App.tsx
