### ISSUE TITLE
useAntdTable 不支持动态更改 pageSize

### ISSUE THREAD

**Issue by PeterChen1997** [alibaba/hooks#1034]
希望支持下面的功能

```js

const { tableProps, search } = useAntdTable(getTableData, {
        defaultPageSize: defaultPageSize,
        // pageSize: pageSize
        form,
        refreshDeps: [staffData, pageSize],
    });

```

**Comment by brickspert** [comment]
其实是支持的，你可以使用 tableProps.onChange 来修改 pageSize~~

并且你给的示例代码，目前是有什么问题么？ 

refreshDeps 里面的数据，只是通知重新刷新，并不会使用到里面的参数的~

**Comment by PeterChen1997** [comment]
> 其实是支持的，你可以使用 tableProps.onChange 来修改 pageSize~~
> 
> 并且你给的示例代码，目前是有什么问题么？
> 
> refreshDeps 里面的数据，只是通知重新刷新，并不会使用到里面的参数的~

哦哦好的哇，感谢，那应该没问题啦~

**Comment by a798032825** [comment]
> 其实是支持的，你可以使用 tableProps.onChange 来修改 pageSize~~
> 
> 并且你给的示例代码，目前是有什么问题么？
> 
> refreshDeps 里面的数据，只是通知重新刷新，并不会使用到里面的参数的~

通知重新刷新是指，没理解到

**Comment by kkxiaojun** [comment]
> > 其实是支持的，你可以使用 tableProps.onChange 来修改 pageSize~~
> > 并且你给的示例代码，目前是有什么问题么？
> > refreshDeps 里面的数据，只是通知重新刷新，并不会使用到里面的参数的~
> 
> 哦哦好的哇，感谢，那应该没问题啦~

没理解到，具体是怎么实现呢
