### ISSUE TITLE
pagination显示总条数

### ISSUE THREAD

**Issue by astudentat** [alibaba/hooks#1036]
请问怎么配置分页显示总条数呢？如下设置会导致切换分页时 total也会改变
const listReq = useRequest(
    async (p, query = {} as GetEdiInterfaceQueryModel) => {
      const {
        result: { records, total },
      } = await api.getEdiInterfacePage({
        current: p.current,
        size: p.pageSize,
        model: query,
      })
      return { list: records, total }
    },
    {
      paginated: true,
      defaultPageSize: DefaultPageSize,
      manual: DefaultManual,
    }
  )
  listReq.tableProps = {
    ...listReq.tableProps,
    ...{
      pagination: {
        showTotal: (total) => {
          console.log('total',total)
          return `${t('共')} ${total} ${t('条')}`
        },
      },
    },
  }

**Comment by brickspert** [comment]
为啥切换分页 total 会变化呢？

是不是自己的接口数据有问题啥的？可以提供个示例么？
