### ISSUE TITLE
[Question] Why is `useCallback` used in the `useLockFn` hook

### ISSUE THREAD

**Issue by YuanRuQian** [alibaba/hooks#1038]
My question: why is `useCallback` used in the `useLockFn` hook?

I understand that `useCallback` returns the same function here, but why we need the same function? 

I removed the `useCallback` part in this demo: https://codepen.io/yuanruqian/pen/eYWgVpM

And it still works fine as a duplicate requests guard.

`useLockFn`: https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useLockFn/index.ts
```typescript
function useLockFn<P extends any[] = any[], V extends any = any>(fn: (...args: P) => Promise<V>) {
  const lockRef = useRef(false);

  return useCallback(
    async (...args: P) => {
      if (lockRef.current) return;
      lockRef.current = true;
      try {
        const ret = await fn(...args);
        lockRef.current = false;
        return ret;
      } catch (e) {
        lockRef.current = false;
        throw e;
      }
    },
    [fn],
  );
}
```
I  guess there must be some scenarios I haven't thought about, so could anyone give me some hints? Thanks!

**Comment by awmleer** [comment]
This is mainly for performance concern. For example:

```jsx
const Foo = memo(props => {...})

const Bar = () => {
  const fetchData = useCallback(() => {...}, [])
  const lockedFetchData = useLockFn(fetchData)
  return (
    <Foo fetchData={lockedFetchData} />
  )
}
```

With `useCallback`, we can guarantee the behavior of `lockedFetchedData` and `fetchData` are exactly same. If the reference of `fetchData` does not change, `lockedFetchData` stays the same, and vise versa.

**Comment by YuanRuQian** [comment]
Ah... now I get it 👌 Thank you!

( I made two more demos for anyone who is as confused as I was )

[UseLockFn  with useCallback prevent unnecessary re-rendering](https://codepen.io/yuanruqian/pen/yLbgqEm)

Press the "trigger bar re-rendering" button to update the state, which causes the <Bar /> to re-render

Because the `memo` + `useCallback` combo, the <Foo /> will not re-render

![Screen Shot 2021-07-14 at 18 56 07 (2)](https://user-images.githubusercontent.com/32387159/125611142-462c6682-6638-47d9-8d1a-5d8bba44f00f.png)

[UseLockFn  without useCallback cause unnecessary re-rendering](https://codepen.io/yuanruqian/pen/rNmjreX)

Press the "trigger bar re-rendering" button to update the state, which causes the <Bar /> to re-render

Because the `lockedFetchData` is a newly created function (because I removed the `useCallback`), the <Foo /> will also re-render

![Screen Shot 2021-07-14 at 19 00 55 (2)](https://user-images.githubusercontent.com/32387159/125611649-0ae6229b-3e6d-4605-8cdd-061dc912d175.png)

---

I think this also reminds me that the best practices for this hook are:

- a `useCallback` memoized function as the param of the `useLockFn` so the inside `useCallback` always depends on the same deps array thus return the same function
- a `memo` wrapped component with the returned locked function as a prop
