### ISSUE TITLE
设置 refreshDeps 的时候 throttleInterval 无效？

### ISSUE THREAD

**Issue by sanheng** [alibaba/hooks#1059]
代码示例如下：

```js
const { data: tagList = [] } = useRequest(queryList, {
  throttleInterval: 1000,
  refreshDeps: [params],
})
```

看着好像 refreshDeps 和节流、防抖是分开的？

https://github.com/alibaba/hooks/blob/96da2164ae90f886cf02aa24b755e47fc35b81fd/packages/use-request/src/useAsync.ts#L456-L464

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
