### ISSUE TITLE
我希望能自定返回结果集

### ISSUE THREAD

**Issue by lovesL** [alibaba/hooks#1071]
![image](https://user-images.githubusercontent.com/27960630/127279770-6714989f-f8d2-49cb-95ae-3acc4a6dd944.png)
我按照文档这样配置  似乎不管用 我不希望默认取data 我想要完整的结果集 

我的 版本"ahooks": "^2.10.5",

**Comment by brickspert** [comment]
`import { UseRequestProvider } from 'umi'` 

这样试试

因为你的 useRequest 肯定是从 umi 中导出的。

**Comment by lovesL** [comment]
> `import { UseRequestProvider } from 'umi'`
> 
> 这样试试
> 
> 因为你的 useRequest 肯定是从 umi 中导出的。

哎呀 真是umi坑了我一把 我发现 我把useRequest  UseRequestProvider都从umi导出, UseRequestProvider配置是不起做用的 必须都的从ahooks里面导出  如果用ahooks的 useRequest  不知道umi 的request拦截能否拦截到
