### ISSUE TITLE
useVirualList. re-rendering with scroll

### ISSUE THREAD

**Issue by ilyanikulin** [alibaba/hooks#1072]
Re-rendering of Component with useVirtualList hook. Are you sure that it's right?

it's hard if I use difficult logic for  output list of this hook

https://codesandbox.io/s/dynamic-item-height-forked-c1949

![image](https://user-images.githubusercontent.com/39908280/127280722-4c440bac-5662-4103-afff-82078da28ed1.png)

**Comment by brickspert** [comment]
We must trigger the rerender in order to update the latest list.
