### ISSUE TITLE
【feature】useLockFn add memoize

### ISSUE THREAD

**Issue by cc7gs** [alibaba/hooks#1109]
# demo

when onSubmit as props,I have to do this ：
```
const onSubmit=useMemoizedFn(useLock(fn))
```

# expect
```
const onSumit=useLock(fn)
```

**Comment by brickspert** [comment]
Maybe you should write like this

```ts
const Foo = memo(props => {...})

const Bar = () => {
  const fetchData = useCallback(() => {...}, [])
  const lockedFetchData = useLockFn(fetchData)
  return (
    <Foo fetchData={lockedFetchData} />
  )
}
```

**Comment by cc7gs** [comment]
> Maybe you should write like this
> 
> ```ts
> const Foo = memo(props => {...})
> 
> const Bar = () => {
>   const fetchData = useCallback(() => {...}, [])
>   const lockedFetchData = useLockFn(fetchData)
>   return (
>     <Foo fetchData={lockedFetchData} />
>   )
> }
> ```

but sometimes I have deps,the `fn` will be also updated 
```ts
const fetchData=useCallback(()=>{...},[...]);
```

**Comment by brickspert** [comment]
This is expected behavior.

**Comment by mason-hz** [comment]
把 useLockFn 做成这个样子会有什么问题？

`export function useLockFn<T extends (...args: any[]) => any>(callback: T, deps: DependencyList) {
  const lock = useRef(false);
  return useCallback(async (...args) => {
    if (lock.current) return;
    lock.current = true;
    try {
      const req = await callback(...args);
      lock.current = false;
      return req;
    } catch (e) {
      lock.current = false;
      throw e;
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps);
}`

**Comment by mason-hz** [comment]
useLockFn 做成这样会有什么问题？
````
export function useLockFn<T extends (...args: any[]) => any>(callback: T, deps: DependencyList) {
  const lock = useRef(false);
  return useCallback(async (...args) => {
    if (lock.current) return;
    lock.current = true;
    try {
      const req = await callback(...args);
      lock.current = false;
      return req;
    } catch (e) {
      lock.current = false;
      throw e;
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps);
}
````

**Comment by brickspert** [comment]
> useLockFn 做成这样会有什么问题？
> 
> ```
> export function useLockFn<T extends (...args: any[]) => any>(callback: T, deps: DependencyList) {
>   const lock = useRef(false);
>   return useCallback(async (...args) => {
>     if (lock.current) return;
>     lock.current = true;
>     try {
>       const req = await callback(...args);
>       lock.current = false;
>       return req;
>     } catch (e) {
>       lock.current = false;
>       throw e;
>     }
>     // eslint-disable-next-line react-hooks/exhaustive-deps
>   }, deps);
> }
> ```

没啥问题，就是 API 设计的取舍了~
