### ISSUE TITLE
[feature] May be need useLatest replace useMemoizedFn? 

### ISSUE THREAD

**Issue by cc7gs** [alibaba/hooks#1115]
# What is Expected? 
 #728 
# Need replace hooks list ?

- [ ] useInterval
- [ ] useTimeout
- [ ] useThrottleFn
- [ ] useDebounceFn

# Version
  - ahooks: v3

**Comment by brickspert** [comment]
Doc is here: https://ahooks-next.surge.sh/zh-CN/guide/function

**Comment by gracehui88** [comment]
> Doc is here: https://ahooks-next.surge.sh/zh-CN/guide/function

Url updated to: https://ahooks-next.surge.sh/zh-CN/guide/blog/function
