### ISSUE TITLE
useAntdTable 无法获取 form 的值

### ISSUE THREAD

**Issue by esclipse** [alibaba/hooks#1118]
https://codesandbox.io/s/fu-za-de-dong-tai-zeng-jian-biao-dan-xiang-antd-4-16-12-forked-egf8q?file=/index.js:1132-1138

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/141063427-e543137c-076b-4945-82ef-3dd94ff40bbb.png)

name 改成字符串就可以了。

**Comment by esclipse** [comment]
当 name 是数组获取不到，name 是数组是 antd 新支持的特性
