### ISSUE TITLE
useUpdateEffect can not use with useModel in umi

### ISSUE THREAD

**Issue by ccforeverd** [alibaba/hooks#1120]
```
function Page () {
  const { currentAppId } = useModel('appsInfo')
  const [isEditMode, setIsEditMode] = useState<boolean>(false)

  useEffect(() => {
    console.log('currentAppId useEffect', currentAppId)
  }, [currentAppId])

  useUpdateEffect(() => {
    console.log('currentAppId useUpdateEffect', currentAppId)
    // history.replace('page-list')
  }, [currentAppId])

  useUpdateEffect(() => {
    console.log('isEditMode useUpdateEffect', isEditMode)
  }, [isEditMode])

  // ...
}
```

I want to watch `currentAppId` which comes from the `useModel` but not on monuted. When `currentAppId` changes the `useEffect` worked but the `useUpdateEffect` not. When I change  `isEditMode` the `useUpdateEffect` works.

So is the `useUpdateEffect` can only be used with `state` but not `model`?

**Comment by ccforeverd** [comment]
```
umi^3.5.8
ahooks^2.10.9
```

**Comment by ccforeverd** [comment]
```
react^16.13.1
```

**Comment by brickspert** [comment]
`useUpdateEffect` only work on it's deps change. 

You have two `useUpdateEffect`, they are only related to their own deps.

**Comment by ccforeverd** [comment]
@brickspert You're right. I deleted all my node_modules and reinstall packages and then it works. It's my fault, thank you so much!
