### ISSUE TITLE
为什么要再次给fnRef赋值❓

### ISSUE THREAD

**Issue by Ezreal09** [alibaba/hooks#1121]
![1629880586937_C03A5656-BDF0-4230-9224-35EFE327890B](https://user-images.githubusercontent.com/44263381/130758583-640a530b-a785-415c-912a-9a10e5e49ff9.png)
为什么要给fnRef重新赋值，看见很多hook里面都有这种写法😊😊😊

**Comment by brickspert** [comment]
这个目的是为了解决闭包问题。 后面我写一篇文章来解释下~~

**Comment by Liuhuan247** [comment]
之前我也问了尽龙大佬这个问题，大佬没回复。我的理解是这样的
1. 当外层FC重新执行后，调用usePerisitFn，传如了一个新的fn，而useRef在initial后不会再去赋初值，为了更新fnRef的引用，再赋值一次fn
2. 为了外层FC组件中的子组件因不同的props导致重新render，所以用persistFn保留一直的引用，内部捕获的fnRef依旧是新的fn

**Comment by Ezreal09** [comment]
> 之前我也问了尽龙大佬这个问题，大佬没回复。我的理解是这样的
> 
> 1. 当外层FC重执行后，调用usePerisitFn，如传了一个新的fn，而useRef在initial后不会再去赋初值，为了更新fnRef的引用，再赋一次fn
> 2. 为了外层FC组件的子组件因不同的道具导致变重，所以用坚持F中n保留一直的引用，内心精神的fnRef仍然是新的fn

你的理解对这个usePersistFn好像能解释的通，但是其他hook里也有这种情况。坐等砖家老师解释

**Comment by thomas-void0** [comment]
插个眼

**Comment by Camusama** [comment]
就是FC 每次更新新tick，传进来的Fn 也是新的，当然要重新赋值啊，其实官方文档有一处专门解释了，useRef就是给FC开的口子
https://zh-hans.reactjs.org/docs/hooks-faq.html#how-to-read-an-often-changing-value-from-usecallback

**Comment by brickspert** [comment]
文档在这里：https://ahooks-next.surge.sh/zh-CN/guide/function

**Comment by omitchen** [comment]
文章打不开？

> 文档在这里：https://ahooks-next.surge.sh/zh-CN/guide/function

**Comment by brickspert** [comment]
> 文章打不开？
> 
> > 文档在这里：https://ahooks-next.surge.sh/zh-CN/guide/function

换了个链接：https://ahooks-next.surge.sh/zh-CN/guide/blog/function
