### ISSUE TITLE
useToggle 的文本动态修改后，state 没有同步

### ISSUE THREAD

**Issue by bigmgreen** [alibaba/hooks#1123]
https://codesandbox.io/s/ji-chu-yong-fa-forked-fyx2d?file=/App.tsx

```js
  const [name, setName] = useState("---");
  const [state, { toggle }] = useToggle(name, "2");

  useEffect(() => {
    setName("+++");
  }, []);
```

期望 state 显示 +++
结果 state 还是显示 ---

**Comment by brickspert** [comment]
目前不支持动态变换值。

下个大版本考虑支持。

**Comment by binvb** [comment]
官方不建议用衍生state的方式，这个是官方post: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html
