### ISSUE TITLE
提议`useFullscreen`增加第三个返回值，返回`screenfull.isEnabled`

### ISSUE THREAD

**Issue by IronKinoko** [alibaba/hooks#1124]
`useFullscreen` 虽然内部是用了 `screenfull.isEnabled` 做校验了，但一般使用这个hook的时候还是得在外部判断下是否能够全屏，并按结果渲染按钮，所以建议第三个参数把里面`screenfull.isEnabled`转发出来

**Comment by woow-wu7** [comment]
挺有道理的哦，应该直接把整个 `screenfull对象` 暴露出来.
为什么是第三个参数，而不是第二个对象呢？

**Comment by IronKinoko** [comment]
对，在第二个参数加 `isEnabled` 似乎是更好的选择
另外这个hook已经对 进入/退出全屏 做额外的处理了，暴露 `screenfull` 对象本身感觉有点多余了，转发个 `isEnabled` 应该就够了吧

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
