### ISSUE TITLE
并行请求造成组件刷新问题useRequest

### ISSUE THREAD

**Issue by webtianjia** [alibaba/hooks#1127]
queryGroupList.run().then((ret) => {
            Promise.all(ret.map(item => {
                return queryGroupMembers.run(item.gid).then(members => {
                    item.members = members
                })
            }))
        })
        请问我有一份接口,必须这样才能拿到完整数据, 但并行请求赋值会使组件持续多次更新, 请问有优化方案吗,多谢拉

**Comment by brickspert** [comment]
你这样的写法应该组件不会持续更新的吧？

**Comment by webtianjia** [comment]
@brickspert  目前我console会持续更新queryGroupMembers 30次会更新30次,感觉会出现性能问题

**Comment by brickspert** [comment]
> @brickspert 目前我console会持续更新queryGroupMembers 30次会更新30次,感觉会出现性能问题

贴个代码看看~~

**Comment by webtianjia** [comment]
在同一个函数组件使用了,促使组件多次渲染,目前我们SKD只能这样,问题关闭了
