### ISSUE TITLE
发布的包里useAsync的es module的文件不完整

### ISSUE THREAD

**Issue by wenjoy** [alibaba/hooks#1131]
```json
 "name": "@ahooksjs/use-request",
  "version": "2.8.10",
  "description": "React Hooks for fetching, caching and updating asynchronous data",
  "main": "./lib/index.js",
  "module": "./es/index.js",
  ...
```

文件node_modules/@ahooksjs/use-request/es/useAsync.js在303行被截断了：

```js
...
297   return Fetch;
298 }();
299
300 function useAsync(service, options) {
301   var _options = options || {};
302
303   var _a = _options.refresh
```

taobao源和官方源都是这样

**Comment by brickspert** [comment]
测试没有问题~~

![image](https://user-images.githubusercontent.com/12526493/132433018-cc6e755a-38e4-4df3-83ca-01e142767585.png)
![image](https://user-images.githubusercontent.com/12526493/132433032-2efb29f2-9de7-4f29-9b9e-549e3b4a3f85.png)

**Comment by wenjoy** [comment]
是我本地的缓冲的包有问题，后来每次都用了这个缓冲。抱歉，误报了 😅
