### ISSUE TITLE
The example in the official document, run to get the data in fetches is always undefined

### ISSUE THREAD

**Issue by JayMo666** [alibaba/hooks#1133]
English：
The example in the official document (https://ahooks.js.org/hooks/async/#concurrent-request), run to get the data in fetches is always undefined;
I need to get the data in fetches[key]。

中文：
官方文档(https://ahooks.js.org/hooks/async/#concurrent-request)的例子，运行得到fetches 里面的data 永远为undefined。我需要得到fetches[key]里data

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/133079716-2bec055c-6155-4a25-8f82-0e1ff8af8897.png)



https://codesandbox.io/s/refreshonwindowfocus-forked-v3tqu?file=/App.tsx


测试是有 data 的。

**Comment by AlexHodovas** [comment]
@brickspert 
Hello, could you help please, 
the issue that was mentioned on the top, 
still reproduced.
(the value "fetches" is always undefined)
