### ISSUE TITLE
useKeyPress thow an error that the dom isn't mount

### ISSUE THREAD

**Issue by it950** [alibaba/hooks#1134]
Use a function as a target of option of useKeyPress, the function as follow:
``` javascript
document.getElementById('targetId')
```
Because the target dom mount by some condition, for example: 
1. a config object which was loaded from an api by send a http request to the server when the component mount, 

The source code of useKeyPress as follow,  can take a check for the `el`?
``` javascript
for (const eventName of events) {
      el.addEventListener(eventName, callbackHandler);
}
```

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
