### ISSUE TITLE
useTable 无法获取经过封装的表单的值

### ISSUE THREAD

**Issue by iceberg211** [alibaba/hooks#115]
版本: 1.3.1, 1.2.0.

```
 <Form className="simpleForm" onSubmit={submit}>
      <Row gutter={24}>
        <Col span={6}>
          <Form.Item label="角色">
            {getFieldDecorator('role_id')(<RoleSelect placeholder="选择角色" />)}
          </Form.Item>
        </Col>
        <Col span={6}>
          <Button type="primary" htmlType="submit" >
            搜索
          </Button>
        </Col>
      </Row>
```
此下拉组件是经过简单封装，但是提交的时候不能获取到此组件数据。

**Comment by ttys026** [comment]
![image](https://user-images.githubusercontent.com/19804057/67853021-8b9c3c80-fb48-11e9-9f91-e06bc1b053f1.png)
这个属于 antd form 组件使上的问题，参考[这个例子](https://ant.design/components/form-cn/#components-form-demo-customized-form-controls), 可以使用 getFieldDecorator 绑定自己封装过的组件

**Comment by brickspert** [comment]
RoleSelect 组件需要提供 value 和 onChange 属性，供表单使用的哦。
