### ISSUE TITLE
2.10.10 break CommonJS

### ISSUE THREAD

**Issue by Ty3uK** [alibaba/hooks#1166]
Hi!

Version 2.10.10 contains ESM imports inside CJS folder:

https://unpkg.com/browse/ahooks@2.10.10/lib/useCounter/index.js
https://unpkg.com/browse/ahooks@2.10.9/lib/useCounter/index.js

Those changes break NextJS SSR completely 😕

**Comment by brickspert** [comment]
I have revert v2.10.10~~

v2.10.9 is work ok~

**Comment by Ty3uK** [comment]
> I have revert v2.10.10~~
> 
> v2.10.9 is work ok~

Yeah, I did the same thing, but still...

**Comment by gurkerl83** [comment]
Hi, reverting back requires a bit more than just decreasing the version number from 2.10.10 > 2.10.9. The reason is the following. You can do it but you have to restrict @ahooksjs/use-request to the previous version which is 2.8.10.

```
With the release of ahooks version 2.10.10 the build seems broken. It seems a conflict got introduced with core/js used in the use-request package, an internal module used in ahooks.
Pinning ahooks to version 2.10.9 does not resolve the problem; this is due to a new version of use-request with a minor version increase was also published. A workaround is to pin also the version number of use-request to the previous version, which is 2.8.10.
```

see https://github.com/project-millipede/millipede-docs/commit/35858f69c431e2978b915cc18b21142aa94aee39

with Yarn
```
"resolutions": {
    "ahooks": "2.10.9",
    "@ahooksjs/use-request": "2.8.10" // !!!this line is not required anymore!!!
},
```

with NPM
```
"dependencies": {
    "ahooks": "2.10.9"
}
```

Thx!

**Comment by brickspert** [comment]
I have already revert ahooks, @ahooksjs/use-request, @ahooksjs/use-url-state.

Maybe you don't need to lock the version. 

I tested it and there is no problem

![image](https://user-images.githubusercontent.com/12526493/134170836-2e7faac9-afe0-41e7-8d05-23cb363d07ae.png)

**Comment by gurkerl83** [comment]
@brickspert ~~When you remove node_modules folder entirely or remove yarn.lock then you have to pin both versions. I tried pinning just ahooks in the first place, but the result was use-request with version 2.8.11 (10 -> 11 minor version, fetches a newer version anyway) was loaded. I use Yarn 3.0.2, maybe the resolution strategy is different on Yarn 1 / 2 or NPM but my guess it is the same.~~

Seems you are right, pining to just 2.10.9 solves the problem, maybe I saw the use-request version 2.8.11 after the udate earlier today and got something mixed up.

@brickspert Did you delete use-request version 2.8.11 from NPM, so the explanation above is in theory reasonable.

**Comment by brickspert** [comment]
> @brickspert ~When you remove node_modules folder entirely or remove yarn.lock then you have to pin both versions. I tried pinning just ahooks in the first place, but the result was use-request with version 2.8.11 (10 -> 11 minor version, fetches a newer version anyway) was loaded. I use Yarn 3.0.2, maybe the resolution strategy is different on Yarn 1 / 2 or NPM but my guess it is the same.~
> 
> Seems you are right, pining to just 2.10.9 solves the problem, maybe I saw the use-request version 2.8.11 after the udate earlier today and got something mixed up.
> 
> @brickspert Did you delete use-request version 2.8.11 from NPM, so the explanation above is in theory reasonable.

You are right.

Thank you for your feedback~ ღ( ´･ᴗ･` )
