### ISSUE TITLE
dnd 组件内有其他标签时，hovering效果不好使

### ISSUE THREAD

**Issue by yan-labs** [alibaba/hooks#1168]
demo
https://codesandbox.io/s/ji-chu-yong-fa-forked-gzh65

hover在文字上的时候，没有出现border

**Comment by xiaohuoni** [comment]
@KanChaiShaoXia 你提供的 demo 不可用

**Comment by yan-labs** [comment]
> @KanChaiShaoXia 你提供的 demo 不可用

https://codesandbox.io/s/ji-chu-yong-fa-forked-13ip2?file=/App.tsx

> line62 加一层div，isHovering就不好使了

**Comment by brickspert** [comment]
@hxp1021

**Comment by brickspert** [comment]
fixed on ahooks@3.0.0-alpha.13
