### ISSUE TITLE
[QUESTION]如何正确使用useRequest的mutate/如何正确修改或情况useRequest的值

### ISSUE THREAD

**Issue by xmsz** [alibaba/hooks#1169]
背景
- 一个useRequest
- run过一次
- 然后我想修改data的值/清空值/初始化值
- 我使用了mutate，但是提示
```
You should't call mutate when service not executed once.
```
并且值并没有被修改

需求
- mutate正确使用方式？
- 是否有类似reset的方法，将值直接还原成默认值

**Comment by brickspert** [comment]
如果已经 run 过，mutate 是不会有警告的。

参考示例：https://codesandbox.io/s/tu-bian-forked-eyrx0?file=/App.tsx:340-344

可以提供一个错误示例代码？

**Comment by xmsz** [comment]
ok 我整理一下代码

先贴一下伪代码
```
  const {
    data: adData,
    run: loadAd,
    mutate: mutateAd,
  } = useRequest(services.order.getAdList, {
    manual: true,
    onSuccess: () => {
      console.log('加载过一次');
    },
  });


// other method
mutateAd({ page: 0, pageSize: 10, list: [], total: 0, last: true });
```
![image](https://user-images.githubusercontent.com/5879146/134447030-8e5892c2-df66-4b1f-b218-94a076eaa6b3.png)

**Comment by xmsz** [comment]
我大概知道什么情况了
```
  const field = Field.useField({
    onChange: (name, value) => {
      switch (name) {
        case 'platformId':

          mutateAd({ page: 0, pageSize: 10, list: [], total: 0, last: true });

          break;

        default:
          break;
      }
    },
  });

```

我在useField.onChange这里执行，但是这个mutate方法在这里是旧的值
如果我在其他地方执行就没问题

我现在将mutate方法移到这段之前执行就可以了

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
