### ISSUE TITLE
useLocalStorageState参数错误时，导致页面js无限加载卡死

### ISSUE THREAD

**Issue by derek2035** [alibaba/hooks#1170]
使用useLocalStorageState时，当不小心忘写参数key时，比如useLocalStorageState('')，会导致刷新页面后，network中看到页面的js文件无限重复加载。我实际遇到的，离开电脑半小时回来，页面已经加载30多G，还在继续加载。

希望参数不规范时，做一下判断，给出错误提示。这种情况排查问题也不容易。

**Comment by xiaohuoni** [comment]
localStorage 的 key 是支持 `''` 的，没有重现你说的这个问题
