### ISSUE TITLE
不支持按需引入

### ISSUE THREAD

**Issue by 94cstyles** [alibaba/hooks#1172]
RT

`babel-plugin-import` or  `vite-plugin-imp`

问题原因是 **useRequest** 不在 `ahooks/es` 下，能否处理下？

**Comment by brickspert** [comment]
默认是会按需引入的，其实不需要 babel-plugin-import 的

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
