### ISSUE TITLE
useAntdTable不支持refreshOnWindowFocus的吗？

### ISSUE THREAD

**Issue by su1924** [alibaba/hooks#1238]
我怎么记得原来是可以的，不知道什么时候设置refreshOnWindowFocus不起作用了

**Comment by brickspert** [comment]
目前 useAntdTable 确实不支持 refreshOnWindowFocus，需要修复一下。

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
