### ISSUE TITLE
useRequest 的 option 直接写 defaultParams 报错

### ISSUE THREAD

**Issue by suedar** [alibaba/hooks#1239]
### 版本
"@umijs/hooks": "^1.9.3"
### 问题描述

![image](https://user-images.githubusercontent.com/18492953/134801267-9b2deb35-c6af-46b1-bd75-20976ac62a44.png)

``` js
const { data: notificationList, error: notificationListError, loading: notificationListLoading} = useRequest(getNotificationList, {
  manual: false,
  defaultParams: {
    pageno: 1,
    count: 8,
  },
  // onError: (a) => {
  //   console.log(a, '123');
  // }
});
```

### 在线 DEMO
https://codesandbox.io/s/pensive-goldstine-iwec3?file=/src/App.js

**Comment by suedar** [comment]
这似乎是一个逻辑问题
manual 改为 true 就可以

**Comment by brickspert** [comment]
defaultParams 需要是一个数组
