### ISSUE TITLE
useRequest 缓存机制问题

### ISSUE THREAD

**Issue by zzzgydi** [alibaba/hooks#1242]
```typescript
const PageA = () => {
  const { data, error } = useRequest(fetcher, {
    cacheKey: 'keyA',
  });

  if (error) return <Redirect to="/login" />;

  return <div>{data}</div>;
}

const LoginPage = () => {
  const onLogin = () => {
    // do something
    history.replace('/page-a');
  };

  return <Button onClick={onLogin}>登录</Button>;
}
```

假如有如上的需求，就会存在一个问题。我先访问PageA页面，发现没有登录，重定向到登录页，在登录页登录完成后跳转回原页面，而由于缓存时间可能没过，还是返回上一次的错误，导致再次重定向页面。

我目前的做法是：

```typescript
let errorCount = 0;

const PageA = () => {
  const { data, error } = useRequest(fetcher, {
    cacheKey: 'keyA' + errorCount,
  });

  if (error) {
    errorCount++;
    return <Redirect to="/login" />;
  }

  return <div>{data}</div>;
}
```

我想请问一下，目前useRequest是否有一些设置可以支持处理这个问题。

**Comment by brickspert** [comment]
这个我们处理下，如果 error 的话，就不缓存了。

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
