### ISSUE TITLE
useEffect依赖问题

### ISSUE THREAD

**Issue by strongyc** [alibaba/hooks#1249]
ts hooks中，useEffect提示缺乏依赖项，是否需要将useRequest加入useCallback包裹后加入useEffect依赖？
![image](https://user-images.githubusercontent.com/51156342/136490293-829fb1f9-59e1-4db5-8d09-30945e4372ef.png)
![image](https://user-images.githubusercontent.com/51156342/136490308-88e05077-1cb1-4c4b-8dd5-ddb04880c231.png)

**Comment by brickspert** [comment]
不需要的

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
