### ISSUE TITLE
useClickAway 错误的触发了

### ISSUE THREAD

**Issue by awmleer** [alibaba/hooks#1250]
来自社区同学的反馈：

> useClickAway 因为内部使用 element.contains 判定，所以，如果容器内的某元素 click 后会导致该元素销毁，也会触发 click away。em... 目前只能通过 stopImmediatePropagation 解决
> https://codesandbox.io/s/recursing-lamarr-w0ib8?file=/src/App.js

**Comment by thomas-void0** [comment]
useClickAway 这个名字我觉得取得不是很恰当，因为这个钩子既然可以通过传入eventName的方式指定事件类型。那么单单以click来进行命名的话可能不是很好。

**Comment by awmleer** [comment]
useEventOutside?

**Comment by brickspert** [comment]
建议给消失的元素上加个 stoppropagation 来解决这个问题。

https://github.com/alibaba/hooks/pull/1252#issuecomment-939724656

**Comment by Enivia** [comment]
不能用 useLayoutEffect 解决嘛

**Comment by 14glwu** [comment]
> 建议给消失的元素上加个 stoppropagation 来解决这个问题。
> 
> [#1252 (comment)](https://github.com/alibaba/hooks/pull/1252#issuecomment-939724656)

同样遇到这个问题，感觉能否补充在文档呢？
