### ISSUE TITLE
const a = useRef(new Subject()) // 每次重渲染，都会执行实例化 Subject 的过程，即便这个实例立刻就被扔掉了

### ISSUE THREAD

**Issue by XdyGoGo** [alibaba/hooks#1255]
貌似并不会

**Comment by XdyGoGo** [comment]
import React, { useState, useRef } from 'react';
import { Button } from 'antd';

type UseCreationProps = {};

class Counter {
  data: number;
  constructor() {
    this.data = Math.random();
  }
}

const UseCreation: React.FC<UseCreationProps> = (props) => {
  const counter = useRef(new Counter());
  const [, update] = useState({});

  return (
    <>
      <p>{counter.current.data}</p>
      <Button onClick={() => update({})}>Re-Render</Button>
    </>
  );
};

export default UseCreation;

**Comment by wangjs-jacky** [comment]
> 貌似并不会

我估计他们是想说 new Counter 这一句会执行，也就是 Counter 里头的constructor 会被执行，但是这种计算即使执行了，也不会赋值到 current，所以你写的案例永远不变。而用了 useCreation 可以节省这部分计算，感觉有点像 useMemo 和 useRef 的结合体。useMemo 将new Counter 的结果缓存，然后交给 ref 去缓存结果。
