### ISSUE TITLE
useAntdTable with mobx query repeated

### ISSUE THREAD

**Issue by Nicklzy** [alibaba/hooks#1257]
[Recurring address](https://codesandbox.io/s/ji-ben-antd-4-17-0-alpha-5-forked-ywff4?file=/content.js)
When I click the tab2,I expect it will query everytime. But I found a bug. When I clicked Tab2 and then back to Tab1 , and then click the tab2, it will query twice. The bug only shows when second time click the tab2.

The current requirement is to send a request every time you click on tab2. The switching of tabs is handled by mobx, so I use
```
    {
      refreshDeps: [store.tabKey],
      ready: store.tabKey === "2"
    }
```
to implement the demand, then I found this bug

-------------
 [复现地址](https://codesandbox.io/s/ji-ben-antd-4-17-0-alpha-5-forked-ywff4?file=/content.js)
预期是每次点击tab2的时候，都会发送一次请求。但是发现一个问题，当第一次点击tab2 之后，返回tab1，再次点击tab2，页面会请求两次。这个bug只在第二次点击tab2的时候会出现这个问题。
目前的需求是希望点击tab2的每次都发送请求。tabs的切换是用mobx处理的，所以我用
```
    {
      refreshDeps: [store.tabKey],
      ready: store.tabKey === "2"
    }
```
来实现这个需求，然后出现了这个问题。

**Comment by brickspert** [comment]
目前 `ready` 只会生效一次，也就是后面 `ready` 就不生效了。你可以先不要使用 ready。

下个大版本会修复。

**Comment by brickspert** [comment]
related: https://github.com/alibaba/hooks/discussions/1291

可以来这里讨论 ready 的行为。
