### ISSUE TITLE
useHistoryTravel 在setValue时可能会出现错误

### ISSUE THREAD

**Issue by dumeng-chn** [alibaba/hooks#1258]
**使用代码**
![use1](https://user-images.githubusercontent.com/29587964/138016814-08379937-9714-4247-b74c-39a6efadcefb.png)
![use2](https://user-images.githubusercontent.com/29587964/138016833-4acc66e9-cfed-4cb1-840b-166ffda9baf2.png)

**效果图 修改之前始终只会存储一次记录**
![before](https://user-images.githubusercontent.com/29587964/138017726-20790393-aa87-4325-924e-1a8ea7df1013.gif)
**效果图 修改之后正常**
![after](https://user-images.githubusercontent.com/29587964/138017730-a73a41c9-8e93-4e4a-b9ac-56a4cc8a684b.gif)
**修改useHistoryTravel代码**
![code](https://user-images.githubusercontent.com/29587964/138017023-419a579a-c395-4e3b-8408-3798b76e0558.png)

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/138834833-3a8368d4-9102-4bc0-947c-d08d6053f011.png)

deps 似乎少了一个？

**Comment by dumeng-chn** [comment]
@brickspert 我我这里测试更新deps仍然无效

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
