### ISSUE TITLE
useCreation 对依赖的比较或许应该使用Object.is？

### ISSUE THREAD

**Issue by yuivan** [alibaba/hooks#1271]
在源码中对于hooks依赖项的比较都是使用的Object.is,useCreation作为useMemo的替代品，是否也应该使用Object.is进行比较呢？

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
