### ISSUE TITLE
[QUESTION]如何正确监听useTable的分页

### ISSUE THREAD

**Issue by yiescc** [alibaba/hooks#1273]
背景
```
  const {
    paginationProps,
  } = useFusionTable();
```
- 我现在想在table的分页改变时做一些处理
然后我用这样
```
useEffect(()=>{
 // TODO 
},[paginationProps.current])
```
但是IDE提示我监听这个没有用，需要监听paginationProps
然后确实没有用

需求
- 如何监听这个currrent

**Comment by brickspert** [comment]
```ts
useEffect(()=>{
 // TODO 
},[paginationProps.current])
```

就是应该这样写的~~

**Comment by topwood** [comment]
如何在监听current之后取消查询，例如我的分页接口只支持50页，如果用户在分页器那边选择了51页，希望直接提示并且不进行接口查询

**Comment by liuyib** [comment]
> 如何在监听current之后取消查询，例如我的分页接口只支持50页，如果用户在分页器那边选择了51页，希望直接提示并且不进行接口查询

调用 `cancel` 方法:

![image](https://user-images.githubusercontent.com/38221479/224613651-c9872423-266a-4ebb-98ba-d2c9782b3afa.png)

如果还是解决不了你的问题，请新开 issue，在已关闭的 issue 下评论可能没人回应
