### ISSUE TITLE
useRequest的refreshOnWindowFocus是否有办法在创建之后再次手动开启和关闭

### ISSUE THREAD

**Issue by diklios5768** [alibaba/hooks#1274]
如果一个页面上有两种HTTP请求都在修改一个数据，是否可以让其中一个请求的refreshOnWindowFocus 手动关闭和手动开启

**Comment by brickspert** [comment]
是指同一个 useRequest 吗？

下个大版本会支持这个能力，当前版本没有这个能力。

**Comment by diklios5768** [comment]
> 是指同一个 useRequest 吗？
> 
> 下个大版本会支持这个能力，当前版本没有这个能力。

是的，感谢。那同样的，轮询功能是不是也不能支持手动开启和关闭。

**Comment by brickspert** [comment]
> > 是指同一个 useRequest 吗？
> > 下个大版本会支持这个能力，当前版本没有这个能力。
> 
> 是的，感谢。那同样的，轮询功能是不是也不能支持手动开启和关闭。

是支持的，run 和 cancel

**Comment by diklios5768** [comment]
> > > 是指同一个 useRequest 吗？
> > > 下个大版本会支持这个能力，当前版本没有这个能力。
> > 
> > 
> > 是的，感谢。那同样的，轮询功能是不是也不能支持手动开启和关闭。
> 
> 是支持的，run 和 cancel

好的，谢谢

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
