### ISSUE TITLE
【useRequest问题】refreshDeps 变更后，service 的 args 还是之前的旧数据

### ISSUE THREAD

**Issue by woohs** [alibaba/hooks#1277]
### 背景

 service 以` (...args) => promise` 的形式使用，并且添加 refreshDeps 选项使用；此时手动 run 并传参，后续的 refreshDeps 触发请求都会带上之前手动 run 的参数。

个人感觉在实际业务中会有这种使用场景，不同的触发方式带的参数不会互相影响

### 期望
refreshDeps 触发的请求不会带上之前手动触发的 args 参数

### 代码演示
https://codesandbox.io/s/shou-dong-chu-fa-forked-pp884?file=/App.tsx

![image](https://user-images.githubusercontent.com/31387031/140902666-1c549e1b-051f-48d5-9af5-79061c4b527d.png)

**Comment by woohs** [comment]
查看源码，初步分析是由于调用了 `refresh` 函数，而 `refresh` 函数会使用上一次的 `params` ，也许当初设计者就是想 `refreshDeps` 这么运行的？那可能需要在文档上作下提示

> ![image](https://user-images.githubusercontent.com/31387031/141032915-f4c8624b-e46e-4dbc-b65d-abfef0ff39af.png)
![image](https://user-images.githubusercontent.com/31387031/141032842-329c7145-f70b-48ba-9d7a-f378c5dcd241.png)

**Comment by brickspert** [comment]
> 查看源码，初步分析是由于调用了 `refresh` 函数，而 `refresh` 函数会使用上一次的 `params` ，也许当初设计者就是想 `refreshDeps` 这么运行的？那可能需要在文档上作下提示
> 
> > ![image](https://user-images.githubusercontent.com/31387031/141032915-f4c8624b-e46e-4dbc-b65d-abfef0ff39af.png)
> > ![image](https://user-images.githubusercontent.com/31387031/141032842-329c7145-f70b-48ba-9d7a-f378c5dcd241.png)

设计的方案就是 refresh，这个需要在文档上说明下~~
