### ISSUE TITLE
v3 版本: 构建产物 lib/xxx.js 没有编译到 es5, 还存在 import polyfill 语法

### ISSUE THREAD

**Issue by AnaniZhu** [alibaba/hooks#1280]
版本: v3.0.0-alpha.3

下图为 `lib/useAntdTable/index.js`

![image](https://user-images.githubusercontent.com/26708304/141254490-54952092-7e99-4f12-b070-e1e6d77eda8b.png)

**Comment by brickspert** [comment]
暂时修复了~
