### ISSUE TITLE
v3 useAntdTable refreshDeps 选项不生效

### ISSUE THREAD

**Issue by suiyun39** [alibaba/hooks#1305]
虽然在内部, 把 refreshDeps 传给了 usePagination, 但是因为内部 usePagination 的 `manual: true` 导致了参数变化时不会重新请求.
目前只能在参数变化后手动调用一次 refresh 来执行新的请求.

**Comment by brickspert** [comment]
Thank you for your feedback, we have fixed this on ahooks@v3.0.0-alpha.8
