### ISSUE TITLE
[RFC] useGetState: 在普通 useState 返回值中增加 getter 方法穿透闭包获取最新值

### ISSUE THREAD

**Issue by CJY0208** [alibaba/hooks#1306]
React hooks 中存在闭包问题，业务中通常配合额外 useRef 来穿透闭包获取最新值，如下：

```jsx
function Test() {
  const [count, setCount] = useState(0)
  const countRef = useRef(count)
  countRef.current = count

  useEffect(() => {
    setInterval(() => {
      console.log(countRef.current) // 使用 ref 穿透闭包
    }, 1000)
  }, [])

  return (
    <button onClick={() => setCount(count => count + 1)}>
      count: {count}
    </button>
  )
}
```

目前凡有此需求均需额外配合一个 useRef 解决

可考虑将 useRef 封装在内，如下

```jsx
function Test() {
  const [count, setCount, getCount] = useGetState(0)

  useEffect(() => {
    setInterval(() => {
      console.log(getCount()) // 使用 ref 穿透闭包
    }, 1000)
  }, [])

  return (
    <button onClick={() => setCount(count => count + 1)}>
      count: {count}
    </button>
  )
}
```

`react-use` 中类似功能为 [useGetSet](https://github.com/streamich/react-use/blob/master/docs/useGetSet.md) 与 [useGetSetState](https://github.com/streamich/react-use/blob/master/docs/useGetSetState.md)

区别在于目前的设计只在 useState 心智上额外增加 getState 函数

**Comment by chj-damon** [comment]
> ```js
>   const [count, setCount] = useState(0)
>   const countRef = useRef(count)
>   countRef.current = count
> ```

为什么要这么写啊？

**Comment by CJY0208** [comment]
@chj-damon 用来穿透闭包的，这里有个不太恰当的 [demo](https://codesandbox.io/s/hardcore-khayyam-bfw3q)，但能说明 react hooks 中存在的闭包问题
 
![](https://user-images.githubusercontent.com/18415774/142174017-6491e11f-2eb0-4c23-bbbd-55c321c51326.gif)

**Comment by brickspert** [comment]
Released on v3.0.0-alpha.9

**Comment by SignDawn** [comment]
这种实现方式可能还是有问题的吧，stateRef.current 的更改仍然需要在下一次的 re-render 中才会更新。
与 react-use 中的实现还是有差异。
https://codesandbox.io/s/da-kai-kong-zhi-tai-cha-kan-shu-chu-forked-8v8swd?file=/App.tsx

参考这个 demo

**Comment by CJY0208** [comment]
@SignDawn 看了一下 react-use 是在 setState 时就改变了 stateRef.current，确实会提早一些

感觉 state 值大部分还是在 re-render 下获取才有意义，目前的实现方式，具体在哪种场景下会产生问题，可以举个例子嘛？

**Comment by SignDawn** [comment]
https://codesandbox.io/s/modest-wave-30gp3y?file=/src/index.js

**Comment by SignDawn** [comment]
https://codesandbox.io/s/modest-wave-30gp3y?file=/src/App.js

**Comment by SignDawn** [comment]
简单 demo 。
当切换到下一页时， setPage(page + 1)；去请求数据，请求下一页的数据，希望 getPage 能够直接得到下一页的页码。

**Comment by SignDawn** [comment]
我这边也不再推荐更改这个 hooks 了，估计会影响到 已经 使用该 hooks 的人。
我直接用 react-use 的 useGetSet

**Comment by fallenleavesguy** [comment]
应当使用react-use的useGetSet
