### ISSUE TITLE
useInfiniteScroll 首次请求调用了两次

### ISSUE THREAD

**Issue by ljianc** [alibaba/hooks#1309]
![1637225751(1)](https://user-images.githubusercontent.com/10055508/142383307-24a75a4b-1e82-4c68-8fb7-cd7e3777991c.png)
![1637225794(1)](https://user-images.githubusercontent.com/10055508/142383460-04815985-0393-4370-bb6a-1eb2c863bc00.png)

**Comment by brickspert** [comment]
Fixed on v3.0.0-alpha.9 

Thank you~
