### ISSUE TITLE
usePagination 手动触发时每次都要显式传递current 和pageSize不合理

### ISSUE THREAD

**Issue by chj-damon** [alibaba/hooks#1312]
const { run } = usePagination(service, { manual: true });

在执行run 方法的时候，实际上走的是Fetch => run(params) => runAsync(params) => servicePromise(...params);
在这个过程中，并不会用到usePagination的默认参数，即 { current: 1, pageSize: defaultPageSize }。
也就意味着，每次在手动run的时候，都要显式地传递 current 和 pageSize。

我觉得这是一种不太合理的情况。

**Comment by brickspert** [comment]
因为这样设计是最灵活的，也是符合 useRequest 的规范的。

* 如果用户需要手动 `run` 的时候变更分页，就只能这么做
* 返回的 params 参数，第一个就是分页相关数据，如果 `run` 又不带分页数据，就很不直观了

**Comment by My-phantom** [comment]
为什么current减不到0啊

**Comment by liuyib** [comment]
> 为什么current减不到0啊

在已关闭的 issue 后面评论，可能没人跟踪你的问题。请开新的 issue，反馈下你的需求或问题
