### ISSUE TITLE
useReactive - read-only and non-configurable data property 

### ISSUE THREAD

**Issue by rimsila** [alibaba/hooks#1317]
ahooks v2.10.12
can't access to record.rule it will showing error like picture below other wise like record.id is working fine. thanks you
<img width="481" alt="Screen Shot 2021-11-20 at 2 53 54 PM" src="https://user-images.githubusercontent.com/51617383/142719275-d6fc3956-e87c-4731-87cd-6b92b9d66ffa.png">
<img width="1030" alt="Screen Shot 2021-11-20 at 2 54 21 PM" src="https://user-images.githubusercontent.com/51617383/142719280-1909c7b0-f8d1-4a16-92ff-8164edb8b462.png">

**Comment by brickspert** [comment]
Can you provide an example？I can’t reproduce this problem in my test：https://codesandbox.io/s/eager-resonance-ebbh8?file=/App.tsx

**Comment by rimsila** [comment]
I not sure about that too maybe it error because of the data  was not initial to useReactive (get from server) I can access to `state.record.id` but can't access to`state.record.rule` maybe rule is object and very nested data. thanks you

**Comment by rimsila** [comment]
> Can you provide an example？I can’t reproduce this problem in my test：https://codesandbox.io/s/eager-resonance-ebbh8?file=/App.tsx

@brickspert  In my case above I'm not sure the root cause but I have test I see new case when useReactive contain react element or form data it cause the error  
```tsx
'get' on proxy: property '_store' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '#<Object>')
```
here is my reproduce https://codesandbox.io/s/condescending-pateu-rkq85?file=/App.tsx

**Comment by askurat** [comment]
Same issue here: If you set a property to a React component you will get this error.

**Comment by liuyib** [comment]
mark a test case:

```ts
const NonConfigurableObject = function createNonProxyableObject(): {user: {name: string}} {
  const obj = {}
  Reflect.defineProperty(obj, 'user', { 
    value: { name: "Alice" }, 
    writable: false, 
    configurable: false,
  })
  // Reflect.getOwnPropertyDescriptor(obj, 'user')
  // { value: {…}, writable: false, enumerable: true, configurable: false }
  return obj as any
}();

export default () => {
  const state = useReactive(NonConfigurableObject);

  return (
    <div>
      <div>{state.user.name}</div>
    </div>
  );
};
```

**Comment by liuyib** [comment]
这个暂时看无解，见排查过程：https://github.com/alibaba/hooks/pull/2079#discussion_r1118106494, 后续慢慢研究

**Comment by liuyib** [comment]
This seems to work: https://github.com/patriksimek/vm2/issues/62#issuecomment-307606058
