### ISSUE TITLE
useWebsocket 无法传参 protocols

### ISSUE THREAD

**Issue by xiaoyueguang** [alibaba/hooks#1320]
建议加个参数, 允许传参 `protocols`

[相关文档](https://developer.mozilla.org/zh-CN/docs/Web/API/WebSocket/WebSocket)

看代码里的实现是没有传这个东西, 导致无法实现多个WebSocket子协议

**Comment by brickspert** [comment]
在 v3.0.0-alpha.11 增加了这个属性。

你现在用的是 2.0 版本，还是 3.0 版本·~

https://ahooks-next.surge.sh/zh-CN/hooks/use-web-socket

**Comment by xiaoyueguang** [comment]
> 在 v3.0.0-alpha.11 增加了这个属性。
> 
> 你现在用的是 2.0 版本，还是 3.0 版本·~
> 
> https://ahooks-next.surge.sh/zh-CN/hooks/use-web-socket

很显然, 我用的2.0。看来得3.0发布后再使用了
