### ISSUE TITLE
useRequest 可以动态传递 url，method，和 data 吗

### ISSUE THREAD

**Issue by zhgtt** [alibaba/hooks#1321]
由于请求的参数，url，请求方式都需要动态显示，而  useRequest 又是一个 hook，只能写在函数组件中，请问有什么好的方式可以对其进行封装，动态进行请求呢？类似下面这样的（当然这是个错误的写法）。。
![image](https://user-images.githubusercontent.com/39938981/142854625-8037f37a-6619-4c9b-b464-97762b48e297.png)

**Comment by brickspert** [comment]
```ts
const result = useRequest((url, method, params) => {
  return fetch({url, method, params});
});
```

**Comment by brickspert** [comment]
你可以理解 useRequest 就是处理 Promise 的
