### ISSUE TITLE
[v3] useRequest 设置 statleTime 后，保鲜期内 refresh 不会发起请求，与“刷新”操作语义相悖

### ISSUE THREAD

**Issue by whinc** [alibaba/hooks#1323]
关于 refresh 有个疑问，当前的版本(3.0.0.alpha-12）中，一旦指定 staleTime 后，在 staleTime 保鲜期内，调用 refresh 并不会实际发起请求，这与“刷新”这个操作的意图相违背，个人认为 refresh 应当无视本地数据始终发起请求，达到刷新的目的。或者 refresh 接口能提供类似 skipStale 的选项

下面是一个示例，点击刷新按钮后，调用 refresh 操作并不会发起请求
https://codesandbox.io/s/agitated-mcclintock-j2lu3?file=/App.tsx

**Comment by brickspert** [comment]
v3.0.0-alpha.18 提供了一个 `clearCache` 能力来清空缓存。

至于 refresh 是否会强制刷新，这个暂时不会添加。
