### ISSUE TITLE
useRequest 如何传递 FormData 形式的参数？

### ISSUE THREAD

**Issue by zhgtt** [alibaba/hooks#1324]
useRequest 如何传递 FormData 形式的参数？找文档并没有找到想要的结果
![image](https://user-images.githubusercontent.com/39938981/143043452-876ed4f5-7708-4df2-879f-ce41a73a7f50.png)

**Comment by zhgtt** [comment]
![image](https://user-images.githubusercontent.com/39938981/143045000-145b3d26-dee9-460c-be5e-372cb6c23c76.png)
尝试这样的写法也不可行

**Comment by brickspert** [comment]
useRequest 就是把这些参数，透传给 fetch，建议你自行用 fetch 测试如何发送正确的数据。
