### ISSUE TITLE
[v3] v3的文档在哪里呀，找不到了，之前官网上有提示能跳转过去，现在没有了。

### ISSUE THREAD

**Issue by fernandoxu** [alibaba/hooks#1327]

**Comment by brickspert** [comment]
https://ahooks-next.surge.sh/

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/143361150-858b3947-e0c0-447e-ba08-907f0314156a.png)

**Comment by fernandoxu** [comment]
@brickspert 
![image](https://user-images.githubusercontent.com/20871468/143386248-3acb434c-57a0-40c6-8af0-e0f6a2aa665d.png)
原来是被AdGuard插件拦掉了
