### ISSUE TITLE
使用useUrlState的问题

### ISSUE THREAD

**Issue by zhaomenglu** [alibaba/hooks#1331]
项目react版本和react-router版本以及@ahooksjs/use-url-state，版本都和官网实例一致，
![image](https://user-images.githubusercontent.com/39189837/143539702-ab332bb2-dc5d-41a0-b231-65f6457efe05.png)
但是使用还是有问题，
![image](https://user-images.githubusercontent.com/39189837/143539749-1082dde6-6403-4eb4-8d02-5543407c9dc6.png)

**Comment by brickspert** [comment]
参考：https://codesandbox.io/s/suspicious-feather-cz4e0?file=/App.tsx

官网上提供了一个在线示例，可以对比下有啥差异。  是不是没有初始化 react-router.

**Comment by liaojunhao** [comment]
umi哪里去写这个`<Router history={history}>
      <Route component={App} />
    </Router>`

**Comment by ywzhaiqi** [comment]
同楼上，umi 怎么解决这个问题？
