### ISSUE TITLE
useAntdTable的defaultParams不支持antd v4的from初始化吗

### ISSUE THREAD

**Issue by xiaoshui222** [alibaba/hooks#1334]
const [form] = Form.useForm();
  
  const { tableProps, search, loading } = useFormTable(getTableData, {
    form,
    defaultParams: [
      { current: 2, pageSize: 5 },
      { name: 'hello', email: 'abc@gmail.com', gender: 'female' }
    ],
    defaultType: 'advance'
  });

用的v4的Form

**Comment by brickspert** [comment]
> const [form] = Form.useForm();
> 
> const { tableProps, search, loading } = useFormTable(getTableData, { form, defaultParams: [ { current: 2, pageSize: 5 }, { name: 'hello', email: '[abc@gmail.com](mailto:abc@gmail.com)', gender: 'female' } ], defaultType: 'advance' });
> 
> 用的v4的Form

1. 用的是 ahooks 2.0 吗？
2. 可以提供个复现  demo？

**Comment by xiaoshui222** [comment]
> > const [form] = Form.useForm();
> > const { tableProps, search, loading } = useFormTable(getTableData, { form, defaultParams: [ { current: 2, pageSize: 5 }, { name: 'hello', email: '[abc@gmail.com](mailto:abc@gmail.com)', gender: 'female' } ], defaultType: 'advance' });
> > 用的v4的Form
> 
> 1. 用的是 ahooks 2.0 吗？
> 2. 可以提供个复现  demo？

可以了，Form忘记绑form了，感谢回复
