### ISSUE TITLE
useRequest 返回的tableProps 中的 pagination 类型和antd 4.17.2的table类型对不上

### ISSUE THREAD

**Issue by cl1107** [alibaba/hooks#1336]
useRequest 返回的 Pagination类型
` itemRender?: (page: number, type: 'page' | 'prev' | 'next' | 'jump-prev' | 'jump-next', originalElement: React.ReactElement<HTMLElement>) => React.ReactNode;`

antd 中的类型是 `itemRender?: (
      page: number,
      type: 'page' | 'prev' | 'next' | 'jump-prev' | 'jump-next',
      element: React.ReactNode,
    ) => React.ReactNode;`
![image](https://user-images.githubusercontent.com/21985353/144157828-c344bdb6-e43c-4c4b-8114-27ebc92b1d57.png)

**Comment by brickspert** [comment]
建议暂时先 `as any` 来解决这个问题，升级到 v3.0 之后已经修复该问题~
