### ISSUE TITLE
useRequset如何监听document滚动来加载更多呢

### ISSUE THREAD

**Issue by liujianchaogit** [alibaba/hooks#1340]
可设置loadMore和ref来监听某个div滚动到底部来加载更多
那如果要监听的是document滚动到底部ref要怎么写呢？

**Comment by brickspert** [comment]
> 可设置loadMore和ref来监听某个div滚动到底部来加载更多 那如果要监听的是document滚动到底部ref要怎么写呢？

ahooks v2.0 的 useRequest 不支持这个能力。

不过 ahooks v3.0 的 [useInfiniteScroll](https://ahooks-next.surge.sh/zh-CN/hooks/use-infinite-scroll) 支持这个能力。

**Comment by IronKinoko** [comment]
useInfiniteScroll 监听document滚动该怎么写，target传的是什么？
我尝试了 window , document , document.body , document.scrollingElement 都没有效果 @brickspert

**Comment by brickspert** [comment]
> useInfiniteScroll 监听document滚动该怎么写，target传的是什么？ 我尝试了 window , document , document.body , document.scrollingElement 都没有效果 @brickspert

v3.0.3 修复了这个问题，现在传递 document 就可以了。

**Comment by taoliujun** [comment]
> 

不知道是否使用方式有问题，使用document后，在未滚动的情况下，无限触发dataRequest
