### ISSUE TITLE
建议'防抖'和'截流'不要放在 useRequest API 功能里面

### ISSUE THREAD

**Issue by zm8** [alibaba/hooks#1343]
因为它额外引用了 lodash 的 防抖和截流, 多了些依赖,  防抖和截流其实可以引用 useDebouce 和 useDebounce 代码处理。

而且像下面的 issue 目前也没解决，还是一个比较常见的场景的。
https://github.com/alibaba/hooks/issues/759

**Comment by brickspert** [comment]
1. useRequest 还是希望做一个比较全面的请求解决方案。如果按这样的拆分思路，轮询/refreshOnWindowFocus 等都可以通过其它 hooks 实现，就没那么强大了。
2. lodash 可以按需加载，所以不需要太担心
3.  #759 issue，不是一个通用的需求，useRequest 暂时不会支持~~

**Comment by zm8** [comment]
好的，谢谢
