### ISSUE TITLE
useRequest 是否有 使缓存失效的功能

### ISSUE THREAD

**Issue by zm8** [alibaba/hooks#1344]
比如一个很常见的场景, A 用户访问一个页面用了 cacheKey 这个功能, 
然后A 用户退出了, B 用户登录, 这个时候 A 使用的缓存还在, 感觉体验不太好。

是否做一个类似 React Query 的 invalidateQueries 方法?

**Comment by brickspert** [comment]
ahooks v3 会增加一个 clearCache 能力，正在开发中~

**Comment by brickspert** [comment]
Duplicate: #884

**Comment by zm8** [comment]
好的 感谢回复~

**Comment by zm8** [comment]
> ahooks v3 会增加一个 clearCache 能力，正在开发中~

想问下大佬，大概什么时候开发好?

**Comment by brickspert** [comment]
added on v3.0.0-alpha.18

**Comment by Valar103769** [comment]
> 比如一个很常见的场景, A 用户访问一个页面用了 cacheKey 这个功能, 然后A 用户退出了, B 用户登录, 这个时候 A 使用的缓存还在, 感觉体验不太好。
> 
> 是否做一个类似 React Query 的 invalidateQueries 方法?

大佬, 我没有缓存接口的场景,请问是什么需求, 徐啊哟缓存, 学习一下
