### ISSUE TITLE
`useRequest` return stale data

### ISSUE THREAD

**Issue by kongmoumou** [alibaba/hooks#1345]
reproduction demo: https://codesandbox.io/s/userequest-refreshdeps-demo-1bovp?file=/App.tsx

When `refreshDeps` changed, its return data should immediately change to  `{ data: null, loading: true }` just like other react request lib (e.g. swr, react-query).

![image](https://user-images.githubusercontent.com/35442047/144438216-aac9404d-bdc8-4235-9790-5df9984b231f.png)

**Comment by brickspert** [comment]
`refreshDeps` is just a syntactic sugar, when it changes, call `refresh` once. The current processing has nothing to do with cache.

Now there are two solutions:

1. You can change `options.cacheKey` when `refreshDeps` change.
2. `useRequest` return a force refresh method to ignore cache.

**Comment by kongmoumou** [comment]
我意思是 deps 变化在当前 render 中仍返回了旧的请求数据，effect 里 refresh 下次 render 才能拿到新状态。其他两个主流的请求库（swr, react-query）默认都是跟 deps 同步变化的，这符合预期嘛😂

**Comment by brickspert** [comment]
> 我意思是 deps 变化在当前 render 中仍返回了旧的请求数据，effect 里 refresh 下次 render 才能拿到新状态。其他两个主流的请求库（swr, react-query）默认都是跟 deps 同步变化的，这符合预期嘛😂

符合预期的。 useRequest 的理念就是这样的，不会清空上一次的数据。
