### ISSUE TITLE
useFormData Form.Item里用了一个封装的组件后，service里的formData就拿不到此项Form.Item的数据

### ISSUE THREAD

**Issue by xiaoshui222** [alibaba/hooks#1346]
重现链接：https://codesandbox.io/s/dank-breeze-xuekc?file=/demo.tsx

封装里SelectSearch组件，但是搜索的时候拿不到这个数据

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/144774267-5b1809f6-6e21-4994-8f23-506911085045.png)
https://ahooks.js.org/zh-CN/hooks/table/use-antd-table#1-%E6%97%A0%E6%B3%95%E8%AF%BB%E5%8F%96%E6%88%96%E5%88%9D%E5%A7%8B%E5%8C%96%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E7%BB%84%E4%BB%B6%E7%9A%84%E5%80%BC
