### ISSUE TITLE
useUrlState在vite打包后报错

### ISSUE THREAD

**Issue by hemengke1997** [alibaba/hooks#1349]
![image](https://user-images.githubusercontent.com/49073282/144832205-b419770d-e854-4fe5-86f1-879be1653553.png)
![image](https://user-images.githubusercontent.com/49073282/144832293-ef6e2a96-0fa7-4000-ac2d-a0ece12a8459.png)

本地运行没问题，打包部署后报错，所以无法给复现...

**Comment by brickspert** [comment]
fixed on v3.0.0-alpha.18
