### ISSUE TITLE
ts 使用useusePagination  时 onChange 没有类型没有适配上

### ISSUE THREAD

**Issue by 957651480** [alibaba/hooks#1352]
![image](https://user-images.githubusercontent.com/10103541/145024086-80267f01-6487-4d99-a76f-12abfddc17d2.png)

TS2322: Type '(c: number, p: number) => void' is not assignable to type '(page: number, pageSize?: number | undefined) => void'.   Types of parameters 'p' and 'pageSize' are incompatible.     Type 'number | undefined' is not assignable to type 'number'.       Type 'undefined' is not assignable to type 'number'.

**Comment by 957651480** [comment]
后面直接这样就正常了onChange:(page,pageSize)=>pagination.onChange,

**Comment by crazylxr** [comment]
现在没有这个问题了，先 close 了
