### ISSUE TITLE
useRequest 去掉的 formatResult，如何拦截响应数据呢

### ISSUE THREAD

**Issue by thinkingc** [alibaba/hooks#1356]
useRequest 去掉的 formatResult，如何拦截响应数据呢

**Comment by brickspert** [comment]
service 返回期望的最终数据就好了~~

```ts
const { data } = useRequest(()=>{
    const res = request();
    return res.data;
});
```

**Comment by thinkingc** [comment]
> service 返回期望的最终数据就好了~~
> 
> ```ts
> const { data } = useRequest(()=>{
>     const res = request();
>     return res.data;
> });
> ```

useRequest 第一个参数只能是返回Promise的函数，不能是字符串、对象，或者返回对象的函数了吗？
感觉这个限制不太好，之前用的时候第一个参数很多都是直接传个对象或字符串。

升级好麻烦，而且也感觉不方便了，不想升级了。

**Comment by brickspert** [comment]
> > service 返回期望的最终数据就好了~~
> > ```ts
> > const { data } = useRequest(()=>{
> >     const res = request();
> >     return res.data;
> > });
> > ```
> 
> useRequest 第一个参数只能是返回Promise的函数，不能是字符串、对象，或者返回对象的函数了吗？ 感觉这个限制不太好，之前用的时候第一个参数很多都是直接传个对象或字符串。
> 
> 升级好麻烦，而且也感觉不方便了，不想升级了。

这种需求建议自己基于 useRequest，封装一个 Hooks~~

**Comment by brickspert** [comment]
Relation #1358

**Comment by james70s** [comment]
```typescript
const { data } = useRequest(()=>{
      const res = request();
      return res.data;
  }, 
    {
      formatResult: (res) => {
        // 这里的res是拿到的接口返回的数据
        return list;
      },
    },
  );
```
