### ISSUE TITLE
3.x 版本的 useRequest 升级麻烦

### ISSUE THREAD

**Issue by thinkingc** [alibaba/hooks#1358]
2.x 好用的地方
1. 可以在全局配置 UseRequestProvider 的 requestMethod 默认用自己的请求器，比如统一用axios，或者公司自己封装的 $http
2. 第一个参数接收 string 、 object 、 (...args) => string | object，使用上面配置的请求器很方便
3. formatData 拦截处理响应数据

3.x 不好用的地方
1. 第一个参数只能接收 (...args: TParams) => Promise<TData>，限制的很死板，虽然可以在这个函数里面定制各种功能，但变的很笨重。
2. 升级困难，需要改动每一个useRequest请求，**能否基于2.x做个兼容呢**？

**Comment by brickspert** [comment]
建议基于 useRequest 封装一个自己的 Hooks，类似：

```ts
function useCustomRequest(pathname, options){
  return useRequest(()=> {
      return axios(pathname);
  }, options);
}

```

这样比较灵活。

**Comment by brickspert** [comment]
这个我补充到文档里面，整体思路还是一些高级功能希望大家基于 useReqeust 封装来解决。
