### ISSUE TITLE
使用了缓存的 cacheKey 之后报错

### ISSUE THREAD

**Issue by zm8** [alibaba/hooks#1359]
``` js
TypeError: t.finally is not a function
```
手机端报错了, 看了下是 ```cachePromise.ts``` 使用了 ```promise.finally```,   这个pollyfill 要自己加? 请问下建议?

https://github.com/alibaba/hooks/blob/8a443f5f3fbd0fd2fdd732059d9a8262493688c7/packages/hooks/src/useRequest/src/utils/cachePromise.ts

**Comment by zm8** [comment]
ahooks 需要依赖哪些 pollyfill, 建议文档上面写下, 
Map 和 Set 因为 React 本身也依赖了, 不写问题不大, 
其它的是否需要补充下文档？

**Comment by brickspert** [comment]
我看下兼容性这边需要怎么搞

**Comment by brickspert** [comment]
v3.0.7 暂时移除了 promise.finally 的使用。

**Comment by zm8** [comment]
> v3.0.7 暂时移除了 promise.finally 的使用。

好的，下次如果使用类似兼容性的代码时，期望加强 code review，否则使用库的人容易造成生产故障。
