### ISSUE TITLE
能问一下为什么 useRequest 取消了并行请求的能力吗

### ISSUE THREAD

**Issue by GeraltX** [alibaba/hooks#1378]
如果父组件是个虚拟滚动列表，子组件中发请求，那滚动时子组件的请求状态就丢失了。

**Comment by brickspert** [comment]
1. 为什么取消了并行请求？

useRequest 实现并行能力复杂度太高。
我们建议将 请求和UI 封装成一个组件实现并行请求的能力。而不是把所有请求都放到父级。

2. 虚拟滚动场景，确实会有问题。这种场景建议自行管理请求状态。


o(╥﹏╥)o
