### ISSUE TITLE
typescript useMap语法报错

### ISSUE THREAD

**Issue by kechen123** [alibaba/hooks#1385]
"typescript": "^4.1.2",
"ahooks": "^3.0.0-alpha.18",

是我哪里设置的有问题吗

![image](https://user-images.githubusercontent.com/16396880/146359983-49903c27-b106-4c28-bba3-9567cbfab67f.png)

tsconfig.json文件
![image](https://user-images.githubusercontent.com/16396880/146360169-4abb959a-1eb8-4099-8c85-bda35943f0fe.png)

**Comment by awmleer** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/16526078/146382473-cb63f2a4-d217-48e7-b01c-fc2d60746cc4.png">

不科学啊，我试了一下是正常的

**Comment by kechen123** [comment]
> <img alt="image" width="603" src="https://user-images.githubusercontent.com/16526078/146382473-cb63f2a4-d217-48e7-b01c-fc2d60746cc4.png">
> 
> 不科学啊，我试了一下是正常的

是啊 不知道啥情况 我试着把 ts和 ahook版本都更新到最新还是这样

**Comment by brickspert** [comment]
同正常

**Comment by chocWan** [comment]
我也遇到这个错误，改版本也不行
