### ISSUE TITLE
peerDependencies中React版本声明问题

### ISSUE THREAD

**Issue by hangaoke1** [alibaba/hooks#1392]
ahooks版本v.1.1.5中升级了react-reconciler@0.26.2，但是这个包中声明的peerDependencies是17.x，与ahooks中声明的16.x冲突，导致npm自检失败

**Comment by brickspert** [comment]
ahooks v1.1.5？是不是错了。。 ahooks 现在都 v3 版本了。

ahooks 声明的是 `^16.8.6 || ^17.0`

**Comment by hangaoke1** [comment]
不好意思，走错路了，是hox库里的问题 emmm
