### ISSUE TITLE
useRequest自定义缓存, 能否支持不重新发起请求呢

### ISSUE THREAD

**Issue by FloaJa** [alibaba/hooks#1393]
缓存对于不变的枚举列表来说太方便了, 但是项目规定要存入session, 通过自定义缓存实现后, 还是每次都要发起请求
希望: 比如`getCache`返回`null`或者`undefined`才会重新发起请求这样

**Comment by brickspert** [comment]
配置 `options.staleTime = -1` 即可

**Comment by FloaJa** [comment]
> 

不行诶, 自定义缓存之后`staleTime`不生效

**Comment by brickspert** [comment]
https://codesandbox.io/s/nice-river-vz3sq?file=/App.tsx

生效的，看下这个 demo。
