### ISSUE TITLE
Userequest 支持debouncewait参数么？

### ISSUE THREAD

**Issue by JJunYang** [alibaba/hooks#1398]
使用useRequest的时候，options.debounceWait无法设置，只能找到debounceInterval这个选项，跟文档说明有点出入https://ahooks.js.org/zh-CN/hooks/use-request/debounce。
![截屏2021-12-21 下午8 26 32](https://user-images.githubusercontent.com/50793382/146929869-be58e228-75b0-4f9a-8da0-4df1e9a70eca.png)

**Comment by brickspert** [comment]
文档是 v3.0 版本的，你应该用的还是 v2.0 版本的奥~  2.0 还不支持 debouncewait~
