### ISSUE TITLE
Add hook to detect focusWithin and focusOutside

### ISSUE THREAD

**Issue by equinusocio** [alibaba/hooks#1399]
**Is your feature request related to a problem? Please describe.**
An hook to detect if focus is moved within or outside an element would be useful for accessibility, like the `:focus-within` css selector.

**Describe the solution you'd like**
DEMO:
https://react-spectrum.adobe.com/react-aria/useFocusWithin.html

EXAMPLE SRC
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/useFocusWithin.ts

**Describe alternatives you've considered**
Using the react-aria hooks

**Comment by brickspert** [comment]
This Hooks is more used in the basic component library, and it is hardly used in the actual business code? I haven't encountered a similar scene, which requires JS to handle it.

o(╥﹏╥)o

**Comment by equinusocio** [comment]
This hook is useful when building a components library yes. For example in dialogs component, which requires to be removed from the dom/unmounted when the user navigate outside it with the keyboard. 

A real example is a dropdown component, when the dropdown is open and the user navigates the items inside using the keyboard, the dropdown should close (and be unmounted) once the focus goes outside it. You can see an [example here](https://design.wonderflow.ai/components/dialogs/dropdown/) where we're using the react-aria hook just for this.

The `CSS` alternative `:focus-within` doesn't allow to unmount the component, but just to hide it.

**Comment by brickspert** [comment]
Wow, your components are so surprised!

In my cognition, components such as DropDown are clicked outside to trigger hidden, such as the [DropDown](https://ant.design/components/dropdown/) component of ant design.

So we provide [useClickAway](https://ahooks.js.org/hooks/use-click-away) to meet such scenarios.

But it is true that blur behaviors such as `tab` also require unmount components.

But at present, there are fewer demand scenarios for this Hooks, so it will not be added to ahooks for the time being.

If there are more users in demand, let's add it again.

**Comment by equinusocio** [comment]
> In my cognition, components such as DropDown are clicked outside to trigger hidden, such as the DropDown component of ant design.

Yes, this is for those who use fine pointers (mouse and pens), to be accessible, keyboard navigation should be covered too.

> So we provide useClickAway to meet such scenarios.

Yep we use it to handle the click outside

> But at present, there are fewer demand scenarios for this Hooks, so it will not be added to ahooks for the time being.

This is a bit sad to read, accessibility is a core value of web development, not a plus. I asked to add the same on [rooks](https://github.com/imbhargav5/rooks/issues/592) and [react-use](https://github.com/streamich/react-use/issues/2119) (which seems abandoned).

**Comment by awmleer** [comment]
@equinusocio I totally agree with you. Accessibility is really something we need to concern about.

**Comment by brickspert** [comment]
OK, I will add this hooks as soon as~

**Comment by brickspert** [comment]
[useFocusWithin](https://ahooks.js.org/hooks/use-focus-within) is coming! you should install v3.1.0, welcome to use ahooks~

**Comment by equinusocio** [comment]
That's amazing. Thank you. We can finally drop both react-use and react-aria.
