### ISSUE TITLE
useAPI 的两个问题

### ISSUE THREAD

**Issue by Deturium** [alibaba/hooks#14]
## useAPI 讨论

在我看来 useAPI 现在的设计和实现有两个问题：

### 与  `axios`  强耦合

在绝大部分业务中，request 库都是有自己封装的，可能用的是 `fetch` 又或者是 `umi-request` 等等，`useAPI` 作为一个基础 hook，不应该钦点用户使用 `axios`

再者，在钦点的情况下，对于请求参数也仅仅透传了 url、method、body 三者，对于复杂请求也是不够的

因此，这个 api 设计的没有可扩展性的，我实际使用中更倾向自己封装服务的 Promise 然后去使用类似 `useAsync` 的 hook

### 没有竞态处理

这里说的竞态处理不是指取消请求，而是

1. 重复请求的覆盖
2. 请求返回之前组件就没卸载

情况1经常发生于快速翻页表单一类的情况下，所需要做处理接近 `rxjs` 中的 `switchMap`

后者如果不处理 `React` 会在 console 给你报 error

这里我给一个处理思路参考

```js
function useAPI(apiService, deps) {
  // ...
  // 处理竞态请求
  const serviceUID = useRef(0);
  useEffect(() => {
    const thisUID = serviceUID.current;
    // 请求
    apiService().then(/res/ => {
      // 原请求被新请求覆盖
      if (thisUID !== serviceUID.current) {
        return;
      }
      // ...
    })

    return () => {
      // 抛弃未完成的请求
      serviceUID.current += 1;
    };
  }, [deps]);
}
```

**Comment by ttys026** [comment]
感谢建议，现在的 useAPI 确实存在比较多的问题，一开始只是业务里用到的一个代码片段，希望在写 hooks 教程的时候能在 riddle 中直接引用。没有经过慎重考虑。

之后版本的 useAPI 会基于目前的 useAsync 重写，request 的方法会由用户传入，竞态处理在 useAsync 中用了 boolean 值处理，不过当同时处理多个请求的时候，用自增的 counter 应该是更可靠的。
