### ISSUE TITLE
useVirtualList  虚拟列表 list 为空数组

### ISSUE THREAD

**Issue by PiccoloYu** [alibaba/hooks#1402]
![image](https://user-images.githubusercontent.com/44945137/147078589-46d1ffe3-15fe-4e8c-a24f-2bacee50c455.png)
![image](https://user-images.githubusercontent.com/44945137/147078738-8b689f3b-e35c-459e-83c4-88c74c61de79.png)
按照官网例子 敲得

**Comment by PiccoloYu** [comment]
原因发现了，v3的useVirtualList 要给父元素 固定高度，动态高度没有了吗

**Comment by PiccoloYu** [comment]
原因是 v3的useVirtualList 必须给 固定height，max min 不行，有可替代方案吗

**Comment by brickspert** [comment]
理论上不需要固定的 height，可以提供个复现代码~~

**Comment by PiccoloYu** [comment]
https://codesandbox.io/s/usevirtuallist-d4iff?file=/src/App.js

就像这个例子 
originalList 给了 固定的height 它的 useVirtualList  中的 list 是能够获取到值的。
 originalList1 给了 不固定的maxHeight 它的 useVirtualList  中的 list1 获取到的都是空数组
这是 设计如此吗

**Comment by brickspert** [comment]
你只给了 `max-height`，那默认高度就是 0，此时肯定是没有数据展示的。

再加个 `min-height` 就 ok 了。

https://codesandbox.io/s/usevirtuallist-forked-1f2ih?file=/src/App.js

**Comment by PiccoloYu** [comment]
哦哦 明白了
