### ISSUE TITLE
[Feature request] useKeyPress 回调传入触发的快捷键

### ISSUE THREAD

**Issue by yunsii** [alibaba/hooks#1404]
## 使用场景

使用单个 hook 注册多个快捷键的不同回调，回调时不能直接知道是什么快捷键触发，特别是使用组合键时。

例如：

```
useKeyPress(['r', 'o', 'l', 'a', 's'], (event) => {})
```

通过一个 hook 注册了 5 个快捷键，每个快捷键对应不同的逻辑，目前是在回调里自己额外处理的。不方便分别注册实现，因为是通过注册器得到的一类快捷键定义。

**Comment by yunsii** [comment]
看了下代码，好像还不是三两下能改好的……

**Comment by brickspert** [comment]
v3.1.2

**Comment by Simon-He95** [comment]
@yunsii 
这个是不是应该再自己的逻辑里面去判断比较好，信息都在e中，可以根据自己的需要包一层e，因为这个组合ctrl+c会跟你业务定义的逻辑相关有的人定义ctrl&c或者ctrl + c，觉得不应该在useKeyPress中处理

**Comment by yunsii** [comment]
@Simon-He95 是可以自己处理的，但是就想你说的如果额外定义了组合键判断起来就很麻烦。我最初的想法是这样：

```ts
const hotKeys = [
	{
		keys: ['ctrl', 'c'],
		callback: () => {}
	},
	{
		keys: ['c'],
		callback: () => {}
	},
]

// ...

useKeyPress([hotKeys.map(item => item.keys)], (event, keys) => {
	hotKeys.find(item => _.isEqual(item.keys, keys))?.callback()
})
```

或者说内部直接支持传 callback 得了？

**Comment by Simon-He95** [comment]
我觉得还是不要支持传callback比较好，会增加额外的开销，还是第二个参数传string[]的方式好一些

**Comment by yunsii** [comment]
能支持第二个入参挺好的，特别是这种场景
