### ISSUE TITLE
setUrlState与useAntdTable配合使用时，首次加载时分页组件没有选中当前页面

### ISSUE THREAD

**Issue by Hitotsubashi** [alibaba/hooks#1405]
想做出的效果是location.search记录current和pageSize且随着两者的变化而变化，然而发现每次刷新页面时，虽然发出请求的current和pageSize是正确的，但分页组件没有根据current选中当前页面。
https://codesandbox.io/s/lucid-dubinsky-ezrjp?file=/src/App.js:732-744

**Comment by brickspert** [comment]
demo 中，从 url 上拿到的 `page.current` 等是字符串，需要自行转成 number~
