### ISSUE TITLE
userequest的cancel无法终止promise请求

### ISSUE THREAD

**Issue by s464446877** [alibaba/hooks#1406]
用cancel终止请求无效，请求还在继续发送状态最终返回结果，实际发送请求用的umi-request，把请求函数放到的userequest的第一个参数上

**Comment by brickspert** [comment]
你是指调用 `cancel` 之后，`data`、`loading` 等状态依旧会更新？

还是仅仅只是网络请求没有终止？

**Comment by s464446877** [comment]
仅仅网络没有终止，loading状态是对的，已经是false了

**Comment by brickspert** [comment]
那这个是预期行为，useRequest 是对 Promise 的管理，在 cancel 的时候，我们只会放弃对该次 Promise 的响应。

并没有中止 Promise 的行为。

**Comment by s464446877** [comment]
那请教一下有什么办法阻止一下请求呢，因为有可能请求失败提示信息，但是可能已经跳转到别的页面了，突然提示一条之前页面的错误信息，这种情况有什么方法避免么

**Comment by brickspert** [comment]
参考 umi-request 的终止请求文档：https://github.com/umijs/umi-request/blob/master/README_zh-CN.md#%E9%80%9A%E8%BF%87-abortcontroller-%E6%9D%A5%E4%B8%AD%E6%AD%A2%E8%AF%B7%E6%B1%82

**Comment by ederzz** [comment]
wtf, why excute promise when canceled?
