### ISSUE TITLE
v3 版本 useInfiniteScroll options 缺少 ready 属性

### ISSUE THREAD

**Issue by dobble11** [alibaba/hooks#1407]
![image](https://user-images.githubusercontent.com/23068345/147332243-70551b90-7daf-4105-a5bc-20be3cca5dc0.png)

**Comment by brickspert** [comment]
是不支持这个参数的，可自行通过 `manual=false` 和 `reload()` 实现

**Comment by dobble11** [comment]
> 是不支持这个参数的，可自行通过 `manual=false` 和 `reload()` 实现
考虑加入吗，毕竟有改造成本

**Comment by brickspert** [comment]
暂时不会添加的哈。
