### ISSUE TITLE
【BUG&建议】 useControllableValue api设计问题以及改进意见

### ISSUE THREAD

**Issue by iamyoki** [alibaba/hooks#1408]
我前天的直播 https://www.bilibili.com/video/BV1Vm4y197SZ/ 专门讲了下自动受控钩子封装的技巧
播完后有朋友问我于老师，发生肾么事了？我说怎么回事, 给我发了几张截图。我一看！嗷！原来是ahooks有个钩子，有两个api。一个用于受控组件，一个用于非受控组件。他们说，诶...有一个说是我用ahooks的useControllableValue把代码练坏了，于老师你能不能教教我混元钩法，诶...帮助修复一下我的报错。我说可以。我说你在本地写死代码，不好用，他不服气。诶...我说小朋友，你把代码提交到github我才能帮你看代码啊，他提交不上去报403。他说你这也没用。我说我这有用，这是开源精神，传统钩子是讲开源精神的，四两拨千斤，二百多天的通宵都肝不动我这一个issue啊...吭！他非要和我试试，我说可以。诶...我一说完啪就拉代码了很快啊！然后上来一个yarn install，吭，一个yarn run init 一个 yarn run dev, 我全部跑起来了啊！跑起来以后自然是开源项目以点到为止，我左手放在ctrl+c上没按下去，我笑一下准备收手，因为这时间，按开源项目的点到为止项目已经成功跑起来了。如果这一按下去，一下就把项目关掉了，他也承认，我先把项目跑起来的。他不知道我手放在ctrl+c上，他承认我先跑起来的啊！我收手的时间不按了，他突然袭击，控制台报红来打我脸，啊，我大意了啊，没有及时ctrl+c，但没关系！他也说，啊他日志也说了，两分多钟以后，当时流眼泪了，捂着眼，我说停停。然后两分钟以后，两分多钟以后诶就好啦。。。

## 言归正传，先讲[useControllableValue](https://ahooks.js.org/hooks/use-controllable-value#options)的 BUG
- 每一次触发setState都会触发onChange 即使值没有发生变化
![2021-12-27 09 45 23](https://user-images.githubusercontent.com/74389358/147426184-c1780701-d73d-4d25-a621-10b255b95c03.gif)
https://codesandbox.io/s/bugs-of-ahooks-usecontrollablevalue-5ruy1?file=/src/App.jsx

- 同时传入value 和 defaultValue时没有报错提示 （应该要像原生一样同时传入时提供报错信息）
![image](https://user-images.githubusercontent.com/74389358/147426345-516f04c6-528a-4ef5-a94a-7e66968e1010.png)
![image](https://user-images.githubusercontent.com/74389358/147426346-cd09e9e0-bc7b-4e26-964c-f1be77954364.png)

## API设计改进建议
可以看一下我直播中封装的最终源码，和使用方式
![image](https://user-images.githubusercontent.com/74389358/147426419-69852b64-7980-4adc-aff3-3e2b54adff24.png)
https://codesandbox.io/s/2021-12-25-auto-controlled-state-live-gtpw5?file=/src/Switch.jsx

个人认为比useControllableValue设计更优的地方在于：
- 不需要额外设计defaultValuePropName和valuePropName这样冗余的api来给prop匹配命名，直接通过入参传入即命名，安全且高效。
- 能够解构props，反之useControllableValue是不能解构props的，因为它需要通过 property in obj这样的语法来判断value属性是否存在。
- 代码量更少
- 不需要单独设计trigger api，用户可以通过传入的onChange函数做二次封装以实现触发的目的
```js
const [] = useAutoControlledState({value, defaultValue, onChange: (newValue)=>{
  onChange(newValue)
  myCustomTrigger(newValue)
}})
```
- 没有上面提到的BUG
- api设计更符合直觉，不需要面向文档

如果Maintainers觉得该提议合理，可以Assign我来提pr改进哦~，但改动较大，需要确定是重新起一个hook还是在此基础上重构

**Comment by brickspert** [comment]
很感谢反馈，针对反馈，我这边建议如下：


> 每一次触发setState都会触发onChange 即使值没有发生变化

这个确实是 bug，需要优化下代码。

> 同时传入value 和 defaultValue时没有报错提示 （应该要像原生一样同时传入时提供报错信息）

这个我认为 ahooks 不需要有报错提示，因为这两个都是 ahooks 支持的属性。


> 不需要额外设计defaultValuePropName和valuePropName这样冗余的api来给prop匹配命名，直接通过入参传入即命名，安全且高效。
能够解构props，反之useControllableValue是不能解构props的，因为它需要通过 property in obj这样的语法来判断value属性是否存在。

关于建议这几点，我是不赞同的。

1. `value in props` 和 `value !== undefined` 是两种不同的含义。
2. 现在的 Hooks 已经稳定，做不了 break change 的。
3. 关于 `valuePropName` 等自定义名字，我觉得仁者见仁吧，在写组件的时候，这种会更方便点感觉，大部分情况传递一个 `props` 就够了，只有极少的情况才需要自定义名字。

**Comment by iamyoki** [comment]
@brickspert 谢谢你的回复，我先关闭此issue 因为breaking change部分不采纳，bug部分在另外开一个issue🤝
