### ISSUE TITLE
useAntTable 和 useAsync 同时使用的问题

### ISSUE THREAD

**Issue by Nokecy** [alibaba/hooks#141]
在useAsync  onSuccess 中调用useAntTable的submit方法不会重新刷新表格。
用例是:使用useAsync新增一条数据后需要刷新表格数据。
[https://codesandbox.io/s/hooks-demo-u3l66](url)

**Comment by brickspert** [comment]
> 在useAsync onSuccess 中调用useAntTable的submit方法不会重新刷新表格。
> 用例是:使用useAsync新增一条数据后需要刷新表格数据。
> [https://codesandbox.io/s/hooks-demo-u3l66](url)

把 submit 放到 useAsync 的 deps 中就可以了。

```
  const { loading, run } = useAsync(
    () => {},
    [submit, hide],
    {
      manual: true,
      onSuccess: () => {
        submit();
        hide();
      }
    }
  );
```

或者你可以这样写
```
run().then(()=>{
        submit();
        hide();
});
```

**Comment by brickspert** [comment]
有问题再 open 哦。

**Comment by Nokecy** [comment]
```
run().then(()=>{
        submit();
        hide();
});
```  
这种方法可行
