### ISSUE TITLE
为什么 useInfiniteScroll 需要在 onSuccess 回调中再调用一次 scrollMethod？

### ISSUE THREAD

**Issue by xdlrt** [alibaba/hooks#1422]
https://github.com/alibaba/hooks/blob/1a67662c37aa8a18d4c612d0516e328e0ff5fad4/packages/hooks/src/useInfiniteScroll/index.tsx#L55

好奇，想了解下是为了解决什么问题

**Comment by brickspert** [comment]
> https://github.com/alibaba/hooks/blob/1a67662c37aa8a18d4c612d0516e328e0ff5fad4/packages/hooks/src/useInfiniteScroll/index.tsx#L55
> 
> 好奇，想了解下是为了解决什么问题

比如首次加载了 10 条，但是没有撑满一个屏幕，需要继续加载第二页数据。

**Comment by peng-yin** [comment]
我现在遇到了问题， 
mutate | 直接修改 data， 造成了， 没有撑满屏幕， 如果更改的数据量大， 会一致请求， 请帮忙解答一下吧，谢谢
