### ISSUE TITLE
使用 useRequest 时，多次请求，返回的内容会出现 undefined

### ISSUE THREAD

**Issue by Maconzhang** [alibaba/hooks#1424]
https://github.com/alibaba/ice/issues/3840

https://codesandbox.io/s/spring-dawn-06okc?file=/src/App.js

老问题, 在hooks 3.0 是复现, fetchKey 无效

**Comment by boiboif** [comment]
3.0不是删除了fetchKey吗。。 另外3.0 run不再返回promise，使用runAsync返回promise

**Comment by brickspert** [comment]
> 3.0不是删除了fetchKey吗。。 另外3.0 run不再返回promise，使用runAsync返回promise

楼上正解，3.0 升级文档见：https://ahooks.js.org/zh-CN/guide/upgrade
