### ISSUE TITLE
请问在ahooks3中如何formatter返回的数据

### ISSUE THREAD

**Issue by qinfeng0214** [alibaba/hooks#1428]

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/148365137-b0585abb-a893-412d-9c26-f8ef2a2a8720.png)

**Comment by qinfeng0214** [comment]
> ![image](https://user-images.githubusercontent.com/12526493/148365137-b0585abb-a893-412d-9c26-f8ef2a2a8720.png)

感谢，掘金关注您了
