### ISSUE TITLE
useAsync run 方法返回异常被吃掉了。

### ISSUE THREAD

**Issue by Nokecy** [alibaba/hooks#143]
https://github.com/umijs/hooks/blob/b6a3d3083381e6393578da923699f69c9feed160/src/useAsync/index.ts#L144-L154

**Comment by brickspert** [comment]
最后的 `return error` 改成 `throw error` 吗？

**Comment by Nokecy** [comment]
[https://github.com/umijs/hooks/issues/141#issuecomment-551886884](https://github.com/umijs/hooks/issues/141#issuecomment-551886884)

```
run().then(()=>{
        submit();
        hide();
})
.catch(err=>{});
```
 这样异常处理不了。

**Comment by brickspert** [comment]
@umijs/hooks@1.4.0-beta.1 解决了这个问题。你可以试试~~
