### ISSUE TITLE
ie9 中使用 useRequest 无法获取到数据

### ISSUE THREAD

**Issue by ZelinBu** [alibaba/hooks#1430]
umi 中安装 ahooks，使用 useRequest 后获取不到数据，显示为 null
ie11 和 ie10 都正常

umi 版本：3.5.20
ahooks 版本：3.0.8

**Comment by brickspert** [comment]
1. 查看是否有 JS 报错
2. 参考 https://www.jianshu.com/p/98318e411acc 等文章，安装兼容依赖

**Comment by ZelinBu** [comment]
> 1. 查看是否有 JS 报错
> 2. 参考 https://www.jianshu.com/p/98318e411acc 等文章，安装兼容依赖

已解决，感谢😊
