### ISSUE TITLE
[问题] useLocalStorage 的触发机制

### ISSUE THREAD

**Issue by hemengke1997** [alibaba/hooks#1433]
假设有 组件A， 组件B
A、B都使用了 useLocalStorage('相同的key')

目前的机制是 组件A中setLocalStorage 不会触发 B 的localStorage更新渲染

请问作者大大，这个机制能否改成 相同key的localStorage在不同组件下set后，都会触发渲染？

**Comment by image72** [comment]
如果useLocalStorageState 只能在同一个组件内使用，那么使用useLocalStorageState 意义不大

**Comment by hansonfang** [comment]
有好的解决方案了不

**Comment by promise96319** [comment]
请问这个有解决方案吗？如果两个组件同时用了 useLocalStorageState，A 组件改了 storage，但是 B 组件拿到的还是上一次的 storage，得到的结果不一致。

**Comment by liuyib** [comment]
目前有对应 PR 来解决了：https://github.com/alibaba/hooks/pull/2298
