### ISSUE TITLE
tsc打包的时候报Could not find a declaration file for module 'js-cookie'

### ISSUE THREAD

**Issue by 314857493** [alibaba/hooks#1437]
node_modules/ahooks/lib/useCookieState/index.d.ts:1:21 - error TS7016: Could not find a declaration file for module 'js-cookie'. '/test项目/vite-react-ts/node_modules/js-cookie/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/js-cookie` if it exists or add a new declaration (.d.ts) file containing `declare module 'js-cookie';`

1 import Cookies from 'js-cookie';

**Comment by 314857493** [comment]
项目是使用vite搭建的项目 vite build时会执行`tsc && vite build` 在这个tsc的过程中会报错 但是我看lock和package.json中都有@types/js-cookie

**Comment by brickspert** [comment]
麻烦提供下 ahooks 版本。

**Comment by 314857493** [comment]
> 麻烦提供下 ahooks 版本。

^3.1.5

**Comment by jiahao-c** [comment]
在`3.1.8` 版本中也遇到了这个问题，也是使用 vite。在 `pnpm add -D @types/js-cookie` 后解决，也可以通过 ` "skipLibCheck": true` 解决

**Comment by 314857493** [comment]
> 在`3.1.8` 版本中也遇到了这个问题，也是使用 vite。在 `pnpm add -D @types/js-cookie` 后解决，也可以通过 ` "skipLibCheck": true` 解决

ok 好使 感谢

**Comment by brickspert** [comment]
fixed in v3.1.9
