### ISSUE TITLE
useRequest 使用run 不同的参数的时候只会请求第一次请求时所带的参数

### ISSUE THREAD

**Issue by hetaoov** [alibaba/hooks#1446]

**Comment by brickspert** [comment]
提供个复现 demo 哈，理论上所有请求都会发出，但只有最后一个请求的响应才会生效。

**Comment by hetaoov** [comment]
抱歉，不是useRequest的问题，是我的请求有问题。谢谢

**Comment by skoll1** [comment]
for循环request.run()这种触发好多请求.确实会全部发出请求,但是onSuccess里面只会返回最后一次调用的回调.前面的数据都没有响应到,是不是请求一批数据的时候不能用for这种操作,之前版本是有给demo的,改了新版本这种情况没有说怎么操作...

**Comment by yangrenmu** [comment]
> 提供个复现 demo 哈，理论上所有请求都会发出，但只有最后一个请求的响应才会生效。

你好，请问怎么才可以响应每次请求，而不是只响应最后一次呢？

**Comment by G-Will** [comment]
![image](https://github.com/alibaba/hooks/assets/24311363/3cd3ebb9-ba3a-454d-b2a2-e9789811dea7)
从源码可以看出来

**Comment by kongchenglc** [comment]
> for循环request.run()这种触发好多请求.确实会全部发出请求,但是onSuccess里面只会返回最后一次调用的回调.前面的数据都没有响应到,是不是请求一批数据的时候不能用for这种操作,之前版本是有给demo的,改了新版本这种情况没有说怎么操作...

这是个bug吧？有解决办法吗
