### ISSUE TITLE
taro中使用防抖节流会报错

### ISSUE THREAD

**Issue by wangqi908** [alibaba/hooks#1448]
![image](https://user-images.githubusercontent.com/32876059/150478787-361caa44-5793-42ea-b474-989a3010e892.png)
![image](https://user-images.githubusercontent.com/32876059/150478809-f8ee0d6c-1e24-44bd-af57-b6d8e9e08ba5.png)

**Comment by brickspert** [comment]
ahooks 版本？3.x 的应该已经解决过类似的问题。

**Comment by laolaolulu** [comment]
真机下的错误,taro中找到的:

` Object.assign(global, {
    Array: Array,
    Date: Date,
    Error: Error,
    Function: Function,
    Math: Math,
    Object: Object,
    RegExp: RegExp,
    String: String,
    TypeError: TypeError,
    setTimeout: setTimeout,
    clearTimeout: clearTimeout,
    setInterval: setInterval,
    clearInterval: clearInterval
  });`

**Comment by zengyayao** [comment]
useThrottleFn 也会出现同样的问题，版本 3.7.7
![image](https://user-images.githubusercontent.com/29397149/236156523-8f12bb54-d52d-40a6-a8f7-3e4105c80311.png)
![image](https://user-images.githubusercontent.com/29397149/236156626-f69047b1-d3ae-45a7-a750-e69b25308e58.png)
