### ISSUE TITLE
useNetwork在think pad 翼 480上不通知断线？

### ISSUE THREAD

**Issue by lidaylin** [alibaba/hooks#1449]
实测过在该型电脑上浏览器监听offline事件没有触发。

**Comment by brickspert** [comment]
需要提供下浏览器版本，ahooks 版本。

另外就是在电脑上其它浏览器也一样不生效吗？

**Comment by lidaylin** [comment]
浏览器版本: 96.0.4664.110，ahooks:2.10.12
其他电脑没有问题，目前发现就是这个型号的电脑有问题

**Comment by crazylxr** [comment]
这个问题我们没办法复现，很久也没有其他的用户反馈，你再关注下，如果还有类似的情况，咱们再一起解决一下，issue 先关闭了哈，需要的时候再 reopen。

**Comment by Suzichen** [comment]
![Image](https://github.com/user-attachments/assets/0f73a968-86dd-4aba-8037-f33e4e4695f4)  win11 Pro版本可复现。(虽然我认为是windows的BUG)

**Comment by crazylxr** [comment]
> ![Image](https://github.com/user-attachments/assets/0f73a968-86dd-4aba-8037-f33e4e4695f4) win11 Pro版本可复现。(虽然我认为是windows的BUG)

那要不你帮忙继续跟进一下，如果真的是 Windows 的问题，也确认一下，我这边没这样的设备确实不好解决
