### ISSUE TITLE
useTableList搜索中使用RangePicker,无法手动处理其值

### ISSUE THREAD

**Issue by 3lang3** [alibaba/hooks#145]
```jsx
<Form.Item label="有效期">
              {getFieldDecorator('valueTime')(
                <DatePicker.RangePicker
                  style={{ width: '100%' }}
                  format="YYYY-MM-DD HH:mm:ss"
                />
              )}
            </Form.Item>
```
触发submit时 
提交了一大推无用的value导致414
![umijs_hooks_usetable_](https://user-images.githubusercontent.com/7098719/68639951-2fbab600-0541-11ea-9b11-87e04d6db8cc.png)

**Comment by 3lang3** [comment]
提交信息不完整 先关了
stringify方法导致解析params时出现差异
并非hooks问题

**Comment by 3lang3** [comment]
但是还是存在无法手动组装RangePicker值的问题
submit能否接受查询参数：
```jsx
// paginationParams 当前的分页信息
submit({...values, ...paginationParams, page: 1 })
```
后台查询中，操作人员经常刷新页面 导致当前页面信息丢失
能否增加查询参数url映射的hook

**Comment by brickspert** [comment]
> 但是还是存在无法手动组装RangePicker值的问题
> submit能否接受查询参数：
> 
> ```js-jsx
> // paginationParams 当前的分页信息
> submit({...values, ...paginationParams, page: 1 })
> ```
> 
> 后台查询中，操作人员经常刷新页面 导致当前页面信息丢失
> 能否增加查询参数url映射的hook

1. submit 这个提议不错，下个 feature 加下。
2. 查询参数url映射的 hook ，需要好好权衡下，应该是一个独立的 Hook。在 useAntdTable 中，你可以手动把 url 上的参数放到表单的 initialValue 里面。

**Comment by brickspert** [comment]
> 但是还是存在无法手动组装RangePicker值的问题
> submit能否接受查询参数：
> 
> ```js-jsx
> // paginationParams 当前的分页信息
> submit({...values, ...paginationParams, page: 1 })
> ```
> 
> 后台查询中，操作人员经常刷新页面 导致当前页面信息丢失
> 能否增加查询参数url映射的hook

我研究了下，其实 submit 是不用接受参数的，你可以在自己的 异步函数 中，来添加你需要的参数。
比如下图，你可以在这个函数中添加你的其它参数哦~
![image](https://user-images.githubusercontent.com/12526493/69143515-25318b00-0b04-11ea-9904-5ac1756d33ba.png)
