### ISSUE TITLE
useKeyPress绑定keyFilter冲突

### ISSUE THREAD

**Issue by ida-fe** [alibaba/hooks#1452]
复现：
使用useKeyPress绑定快捷键s和组合快捷键ctrl.s，当使用ctrl.s时，s事件也会触发
https://codesandbox.io/s/ji-chu-yong-fa-forked-xzejm?file=/App.tsx

预期：
使用ctrl.s时，只触发ctrl.s对应事件

**Comment by brickspert** [comment]
目前确实会有这样的问题，在监听普通键时，没有过滤修饰键，应该修复。
