### ISSUE TITLE
useRequest Conditional Fetching?

### ISSUE THREAD

**Issue by isaced** [alibaba/hooks#1454]
`useRequest` doesn't support conditional fetching like SWR?

> Use null or pass a function as key to conditionally fetch data. If the function throws or returns a falsy value, [SWR](https://swr.vercel.app/docs/conditional-fetching) will not start the request.

```
// conditionally fetch
const { data } = useSWR(shouldFetch ? '/api/data' : null, fetcher)
```

---

I got some error:

```
const { data } = useRequest(() => (value ? query(value) : null));  // ERROR: Type 'null' is not assignable to ...
```

**Comment by brickspert** [comment]
You should use the `options.ready` to do like this~
