### ISSUE TITLE
useLocalStorageState 设置初始值的时候不会将值同步到LocalStorage

### ISSUE THREAD

**Issue by kitety** [alibaba/hooks#1458]
useLocalStorageState 设置初始值的时候不会将值同步到LocalStorage（之前没有设置过这个key），只有在修改的时候才会同步。不知道是特意设置的还是存在的缺陷。

复现地址：https://190pj.csb.app/

**Comment by brickspert** [comment]
这个是预期行为。

参数叫 defaultValue 默认值，也就是 localstorage 里面没有数据时，使用默认值。
