### ISSUE TITLE
React native 项目中v2 升级到v3 之后，正常运行没有问题， fast refresh时会遇到原本声明的static 变量 undefined ，导致crash

### ISSUE THREAD

**Issue by kaizhou-lab** [alibaba/hooks#1475]

**Comment by brickspert** [comment]
能提供下具体的报错截图吗？

**Comment by yutianhaijiao** [comment]
`   
export default class ExchangeDataProvider {

 public static websocketManager: QuotationSocketMgr
`

![simulator_screenshot_C747BC75-91D4-4E7C-8EA4-07D1049F2897](https://user-images.githubusercontent.com/18323274/155681480-1513d106-1576-4220-97c5-10da3cdf63a1.png)

**Comment by yutianhaijiao** [comment]
`export default class ExchangeDataProvider {

 public static websocketManager: QuotationSocketMgr`

**Comment by kaizhou-lab** [comment]
`export default class ExchangeDataProvider {

 public static websocketManager: QuotationSocketMgr`
 
 
之后在 fast refresh 时候，websocketManager 为undefined
 
![simulator_screenshot_BD8D1745-9F47-4784-9246-6E0EB3F8A347](https://user-images.githubusercontent.com/18323274/155682178-a31fc25c-b8a1-46de-8373-0d505f362517.png)

**Comment by brickspert** [comment]
这个看不出来是 ahooks 的报错呀，能提供个最简代码复现吗？

**Comment by kaizhou-lab** [comment]
@brickspert 错误确实不在此，谢谢
