### ISSUE TITLE
useLongPress 增加松开时的回调

### ISSUE THREAD

**Issue by SuperHuangXu** [alibaba/hooks#1477]
业务中需要得到按键松开的事件。

**Comment by brickspert** [comment]
能描述具体的需求细节吗？

松开是指长按之后松开，还是点击之后松开呢？

**Comment by SuperHuangXu** [comment]
> 能描述具体的需求细节吗？
> 
> 松开是指长按之后松开，还是点击之后松开呢？

长按松开。

**Comment by brickspert** [comment]
那应该加一个 onLongPressEnd 类似名字的参数。

enEnd 太抽象了，不够形象。

**Comment by SuperHuangXu** [comment]
改成 `onLongPressEnd` 了 😊

**Comment by brickspert** [comment]
v3.1.11
