### ISSUE TITLE
useRequest 源码里面关于缓存的插件 useCachePlugin 里面 trigger 没有作用

### ISSUE THREAD

**Issue by superBigPotato** [alibaba/hooks#1479]
onSuccess: (data, params) => {
      if (cacheKey) {
        // cancel subscribe, avoid trigger self
        unSubscribeRef.current?.()
        _setCache(cacheKey, {
          data,
          params,
          time: new Date().getTime()
        })
        // resubscribe
        unSubscribeRef.current = cacheSubscribe.subscribe(cacheKey, d => {
          fetchInstance.setState({ data: d })
        })
      }
    },

const _setCache = (key: string, cachedData: CachedData) => {
    if (customSetCache) {
      customSetCache(cachedData)
    } else {
      cache.setCache(key, cacheTime, cachedData)
    }
    cacheSubscribe.trigger(key, cachedData.data)
  }
源码里面的 trigger 我看只有 onSuccess 和 onMutate 的时候 先执行unSubscribeRef.current?.() 取消监听之后再去执行_setCache触发，那触发就没有意义了呀，之后再重新监听，全局也没有找到其他trigger的地方，监听的意义在哪里呢

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/156144888-f6c575cf-2fc0-45a2-bc96-1181f65b68ad.png)


代码里面有相应的注释奥，避免触发自己
