### ISSUE TITLE
UseRequestProvider

### ISSUE THREAD

**Issue by lovesL** [alibaba/hooks#1481]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/27960630/156487236-2cf80765-e0a4-4f97-a1b8-3c0eb21ceb41.png">
  这个API  怎么没有了呀 有其他方面的API嘛

**Comment by brickspert** [comment]
v3 版本期望基于 useRequest 封装自己的 Hooks，来实现 UseRequestProvider 类似的公共配置的能力。

**Comment by lovesL** [comment]
> v3 版本期望基于 useRequest 封装自己的 Hooks，来实现 UseRequestProvider 类似的公共配置的能力。

要自己实现啊？

**Comment by brickspert** [comment]
> > v3 版本期望基于 useRequest 封装自己的 Hooks，来实现 UseRequestProvider 类似的公共配置的能力。
> 
> 要自己实现啊？

不是呀。。就是你稍微基于 useRequest 封装下.. 类似这样：

```js
const useCustomRequest = (service, options)=>{
   return useRequest(service, {
       ...options,
       debounceInterval: 1000
   })
};
```

**Comment by lovesL** [comment]
> > > v3 版本期望基于 useRequest 封装自己的 Hooks，来实现 UseRequestProvider 类似的公共配置的能力。
> > 
> > 
> > 要自己实现啊？
> 
> 不是呀。。就是你稍微基于 useRequest 封装下.. 类似这样：
> 
> ```js
> const useCustomRequest = (service, options)=>{
>    return useRequest(service, {
>        ...options,
>        debounceInterval: 1000
>    })
> };
> ```

  明白 明白  谢谢
