### ISSUE TITLE
defaultCurrent property in useAntdTable's defaultParams not work

### ISSUE THREAD

**Issue by programmer-yang** [alibaba/hooks#1483]
reproduce demo:
https://codesandbox.io/s/bold-wu-u6qkvg?file=/App.tsx

expect:
normal display default pagination

**Comment by brickspert** [comment]
Refer to this example：https://ahooks.js.org/hooks/use-antd-table#default-params

**Comment by xmsz** [comment]
useFusionTable因为是基于useAntTable 所以也不支持，需要用defaultParams。但是还是暴露了defaultCurrent这个属性，很容易忘记规则
