### ISSUE TITLE
[useReactive] Cannot read properties of undefined (reading 'xxx')

### ISSUE THREAD

**Issue by xXAvoraXx** [alibaba/hooks#1484]
I am trying to use it in useReactive ant design pro component model.

![errrrr](https://user-images.githubusercontent.com/6988989/156659915-bcaba8cc-a2e1-4c55-be39-66a15082a904.png)

**Comment by brickspert** [comment]
看着是 `this.tariffs` 报错的呀，没有 `this` 对象吧~

**Comment by xXAvoraXx** [comment]
> 看着是 `this.tariffs` 报错的呀，没有 `this` 对象吧~
yes 'this' doesn't occur, but that's how it's used here.
https://ahooks.js.org/hooks/use-reactive#computed-properties

**Comment by brickspert** [comment]
Can you provide an online demo?


https://codesandbox.io/s/bold-pike-bl5u2q?file=/App.tsx

**Comment by xXAvoraXx** [comment]
> Can you provide an online demo?
> 
> https://codesandbox.io/s/bold-pike-bl5u2q?file=/App.tsx

https://codesandbox.io/s/confident-haslett-n4ml2r?file=/App.tsx

**Comment by brickspert** [comment]
https://codesandbox.io/s/intelligent-gwen-iu58ix

You need to pay attention to what `this` points to.

```diff
useEffect(() => {
- getTariffs();
+  state.getTariffs(); 
}, [state.getTariffs]);
```

`state.getTariffs()`  this is state

`getTariffs` this is undefined

**Comment by xXAvoraXx** [comment]
I can't run the first function because it doesn't wait for data from initialState.

```
  const { initialState } = useModel('@@initialState');
  const { business } = initialState || {};

const state = useReactive({
    tariffs: [] as API.BusinessTariffListDto[],
    async getTariffs() {
      if (business?.businessId && this.tariffs.length === 0) {
        return await getRequestTariffs({ businessId: business.businessId }).then((t) => {
          message.info('hey');
          this.tariffs.push(...t!);
          return t;
        });
      } else {
        return this.tariffs;
      }
    });
// business?.businessId always undefined because useReactive does'nt re-render.
```
