### ISSUE TITLE
[QUESTION]useTable有没有办法一开始就设置table的sort值

### ISSUE THREAD

**Issue by xmsz** [alibaba/hooks#1493]
背景
- 我有个sort的初始值
- 然后我希望有地方可以赋值table的sort值，实现进入页面的时候就显示排序的图标
- 现在没办法显示是因为，tableProps里并没有sorter的值，或者说table里的sorter的值是不受控的，所以我不知道怎么修改

**Comment by brickspert** [comment]
参考这个 demo：https://codesandbox.io/s/red-night-u1zyhv

**Comment by xmsz** [comment]
> 

我看是通过sortOrder来实现默认显示
然后我用的是fusion好像没有这个属性

相当于如果我要实现这样的修改就需要自己维护order的感觉

**Comment by brickspert** [comment]
> > 
> 
> 我看是通过sortOrder来实现默认显示 然后我用的是fusion好像没有这个属性
> 
> 相当于如果我要实现这样的修改就需要自己维护order的感觉

功能都是类似的，只是 sortOrder 的格式可能不太一样。
