### ISSUE TITLE
setState里面执行useRequest居然会被执行两次

### ISSUE THREAD

**Issue by laolaolulu** [alibaba/hooks#1495]
const [test, setTest] = useState(0);
 const { loading: edityytime, run: YuYueTime } = useRequest(park.order.setYuYueTime, {
    manual: true,
    onSuccess: () => {
      openUpdateModal(0);
      ref.current?.reload();
    },
  });

//触发一次
 setTest((s) => {
              console.log('edit');
              YuYueTime(updateModalVisible, value.aid, value.time);
              return 0;
            });

结果输出了两次 console.log('edit');

**Comment by brickspert** [comment]
`loading` 先变成 `true` ，再变成 `false`，所以会有两次 `render`。

你需要搞清楚函数组件在什么时候会重新 `render`~

**Comment by laolaolulu** [comment]
> `loading`先变成`true`，再变成`false`，所以会有两次`render`。
> 
> 你需要清楚的在什么时候重新开始`render`~

并不是render导致的执行两次? 而是setTest里面执行了2次,如果我用延迟函数去执行useRequest就不会执行2次

**Comment by brickspert** [comment]
你的代码不是每次 render 都会调用 `setTest()` 么。

**Comment by laolaolulu** [comment]
> 你的代码不是每次 render 都会调用 `setTest()` 么。

不是,我的setTest是在一个按钮事件中执行

**Comment by brickspert** [comment]
建议提供一个在线复现。

你提问的代码，确实看不出来是点击执行的。。

**Comment by laolaolulu** [comment]
const [test, setTest] = useState(0);
const { loading: edityytime, run: YuYueTime } = useRequest(park.order.setYuYueTime, {
manual: true,
onSuccess: () => {
openUpdateModal(0);
ref.current?.reload();
},
});

useEffect(() => {
setTest((s) => {
console.log('edit');
YuYueTime(updateModalVisible, value.aid, value.time);
return 0;
});
},[]);

结果输出了两次 console.log('edit');

不好意思,这样描述行吗?

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/157366241-ba5ee193-1317-4010-bdb3-3bffd2629edd.png)

点这里，在 codesandbox 给一个复现

**Comment by laolaolulu** [comment]
https://github.com/facebook/react/issues/24057

**Comment by crazylxr** [comment]
你这个demo 我看了，确实是会执行两次。不过 你这个写法是有问题的，你如果想在 test 发生变化的时候去执行 YuYueTime这个函数，你应该这样去做：
```javascript

useEffect(() => {
  YuYueTime(updateModalVisible, value.aid, value.time);
}, [test])
```

**Comment by laolaolulu** [comment]
> 你这个demo 我看了，确实是会执行两次。不过 你这个写法是有问题的，你如果想在 test 发生变化的时候去执行 YuYueTime这个函数，你应该这样去做：
> 
> ```js
> useEffect(() => {
>   YuYueTime(updateModalVisible, value.aid, value.time);
> }, [test])
> ```

谢谢您! react的问题;  我的实际需求是一个事件触发useRequest去读取数据,而事件闭包导致useEffect读取不到state值,所以我利用的setState里面的函数值就能读取到state;;;我尝试加了个延迟函数去执行useRequest就只会执行一次了,我也不知道是否是react的bug还是我确实不太懂hooks的基础

**Comment by xiaocode337317439** [comment]
> > 你这个demo 我看了，确实是会执行两次。不过 你这个写法是有问题的，你如果想在 test 发生变化的时候去执行 YuYueTime这个函数，你应该这样去做：
> > ```js
> > useEffect(() => {
> >   YuYueTime(updateModalVisible, value.aid, value.time);
> > }, [test])
> > ```
> 
> 谢谢您! react的问题; 我的实际需求是一个事件触发useRequest去读取数据,而事件闭包导致useEffect读取不到state值,所以我利用的setState里面的函数值就能读取到state;;;我尝试加了个延迟函数去执行useRequest就只会执行一次了,我也不知道是否是react的bug还是我确实不太懂hooks的基础

<React.StrictMode> 这个标签会在dev环境下 useEffect 执行两次，这是react用来检查 hooks是潜在警告，正式环境不会生效
