### ISSUE TITLE
ahooks@3.x usePagination 支持ssr

### ISSUE THREAD

**Issue by wkeylin** [alibaba/hooks#1496]
在ssr 模式下，服务端会先请求一页数据，然后客户端进行同构渲染，此时不需要usePagination自动执行或者useEffect中进行run, 但是usePagination 不支持默认的pagination初始化，无法将服务端已经请求的数据给usePagination, 导致在Pagination 组件中onChange时，点击任何页面都是pageNo都是1

**Comment by brickspert** [comment]
`usePagination ` 支持支持默认 pagination 的，参考：https://ahooks.js.org/zh-CN/hooks/use-antd-table#%E5%88%9D%E5%A7%8B%E5%8C%96%E6%95%B0%E6%8D%AE
