### ISSUE TITLE
为啥要移除掉formatResult呢？

### ISSUE THREAD

**Issue by SH748** [alibaba/hooks#1497]
3.X为啥要移除掉formatResult呢？格式化的需求有问题嘛？没有问题。所以，为什么要移出掉格式化呢？这样还要去维护一个state，这多麻烦啊。

**Comment by brickspert** [comment]
Relation: https://github.com/alibaba/hooks/issues/1356#issuecomment-989787593

formatResult 会导致 useRequest 的 ts 重载，非常难维护和继承。

**Comment by fangqibin** [comment]
我也是遇到这个问题，formatResult移除之后变的好麻烦啊，你是怎么解决了，可以贴一下代码吗

**Comment by brickspert** [comment]
> 我也是遇到这个问题，formatResult移除之后变的好麻烦啊，你是怎么解决了，可以贴一下代码吗


service 返回最终格式的数据就 OK 了吧~

```ts
const { data } = useRequest(()=>{
    const res = request();
    return res.data;
});
```

**Comment by Valar103769** [comment]
> 
需要使用antv/data-set 来格式化数据,放到service里不好吧
