### ISSUE TITLE
使用runAsync并行请求的问题

### ISSUE THREAD

**Issue by liuwei1025** [alibaba/hooks#1498]
看到`Fetch`的实现中使用`this.count === currentCount`判断是否是取消了请求，这样会导致`runAsync`并行请求时 只有最后一个请求可以是`fulfilled`的，之前的请求都会是`pending` 状态，感觉和直观是不相符的；且返回一直`pending`的`Promise`是否是一种内存泄漏呢？

[示例](https://codesandbox.io/s/demo-for-ahooks-forked-45ce3v?file=/src/App.js)  可以打开devTool查看打印结果

**Comment by brickspert** [comment]
useRequest 默认是会有竞态处理的，也就是只有最后一个请求才会响应，之前的请求都会被废弃掉。

因为 Promise 是不能中止的，所以目前的方案就是「挂起」，也就是一直处于 pending 状态。 目前没有其它好的解决方案~

**Comment by liuwei1025** [comment]
> useRequest 默认是会有竞态处理的，也就是只有最后一个请求才会响应，之前的请求都会被废弃掉。
> 
> 因为 Promise 是不能中止的，所以目前的方案就是「挂起」，也就是一直处于 pending 状态。 目前没有其它好的解决方案~

为什么需要有竞态处理呢？

**Comment by brickspert** [comment]
> > useRequest 默认是会有竞态处理的，也就是只有最后一个请求才会响应，之前的请求都会被废弃掉。
> > 因为 Promise 是不能中止的，所以目前的方案就是「挂起」，也就是一直处于 pending 状态。 目前没有其它好的解决方案~
> 
> 为什么需要有竞态处理呢？

举个简单的例子

```js
const { data, run } = useRequest(()=> fetch('xxx'));

run(1);
run(2);
run(3);
```

连续发出三个请求，那最后 `data` 是用的第几次发出去的请求结果呢？

如果有竞态，那就是用的第三个。
如果没有竞态，那就用的是最后返回的请求。这个是不可控的。

**Comment by liuwei1025** [comment]
> > > useRequest 默认是会有竞态处理的，也就是只有最后一个请求才会响应，之前的请求都会被废弃掉。
> > > 因为 Promise 是不能中止的，所以目前的方案就是「挂起」，也就是一直处于 pending 状态。 目前没有其它好的解决方案~
> > 
> > 
> > 为什么需要有竞态处理呢？
> 
> 举个简单的例子
> 
> ```js
> const { data, run } = useRequest(()=> fetch('xxx'));
> 
> run(1);
> run(2);
> run(3);
> ```
> 
> 连续发出三个请求，那最后 `data` 是用的第几次发出去的请求结果呢？
> 
> 如果有竞态，那就是用的第三个。 如果没有竞态，那就用的是最后返回的请求。这个是不可控的。

**Comment by liuwei1025** [comment]
我觉得应该提供一种纯函数的场景，在传递了manual的场景下，返回的函数 `run` `runAsync`都可以按照纯函数的形式运行；如果你们感兴趣的话，我可以尝试提供一个PR

**Comment by liuwei1025** [comment]
如果处理竞态的话，`run`,`runAsync`等方法感觉就完全被限制在了需要使用`data`的场景下

**Comment by brickspert** [comment]
暂时不会调整这个逻辑，属于 break change 了~~

**Comment by crazyair** [comment]
@crazylxr  关于这个`因为 Promise 是不能中止的，所以目前的方案就是「挂起」，也就是一直处于 pending 状态。 目前没有其它好的解决方案~`
目前是用 count 计数，是不是可以用 list 缓存 promise，如果 length 不等，则 return 最后一次 promise，保证返回始终是最后的 promise，也没有内存泄露问题

**Comment by crazylxr** [comment]
> @crazylxr 关于这个`因为 Promise 是不能中止的，所以目前的方案就是「挂起」，也就是一直处于 pending 状态。 目前没有其它好的解决方案~` 目前是用 count 计数，是不是可以用 list 缓存 promise，如果 length 不等，则 return 最后一次 promise，保证返回始终是最后的 promise，也没有内存泄露问题

感觉可以，v4 的时候仔细思考一下
