### ISSUE TITLE
useDebounceEffect

### ISSUE THREAD

**Issue by KeithChou** [alibaba/hooks#1501]
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/18112461/158013983-7baa9c4d-3793-423e-98d7-7b1a3c830971.png">
请教一个问题，这里我看v3的yuan m源码使用的是useDebounceFn, 而该hook内部使用的是lodash/debounce。这里是不是少了一个maxWait最大等待时间的参数？

**Comment by brickspert** [comment]
文档是少了 maxWait，欢迎 PR
