### ISSUE TITLE
ahook跟umijs/hooks是什么关系

### ISSUE THREAD

**Issue by fangqibin** [alibaba/hooks#1502]
ahook跟umijs/hooks是什么关系，我之前都是用umijs/hooks，文档打不开了，什么原因呢。

**Comment by brickspert** [comment]
暂时先看下 v1.x 的 md 文件吧：https://github.com/alibaba/hooks/tree/release/v1.x

**Comment by fangqibin** [comment]
> 暂时先看下 v1.x 的 md 文件吧：https://github.com/alibaba/hooks/tree/release/v1.x

文档打不开，这个是强制要升级到v3吗，有时候想看一下参数，很不方便。

**Comment by LukerSpringtree** [comment]
ahook 新版本;
umijs/hooks 老版本;

**Comment by fangqibin** [comment]
> ahook 新版本; umijs/hooks 老版本;

我看版本不太兼容啊

**Comment by crazylxr** [comment]
大版本不兼容不是很正常么，umijs/hooks 是 ahooks 1 了，现在 ahooks 已经到 3 了
