### ISSUE TITLE
useControllableState不支持函数式更新

### ISSUE THREAD

**Issue by mraiguo** [alibaba/hooks#1505]
不支持 setState 函数参数
> https://codesandbox.io/s/usecontrollablevaluewu-fa-han-shu-shi-geng-xin-u5qlie?file=/App.tsx

**Comment by daixiongsheng** [comment]
useControllableValue 目前不支持入参为函数

**Comment by daixiongsheng** [comment]
> useControllableValue 目前不支持入参为函数

需要这样使用
<img width="522" alt="image" src="https://user-images.githubusercontent.com/28498805/160644388-306f1fd2-cd14-4668-92d3-cfb12bfb6b99.png">

**Comment by crazylxr** [comment]
已经解决了，close 了
