### ISSUE TITLE
useRequest发起多个请求

### ISSUE THREAD

**Issue by wikiNed** [alibaba/hooks#1506]
在一个页面里面，需要请求多种数据并且部分数据存在依赖，请问怎么使用useRequest来达到目的。

**Comment by brickspert** [comment]
假设需要先请求 A，成功后再请求 B，有两种方案：
1. 请求 A 之后，在 onSuccess 中调用 b.run 来执行 B
2. 通过配置 b.options.ready 参数来控制 B 什么时候请求
