### ISSUE TITLE
usePagination 应该缓存 total 字段

### ISSUE THREAD

**Issue by liuweiGL** [alibaba/hooks#1514]
## 场景
假如一个接口在第 3 次调用时失败了，期望的展示效果应该是分页仍然在，仅仅是 table 展示为空数据。

## 问题
目前的 total 每次都从 result 里面重新取值，会因为某一次的请求失败而破坏分页：
```ts
  const total = result.data?.total || 0;
  const totalPage = useMemo(() => Math.ceil(total / pageSize), [pageSize, total]);
```

## 方案
应该把请求成功的 total 缓存起来，当请求失败时使用上一次的 total 值。

**Comment by brickspert** [comment]
建议自行在业务层面处理，`usePagination` 不应该吃这种逻辑的。

**Comment by liuweiGL** [comment]
这个逻辑跟业务无关吧？hook 内部如果不加这个处理，返回结果按常理来讲是错的。

**Comment by brickspert** [comment]
对于 usePagination 来说，有一个要求，就是 service 返回的数据格式必须为 `{total: number, list: any[]}`。

在使用时，应该保证任何时候 service 返回的数据结构是符合期望的。

你需要在数据结构不符合的时候，缓存 total，但不是所有人都会有这种诉求。
