### ISSUE TITLE
Remove cyclic dependencies from v3

### ISSUE THREAD

**Issue by francois-pasquier** [alibaba/hooks#1517]
Starting with v3.0.0, cyclic dependencies have been introduced.
example commit: https://github.com/alibaba/hooks/commit/32ace8703f68f43d371bdcf9b3edece09d2b82e4
See:  `import { useRafState } from '..';`

e.g: 
```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/ahooks/lib/index.js -> node_modules/ahooks/lib/useScroll/index.js -> node_modules/ahooks/lib/index.js
```

These add a lot of noise...

**Comment by brickspert** [comment]
Fixed on v3.1.14
