### ISSUE TITLE
useKeyPress能否添加useCapture属性

### ISSUE THREAD

**Issue by Kido-200** [alibaba/hooks#1520]

**Comment by crazylxr** [comment]
useCapture 用来干啥的

**Comment by Kido-200** [comment]
捕获阶段调用
比如react-view这组件库自己支持键盘事件，他在捕获阶段调用，还用了stoppropogation，导致我用useKeyPress的事件会触发不了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/hooks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月27日(星期天) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/hooks] useKeyPress能否添加useCapture属性 (Issue #1520)





 
useCapture 用来干啥的

**Comment by crazylxr** [comment]
感觉可以，欢迎 pr

**Comment by liuyib** [comment]
这个 issue 对应的 PR 已经合并了：https://github.com/alibaba/hooks/pull/1911, 感觉 issue 可以关了 @crazylxr
