### ISSUE TITLE
[RFC] useRafInterval

### ISSUE THREAD

**Issue by lihongxun945** [alibaba/hooks#1522]
新增 `useRafInterval` ，用 `requestAnimationFrame` 代替 `setInterval` ，以实现更好的性能。
在node环境下自动降级成 `setInterval` 实现。

PR 已发：https://github.com/alibaba/hooks/pull/1521

## API
```typescript
useRafInterval(
  fn: () => void,
  delay: number | undefined,
  options?: {
    immediate?: boolean;
  },
)
```

## 用法示例
```typescript
useRafInterval(() => {
  setCount(count + 1);
}, 1000);
```

**Comment by brickspert** [comment]
Released in v3.2.0!
