### ISSUE TITLE
增加useWebSocket 新特性，可以改变websocketUrl 而不重复渲染

### ISSUE THREAD

**Issue by LoveEocding** [alibaba/hooks#1523]
### 使用场景
目前有个使用场景是，在当前页面可以切换url,目前使用useWebSocket时，会出现切换第二个实例之后，第一个会在关闭回调中继续reconnect，这样就会导致两个websocket链接不断改变状态，不断重复链接。
<img width="437" alt="image" src="https://user-images.githubusercontent.com/29218661/160356361-036fe646-a5eb-4515-a785-4f9a53523643.png">
### 需求
希望增加一个新的feature 支持这种切换场景，也保留断掉重试机制

**Comment by liuyib** [comment]
fixed by: https://github.com/alibaba/hooks/pull/2177
