### ISSUE TITLE
Memoized是否拼写错误？

### ISSUE THREAD

**Issue by huangshiqiang** [alibaba/hooks#1533]

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/160960807-ad635c6a-6e5d-4f89-b5cf-0beaa26b08c7.png)

![image](https://user-images.githubusercontent.com/12526493/160960816-f7852cdc-3f5a-463f-ae07-c237a54b0163.png)


没有拼写错误哦~
