### ISSUE TITLE
useAntdTable的search.submit入参丢失的bug

### ISSUE THREAD

**Issue by cqhaisenbao** [alibaba/hooks#1535]
useAntdTable的search.submit到底对参数做了什么？为什么请求发出的参数和实际Form拿到的数据比，少了一个？

**Comment by cqhaisenbao** [comment]
`
import { Form, Input } from "antd";
import { useAntdTable } from "ahooks";

const MyInput = () => {
	return <Input />;
};

const Test = () => {
	const [form] = Form.useForm();
	const { search } = useAntdTable(getInnerOrderMatchedList, {
		form,
	});
	return (
		<>
			<Form form={form}>
				<Form.Item label="姓名" name={"name"}>
					<Input placeholder="请输入姓名" />
				</Form.Item>
				<Form.Item label="年龄" name={"age"}>
					<MyInput />
				</Form.Item>
			</Form>
			<button onClick={() => {
				console.log(form.getFieldsValue());  //这里打印出来包括name和age
				search.submit(form.getFieldsValue());  //getInnerOrderMatchedList打印出来的参数只有name
			}}>show
			</button>
		</>
	);
};

export default Test;
`

**Comment by cqhaisenbao** [comment]
这是Demo代码，Form.Item里是自定义组件会出现这个bug
![企业微信截图_16487178533856](https://user-images.githubusercontent.com/69225950/161016395-99e3a2b6-129c-4e06-a8b8-6cb2bd7358b5.png)

**Comment by brickspert** [comment]
1. 可以提供个在线复现吗？官方 demo 是没有问题的。
2. `search.submit` 应该是不能接收参数的

`search.submit` 就是调用了 `form.getFiledsValue`，然后忽略了不显示的 Form 字段。

**Comment by brickspert** [comment]
自定义组件的话，参考下这个：https://github.com/alibaba/hooks/issues/496

**Comment by cqhaisenbao** [comment]
> 

66666，用forwardRef把自定义组件包起来就可以了
