### ISSUE TITLE
useVirtualList里的overscan属性设置为0时，第一条数据不会渲染

### ISSUE THREAD

**Issue by LCzxy** [alibaba/hooks#1538]

**Comment by LCzxy** [comment]
useVirtualList里的overscan属性设置为0时，第一条数据不会渲染

**Comment by coder-lcn** [comment]
已经解决了？咋不 close 掉呀

**Comment by crazylxr** [comment]
> 已经解决了？咋不 close 掉呀

还没呢！pr 见 #1548

**Comment by Pulset** [comment]
> > 已经解决了？咋不 close 掉呀
> 
> 还没呢！pr 见 #1548
我把可视区域展示的list数量方法改了，应该可以解决这个问题和1548里的那个问题

**Comment by JX-Zhuang** [comment]
需要解决吗

**Comment by Pulset** [comment]
@brickspert @crazylxr 帮忙review下代码
