### ISSUE TITLE
useFusionTable 每次使用search.submit( )页码就回到第一页了 

### ISSUE THREAD

**Issue by angentle** [alibaba/hooks#1540]
出现场景如下，使用useFusionTable 结合搜索框和table以及pagination时，当用户翻页到第N页（非第一页）时，对table某一栏数据修改的操作，这时请求seach.submit() 自动回到第一页了。

期望结果： 对第N页的table数据进行操作，使用seach.submit() ，页面停留在第N页。

问题代码如下：
![image](https://user-images.githubusercontent.com/20704660/161374829-3567dd27-b203-40be-b826-035b3680258e.png)

**Comment by brickspert** [comment]
这个是预期行为，在搜索条件变更后，是会重置到第一页的。

考虑：比如现在在第十页，变更了搜索条件后，可能一共只有两页，那如果还停留在第十页肯定有问题的。所以重置到第一页才是普遍场景。

**Comment by dongliang1993** [comment]
> 这个是预期行为，在搜索条件变更后，是会重置到第一页的。
> 
> 考虑：比如现在在第十页，变更了搜索条件后，可能一共只有两页，那如果还停留在第十页肯定有问题的。所以重置到第一页才是普遍场景。

不一定吧？比如有一个场景需要前端轮训后端接口，我需要每隔一段时间调用 submit 函数来查询表格数据，这个时候因为内部会重置 current ，会出现用户在【非第一页但是突然跳回第一页】的情况。
感觉重置翻页是不是有一个 setPagination 会更好一些呢？

**Comment by brickspert** [comment]
> 

这个场景你应该用 refresh 的，而不是用 submit~

**Comment by dongliang1993** [comment]
useAntdTable 、useFusionTable 暴露出没有 refresh api 出来

**Comment by dongliang1993** [comment]
useAntdTable 、useFusionTable 没有暴露出 refresh api 出来

**Comment by brickspert** [comment]
> 

https://ahooks.js.org/zh-CN/hooks/use-request/basic#%E5%88%B7%E6%96%B0%E9%87%8D%E5%A4%8D%E4%B8%8A%E4%B8%80%E6%AC%A1%E8%AF%B7%E6%B1%82

有的，只是是 useRequest 的 API，所以在 useAntdTable 、useFusionTable 没有单独写。

**Comment by dongliang1993** [comment]
好的，谢谢~~

**Comment by cixiangtao** [comment]
> > 
> 
> https://ahooks.js.org/zh-CN/hooks/use-request/basic#%E5%88%B7%E6%96%B0%E9%87%8D%E5%A4%8D%E4%B8%8A%E4%B8%80%E6%AC%A1%E8%AF%B7%E6%B1%82
> 
> 有的，只是是 useRequest 的 API，所以在 useAntdTable 、useFusionTable 没有单独写。

建议补充道文档中，这个需求还是挺常用的，特别是在编辑操作中，需要刷新当前页码。我翻了好久才翻到这条issues

**Comment by liuyib** [comment]
> > > 
> > 
> > 
> > https://ahooks.js.org/zh-CN/hooks/use-request/basic#%E5%88%B7%E6%96%B0%E9%87%8D%E5%A4%8D%E4%B8%8A%E4%B8%80%E6%AC%A1%E8%AF%B7%E6%B1%82
> > 有的，只是是 useRequest 的 API，所以在 useAntdTable 、useFusionTable 没有单独写。
> 
> 建议补充道文档中，这个需求还是挺常用的，特别是在编辑操作中，需要刷新当前页码。我翻了好久才翻到这条issues

来个 PR？改善下文档~ @Mrcxt

**Comment by liuyib** [comment]
> > > 
> > 
> > 
> > https://ahooks.js.org/zh-CN/hooks/use-request/basic#%E5%88%B7%E6%96%B0%E9%87%8D%E5%A4%8D%E4%B8%8A%E4%B8%80%E6%AC%A1%E8%AF%B7%E6%B1%82
> > 有的，只是是 useRequest 的 API，所以在 useAntdTable 、useFusionTable 没有单独写。
> 
> 建议补充道文档中，这个需求还是挺常用的，特别是在编辑操作中，需要刷新当前页码。我翻了好久才翻到这条issues

其实文档里有写到：

<img width="1032" alt="image" src="https://github.com/alibaba/hooks/assets/38221479/da1cc986-b536-4381-8f26-85b8930d0078">

---

antd 的文档也是类似的，共享的 api 只在一个地方写了：

<img width="784" alt="image" src="https://github.com/alibaba/hooks/assets/38221479/2ad9c070-f8c5-49d6-8279-525ae1daee60">
<img width="641" alt="image" src="https://github.com/alibaba/hooks/assets/38221479/a1b0f771-edb1-4a6c-b937-9fa625c12d28">
