### ISSUE TITLE
[RFC] useMutationObserver

### ISSUE THREAD

**Issue by hesterrk** [alibaba/hooks#1542]
API
```typescript
function useMutationObserver(
  targetEl: Node | null,
  config: MutationObserverInit,
  onElMutation: MutationCallback,
)<T>(fn: T): T
```
Demo
```typescript
  const onTitleElMutation: MutationCallback = (mutationList, observer) => {
    const prevTitleVal = mutationList[0].removedNodes[0].nodeValue
    if (prevTitleVal !== document.title) {
      document.title = prevTitleVal ? prevTitleVal : '' 
      if (observer) observer.disconnect()
    }
  }
  const titleEl = document.querySelector('title')
  useMutationObserver(titleEl, { childList: true }, onTitleElMutation)
```

**Comment by brickspert** [comment]
```ts
function useMutationObserver(
  target: Element | (() => Element) | MutableRefObject<Element>,
  callback: MutationCallback,
  options?: MutationObserverInit,
)
```

API should like this: 

1. target support `ref` or `Element`
2. options is optional

**Comment by brickspert** [comment]
Welcome your PR~

**Comment by daixiongsheng** [comment]
> ```ts
> function useMutationObserver(
>   target: Element | (() => Element) | MutableRefObject<Element>,
>   callback: MutationCallback,
>   options?: MutationObserverInit,
> )
> ```
> 
> API should like this:
> 
> 1. target support `ref` or `Element`
> 2. options is optional

when the target observed by instance of MutationObserver the 'observe' API need an options that must set at least one of 'attributes', 'characterData', or 'childList' to true

so API should like this:
```ts
function useMutationObserver(
  target: Element | (() => Element) | MutableRefObject<Element>,
  callback: MutationCallback,
  options: MutationObserverInit,
)
```

**Comment by daixiongsheng** [comment]
Has any contributor for this ?

**Comment by brickspert** [comment]
I think it should have a default value, so options is optional.

@hesterrk are you working for it?

**Comment by hesterrk** [comment]
Sure, I agree with the the feedback and will amend, and yes I am
