### ISSUE TITLE
feat: export metadata about all hooks

### ISSUE THREAD

**Issue by Jungzl** [alibaba/hooks#1551]
If you can provide metadata information just like @vueuse, we can maintain a preset config to auto import ahooks

**Comment by antfu** [comment]
For the context, here is how we do it in VueUse https://unpkg.com/browse/@vueuse/metadata@8.2.5/index.json

Auto import using that metadata
https://github.com/antfu/unplugin-auto-import/blob/main/src/presets/vueuse-core.ts

**Comment by brickspert** [comment]
publish in v3.3.2

**Comment by Jungzl** [comment]
> publish in v3.3.2

seems like there is no new version on [npm](https://www.npmjs.com/package/ahooks)

**Comment by brickspert** [comment]
> 

sorry, [3.3.8](https://www.npmjs.com/package/ahooks/v/3.3.8) is work~

**Comment by Jungzl** [comment]
whoa, that's a lot patch version bump

**Comment by brickspert** [comment]
> whoa, that's a lot patch version bump

hhh, I just got a new computer and the environment is not configured properly~~
