### ISSUE TITLE
useFormTable新安装依赖会导致查询项失效

### ISSUE THREAD

**Issue by qwq706040690** [alibaba/hooks#1554]
useFormTable重新安装node moudules会导致查询项失效

**Comment by qwq706040690** [comment]
查询项被重置,老的node modules没问题

**Comment by brickspert** [comment]
useFormTable? 没有这个 Hooks 呀~

**Comment by qwq706040690** [comment]
> 使用表格？没有这个 Hooks 呀~

import { useFormTable } from '@umijs/hooks';



包版本 "@umijs/hooks": "^1.9.2",

**Comment by qwq706040690** [comment]
> 使用表格？没有这个 Hooks 呀~

 "@umijs/hooks": "^1.9.2",umi-hooks文档页面404了,是完全弃用了吗

**Comment by brickspert** [comment]
umi-hooks 的文档是挂掉了。暂时可以在[这里](https://github.com/alibaba/hooks/blob/release/v1.x/packages/hooks/src/useFormTable/index.zh-CN.md)看文档.

然后这个库已经好久没动了，我估计是其它 antd 等库的升级导致的？最好提供一个复现，或者本地锁一下 antd 版本试试。

**Comment by qwq706040690** [comment]
> umi-hooks 的文档是挂掉了。暂时可以在[这里](https://github.com/alibaba/hooks/blob/release/v1.x/packages/hooks/src/useFormTable/index.zh-CN.md)看文档.
> 
> 然后这个库已经好久没动了，我估计是其它 antd 等库的升级导致的？最好提供一个复现，或者本地锁一下 antd 版本试试。
    "@ant-design/pro-layout": "5.0.14",
    "@umijs/hooks": "^1.9.2",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "3.1.4",
    "axios": "^0.21.1",
    "cross-env": "^7.0.3",
    "crypto-js": "^4.0.0",
    "file-saver": "^2.0.5",
    "immutability-helper": "^3.1.1",
    "js-md5": "^0.7.3",
    "lint-staged": "^10.0.7",
    "mathjs": "^9.4.4",
    "pdfobject": "^2.1.1",
    "prettier": "^1.19.1",
    "qrcode.react": "^1.0.1",
    "quill-image-drop-module": "^1.0.3",
    "react": "^16.12.0",
    "react-amap": "^1.2.8",
    "react-color": "^2.19.3",
    "react-copy-to-clipboard": "^5.0.4",
    "react-dnd": "^11.1.3",
    "react-dnd-html5-backend": "^11.1.3",
    "react-dom": "^16.12.0",
    "react-infinite-scroll-component": "^6.1.0",
    "react-quill": "^1.3.5",
    "react-virtualized": "^9.22.2",
    "solarday2lunarday": "^1.10.1",
    "umi": "^3.1.4",
版本一直都是这个版本,老的本地项目是没问题的,git上拉下来的代码yarn完有搜索项点完被置空,无效的问题

**Comment by qwq706040690** [comment]
> umi-hooks 的文档是挂掉了。暂时可以在[这里](https://github.com/alibaba/hooks/blob/release/v1.x/packages/hooks/src/useFormTable/index.zh-CN.md)看文档.
> 
> 然后这个库已经好久没动了，我估计是其它 antd 等库的升级导致的？最好提供一个复现，或者本地锁一下 antd 版本试试。

![image](https://user-images.githubusercontent.com/31041082/163397503-385ebb39-9999-43c6-b424-55b906468fd0.png)

search.submit()  表单里是有传值的,在源码里打断点,到这一步获取到的所有值都是undefined

**Comment by qwq706040690** [comment]
> > umi-hooks 的文档是挂掉了。暂时可以在[这里](https://github.com/alibaba/hooks/blob/release/v1.x/packages/hooks/src/useFormTable/index.zh-CN.md)看文档.
> > 然后这个库已经好久没动了，我估计是其它 antd 等库的升级导致的？最好提供一个复现，或者本地锁一下 antd 版本试试。
> 

> 
> search.submit() 表单里是有传值的,在源码里打断点,到这一步获取到的所有值都是undefined
![image](https://user-images.githubusercontent.com/31041082/163401075-f116e751-c133-417e-b739-d8556702a0d1.png)

**Comment by brickspert** [comment]
> > > umi-hooks 的文档是挂掉了。暂时可以在[这里](https://github.com/alibaba/hooks/blob/release/v1.x/packages/hooks/src/useFormTable/index.zh-CN.md)看文档.
> > > 然后这个库已经好久没动了，我估计是其它 antd 等库的升级导致的？最好提供一个复现，或者本地锁一下 antd 版本试试。
> 
> > search.submit() 表单里是有传值的,在源码里打断点,到这一步获取到的所有值都是undefined
> > ![image](https://user-images.githubusercontent.com/31041082/163401075-f116e751-c133-417e-b739-d8556702a0d1.png)

你有安装 ant design 吗？我看你依赖里面没有？

你把 ant design 版本锁住试试。

**Comment by qwq706040690** [comment]
> > > > umi-hooks 的文档是挂掉了。暂时可以在[这里](https://github.com/alibaba/hooks/blob/release/v1.x/packages/hooks/src/useFormTable/index.zh-CN.md)看文档.
> > > > 然后这个库已经好久没动了，我估计是其它 antd 等库的升级导致的？最好提供一个复现，或者本地锁一下 antd 版本试试。
> > 
> > 
> > > search.submit() 表单里是有传值的,在源码里打断点,到这一步获取到的所有值都是undefined
> > > ![image](https://user-images.githubusercontent.com/31041082/163401075-f116e751-c133-417e-b739-d8556702a0d1.png)
> 
> 你有安装 ant design 吗？我看你依赖里面没有？
> 
> 你把 ant design 版本锁住试试。

**Comment by qwq706040690** [comment]
> > > > > umi-hooks 的文档是挂掉了。暂时可以在[这里](https://github.com/alibaba/hooks/blob/release/v1.x/packages/hooks/src/useFormTable/index.zh-CN.md)看文档.
> > > > > 然后这个库已经好久没动了，我估计是其它 antd 等库的升级导致的？最好提供一个复现，或者本地锁一下 antd 版本试试。
> > > 
> > > 
> > > > search.submit() 表单里是有传值的,在源码里打断点,到这一步获取到的所有值都是undefined
> > > > ![image](https://user-images.githubusercontent.com/31041082/163401075-f116e751-c133-417e-b739-d8556702a0d1.png)
> > 
> > 
> > 你有安装 ant design 吗？我看你依赖里面没有？
> > 你把 ant design 版本锁住试试。

请问下,应该锁哪个版本

**Comment by qwq706040690** [comment]
刚看了下本地没问题的antd版本是4.18.2 ,新装的的4.19.5有问题, yarn add antd@4.18.2 解决
