### ISSUE TITLE
useLongPress: Add option to trigger only if no significant touch/mousemove

### ISSUE THREAD

**Issue by uelibaumgartner** [alibaba/hooks#1559]
We have situation where we have swipe and long press functionality combined. We don't want to trigger the long press function when the user moves his finger to swipe. It would be great to have the option to not trigger the event if there was x-y movement above a certain threshold.

Would this be a viable feature for useLongPress?

P.S.: Really appreciate the library overall. It covers most common cases I encounter and has a really simple interface to interact with.

**Comment by crazylxr** [comment]
I think it's reasonable. don't you  @brickspert

**Comment by brickspert** [comment]
> I think it's reasonable. don't you @brickspert

Yes, we should add a config to ignore long press events when moving a specified distance.

This config is used to specify the distance.
