### ISSUE TITLE
[QUESTION] useReactive能否提供获取非响应式源数据的能力

### ISSUE THREAD

**Issue by yiescc** [alibaba/hooks#1562]
- 类似于vue toRefs()的能力

**Comment by yuzhanglong** [comment]
附议

**Comment by crazylxr** [comment]
暂时是不会提供了，这个  hook 未来甚至可能会移除，不太建议用

**Comment by yiescc** [comment]
> 暂时是不会提供了，这个 hook 未来甚至可能会移除，不太建议用

为什么会移除?

**Comment by crazylxr** [comment]
可能哈，还不确定，因为这个 hook 太不 react 了，不太建议用。

你是什么场景要用到响应式，而不是直接 setState ？

**Comment by yiescc** [comment]
> 可能哈，还不确定，因为这个 hook 太不 react 了，不太建议用。
> 
> 你是什么场景要用到响应式，而不是直接 setState ？

操作数组的时候，方便赋值

**Comment by crazylxr** [comment]
有实际的 例子么，发出来看一下，我看看不用 这个 hook ，有没有更好的方式。

**Comment by yiescc** [comment]
> 有实际的 例子么，发出来看一下，我看看不用 这个 hook ，有没有更好的方式。


就是数组的增删改查，每次都要拷贝一份，层级深的话就很麻烦
```
 const [list, setList] = useState<Array<{ id: number; name: string }>>([]);

  const update = useMemoizedFn((itemIdx: number, item: { id: number; name: string }) => {
    setList((pre) => {
      const next = [...pre];
      pre[itemIdx] = item;
      return next;
    });
  });
```

**Comment by crazylxr** [comment]
对于层级深的 数组或者对象的话，建议用 immer 这样的 immutable 库来解决会更容易一点哦

**Comment by crazylxr** [comment]
结论就是暂时不会考虑哈，issue 先关了，有需要再重新打开。

**Comment by lovelyJason** [comment]
> 可能哈，还不确定，因为这个 hook 太不 react 了，不太建议用。
> 
> 你是什么场景要用到响应式，而不是直接 setState ？

还是有一些场景吧。比如有很复杂的组件嵌套， 好多层级，一层层传递props和回调函数有点麻烦啊，使用React.context把这些相关组件包起来， 直接传一个引用类型的数据， 在后代组件中修改可以同步到所有这个组件

**Comment by yuzhanglong** [comment]
如果喜欢这种 “不 react 的” 写法可以用 mobx，使用起来也很简单，ahooks 支持这一系列能力可能有点太重了，哈哈。

> > 可能哈，还不确定，因为这个 hook 太不 react 了，不太建议用。
> > 你是什么场景要用到响应式，而不是直接 setState ？
> 
> 还是有一些场景吧。比如有很复杂的组件嵌套， 好多层级，一层层传递props和回调函数有点麻烦啊，使用React.context把这些相关组件包起来， 直接传一个引用类型的数据， 在后代组件中修改可以同步到所有这个组件
