### ISSUE TITLE
[BUG] useCounter 做了破坏性的变更，counterActions 是一个实时字面量对象

### ISSUE THREAD

**Issue by zjy01** [alibaba/hooks#1566]
useCounter
ahooks 2.x 版本的 actions 会使用 useMemo 进行包装。
ahooks 3.x 版本的 actions 直接返回了字面量对象

这是一个破坏性的变更，useEffect 依赖了该actions的话，有可能会导致系统崩溃
这个应该在 升级文档中 进行提示，或者重新进行封装。

**Comment by crazylxr** [comment]
你是什么场景会依赖 actions ？

**Comment by zjy01** [comment]
> 你是什么场景会依赖 actions ？

可以不依赖，但是如果放入了deps，升级就会产生问题

**Comment by crazylxr** [comment]
> > 你是什么场景会依赖 actions ？
> 
> 可以不依赖，但是如果放入了deps，升级就会产生问题

这个我们考虑下，issue 就暂时先关了哈。
