### ISSUE TITLE
强烈建议增加formatResult

### ISSUE THREAD

**Issue by zyanfly** [alibaba/hooks#1570]
新版删除了useRequest及其他的请求类的formatResult参数，感觉使用体验下降一大截啊，总觉得在services中写逻辑是不那么优雅

**Comment by brickspert** [comment]
formatResult 会导致 ts 的复杂度乘以一万，导致在基于 useRequest  做封装的时候，ts 无法复用。

useRequest 会消费 service 返回的最终数据，我觉得挺合理的。

**Comment by Lizhooh** [comment]
不能基于 infer 反推么？

**Comment by komagic** [comment]
@brickspert 作者，咱们都是工程师，考虑问题应该基于现有方法论，现状需求，而不是 feeling
