### ISSUE TITLE
useRequest

### ISSUE THREAD

**Issue by lovesL** [alibaba/hooks#1576]
### 问题
<img width="773" alt="image" src="https://user-images.githubusercontent.com/27960630/165419967-5af373fa-bb6a-4d44-916f-53ad44b788ae.png">

![image](https://user-images.githubusercontent.com/27960630/165420017-4e712694-deb7-4242-a325-c4b2d56a76b8.png)
咋个是 undefined 呀 专家

<img width="748" alt="image" src="https://user-images.githubusercontent.com/27960630/165420101-d2968329-9ba6-4f97-9467-538be95ff0d7.png">
  我用的是umi-request请求库
useRequest v2的版本 没问题

**Comment by brickspert** [comment]
用 `a.runAsync()`
