### ISSUE TITLE
v1和v2的文档网站都挂了。

### ISSUE THREAD

**Issue by zyanfly** [alibaba/hooks#1577]

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/165657557-0f4c9c87-aa04-41cd-93e9-a77674d9d61b.png)


v2 可以访问的

**Comment by zyanfly** [comment]
> ![image](https://user-images.githubusercontent.com/12526493/165657557-0f4c9c87-aa04-41cd-93e9-a77674d9d61b.png)
> 
> v2 可以访问的

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/26576825/165668722-08222c2c-f174-4d69-af75-7a215efa4cd2.png">

**Comment by zyanfly** [comment]
白屏

**Comment by zyanfly** [comment]
v2的官网证书过期了

**Comment by RoamingTheUniverse** [comment]
v1 和 v2 官网都挂了，还是麻烦修复一下吧
v1 官网：
![image](https://user-images.githubusercontent.com/42606107/165908466-d17def48-56ab-4ed2-939d-3bf5606951ff.png)
v2 官网：
![image](https://user-images.githubusercontent.com/42606107/165908570-bebab9b4-9bbc-4ab1-ad86-899971bf4a35.png)

**Comment by brickspert** [comment]
不用 chrome 就能访问。我看看怎么修下。

**Comment by brickspert** [comment]
v2 的修好了：https://ahooks-v2.js.org/

贫穷让我只能用免费的静态站点服务器，免费的又不好用。唉~~
