### ISSUE TITLE
Ready由false变为true时，第一次返回的loading是false

### ISSUE THREAD

**Issue by guichch** [alibaba/hooks#1578]

**Comment by crazylxr** [comment]
麻烦详细描述一下问题呢。

**Comment by guichch** [comment]
刚进入页面时请求一个接口，但是ready是false，所以不会立即请求。过一段时间之后ready变为true，此时会发起请求，请求的过程中会返回三次结果，理想的状态是前两次loading返回true，最后一次返回false。但是第一次返回的结果loading是false

**Comment by crazylxr** [comment]
> 刚进入页面时请求一个接口，但是ready是false，所以不会立即请求。过一段时间之后ready变为true，此时会发起请求，请求的过程中会返回三次结果，理想的状态是前两次loading返回true，最后一次返回false。但是第一次返回的结果loading是false

有可复现的 demo 吗？

**Comment by guichch** [comment]
> 这个是必现的，可以自己试下哈

**Comment by crazylxr** [comment]
现在是符合期望的哈，没有啥问题

1. ready 变化的时候，执行了一次 rerender，loading=false
2. useEffect 监听到 ready 变化，开始执行，loading=true
3. 执行完，loading=false

**Comment by GeSnowBoy** [comment]
https://github.com/alibaba/hooks/issues/1780

**Comment by WangLeto** [comment]
折腾了一段时间，发现 ready 跟 loading 一起搭配使用时很难处理，改成 manul + run 了
