### ISSUE TITLE
应该把demo下的 jsx文件 git ignore掉

### ISSUE THREAD

**Issue by awmleer** [alibaba/hooks#158]
每次都要看 demo 里 jsx 文件的 diff 感觉很重复。。这种东西是不是可以 git ignore 掉然后在 build 的时候让ci重新生成一份？

**Comment by brickspert** [comment]
good idea。发布文档的时候，生成一次 jsx，发布完，立马删除。
这样开发着就感知不到 jsx 了。

**Comment by brickspert** [comment]
不用处理了，等着升级 father-doc
