### ISSUE TITLE
useLocalStorageState with default value uses wrong signature

### ISSUE THREAD

**Issue by breezewish** [alibaba/hooks#1582]
Consider:

```js
  const [x, setX] = useLocalStorageState('key', { defaultValue: { foo: true } })
  useEffect(() => {
    setX(v => ({
      ...v,
      foo: !v.foo
    }))
  }, [])
```

The TypeScript check failed complaining error for `v.foo`:

```
(parameter) v: {
    foo: boolean;
} | undefined
Object is possibly 'undefined'.ts(2532)
```

As you can see, v is `{foo:boolean}|undefined` instead of `{foo:boolean}`, even when default value is specified.

**Comment by brickspert** [comment]
和 #1581 两个问题一起在这里回答。

目前 StorageState 的 TS 类型存在一些瑕疵。

即使有 defaultValue，T 也有可能是 undefined 的，因为 defaultValue 只会在初始化的时候生效，后面还是可以删除，并且设置为 `undefined` 的。

**Comment by breezewish** [comment]
@brickspert 从 `useLocalStorageState` 这个 hook 本身视角来看，在有 `defaultValue` 情况下接受 undefined value（允许删除）可能不太合理，这意味着它不幂等? remount 和 render 情况下会有不同的 state

**Comment by fuhaiwei** [comment]
👍
#1586 应该已经修正了options的提示问题。

**Comment by brickspert** [comment]
> @brickspert 从 `useLocalStorageState` 这个 hook 本身视角来看，在有 `defaultValue` 情况下接受 undefined value（允许删除）可能不太合理，这意味着它不幂等? remount 和 render 情况下会有不同的 state

这里的 `defaultValue` 其实叫 `initialValue` 更合理，是一个初始化的默认值。
