### ISSUE TITLE
The factory function of useCreation get called twice in React 18

### ISSUE THREAD

**Issue by awmleer** [alibaba/hooks#1583]
See the codesandbox below:
https://codesandbox.io/s/ahooks-usecreation-with-react-18-9qojqe

![image](https://user-images.githubusercontent.com/16526078/166879861-dcef0ab4-3876-4fad-98b8-f1bc44d51a3e.png)

`id` get logged twice and the two values are different, which seems to violate the guarantee of `useCreation`.

Environments:
React & ReactDOM 18.1.0
ahooks 3.3.10

**Comment by SoonIter** [comment]
Remove the "React.StrictMode",then it will work well.
![image](https://user-images.githubusercontent.com/79413249/166984748-2090acc9-2006-4079-9f85-43d069a43d46.png)

**Comment by awmleer** [comment]
Found out that this is an expected behavior of StrictMode and there is no way to bypass it, even the `useCreation` Hook.
