### ISSUE TITLE
关于useEventEmitter使用

### ISSUE THREAD

**Issue by lovesL** [alibaba/hooks#1584]
useEventEmitter 能否在子组件通知父组件中使用，比如
<img width="892" alt="image" src="https://user-images.githubusercontent.com/27960630/166892341-bd5d32ae-3faf-4176-bf9c-2e957683e699.png">
CommonLayout是个移动端全局布局高阶组件，我想在子组件内控制是否需要显示头部或是底部，希望专家给点建议😊~

**Comment by brickspert** [comment]
可以的。

不过这种场景用全局 store（类 redux），或者 context 似乎更合适。
