### ISSUE TITLE
useRequest 重复发起请求 但是参数不一样。onSuccess只触发最后一次

### ISSUE THREAD

**Issue by zcCodeWarehouse** [alibaba/hooks#1585]
但是请求是成功发出去了的，也有返回值。

**Comment by zcCodeWarehouse** [comment]
我调用两次run，传参是不一样的，请求成功发送，但是只会触发最后一次的onSuccess

**Comment by zcCodeWarehouse** [comment]
从之前的issue得知这是预期行为，那我该如何优雅的解决这个问题呢。

**Comment by brickspert** [comment]
> 从之前的issue得知这是预期行为，那我该如何优雅的解决这个问题呢。

useRequest 目前解决不了这种问题，这种场景下感觉不适合用 useRequest。
