### ISSUE TITLE
useUrlState如果State属性中有Array，可能返回string[] string undefined。

### ISSUE THREAD

**Issue by fuhaiwei** [alibaba/hooks#1588]
useUrlState如果State属性中有Array，可能返回string[] string undefined。
示例链接：https://codesandbox.io/s/use-url-state-1-7cyi11?file=/App.tsx

可以考虑添加一个arrayNames的option，使得返回的state，始终为string[]
示例链接：https://codesandbox.io/s/use-url-state-2-k9l8i1?file=/App.tsx

**Comment by crazylxr** [comment]
> useUrlState如果State属性中有Array，可能返回string[] string undefined。

你是想表达 state 类型可能是 string[] string undefined？

**Comment by fuhaiwei** [comment]
@crazylxr 是的
这有点不方便使用

**Comment by crazylxr** [comment]
> @crazylxr 是的 这有点不方便使用

我们有考虑过这个问题，但是这个 ts 推导有点难，我们还没有找到合适的方法，但是你的建议加一个参数我认为这是为了 ts 类型才加的，不是特别合适的，毕竟 ts 只是一个类型，并不是逻辑，为了它去增加 API 我认为是不合适的。

可以继续讨论还有没有其他的方案

**Comment by fuhaiwei** [comment]
@crazylxr 
不是因为TypeScript类型才加的，可以看上面第一个代码示例。
传入单个元素的数组，会返回string，这样 array.includes()都没法调用了。

setState({ types: [] })
返回：{ }
预期：{ types: [] }

setState({ types: [1] })
返回：{ types: "1" }
预期：{ types: ["1"] }

setState({ types: [1, 2] })
返回：{ types: ["1", "2"] }
预期：{ types: ["1", "2"] }

**Comment by wangxingkai** [comment]
@brickspert @crazylxr 

哦，我懂了，这里说的是Hook输出的state和原始输入的state不一致的问题:

这里我们传入的`types` 始终是数组（大于一个元素的数组，一个元素的数组，空数组），而我们期待在返回的state里，`types`仍然应该是数组。

但第2和第3个用例中`types`的类型变成了"单个元素的字符串"和"undefined"。

```js
const [state, setState] = useUrlState();

// case 1
setState({ types: [1, 2] })
state.types // [1, 2]

// case 2
setState({ types: [1] })
state.types // '1'

// case 3
setState({ types: [] })
state.types // undefined

// in rendering
state.types.join(', ') // TypeError in case 2 and case 3
```

还没看代码，感觉是输入的原始state被`query-string`在flatten params到query string的过程给消化掉了。

我们在使用这个Hook的时候，应该是期待输入输出一致的，Hook的工作是把输入的state同步到URL。

---

另外，我发现，如果设置了初始state，setState空数组并不能覆盖初始值，个人觉得这不是预期的行为:

```js
const [state, setState] = useUrlState({ types: [1, 2, 3] });

setState({ types: [] })
state.types // [1, 2, 3]
```

**Comment by fuhaiwei** [comment]
@wangxingkai 是的，我正是这个意思。
useUrlState()自己并不保留状态，而是每次都把状态写入url，并读取url。并且default每次都会起作用。
感觉还是要写一个urlToState方法，这样才能返回具有正确类型的数据。

**Comment by fuhaiwei** [comment]
@wangxingkai 
> 另外，我发现，如果设置了初始state，setState空数组并不能覆盖初始值，个人觉得这不是预期的行为:
> 
> ```js
> const [state, setState] = useUrlState({ types: [1, 2, 3] });
> 
> setState({ types: [] })
> state.types // [1, 2, 3]
> ```

其实应该期待，只会返回string[]，而不是number[]。
但传入有number[]默认值的情况下，有可能返回number[]，string[]。
也许文档应该明确，只能传入string，string[]类型的数据

**Comment by brickspert** [comment]
可以通过 `options.parseOptions` 和 `options.stringifyOptions` 来控制 url 参数的转换逻辑，可以满足你的需求。

https://ahooks.js.org/zh-CN/hooks/use-url-state#options

**Comment by brickspert** [comment]
目前的输入输出就是通过 `query-string` 默认值来处理的，需要其它格式的，传递配置就好了~

**Comment by wangxingkai** [comment]
> ```js
> setState({ types: [] })
> ```

哦，我说的并不是返回string或者number的区别。我主要是说，我觉得空数组应该可以覆盖掉初始值

**Comment by wangxingkai** [comment]
@fuhaiwei
> 其实应该期待，只会返回string[]，而不是number[]。 但传入有number[]默认值的情况下，有可能返回number[]，string[]。 也许文档应该明确，只能传入string，string[]类型的数据

哦，我说的并不是返回string或者number的区别。我主要是说，我觉得空数组应该可以覆盖掉初始值

**Comment by wangxingkai** [comment]
> 可以通过 `options.parseOptions` 和 `options.stringifyOptions` 来控制 url 参数的转换逻辑，可以满足你的需求。
> 
> https://ahooks.js.org/zh-CN/hooks/use-url-state#options

`arrayFormat`  设置成其他显式用array的类型，可以解决“单元素数组”的情况 `setState({ types: [1] })`，但是"空数组“情况`setState({ types: [] })`仍然会返回`undefined`

https://github.com/sindresorhus/query-string#arrayformat
新版本的`query-string` 有个 `colon-list-separator` 格式，不知道是否能解决"空数组”情况
