### ISSUE TITLE
useEventListener能否监听dom数组

### ISSUE THREAD

**Issue by birdycn** [alibaba/hooks#1594]
```
 useEventListener(
     'click',
     (e: { target: { nodeName: string } }) => {
       console.log(e)
     },
     { target: () => document.querySelector('.content').querySelectorAll('img') },
   );
```

**Comment by birdycn** [comment]
希望能够监听某个父元素下的所有img标签的点击事件

**Comment by hchlq** [comment]
> 希望能够监听某个父元素下的所有img标签的点击事件

我觉得监听父元素就好了，通过事件委托即可
可以看一下这个例子哈
[demo](https://codesandbox.io/s/divine-cdn-x7m9mf?file=/src/App.js)

**Comment by brickspert** [comment]
> > 希望能够监听某个父元素下的所有img标签的点击事件
> 
> 我觉得监听父元素就好了，通过事件委托即可 可以看一下这个例子哈 [demo](https://codesandbox.io/s/divine-cdn-x7m9mf?file=/src/App.js)

正解 +10086
