### ISSUE TITLE
[RFC] useDeepCompareLayoutEffect

### ISSUE THREAD

**Issue by hchlq** [alibaba/hooks#1598]
用法： useLayoutEffect 一致，但依赖项通过 [lodash isEqual](https://lodash.com/docs/4.17.15#isEqual) 进行深比较。
场景：用于执行时机比较早的useLayoutEffect，并且对依赖项进行深比较
## API
```ts
function useDeepCompareLayoutEffect(effect: EffectCallback, deps: DependencyList): void
```

## Demo

```ts
  useDeepCompareLayoutEffect(() => {
    // if foo and bar change, do something
  }, [{foo, bar}])
```

**Comment by brickspert** [comment]
没问题的，代码完全参考 https://ahooks.js.org/hooks/use-deep-compare-effect 即可
