### ISSUE TITLE
useAntdTable 相关的 FnParams 没有导出

### ISSUE THREAD

**Issue by GYxiaOZ** [alibaba/hooks#160]
按照demo里的代码写，项目报错 FnParams 没有导出
![img](https://github.com/GYxiaOZ/Image-Hosting/blob/master/QQ%E5%9B%BE%E7%89%8720191125165512.png?raw=true)

再问一下是否有官方讨论群？
项目是否稳定，能否直接用于生产环境？

**Comment by brickspert** [comment]
1. 能提供一个可以复现的 demoe 吗？ FnParams 确实有导出。。
2. 目前有问题可以通过 issue 提问，我们会及时回复的。
3. 项目目前比较稳定，可以用于生产环境。蚂蚁内部已有多个生产项目使用~

**Comment by brickspert** [comment]
demo 确实有问题，需要这样导出。
`import { FnParams } from "@umijs/hooks/lib/useAntdTable";`
