### ISSUE TITLE
useResquest防抖

### ISSUE THREAD

**Issue by lovesL** [alibaba/hooks#1600]
"ahooks": "2.10.12",

![image](https://user-images.githubusercontent.com/27960630/167353943-718ad67a-85af-4389-aac4-e8c3b734a5d4.png)
![image](https://user-images.githubusercontent.com/27960630/167354370-43685ab4-2d3d-42b8-85c7-0f6d64d524eb.png)
  咋整。。。

**Comment by hchlq** [comment]
没太理解，能简述一下你遇到的问题吗？你要使用run的返回值？

**Comment by hchlq** [comment]
你要使用run的返回值么，这个是啥场景呢

**Comment by lovesL** [comment]
场景：i输入框输入值加防抖调接口。问题是
<img width="755" alt="image" src="https://user-images.githubusercontent.com/27960630/167369935-d04e41a9-931d-47f6-a19e-3b45bd0437c8.png">
接口调了 但是我拿不到接口的值

**Comment by hchlq** [comment]
这样设计感觉不好，提供一个建议
```js
  const { data, loading, run } = useRequest(getEmail, {
    debounceInterval: 500,
    manual: true,
  });

  const loadMore = () => {
    run({pageNum: page});
  };

  useEffect(() => {
    if (data) {
      if (page === 1) {
        // ...
      } else {
        // ...
      }
    }
  }, [someDeps]);
```

**Comment by lovesL** [comment]
> 这样设计感觉不好，提供一个建议
> 
> ```js
>   const { data, loading, run } = useRequest(getEmail, {
>     debounceInterval: 500,
>     manual: true,
>   });
> 
>   const loadMore = () => {
>     run({pageNum: page});
>   };
> 
>   useEffect(() => {
>     if (data) {
>       if (page === 1) {
>         // ...
>       } else {
>         // ...
>       }
>     }
>   }, [someDeps]);
> ```
。。。data 
![image](https://user-images.githubusercontent.com/27960630/167373088-667aee08-3caa-4b55-9ced-53059732d9fb.png)

**Comment by lovesL** [comment]
> 这样设计感觉不好，提供一个建议
> 
> ```js
>   const { data, loading, run } = useRequest(getEmail, {
>     debounceInterval: 500,
>     manual: true,
>   });
> 
>   const loadMore = () => {
>     run({pageNum: page});
>   };
> 
>   useEffect(() => {
>     if (data) {
>       if (page === 1) {
>         // ...
>       } else {
>         // ...
>       }
>     }
>   }, [someDeps]);
> ```

我只要加了 debounceInterval: 500,  data就拿不到值

**Comment by hchlq** [comment]
是不是useEffect的依赖项不对呢

**Comment by lovesL** [comment]
> 是不是useEffect的依赖项不对呢

不是  我确实没拿到值

> 是不是useEffect的依赖项不对呢

cosnt data = await a.run();  和  const { data, loading, run } = useRequest(getEmail  这两个的data  得的值有什么区别吗

**Comment by hchlq** [comment]
不是防抖节流的话是一样的，我这边模拟是没有问题的.
可以看下这个例子
```js
async function getEmail(search: string): Promise<string[]> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(Mock.mock({ 'data|5': ['@email'] }).data);
    }, 1000);
  });
}

export default () => {
  const { data, loading, run } = useRequest(getEmail, {
    debounceInterval: 500,
    manual: true,
  });


  const loadMore = () => {
    run()
  }

  useEffect(() => {
    console.log('data: ', data)
  }, [data])

  return (
    <div>
      <p>Enter quickly to see the effect</p>
      <input placeholder="Select Emails" onChange={(e) => loadMore()} />
      {loading ? (
        <p>loading</p>
      ) : (
        <ul style={{ marginTop: 8 }}>
          {data?.map((i) => (
            <li key={i}>{i}</li>
          ))}
        </ul>
      )}
    </div>
  );
};
```

**Comment by lovesL** [comment]
> 
 const a = useRequest(getTowerList,{ manual:true});
  const b = useRequest(getPackage, { manual: true });
大佬 但是我又多useRequest  不能解构 const { data, loading, run } 呀

> 不是防抖节流的话是一样的，我这边模拟是没有问题的. 可以看下这个例子
> 
> ```js
> async function getEmail(search: string): Promise<string[]> {
>   return new Promise((resolve) => {
>     setTimeout(() => {
>       resolve(Mock.mock({ 'data|5': ['@email'] }).data);
>     }, 1000);
>   });
> }
> 
> export default () => {
>   const { data, loading, run } = useRequest(getEmail, {
>     debounceInterval: 500,
>     manual: true,
>   });
> 
> 
>   const loadMore = () => {
>     run()
>   }
> 
>   useEffect(() => {
>     console.log('data: ', data)
>   }, [data])
> 
>   return (
>     <div>
>       <p>Enter quickly to see the effect</p>
>       <input placeholder="Select Emails" onChange={(e) => loadMore()} />
>       {loading ? (
>         <p>loading</p>
>       ) : (
>         <ul style={{ marginTop: 8 }}>
>           {data?.map((i) => (
>             <li key={i}>{i}</li>
>           ))}
>         </ul>
>       )}
>     </div>
>   );
> };
> ```

**Comment by lovesL** [comment]
我解决了 谢谢大佬
