### ISSUE TITLE
[feature] useTimeout 是否可以考虑 return timer

### ISSUE THREAD

**Issue by asyncguo** [alibaba/hooks#1615]
期望 `useTimeout` 返回 `timer`，方便调用者可以手动取消定时器

```js
function useTimeout(fn: () => void, delay: number | undefined): void {
  const fnRef = useLatest(fn);

  useEffect(() => {
    const timer = setTimeout(() => {
      fnRef.current();
    }, delay);
    return () => {
      clearTimeout(timer);
    };
  }, [delay]);
  
  // return 定时器的标识符
  return {
    timer
  }
}
```

**Comment by hchlq** [comment]
我觉得可以加一个取消定时器的返回函数，你觉得呢 @brickspert

**Comment by brickspert** [comment]
1. 这里如果把 `delay` 改成 `undefined` 就可以暂停当前的 timer
2. 增加一个 clear 函数也可以。 @hchlq

**Comment by hchlq** [comment]
如果把 `delay` 改成 `undefined` 确实可以，不过我觉得增加一个clear函数更好一点
原因是：
1. 如果要更改 `delay` 为 `undefined` ，调用者需要维护一个state去更改，感觉不是很有必要
2. 返回一个clear函数更加符合直觉，调用者直接调用清理定时器即可

**Comment by crazylxr** [comment]
> 如果把 `delay` 改成 `undefined` 确实可以，不过我觉得增加一个clear函数更好一点 原因是：
> 
> 1. 如果要更改 `delay` 为 `undefined` ，调用者需要维护一个state去更改，感觉不是很有必要
> 2. 返回一个clear函数更加符合直觉，调用者直接调用清理定时器即可

同意第二点，第一点不一定，因为取消的时候往往是依赖于其他的 state 去取消的，大多数情况是不需要多声明一个状态的。

不过最终建议还是 加一个 clear。
