### ISSUE TITLE
useRequest为甚么会发起两次http请求？

### ISSUE THREAD

**Issue by 269378737** [alibaba/hooks#1618]
新建了一个空白项目，放入了官网的实例代码（更改了请求代码），结果执行时在浏览器调试工具中看到调用了两次http请求，这是什么原因呢？报错可忽略，跨域引起的。

![image](https://user-images.githubusercontent.com/10287779/168193814-f8c0b132-ac0f-4ed0-8da4-197431adc779.png)

![image](https://user-images.githubusercontent.com/10287779/168194059-a154d76f-bd01-47d6-8a4c-d626fb0d739e.png)

**Comment by crazylxr** [comment]
react 版本是 18 吗？

**Comment by 269378737** [comment]
> react 版本是 18 吗？

是的，另外vite是2.9.9

**Comment by erweixin** [comment]
参考：https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode
React 18 将在开发模式下模拟卸载和重新安装组件
应该是这个原因

**Comment by 269378737** [comment]
> 参考：https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode React 18 将在开发模式下模拟卸载和重新安装组件 应该是这个原因

谢谢，看样子是这个原因，打包后在生产环境就请求一次了。
