### ISSUE TITLE
3.3.10升级到3.3.11，在服务端渲染中会报window is undefined

### ISSUE THREAD

**Issue by li-jia-nan** [alibaba/hooks#1631]
3.3.10升级到3.3.11，在服务端渲染中会报window is undefined，回退到3.3.10报错消失

**Comment by brickspert** [comment]
能贴下具体的报错地方吗

**Comment by u3u** [comment]
https://github.com/alibaba/hooks/blob/c907c7bb0f463db124ddbcc3c83706868277bd27/packages/hooks/src/utils/canUseDom.ts#L4

这里只能用 `typeof window !== 'undefined'`

**Comment by hchlq** [comment]
我了解了，之前typeof 有个暂存性死区 @brickspert ，目前在服务器访问，导致的报错

**Comment by li-jia-nan** [comment]
> 

[hooks/packages/hooks/src/utils/canUseDom.ts](https://github.com/alibaba/hooks/blob/c907c7bb0f463db124ddbcc3c83706868277bd27/packages/hooks/src/utils/canUseDom.ts#L4)

**Comment by li-jia-nan** [comment]
> 能贴下具体的报错地方吗

[hooks/packages/hooks/src/utils/canUseDom.ts](https://github.com/alibaba/hooks/blob/c907c7bb0f463db124ddbcc3c83706868277bd27/packages/hooks/src/utils/canUseDom.ts#L4)

**Comment by brickspert** [comment]
ahooks@3.3.12
