### ISSUE TITLE
SSR issue with useMouse

### ISSUE THREAD

**Issue by equinusocio** [alibaba/hooks#1635]
I'm using the `useMouse` hook inside a component, within NextJS. but I get the `document is not defined` error on page load. My code is very basic:

```tsx
import {useMouse} from 'ahooks'

export const Hero = () => {
  const mouse = useMouse()

  return (
    <>Mouse {mouse.pageX}</>
)}

```

This happens only when page change/reload. Not with hotreload.

> **Note**
> This is the [link](https://stackblitz.com/edit/nextjs-9mufgi?file=pages%2Findex.js) to reproduce the issue

**Comment by hchlq** [comment]
Thank you for your feedback. We have found the problem and fixed it as soon as possible

**Comment by brickspert** [comment]
ahooks@3.3.13
