### ISSUE TITLE
type.Ts中的TData是哪里来的

### ISSUE THREAD

**Issue by 1qazsy** [alibaba/hooks#1643]
TParms 是继承的，那TData 哪里来的呢，求大佬解释下

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by hchlq** [comment]
能详细点描述问题么
指的是 `function useRequest<TData, TParams extends any[]>` 吗

**Comment by crazylxr** [comment]
多天没有更多的信息，先关闭了
