### ISSUE TITLE
之前的loadMore现在有没有替代方案

### ISSUE THREAD

**Issue by fangzhengjin** [alibaba/hooks#1658]
之前的loadMore现在有没有替代方案呀? 
全局的字典下拉都用到了, 新版直接吧这个移除了....

**Comment by hchlq** [comment]
@fangzhengjin 能详细描述下问题不～，是 `useInfiniteScroll` 吗，还是啥问题呢

**Comment by fangzhengjin** [comment]
> @fangzhengjin 能详细描述下问题不～，是 `useInfiniteScroll` 吗，还是啥问题呢

对对对, 是这个, 原来改名拆出来了, 但是这个没有防抖诶, 我们是用useInfiniteScroll作下拉可查询字典, 用户输入的时候需要做防抖

**Comment by hchlq** [comment]
你的意思是下拉做防抖吗，还是用户输入的时候做防抖呢。能提供一个 demo 吗
用户输入做防抖的话，用防抖函数包裹 `loadMore` 就好了呀

**Comment by fangzhengjin** [comment]
恩恩, 还有个建议哈, reload函数能不能加个入参? 比如用户发起搜索的时候可通过reload将入参带入到请求参数

**Comment by crazylxr** [comment]
> 

你这种情况用 reloadDeps 就可以了吧。

**Comment by crazylxr** [comment]
> 恩恩, 还有个建议哈, reload函数能不能加个入参? 比如用户发起搜索的时候可通过reload将入参带入到请求参数

你这种情况用 reloadDeps 就可以了吧。

**Comment by crazylxr** [comment]
@fangzhengjin 你看哈 reloadDeps 能满足你的需求吗？

**Comment by fangzhengjin** [comment]
> @fangzhengjin 你看哈 reloadDeps 能满足你的需求吗？

可以可以 谢谢了
