### ISSUE TITLE
希望每个hooks有较完整的demo代码段，和较完整的注释，比如我看了一会文章，也不知道“asyncFn”具体是个什么样的参数。目前我看到的demo中只有简单是使用方式

### ISSUE THREAD

**Issue by sorryljt** [alibaba/hooks#166]
今天刚开始关注这个项目，感觉很棒，想日后在我们团队中使用，希望能给些较详细的文档支持。

**Comment by ttys026** [comment]
https://hooks.umijs.org/
文档里针对每个 hooks 都写了一些 demo，也可以在 codesandbox 中尝试。
关于文档的问题我们也会持续优化的。

**Comment by sorryljt** [comment]
谢谢，之前没有看到这个网站，我去好好看看
