### ISSUE TITLE
useRequest开启轮询模式，在标签页不可见或者浏览器最小化一段时间后就停止轮询，标签页重新激活后依旧不轮询

### ISSUE THREAD

**Issue by undefined9999** [alibaba/hooks#1661]
useRequest开启轮询模式，在标签页不可见或者浏览器最小化一段时间后就会停止轮询，标签页重新激活后依旧不轮询，这种有什么解决办法么？useInterval也会出现这种情况

**Comment by undefined9999** [comment]
是否考虑将setInterval和setTimeout的执行放到Web Worker中来避免这种问题？

**Comment by hchlq** [comment]
一段时间后大概是多少呢，我这边试了一下好像不会停止轮询，是不可见或最小化时间不够吗
触发的时间不符合预期是有的，因为这是浏览器下对 `setInterval` 和 `setTimeout` 的一个“优化”，执行回调的时机会变得慢一些

**Comment by undefined9999** [comment]
![image](https://user-images.githubusercontent.com/35595635/172976154-3b280138-d218-4a14-ab6f-cd73e447aecd.png)
我这边25分钟左右就停了，浏览器最小化，电脑没有睡眠，网络也没有波动，请求也没有报错

**Comment by hchlq** [comment]
试了一下的确有点问题，这个要不要看一下呢 @brickspert @crazylxr @awmleer

**Comment by hchlq** [comment]
@undefined9999 目前暂时还未考虑加入 Web Work 解决这个问题，主要有两个原因：

1. `ahooks` 不仅仅是在浏览器下，在服务端也会用到
2. 有一些其他的解决方案，可以监听屏幕聚焦，然后重新触发执行就好了

这边建议你通过「监听屏幕聚焦，然后重新触发」这一方案解决哈

**Comment by undefined9999** [comment]
@hchlq 感谢大佬耐心解答。目前是通过使用useDocumentVisibility在窗口激活的时候调用refresh这一方案解决的。但是我理解类似checkStatus这种的轮询即使在窗口非激活态时也是需要不间断执行的（除业务所需主动停止外），那是不是可以考虑将web work或者其他的方法做成可配置的，来满足web端和node端的不同使用方式呢

**Comment by hchlq** [comment]
我们先看下这种方式的改动成本怎么样，再决定要不要改哈。好像社区上其他的 lib 类似的问题也没能很好的解决

**Comment by undefined9999** [comment]
收到，感谢大佬耐心回复

**Comment by hchlq** [comment]
有想法欢迎提 PR 哈

**Comment by hchlq** [comment]
看了一下实现，引入 web worker 后可能导致覆盖全局 setTimeout 和 setInterval 的污染，暂不考虑加入，先关掉该 issue 哈
