### ISSUE TITLE
useAntdTable refreshDeps 改变我想要重置form，有实现方案么？

### ISSUE THREAD

**Issue by zyanfly** [alibaba/hooks#1667]
如题，我的table还依赖一个tab数据，作为refreshDeps，而我每次切换tab，我希望能重置table的筛选表单form，现在是form的数据会保留只有手动reset才可以重置。

**Comment by gqbre** [comment]
你们两个问题是不是相反的 https://github.com/alibaba/hooks/issues/1655

**Comment by crazylxr** [comment]
对，各个业务述求都不太一样，手动处理一下我觉得问题也很简单的。
