### ISSUE TITLE
useSize 在获取宽高带有小数点的元素时，会四舍五入

### ISSUE THREAD

**Issue by tobemaster56** [alibaba/hooks#1668]
复现链接：https://codesandbox.io/s/usesize-bug-7wtvtx

获取元素的 clientHeight，clientWidth，是会四舍五入的，如果需要原始的精确度，可以考虑 getBoundingClientRect() 这个 api

**Comment by hchlq** [comment]
感谢反馈～
感觉这个可以考虑下，你们觉得呢 @brickspert @crazylxr

**Comment by brickspert** [comment]
https://github.com/alibaba/hooks/pull/1303

之前有一个类似的 PR，可以看一下讨论。

可以支持，但是要考虑性能和向下兼容性。 cc @crazylxr

**Comment by hchlq** [comment]
向下兼容性是比较麻烦点的，改动的话可能会对之前版本的使用者有点困难，具体讨论改动可以在 #1303 讨论哈
