### ISSUE TITLE
useInfiniteScroll Service回调函数中的参数只能取到Data类型

### ISSUE THREAD

**Issue by g17628381307** [alibaba/hooks#1671]
export declare type Service<TData extends Data> = (currentData?: Data) => Promise<TData>;

我想在这个回调函数中取得Service返回的数据，
但是只能取得Data，
 currentData这个数据类型是否是TData泛型呢，
还是说这样是有意而为之，
希望能解答一下我的困惑

**Comment by hchlq** [comment]
`export type Service<TData extends Data> = (currentData?: TData) => Promise<TData>;`
默认的数据类型是：`export type Data = { list: any[]; [key: string]: any };`
`TData` 是继承 `Data` 的，即数据类型要符合 { list: any[]; [key: string]: any }

比如:  
```ts
const {.data } = useInfiniteScroll<{
    list: number[];
    foo: string;
  }>((d) => getLoadMoreList(d?.nextId, 4))
```
那么 data 的类型就是
```ts
{
    list: number[];
    foo: string;
}
```

**Comment by g17628381307** [comment]
`const { data } = useInfiniteScroll<{
    list: number[];
    foo: string;
  }>((d) => getLoadMoreList(d?.nextId, 4))`

是的泛型定义了一个额外的key 就是 foo：string类型， 但是在
`(d) => getLoadMoreList(d?.nextId, 4))`
这个回调中 无法取得d.foo

我比较想知道这个回调函数中的d 是什么类型的呢

谢谢你的回答，

**Comment by hchlq** [comment]
为什么要在回调中取得 `d.foo` 呢，这里只是举一个例子，你可以任意定义类型，只要是 promise 的 resolve 返回值类型就好了哈

**Comment by hchlq** [comment]
我理解的你的意思了，你说的对， currentData 的类型应该是 TData

**Comment by hchlq** [comment]
@g17628381307 在开发者没有指定泛型的情况， params 和 result.data 中得有一些取舍，如果改成了 TData，那么 result.data 就推断不出来，所以暂时不做修改哈，具体可以看下 #1673

建议你这边自己定义 params 的类型解决哈
e.g.
```ts
interface Result {
  list: string[];
  nextId: string | undefined;
}

const { data, loading, loadMore, loadingMore, mutate } = useInfiniteScroll((d: Result) =>
    getLoadMoreList(d?.nextId, 4),
  );
```

**Comment by g17628381307** [comment]
我明白为什么这里要使用Data类型了，
通过你的Demo，当d：Result类型时，
会产生
**类型“(d: Result) => void”的参数不能赋给类型“Service<Data>”的参数。**
的问题
舍弃params的话， 就只能在
`(d) => getLoadMoreList(d?.NextId, 4)`
这个回调函数中使用?.操作符去取数据了，

**Comment by hchlq** [comment]
第一个问题：

不会产生这个类型不匹配问题的，你理解错了，d 的类型是 `export type Data = { list: any[]; [key: string]: any };`，你可以指定对

应的类型

第二个问题：

通过 `?.` 取数据跟舍弃 params 没关系的哈，因为是通过 Promise 异步返回的数据，data 可能是为空的情况

**Comment by hchlq** [comment]
```ts
interface Result {
  list: string[];
  nextId: string | undefined;
}
const resultData = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13'];

function getLoadMoreList(nextId: string | undefined, limit: number): Promise<Result> {
  // ...
}
const { data, loading, loadMore, loadingMore, mutate } = useInfiniteScroll((d: Result) =>
  getLoadMoreList(d?.nextId, 4),
);
```
最终 `(d: Result) =>
  getLoadMoreList(d?.nextId, 4),
)`  推导的类型为 
<img width="282" alt="image" src="https://user-images.githubusercontent.com/60802048/173870751-8c003dae-ef66-498f-8d98-e938d00ccc1c.png">

**Comment by g17628381307** [comment]
```JavaScript
import { useInfiniteScroll } from 'ahooks';

interface Result {
    list: string[];
    nextId: string | undefined;
  }

const resultData = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13'];

function getLoadMoreList(nextId: string | undefined, limit: number): Promise<Result> {
  let start = 0;
  if (nextId) {
    start = resultData.findIndex((i) => i === nextId);
  }
  const end = start + limit;
  const list = resultData.slice(start, end);
  const nId = resultData.length >= end ? resultData[end] : undefined;
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        list,
        nextId: nId,
      });
    }, 1000);
  });
}
const Home = () => {
  useInfiniteScroll((d: Result | undefined) => getLoadMoreList(d?.nextId, 4));

  return (
    <div className="h-full">
      hello world
    </div>
  );
};

export default Home;

```

我贴一下我的代码哈， 希望大佬能够帮我看一下哪一步出了问题，我这个代码就会出现类型不匹配的错误

十分感谢！

**Comment by g17628381307** [comment]
```typescript
import { useInfiniteScroll } from 'ahooks';

interface Result {
    list: string[];
    nextId: string | undefined;
  }

const resultData = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13'];

function getLoadMoreList(nextId: string | undefined, limit: number): Promise<Result> {
  let start = 0;
  if (nextId) {
    start = resultData.findIndex((i) => i === nextId);
  }
  const end = start + limit;
  const list = resultData.slice(start, end);
  const nId = resultData.length >= end ? resultData[end] : undefined;
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        list,
        nextId: nId,
      });
    }, 1000);
  });
}
const Home = () => {
  useInfiniteScroll((d: Result | undefined) => getLoadMoreList(d?.nextId, 4));

  return (
    <div className="h-full">
      hello world
    </div>
  );
};

export default Home;

```


我贴一下我的代码哈， 希望大佬能够帮我看看哪里有问题，我这样写
` useInfiniteScroll((d: Result | undefined) => getLoadMoreList(d?.nextId, 4));`
就会出现类型不匹配的错误

感谢大佬的指点

**Comment by hchlq** [comment]
我这没问题的
<img width="725" alt="image" src="https://user-images.githubusercontent.com/60802048/173876308-7c9d59ee-aa9a-4eb8-a74b-a60ac0a13840.png">

**Comment by g17628381307** [comment]
好滴， 在我更新到最新版本的ahooks时就解决了这个问题， 感谢你耐心的恢复
