### ISSUE TITLE
useAntdTable的form里如果是下拉多选框，数据返回异常

### ISSUE THREAD

**Issue by puchenhui** [alibaba/hooks#1674]

**Comment by brickspert** [comment]
https://ahooks-v2.js.org/zh-CN/hooks/table/use-antd-table#faq

应该是类似这个问题吧？

如果不是的话，建议提供个复现。

**Comment by puchenhui** [comment]
不是的。
https://codesandbox.io/s/lb2jr9?file=/App.tsx 
这个是官方的demo，只需要在`select`组件的参数里加上   `mode="multiple"`  就可以复现出来

**Comment by crazylxr** [comment]
> 不是的。 https://codesandbox.io/s/lb2jr9?file=/App.tsx 这个是官方的demo，只需要在`select`组件的参数里加上 `mode="multiple"` 就可以复现出来

怎么异常了呢，我试了一下没看出问题

**Comment by puchenhui** [comment]
如果设置的是多选，传参的时候，首先，多选的内容不会变为list，而是单个传参；其次，会在参数后面加[]

**Comment by crazylxr** [comment]
![image](https://user-images.githubusercontent.com/16161407/174619971-121b0c87-eef4-4a10-9423-3d512bab5c9a.png)
@puchenhui 我这里是正常的呀，就是官方的 demo 改的，你那里如果还有问题的话提供一个完整的 demo 呢

**Comment by puchenhui** [comment]
非常感谢你，我刚在demo中测试是好的。但好奇怪，当时我在项目中用的时候，当下拉是多选情况下，数据是 data[]:1, data[]:2. 这样的，当时为了赶进度，就没用useAntdTable的这个方法。有可能是我版本号的问题吧，等下次了我在项目中再试试。

**Comment by crazylxr** [comment]
好的哈，那这个 issue 就关闭了哈
