### ISSUE TITLE
useInfiniteScroll无限滚动reloadDeps属性与滚动条

### ISSUE THREAD

**Issue by hasnum-stack** [alibaba/hooks#1677]
无限滚动useInfiniteScroll
如果滚动条在最底下时触发reloadDeps,会一直加载到没有数据,
设计如此 还是说要滚动条到顶,然后获取第一页比较好
是否需要在 reloadDeps 时加一个scrollTop = 0
或者加一个 effectLayout

**Comment by hchlq** [comment]
感谢反馈～

麻烦你这边能否组织一下你的问题呢，逻辑有点非，没太理解 😂

能提供一个复现 demo 会更好，更加容易理解哈

**Comment by hchlq** [comment]
因为 `reloadDeps` 改变了就会重新加载数据，可以自己控制调用 `loadMore` 就好了

> 设计如此 还是说要滚动条到顶,然后获取第一页比较好 
> 是否需要在 reloadDeps 时加一个scrollTop = 0 
> 或者加一个 effectLayout

这句没太懂，具体说下你的问题哈

**Comment by hasnum-stack** [comment]
> 因为 `reloadDeps` 改变了就会重新加载数据，可以自己控制调用 `loadMore` 就好了
> 
> > 设计如此 还是说要滚动条到顶,然后获取第一页比较好
> > 是否需要在 reloadDeps 时加一个scrollTop = 0
> > 或者加一个 effectLayout
> 
> 这句没太懂，具体说下你的问题哈

因为 `reloadDeps` 改变了就会重新加载数据, 所以如果滚动条在最底边的时候, 触发了reloadDeps, 就会多次调用service

**Comment by hchlq** [comment]
你是说这个边界需要处理是吗，我觉得这个给使用者自己控制调用 `loadMore` 就好了，不一定需要交给 `ahooks` 这边去控制，

如果场景是一定要在滚动条到底部依赖项变化，建议是自己控制依赖项，然后自己调用 `loadMore` 即可，不一定要依赖 

`reloadDeps` 哈

那和和下面这些描述有啥关系吗
> 设计如此 还是说要滚动条到顶,然后获取第一页比较好
> 是否需要在 reloadDeps 时加一个scrollTop = 0
> 或者加一个 effectLayout

**Comment by hasnum-stack** [comment]
@hchlq 大佬方便wx聊下不哈哈

**Comment by coder-lcn** [comment]
> > 因为 `reloadDeps` 改变了就会重新加载数据，可以自己控制调用 `loadMore` 就好了
> > > 设计如此 还是说要滚动条到顶,然后获取第一页比较好
> > > 是否需要在 reloadDeps 时加一个scrollTop = 0
> > > 或者加一个 effectLayout
> > 
> > 
> > 这句没太懂，具体说下你的问题哈
> 
> 因为 `reloadDeps` 改变了就会重新加载数据, 所以如果滚动条在最底边的时候, 触发了reloadDeps, 就会多次调用service

这种我最近碰巧遇到了，何库无关吧。我自己的做法就是请求完后把 scrollTop 往上调一调就好了

**Comment by hchlq** [comment]
好久没更新了，先关掉了哈

**Comment by hasnum-stack** [comment]
> > > 因为 `reloadDeps` 改变了就会重新加载数据，可以自己控制调用 `loadMore` 就好了
> > > > 设计如此 还是说要滚动条到顶,然后获取第一页比较好
> > > > 是否需要在 reloadDeps 时加一个scrollTop = 0
> > > > 或者加一个 effectLayout
> > > 
> > > 
> > > 这句没太懂，具体说下你的问题哈
> > 
> > 
> > 因为 `reloadDeps` 改变了就会重新加载数据, 所以如果滚动条在最底边的时候, 触发了reloadDeps, 就会多次调用service
> 
> 这种我最近碰巧遇到了，何库无关吧。我自己的做法就是请求完后把 scrollTop 往上调一调就好了

我也是这么做的.

**Comment by hasnum-stack** [comment]
> 好久没更新了，先关掉了哈

先关吧大佬,
