### ISSUE TITLE
升级到v3.5.0部署失败

### ISSUE THREAD

**Issue by li-jia-nan** [alibaba/hooks#1688]
![QQ20220620-190824](https://user-images.githubusercontent.com/49217418/174590785-3aadc793-b588-4fc6-a8cc-eb76443bcb94.png)

开始是v2版本，可以成功部署

升级到v3.5.0，跑 gitlab 的流水线，在 npm install 的时候就会报错连接超时，试了很多次都不行（但是本地是没问题的）

然后回退到v3.4.1，可以成功部署

试了其它几个小版本也都没问题，就是v3.5.0不能部署

**Comment by crazylxr** [comment]
有按照下面报错的提示操作过吗？

**Comment by li-jia-nan** [comment]
> 有按照下面报错的提示操作过吗？

试过了，一样的报错

**Comment by li-jia-nan** [comment]
<img width="804" alt="QQ20220621-153346@2x" src="https://user-images.githubusercontent.com/49217418/174742577-cf3a1e18-a70e-4aae-b6f3-24d88adb364d.png">

解决了，把ci里面的镜像指向cnpm就可以正常部署了

不知道还有没有更好的办法，欢迎讨论
