### ISSUE TITLE
useInterval() 里用到了 clearTimeout() ?

### ISSUE THREAD

**Issue by diydyq** [alibaba/hooks#1694]
https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useInterval/index.ts

**Comment by hchlq** [comment]
神奇的是竟然可以暂停，怪不得测试和文档都没问题 😂

**Comment by miracles1919** [comment]
> 神奇的是竟然可以暂停，怪不得测试和文档都没问题 😂

看了下 [mdn](https://developer.mozilla.org/zh-CN/docs/Web/API/setTimeout) 
![image](https://user-images.githubusercontent.com/22469543/174932534-b798eb26-cada-4343-845d-82a4b8266c55.png)

**Comment by li-jia-nan** [comment]
> > 神奇的是竟然可以暂停，怪不得测试和文档都没问题 😂
> 
> 看了下 [mdn](https://developer.mozilla.org/zh-CN/docs/Web/API/setTimeout) ![image](https://user-images.githubusercontent.com/22469543/174932534-b798eb26-cada-4343-845d-82a4b8266c55.png)

学到了学到了

**Comment by coder-lcn** [comment]
优秀，哈哈
