### ISSUE TITLE
对表格操作后，怎样才能不重置回第一页

### ISSUE THREAD

**Issue by Jack-luo1208** [alibaba/hooks#1700]
![image](https://user-images.githubusercontent.com/65880030/174958468-8897febf-06d3-4283-85ef-bdaea8a0c0d2.png)

**Comment by coder-lcn** [comment]
具体是什么操作呢？可以请提供最小重现嘛。

**Comment by Jack-luo1208** [comment]
> 具体是什么操作呢？可以请提供最小的回报嘛。
比如我点击超额告警后会执行submit方法，但是我想保留在这个页面

**Comment by coder-lcn** [comment]
> > 具体是什么操作呢？可以请提供最小的回报嘛。
> > 比如我点击超额告警后会执行submit方法，但是我想保留在这个页面

这个应该是属于业务问题了，和 `hooks`这个库无关。你可以仔细看看代码，为什么 submit 后，会回到第一页。先捋清楚这个问题。最好还是提供一个最小的重现，这样沟通成本和解决问题的效率都高哦。

**Comment by brickspert** [comment]
有个 `refresh` 的，可以调用后不重置到第一页。
