### ISSUE TITLE
jest tests failed

### ISSUE THREAD

**Issue by zhaomenglu** [alibaba/hooks#1703]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/39189837/174970168-18a445c7-872e-43ae-90f2-5e9bd89737f9.png">
@ahooksjs/use-url-state  -> 3.5.0
react-router -> 6.3.0

**Comment by crazylxr** [comment]
@zhaomenglu 放个可复现的 demo 呢

**Comment by zhaomenglu** [comment]
> @zhaomenglu 放个可复现的 demo 呢

react文件：
import React from 'react';
import useUrlState from '@ahooksjs/use-url-state';

const TestUseUrlState = () => {
  const [ urlState, setUrlState ] = useUrlState<any>({});
  const toggleState = () => {
    const newState: any = {};
    if (urlState.id) {
      newState.id = undefined;
    } else {
      newState.id = '123'
    }
    setUrlState(newState);
  }
  return (
    <div>
      <button onClick={toggleState}>添加参数</button>
      这是url里的参数：{JSON.stringify(urlState)}
    </div>
  )
};

export default TestUseUrlState;
test文件：
import React from 'react';
import { mount } from 'enzyme';
import Test from '../../src/Test/index';

Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(), // deprecated
    removeListener: jest.fn(), // deprecated
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
});

describe('Filter', () => {
  it('🎆 basic use', () => {
    const onSearch = jest.fn();
    const wrapper = mount((
      <Test/>
    ));
    expect(wrapper.find('button')).toHaveLength(1);
    expect(onSearch).toHaveBeenCalled();
  })
})

就是用useUrlState，就会报错，之前用的react-router 5.0.0版本也报错，但是报的不是这个错，我就都升级试了下，就改成报这个错了。。。

**Comment by zhaomenglu** [comment]
> @zhaomenglu 放个可复现的 demo 呢

react文件：
import React from 'react';
import useUrlState from '@ahooksjs/use-url-state';

const TestUseUrlState = () => {
  const [ urlState, setUrlState ] = useUrlState<any>({});
  const toggleState = () => {
    const newState: any = {};
    if (urlState.id) {
      newState.id = undefined;
    } else {
      newState.id = '123'
    }
    setUrlState(newState);
  }
  return (
    <div>
      <button onClick={toggleState}>添加参数</button>
      这是url里的参数：{JSON.stringify(urlState)}
    </div>
  )
};

export default TestUseUrlState;
test文件：
import React from 'react';
import { mount } from 'enzyme';
import Test from '../../src/Test/index';

Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(), // deprecated
    removeListener: jest.fn(), // deprecated
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
});

describe('Filter', () => {
  it('🎆 basic use', () => {
    const onSearch = jest.fn();
    const wrapper = mount((
      <Test/>
    ));
    expect(wrapper.find('button')).toHaveLength(1);
    expect(onSearch).toHaveBeenCalled();
  })
})

就是用useUrlState，就会报错，之前用的react-router 5.0.0版本也报错，但是报的不是这个错，我就都升级试了下，就改成报这个错了。。。

**Comment by zhaomenglu** [comment]
> @zhaomenglu 放个可复现的 demo 呢

react文件：
import React from 'react';
import useUrlState from '@ahooksjs/use-url-state';

const TestUseUrlState = () => {
  const [ urlState, setUrlState ] = useUrlState<any>({});
  const toggleState = () => {
    const newState: any = {};
    if (urlState.id) {
      newState.id = undefined;
    } else {
      newState.id = '123'
    }
    setUrlState(newState);
  }
  return (
    <div>
      <button onClick={toggleState}>添加参数</button>
      这是url里的参数：{JSON.stringify(urlState)}
    </div>
  )
};

export default TestUseUrlState;
jest文件：
import React from 'react';
import { mount } from 'enzyme';
import Test from '../../src/Test/index';

Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(), // deprecated
    removeListener: jest.fn(), // deprecated
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
});

describe('Filter', () => {
  it('🎆 basic use', () => {
    const onSearch = jest.fn();
    const wrapper = mount((
      <Test/>
    ));
    expect(wrapper.find('button')).toHaveLength(1);
    expect(onSearch).toHaveBeenCalled();
  })
})
就简单的用就会报错。。

**Comment by crazylxr** [comment]
我的意思是放一个 可运行的 demo，比如放到  codesandbox 上

**Comment by zhaomenglu** [comment]
> 我的意思是放一个 可运行的 demo，比如放到 codesandbox 上

https://codesandbox.io/s/3losw7?file=/src/Test.js

**Comment by hchlq** [comment]
你放的 demo 这个和 Jest Test 没关系呀，是你这边的使用问题哈，具体可以看下图：

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/60802048/175285240-9c0fb03b-905b-442a-8254-3e8b88f3f7fd.png">

**Comment by hchlq** [comment]
你都没有使用 `react-router` ，所以报错了，内部用的 `useLocation` 是依赖外层的 `<Router></Router>` 的

**Comment by zhaomenglu** [comment]
> 你都没有使用 `react-router` ，所以报错了，内部用的 `useLocation` 是依赖外层的 `<Router></Router>` 的

啊，那我是封装了一个搜索的组件用到了，jest测试就是测试这个组件，组件里是没有Router标签，emmm，Router标签是写在项目里的。那就jest就是没法通过的，要是想通过就要加个Router标签么
