### ISSUE TITLE
[RFC] usePromise

### ISSUE THREAD

**Issue by oney** [alibaba/hooks#1715]
# Problem

目前在React中使用异步的Promise时，大部分开发者都没有考虑到Promise需要cleanup。
例如以下[这个例子](https://maxrozen.com/race-conditions-fetching-data-react-with-useeffect)：
```jsx
function DataDisplayer(props) {
  const [data, setData] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      const newData = await fetch(`https://swapi.dev/api/people/${props.id}/`).then(r => r.json());
      setData(newData);
    };
    fetchData();
  }, [props.id]);

  return <div>{data.name}</div>;
}
```
包含了race condition和memory leak两个问题。
自己处理的解决方案可以是手写`let cleanup = false;`或定义`AbortController()`，但都挺繁琐的。
并且如果是在Event handler中呼叫Promise的话，没有很简单的方式可以cleanup（要动用到useRef）
```jsx
function DataDisplayer(props) {
  const [data, setData] = useState(null);
  const onRefresh = async () => {
      const newData = await fetch(`https://swapi.dev/api/people/${props.id}/`).then(r => r.json());
      setData(newData);
  }

  return <div>{data.name}<button onClick={onRefresh}>refresh</button></div>;
}
```
# Solution
## API
```ts
const getPromise: () => R = usePromise<R extends Promise<any>>(
  callback: () => R,
  deps: React.DependencyList
);
```
## Demo
```jsx
function DataDisplayer(props) {
  const [data, setData] = useState(null);
  const getPromise = usePromise(
    () => fetch(`https://swapi.dev/api/people/${props.id}/`).then(r => r.json()),
    [props.id]
  );

  useEffect(() => {
    const fetchData = async () => {
      try {
        const newData = await getPromise();
        setData(newData);
      } catch (_) {}
    };
    fetchData();
  }, [getPromise]);

  return <div>{data.name}</div>;
}
```
把fetch promise用`usePromise`包住，并正确填入所有`deps`，当`deps`变化时，就视为这个promise已经过时了，没有继续处理的必要，否则会造成race condition或memory leak，所以它会被abort。

有了这个hook应该会让开发者比较轻鬆的管理promise，虽然说大家现在也应该都用某个data fetching library，没多少自己管理的情况，但也还是一个补充。另外，如果是mutation类的promise，就要视情况而定，不一定在deps变化时一定要abort，所以可以不用usePromise包。
## Implementation
#1712

**Comment by miracles1919** [comment]
1、处理 promise 的 hook 已经有了，可以看下 `useRequest`
2、`useRequest`支持依赖刷新，内部有一个 ref 变量记录最新的 promise，所以能解决 race condition 的问题
3、promise 执行完会释放内存的.. 应该不用担心 promise 引发的内存泄漏吧 .. 
4、看代码实现上用了 `AbortController`，[MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/AbortController) 上说这还是一个实验中的功能，兼容性也不好

**Comment by oney** [comment]
啊。。。useRequest基本上实现了我这个usePromise的功能，那应该是不需要了。
