### ISSUE TITLE
useUrlState为什么需要 useUpdate 强制更新一次

### ISSUE THREAD

**Issue by xm-yu** [alibaba/hooks#1720]
看useUrlState这个hooks 中每次都会执行`update()`强制更新一次，这在没有命中react 批量更新的时候会有多次更新
![image](https://user-images.githubusercontent.com/20613441/176088321-7cc7d24b-5ea5-4a71-b650-39a7a0aa4d83.png)
```js

import React from 'react';
import useUrlState from '@ahooksjs/use-url-state';

export default () => {
  const [state, setState] = useUrlState({ page: '1', pageSize: '10' });

  return (
    <>
      <div>
        page: {state.page}
        <span style={{ paddingLeft: 8 }}>
          <button
            onClick={() => {
              setTimeout(() => {
                setState((s) => ({ page: Number(s.page) + 1 })); // 触发两次render
              });
            }}
          >
            +
          </button>
        </span>
      </div>
    </>
  );
};

```
我看源码里有依赖 useLocation，每次 `history.push` or `history.replace` 每次都是新的location ，已经达到更新的效果。
感觉没有必要再用`update` 再强制触发一次更新了
![image](https://user-images.githubusercontent.com/20613441/176088493-db9d87d6-03b4-44a6-8073-bd17be21de5b.png)

**或者有什么特殊场景，是我没想到的**

**Comment by miracles1919** [comment]
额... 这不是有注释么... 

> 1. 如果 setState 后，search 没变化，就需要 update 来触发一次更新。比如 demo1 直接点击 clear，就需要 update 来触发更新。
> 2. update 和 history 的更新会合并，不会造成多次更新

**Comment by xm-yu** [comment]
> 额... 这不是有注释么...
> 
> > 1. 如果 setState 后，search 没变化，就需要 update 来触发一次更新。比如 demo1 直接点击 clear，就需要 update 来触发更新。
> > 2. update 和 history 的更新会合并，不会造成多次更新
第一条

**Comment by xm-yu** [comment]
> 额... 这不是有注释么...
> 
> > 1. 如果 setState 后，search 没变化，就需要 update 来触发一次更新。比如 demo1 直接点击 clear，就需要 update 来触发更新。
> > 2. update 和 history 的更新会合并，不会造成多次更新

1、search没变化 也不需要 update来触发一次更新， 因为 location 每次都会变化，已经达到更新作用
2、在没有命中 批量更新机制的时候 表现 是多次更新。

**Comment by hchlq** [comment]
@xm-yu 这个更新导致你有哪些预期之外的结果呢

**Comment by brickspert** [comment]
> ，已经达到更新作用

`如果 setState 后，search 没变化，就需要 update 来触发一次更新。比如 demo1 直接点击 clear，就需要 update 来触发更新。`

search 没变化，不代表 state 不会变化。可以具体删掉 `update()`，然后体验一下 demo1 直接点击 `clear` 会有什么变化。

期望是 count 变化为 `undefined`，但删掉 `update()` 后，不会触发变化。

**Comment by YangYmimi** [comment]
useUrlState 会导致 onRouteChange 被触发多次。
