### ISSUE TITLE
【bug】React18  useVirtualList 会无限循环

### ISSUE THREAD

**Issue by ClenLu** [alibaba/hooks#1726]
复现步骤
1 umi4 项目
2 使用 useVirtualList 案例什么都不动的情况下 鼠标快速往下滚动  会无限循环下去

**Comment by crazylxr** [comment]
有在线的 demo 么？

**Comment by ClenLu** [comment]
> 有在线的 demo 么？

不好意思。 和 #1606 重复了。同样的问题

**Comment by crazylxr** [comment]
那这个就先关了哈，关注另外一个就行

**Comment by laiyuzenb** [comment]
![image](https://user-images.githubusercontent.com/44738912/182123422-c284474a-b66f-4901-a533-3e2d971ed17c.png)

初步定位是calculateRange 重复执行造成的  在 calculateRange 内添加scrollTriggerByScrollToFunc.current = true 即可减少重复执行 但滚动结束后还是有略微渲染抖动
