### ISSUE TITLE
希望useCountdown增加一个参数

### ISSUE THREAD

**Issue by frontlich** [alibaba/hooks#1727]
`useCountdown`现在存在两个问题

1. 内部计算剩余时间的 `calcLeft` 函数，采用的是 new Date().getTime()，不是服务器时间，可能会产生倒计时不准的问题
2. 如果想做验证码或者确认按钮的倒计时，还得计算出targetDate，不方便

希望增加一个参数 `leftTime`，即剩余时间毫秒数，这样可以解决以上两个问题
1. 通过 targetDate - timeStamp(服务器返回的时间戳) 计算出剩余时间可解决
2. 如果想倒计时60s，直接传leftTime: 60 * 1000 即可

**Comment by li-jia-nan** [comment]
@crazylxr 大佬看下这个，我可以提个pr，但是感觉好像没啥必要，倒计时不准的原因应该不是 `new Date().getTime()` 吧，而是 `setInterval`，把 `calcLeft` 换成 `leftTime` 依然无法解决不准的问题

**Comment by hchlq** [comment]
确认两个问题：

1.  返回服务器时间是时间戳吗
2. 倒计时不准指的是有延迟还是啥呢

**Comment by hchlq** [comment]
其实感觉没必要增加一个参数的，**主要关注的是倒计时不准的问题**

第一个问题：

如果服务器返回的是时间戳，可以参考官网案例的 [配置项动态变化](https://ahooks.js.org/zh-CN/hooks/use-count-down#%E5%A4%87%E6%B3%A8) 进行更改

第二个问题：

我觉得其实没必要，通过把目标时间这个参数聚合到了 `targetDate` 中，`targetDate` 相当于支持多个写法，是一个底层设计，

不应该为了写法简便去更改 api 接口，如果想使用更加简洁的，可以自己封装一些 util 函数

**Comment by frontlich** [comment]
> 确认两个问题：
> 
> 1. 返回服务器时间是时间戳吗
> 2. 倒计时不准指的是有延迟还是啥呢

```ts
const calcLeft = (t?: TDate) => {
  if (!t) {
    return 0;
  }
  // https://stackoverflow.com/questions/4310953/invalid-date-in-safari
  const left = dayjs(t).valueOf() - new Date().getTime();
  if (left < 0) {
    return 0;
  }
  return left;
};
```

如果用户本地时间异常，由new Date().getTime()计算剩余时间，则这个函数返回的left值不准
比如：用户本地时间是 2022-07-04 18:00:00，服务器时间是 2022-07-04 12:00:00，targetDate是2022-07-04 18:00:00，则倒计时直接结束了，实际上还差6个小时

**Comment by hchlq** [comment]
的确可能存在这个问题～

@brickspert @crazylxr 看下要不要处理呢～

**Comment by brickspert** [comment]
我觉得加一个 leftTime OK 的~

**Comment by hchlq** [comment]
@li-jia-nan PR Welcome !

**Comment by li-jia-nan** [comment]
> @li-jia-nan PR Welcome !

有一个问题，增加了新的参数之后，如果同时传了leftTime和targetDate，那么哪个优先级更高呢？

**Comment by hchlq** [comment]
需要兼容之前的版本，后面新增的以 `leftTime` 为主
