### ISSUE TITLE
ahooks 可以精确导入吗？

### ISSUE THREAD

**Issue by lynn1286** [alibaba/hooks#1739]
我在nextjs 中使用 ahooks ，但是发现nextjs 中无法做到精确Tree Shake ， 例如： 比如在 Page A 使用了 useSetState 方法，在 Page B 使用了 useDebounceFn 方法，由于都是使用 import {} from 'ahooks' 导入，导致在 Page A 加载时也会去加载 Page B 的 useDebounceFn 方法， 我不确定这个是不是个问题所在，但是打包出来的首次加载size特别庞大，我试着将项目中的 lodash 修改成import { merge } from 'lodash-es' 到 import merge from 'lodash-es/merge'， 打包后确实有所降低，所以我想试着修改下 ahooks 的导入方式，但是发现不可行

**Comment by hchlq** [comment]
可以通过 `import useRequest from 'ahooks/es/useRequest'` 的方式导入，这种方式导入也没解决吗

项目下是配置了 `sideEffect: false` 的，看下 build 出来的产物还会打包进去么

**Comment by crazylxr** [comment]
@lynn1286 先按照 @hchlq 的方式试一下哈，issue 先 close 了，有问题再重新 open
