### ISSUE TITLE
useFullscreen方法中遇到一个问题

### ISSUE THREAD

**Issue by KangXinzhi** [alibaba/hooks#1741]
我在实际项目中调用enterFullscreen全屏后进入另外的页面。页面路由跳转会导致useFullscreen的状态刷新，返回isFullScreen默认为false，这时候在另外的页面调用exitFullscreen退出全屏方法，源码中会被拦截掉，导致无法退出全屏。个人认为exitFullscreen的方法中并不太需要判断state这个限制。

**Comment by KangXinzhi** [comment]
我的解决方法是在项目里面额外封装一个 useFullscreen 的hooks，在其中改写了exitFull方法,去掉了state的判断逻辑。
```
  const exitFullscreen = useCallback(() => {
    if (screenfull.isEnabled) {
      screenfull.exit()
    }
  }, [])
```
想提一个pr，大佬帮忙看看有没有这个必要。

**Comment by miracles1919** [comment]
我觉得 `isFullScreen` 的初始状态用 `Boolean(screenfull.isFullscreen)` 是不是更好 ？

**Comment by hchlq** [comment]
页面路由跳转会导致原来的状态消失吗，不会的吧～

能给个复现 demo 不

**Comment by miracles1919** [comment]
```
// 组件
Parent
  useFullscreen()
  
  Child 1
    useFullscreen()

  Child 2
    useFullscreen()
```

```
// 路由
/child1 -> Child1
/cihld2 -> Child2
```

类似这样的结构

1. 访问 child1，设置全屏
2. 跳转 child2，此时 child2 中 useFullscreen 的 `isFullscreen` 为 false（默认值，但还是全屏中）

**Comment by brickspert** [comment]
> 我的解决方法是在项目里面额外封装一个 useFullscreen 的hooks，在其中改写了exitFull方法,去掉了state的判断逻辑。
> 
> ```
>   const exitFullscreen = useCallback(() => {
>     if (screenfull.isEnabled) {
>       screenfull.exit()
>     }
>   }, [])
> ```
> 
> 想提一个pr，大佬帮忙看看有没有这个必要。

我觉得应该比较合理的，可以提个 PR

**Comment by KangXinzhi** [comment]
🆗，写了一个小demo复现了一下我的问题：https://codesandbox.io/s/e6rss0，全屏的效果可以在https://e6rss0.csb.app/中看到。我将useFullScreen全屏对象绑定到了document下的root身上，在首页是可以正常切换是否全屏，但是首页全屏后进入子页面后，再返回到首页，这时exitFullscreen方法已经无法使用了，因为控制台打印的 isFullScreen返回false（此时应该为true）。exitFullscreen源码中判断了一次isFullScreen，导致被拦截掉无法退出全屏。

**Comment by KangXinzhi** [comment]
🆗，我写了一个小demo复现了一下我的问题：https://codesandbox.io/s/e6rss0
效果在: https://e6rss0.csb.app
我将useFullScreen全屏对象绑定到了document下的root身上，在首页是可以正常切换是否全屏，但是首页全屏后进入子页面后，再返回到首页，这时exitFullscreen方法已经无法使用了，因为控制台打印的 isFullScreen返回false（此时应该为true）。exitFullscreen源码中判断了一次isFullScreen，导致被拦截掉无法退出全屏。

**Comment by miracles1919** [comment]
> 但是首页全屏后进入子页面后，再返回到首页，这时exitFullscreen方法已经无法使用了，因为控制台打印的 isFullScreen返回false（此时应该为true）

所以我觉得应该修改 isFullScreen 的初始值

**Comment by hchlq** [comment]
不要两个 PR 吧，讨论下关掉一个 PR，放在一个 PR 就好了～

**Comment by KangXinzhi** [comment]
> > 但是首页全屏后进入子页面后，再返回到首页，这时exitFullscreen方法已经无法使用了，因为控制台打印的 isFullScreen返回false（此时应该为true）
> 
> 所以我觉得应该修改 isFullScreen 的初始值

确实，这样的方式更好一些，我在本地测试解决了所有的问题。大佬，可以让我来提这个PR么？很想参与下ahooks开源库的贡献(─‿─)

**Comment by miracles1919** [comment]
ok 的，我就是看下代码效果，你来吧 ~

**Comment by crazylxr** [comment]
虽然现在这个方式确实是没问题的，但是我觉得
```js
  const exitFullscreen = () => {
    if (!state) {
      return;
    }
    if (screenfull.isEnabled) {
      screenfull.exit();
    }
  };
```

中的这个状态判断还是有点多余呢，用户要退出就直接退出就行了。所以除了改初始值，这个状态判断也可以删掉。

@KangXinzhi @miracles1919 你们觉得呢？

**Comment by KangXinzhi** [comment]
> 虽然现在这个方式确实是没问题的，但是我觉得
> 
> ```js
>   const exitFullscreen = () => {
>     if (!state) {
>       return;
>     }
>     if (screenfull.isEnabled) {
>       screenfull.exit();
>     }
>   };
> ```
> 
> 中的这个状态判断还是有点多余呢，用户要退出就直接退出就行了。所以除了改初始值，这个状态判断也可以删掉。
> 
> @KangXinzhi @miracles1919 你们觉得呢？

我觉得这个状态判断也没什么必要，删掉没什么影响。

**Comment by miracles1919** [comment]
> 我觉得中的这个状态判断还是有点多余，所以除了改初始值，这个状态判断也可以删掉。

看下 [screenfull](https://github.com/sindresorhus/screenfull/blob/main/index.js#L96-L102) 里的 exit 方法，对 `isFullscreen` 状态也做了判断的，我觉得也可以去掉

**Comment by crazylxr** [comment]
@KangXinzhi 那你在你的那个 pr 那里去掉一下。

**Comment by KangXinzhi** [comment]
> @KangXinzhi 那你在你的那个 pr 那里去掉一下。

ok，已经去掉了

**Comment by KangXinzhi** [comment]
> 我觉得 `isFullScreen` 的初始状态用 `Boolean(screenfull.isFullscreen)` 是不是更好 ？

https://github.com/alibaba/hooks/pull/1755/files/8048728b3aa7c8a1aa3717135c1203a7b3c534e9#r924356319
大佬帮忙一起看看，砖家大佬给了些建议

**Comment by brickspert** [comment]
> > 我觉得 `isFullScreen` 的初始状态用 `Boolean(screenfull.isFullscreen)` 是不是更好 ？
> 
> https://github.com/alibaba/hooks/pull/1755/files/8048728b3aa7c8a1aa3717135c1203a7b3c534e9#r924356319 大佬帮忙一起看看，砖家大佬给了些建议

已经改好了~

**Comment by crazylxr** [comment]
3.6.2 已经修复了

**Comment by xiaofuliang** [comment]
@KangXinzhi 请问怎么解决的，3.7.1还是有这样的问题
