### ISSUE TITLE
useCounter不能把value设置成‘’，不然就报这个错误

### ISSUE THREAD

**Issue by ladyruo** [alibaba/hooks#1742]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/28803604/177753765-ce149114-1246-49c4-8e34-3131befe6af2.png">
<img width="660" alt="image" src="https://user-images.githubusercontent.com/28803604/177754072-2159a713-e3eb-47c9-8da5-aa85ac3be197.png">

**Comment by ladyruo** [comment]
@muescha @tony @shiny @popomore

**Comment by ladyruo** [comment]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/28803604/177754035-bd9d7f11-1fa1-4270-b984-b1ae1c7e29a0.png">

**Comment by brickspert** [comment]
要求是 `number` 类型呀
