### ISSUE TITLE
useRequest 默认的『竞态取消』功能能否 可配置

### ISSUE THREAD

**Issue by fubd** [alibaba/hooks#1758]
某些场景下，相同的接口，仅仅是参数不同。不需要自动取消其他未完成的请求。

**Comment by miracles1919** [comment]
这种情况并不适合用 `useRequest`

**Comment by brickspert** [comment]
是的，这种情况下不使用 useRequest 会更合理的。

**Comment by SignDawn** [comment]
只有一个 data ，不取消不合理吧

**Comment by CaptainJon** [comment]
> 只有一个 data ，不取消不合理吧

但是我可以不使用那个data，而是在onSuccess中自己管理state
