### ISSUE TITLE
useWebWorker

### ISSUE THREAD

**Issue by sunshineLixun** [alibaba/hooks#1759]
有计划增加一个useWebWorker 的Hooks ？ 大佬们评审下 。  如果没有，可否自己PR一个。

**Comment by hchlq** [comment]
感觉不是很有必要呢，原因有：

1. webWorker 使用场景可能不是很多
2. ahooks 不仅支持浏览器，还会支持服务端，而 web worker 只支持浏览器～

**Comment by sunshineLixun** [comment]
> 感觉不是很有必要呢，原因有：
> 
> 1. webWorker 使用场景可能不是很多
> 2. ahooks 不仅支持浏览器，还会支持服务端，而 web worker 只支持浏览器～

ths
