### ISSUE TITLE
[RFC] add new Hook

### ISSUE THREAD

**Issue by li-jia-nan** [alibaba/hooks#1761]
### 看了一下 react-use，感觉里面有一些比较有趣的 hook 可以搞过来，比如：

| hook | 功能 |
| :-: | :-: |
| **useVideo** | 播放音频，跟踪其状态，并向外暴露播放暂停调整音量等方法 |
| **useAudio** | 播放视频，跟踪其状态，并向外暴露播放暂停调整音量等方法 |
| **useFirstMount** | 是否首次渲染，类似 useMount，但是对外暴露一个布尔值 |
| **useGeolocation** | 跟踪用户设备的地址位置信息（需要用户授权） |
| **useInterval** | 定时器的钩子，与 ahooks 中的 useInterval 不同的是，可以通过将延迟设置为 null 来暂停计时 |
| **useLogger** | 可以记录生命周期的钩子，在每个生命周期打印日志 |
| **useOrientation** | 传感器钩子，监听设备的屏幕方向 |
| **useQueue** | 实现一个简单的队列，暴露 add、remove、reset 等方法（这个好像已经存在了？） |
| **useSpeech** | 可以说出指定字符串的语音,用 SpeechSynthesisUtterance 实现（不支持 IE） |
| **useRendersCount** | 记录组件渲染次数，返回一个 number 类型的值 |

（暂时想到这些，后面有其它的再补充）

### @brickspert @crazylxr @hchlq 麻烦各位 review 一下，看看哪些可以做，哪些不用做，如果可以，我想参与这件事情！

**Comment by hchlq** [comment]
其实不太需要的哈，之前作者也讲过，ahooks 是服务于一些使用比较多的业务场景，如果 hook 过多的话，使用场景不多，可能还会增加包体积的～

另外 useInterval 现在既可以满足延迟设置为 undefined 来暂停计时，同时也可以使用返回的清理函数来暂停，只是建议使用清理函数进行～

**Comment by li-jia-nan** [comment]
> 其实不太需要的哈，之前作者也讲过，ahooks 是服务于一些使用比较多的业务场景，如果 hook 过多的话，使用场景不多，可能还会增加包体积的～
> 
> 另外 useInterval 现在既可以满足延迟设置为 undefined 来暂停计时，同时也可以使用返回的清理函数来暂停，只是建议使用清理函数进行～

🫡

**Comment by hchlq** [comment]
先关掉了哈～

**Comment by li-jia-nan** [comment]
> 先关掉了哈～

好的 大佬
