### ISSUE TITLE
useCookieState 不是响应式的？

### ISSUE THREAD

**Issue by SignDawn** [alibaba/hooks#1766]
例如我修改了一个同名的 cookie ,它并不影响另外一个。
 const [message, setMessage] = useCookieState('useCookieStateString');
  const [message2, setMessage2] = useCookieState('useCookieStateString');
 
通过 setMessage2 修改值以后，并不影响 message 的结果。

这是否有必要做个监听呢？

**Comment by GpingFeng** [comment]
具体的场景是？感觉同一个页面不需要维护两个状态（针对同一个 cookie）？

**Comment by SignDawn** [comment]
目前没有遇到这样的场景。
只是疑惑在不同组件或不同页面里使用同一个 cookie .
