### ISSUE TITLE
useAntdTable中tableProps里的data为什么不能推导出类型？

### ISSUE THREAD

**Issue by pule-dpr** [alibaba/hooks#1767]

**Comment by pule-dpr** [comment]
![image](https://user-images.githubusercontent.com/73623940/179196764-915585c8-ec53-4d95-9486-c4933ebc3f4a.png)

**Comment by GpingFeng** [comment]
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/20135760/179385340-188958f5-a25e-4b4c-9005-241dec45f66d.png">


请问你是想推倒出这个 dataSource 的类型么？

**Comment by pule-dpr** [comment]
是的，原来是any[ ]

**Comment by li-jia-nan** [comment]
@crazylxr 来关issue了

**Comment by crazylxr** [comment]
3.6.2 已经发布。
