### ISSUE TITLE
[RFC] useAppendRootNode

### ISSUE THREAD

**Issue by GrinZero** [alibaba/hooks#1770]
用于往页面中插入DOM节点，因为React对于插入节点提供的传送门仍和原本的ReactTree处于同一目录，并不符合需求。通过这个hook可以往页面中插入一个全新的节点，可以用来挂载Modal、Message、ContextMenu等有一定命令式调用需求的节点。
### API
```tsx
useAppendRootNode=(
  id: string,
  render: () => JSX.Element | null,
  createElement?: () => HTMLElement,
  parent?: HTMLElement
)=>AppendRootNodeResult
```
### DEMO
```tsx
  useAppendRootNode('right-click-context-menu', () => (
    <div
      className="absolute"
      ref={ref}
      style={{
        position: 'absolute',
        left: contextMenu.x,
        top: contextMenu.y,
        display: contextMenu.visible ? 'flex' : 'none',
        zIndex: 9999999,
      }}
    >
      {menu}
    </div>
  ));

```

**Comment by brickspert** [comment]
感觉这种不用 Hooks 用起来是不是更好？

使用最基础的方法来做。

**Comment by GrinZero** [comment]
> 感觉这种不用 Hooks 用起来是不是更好？
> 
> 使用最基础的方法来做。


我感觉还是可以做一个hook的，因为要使用最基础方法做的话需要关心到`document.createElement('div')`，像我这里实现了一下：
<img width="521" alt="image" src="https://user-images.githubusercontent.com/70185413/179910718-599e0ecc-ce9e-41eb-9b4e-3bf416e84b0d.png">
里边的逻辑是在页面中确切地插入某个id为"xx"的dom节点，使用这个hook可以让使用者更少地接触来自document 的API

**Comment by miracles1919** [comment]
做成 Hook 和做成一个工具函数相比，有什么优势吗？看起来更复杂了..

```tsx
function renderToBody(element: ReactElement) {
  const container = document.createElement('div')
  document.body.appendChild(container)
  function unmount() {
    const unmountResult = ReactDOM.unmountComponentAtNode(container)
    if (unmountResult && container.parentNode) {
      container.parentNode.removeChild(container)
    }
  }
  ReactDOM.render(element, container)
  return unmount
}
```

用起来也很方便

```jsx
renderToBody(<Element />)
```

**Comment by GrinZero** [comment]
做成hook对于使用会更友好，可能我的实现上确实有某些地方比较复杂...
```js
useEffect(()=>{
    const umount=renderToBody(<div>TEST</div>)
    return umount;
})
```
设计上之所以强制要求id是要求使用者对于通过hook在页面中每一个插入的dom都是清晰的，其余的render、parent、createElement都是一些拓展性设计

**Comment by miracles1919** [comment]
> 做成hook对于使用会更友好

这个没看出来哪里更友好了.. 

我举个例子，点击按钮的时候，展示 Modal

- util 
```jsx
<button onClick={() => {
  renderToBody(<Modal />)
}}>
  弹窗
</button>
```

- hook
```jsx
const [element, setElement] = useState(null)
useAppendRootNode('id', () => element)

<button onClick={() => {
  setElement(<Modal />)
}}>
  弹窗
</button>
```

很明显用 hook 的复杂度上升了

**Comment by GrinZero** [comment]
啊不，不是你这个场景的哦。我的想法是通过hook挂载的是`ModalContainer`容器，毕竟`Message、Modal`这些弹出肯定是不只一次的。

**Comment by miracles1919** [comment]
> 我的想法是通过hook挂载的是ModalContainer容器

可以用 `ReactDOM.createPortal`

```jsx
const ModalContainer = () => (
  return (
     ReactDOM.createPortal(<Modal />, domNode)
  )
)

```

**Comment by GrinZero** [comment]
> > 我的想法是通过hook挂载的是ModalContainer容器
> 
> 可以用 `ReactDOM.createPortal`
> 
> ```js
> const ModalContainer = () => (
>   return (
>      ReactDOM.createPortal(<Modal />, domNode)
>   )
> )
> ```

传送门仍需要声明式写在页面上
```js
const App=()=>{
    return (
        <div>
           <Page/>
          <ModalContainer/>
       </div>
    )
}
```

**Comment by GrinZero** [comment]
useAppendRootNode其实也可以看作usePortal

**Comment by miracles1919** [comment]
> 传送门仍需要声明式写在页面上

没理解.. hook 不用么？

**Comment by GrinZero** [comment]
> > 传送门仍需要声明式写在页面上
> 
> 没理解.. hook 不用么？

### NoHook
```tsx
const ModalContainer = ({domNode}) => ReactDOM.createPortal(<Modal />, domNode)
const App1=()=>{
  useEffect(()=>{
    const container = document.createElement('div')
    container.id="right-click-context-menu"
    document.body.appendChild(container)
    return ()=>{
      const unmountResult = ReactDOM.unmountComponentAtNode(container)
      if (unmountResult && container.parentNode) {
        container.parentNode.removeChild(container)
      }
    }
  },[])
  return (
    <div>
      <span>这是正常使用传送门</span>
      <span>你仍需要把ModalContainer写入render的返回中</span>
      <span>同时你需要手动在页面加入一个DOM节点用于挂载</span>
      <ModalContainer domNode={document.getElementById("right-click-context-menu")}/>
    </div>
  )
}
```

### hook
```tsx
const App2=()=>{
  useAppendRootNode('right-click-context-menu', () => (
    <ModalContainer/>
  ));
  return (
    <div>
      <span>这是使用Hook</span>
      <span>你不需要把ModalContainer写入render的返回中</span>
      <span>同时在没有过多定制需求的情况下，你也无需传递domNode</span>
    </div>
  )
}
```

### Why Hook?
hook的作用不就是为了组件逻辑共享嘛，这里应该看得比较明白了

**Comment by awmleer** [comment]
我发现有两个问题

1. 更新/销毁/卸载不够明确（explicit）

render 函数更新时，例如从 `() => <Modal content='foo' />` 变为 `<Modal content='show' />`，看你现在的实现，实际会触发旧组件的销毁 & 新组件的重新创建，但是对用户来说，他可能并不会意识到这一点，会带来很多潜在的理解成本

2. Hook 的局限性

如果做成 Hook，那自然只能在 React 组件渲染中调用，而且还会受到各种限制（例如每次渲染的调用顺序和数量必须一致），很多时候，如果我们希望用户点击一个按钮，弹出一条 Toast，使用 Hook 的话未必是最方便的，可以写个 demo 试试看，毕竟你上面发的 demo 有点简单，并没有涉及到用户交互

**Comment by GrinZero** [comment]
> 我发现有两个问题
> 
> 1. 更新/销毁/卸载不够明确（explict）
> 
> render 函数更新时，例如从 `() => <Modal content='foo' />` 变为 `<Modal content='show' />`，看你现在的实现，实际会触发旧组件的销毁 & 新组件的重新创建，但是对用户来说，他可能并不会意识到这一点，会带来很多潜在的理解成本
> 
> 2. Hook 的局限性
> 
> 如果做成 Hook，那自然只能在 React 组件渲染中调用，而且还会受到各种限制（例如每次渲染的调用顺序和数量必须一致），很多时候，如果我们希望用户点击一个按钮，弹出一条 Toast，使用 Hook 的话未必是最方便的，可以写个 demo 试试看，毕竟你上面发的 demo 有点简单，并没有涉及到用户交互

OK~我今天内给一个#2的DEMO，#1的话可以调整一下：
```tsx
useAppendRootNode=(
  id: string,
  render: (() => JSX.Element) | JSX.Element | string
  createElement?: () => HTMLElement,
  parent?: HTMLElement
)=>AppendRootNodeResult

// 调用时
render instanceof Function ? render() : render
```

**Comment by GrinZero** [comment]
> 我发现有两个问题
> 
> 1. 更新/销毁/卸载不够明确（explicit）
> 
> render 函数更新时，例如从 `() => <Modal content='foo' />` 变为 `<Modal content='show' />`，看你现在的实现，实际会触发旧组件的销毁 & 新组件的重新创建，但是对用户来说，他可能并不会意识到这一点，会带来很多潜在的理解成本
> 
> 2. Hook 的局限性
> 
> 如果做成 Hook，那自然只能在 React 组件渲染中调用，而且还会受到各种限制（例如每次渲染的调用顺序和数量必须一致），很多时候，如果我们希望用户点击一个按钮，弹出一条 Toast，使用 Hook 的话未必是最方便的，可以写个 demo 试试看，毕竟你上面发的 demo 有点简单，并没有涉及到用户交互

#2的简单demo
https://codesandbox.io/s/rough-pond-durt2g

**Comment by miracles1919** [comment]
```tsx
const message = {
  success: (text: string) => {
    if (!modalControl.addChild) return;
    const id = modalControl.addChild(<div>{text}</div>);
    setTimeout(() => {
      if (!modalControl.removeChild) return;
      modalControl.removeChild(id);
    }, 3000);
  }
};

function Apps() {
  useAppendRootNode("modal-contaienr", <ModalContainer />);
  return (
    <div className="App">
      <button onClick={() => message.success("SUCCESS")}>
        Click to show Modal
      </button>
    </div>
  );
}
```

看了下你的 demo，`useAppendRootNode` 的作用仅仅是挂载/卸载了一个 container 节点

实际 `Modal` 的挂载/卸载依赖的是 `addChild`/`removeChild` 方法

使用起来还需要借助外部的变量，是不是不太方便..?

**Comment by awmleer** [comment]
1. 如果用户没有调用过 `useAppendRootNode()`，这时调用 `message.success()` 会发生什么？
2. 如果用户在多个组件内调用了 `useAppendRootNode()`，这时再调用 `message.success()` 会发生什么？
3.  如果用户调用了 `useAppendRootNode()` 返回的 `destroy()` 方法，这时再调用 `message.success()` 会发生什么？

这三种情况都蛮影响开发体验的

**Comment by GrinZero** [comment]
我觉得关注重心现在放到了Message的实现...我这里在Message的实现我感觉还是有些问题...
这是我的实际使用：
<img width="622" alt="image" src="https://user-images.githubusercontent.com/70185413/180355215-9fb7bdfb-f259-4210-82ef-6f1995cc8cd9.png">
我主要是做了个`useRightClickMenu`用来快速接入右键菜单

**Comment by awmleer** [comment]
我来总结一下吧～

1. 如果是在 React 组件内使用，那更推荐使用 portal，而不是直接 ReactDOM.render，这种情况情况下，这个 Hook 的意义不大
2. 如果是在非 React 组件的环境下使用，那就完全不能使用这个 Hook 了

所以这个 RFC 先关闭掉了，不过后续如果有更新的话，可以继续在这里讨论

**Comment by GrinZero** [comment]
我不是很认可你的总结#1...portal的作用是能够表面上渲染在一个地方，实际上渲染到了另一个地方。但是这里缺失了两个地方
1. 使用Portal你必定需要做一个渲染的流程，你需要把组件放进`render`中
2. 你需要通过原生的方式挂载一个节点或者直接写死一个节点在index.html中

**Comment by awmleer** [comment]
从你上面提供过的例子和文字描述来看，似乎都可以通过 portal 来实现，而且并不会增加代码复杂度，所以并没有很好的说明什么场景下为什么一定需要这个 Hook

如果可以的话，要不你再发一个具体的 demo，能够证明 useAppendRootNode 的**必要性**？
