### ISSUE TITLE
useRequest 轮询问题

### ISSUE THREAD

**Issue by dadanliu** [alibaba/hooks#1774]
轮询的cancel 能否通过自定义的 生命周期方法抛出来；
场景：
如果在formChange 触发轮询方法，必须单独定义一个useEffect 去监听返回值，去做cancel；
如果生命周期方法抛出来，将很简洁

**Comment by dadanliu** [comment]
轮询是否也能增加一个最大轮询次数呢？

**Comment by dadanliu** [comment]
是否接受PR

**Comment by miracles1919** [comment]
> 轮询的cancel 能否通过自定义的 生命周期方法抛出来

这是啥意思.. 能举个例子不

**Comment by dadanliu** [comment]
> > 轮询的cancel 能否通过自定义的 生命周期方法抛出来
> 
> 这是啥意思.. 能举个例子不

满足异步轮询查询全量数据的场景；
```js
useRequest(service,{
// 仅轮询5次
maxPollingCount:5,
onSuccess:(res,params,fns)=>{
if(isConditionA(res)){
fns.cancel()
}
}})
```
@miracles1919

**Comment by miracles1919** [comment]
目前已经有了"轮询错误重试次数"，这个"轮询次数"包不包含错误重试次数呢？感觉这是一个有争议的地方 

@dadanliu

**Comment by dadanliu** [comment]
是否应该限定“次数只与错误的关联“呢？还是说默认关联错误，支持自定义会不会从设计的角度来说更友好
1. 简单增加一个最大轮询次数
2. 默认次数只包括错误重试关联，支持拓展或替换成其他的关联，比如请求成功但在某种返回状态的时候。
@miracles1919

**Comment by dadanliu** [comment]
还有在onSuccess 中抛出 cancel polling 的方法，这个有考虑么。当一个页面有很多异步轮询的异步逻辑，没有这种支持很容易让逻辑走向混乱。
@miracles1919

**Comment by miracles1919** [comment]
> 默认关联错误

那不就是 `pollingErrorRetryCount` 

> 支持拓展或替换成其他的关联，比如请求成功但在某种返回状态的时候

目前的设计用户可以自己选择 `cancel` 的时机，可以自己做关联的

> 在onSuccess 中抛出 cancel polling 的方法

不太理解这句话，现在 cancel 方法不是暴露出来了么 ..？ 

```js
  const ref = useRef(0);
  const { data, loading, run, cancel } = useRequest(service, {
    pollingInterval: 1000,
    onSuccess: () => {
      ref.current++;
      console.log('ref.current', ref.current);
      if (ref.current === 3) {
        cancel();
      }
    },
  });
```
---

增加“最大轮询次数”，会带来一系列需要考虑的地方

例如：
- 包不包含错误重试次数
- 最大轮询和错误重试哪个优先级高

感觉会增加整体的复杂度

@dadanliu

**Comment by dadanliu** [comment]
> 目前的设计用户可以自己选择 cancel 的时机，可以自己做关联的

cancel 能放在，自定义的生命周期钩子中，比用户单独定义hooks去处理更简洁，
比如多次调用一个轮询请求，第一次可以根据上一次的空值和这一次的有值判断是否cancel，
但如果是第二次就需要去做 diff。

1.判断是否和第一次相同，两个分支去判断。
2.相同表示请求到了新的数据还是说上次的数据没有改变，又多了两个分支去判断；
3. 不同还需要判断是请求成功的结果还是请求失败的结果，再次多了两个分支去判断；

但其实我只需要在自定义的生命周期中，在请求成功时走对应的生命周期勾子，一个链式的调用；
而不是自定义一堆 hook，去处理这种分叉，跟上某个内部的生命周期勾子的调用时机；

@miracles1919

**Comment by miracles1919** [comment]
> cancel 能放在，自定义的生命周期钩子中

这个我一直不太理解.. cancel 不是暴露出来了么？想在哪调用就在哪调用啊

```js
  const { cancel } = useRequest(service, {
    pollingInterval: 1000,
    onSuccess: () => {
      if (condition) {
        // 在请求成功时调用 cancel 
        cancel();
      }
    },
  });
```

@dadanliu 要不你写个 demo ，看看真正的场景... 不然 get 不到你真实的痛点

**Comment by dadanliu** [comment]
https://codesandbox.io/s/dreamy-kalam-rg9dfg?file=/src/App.jsx:1824-1871
@miracles1919 大概是这个意思

**Comment by miracles1919** [comment]
```jsx
  /* 
  限制最大轮询次数 5次，
  可能中间状态走了 onSuccess 逻辑比如这里的请求中，或者就是实时变化的数据，限制了更新次数。
  Wish：综上一个此类的异步请求就多了两个 hook，期望一个useRequest hook 就可以解决。
   */
  const [pollingLimit, setPollingLimit] = useState(0);
  const { data: data5, run: run5, cancel: cancel5 } = useRequest(getUsername5, {
    pollingInterval: 3000,
    onSuccess: (data) => {
      setPollingLimit((prev) => prev + 1);
    }
  });
  useEffect(() => {
    if (Array.isArray(data5?.list)) cancel5();
    if (pollingLimit >= 3) cancel5();
  }, [data, pollingLimit]);
```
这是你的代码

其实如果用 ref 记录成功的次数，就不需要额外的 hook 

```jsx
const count = useRef(0)
const { cancel } = useRequest(getUsername5, {
    pollingInterval: 3000,
    onSuccess: (data) => {
      count.current ++
      if (count.current >= 3) cancel()
    }
  });
```

另外，最大轮询次数感觉不是很有必要，用 ref 的话很方便处理，暂时就不考虑加了

这个 pr 我先关了哈~ 有问题可以继续讨论

**Comment by dadanliu** [comment]
```js
const count = useRef(0)
const { cancel } = useRequest(getUsername5, {
    pollingInterval: 3000,
    onSuccess: (data) => {
      count.current ++
      if (count.current >= 3) cancel()
    }
  });
```
老哥 这个cancel 没抛出来，没法直接调 @miracles1919 
如果cancel 可以在自定义的生命周期里面调用确实方便很多

**Comment by miracles1919** [comment]
<img width="906" alt="image" src="https://user-images.githubusercontent.com/22469543/182780796-7b438c36-4a12-4123-ae22-a4aba5b28927.png">

cancel 不是暴露出来了么 ？

<img width="650" alt="image" src="https://user-images.githubusercontent.com/22469543/182781017-13f50fbb-67a9-4e79-aa1c-b38b88aac646.png">

在你的 demo 也用到了

**Comment by dadanliu** [comment]
是的 不过这样还要自己加一个ref 再加一个useEffect
@miracles1919

**Comment by miracles1919** [comment]
如果只是**轮训次数**的判断，一个 ref 就够了，上面提供过好几次代码了

**Comment by chiga0** [comment]
我觉得最大轮询次数还是有必要的，不然可能会有一种情况：`轮询页面打开后一直放着，然后请求了一晚上` 类似的问题。
业务侧肯定会去判断轮询停止的条件，但是不保证后端接口一定会满足条件，最好还是前端轮询的时候就限制一下最大次数，避免上述轮询一晚上发起几千次请求的情况。
