### ISSUE TITLE
[RFC] useResetState

### ISSUE THREAD

**Issue by hemengke1997** [alibaba/hooks#1776]
# 功能
跟 `React.useState` 基本一致，但是返回一个可以重置state初始值的方法

```
const [state, setState, resetState] = useResetState(initialState)

resetState() // state => initialState
```

同理，`useSetState` 也可以加此功能

解决痛点：`resetState` 在业务场景中很常见，可是开发者不得不写一份初始值，在代码维护性上也不太好

**Comment by hchlq** [comment]
感觉不是很有必要增加这个 hook 呢，可以在 useSetState 的基础上扩展～

**Comment by GpingFeng** [comment]
@hchlq 确实感觉可以支持这个功能，类似 antd 中 form 表单支持 reset 的功能。在 useSetState 中的话，咱们直接返回多一个 function。resetState?

**Comment by hchlq** [comment]
我觉得是可以的， @brickspert @crazylxr 你们觉得呢

**Comment by crazylxr** [comment]
+1，我觉得可以的

**Comment by brickspert** [comment]
感觉直接加一个 useResetState Hook 好了，在 useSetState 中增加倒是显得不伦不类了，因为 useSetState 的 API 是和 useState 保持一致的。

**Comment by hemengke1997** [comment]
> 感觉直接加一个 useResetState Hook 好了，在 useSetState 中增加倒是显得不伦不类了，因为 useSetState 的 API 是和 useState 保持一致的。

`useState` ==> `useResetState` 
`useSetState`  ==> `useResetSetState`
`reset` 的功能本身是在 `state` 类的hook上扩展的，为了保持API一致性，我认为在与 `state` 相关的hook中都加一个 "选项控制返回 or 直接返回" `reset `

**Comment by crazylxr** [comment]
> > 感觉直接加一个 useResetState Hook 好了，在 useSetState 中增加倒是显得不伦不类了，因为 useSetState 的 API 是和 useState 保持一致的。
> 
> `useState` ==> `useResetState` `useSetState` ==> `useResetSetState` `reset` 的功能本身是在 `state` 类的hook上扩展的，为了保持API一致性，我认为在与 `state` 相关的hook中都加一个 "选项控制返回 or 直接返回" `reset `

赞同

**Comment by brickspert** [comment]
> > > 感觉直接加一个 useResetState Hook 好了，在 useSetState 中增加倒是显得不伦不类了，因为 useSetState 的 API 是和 useState 保持一致的。
> > 
> > 
> > `useState` ==> `useResetState` `useSetState` ==> `useResetSetState` `reset` 的功能本身是在 `state` 类的hook上扩展的，为了保持API一致性，我认为在与 `state` 相关的hook中都加一个 "选项控制返回 or 直接返回" `reset `
> 
> 赞同

别，建议先加一个 useResetState 试试。

PS：Hooks 的能力组合是另外一个问题。比如 useSetState 和 useCookieState 组合等等。

**Comment by hemengke1997** [comment]
好的，谢谢各位的回复
这个feature由维护团队来做吗，还是说我提个pr？

**Comment by crazylxr** [comment]
可以直接提 pr 的哈。

**Comment by hemengke1997** [comment]
> 可以直接提 pr 的哈。

请问 `pnpm start` 时报错
```
Error: Cannot find module 'umi'
Require stack:
- C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+preset-built-in@3.5.28_wcqkhtmu7mswc6yz4uyexck3ty\node_modules\@umijs\preset-built-in\lib\plugins\features\forkTSChecker.js
- C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+core@3.5.28\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js
- C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+core@3.5.28\node_modules\@umijs\core\lib\Service\PluginAPI.js
- C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+core@3.5.28\node_modules\@umijs\core\lib\index.js
- C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+umi@3.5.28_react-router@5.2.0\node_modules\umi\lib\ServiceWithBuiltIn.js
- C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+umi@3.5.28_react-router@5.2.0\node_modules\umi\lib\forkedDev.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+bundler-webpack@3.5.28_hflg5r6ml7trnjm7sh3tgaza54\node_modules\@umijs\bundler-webpack\lib\requireHook.js:49:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at _umi (C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+preset-built-in@3.5.28_wcqkhtmu7mswc6yz4uyexck3ty\node_modules\@umijs\preset-built-in\lib\plugins\features\forkTSChecker.js:19:16)
    at _default (C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+preset-built-in@3.5.28_wcqkhtmu7mswc6yz4uyexck3ty\node_modules\@umijs\preset-built-in\lib\plugins\features\forkTSChecker.js:31:21)
    at C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+core@3.5.28\node_modules\@umijs\core\lib\Service\Service.js:364:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+core@3.5.28\node_modules\@umijs\core\lib\Service\Service.js:110:103)
```

项目启动需要什么node环境呢，我现在是 16.14.2

**Comment by brickspert** [comment]
> > 可以直接提 pr 的哈。
> 
> 请问 `pnpm start` 时报错
> 
> ```
> Error: Cannot find module 'umi'
> Require stack:
> - C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+preset-built-in@3.5.28_wcqkhtmu7mswc6yz4uyexck3ty\node_modules\@umijs\preset-built-in\lib\plugins\features\forkTSChecker.js
> - C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+core@3.5.28\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js
> - C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+core@3.5.28\node_modules\@umijs\core\lib\Service\PluginAPI.js
> - C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+core@3.5.28\node_modules\@umijs\core\lib\index.js
> - C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+umi@3.5.28_react-router@5.2.0\node_modules\umi\lib\ServiceWithBuiltIn.js
> - C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+umi@3.5.28_react-router@5.2.0\node_modules\umi\lib\forkedDev.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.mod._resolveFilename (C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+bundler-webpack@3.5.28_hflg5r6ml7trnjm7sh3tgaza54\node_modules\@umijs\bundler-webpack\lib\requireHook.js:49:28)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at _umi (C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+preset-built-in@3.5.28_wcqkhtmu7mswc6yz4uyexck3ty\node_modules\@umijs\preset-built-in\lib\plugins\features\forkTSChecker.js:19:16)
>     at _default (C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+preset-built-in@3.5.28_wcqkhtmu7mswc6yz4uyexck3ty\node_modules\@umijs\preset-built-in\lib\plugins\features\forkTSChecker.js:31:21)
>     at C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+core@3.5.28\node_modules\@umijs\core\lib\Service\Service.js:364:29
>     at Generator.next (<anonymous>)
>     at asyncGeneratorStep (C:\hemengke\github\hooks\node_modules\.pnpm\registry.npmmirror.com+@umijs+core@3.5.28\node_modules\@umijs\core\lib\Service\Service.js:110:103)
> ```
> 
> 项目启动需要什么node环境呢，我现在是 16.14.2

有没有执行 pnpm init

**Comment by hemengke1997** [comment]
执行了 `init` 的，成功安装依赖和打包。就是 `start` 的时候会报错

**Comment by crazylxr** [comment]
这个问题我好像遇到过，是 npm 源的问题，让我想一下。

**Comment by crazylxr** [comment]
@hemengke1997 pnpm-lock.yaml 文件有点问题，我重新 push 一个 lock 文件，你再重新 pull 一下，然后执行一下 `pnpm run clean`，然后再 `pnpm install` 一下 应该就可以了
