### ISSUE TITLE
[QUESTION]useFusionTable的formData能否拿的是field.getValues()

### ISSUE THREAD

**Issue by xmsz** [alibaba/hooks#1779]
背景
```
const field = Field.useField({
   values: {
      a: 1,
      b: 2
   }
})
<Form.Item name="b">
  <Input />
</Form.Item>
useFusionTable(({},formData)=>console.log)
```
如果我只用Form.Item声明了b，那么formData是拿不到a的值

https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useFusionTable/fusionAdapter.ts#L6

因为field.getNames()是不包含a的

然后我的场景是，有些默认值可能暂时不需要被修改，所以不会用form.Item声明，但同时又希望formData能直接用到

**Comment by miracles1919** [comment]
我试了下，能拿到呀 https://codesandbox.io/s/bold-dawn-de6rgc?file=/App.tsx

**Comment by xmsz** [comment]
> 我试了下，能拿到呀 https://codesandbox.io/s/bold-dawn-de6rgc?file=/App.tsx

你的例子里，Form.Item 没有设置name

```
 <Form.Item label="b" name="b">
          <Input />
        </Form.Item>
```

**Comment by miracles1919** [comment]
这个需求不太符合目前的设计，Form 的字段是支持隐藏的，隐藏后就不该读取到了

具体可以看下官网 ”简易表单/复杂表单“ 切换的例子

**Comment by xmsz** [comment]
> 这个需求不太符合目前的设计，Form 的字段是支持隐藏的，隐藏后就不该读取到了
> 
> 具体可以看下官网 ”简易表单/复杂表单“ 切换的例子

好吧 我现在只能

```
 <div className="hidden">
            {['planID', 'start', 'end'].map((item) => (
              <Form.Item name={item} key={item}>
                <Input />
              </Form.Item>
            ))}
  </div>
```

或者直接在service里调用field.getValues()

**Comment by miracles1919** [comment]
嗯，先自行处理吧，这个 issue 我先关了，后面有问题可以继续讨论 ~
