### ISSUE TITLE
为什么useAntdTable返回的search.submit要把没有用<Form.Item>包裹的field过滤掉？

### ISSUE THREAD

**Issue by ggd543** [alibaba/hooks#178]
https://github.com/umijs/hooks/blob/v1.5.0/src/useAntdTable/index.ts#L279

是否应该提供一个可选项，由调用方决定是否过滤掉？

**Comment by brickspert** [comment]
不是吧。 和 <Form.Item> 没关系吧。

目前会把用 getFieldDecorator 声明的 filed 加上去。

你标的这段代码，是用来处理 某些字段 消失后，需要废弃相关 filed 的情况。

不过我没想明白，在什么情况下会出问题呢？可否写个 codesandbox，复现一下你的需求呢？

**Comment by brickspert** [comment]
先关闭了。如果有问题再打开哦。
