### ISSUE TITLE
ready再次为false时,仍然会触发请求

### ISSUE THREAD

**Issue by GeSnowBoy** [alibaba/hooks#1780]
## 问题描述

>  `ready` 从 `false` 变成 `true` 的时候, 请求正常发出. 当 `ready` 再次变成 `false` 的时候, `refreshDeps` 的变化仍然会触发请求发出. 且调用 `run` 不会发出请求.

## 希望结果
> `ready` 为 `false` 的时候, 永远不能发送请求

## 展示链接

[点击跳转CodeSandbox](https://codesandbox.io/s/read-username-forked-0heuk0?file=/App.tsx)

##  修改理由
*  如果`ready` 为 `false` 仍然可以发送请求,那么这个配置就毫无意义,而且极易引发bug,需要用户在 `ready` 处 写一遍判断,发送请求的时候还需在写一遍判断, 没有任何意义. 为何不在请求前加下判断呢? 那么这个 `ready` 就没有任何意义了
* `ready` 再次变成 `false`的时候,  主动触发 `run` 不会发送请求, 但是 `refreshDeps`的变化却能引发请求,所以两种截然不同的表现让人很难理解
*  `ready` 为 `false`还能发送请求这个在阅读理解上让人难以接受

![image](https://user-images.githubusercontent.com/17561864/180753056-a2c0c5da-0f12-41f7-868e-6ee7bab186a7.png)

**Comment by GeSnowBoy** [comment]
3.0.0-alpha.14 版本上好像已经修复了 我用的版本太低了

**Comment by crazylxr** [comment]
那就关了哈
