### ISSUE TITLE
useDynamicList  按照antd中使用树形数据 ，展开时会报错

### ISSUE THREAD

**Issue by pangxzi** [alibaba/hooks#1782]
按照antd使用树形数据，展开会报错
![image](https://user-images.githubusercontent.com/52907799/180987730-a0f9a6f2-4ce6-447b-a556-014baa201db9.png)

![image](https://user-images.githubusercontent.com/52907799/180987505-67b7128b-9a00-495c-8e60-aae5a8e4ee6d.png)

**Comment by miracles1919** [comment]
能提供下在线的 demo 不，例如 https://codesandbox.io/s/wr11ms

**Comment by pangxzi** [comment]
> 能提供下在线的 demo 不，例如 https://codesandbox.io/s/wr11ms

https://codesandbox.io/s/chuan-ru-dom-yuan-su-forked-r3uq0r?file=/App.tsx

**Comment by miracles1919** [comment]
看起来是 antd 的使用问题

可以看下 antd form 的规则 [https://github.com/react-component/field-form/pull/111](https://github.com/react-component/field-form/pull/111)

**Comment by miracles1919** [comment]
这个 issue 我先关了哈，有问题可以继续讨论 ~
