### ISSUE TITLE
类型“Parameters<T>”必须具有返回迭代器的 "[Symbol.iterator]()" 方法。

### ISSUE THREAD

**Issue by zxxvGW** [alibaba/hooks#1785]
https://github.com/alibaba/hooks/blob/0278f9b9390625bf181f039205b2b34d94ee3836/packages/hooks/src/useDebounceFn/index.ts#L25
![image](https://user-images.githubusercontent.com/51041769/181294874-f83e0734-8dd2-4303-96be-ee9159aada35.png)

不知道为啥下载源码下来不会TS报错，用的TS版本不对？（"typescript": "^4.6.4"）
![image](https://user-images.githubusercontent.com/51041769/181295013-2934d4ef-be8d-425f-aef8-1db6428e58de.png)

改成这样就不会报错了

**Comment by zxxvGW** [comment]
最后打包出来的文件，也是通过apply调用的
![image](https://user-images.githubusercontent.com/51041769/181293804-8f3b3baf-2bd3-4316-8fe2-72e653ea8fa8.png)

**Comment by hchlq** [comment]
不太理解这里是表达啥呢...

报错是在哪复现的？，源码没报这个 TS 错误的～

**Comment by zxxvGW** [comment]
> 不太理解这里是表达啥呢...
> 
> 报错是在哪复现的？，源码没报这个 TS 错误的～

可能和使用ts的版本有关，看这里。https://codesandbox.io/s/agitated-bird-72hjm7?file=/src/hooks/index.ts

**Comment by hchlq** [comment]
代码我升级到 4.7.2 还是没有复现这个问题，不知道 codesandbox 咋编译的，可以先不用管这个问题哈

另外，只要改成 `type noop = (...args: any[]) => any;` 就可以解决了
