### ISSUE TITLE
pnpm build 遇到的问题

### ISSUE THREAD

**Issue by dadanliu** [alibaba/hooks#1786]
![image](https://user-images.githubusercontent.com/78400194/181672469-3136c9ea-e960-469d-b724-3cc99caba03b.png)
拉下来起项目，貌似是走 gulpfile.js 报的处理typescript 报的错，这个是什么问题哦

**Comment by dadanliu** [comment]
pnpm 版本问题

**Comment by miracles1919** [comment]
总结一下：
- pnpm 7.1.9 ✅
- pnpm > 7.1.9 ❎
- ts > 3.9 ❎
