### ISSUE TITLE
关于useRequest的轮询功能，pollingWhenHidden=false时发起请求时机的一点疑问。

### ISSUE THREAD

**Issue by icy9596** [alibaba/hooks#1787]
在 pollingWhenHidden=false 的场景下，目前的轮询的实现逻辑是：
当上一次请求结束之后，检查当前的页面是否是可见的，页面可见->发起请求，页面不可见->订阅页面可见事件，触发事件时立即请求。

这似乎存在一个小问题，在以下场景中：
假如上一次请求结束之后，页面是可见状态，然后开启定时器，在到定时器到期时间之前用户切到了别的标签页，原来的页面变成不可见，等定时器时间到了之后请求还是会发出，感觉好像和pollingWhenHidden=false的效果不太对，理想情况应该是不会发出这个请求。

是否可以这样调整：
当上次请求结束之后，直接开启定时器，定时器的时间到了之后走再原来的判断逻辑：页面可见->请求，页面不可见->订阅事件。

代码调整如下：
```javascript
// usePollingPlugin.ts

timerRef.current = setTimeout(() => {
  if (!pollingWhenHidden && !isDocumentVisible()) {
    unsubscribeRef.current = subscribeReVisible(() => {
      fetchInstance.refresh();
    });
  } else {
      fetchInstance.refresh();
  }
}, pollingInterval);
```

**Comment by hchlq** [comment]
能提供修改前后的 demo 吗，给个 codesandbox 最好哈

**Comment by icy9596** [comment]
大概是这个情况：

https://codesandbox.io/s/reverent-sun-xd0n66?file=/src/App.js

**Comment by hchlq** [comment]
@brickspert 大龙哥你觉得呢

**Comment by brickspert** [comment]
应该没啥问题，可以提个 PR，Thanks♪(･ω･)ﾉ

**Comment by icy9596** [comment]
感谢，已提。

**Comment by crazylxr** [comment]
3.7.0 已发布
