### ISSUE TITLE
babel-plugin-import配置ahooks按需加载后createUpdateEffect报错

### ISSUE THREAD

**Issue by mushan0x0** [alibaba/hooks#1791]
会报错找不到createUpdateEffect
![image](https://user-images.githubusercontent.com/29084441/182096689-cfcb29ee-20cb-4b54-bc94-fdb41feddb40.png)
![image](https://user-images.githubusercontent.com/29084441/182096725-b7673710-8007-47f3-864e-0f3e40e1868a.png)

**Comment by miracles1919** [comment]
能提供下复现的包么 👀

**Comment by mushan0x0** [comment]
> 能提供下复现的包么 👀

[v115zc 2.zip](https://github.com/alibaba/hooks/files/9234383/v115zc.2.zip) @miracles1919

**Comment by miracles1919** [comment]
确实有这个问题，在 pr 里回你了哈
