### ISSUE TITLE
能否添加: 轮询之前执行一些操作

### ISSUE THREAD

**Issue by Valar103769** [alibaba/hooks#1792]
轮训之前需要修改参数里的时间为最新时间,所以能增加一个beforeHook吗?

**Comment by miracles1919** [comment]
[文档中有写](https://ahooks.js.org/zh-CN/hooks/use-request/polling#%E5%A4%87%E6%B3%A8
)
> 如果设置 options.manual = true，则初始化不会启动轮询，需要通过 run/runAsync 触发开始。

设置成手动的是不是就可以了

**Comment by Valar103769** [comment]
> [文档中有写](https://ahooks.js.org/zh-CN/hooks/use-request/polling#%E5%A4%87%E6%B3%A8)
> 
> > 如果设置 options.manual = true，则初始化不会启动轮询，需要通过 run/runAsync 触发开始。
> 
> 设置成手动的是不是就可以了

肯定不行啊, 而且轮训跟manual无关 哈哈

**Comment by miracles1919** [comment]
你说的是哪个 hook，要么举个例子？

**Comment by brickspert** [comment]
直接在 service 里面写这个逻辑就可以的。

```ts
useRequest(()=> {
  return doSomething(new Date());
}, {
  .....
})
```

**Comment by Valar103769** [comment]
> 

那手动选择时间, 手动请求的时候呢?

**Comment by miracles1919** [comment]
```js
const { run } = useRequest((date) => {
  return doSomething(date);
}, { manual: true })

// 选择时间后手动请求
run(time)
```

**Comment by brickspert** [comment]
> 

手动的时候可以一样的。

```ts
const run = useRequest((params)=> {
  return doSomething(...params, new Date());
}, {
  manual: true,
  .....
})

run({})
```

**Comment by Valar103769** [comment]
> > 
> 
> 手动的时候可以一样的。
> 
> ```ts
> const run = useRequest((params)=> {
>   return doSomething(...params, new Date());
> }, {
>   manual: true,
>   .....
> })
> 
> run({})
> ```

需求是, 手动选择时间时, 使用params传递的参数, 轮训时总是使用最新的时间

**Comment by brickspert** [comment]
> > > 
> > 
> > 
> > 手动的时候可以一样的。
> > ```ts
> > const run = useRequest((params)=> {
> >   return doSomething(...params, new Date());
> > }, {
> >   manual: true,
> >   .....
> > })
> > 
> > run({})
> > ```
> 
> 需求是, 手动选择时间时, 使用params传递的参数, 轮训时总是使用最新的时间

那也可以呀，你整个 ref 来记录最新的时间，轮询的时候 service 每次去读取 ref 的时间。
