### ISSUE TITLE
useVirtualList new param of `listChgSignal`

### ISSUE THREAD

**Issue by at86** [alibaba/hooks#1798]
```
const useVirtualList = <T = any>(list: T[], options: Options<T>) => {
// change to 
const useVirtualList = <T = any>(list: T[], options: Options<T>, listChgSignal:any) => {
```

```
  const totalHeight = useMemo(() => {
    ......
  }, [list, listChgSignal]);

 useEffect(() => {
   ......
  }, [size?.width, size?.height, list, listChgSignal]);
```
add new param `listChgSignal`, put `listChgSignal` beside of `list` , a large `list` for performance not statefull, need `listChgSignal` tell list change.

**Comment by miracles1919** [comment]
https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useVirtualList/index.ts#L105-L109

list change with a shallow copy, so `[list, listChgSignal]` is equivalent to `[list]`

It's not need to add new param
