### ISSUE TITLE
🐛[Bug] useCountdown返回值与文档不一致

### ISSUE THREAD

**Issue by darkdx** [alibaba/hooks#1800]
![image](https://user-images.githubusercontent.com/88136242/183392849-71b59e5e-a7b4-47be-9ab9-d1986ff06072.png)
![image](https://user-images.githubusercontent.com/88136242/183393074-6b0a0315-60e7-4267-821f-ff412fd9722a.png)
问题描述： 返回结果与文档不一致，少个参数

**Comment by li-jia-nan** [comment]
唉？是官方文档吗？为什么你的文档跟我的文档不一样？

**Comment by darkdx** [comment]
> 唉？是官方文档吗？为什么你的文档跟我的文档不一样？

https://ahooks.gitee.io/ahooks-v2/zh-CN/hooks/state/use-count-down 这个文档

**Comment by darkdx** [comment]
已解决，最新文档 https://ahooks.js.org/zh-CN/hooks/use-count-down

**Comment by li-jia-nan** [comment]
> > 唉？是官方文档吗？为什么你的文档跟我的文档不一样？
> 
> https://ahooks.gitee.io/ahooks-v2/zh-CN/hooks/state/use-count-down 这个文档

这是v2的文档，你安装的应该是v3

**Comment by darkdx** [comment]
> > > 唉？是官方文档吗？为什么你的文档跟我的文档不一样？
> > 
> > 
> > https://ahooks.gitee.io/ahooks-v2/zh-CN/hooks/state/use-count-down 这个文档
> 
> 这是v2的文档，你安装的应该是v3

对的，已发现问题，感谢回复！🙏🏻
