### ISSUE TITLE
useSetState 不能获取到最新的state

### ISSUE THREAD

**Issue by medmin** [alibaba/hooks#1801]
最小可复现的code: https://codesandbox.io/s/intelligent-drake-rbe918

```

  const [state, setState] = useSetState<State>({
    hello: "",
    count: 0
  });

    const log = () => {
      setState((prev) => ({ count: prev.count + 1 }));
      console.log(state.count);
    };
```

上面这个code，永远是先打印出来+1之前的count的值，而不是+1之后的值

请问怎样才能让count打印出最新的count值？

**Comment by haobarry** [comment]
同样的问题  这个是异步的操作么? @medmin

**Comment by liuyib** [comment]
> 同样的问题 这个是异步的操作么? @medmin

@haobarry 是异步的。这是 React 的固有特性，setState 在浏览器渲染的下一帧才会真正被更新，同一个函数体中的**同步代码**属于同一帧，自然拿不到最新值。

需要同一个函数体获取最新值的话，需要用 ref 处理，可以参考 https://github.com/alibaba/hooks/pull/2348/files#diff-76c61d62531ecc700f45674c682088d71bd18965b9a3e906c084821a362378ef 的思路自己处理下。
