### ISSUE TITLE
希望能抛出一个请求之前的回调

### ISSUE THREAD

**Issue by cuiaiguanggh** [alibaba/hooks#1809]
能否加一个请求之前的回调函数，这样可以在发起请求之前做一些逻辑

**Comment by miracles1919** [comment]
可以设置成手动的，在逻辑处理完成后，调用 `run/runAsync`

**Comment by cuiaiguanggh** [comment]
手动方式确实可以，但是语法风格就不一样了不是？



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: github-actions[bot] ***@***.***>
发送时间: Monday, August 15, 2022 9:47:30 AM
收件人: alibaba/hooks ***@***.***>
抄送: Afterain ***@***.***>; Author ***@***.***>
主题: Re: [alibaba/hooks] 希望能抛出一个请求之前的回调 (Issue #1809)


Hi, cuiaiguanggh.

It seems that this issue is a bit vague and lacks some necessary information.

看起来这条 issue 描述得有些模糊，缺少一些必要的信息。

―

**Comment by crazylxr** [comment]
那你可以自己写在 service 里，像这样
```js
useRequest(() => {
  // 请求之前的逻辑。
 // 发起请求的 code
})
```

**Comment by cuiaiguanggh** [comment]
这个没用暴露出api啊

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: lxr ***@***.***>
发送时间: Monday, August 15, 2022 10:01:55 AM
收件人: alibaba/hooks ***@***.***>
抄送: Afterain ***@***.***>; Author ***@***.***>
主题: Re: [alibaba/hooks] 希望能抛出一个请求之前的回调 (Issue #1809)


那你可以自己写在 service 里，像这样

useRequest(() => {

  // 请求之前的逻辑。

 // 发起请求的 code

})

―

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/184565597-f35ce55a-880a-4760-bccf-6a33a21009ce.png)


有个 onBefore 参数的

**Comment by cuiaiguanggh** [comment]
真的吗我看看，我就说这不应该没用的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 砖家 ***@***.***>
发送时间: Monday, August 15, 2022 10:05:21 AM
收件人: alibaba/hooks ***@***.***>
抄送: Afterain ***@***.***>; Author ***@***.***>
主题: Re: [alibaba/hooks] 希望能抛出一个请求之前的回调 (Issue #1809)


[image]<https://user-images.githubusercontent.com/12526493/184565597-f35ce55a-880a-4760-bccf-6a33a21009ce.png>

有个 onBefore 参数的

―

**Comment by cuiaiguanggh** [comment]
我知道了，我用的是ice封装了一层的request  它把这个去掉了

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 崔 爱广 ***@***.***>
发送时间: Monday, August 15, 2022 10:07:07 AM
收件人: alibaba/hooks ***@***.***>; alibaba/hooks ***@***.***>
抄送: Author ***@***.***>
主题: Re: [alibaba/hooks] 希望能抛出一个请求之前的回调 (Issue #1809)

真的吗我看看，我就说这不应该没用的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 砖家 ***@***.***>
发送时间: Monday, August 15, 2022 10:05:21 AM
收件人: alibaba/hooks ***@***.***>
抄送: Afterain ***@***.***>; Author ***@***.***>
主题: Re: [alibaba/hooks] 希望能抛出一个请求之前的回调 (Issue #1809)


[image]<https://user-images.githubusercontent.com/12526493/184565597-f35ce55a-880a-4760-bccf-6a33a21009ce.png>

有个 onBefore 参数的

―

**Comment by cuiaiguanggh** [comment]
也不是  是老的版本没有

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 崔 爱广 ***@***.***>
发送时间: Monday, August 15, 2022 10:09:20 AM
收件人: alibaba/hooks ***@***.***>; alibaba/hooks ***@***.***>
抄送: Author ***@***.***>
主题: Re: [alibaba/hooks] 希望能抛出一个请求之前的回调 (Issue #1809)

我知道了，我用的是ice封装了一层的request  它把这个去掉了

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 崔 爱广 ***@***.***>
发送时间: Monday, August 15, 2022 10:07:07 AM
收件人: alibaba/hooks ***@***.***>; alibaba/hooks ***@***.***>
抄送: Author ***@***.***>
主题: Re: [alibaba/hooks] 希望能抛出一个请求之前的回调 (Issue #1809)

真的吗我看看，我就说这不应该没用的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 砖家 ***@***.***>
发送时间: Monday, August 15, 2022 10:05:21 AM
收件人: alibaba/hooks ***@***.***>
抄送: Afterain ***@***.***>; Author ***@***.***>
主题: Re: [alibaba/hooks] 希望能抛出一个请求之前的回调 (Issue #1809)


[image]<https://user-images.githubusercontent.com/12526493/184565597-f35ce55a-880a-4760-bccf-6a33a21009ce.png>

有个 onBefore 参数的

―

**Comment by crazylxr** [comment]
好的，那 close 了

**Comment by cuiaiguanggh** [comment]
> 好的，那 close 了

好的

**Comment by chj-damon** [comment]
onBefore里面要怎么做？我现在是通过throw new Error的方式来阻止，但是感觉不太优雅。

**Comment by crazylxr** [comment]
> onBefore里面要怎么做？我现在是通过throw new Error的方式来阻止，但是感觉不太优雅。

直接 cancel 就可以了
