### ISSUE TITLE
3.7.0 useDrag data 闭包问题， data更新后， useDrop得到的还是旧的数据

### ISSUE THREAD

**Issue by Superman-wc** [alibaba/hooks#1818]
useDrag({index:number},  ref, {});

useDrag 里边 useEffectWithTarget(effect, deps, target);

其中的deps为[]; 导致effect中的onDragStart里边 event.dataTransfer.setData('custom', JSON.stringify(data)); 的data始终都是初始的数据

ahooks version 3.7.0

**Comment by crazylxr** [comment]
能直接放个 codesandbox 的demo 么

**Comment by Superman-wc** [comment]
https://codesandbox.io/s/ji-chu-yong-fa-forked-b76nl5?file=/App.tsx


codesandbox 例子
