### ISSUE TITLE
useMutationObserver 不存在

### ISSUE THREAD

**Issue by H-Sven** [alibaba/hooks#1819]
在"ahooks": "^3.1.9"版本中， useMutationObserver似乎被移除了？

报错
```
"export 'useMutationObserver' was not found in 'ahooks'
```

**Comment by H-Sven** [comment]
但是你们官方文档上面还有这个hooks

**Comment by hchlq** [comment]
useMutationObserver 是最近才有的 hook，3.1.9 版本是没有的～

**Comment by crazylxr** [comment]
useMutationObserver 是 3.6.2 发布的，你看下你的  ahooks 版本是多少
