### ISSUE TITLE
useDynamicList使用antd的Table的scroll后，拖拽会报错

### ISSUE THREAD

**Issue by pangxzi** [alibaba/hooks#1820]
https://codesandbox.io/s/ke-tuo-zhuai-de-dong-tai-biao-ge-forked-bwwd3g?file=/App.tsx

**Comment by miracles1919** [comment]
我试了下，没有报错... 有一堆 antd 的 warnning，感觉是 Table 的用法问题？

**Comment by pangxzi** [comment]
> 我试了下，没有报错... 有一堆 antd 的 warnning，感觉是 Table 的用法问题？

你向上拖一下，list就会多出来一项

**Comment by miracles1919** [comment]
看了下问题出在这里

```jsx
<ReactDragListView
  onDragEnd={(oldIndex: number, newIndex: number) => move(oldIndex, newIndex)}
>
  <Table 
    scroll={{ x: 600 }}
   />
</<ReactDragListView>
```

以你的 demo 举例，list 长度为 4，item 下标为 0 - 3 

- 存在 `scroll` prop 时移动 item 3 至 item 2 ，onDragEnd 方法里 `oldIndex: 4, newIndex: 3`，而 move 方法会移动 old/new item，此时 list 就会 +1（`list[4] = undefined`）
- 去掉 `scroll` prop ，移动 item 3 至 item 2，onDragEnd 方法里 `oldIndex: 3, newIndex: 2`，表现符合预期

所以看起来是组件的问题（或者使用问题？），跟 useDynamicList 没有关系

**Comment by pangxzi** [comment]
> 看了下问题出在这里
> 
> ```js
> <ReactDragListView
>   onDragEnd={(oldIndex: number, newIndex: number) => move(oldIndex, newIndex)}
> >
>   <Table 
>     scroll={{ x: 600 }}
>    />
> </<ReactDragListView>
> ```
> 
> 以你的 demo 举例，list 长度为 4，item 下标为 0 - 3
> 
> * 存在 `scroll` prop 时移动 item 3 至 item 2 ，onDragEnd 方法里 `oldIndex: 4, newIndex: 3`，而 move 方法会移动 old/new item，此时 list 就会 +1（`list[4] = undefined`）
> * 去掉 `scroll` prop ，移动 item 3 至 item 2，onDragEnd 方法里 `oldIndex: 3, newIndex: 2`，表现符合预期
> 
> 所以看起来是组件的问题（或者使用问题？），跟 useDynamicList 没有关系

还有个问题，就是列表超过一个屏幕，拖拽的时候页面不会随着鼠标往下移动，这个是ReactDragListView这个组件的问题？

**Comment by miracles1919** [comment]
应该是的
