### ISSUE TITLE
如何通过 useRequest 发送网络请求？

### ISSUE THREAD

**Issue by liuzhaowei55** [alibaba/hooks#1824]
文档翻来覆去找没有看到如何直接传递 host、path、params 等参数，是需要自己通过 axios 等库构建 Promise 然后放在 useRequest 中使用吗？看到有其他 issue 中有提到可以直接传入 fetch 的参数来发送请求，尝试了一下又 type error，能提供一个直接发送网络请求的例子吗？

**Comment by li-jia-nan** [comment]
```ts
const getNotifications = (pageNumber, pageSize) => {
  return axios({
    method: 'POST',
    url: `/api/users/me`,
    data: { page: pageNumber, size: pageSize },
  });
};

const App = () => {

  const { data, error, loading, run } = useRequest(() => getNotifications(1, 10));

  if (loading) {
    return <div>loading……</div>;
  }

  if (error) {
    return <div>{error.message}</div>;
  }

  return (
    <>
      <div>{data}</div>
    </>
  );
}
```

**Comment by liuzhaowei55** [comment]
OK，这样一眼就能看明白了，希望可以更新在文档中。

**Comment by miracles1919** [comment]
useRequest 里的第一个例子不就是么...

![image](https://user-images.githubusercontent.com/22469543/186298045-344c53cc-544a-460d-a26f-662b538b42cb.png)

**Comment by liuzhaowei55** [comment]
![image](https://user-images.githubusercontent.com/1835787/186428458-fa49cdb4-b3e3-4b65-bda2-dc8db44dd3db.png)

这应该算是知识诅咒吧，第一次看到文档我的理解 useRequest 是用来替换掉 axios，Fetch 这些的，现在了解这个 hook 的应用场景了。

**Comment by li-jia-nan** [comment]
@crazylxr close
