### ISSUE TITLE
useRequest的取消请求

### ISSUE THREAD

**Issue by aloniacode** [alibaba/hooks#1826]
能否在useRequest的onBefore中进行请求的取消？
主要是想把参数的判断放在onBefore中，但是useRequest中使用cancel()和return都无效。

**Comment by miracles1919** [comment]
onBefore 里可以用 cancel 的

**Comment by aloniacode** [comment]
> onBefore 里可以用 cancel 的

```
const {
    run: runxxxxx,
    loading,
    cancel,
  } = useRequest(xxxx, {
    manual: true,
    onBefore: (params) => {
      if (params[0].message === '' || params[0].description === '') {
        cancel();
      }
    },
    onSuccess: (res) => {
      if (res) {
     ...
      }
    },
  });
```
取消不了，还是会发送的

**Comment by miracles1919** [comment]
> 取消不了，还是会发送的

这是预期行为... cancel 只是放弃对本次请求的响应，并不会终止本次请求

useRequest 只是对 Promise 的管理，不会去终止 Promise 的

**Comment by aloniacode** [comment]
> > 取消不了，还是会发送的
> 
> 这是预期行为... cancel 只是放弃对本次请求的响应，并不会终止本次请求
> 
> useRequest 只是对 Promise 的管理，不会去终止 Promise 的

这样的话，官方文档的说明描述多少有点误导人。。。
![image](https://user-images.githubusercontent.com/55039022/186561644-d1c1af5e-e7e5-4756-a7df-f35b3658896c.png)

**Comment by miracles1919** [comment]
嗯嗯 我们更新下文档

**Comment by li-jia-nan** [comment]
@crazylxr close

**Comment by chj-damon** [comment]
只是更新了一下文档吗？那这个问题有什么办法可以解？

**Comment by crazylxr** [comment]
> 只是更新了一下文档吗？那这个问题有什么办法可以解？

promise 是没办法终止的

**Comment by chj-damon** [comment]
现在发现，即便是在onBefore里面调用了cancel方法，但是loading的状态还是没有变。
