### ISSUE TITLE
useRequest 轮询重启

### ISSUE THREAD

**Issue by kongmoumou** [alibaba/hooks#1827]
当前 useRequest 轮询在 pollingInterval 由 0 变成其他值时不会启动轮询，需要手动 refresh 一次才能启动轮询，符合预期么？

看了下源码里只有停止轮询的逻辑，没有重启逻辑，是否需要添加 🤣 @crazylxr 

```diff
useUpdateEffect(() => {
  if (!pollingInterval) {
    stopPolling();
+   return () => fetchInstance.refresh()
  }
}, [pollingInterval]);
```

PS: 另外两家 react-query 跟 swr 都支持轮询重启～

**Comment by jk4235** [comment]
+1 由0变成其他值不会重启比较迷惑

**Comment by brickspert** [comment]
这个确实是个 BUG，需要修复一下。

**Comment by li-jia-nan** [comment]
我来试试

**Comment by brickspert** [comment]
这个我重新思考了一下，目前的实现应该是没有问题的。

`pollingInterval` 自己是不会自动触发 service 执行的，它只会控制在一次执行之后，需不需要进行下一次请求。

所以在 `pollingInterval=0` 的时候，一次请求完，不会继续请求。
在 `pollingInterval>0` 的时候，一次请求完，会继续请求。

结论是：`pollingInterval` 不会自己触发执行，只会控制一次执行完后，要不要进行下一次执行。需要自己用 `run` 来触发执行。

> 本质上使用到自动触发执行的地方，都需要同时考虑 `manual`、`ready` 等参数。

**Comment by kongmoumou** [comment]
好吧，那现在 0->1 只能手动触发请求了 🤔

**Comment by jk4235** [comment]
useInterval可以通过更新 delay 重启,这里 pollingInterval 又无法重启,总感觉不太一致

那还不如用useInterval自己封装下(我现在也是这么做的

在业务层面 重启轮询 应该还是一个挺常见的需求,特别是和一些表格封装在一起

**Comment by kongmoumou** [comment]
如果确定不重启感觉还是文档里说明一下吧 😂 @brickspert

**Comment by 18518300669** [comment]
文档说明一下吧，只说了支持动态变化，还以为是我的逻辑有问题，试了好几次不知道为什么，

**Comment by liuyib** [comment]
> 文档说明一下吧，只说了支持动态变化，还以为是我的逻辑有问题，试了好几次不知道为什么，

文档我补充下。想了解下，什么场景下需要通过控制 `pollingInterval = 0` 停止轮询，然后再设置 `pollingInterval = 非 0` 来启动轮询呢？这样场景下通过 `cancel, run` 一样可以实现停止和重启，为什么一定要通过更新 `pollingInterval` 来实现呢？麻烦解答下疑惑~

**Comment by 18518300669** [comment]
> > 文档说明一下吧，只说了支持动态变化，还以为是我的逻辑有问题，试了好几次不知道为什么，
> 
> 文档我补充下。想了解下，什么场景下需要通过控制`pollingInterval = 0`停止轮询，然后再设置`pollingInterval = 非 0`来启动轮询呢？这样的场景下通过`cancel, run`同样可以实现停止和重启，为什么一定要通过更新`pollingInterval`来实现呢？麻烦解答下疑惑~

我的场景是根据接口返回值设置是否轮询以及轮询的时间，然后默认值是0（不开启轮询），然后我以为pollingInterval是一个变量就能做到支持开关和设置

**Comment by liuyib** [comment]
> 我的场景是根据接口返回值设置是否轮询以及轮询的时间，然后默认值是0（不开启轮询），然后我以为pollingInterval是一个变量就能做到支持开关和设置

原来如此，受教了。确实如果 pollingInterval 从 0 -> 非0 如果能自动开启轮询貌似更方便些，后面可以考虑支持这个，但不一定哈~

**Comment by xmsz-stu** [comment]
这就会触发一个比较好玩的

比如让用户自定义间隔时间，然后用户一般是会先清空(变成0)，然后再修改成其他值，然后这种行为就会导致定时中止
就算再修改其他值也没用了

解决办法
- 判断>0，手动开启
- 严格控制间隔时间，传递给useRequest的时候不能低于最小值
