### ISSUE TITLE
use-infinite-scroll: 在回调的钩子中拿不到，全量的数据，能不能增加一个钩子，来取全量数据

### ISSUE THREAD

**Issue by xiaoliangpan** [alibaba/hooks#1828]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/13153085/186324344-ecb2d18d-dfbb-4bb2-b040-5b5c561cfc43.png">
类似上面的代码，在回调的钩子拿到全量数据，

现在获取方式：
不然外部组件获取全量数据需要使用useEffect(() => {

},[data]) 增加周期时长，不太友好

**Comment by brickspert** [comment]
你 use-infinite-scroll 是哪里的代码呀。。我看不是 ahooks useInfiniteScroll 代码呀。

**Comment by xiaoliangpan** [comment]
> 



> 你 use-infinite-scroll 是哪里的代码呀。。我看不是 ahooks useInfiniteScroll 代码呀。

在你的代码基础上改了，能获得我想说的效果，但是真正的实现，比较尊重你们的实现规范。
