### ISSUE TITLE
How can I contribute to the page?

### ISSUE THREAD

**Issue by szachy113** [alibaba/hooks#1833]
Hi guys, just a quick question. How do I access the actual source code of a page? I'd like to contribute (namely, fix some bug). How can I do that?

Thanks in advance! 🙏🏻

**Comment by crazylxr** [comment]
You can read this article： https://opensource.com/article/19/7/create-pull-request-github

**Comment by szachy113** [comment]
@crazylxr Yes, sir. I know how to create a PR. However, what I don't know is how to contribute specifically to the [page](https://ahooks.js.org/) itself. I don't see any of the components in the source code 🙂

**Comment by miracles1919** [comment]
docs/index.en-US.md

**Comment by brickspert** [comment]
1. First, you should start the project in you local.

```bash
$ git clone git@github.com:alibaba/hooks.git
$ cd hooks
$ pnpm run init
$ pnpm start
```

2. Then, you should search the keyword. The code for the page is here `/packages/hooks/src/**/index.en-US.md`

**Comment by szachy113** [comment]
I don't think we understand each other well. I'd like to work on that particular site: https://ahooks.js.org. Not on docs, not on hooks, but rather -- on the site itself. Is this even possible since it's all "powered by dumi"? 🤔

**Comment by ysh199882** [comment]
> I don't think we understand each other well. I'd like to work on that particular site: https://ahooks.js.org. Not on docs, not on hooks, but rather -- on the site itself. Is this even possible since it's all "powered by dumi"? 🤔

Do you mean to join this organization?

**Comment by szachy113** [comment]
@ysh199882 Nope.

**Comment by brickspert** [comment]
> @ysh199882 Nope.
Maybe you are finding [dumi](https://d.umijs.org/)?

**Comment by szachy113** [comment]
No one will answer, I suppose ☹️

**Comment by crazylxr** [comment]
It's not that we're here to help you, but we don't know what you want
