### ISSUE TITLE
请教一个用法上的问题

### ISSUE THREAD

**Issue by oldturkey** [alibaba/hooks#184]
比如useSearch这个组件的例子，在select中，我们需求往往是选中之后根据选中的值来做一些事情，例如onselect事件去触发操作，在用hooks编写的纯函数组件里面，想把这个select的值告诉外面其他组件去做各种操作该用什么方案，看例子里的代码没有提到，感觉是否只能加上store才能达到这种最基本的场景需求了？

**Comment by brickspert** [comment]
函数组件 和  class 组件 写法虽然不一样，但是用法是一样的。

可以用 props 来和外面交互呀~

**Comment by oldturkey** [comment]
好的，明白了，谢谢
