### ISSUE TITLE
[RFC] add new package @ahooks/common

### ISSUE THREAD

**Issue by SnowingFox** [alibaba/hooks#1846]
展开讨论一下这个https://github.com/alibaba/hooks/issues/1761 issue @hchlq @li-jia-nan 

对于这种不常用的hook，但肯定会有人有需求的hook，我建议采用monorepo的架构，新增一个`@ahooks/common`的包，让用户按需引入，这种做法可以很好的规避ahooks不想主包体积过大的考量

目前在vue社区有一个hook库就采用了上诉做法，像[vueuse](https://github.com/vueuse/vueuse/tree/main/packages)，他们并不是一股脑的把hook丢进主包，而是分包，比如说对数学计算有需求的用户可以下载`@vueuse/math`这个包，对rxjs有需求的用户可以下载`@vueuse/rxjs`这个包

将不同场景的hook分在不同的包，如此做法我觉得可以更方便用户去使用

 欢迎大家一起讨论

**Comment by hchlq** [comment]
其实这个可以考虑一下的哈，cc @brickspert @crazylxr

**Comment by li-jia-nan** [comment]
commented

**Comment by crazylxr** [comment]
ahooks 是支持 tree shaking 的，基本上不会由于 ahooks 导致性能瓶颈。

另外咱们现在就是 monorepo 的架构，现在就是发的两个包。

我觉得等以后发 V4 的时候再考虑吧。

**Comment by SnowingFox** [comment]
> ahooks 是支持 tree shaking 的，基本上不会由于 ahooks 导致性能瓶颈。
> 
> 另外咱们现在就是 monorepo 的架构，现在就是发的两个包。
> 
> 我觉得等以后发 V4 的时候再考虑吧。

坐等大佬们的消息

**Comment by brickspert** [comment]
不常用的 Hooks，我暂时不建议放进来，会给用户造成选择恐惧症。

**Comment by SnowingFox** [comment]
> 不常用的 Hooks，我暂时不建议放进来，会给用户造成选择恐惧症。

若是这样，用户想用一些hook就得手动封装，参考隔壁react-use封装的很齐全

**Comment by crazylxr** [comment]
这个后面再说哈，现在暂时不搞。先 close 了
