### ISSUE TITLE
useLatest 这个应用场景

### ISSUE THREAD

**Issue by orzhtml** [alibaba/hooks#1852]
useLatest 这个应用场景不是特别能理解为什么要用它，因为 useRef的作用应该是没问题的

**Comment by crazylxr** [comment]
https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useLatest/index.ts  你可以看一下源码，其实就是 useRef 的封装，只是相比写 useRef，写法更简单一点，更语义化一点。

**Comment by orzhtml** [comment]
useRef 不会因为渲染而改变内部的.current 的值，但是用 useLatest 的话就会在渲染的时候就会被重新赋最新值，所以不明白什么样的场景用到时时保持最新值

**Comment by orzhtml** [comment]
> https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useLatest/index.ts 你可以看一下源码，其实就是 useRef 的封装，只是相比写 useRef，写法更简单一点，更语义化一点。

useRef 不会因为渲染而改变内部的.current 的值，但是用 useLatest 的话就会在渲染的时候就会被重新赋最新值，所以不明白什么样的场景用到时时保持最新值（不是为了抬杠，因为在项目中用了后发现有问题，才来讨论下）

**Comment by brickspert** [comment]
> 

你可以看下在 ahooks 源码中大量使用了 useLatest 来包装用户输入的函数，就是为了永远能调用到最新的函数，避免调用到旧的函数。
