### ISSUE TITLE
【源码困惑】useRequest/Fetch.ts中Fetch类中定义的「runAsync」方法

### ISSUE THREAD

**Issue by JustForLucky** [alibaba/hooks#1853]
困惑：源码中runAsync里使用的state在何处声明的？类方法中可以直接使用实例的属性么？或者在构建的时候，增加了哪些特殊配置？
![useRequest_fetch_runAsync](https://user-images.githubusercontent.com/12389643/187637974-b05841db-7021-46e3-8bbe-49c8342c0991.png)

**Comment by li-jia-nan** [comment]
state是剩余参数，不是一个具体的变量，这里只是命名为state，你可以命名aaa、bbb，这里代表的是 plugins 数组里面的内容

**Comment by JustForLucky** [comment]
> 

明白啦～感谢
