### ISSUE TITLE
useTextSelection从指定区域外划词至区域内会把区域外的文字也识别了

### ISSUE THREAD

**Issue by chenyjam** [alibaba/hooks#1854]
![image](https://user-images.githubusercontent.com/24648575/187647246-a580698b-00ae-4783-bf57-52462b8e2ef9.png)

**Comment by li-jia-nan** [comment]
好像是会这样，我来尝试修一下

**Comment by li-jia-nan** [comment]
这里有一个问题，界定文字是否在dom元素之内，有两个标准：

- 视觉上文字在dom元素之内，html层级不一定符合
- html结构上文字在dom元素之内，视觉上不一定符合

我们判断时应该以哪个为准呢？

**Comment by chenyjam** [comment]
> 这里有一个问题，界定文字是否在dom元素之内，有两个标准：
> 
> * 视觉上文字在dom元素之内，html层级不一定符合
> * html结构上文字在dom元素之内，视觉上不一定符合
> 
> 我们判断时应该以哪个为准呢？

以html结构上文字在dom元素之内更合适一点

**Comment by brickspert** [comment]
目前判断标准是：如果鼠标释放的地方，在指定元素之内，则认为符合要求，会取用户选择的所有问题。

目前看，可能解决办法有两个：
1. 如果鼠标点击的时候，不在指定元素内，则放弃本次。（可能是个 break change）
2. 选择完成后，遍历所有元素，看看是不是在指定元素之内。

**Comment by chenyjam** [comment]
> 目前判断标准是：如果鼠标释放的地方，在指定元素之内，则认为符合要求，会取用户选择的所有问题。
> 
> 目前看，可能解决办法有两个：
> 
> 1. 如果鼠标点击的时候，不在指定元素内，则放弃本次。（可能是个 break change）
> 2. 选择完成后，遍历所有元素，看看是不是在指定元素之内。

从使用角度看第二种方法更好了，毕竟使用的时候是指定了区域的，返回区域内选择的文字也很合理

**Comment by liuyib** [comment]
相关 PR 已合并，issue 关了哈
