### ISSUE TITLE
useUrlState ts 返回类型是不是应该 -? 

### ISSUE THREAD

**Issue by tolerance-go** [alibaba/hooks#1856]
![image](https://user-images.githubusercontent.com/37258382/188110041-a396efe9-bd35-4fff-a2dc-2910e603b1e1.png)

如果设置了默认值，属性应该必定存在，如果 setQuery({ activeTabKey: undefined }) 了，我测试了一下，不会改变 query 的值，只是清空了 url 上的 searchParams

还有一个问题是，query keyVal 的类型为什么是 any，一般 set 的时候也不会改变类型吧，还少了检查

![image](https://user-images.githubusercontent.com/37258382/188110654-403e28ea-57d8-4f9c-a386-0b9f53ba769b.png)

![image](https://user-images.githubusercontent.com/37258382/188110567-5aa152f8-de68-4d39-9947-c5d3e1380dd6.png)

**Comment by crazylxr** [comment]
第一个问题：设置了默认值 属性也不一定存在的哈，这个query 是跟 url 上同步的，如果 url 上把参数删了呢？

第二个问题：你可以看下这个 hook ，有 options 这个参数，是支持对 参数自定义 query-string，那么这个类型的类型除了默认值，还可能 query-string 的类型一样，这里我们暂时还没有想到合适的办法，如果你能解的话，欢迎 pr

**Comment by crazylxr** [comment]
@tolerance-go 你还有其他的问题不？没有的话 issue 暂时 close 了
