### ISSUE TITLE
useMap获取总数`size`有问题

### ISSUE THREAD

**Issue by cgfeel** [alibaba/hooks#1861]
直接拿官方示例代码做演示：
https://codesandbox.io/s/strange-glade-yxohu5?file=/App.tsx

 - 通过`api`提供的`set`方法的`add`，`map`数据增加，但是每次`map.size`数量少1
 - 通过`map`的方法`push`，每次`map.set`，数据增加，但不会更新`map`数据

原因：官方提供的接口是异步的，而且没有提供获取`set`后`map`总数的方法

期待的效果：
 - `set`后能实现map数据更新，并且可以拿到`map`的`size`

**Comment by hchlq** [comment]
我觉得这个不是问题，因为 useMap 就是用 useState 实现的，set 最终会调用 useState 的更新函数进行更新，肯定不能同步拿到数据的～

就好像你更新完 useState 之后就想立即拿到新的数据一样

```js
cosnt [count, setCount] = useState(0)

handleClick = () => {
    setCount(count + 1)
    // 此时在这肯定拿不到更新的数据的
    console.log(count) // 还是 0
}

```

**Comment by cgfeel** [comment]
> 我觉得这个不是问题，因为 useMap 就是用 useState 实现的，set 最终会调用 useState 的更新函数进行更新，肯定不能同步拿到数据的～
> 
> 就好像你更新完 useState 之后就想立即拿到新的数据一样
> 
> ```js
> cosnt [count, setCount] = useState(0)
> 
> handleClick = () => {
>     setCount(count + 1)
>     // 此时在这肯定拿不到更新的数据的
>     console.log(count) // 还是 0
> }
> ```

好的，感谢，已知道如何获取
