### ISSUE TITLE
[useReqest] 有非hook的纯的axios/fetch封装吗

### ISSUE THREAD

**Issue by Valar103769** [alibaba/hooks#1863]
请问 你们有没有纯的请求方法的二次封装
脱离react, 没有hook, 只是原生js的封装? 支持了失败重试, 轮训, 竞态等等功能? 或者有推荐吗? 
因为我觉得hook只能在顶层调用, 不能在任何地方request(), 限制了我的发挥, 让我写不出诗一样的代码

**Comment by miracles1919** [comment]
这里是 hooks 库，只有 hook..

如果你不想用 hook 的话，可以试下 axios + 扩展（自己封装 or 找其他人开发的）

**Comment by xiaorong61** [comment]
> 请问 你们有没有纯的请求方法的二次封装 脱离react, 没有hook, 只是原生js的封装? 支持了失败重试, 轮训, 竞态等等功能? 或者有推荐吗? 因为我觉得hook只能在顶层调用, 不能在任何地方request(), 限制了我的发挥, 让我写不出诗一样的代码

axios 就是个封装，你可以看看 axios 文档有没有你需要的功能。。。
