### ISSUE TITLE
不想让usePagination的refreshDeps改变时重置到第一页

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [alibaba/hooks#1864]
请问能不能给一个option让用户选择：https://github.com/alibaba/hooks/blob/master/packages/hooks/src/usePagination/index.ts#:~:text=%7D%5D%2C-,refreshDepsAction,-%3A%20()

```
  const result = useRequest(service, {
    defaultParams: [{ current: defaultCurrent, pageSize: defaultPageSize }],
    refreshDepsAction: () => {
      // eslint-disable-next-line @typescript-eslint/no-use-before-define
      changeCurrent(1);
    },
    ...rest,
  });
```

**Comment by miracles1919** [comment]
你可以用 `refresh` 或者 `run`(usePagination 支持 useRequest 的 所有 API)

**Comment by AttackXiaoJinJin** [comment]
> 你可以用 `refresh` 或者 `run`(usePagination 支持 useRequest 的 所有 API)

你意思是不把字段放进refreshDeps，而是在该字段更新时，手动去refresh/run吗？也是一种解决方法。但字段一多，可能就麻烦些，后面遇到这种情况再提吧。

先close了
