### ISSUE TITLE
React 18 可中断 mount 导致 useRequest 有 cacheKey 时更新报错

### ISSUE THREAD

**Issue by zjfresh** [alibaba/hooks#1866]
问题：

页面组件异步加载时，在挂载过程触发了其他高优先级任务(如下图鼠标滑到上面的tab触发 hover)，打断当前的 mount 过程

![react18可中断mount导致ahooks更新bug](https://user-images.githubusercontent.com/28496323/188542092-a3183967-3060-43d1-867d-04357a41e249.gif)

![image](https://user-images.githubusercontent.com/28496323/188556483-c37626bf-c828-4925-9bf3-e04204b6a5ed.png)

![image](https://user-images.githubusercontent.com/28496323/188567988-0984e470-eed2-430b-b101-ca0abacd8822.png)

![image](https://user-images.githubusercontent.com/28496323/188568048-2582a5e5-ee03-4179-b7ff-c335340d3693.png)

原因：

mount可中断导致 useRef 会重新初始化，进而导致被中断 mount 的 Fiber hook useUpdate 的 update 函数被重复构造的 fetchInstance = useCreation() 收集，最终在 cacheSubscribe 监听无法取消（因为没有 mount 不会触发 unmount ）

https://github.com/alibaba/hooks/blob/a9020108080141170f380c20d0a56d6bf789f9d6/packages/hooks/src/useCreation/index.ts#L5-L17

update 函数被 重复 new Fetch 收集
https://github.com/alibaba/hooks/blob/a9020108080141170f380c20d0a56d6bf789f9d6/packages/hooks/src/useRequest/src/useRequestImplement.ts#L25-L36

https://github.com/alibaba/hooks/blob/a9020108080141170f380c20d0a56d6bf789f9d6/packages/hooks/src/useRequest/src/Fetch.ts#L18-L23

https://github.com/alibaba/hooks/blob/a9020108080141170f380c20d0a56d6bf789f9d6/packages/hooks/src/useRequest/src/Fetch.ts#L31-L37

然后被会话变量 cacheSubscribe.subscribe 注册（每次的 Fetch 实例都会被注册到一个内存变量中，直到 unmount 或刷新页面）
https://github.com/alibaba/hooks/blob/a9020108080141170f380c20d0a56d6bf789f9d6/packages/hooks/src/useRequest/src/plugins/useCachePlugin.ts#L114-L116

https://github.com/alibaba/hooks/blob/a9020108080141170f380c20d0a56d6bf789f9d6/packages/hooks/src/useRequest/src/utils/cacheSubscribe.ts#L2

https://github.com/alibaba/hooks/blob/a9020108080141170f380c20d0a56d6bf789f9d6/packages/hooks/src/useRequest/src/utils/cacheSubscribe.ts#L10-L20
debugger log:

![image](https://user-images.githubusercontent.com/28496323/188556617-b46fba23-9235-4e63-bcba-8085742b5d6d.png)

综上，在被中断 mount 时，此次更新的 fiber 的 强制渲染 update 函数随着 Fetch 实例 被注册到一个内存变量中 ``{ cacheKey: [] }``，在下次正常 mount 完成请求后触发对应 cacheKey 的所有 Fetch 实例更新导致 update 更新在一个 hasn't mounted component

测试仓库： https://github.com/zjfresh/umi4-umi-max

**Comment by zjfresh** [comment]
考虑给 useUpdate 做容错？试了下用 mountedRef 来判断可以避免
![image](https://user-images.githubusercontent.com/28496323/188578647-fbedfa0b-e2ba-4662-b751-9eb354e1a24b.png)

![image](https://user-images.githubusercontent.com/28496323/188578735-9c7d8da8-1a75-4b34-aed6-b09d7f03898e.png)

**Comment by brickspert** [comment]
1. 你说的 React18 可中断机制，确实会有问题，这个我们也在规划处理，有兴趣可以一起来讨论
2. 没太明白 useUpdate 为什么要处理，useUpdate 没有使用 ref，为什么会有问题呢？

**Comment by zjfresh** [comment]
这个 issue 的问题主要不是 useUpdate 引起的

而我是觉得既然 React 存在 render/update 可中断的的情况，那么 useUpdate 作为一个对外的 hook，也应该考虑对这种情况的兼容

保证 update() 执行是在被中断的情况下，是否应该有容错呢？因为这种在 unmount 的 Component 中进行更新产生了报错是 React 的渲染机制导致的，不是用户的不规范编码导致的

这个可以讨论看下，我也不确定这种报错是否可以算作是用户的编码不规范导致的，ahook useUpdate 不作容错，让 React 正常报错

搞了个 [Demo](https://github.com/zjfresh/ahooks-use-update) 试了下直接在 Component 内使用是没事，但放在另一个 hook 内的复杂场景是会出错的，如上面的 useRequest

> CodeSandbox 上的在线演示也可以模拟出来，在控制台看到报错 [Link](https://codesandbox.io/p/github/zjfresh/ahooks-use-update/draft/elated-flower?file=%2F.umirc.ts&selection=%5B%7B%22endColumn%22%3A17%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A17%2C%22startLineNumber%22%3A14%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl7rsd0ad0002lqg197dif6xc%2522%252C%2522openFiles%2522%253A%255B%2522%252F.umirc.ts%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8000%252C%2522key%2522%253A%2522cl7rsfqsx00n33p6h1yggpn1a%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Findex%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl7rsfkzt00i63p6hct0iot9z%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522key%2522%253A%2522cl7rsd2q800073p6htens8r15%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Atrue%257D%255D%257D)

```tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { PageContainer } from '@ant-design/pro-layout';
import { useUpdate, useMount, useCreation } from 'ahooks';

const DocsPage = () => {
  const countRef = useRef(0);
  console.log('🚀 ~ file: index.tsx ~ line 7 ~ countRef pre', countRef.current);
  countRef.current = countRef.current + 1;

  console.log('🚀 ~ file: index.tsx ~ line 10 ~ countRef after', countRef.current);

  const data = useCustom(
    new Promise((requestBack) => {
      setTimeout(() => {
        requestBack('requestData');
      }, 1500);
    })
  );

  useEffect(() => {
    console.log('useEffect [] 是只执行了一次');
  }, []);

  console.time('模拟耗时的 render ');
  let n = 0;
  while (true) {
    window.getComputedStyle(document.body);
    n++;
    if (n > 999999) break;
  }
  console.timeEnd('模拟耗时的 render ');

  return (
    <PageContainer>
      <p>This is umi docs.</p>
    </PageContainer>
  );
};

function useCustom(service: PromiseLike<string>) {
  const update = useUpdate();
  const dataRef = useRef<string | null>(null);

  useCreation(() => {
    service.then((data) => {
      dataRef.current = data;
      update();
    });
  }, []);
}

export default DocsPage;
```

![image](https://user-images.githubusercontent.com/28496323/188917697-89676b79-401e-4eac-b1f8-eace7cc1adc1.png)

**Comment by brickspert** [comment]
> 这个可以讨论看下，我也不确定这种报错是否可以算作是用户的编码不规范导致的，ahook useUpdate 不作容错，让 React 正常报错

这个报错是正常的，React18 已经解释过，这个报错是可以忽略的。 看下这个：https://github.com/brickspert/blog/issues/47

**Comment by zjfresh** [comment]
> > 这个可以讨论看下，我也不确定这种报错是否可以算作是用户的编码不规范导致的，ahook useUpdate 不作容错，让 React 正常报错
> 
> 这个报错是正常的，React18 已经解释过，这个报错是可以忽略的。 看下这个：[brickspert/blog#47](https://github.com/brickspert/blog/issues/47)

[brickspert/blog#47](https://github.com/brickspert/blog/issues/47) 这个链接与上面的问题在给出的处理结果上可能是一致的(允许在 unmounted 的组件 setState)

但具体可能还是不太一样，官方说的是 mount 后 unmount 引起 setState，上面的是 mount 中断后重新 mount 引起的第一个已经没意义的 mount fiber 中的 setState，像提到的以后允许在 umounted 的组件可以正常 setState，但这种未正常 mount 的组件我觉得应该不在这个范围吧

而上面提到的报错可能还是会令人感到困惑，毕竟那个只是告警都作了移除以避免误导，而这个错误还是在 React@18.2.0 中

<img width="794" alt="image" src="https://user-images.githubusercontent.com/28496323/189266204-aa7d1a3c-c1c5-4aa8-8f58-85b4eb76ccb4.png">

不清楚官方对这个有没有计划，或许这个错误该放到 React 18 中去讨论 👀

**Comment by keyus** [comment]
这个ahook是不是考虑，升级一下，现在的性能确实稍差，比起swr还是有些不如， 主要还是缓存那块，问题有些大啊
