### ISSUE TITLE
useKeyPress指定target时如何支持更多event?

### ISSUE THREAD

**Issue by SignDawn** [alibaba/hooks#1882]
### Discussed in https://github.com/alibaba/hooks/discussions/1878

<div type='discussions-op-text'>

<sup>Originally posted by **xmsz** September 15, 2022</sup>
背景
- 我想在div.a里触发回调
- 但是发现触发不了
- 必须操作div.a里的input才能触发？

还是因为我是在弹窗(dialog)里触发
我发现useFocusWithin也不行，但是useHover可以
</div>

**Comment by hchlq** [comment]
看了下 Discussed，这个还有啥问题吗

<img width="716" alt="image" src="https://user-images.githubusercontent.com/60802048/190945978-7e750a57-b1b9-4f07-88d1-94f248490de3.png">
