### ISSUE TITLE
next.js useVirtualList  list undefined 

### ISSUE THREAD

**Issue by ADZG** [alibaba/hooks#1885]
直接贴了官网的例子
![image](https://user-images.githubusercontent.com/44188873/190961707-e28685c9-6069-462a-8ba4-22387496903b.png)
![image](https://user-images.githubusercontent.com/44188873/190961737-b5b7221d-9ab1-469c-b2b1-4925d1dce80a.png)

**Comment by ADZG** [comment]
3.7.1

**Comment by ADZG** [comment]
next 12.3.0

**Comment by hchlq** [comment]
可以提供一个在线 demo 吗，比如 [codesandbox](https://codesandbox.io/)
