### ISSUE TITLE
关于babel

### ISSUE THREAD

**Issue by dadanliu** [alibaba/hooks#1890]
为什么没用 babel-preset-env里自带的transform-async-to-generator plugin，而是选择了 transform-async-to-promises plugin呢？有什么说法么

**Comment by crazylxr** [comment]
我觉得应该用自带的应该也可以吧。 @brickspert 你还记得之前为啥这样搞不

**Comment by brickspert** [comment]
没什么说法。。。就是随便选了一个用。
