### ISSUE TITLE
useRequest 如何拿到接口响应的HTTP Head 信息

### ISSUE THREAD

**Issue by fengluhome** [alibaba/hooks#1891]
有些业务场景需要到响应的接口 http 表头信息， 请问如何实现？

**Comment by crazylxr** [comment]
在你的 service 里面去拿哈，而不是通过 useRequest 去拿哦。

```js
const { data, error, loading } = useRequest(service);
```
这个第一个参数里面的这个 service， 想办法去拿

**Comment by brickspert** [comment]
你可以理解 useRequest 第一个参数 service 是 promise，至于 promise 返回啥，其实是你自己控制的。
