### ISSUE TITLE
useRequest能设置超时时间吗？

### ISSUE THREAD

**Issue by ouqin-live** [alibaba/hooks#1892]
如题↑

**Comment by crazylxr** [comment]
没有，一般超时时间后端设置比较合适。

**Comment by brickspert** [comment]
这个一般是你用的请求库设置，比如 axios 等是支持这个超时时间设置的。

**Comment by crazylxr** [comment]
基于 fetch 的都没办法设置超时，没办法中断，axios 基于 [XMLHttpRequests](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) 的，可以中断才能搞。
