### ISSUE TITLE
求教：useRequest 时序能否保证？

### ISSUE THREAD

**Issue by WuHuSa** [alibaba/hooks#1894]
求教：useRequest 时序能否保证？
2.9.0 版本
假如 100ms 内前后发出两次请求，能否保证后发的接口返回数据一定不会被前发的覆盖？（入参不同）

**Comment by crazylxr** [comment]
需要用户自己去串行请求，useRequest 目前无法保证

**Comment by brickspert** [comment]
第一次响应会被废弃的，useRequest 只会处理第二次返回的结果的。

**Comment by AmAzing129** [comment]
求教 useRequest 3.x版本是否取消了废弃

> 第一次响应会被废弃的，useRequest 只会处理第二次返回的结果的。
