### ISSUE TITLE
[useUrlState] Loosing state property in useLocation

### ISSUE THREAD

**Issue by ArturKustyaev** [alibaba/hooks#1902]
After using the useUrlState, the state property in the uselocation hook is lost

**Comment by crazylxr** [comment]
Please provide a demo that can be reproduced

**Comment by ArturKustyaev** [comment]
I'm using the useLocation hook from the react-router-dom library to store the breadcrumb information I need in the hook's state property. When using the useLocation and useUrlState hooks in the same component, all information from state is erased and becomes undefined.

> Привет, АртурКустьяев.
> 
> Кажется, что этот вопрос немного расплывчат и не хватает некоторой необходимой информации.
> 
> 看起来这条 вопрос 描述得有些模糊，缺少一些必要的信息。

**Comment by crazylxr** [comment]
Please provide a demo that can be reproduced online, such as codesanbox

**Comment by crazylxr** [comment]
The issue is closed first and can be opened again when you provide demo
