### ISSUE TITLE
运行hooks源码，执行pnpm run init，报这个错

### ISSUE THREAD

**Issue by wuyanwen** [alibaba/hooks#1904]
![lALPJu1c21jitr3NAn7NBbA_1456_638](https://user-images.githubusercontent.com/7331663/194762933-98949c39-b333-4ffc-92e6-b374bd10619d.png)

pnpm版本是最新的7.13.3

**Comment by miracles1919** [comment]
之前也遇到过， https://github.com/alibaba/hooks/issues/1786#issuecomment-1200620307

很有可能是 [pnpm 的版本问题](https://github.com/alibaba/hooks/blob/master/package.json#L80), 用 `pnpm@7.1.9` 试试

**Comment by miracles1919** [comment]
这个问题我知道了，@types/react-router 版本和 ts 版本不适配，目前 ahooks 的 ts 版本是 3.x，@types/react-router v5.1.19 之后就是 ts 4.9 了

**Comment by crazylxr** [comment]
已解决了哈，可以重新拉一下 master 代码
