### ISSUE TITLE
文字超出修复

### ISSUE THREAD

**Issue by KangXinzhi** [alibaba/hooks#1906]

**Comment by KangXinzhi** [comment]
![image](https://user-images.githubusercontent.com/50164727/194850736-75b4384e-7ebc-471f-8e45-dc81ffa37327.png)

**Comment by crazylxr** [comment]
欢迎 pr

**Comment by KangXinzhi** [comment]
> 欢迎 pr

提pr了，但是ci挂了，Node CI / build (16.x) (pull_request) ，这个有影响么？

**Comment by crazylxr** [comment]
有，我来看下
