### ISSUE TITLE
useAntdTable 在 antd@4.0 beta0 中报错

### ISSUE THREAD

**Issue by MinJieLiu** [alibaba/hooks#191]
antd onChange 中的参数:
```
filters: Record<string, Key[] | null>
```

tableProps:
```
filters?: Record<keyof Item, string[]>
```

**Comment by brickspert** [comment]
我们处理一下~

**Comment by brickspert** [comment]
现在这个问题已经解决了~

**Comment by liujiayii** [comment]
> 现在这个问题已经解决了~

antd form的4.0 搜索是不是不能用呢，我这试了下好像不行

**Comment by brickspert** [comment]
> > 现在这个问题已经解决了~
> 
> antd form的4.0 搜索是不是不能用呢，我这试了下好像不行

是不行。因为 4 和 3 的 Form 语法不一致。我们下个版本会支持 4 的 Form

**Comment by MinJieLiu** [comment]
只是 ts 类型合不上而已，功能可以使用

**Comment by brickspert** [comment]
最新版 1.6.0 的 [usRequest](https://hooks.umijs.org/zh-CN/async?anchor=%E5%88%86%E9%A1%B5) 和 [useFormTable](https://hooks.umijs.org/zh-CN/antd/use-form-table) 已经修复了。

支持 antd3 和 antd4
