### ISSUE TITLE
useRefreshOnWindowFocusPlugin存在bug

### ISSUE THREAD

**Issue by meixiang474** [alibaba/hooks#1913]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/59130116/195265342-864e99f6-c4c0-4fcf-9e36-491b3b12401f.png">
这里组件卸载时会调用两次stopSubscirbe。
<img width="413" alt="image" src="https://user-images.githubusercontent.com/59130116/195265613-e5bb9524-19db-495e-b304-bf36db8b9a0c.png">
其中第二次stopSubscribe时，其listener在listeners中已经不存在，所以获取的索引是-1，但是listeners的长度不为0的话, listeners.splice(-1, 1)会删除掉数组的最后一项，从而引发bug。

**Comment by hchlq** [comment]
看着逻辑是是有点问题，有具体的产生 bug 的 demo 示例吗

**Comment by meixiang474** [comment]
> 看着逻辑是是有点问题，有具体的产生 bug 的 demo 示例吗

https://github.com/meixiang474/use-request-bug-demo 这个例子中当子组件销毁后，由于执行了两次stopSubscribe导致父组件中useRequest的listener也被移除，从而父组件中的useRequest丧失了refreshOnWindowFocus的能力。

**Comment by hchlq** [comment]
可以把 demo 转到 codesandbox 哈

**Comment by meixiang474** [comment]
> 可以把 demo 转到 codesandbox 哈

https://codesandbox.io/s/blissful-johnson-pyh792?file=/src/index.js
