### ISSUE TITLE
useHistoryTravel 能限制历史记录的长度吗?

### ISSUE THREAD

**Issue by Alt-er** [alibaba/hooks#1917]
比如 设置maxBackLength =100

当 backLength 大于 100的时候删除最前面的记录,保持backLength最多为100

**Comment by crazylxr** [comment]
你的使用场景是什么？

**Comment by Alt-er** [comment]
例如实现一个在线设计器,可能操作步骤非常的多,如果把所有的步骤都存起来会不会占用过多的内存? 虽然可以使用immer之类的库优化一下大小, 但是也有优化不到的地方, 这样长时间的操作创建变量并且GC无法回收算不算是内存泄漏了

> 你的使用场景是什么？

**Comment by crazylxr** [comment]
合理，来个 pr 吧。

**Comment by Alt-er** [comment]
> 



> 合理，来个pr吧。

源码跑不起来 = = 

<img width="561" alt="image" src="https://user-images.githubusercontent.com/18004903/195830310-12e6989f-1ada-4ff5-8090-42d0f63a1552.png">

**Comment by Alt-er** [comment]
有人说需要使用这个版本 pnpm@7.1.9  测试发现还是不行

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/18004903/195849921-b5a5eb9c-36ac-4c37-86e1-a6641652ad86.png">

**Comment by crazylxr** [comment]
这个问题我这两个处理一下，稍等一下

**Comment by crazylxr** [comment]
已解决了哈，可以重新拉一下 master 代码

**Comment by Alt-er** [comment]
已提交

**Comment by crazylxr** [comment]
3.7.2 已发布
