### ISSUE TITLE
useSearch - How to use dispatch()

### ISSUE THREAD

**Issue by tnduc** [alibaba/hooks#192]
>https://hooks.umijs.org/useSearch#input-search

How to apply redux?

**Comment by brickspert** [comment]
you can use like this. first parameter is promise.

```javascript
const { xx } = useSearch(()=>{
    return new Promise((resolve)=>{
        dispatch(xxx);
        resolve();
    });
});
```

if you use dva, you can use like this
```javascript
const { xx } = useSearch(()=>dispatch(xxx));
```

**Comment by tnduc** [comment]
I use dva,

```
const { data = [], loading, onChange } = useSearch<string[]>(
    text => dispatch({
          type: 'pos/search',
          payload: {
            keyword: text
          },
        }),
    [type],
    { wait: 1000 }
  );
```
 VSCode problem:
> Type '{type: string; payload: {keyword: any; }; } 'is missing the following properties from type' Promise <string []> ': then, catch, [Symbol.toStringTag], finally

- in the model what do I need to do to { data } = useSearch() to have the data returned

**Comment by brickspert** [comment]
this not useSearch problem.
this maybe dva typescript error.  
you can try this
```
const { data = [], loading, onChange } = useSearch<string[]>(
    text => dispatch({
          type: 'pos/search',
          payload: {
            keyword: text
          },
        }) as Promise<string[]>,
    [type],
    { wait: 1000 }
  );
```

**Comment by tnduc** [comment]
@brickspert data always = [], how does the data variable receive data from redux.

**Comment by brickspert** [comment]
data = dispatch return
you can console the result dispatch return.

maybe you should return the value  in this dispatch.
