### ISSUE TITLE
useDrag和useDrop和antd下拉组件或日历组件一起用时白屏

### ISSUE THREAD

**Issue by bjtqti** [alibaba/hooks#1932]
https://codesandbox.io/s/ji-chu-yong-fa-forked-mm9cr8
重现方式一：
1.将box1拖放到第二行，点下select,随便选一个值 2.将box1拖回第一行，再点select，可以看到下拉框白屏
重现方式二：
1. 点一下select date, 随便选一个日期， 2. 把box1拖到第二行，再点select date
总结： 只要先点了antd组件，然后再拖一次，回头再点select组件，反复几次必出现问题
code:

import React, { useRef, useState } from "react";
import { useDrop, useDrag, useSetState } from "ahooks";
import { Select, DatePicker } from "antd";
import "antd/dist/antd.css";

type Item = {
  key: React.Key;
  label: string;
};

/**
 * 可以拖动的box
 * @param param0
 */
const DragItem = ({ item, path }: { item: Item; path: string }) => {
  const dragRef = useRef(null);

  const [dragging, setDragging] = useState(false);

  useDrag({ item, path }, dragRef, {
    onDragStart: () => {
      console.log("drag path:", path, item);
      setDragging(true);
    },
    onDragEnd: () => {
      setDragging(false);
    }
  });

  return (
    <div
      ref={dragRef}
      style={{
        border: "1px solid #e8e8e8",
        padding: 16,
        width: 80,
        textAlign: "center",
        marginRight: 16
      }}
    >
      <div>{dragging ? "dragging" : `box-${item.label}`}</div>
      <p>{path}</p>
    </div>
  );
};

/**
 * 可以放置的box
 * @param param0
 */
const DropBox = ({
  list,
  index,
  onMove
}: {
  list: Item[];
  index: number;
  onMove: (source: string, target: string) => void;
}) => {
  const [isHovering, setIsHovering] = useState(false);

  const dropRef = useRef(null);

  useDrop(dropRef, {
    onDom: (content: { path: string; item: Item }, e) => {
      console.log(`custom:  dropped, path`, content.path, content.item);
      onMove(content.path, `${index}-${list.length}`);
    },
    onDragEnter: () => setIsHovering(true),
    onDragLeave: () => setIsHovering(false)
  });

  return (
    <div
      ref={dropRef}
      style={{
        padding: 10,
        border: "1px solid #999",
        display: "flex",
        marginTop: 8,
        background: isHovering ? "#f00" : "#fff"
      }}
    >
      {list.map((it, idx) => (
        <DragItem key={it.key} item={it} path={`${index}-${idx}`} />
      ))}
    </div>
  );
};

/**
 * 两行box, 3个item, 从一个box中拖动一个item 到另一个box中
 */
export default () => {
  const [data, setData] = useSetState<{ list: Item[][] }>({
    list: [
      [
        { key: 1, label: "1" },
        { key: 2, label: "2" },
        { key: 3, label: "staic" }
      ],
      [{ key: 4, label: "4" }]
    ]
  });
  const options = [
    { label: "aaa", value: "aaa" },
    { label: "bbb", value: "bbb" },
    { label: "ccc", value: "ccc" }
  ];
  return (
    <div>
      <h3>拖动会导致antd的下拉组件和日历级件出现白屏</h3>
      <ul>
        <li>重现方式一：</li>
        <li>
          1.将box1拖放到第二行，点下select,随便选一个值
          2.将box1拖回第一行，再点select，可以看到下拉框白屏
        </li>
        <li>重现方式二：</li>
        <li>
          1. 点一下select date, 随便选一个日期， 2. 把box1拖到第二行，再点select
          date
        </li>
        <li>
          总结：
          只要先点了antd组件，然后再拖一次，回头再点select组件，反复几次必出现问题
        </li>
      </ul>
      <Select options={options} placeholder="select" />
      <DatePicker />
      {data.list.map((it, index) => (
        <DropBox
          list={it}
          index={index}
          onMove={(source, target) => {
            console.log("move", source, target);
            const [sIndex, sIdx] = source
              .split("-")
              .map((it) => parseInt(it, 10));
            const [tIndex, tIdx] = target
              .split("-")
              .map((it) => parseInt(it, 10));
            const [item] = data.list[sIndex].splice(sIdx, 1);
            data.list[tIndex] = data.list[tIndex]
              .splice(0, tIdx)
              .concat([item, ...data.list[tIndex]]);
            setData({ list: [...data.list] });
          }}
        />
      ))}
    </div>
  );
};

**Comment by hchlq** [comment]
可否放到 codesandbox 里面呢，直接看到 demo，这样可读性很差，为了提高效率~

**Comment by hchlq** [comment]
是报这个错吗
<img width="653" alt="image" src="https://user-images.githubusercontent.com/60802048/197096038-c1eab3d9-7af9-4343-8824-7cc92732f51c.png">

**Comment by hchlq** [comment]
ahooks 升级到 3.7.2 哈，这个 bug 修复过了~

**Comment by bjtqti** [comment]
首先，非常感谢您的及时回复，我要描述的不是抛的这个异常，而是拖动后下拉菜单和日历的内容为空了。

**Comment by bjtqti** [comment]
![image](https://user-images.githubusercontent.com/5865071/197138535-e376c89f-c0f0-42c5-95b5-b17c60739bf6.png)

**Comment by hchlq** [comment]
应该不可能的，看了你的 demo，这个 hook 和 antd 都没有任何交集，如果白屏可以找 antd 看看

**Comment by hchlq** [comment]
我反复操作了一下也没有白屏，怎么操作的录个屏看看~

**Comment by bjtqti** [comment]
谢谢你的回复，我把问题也和antd反馈了。大概率是antd的问题。
