### ISSUE TITLE
usePagination

### ISSUE THREAD

**Issue by dmandlove** [alibaba/hooks#1938]
pageSize由多变少时 会先更新pageSize再改变dataSource 触发antd内部警告 请问这个警告影响使用吗
https://codesandbox.io/s/confident-albattani-rdrxot?file=/src/App.js
![image](https://user-images.githubusercontent.com/87518492/197704705-53447777-e858-40a1-b8ff-dedf049c06ab.png)

**Comment by crazylxr** [comment]
警告理论上不会影响使用，这个 issue 建议你提给 antd
