### ISSUE TITLE
useRequest: 是否支持loaded状态

### ISSUE THREAD

**Issue by xiaoliangpan** [alibaba/hooks#1944]
问题：首次加载页面时，没有辅助字段判断是否发起过请求loaded，导致页面会先展示空状态在展示加载数据。页面显示不够准确。
我自己实现的loaded:
`import { useState } from 'react';
import { useRequest as useRequests } from 'ahooks';

const useRequest = (service: any, options: any) => {
  const [loaded, setLoaded] = useState(false);
  let request: any = useRequests(service, {
    ...options,
    onBefore: params => {
      setLoaded(false);
      options?.onBefore && options?.onBefore?.(params);
    },
    onFinally: (params, data, e) => {
      setLoaded(true);
      options?.onFinally && options?.onFinally?.(params, data, e);
    },
  });
  request.loaded = loaded;
  return request;
};
export default useRequest;`

我尝试用插件方式实现，但是发下 useRequestImplement 返回的对象不支持动态扩展， useRequest 是否会考虑支持loaded或者。你们是怎么判断loaded的。

**Comment by xiaoliangpan** [comment]
展示空状态逻辑是：  total === 0 && loaded ? <Empty /> : <Data />;
没有loaded字段      total === 0 && loading === false ? <Empty /> : <Data />

**Comment by miracles1919** [comment]
`loading && !data` 这样呢？

**Comment by crazylxr** [comment]
@xiaoliangpan 怎么样，能解决你的问题了不？
