### ISSUE TITLE
[QUESTION]useFusionTable拿到的formData和field.getValues的不一致

### ISSUE THREAD

**Issue by xmsz** [alibaba/hooks#1957]
```
const field = Field.useField()
useFusionTable(
    async ({}, formData) => {
      console.log(formData) // {type:"we"}
    },
{field}
)
  {show && (
            <Form field={field}>
<Form.Item name='type'>
              <Input/>
</Form.Item>
            </Form>
          )}

```

- 切换show

预期
- formData拿到的是 {}

实际
- formData拿到的是 {type:"we"}，或者说还是上一次的结果
- field.getValues()拿到的是 {}，是正常

**Comment by li-jia-nan** [comment]
可以给个完整的 codesandbox 复现 demo 吗？

**Comment by xmsz** [comment]
> 可以给个完整的 codesandbox 复现 demo 吗？

https://codesandbox.io/s/default-usage-forked-nyyp5g?file=/App.tsx

输入input，formData拿到的是{}，但是field.getValues拿到的是{type:sting}

**Comment by xmsz** [comment]
尴尬，好像之前问过了https://github.com/alibaba/hooks/issues/1779

就是如果是动态显隐的Form.Item就不是同步了
