### ISSUE TITLE
[RFC] useDark

### ISSUE THREAD

**Issue by faga295** [alibaba/hooks#1958]
# useDark
API
```
const isDark = useDark()
const toggleDark = useToggle(isDark)
// <body class="dark">
```
```
const isDark = useDark({
selector: 'body',
attribute: 'mode',
darkValue: 'dark'
lightValue: 'light'
})
const toggleDark = useToggle(isDark)
// <body mode="dark">
```
参数
| 参数 | 说明 | 类型 |
| ---- | ---- | ---- |
| options | 选项 | options |

options
| 参数 | 说明 | 类型 |
| ---- | ---- | ---- |
| selector | 选择器 | string |
| attribute | 给选中元素添加的attribute | string|
| darkValue | 深色模式给选中元素的目标attribute添加的值 | string |
| lightValue | 浅色模式给选中元素的目标attribute添加的值 | string |
| onChange | 自定义修改isDark的行为 | (...args: any[]) => any |

**Comment by brickspert** [comment]
这个不建议提交到 ahooks，主要是因为

1. 适用范围比较小
2. 应用用一个全局状态管理器是可以很方便的管理这个状态的
3. 适用原生 js 也比较容易修改 dom

暂时不太建议收纳~~ 感谢
