### ISSUE TITLE
useAntdTable里的类型FnParams导出报错

### ISSUE THREAD

**Issue by headwindz** [alibaba/hooks#196]
看例子上 （https://hooks.umijs.org/useAntdTable）:

`
import { FnParams , useAntdTable  } from '@umijs/hooks';
`

这样会报错  FnParams 找不到。因为FnParams 没有在最外层导出 。

必须要这样引入才可以

`
import { FnParams } from '@umijs/hooks/lib/useAntdTable'
`

不知道后续怎么规划的？有计划在最外层导出FnParams么？ import导入的时候如果路径需要进入到useAntdTable 的话对使用方不是太方便。另外跟文档上的也对不上。

**Comment by brickspert** [comment]
> 不知道后续怎么规划的？有计划在最外层导出FnParams么？ import导入的时候如果路径需要进入到useAntdTable 的话对使用方不是太方便。另外跟文档上的也对不上。

嗯嗯，这个问题已经已知了。      
未来不会在最外层导出 FnParams。
我们近期会更新一版文档。

**Comment by brickspert** [comment]
最新的文档已经修复了这些问题。
