### ISSUE TITLE
[提案]Drag Drop 希望加上分组 key ，同组的才响应拖放事件

### ISSUE THREAD

**Issue by SturdyCat** [alibaba/hooks#1960]
Drag Drop 希望加上分组 key ，同组的才响应拖放时间

**Comment by hchlq** [comment]
@SturdyCat 可以描述详细点么，没 GET 到点~

**Comment by SturdyCat** [comment]
@hchlq 拖拽区域有很多不同功能元素，比如同是圆形的元素响应拖拽事件，但是方形的不响应。希望在拖拽目标上可以设置类似分组的ID，进行分组操作控制。
如：希望拖拽排序，那么元素同时绑定拖和放2种事件，多个元素有相同分组的才响应放事件

**Comment by hchlq** [comment]
信息还是不太够，给一下使用的案例吧。否则我们没法判断是否需要新增这个功能

**Comment by hchlq** [comment]
业务自己去决定是否需要使用拖拽就好了，因为 useDrag / useDrog 不知道有有多少个子元素，只是处理拖拽事件而已，不能处理分组的功能。业务在数据上自己分组，比如不想让某个子元素有拖拽，不在目标元素上 ref 传空就可以了，这个元素就不会启用拖拽功能了。
