### ISSUE TITLE
useKeyPress中，keyFilter为['meta'], events为['keyup']，触发相应事件，没有调用回调

### ISSUE THREAD

**Issue by Jusme-wx** [alibaba/hooks#1962]
mac电脑，meta对应command按键，代码如下，按下command，不会触发console

```
useKeyPress(
    ['meta'],
    () => {
      console.log('keyup-meta');
    },
    {
      events: ['keyup'],
    }
 );
```

**Comment by miracles1919** [comment]
看了下是因为 meta 没有对应的 aliasKeyCode
https://github.com/alibaba/hooks/blob/87ab99da748264035991ac83314e6f3637c90d57/packages/hooks/src/useKeyPress/index.ts#L174-L176

而 mac 中 command 有 Left 和 Right 之分，keyCode 分别为 91 和 93，会和已有的 keyCodeMap 冲突，所以打算在下方增加 `event.type` 的判断

```diff
meta: (event: KeyboardEvent) => {
+    if (event.type === 'keyup') {
+      return event.keyCode === 91 || event.keyCode === 93;
+    }
    return event.metaKey;
  },

```

https://github.com/alibaba/hooks/blob/87ab99da748264035991ac83314e6f3637c90d57/packages/hooks/src/useKeyPress/index.ts#L130

**Comment by trace59** [comment]
> 看了下是因为 meta 没有对应的 aliasKeyCode
> 
> https://github.com/alibaba/hooks/blob/87ab99da748264035991ac83314e6f3637c90d57/packages/hooks/src/useKeyPress/index.ts#L174-L176
> 
> 而 mac 中 command 有 Left 和 Right 之分，keyCode 分别为 91 和 93，会和已有的 keyCodeMap 冲突，所以打算在下方增加 `event.type` 的判断
> 
> ```diff
> meta: (event: KeyboardEvent) => {
> +    if (event.type === 'keyup') {
> +      return event.keyCode === 91 || event.keyCode === 93;
> +    }
>     return event.metaKey;
>   },
> ```
> 
> https://github.com/alibaba/hooks/blob/87ab99da748264035991ac83314e6f3637c90d57/packages/hooks/src/useKeyPress/index.ts#L130

有计划什么时候修复吗？

**Comment by miracles1919** [comment]
PR 已经有了#1968
