### ISSUE TITLE
异步中调用Toast.show，可能会同时出现两个提示，其中一个永远不会关闭

### ISSUE THREAD

**Issue by MallenFan** [alibaba/hooks#1964]
如题，[点击复现](https://codesandbox.io/s/cause-two-toasts-appear-at-the-same-time-forked-btj7gn?file=/app.tsx)

**Comment by miracles1919** [comment]
感觉跟 react 版本有关，我看你依赖的版本是 
![image](https://user-images.githubusercontent.com/22469543/201307545-79aa332d-93aa-4dd1-818e-1f3071a419e3.png)

我把 react react-dom 的版本都改成 18.2.0 就正常了（目前的 latest 版本）

**Comment by miracles1919** [comment]
另外 antd-mobile 的问题可以去相应的 [Github](https://github.com/ant-design/ant-design-mobile) 上提哈~
