### ISSUE TITLE
useAntdTable 生成的tableprops和antd 的tableprops不一致，ts类型检查报错

### ISSUE THREAD

**Issue by NsNe** [alibaba/hooks#197]

**Comment by brickspert** [comment]
我测试是一致的。

能截个图，或者给个复现吗？

**Comment by NsNe** [comment]
> 我测试是一致的。
> 
> 能截个图，或者给个复现吗？


![image](https://user-images.githubusercontent.com/25630824/71409726-89a0b680-267d-11ea-8f7a-270b2baa861d.png)

**Comment by NsNe** [comment]
> 我测试是一致的。
> 
> 能截个图，或者给个复现吗？

额，这个可能是因为我先安装了高版本的antd，然后才安装了umijs hook，所以antd版本不那么match，这个issue我先close了哈
