### ISSUE TITLE
bug: useInfiniteScroll在reload时数据混乱问题

### ISSUE THREAD

**Issue by wenda10086** [alibaba/hooks#1970]
ahooks版本3.7.2
umi版本4.0.32
react版本18.2.0
demo由命令`pnpm dlx create-umi@latest`创建

功能描述：
在输入框中输入数字几，列表便展示几条数据。默认是15条
由于项目中是通过接口获取的数据

错误出现场景：大概率会出现
1）当上一次查询时，数据量很多，足以达到翻页
2）在输入框中输入数字2（比较小，没有翻页）
3）此时列表中会先显示2条，1s后又显示出原来的15条了

断点时发现在useRequest中onSuccess调用scrollMethod方法，此时获取到的finalData还是老的值

下面是测试代码
```tsx
function Demo() {
  const divRef = useRef<HTMLDivElement>(null);
  const numberRef = useRef(15);
  const { data, reload } = useInfiniteScroll(
    async () => {
// await 1s是必须（模拟接口时间），如果不await，则没问题
      await new Promise((r) => {
        setTimeout(() => {
          r();
        }, 1000);
      });
      return Promise.resolve({
        list: Array.from({
          length: Number(numberRef.current),
        }).map((_, index) => index + 1),
        last: numberRef.current < 10, // 表示大于10条的可以往下翻页，小于10条的不能翻页
      });
    },
    {
      target: divRef,
      isNoMore: (d) => d?.last !== false,
    }
  );
  return (
    <div>
      <input
        onBlur={(e) => {
          numberRef.current = Number(e.target.value);
          reload();
        }}
      />
      <div ref={divRef} style={{ height: 100, overflow: "scroll" }}>
        {data?.list?.map((item) => (
          <div key={Math.random()}>{item}</div>
        ))}
      </div>
    </div>
  );
}
```

https://user-images.githubusercontent.com/47812628/201863510-3c34a2fe-d486-4fc4-a9f5-b1bfca7ef5f7.mov

备注：
当我使用dumi:1.1.0创建的组件库中使用时，发现改问题并没有复现
是react版本导致的，如果我umi降级react至17，则没问题

我个人的修复方式：
为loadMore、loadMoreAsync、scrollMethod添加useMemoizedFn

**Comment by wenda10086** [comment]
react18版本会有上述问题
react17是好的

**Comment by hchlq** [comment]
@wenda10086 看你有建议的修改方式，来个 PR 行不，我复现了一下，发现是 React 18 引入的~

**Comment by wenda10086** [comment]
好的

**Comment by hchlq** [comment]
这边建议只给 `loadMore` 加上 `useMemoizedFn` 包裹即可解决。

**Comment by wenda10086** [comment]
那我重新提一下，刚才我全加上了

**Comment by wenda10086** [comment]
pr提了
https://github.com/alibaba/hooks/pull/1980

**Comment by wenda10086** [comment]
https://github.com/alibaba/hooks/pull/1981

**Comment by JX-Zhuang** [comment]
@wenda10086 @hchlq 还需要解决吗

**Comment by tulies** [comment]
@wenda10086 @hchlq   可以顺带看下 scrollMethod 是不是应该需要 用useMemoizedFn包裹下。不包裹会出现多次请求。

**Comment by HumanSean** [comment]
2023.03.03，还是有问题
