### ISSUE TITLE
[QUESTION]useRequest 如何只在业务请求成功时缓存缓存？

### ISSUE THREAD

**Issue by dodododooo** [alibaba/hooks#1983]
背景
    业务中，需要判断请求是否有效再决定是否缓存。

举例
    请求一个活动配置信息：
    useRequest(promise); // http请求成功，活动未开启，业务状态返回失败，不缓存
    useRequest(promise); // http请求成功，活动开启，业务状态返回成功，缓存

目前根据业务状态判断返回失败时强制进入reject中，但感觉不太优雅。。。
另外即使业务状态返回失败也需要一些返回信息做出相应的逻辑处理，在error信息中既有http错误也业务错误和其他错误，处理起来也比较麻烦。

**Comment by hchlq** [comment]
目前 useRequest 只是在成功时才会缓存，建议是请求成功后，根据业务的条件，清除掉缓存就好了。
