### ISSUE TITLE
useAntdTable是否应该增加参数来接收接口返回的分页信息而不是只是一个total字段

### ISSUE THREAD

**Issue by wanliyunyan** [alibaba/hooks#1987]
公司提出一个需求，table页面删除数据，当最后一页的数据被删干净时，接口会返回上一页的数据，useAntdTable只接收一个total字段，前端页面的pagination中的current与接口返回的pageNumber数据就不一样了，current会比接口返回的pageNumber大1页，现在有什么办法能让table组件使用后端回来的分页信息吗？而不是用tableProps.pagination

**Comment by miracles1919** [comment]
`tableProps.onChange`
