### ISSUE TITLE
useRequest 的 ready 参数值为 undefined 的时候也会执行 service？

### ISSUE THREAD

**Issue by ZKL-VOILET** [alibaba/hooks#1990]
useRequest 的 ready 参数值为 undefined 的时候也会执行 service，这应该是一个 bug 吧？
如下代码，当 ready === undefined 时，也会执行请求
`const { data } = useRequest(service, {
      ready: undefined
})`

请问这个问题会修复吗？

**Comment by Mess663** [comment]
ready: undefined 跟不传 ready 的表现是一致的，应该不算 bug 吧

**Comment by miracles1919** [comment]
这不是 bug，`ready` 的默认值就是 `true`

```js
function fun({ ready = true }){}

// ready 都是 true
fun({}) 
fun({ ready: undefined })
```
