### ISSUE TITLE
useRequest 支持组件挂载不执行

### ISSUE THREAD

**Issue by guaijie** [alibaba/hooks#1993]
const { data, loading } = useRequest(
    async () => {
      const { data, code } = await getUserList({
        page: pager.current,
        pageSize: pager.pageSize,
        ...values
      })
      if (code === 0) {
        const { list } = data
        return list
      }
    },
    {
      manual: true,
      refreshDeps: [pager, values],
      throttleWait: 600
    }
  )

设置 manual 为 true 组件挂载时不执行，但主动修改依赖时不会执行请求， refreshDeps 与 manual 相冲突， 如果是有意这么设计，希望提供有一个属性支持在组件初次挂载时不执行请求

**Comment by miracles1919** [comment]
有几种方法

1.  ready 属性：https://ahooks.js.org/zh-CN/hooks/use-request/ready
2.  手动触发

```jsx
useEffect(() => {
  run()
},[page, values])
```

**Comment by guaijie** [comment]
> 有几种方法
> 
> 1. ready 属性：https://ahooks.js.org/zh-CN/hooks/use-request/ready
> 2. 手动触发
> 
> ```js
> useEffect(() => {
>   run()
> },[page, values])
> ```

我需要组件挂载时不执行，之后通过依赖更新来执行。但如果先设置 ready 为 false, 再修改 ready 为 true 时接口就会被调用，这并非是我想要的(我不希望这个时候接口被调用)

**Comment by miracles1919** [comment]
> 我需要组件挂载时不执行，之后通过依赖更新来执行

- 用 `ready` 的话不就是组件挂载时设置 ready 为 false，依赖更新时设置 ready 为 true 么
- 手动触发的话就是组件挂载时不调用 `run`，依赖更新时调用 `run` 么

@guaijie 是哪里有疑惑呢
