### ISSUE TITLE
关于AntD5.x的支持情况

### ISSUE THREAD

**Issue by MrMJY** [alibaba/hooks#1999]
1、想问一下现在版本支持Antd5了吗（提问时的版本V3.7.2）？
2、如果不支持，有计划什么时间支持吗？

**Comment by crazylxr** [comment]
现在不支持，欢迎 pr

**Comment by miracles1919** [comment]
Antd Table 组件 v5 没有什么大的差异，所以是支持的，例子：https://codesandbox.io/s/relaxed-bose-z0vwvt?file=/index.tsx
