### ISSUE TITLE
[提案] useUrlState 可否增加配置保留location.state

### ISSUE THREAD

**Issue by zyt-cloud** [alibaba/hooks#2000]
### 需求背景
某页面使用location.state 存储数据，使用useUrlState 添加search后刷新浏览器 state丢失，希望增加配置保持state

**Comment by miracles1919** [comment]
为什么用 `location.state` 存储数据？ 一刷新不就没了吗

**Comment by zyt-cloud** [comment]
> 为什么用 `location.state` 存储数据？ 一刷新不就没了吗

当前路由刷新是不会丢失state的，使用useUrlState 后已经调用了push或者replace了 ，这个时候location.state才会丢失

**Comment by zyt-cloud** [comment]
> 

可能表述没清楚，history.push（或者react-router6的navigate）的时候传了state，目标页面通过useLocation获取state

**Comment by miracles1919** [comment]
get，目前是没处理 history 的 state

**Comment by crazylxr** [comment]
已经发布。
