### ISSUE TITLE
> 通过属性配置让组件挂载时不执行

### ISSUE THREAD

**Issue by guaijie** [alibaba/hooks#2005]
> 有几种方法
> 
> 1. ready 属性：https://ahooks.js.org/zh-CN/hooks/use-request/ready
> 2. 手动触发
> 
> ```js
> useEffect(() => {
>   run()
> },[page, values])
> ```

我需要组件挂载时不执行，之后通过依赖更新来执行。但如果先设置 ready 为 false, 再修改 ready 为 true 时接口就会被调用，这并非是我想要的(我不希望这个时候接口被调用)

_Originally posted by @guaijie in https://github.com/alibaba/hooks/issues/1993#issuecomment-1343806330_

**Comment by miracles1919** [comment]
在原本的 issue 讨论吧，这个我先 close 了
