### ISSUE TITLE
useAntdTable中current当前页码无法保持的原因

### ISSUE THREAD

**Issue by bobowiki** [alibaba/hooks#2007]
在很多页书上，列表操作了之后需要刷新整个table，但是有的时候是希望页码还是停留在用户选择的页码上，useAntdTable中的current无论是在submit方法还是在refreshDeps上只要在次请求就会把页面重置为1，这个体验很差

**Comment by miracles1919** [comment]
`useAntdTable` 基于 `usePagination` 实现的，你可以这样

```jsx
const { tableProps,  pagination } = useAntdTable()

// 刷新
pagination.changeCurrent(tableProps.pagination.current)
```
