### ISSUE TITLE
请问一下  useAntdTable, 能否暴露出修改 dataSource 的方法？

### ISSUE THREAD

**Issue by PengQingYao** [alibaba/hooks#2008]
场景：  可编辑table， 更改完数据， 然后更新dataSource.  useAntdTable 好像没有提供更新dataSource的方法。只能重新调用接口去更新dataSource

**Comment by SignDawn** [comment]
https://ant.design/components/input-cn

**Comment by liam-wen** [comment]
使用mutate不就可以了吗？https://ahooks.js.org/zh-CN/hooks/use-request/basic#%E7%AB%8B%E5%8D%B3%E5%8F%98%E6%9B%B4%E6%95%B0%E6%8D%AE
useAntdTable应该也是支持的
