### ISSUE TITLE
Dyanmic table validateFields not show errors

### ISSUE THREAD

**Issue by tnduc** [alibaba/hooks#201]
Add rules to the input, but do not display an error when clicking submit.

[Demo online](https://codesandbox.io/embed/hooks-demo-iz293?fontsize=14&hidenavigation=1&theme=dark)

**Comment by ttys026** [comment]
In order to show the validate message, you need to wrap your Input using Form.Item
see [demo](https://codesandbox.io/s/hooks-demo-0pxus)
