### ISSUE TITLE
Can't resolve 'tslib' in '/cloud/source_code/node_modules/_ahooks@3.7.3@ahooks/es/useRequest/src'

### ISSUE THREAD

**Issue by yee94** [alibaba/hooks#2012]
版本 3.7.3，新出现 Can't resolve 'tslib' 依赖~

<img width="901" alt="image" src="https://user-images.githubusercontent.com/19386356/208618121-081de2e3-ae05-42c7-bbfd-d8126a9e43c8.png">

**Comment by crazylxr** [comment]
3.7.4 已修复
