### ISSUE TITLE
fireEvent 的问题

### ISSUE THREAD

**Issue by DomeSy** [alibaba/hooks#2020]
在useHover的单元测试中，使用fireEvent.mouseOver
<img width="523" alt="image" src="https://user-images.githubusercontent.com/41473452/210292947-eec55bba-eb9c-479e-b321-07edbda2b512.png">
但实际上第二个参数并没有执行，就算 expect(result.current).toBe(true); => 改为expect(result.current).toBe(“随便输”);单元测试也能通过，这种方式是不是存在问题

**Comment by DomeSy** [comment]
fireEvent 的第二个参数应该是可选项，不应该是fn吧，验证应该在fireEvent之后执行吧～

**Comment by miracles1919** [comment]
你说的是对的，欢迎 PR

**Comment by DomeSy** [comment]
好的，已提交PR

**Comment by crazylxr** [comment]
已合并
