### ISSUE TITLE
Uncaught Error: useLocation() may be used only in the context of a <Router> component

### ISSUE THREAD

**Issue by pittleCheung** [alibaba/hooks#2023]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/114127651/210481009-778db03e-ae38-4b5e-a09b-5c45df66927e.png">
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/114127651/210481252-a71f5612-d04d-4f62-94ec-58f868113744.png">

**Comment by crazylxr** [comment]
来个在线 demo
