### ISSUE TITLE
useRequest 的 refreshDeps 接收 ref 值会有奇怪的更新效果

### ISSUE THREAD

**Issue by shaunhurryup** [alibaba/hooks#2024]
# 环境
- "ahooks": "^3.5.2"
- 设备：MBP m1

# 背景
有个输入框，但它只是一个非受控组件，我不希望绑定 value 属性

```tsx
const query = useRef<string>('')

useRequest(theFetchRequest, {
  refreshDeps: [query.current]
})

<input onChange={(e) => (query.current = e.target.value)} />
```

当我修改 input 触发 onChange 事件的时候，`theFetchRequest` 并没有按照预期的那样去做更新🤦‍♂️

**Comment by crazylxr** [comment]
ref 不是 state，本来就不会重新刷新。

需要重新刷新，就把 useRef 改成 useState

**Comment by SignDawn** [comment]
归根结底是依赖于 useEffect 的，需要 re-render 的，既重新执行该组件函数时。
