### ISSUE TITLE
useAsyncEffect热更新后不会执行yield之后的清理

### ISSUE THREAD

**Issue by zy97** [alibaba/hooks#2025]
同步的useEffect会执行清理，而异步的useAsyncEffect不会执行清理

**Comment by crazylxr** [comment]
没太明白啥意思？

你是说 useAsyncEffect(() => {
  return clean
}, [])

这个 clean 函数不会执行？

**Comment by zy97** [comment]
@crazylxr  [官方的文档](https://ahooks.gitee.io/zh-CN/hooks/use-async-effect#%E4%B8%AD%E6%96%AD%E6%89%A7%E8%A1%8C)不是说发现effect被清理的话，会执行yield后续的语句。
但是我的使用情况是。如果使用react的官方useEffect的话，热更新之后会执行清理函数，但如果使用useAsyncEffect的话，热更新之后不会执行yield之后的清理，这样说你懂了吗

**Comment by li-jia-nan** [comment]
能给个 codesandbox 的复现链接或者复现 demo 吗？

**Comment by zy97** [comment]
> 能给个 codesandbox 的复现链接或者复现 demo 吗？
[测试地址](https://stackblitz.com/edit/vitejs-vite-dr6bn7?file=src/App.tsx)，我发现不适用useEventEmitter的订阅就没问题，如果使用了就会出现我说的情况

**Comment by zy97** [comment]
@li-jia-nan [测试地址](https://stackblitz.com/edit/vitejs-vite-dr6bn7?file=src/App.tsx)，我发现不适用useEventEmitter的订阅就没问题，如果使用了就会出现我说的情况
