### ISSUE TITLE
useRequest 自动执行渲染次数问题

### ISSUE THREAD

**Issue by qq1038765585** [alibaba/hooks#2026]
使用useRequest自动请求, 会渲染三次, 其中第二次, params一样, 不知道为何会导致组件重渲染, 是因为内存地址不一致?

![image](https://user-images.githubusercontent.com/43376375/211157731-9d368f7d-40d1-4c5e-9dd8-7e0da3c183ce.png)

**Comment by crazylxr** [comment]
你代码咋写的，贴一下呢，最好贴一个在线 demo
