### ISSUE TITLE
useVirtualList 这个 hooks 官网示例会无限重新加载 dom

### ISSUE THREAD

**Issue by Ali-ovo** [alibaba/hooks#2033]
# 复现方法 
打开 hooks 示例 https://ahooks.gitee.io/zh-CN/hooks/use-virtual-list
然后滚动一下页面，会发现dom元素会无限刷新导致页面无法正常展示

看了一下 大概是height变成了科学计数法的原因，下面有截图

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/67216143/213083078-20195416-d1e3-46ff-be7e-efb302607fec.png">

**Comment by Sunny-117** [comment]
bug无疑了

**Comment by Ali-ovo** [comment]
> bug无疑了

应该计算高度的时候出了问题

**Comment by hchlq** [comment]
重复问题，统一在 https://github.com/alibaba/hooks/issues/2049 处理
