### ISSUE TITLE
Dyanmic table sort values form

### ISSUE THREAD

**Issue by tnduc** [alibaba/hooks#204]
I use `unshift`, the data from the values `list` and `form` are contradictory, currently I have to use `reverse` to unify the field position.

![Screenshot from 2019-12-27 15-34-45](https://user-images.githubusercontent.com/26267956/71509690-c7d8e880-28be-11ea-9edf-48f77c13558f.png)

[Demo online](https://codesandbox.io/s/hooks-demo-tomlj?fontsize=14&hidenavigation=1&theme=dark)

**Comment by ttys026** [comment]
Since antd form keep track of the order of field creating, you need to sort the form manually, and it might be hard to do. That's the reason why we have a `sortForm` method. in the example, you can use this method to get correct order of form values (as the value printed)
