### ISSUE TITLE
useKeyPress按住command键，其他按键触发keyup时，没有调用回调函数。

### ISSUE THREAD

**Issue by lvdougao1** [alibaba/hooks#2044]
useKeyPress(
    () => true,
    (event) => {
      console.log(event);  
    },
    {
      events: ['keydown', 'keyup'],
    }
  );

当按住command键时 其他按键不触发keyup回调

**Comment by liuyib** [comment]
这似乎是 Mac 系统级别的限制，或者浏览器的 Bug，见：
- https://bugs.chromium.org/p/chromium/issues/detail?id=108404
- https://bugs.chromium.org/p/chromium/issues/detail?id=28089
- https://github.com/electron/electron/issues/5188
- https://bugzilla.mozilla.org/show_bug.cgi?id=1299553

可以验证，如下：

```js
window.addEventListener("keyup", (ev) => {
  console.log(ev.key);
});
```

例如，同时按下 Command + C，上述代码是不会有任何打印（`keydown` 是没问题的）。 @crazylxr  @miracles1919

**Comment by crazylxr** [comment]
目前看来是的，只能补个 FAQ 了，不太能解
