### ISSUE TITLE
🐛: useVirtualList `flicker`

### ISSUE THREAD

**Issue by kaitoukid-1412** [alibaba/hooks#2049]
[screen-capture.webm](https://user-images.githubusercontent.com/15698245/217126215-addaf79b-287d-452e-9628-38f4e9a49b60.webm)

**Comment by luo3house** [comment]
#2040
#2033 
#1940

**Comment by crazylxr** [comment]
v3.7.5 已修复

**Comment by xiangdongbu** [comment]
> v3.7.5 已修复

使用 3.7.8 的版本 依然会有滑动过程中闪烁的问题

**Comment by liuyib** [comment]
> 使用 3.7.8 的版本 依然会有滑动过程中闪烁的问题

是必现的吗？麻烦来个可复现的在线 demo，感谢 @xiangdongbu

**Comment by xiangdongbu** [comment]
https://github.com/alibaba/hooks/assets/66773251/6832208d-a9f9-4463-af97-0d07424b1a97

```
const RecordList = (props: { dataList: any[] }) => {
  const { dataList } = props;

  const containerRef = useRef(null);
  const wrapperRef = useRef(null);

  const [list] = useVirtualList(dataList, {
    containerTarget: containerRef,
    wrapperTarget: wrapperRef,
    itemHeight: 227,
    overscan: 10
  });

  return (
    <div ref={containerRef}>
      <div ref={wrapperRef}>
        {list && list.length === 0 ? (
          <div className={style.emptyWrap}>
            <Empty />
          </div>
        ) : (
          <>
            {list && list.length > 0
              ? list.map((item, index) => {
                  return (
                    <div style={{ height: '260px' }}>
                      <div>
                        {item.data.zqdm}-{item.data.zqmc}
                      </div>
                      <div>
                        {item.data.zqdm}-{item.data.zqmc}
                      </div>
                      <div>
                        {item.data.zqdm}-{item.data.zqmc}
                      </div>
                      <div>
                        {item.data.zqdm}-{item.data.zqmc}
                      </div>
                    </div>
                  );
                })
              : null}
          </>
        )}
      </div>
    </div>
  );
};
```

**Comment by xiangdongbu** [comment]
> > 使用 3.7.8 的版本 依然会有滑动过程中闪烁的问题
> 
> 是必现的吗？麻烦来个可复现的在线 demo，感谢 @xiangdongbu

https://github.com/alibaba/hooks/issues/2049#issuecomment-1668842267

**Comment by xiangdongbu** [comment]
> > 使用 3.7.8 的版本 依然会有滑动过程中闪烁的问题
> 
> 是必现的吗？麻烦来个可复现的在线 demo，感谢 @xiangdongbu

是必现的，比如list里的每一条都可以点击展开  默认是全部收起的，但是我点击了某一条后，这一条会展开 这一条的总高度也会变高，这时候再去滑动 ，会影响后面。

**Comment by liuyib** [comment]
> 比如list里的每一条都可以点击展开 默认是全部收起的

是像 antd [Collapse](https://4x-ant-design.antgroup.com/components/collapse-cn/) 组件这样折叠展开吗？可否来个在线 demo？

**Comment by xiangdongbu** [comment]
> > 比如list里的每一条都可以点击展开 默认是全部收起的
> 
> 是像 antd [Collapse](https://4x-ant-design.antgroup.com/components/collapse-cn/) 组件这样折叠展开吗？可否来个在线 demo？

是的 跟antd [Collapse](https://4x-ant-design.antgroup.com/components/collapse-cn/) 组件 一样

**Comment by xiangdongbu** [comment]
> > 比如list里的每一条都可以点击展开 默认是全部收起的
> 
> 是像 antd [Collapse](https://4x-ant-design.antgroup.com/components/collapse-cn/) 组件这样折叠展开吗？可否来个在线 demo？

[demo](https://codesandbox.io/embed/friendly-dew-g8gpz6?fontsize=14&hidenavigation=1&theme=dark)
有两个问题：

1. 展开以后，往下滑动的时候，会出现跳动；
2. 展开以后，展开状态会丢失，比如第一个展开 往下滑动，等再次划回来的时候，已经是收起的状态。

**Comment by luo3house** [comment]
钩子会把窗口+缓存范围以外的 Item 卸载。由于 demo 给出 itemHeight 是固定的，钩子不会知道 Item 改变了高度，Item 卸载时就会跳

尝试基于 index 计算动态高度：https://github.com/alibaba/hooks/blob/65791303ff1fe4e35395aa7d481f44346d64eba8/packages/hooks/src/useVirtualList/demo/demo2.tsx#L20-L25

**Comment by liuyib** [comment]
> [demo](https://codesandbox.io/embed/friendly-dew-g8gpz6?fontsize=14&hidenavigation=1&theme=dark) 有两个问题：
> 
> 1. 展开以后，往下滑动的时候，会出现跳动；
> 2. 展开以后，展开状态会丢失，比如第一个展开 往下滑动，等再次划回来的时候，已经是收起的状态。

useVirtualList 并不会真的渲染所有 N 个项，而是复用 DOM。前面展开的项，其 DOM 会被后面的项复用，复用其实就是重新计算为新的项，旧的展开状态自然就没了，所以没法做到第二点。

第一点，我这里看你给的在线 demo，没复现。

@luo3house  的思路应该可以解决第一点，试试呢 @xiangdongbu 

> 钩子会把窗口+缓存范围以外的 Item 卸载。由于 demo 给出 itemHeight 是固定的，钩子不会知道 Item 改变了高度，Item 卸载时就会跳
> 
> 尝试基于 index 计算动态高度：
> 
> https://github.com/alibaba/hooks/blob/65791303ff1fe4e35395aa7d481f44346d64eba8/packages/hooks/src/useVirtualList/demo/demo2.tsx#L20-L25

**Comment by liuyib** [comment]
> 2. 展开以后，展开状态会丢失，比如第一个展开 往下滑动，等再次划回来的时候，已经是收起的状态。

@xiangdongbu  我写了个 demo，自己缓存状态，可以解决第二点状态被重置的问题： 
https://codesandbox.io/s/ahooks-issue-2049-d6w6cz?file=/App.tsx

> 1. 展开以后，往下滑动的时候，会出现跳动；

第一点我怎么都复现不了，来个复现的录屏看下呢 @xiangdongbu

**Comment by xiangdongbu** [comment]
> > 2. 展开以后，展开状态会丢失，比如第一个展开 往下滑动，等再次划回来的时候，已经是收起的状态。
> 
> @xiangdongbu 我写了个 demo，自己缓存状态，可以解决第二点状态被重置的问题： https://codesandbox.io/s/ahooks-issue-2049-d6w6cz?file=/App.tsx
> 
> > 1. 展开以后，往下滑动的时候，会出现跳动；
> 
> 第一点我怎么都复现不了，来个复现的录屏看下呢 @xiangdongbu

好的 👌🏻
