### ISSUE TITLE
基于useAntdTable二次封装设置pagination是ts类型校验错误

### ISSUE THREAD

**Issue by jin-benben** [alibaba/hooks#206]
![image](https://user-images.githubusercontent.com/27982466/71538182-e80db380-2961-11ea-8281-377fc1d5136a.png)

**Comment by brickspert** [comment]
先这样解决下，后面这块的 ts 类型会修复下。

![image](https://user-images.githubusercontent.com/12526493/71541870-2757f680-299a-11ea-836f-389e3f8d798b.png)

**Comment by jin-benben** [comment]
> 先这样解决下，后面这块的 ts 类型会修复下。
> 
> ![image](https://user-images.githubusercontent.com/12526493/71541870-2757f680-299a-11ea-836f-389e3f8d798b.png)

好的，谢谢
