### ISSUE TITLE
useRequest轮训的时候第一次轮训需要loading,后面轮训不需要loading的设置

### ISSUE THREAD

**Issue by xiaolifeipiao** [alibaba/hooks#2066]

**Comment by goodjun** [comment]
@xiaolifeipiao 个人觉得这个功能比较定制化，你可以使用以下方式实现你的功能：

```tsx
export default () => {
  const { data, loading, run } = useRequest(getUsername, {
    manual: true,
    pollingInterval: 2000,
    pollingWhenHidden: false
  });

  const hasLoadedBefore = useRef(false);

  const keepFirstLoading = useMemo(
    () =>
      loading && !hasLoadedBefore.current
        ? ((hasLoadedBefore.current = true), loading)
        : false,
    [loading, hasLoadedBefore]
  );

  return (
    <>
      <p>normal loading: {loading ? "true" : "false"}</p>
      <p>keep only the first loading: {keepFirstLoading ? "true" : "false"}</p>
      <p>username: {loading && data}</p>
      <button type="button" onClick={run}>
        start
      </button>
    </>
  );
};
```

[codesandbox](https://codesandbox.io/s/use-request-polling-loading-xpo6pm?file=/App.tsx)

**Comment by xiaolifeipiao** [comment]
thank you

> @xiaolifeipiao 个人觉得这个功能比较定制化，你可以使用以下方式实现你的功能：
> 
> ```tsx
> export default () => {
>   const { data, loading, run } = useRequest(getUsername, {
>     manual: true,
>     pollingInterval: 2000,
>     pollingWhenHidden: false
>   });
> 
>   const hasLoadedBefore = useRef(false);
> 
>   const keepFirstLoading = useMemo(
>     () =>
>       loading && !hasLoadedBefore.current
>         ? ((hasLoadedBefore.current = true), loading)
>         : false,
>     [loading, hasLoadedBefore]
>   );
> 
>   return (
>     <>
>       <p>normal loading: {loading ? "true" : "false"}</p>
>       <p>keep only the first loading: {keepFirstLoading ? "true" : "false"}</p>
>       <p>username: {loading && data}</p>
>       <button type="button" onClick={run}>
>         start
>       </button>
>     </>
>   );
> };
> ```
> 
> [codesandbox](https://codesandbox.io/s/use-request-polling-loading-xpo6pm?file=/App.tsx)
