### ISSUE TITLE
Dyanmic table - Synchronize list and form data

### ISSUE THREAD

**Issue by tnduc** [alibaba/hooks#207]
- I want to use data from the form, but it's not consistent with the `Dynamic table` data. I use `useEffect()` but a lot of bugs [Code demo](https://codesandbox.io/s/hooks-demo-qnkex?fontsize=14&hidenavigation=1&theme=dark). 
For example, when deleting a row from a table, the form data remains ...

- Is there any way to help me accomplish this?
- How would you feel if you built `Dynamic table` like this [Dynamic Form Item
](https://ant.design/components/form/#components-form-demo-dynamic-form-item)

**Comment by ttys026** [comment]
> Is there any way to help me accomplish this?

Your demo doesn't seem buggy to me. The printed form value( when you hit the submit button) is correct. the list is just used as an initialValue container and won't updated, unless you called `replace` each time your update your form fields.

My suggestion is, In these scenarios, if you wanna use the antd form to store data,  always use `sortForm` to wrap it. all the undefined value will be removed, and order of form fields will be taken care.

> How would you feel if you built `Dynamic table` like this Dynamic Form Item

The is the traditional `class` way to make a dynamic form, what we do is provide an easy way for you to build a dynamic form using hooks. This hook contains all the logic we think you may need when building a dynamic form. You need to take care of the UI part though
