### ISSUE TITLE
useAntdTable的mutate方法不生效，而且会直接清空table的数据

### ISSUE THREAD

**Issue by feimiaojie** [alibaba/hooks#2075]
文档里有说明useRequest 所有参数和返回结果均适用于 useAntdTable，但这句话挺隐蔽的以至于不少新接触ahooks的同学可能不知道useAntdTable有mutate方法，所以我也没搜到有人写过useAntdTable场景使用mutate的例子
重现方式直接复制官网useAntdTable的第一个例子，加一个按钮和onClick事件去调用mutate
const { tableProps, mutate } = useAntdTable(getTableData);
mutate(tableProps.dataSource)或者mutate([...tableProps.dataSource]) 均会清空table

...
      <>
            <Button onClick={() => {
                mutate(tableProps.dataSource)
            }}>Click</Button>
            <Table columns={columns} rowKey="email" {...tableProps} />
        </>

**Comment by liuyib** [comment]
@feimiaojie  这是你的使用问题。请问你的项目里没用到类型检测的工具吗？（TypeScript、Flow、....）。按照你的描述我复现了代码，会提示类型错误的：

<img width="853" alt="image" src="https://user-images.githubusercontent.com/38221479/220556900-1f86e8f2-4688-44ae-b827-9817b97f73de.png">

`mutate ` 接收到的参数，结构上需要和 `getTableData` 返回的结构一致。官网第一个例子中，`getTableData` 返回的结构：

```js
{ total, list }
```

所以，你的 `mutate` 也需要接收这样的结构的数据：

```js
mutate({
  total: tableProps.dataSource.length,
  list: tableProps.dataSource,
})
```

**Comment by liuyib** [comment]
另外文档的描述问题，有好的想法可以给个 PR，@feimiaojie

**Comment by liuyib** [comment]
@crazylxr   使用上的问题，不是 bug，可以关了。但是文档貌似描述的不太清楚？

**Comment by feimiaojie** [comment]
@liuyib 我在学习ahooks，在自己的demo里做练习，像偷懒所以没用ts，ts用的也不是太熟练所以压根没看懂源码里的类型要求是getTableData，非常感谢，我试了你的方法可以工作

**Comment by feimiaojie** [comment]
@liuyib 我在学习ahooks，在自己的demo里做练习，想偷懒所以没用ts，ts用的也不是太熟练所以压根没看懂源码里的类型要求要和getTableData service的一致，非常感谢，我试了你的方法可以工作
