### ISSUE TITLE
useVirtualList的originalList的长度太小会无限触发render

### ISSUE THREAD

**Issue by feijihe** [alibaba/hooks#2077]
文档上的`originalList`的说明是：**包含大量数据的列表**，我测试的时候数据就给了几个，就导致浏览器就卡死了。

**Comment by liuyib** [comment]
@feijihe  暂时无法复现，需要提供更多信息。能否用 CodeSandbox 分享下你的代码。

**Comment by liuyib** [comment]
@feijihe 请执行以下指令：`npx envinfo --system --binaries --browsers --npmPackages react,ahooks`，把打印出来的信息反馈到这里，另外你使用的哪个浏览器测试的？

**Comment by feijihe** [comment]
> @feijihe 暂时无法复现，需要提供更多信息。能否用 CodeSandbox 分享下你的代码。

非常抱歉，是我使用方法搞错了。
```ts
  const [list] = useVirtualList(originalList.slice(1, 10), {
    containerTarget: containerRef,
    wrapperTarget: wrapperRef,
    itemHeight: 60,
    overscan: 10
  });
```
`originalList`我使用slice来截取长度导致错误
