### ISSUE TITLE
useReactive 关于 RegExp 的bug

### ISSUE THREAD

**Issue by xluoyu** [alibaba/hooks#2080]
用例如下：

```js

const a = useReactive({
  b: /123/
})

a.b.test('321')
```

此时浏览器就会报错
`Uncaught TypeError: Method RegExp.prototype.exec called on incompatible receiver [object RegExp]`

目前拿到的 `a.b` 是一个被 `Proxy` 包裹的 `RegExp` ，在后续的使用中造成了麻烦，希望可以在 `get` 时增加一些类型判断，在必要时返回原始类型的数据。

🫡🫡🫡

**Comment by SignDawn** [comment]
出于什么原因？要在 正则 上用 useReactive

**Comment by liuyib** [comment]
虽然这种特殊的值在 useReative 里可能不太常用，但是已经在处理了，[PR](https://github.com/alibaba/hooks/pull/2079) 如果能合并的话，这个问题就可以解决了  @xluoyu
