### ISSUE TITLE
[RFC] useRequest 能否提供一个类run API，能够让新params与上一次的params合并成最终新的params

### ISSUE THREAD

**Issue by xliez** [alibaba/hooks#2081]
# 涉及的API

useRequest

# 提案内容

useRequest 新增返回方法 `refreshMerge(params)`:  接受新的 params 与上一次的 params 做覆盖合并，然后调用 run

# 背景

比如搜索查询的场景下，查询参数是依次叠加上去，条件缩窄，目前的 useRequest 要实现的话需要将所有参数都自己维护一套状态，新的参数需要和之前的参数一起丢进 run 函数中。
是否能提供一个类似 `refreshMerge(params)` 这样的API，这样的话只需要在触发缩窄的时机传入单个新参数即可。

# API

```
const {
    refreshMerge: (...params: TParams) => void,
    refreshMergeAsync: (...params: TParams) => Promise<TData>,
  } = useRequest<TData, TParams>(
    service: (...args: TParams) => Promise<TData>
  );
```

# Demo

```typescript
const { run, refreshMerge } = useRequset(service);

run({ id: 1}) // => final params: { id: 1 }
refreshMerge({ name: 'Jone' }) // => final params: { id: 1, name: 'Jone' }
refreshMerge({ age: 18 }) // => final params: { id: 1, name: 'Jone', age: 18 }
refreshMerge({ id: 2 }) // => final params: { id: 2, name: 'Jone', age: 18 }
run({ id: 3 }) // => final params: { id: 3 }
```

**Comment by SignDawn** [comment]
params 手动合并是不是也可以？

`const { run, params} = useRequset(service);
run({...params[0], name: '213'}
`

**Comment by xliez** [comment]
> params 手动合并是不是也可以？
> 
> `const { run, params} = useRequset(service); run({...params[0], name: '213'} `

是哦，漏了还有 params 这个返回
