### ISSUE TITLE
useBoolean的初始值问题

### ISSUE THREAD

**Issue by KangXinzhi** [alibaba/hooks#2103]
当初始值传入是非boolean类型的数据时，点击toggle时。是一个非boolean类型的初始值和一个boolean值在切换。
比如传入参数是123，点击toggle方法，此时state在123和false之间来回转换。当点击setTrue，再点击toggle方法，我理解state应该变成由true变成false，而实际情况时变成了123。

https://codesandbox.io/s/ji-chu-yong-fa-forked-hdrtyl?file=/App.tsx

是否有必要在函数初始化时，将参数值转为boolean类型的值后再进行后续操作。感觉更符合useBoolean的语义。
```

**Comment by liuyib** [comment]
repeat https://github.com/alibaba/hooks/issues/2104
