### ISSUE TITLE
useBoolean的初始值问题

### ISSUE THREAD

**Issue by KangXinzhi** [alibaba/hooks#2104]
当初始值传入是非boolean类型的数据时，点击toggle时。是一个非boolean类型的初始值和一个boolean值在切换。
比如传入参数是123，点击toggle方法，此时state在123和false之间来回转换。当点击setTrue，再点击toggle方法，我理解state应该变成由true变成false，而实际情况时变成了123。

https://codesandbox.io/s/ji-chu-yong-fa-forked-hdrtyl?file=/App.tsx

是否有必要在函数初始化时，将参数值转为boolean类型的值后再进行后续操作。感觉更符合useBoolean的语义。

**Comment by KangXinzhi** [comment]
```
export default function useBoolean(defaultValue = false): [boolean, Actions] {
// 转为boolean类型的值后再进行后续操作
  const [state, { toggle, set }] = useToggle(!!defaultValue);

  const actions: Actions = useMemo(() => {
    const setTrue = () => set(true);
    const setFalse = () => set(false);
    return {
      toggle,
      set: (v) => set(!!v),
      setTrue,
      setFalse,
    };
  }, []);

  return [state, actions];
}
```

**Comment by liuyib** [comment]
这种没法通过类型检查吧，会 warning 提示出来。其次后续 ahooks 应该会打算：用户传入不合法的参数值或类型时，打印错误提示，防止用户输入类型不合法的值。useBoolean 的默认值的类型，应该由用户侧来保证，我们替用户在背后做转换，万一结果超出了用户意料之外，依然会导致用户疑惑。

**Comment by KangXinzhi** [comment]
> 这种没法通过类型检查吧，会 warning 提示出来。其次后续 ahooks 应该会打算：用户传入不合法的参数值或类型时，打印错误提示，防止用户输入类型不合法的值。useBoolean 的默认值的类型，应该由用户侧来保证，我们替用户在背后做转换，万一结果超出了用户意料之外，依然会导致用户疑惑。

感谢回复。打印错误提示可以帮助用户了解何时传递了不合法的参数值。在这种情况下，提到的用户保证默认值类型的方法似乎是最好的解决方案。

**Comment by liuyib** [comment]
> > 这种没法通过类型检查吧，会 warning 提示出来。其次后续 ahooks 应该会打算：用户传入不合法的参数值或类型时，打印错误提示，防止用户输入类型不合法的值。useBoolean 的默认值的类型，应该由用户侧来保证，我们替用户在背后做转换，万一结果超出了用户意料之外，依然会导致用户疑惑。
> 
> 感谢回复。打印错误提示可以帮助用户了解何时传递了不合法的参数值。在这种情况下，提到的用户保证默认值类型的方法似乎是最好的解决方案。

“打印错误提示” 这是我的个人想法，不一定做。

团队内部讨论的结果，会对默认值做类型转换处理，毕竟 actions 中的 set 函数都转换类型了 `set: (v) => set(!!v)`。可以来个 PR （对默认值做类型转换处理）吗？ @KangXinzhi   搞完 PR 可以 @ 我来 review

**Comment by KangXinzhi** [comment]
> > > 这种没法通过类型检查吧，会 warning 提示出来。其次后续 ahooks 应该会打算：用户传入不合法的参数值或类型时，打印错误提示，防止用户输入类型不合法的值。useBoolean 的默认值的类型，应该由用户侧来保证，我们替用户在背后做转换，万一结果超出了用户意料之外，依然会导致用户疑惑。
> > 
> > 
> > 感谢回复。打印错误提示可以帮助用户了解何时传递了不合法的参数值。在这种情况下，提到的用户保证默认值类型的方法似乎是最好的解决方案。
> 
> “打印错误提示” 这是我的个人想法，不一定做。
> 
> 团队内部讨论的结果，会对默认值做类型转换处理，毕竟 actions 中的 set 函数都转换类型了 `set: (v) => set(!!v)`。可以来个 PR （对默认值做类型转换处理）吗？ @KangXinzhi 搞完 PR 可以 @ 我来 review
ok~

**Comment by KangXinzhi** [comment]
> > > > 这种没法通过类型检查吧，会 warning 提示出来。其次后续 ahooks 应该会打算：用户传入不合法的参数值或类型时，打印错误提示，防止用户输入类型不合法的值。useBoolean 的默认值的类型，应该由用户侧来保证，我们替用户在背后做转换，万一结果超出了用户意料之外，依然会导致用户疑惑。
> > > 
> > > 
> > > 感谢回复。打印错误提示可以帮助用户了解何时传递了不合法的参数值。在这种情况下，提到的用户保证默认值类型的方法似乎是最好的解决方案。
> > 
> > 
> > “打印错误提示” 这是我的个人想法，不一定做。
> > 团队内部讨论的结果，会对默认值做类型转换处理，毕竟 actions 中的 set 函数都转换类型了 `set: (v) => set(!!v)`。可以来个 PR （对默认值做类型转换处理）吗？ @KangXinzhi 搞完 PR 可以 @ 我来 review
> > ok~

@liuyib
