### ISSUE TITLE
useRequest 被删除的能力如何兼容

### ISSUE THREAD

**Issue by komagic** [alibaba/hooks#2109]
formatResult 在之前很多项目中使用了。
升级后，突然没了。项目突然都失效了。
戛然而止的反馈真的很不友好。

希望你的离开不是心态问题

**Comment by liuyib** [comment]
@komagic 

useRequest 被删除的能力如何兼容: https://ahooks.js.org/zh-CN/guide/upgrade#userequest-%E8%A2%AB%E5%88%A0%E9%99%A4%E7%9A%84%E8%83%BD%E5%8A%9B%E5%A6%82%E4%BD%95%E5%85%BC%E5%AE%B9

**Comment by liuyib** [comment]
这样是不是可以解决你的问题：

```ts
const { data } = useRequest(async () => {
  const result = await getData();
  return formatResult(result.data);
});
```

@komagic

**Comment by komagic** [comment]
主要十几个应用很多业务代码都用的 formatReuslt，突然换了个方式写，业务代码很多地方报错，要修改。
你们代码也不报异常，也不发提示。
这不是会不会升级的问题，是作为一个核心库的责任问题

**Comment by KingAmo** [comment]
![image](https://user-images.githubusercontent.com/29938227/224596934-b66c1cdf-843b-474b-af6d-fbef4e856377.png)

https://twitter.com/youyuxi/status/1634542278802030592

**Comment by liuyib** [comment]
> 

这边建议不要你升级。另外，开源库没有责任一说，我们无偿维护。实在不满意的话，推荐你试试竞品呢，例如 react-use

**Comment by liuyib** [comment]
> 主要十几个应用很多业务代码都用的 formatReuslt，突然换了个方式写，业务代码很多地方报错，要修改。 你们代码也不报异常，也不发提示。 这不是会不会升级的问题，是作为一个核心库的责任问题

这边建议你不要升级。另外，开源库没有责任一说，我们无偿维护。实在不满意的话，推荐你试试竞品呢，例如 react-use

**Comment by liuyib** [comment]
> 主要十几个应用很多业务代码都用的 formatReuslt，突然换了个方式写，业务代码很多地方报错，要修改。 你们代码也不报异常，也不发提示。 这不是会不会升级的问题，是作为一个核心库的责任问题

升级大版本是用户侧自行决定的事，前提就是用户需要自行承担升级带来的改动工作，不愿意承担可以不升级。我们只保证“当你遇到升级文档 cover 不住你的升级”时，给予解答。不保证“升级大版本不需要代码改动，完全向后兼容”，这一点我们做不到，其他库也做不到，甚至 react 都没做到（类组件删除了一些生命周期）

**Comment by komagic** [comment]
react肯定会提前在几个版本中，提示某个功能在某个版本后会废弃。
而不是直接啥也不说就没了。而且什么报错也没有

**Comment by komagic** [comment]
肯定接下来 我们这条 业务线全面使用react-query，不会用这个了。

普通开源库我才不鸟。bigfish可以把这库剔除了

**Comment by liuyib** [comment]
> 肯定接下来 我们这条 业务线全面使用react-query，不会用这个了。
> 
> 普通开源库我才不鸟。bigfish可以把这库剔除了

正解，请求相关的处理确实推荐你用 react-query，毕竟这个库是专业处理请求的

**Comment by komagic** [comment]
> ![image](https://user-images.githubusercontent.com/29938227/224596934-b66c1cdf-843b-474b-af6d-fbef4e856377.png)
> 
> https://twitter.com/youyuxi/status/1634542278802030592

别，你看你库挂在哪个公司下面

**Comment by louhaojie99** [comment]
> ![image](https://user-images.githubusercontent.com/29938227/224596934-b66c1cdf-843b-474b-af6d-fbef4e856377.png)
> 
> https://twitter.com/youyuxi/status/1634542278802030592

作为一个核心库突然下掉一个 API 参数虽不友好，但是作为我们白嫖使用方具体问题具体解决吧。。。🤣
