### ISSUE TITLE
useInViewport的问题

### ISSUE THREAD

**Issue by nick121212** [alibaba/hooks#2110]
问题：
    目前正在做一个next.js的项目，当使用动态模块的时候。 ahook的版本是3.7.5

```
    const Module =  dynamic(() => import('@modules/modle1'), {
      ssr: false,
    });

```

我在模块外部传入ref到这个动态模块Module的时候，这个时候hook不工作，此时imppd11.current能拿到正确的dom元素。

```
  const imppd11 = useRef();
  const [inViewport1, ratio1] = useInViewport(imppd11, {});

 return <Module ref={imppd11} />

```

**Comment by liuyib** [comment]
@nick121212  可以给个在线示例吗？感谢

**Comment by liuyib** [comment]
貌似是不是可以通过这个方法解决：

https://ahooks.js.org/zh-CN/guide/blog/ssr

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/38221479/225047261-b15db96e-9d4d-4cdf-afb0-32714b7a3dda.png">

试下呢  @nick121212

**Comment by liuyib** [comment]
> const [inViewport1, ratio1] = useInViewport(imppd11, {});

给 `useInViewport` 传 ref 时，用回调试试： `const [inViewport1, ratio1] = useInViewport(() => imppd11, {});`  @nick121212
