### ISSUE TITLE
【 useInViewport】【feature request】希望inViewport属性设置默认值false 或者 option 参数可设置inViewport的默认值

### ISSUE THREAD

**Issue by KingAmo** [alibaba/hooks#2111]
### 为什么

在使用 `useRequest` 时，希望组件可见时才发出某个接口请求
```
  const [inViewport] = useInViewport(ref);

  useRequest(getUserApi, {ready: inViewport})
```
由于 `inViewport` 默认值为`undefined`，导致 `ready`为 `undefined`，
而 `ready` 的默认值 为 `true`，使得组件在不可见时发出了请求，不符合预期。
除非这样使用：
```
  const [inViewport = false] = useInViewport(ref);
```
感觉不太方便
能否使 `inViewport` 的默认值为 `false` 呢？

**Comment by liuyib** [comment]
我认为可以加上默认值，已提 PR，如果能合并的话，就可以解决了 @KingAmo

**Comment by liuyib** [comment]
useInViewport 之前返回状态的默认值是 undefined，如果被用户用于逻辑判断，如 `isViewport ? 'visible' : 'hidden'` 会走 falsy 逻辑，和默认值是 false 行为一样。是不是设置 false 默认值更好些？ @crazylxr

**Comment by crazylxr** [comment]
不建议改哈。算是一个 小的 break change。

另外我觉得这个没必要改哈，不能因为 useRequest 的 ready 是 undefined  默认是 true，就得把该 hook 的默认值改为 false 哈，这样的话，如果 ready 值依赖其他的 hook 是不是其他所有 默认值是 undefined 的 hook 都得改。

**Comment by crazylxr** [comment]
对于 @KingAmo  的说的不太方便，我不太能理解，就加个 ` = false`  这完全不算成本吧。另外还想 通过 option 去设置 默认值，这样岂不是更麻烦了。需要增加更多的代码。
