### ISSUE TITLE
[QUESTION] useFusionTable如何正确得处理分页问题，例如分页页码变化进行拦截并且不进行后续请求

### ISSUE THREAD

**Issue by topwood** [alibaba/hooks#2115]
const getTableData = ({ current, pageSize }): Promise<Result> => {
  const query = `page=${current}&size=${pageSize}`;

  return fetch(`https://randomuser.me/api?results=${pageSize}&${query}`)
    .then((res) => res.json())
    .then((res) => ({
      total: 55,
      list: res.results.slice(0, 10),
    }));
};

const AppList = () => {
  const { paginationProps, tableProps } = useFusionTable(getTableData);

  return (
    <>
      <Table {...tableProps} primaryKey="email">
        <Table.Column title="name" dataIndex="name.last" width={140} />
        <Table.Column title="email" dataIndex="email" width={500} />
        <Table.Column title="phone" dataIndex="phone" width={500} />
        <Table.Column title="gender" dataIndex="gender" width={500} />
      </Table>
      <Pagination style={{ marginTop: 16 }} {...paginationProps} />
    </>
  );
};

以上是实例代码，如果表格有翻页，并且想做到：
用户在翻页页码数大于50的时候，新进行弹窗提示，并且不在进行接口请求。

1. 如果在 getTableData里面判断current，那么会导致这个方法的返回值影响表格的展示
2. 如果在getTableData里面执行cancel，虽然可以取消查询，但是页码还是变了

请问有什么方式可以做到？

**Comment by topwood** [comment]
![image](https://user-images.githubusercontent.com/13791267/224634271-a6ff6dad-42e7-4fb0-a3f1-393921508327.png)


如果覆盖onChange，那么不知道怎么处理current了

**Comment by hchlq** [comment]
> 如果在 getTableData里面判断current，那么会导致这个方法的返回值影响表格的展示

这个可以影响是咋样的呢，返回和当前页同样的值不就行了么

**Comment by goodjun** [comment]
@topwood 可以给个在线演示DEMO吗？

**Comment by hchlq** [comment]
久不回复，先 close 掉哈
