### ISSUE TITLE
useInfiniteScroll加载更多的时候，再触发重新加载，这时候不会及时返回重新加载的loading

### ISSUE THREAD

**Issue by hubaobao1223** [alibaba/hooks#2118]
https://ahooks.js.org/zh-CN/hooks/use-infinite-scroll#%E6%95%B0%E6%8D%AE%E9%87%8D%E7%BD%AE
![image](https://user-images.githubusercontent.com/38289190/224884117-c223582b-e6f7-4cdd-b72a-6561fd498efc.png)

就用官方文档中的这个例子，点击加载更多之后，再马上进行筛选，这时候还在加载更多的状态。
在实际业务场景中，请求时间比较长的情况下，这个看起来是个非常明显的bug。
理论上下次重新加载请求触发的时候，前面的分页加载就应该马上停止并更新数据。
使用了cancel方法也没有效果。

**Comment by hchlq** [comment]
感谢 issue，预计修复后的状态：

![20230314131143_rec_](https://user-images.githubusercontent.com/60802048/224900997-1fc28f3d-0aba-45c9-9525-3d6e8b36ac97.gif)
