### ISSUE TITLE
useFavicon doesn't work on Safari

### ISSUE THREAD

**Issue by hhhluke** [alibaba/hooks#2126]
[useFavicon document](https://ahooks.js.org/hooks/use-favicon/)

Demo doesn't work on Safari

**Comment by goodjun** [comment]
I did some research and found out that Safari currently does not support dynamic changing of favicons.

[Brady Eidson (Apple software engineer) says:](https://bugs.webkit.org/show_bug.cgi?id=95979#c2)
> We (Apple) intentionally do not want the ability to script favicons.

do we need to update the document? @crazylxr

**Comment by liuyib** [comment]
> I did some research and found out that Safari currently does not support dynamic changing of favicons.
> 
> [Brady Eidson (Apple software engineer) says:](https://bugs.webkit.org/show_bug.cgi?id=95979#c2)
> 
> > We (Apple) intentionally do not want the ability to script favicons.
> 
> do we need to update the document? @crazylxr

Thanks for your help, would you like to contribute a PR that include a FAQ to explain this?

**Comment by goodjun** [comment]
Sure, I am very willing.
