### ISSUE TITLE
useWebsocket 的 connect 方法不能确保当前实例完全断开后再链接

### ISSUE THREAD

**Issue by Fiv5** [alibaba/hooks#2127]
因为 websocket 的 close 方法不是同步的，当前代码实现里是同步调用了 `wsIns.close` 然后重新实例化 WS，可能会导致上一个链接还未关闭，新的实例又进行了创建，进而直接影响了 readState 的更新时序

**Comment by hchlq** [comment]
给个在线 demo 看看哈

**Comment by hchlq** [comment]
和 useWebSocket 没关系，业务需要自己判断，可以在 onClose 钩子中再去重新实例化
