### ISSUE TITLE
[RFC] useDerivedState

### ISSUE THREAD

**Issue by vaynevayne** [alibaba/hooks#2134]
派生状态 以便实现半受控模式, 比如: 当你希望在Modal关闭时,才需要触发 onChange 事件,或者希望在受控模式的 onChange 触发前进行一段校验逻辑,成功才会触发 onChange, 简而言之, 适用于中断 onChange 的场景

### 用法
```jsx
const [internalValue, setInternalValue] = useDerivedState(value)

```

### Demo

```jsx
const InputModal = ({ value, onChange }) => {
  const [internalValue, setInternalValue] = useDerivedState(value)

  return (
    <Modal>
      <Input value={internalValue} onChange={setInternalValue} />
      <Button onClick={() => onChange(internalValue)}>确定</Button>
    </Modal>
  )
}

```

**Comment by hchlq** [comment]
从这个例子没看出这个 hook 适合啥场景，可以给个在线的 demo 看看？

**Comment by vaynevayne** [comment]
https://codesandbox.io/s/ji-ben-yong-fa-antd-5-3-2-forked-21iodh?file=/demo.tsx:0-1076

一个更加贴近生产的例子,  把这个例子里的 input组件 换成 受控组件 JsonEditor, 尝试封装一个在modal里编辑json的组件, 
一般就两种思路: 
 1. 受控模式(value,onChange)?   因为 json编辑过程中,不应该实时的调用onChange,毕竟中途会出现语法错误, 所以希望在关闭弹窗时再把editor 里的值交给外部,  因此不能受控模式 ❌
2. 非受控模式(defaultValue) ? 
传统的方式是封装成 非受控组件, 但是非受控组件接受的defaultValue是只能使用一次的, 无法支持远程数据,  此外 ref 去获取子组件值, 需要父组件维护额外的ref, 子组件也要抛出, 复杂度很高,

3. 在这个需求里, 子组件可以明确知道onChange的调用时间,  因此可以不用非受控模式

另外: 
pr 里有个测试例子, ahooks 提pr 好像不会部署预览, 看到有些项目会自动部署预览

**Comment by hchlq** [comment]
你给的例子不典型，说实话我没太 get 到这个 hook 有啥用， @crazylxr 一起看看哈

**Comment by vaynevayne** [comment]
> 你给的例子不典型，说实话我没太 get 到这个 hook 有啥用， @crazylxr 一起看看哈

做组件的 业务写的少 不理解很正常

**Comment by hchlq** [comment]
你说的对，啥叫做组件的，你很厉害？

**Comment by hchlq** [comment]
已有 useControllableValue

**Comment by vaynevayne** [comment]
> 你说的对，啥叫做组件的，你很厉害？

我并没有骂你的意思啊
