### ISSUE TITLE
如何使用useInfiniteScroll实现向上滚动加载

### ISSUE THREAD

**Issue by Qyokizzzz** [alibaba/hooks#2137]
想做一个聊天窗口，向上滚动加载历史消息，求教，谢谢！

**Comment by liuyib** [comment]
目前 useInfiniteScroll 貌似只支持向下滚动加载更多，我翻到之前有个提案具有上拉加载的能力：https://github.com/alibaba/hooks/issues/7, 但是被关闭了。

临时的解决方案：你可以自己监听页面是否滚动到了父容器的顶部，然后手动触发 useInfiniteScroll 的 loadMore 函数，就可以实现向上滚动加载数据了。 @Qyokizzzz 

@crazylxr  @miracles1919  @hchlq  大佬看看这个怎么说

**Comment by Qyokizzzz** [comment]
> 目前 useInfiniteScroll 貌似只支持向下滚动加载更多，我翻到之前有个提案具有上拉加载的能力：#7, 但是被关闭了。
> 
> 临时的解决方案：你可以自己监听页面是否滚动到了父容器的顶部，然后手动触发 useInfiniteScroll 的 loadMore 函数，就可以实现向上滚动加载数据了。 @Qyokizzzz
> 
> @crazylxr @miracles1919 @hchlq 大佬看看这个怎么说

已实现，感谢！
