### ISSUE TITLE
useMutationObserver 子节点变了没有触发回调

### ISSUE THREAD

**Issue by cuiliangl** [alibaba/hooks#2139]
useMutationObserver(
    () => {
      console.log('变化了')
    },
    scrollNode,
    {
      subtree: true,
      childList: true,
    }
  )
问题：
子节点变了回调没触发，子节点的数量变了才会触发回调。

**Comment by liuyib** [comment]
@cuiliangl  我这边尝试的，改变子节点的 DOM 属性，触发了回调。可以提供个可复现的在线 Demo 吗？感谢

**Comment by cuiliangl** [comment]
>

**Comment by cuiliangl** [comment]
> 

是不是 "^3.7.6" 版本修复了，升级了下版本能触发了。
之前 target 从 一个子节点切换成另一个子节点就不会触发，从一个切换成多个（也就是节点数量发生变化）就会触发。

**Comment by cuiliangl** [comment]
> @cuiliangl 我这边尝试的，改变子节点的 DOM 属性，触发了回调。可以提供个可复现的在线 Demo 吗？感谢

是不是 "^3.7.6" 版本修复了，升级了下版本能触发了。
之前 target 从 一个子节点切换成另一个子节点就不会触发，从一个切换成多个（也就是节点数量发生变化）就会触发。

**Comment by liuyib** [comment]
> > @cuiliangl 我这边尝试的，改变子节点的 DOM 属性，触发了回调。可以提供个可复现的在线 Demo 吗？感谢
> 
> 是不是 "^3.7.6" 版本修复了，升级了下版本能触发了。 之前 target 从 一个子节点切换成另一个子节点就不会触发，从一个切换成多个（也就是节点数量发生变化）就会触发。

应该是 [这个 PR 修复的](https://github.com/alibaba/hooks/commit/b7d6114adf3386367db5f1f60383eb347a9aa6fa#diff-c1813ef389e60fc43b1d0f16f04bc53261b2869b27f71d9b18d9ab24afb3988f), 这个 PR 里面把 useEffect 换成了 useDeepCompareEffectWithTarget, 可以深度对比 target 的变动。 刚尝试了下，确实是这个 PR 修复的。

影响的版本有这些：

![image](https://user-images.githubusercontent.com/38221479/228749092-f2904383-3372-4b8a-a486-473e050edaff.png)
