### ISSUE TITLE
[createDeepCompareEffect] 中的代码存在问题，ref是不能作为useEffec的依赖的，如果只是更新ref的值更新是无法触发依赖更新

### ISSUE THREAD

**Issue by explorerc** [alibaba/hooks#2145]
```ts
const Test = function () {
  const countRef= useRef<number>(0);
  useEffect(() => {
    console.log('countRef change ======', countRef.current)
  }, [countRef.current])

  const handleClick = () => {
    countRef.current +=  countRef.current;
  };

  return <div onClick={handleClick}>click me</div>;
};
```

demo地址：https://code.juejin.cn/pen/7218899263680413751

**Comment by SignDawn** [comment]
const Test = function () {
  const [reload, setReload] = useState(false);
  const countRef= useRef<number>(1);
  useEffect(() => {
    console.log('countRef change ======', countRef.current)
  }, [countRef.current])

  const handleClick = () => {
    countRef.current +=  countRef.current;
     setReload(!reload);
  };

  return <div onClick={handleClick}>click me</div>;
};

**Comment by SignDawn** [comment]
没有 触发 re-render

**Comment by hchlq** [comment]
这个 hook 就是为 useEffect 增强能力的，本身就需要组件自己更新才会触发 re-render，没有更新是不会执行的，没有问题
