### ISSUE TITLE
useResetState的TypeScript类型定义问题

### ISSUE THREAD

**Issue by zhouzhoucxy** [alibaba/hooks#2153]
### 描述
useResetState的setState,修改某一个属性值时,在tsx中会提示报错

```tsx
import React, { FC } from 'react'
import { Button } from 'antd'
import { useNavigate } from 'react-router-dom'
import { useResetState } from 'ahooks'
interface Props {}
const Use: FC<Props> = () => {
	const  [state, setState, resetState] = useResetState({
		hello: '',
		count: 0,
	})
	return (
		<div>
			Use页面
			<Button
				type='primary'
				onClick={() => {
					setState({count:1})
					
				}}>
				修改
			</Button>
		</div>
	)
}
```

**Comment by liuyib** [comment]
你的 ahooks 版本多少？能否使用 codesandbox 提供一个可复现这个问题的在线 demo？ @zhouzhoucxy  感谢

**Comment by zhouzhoucxy** [comment]
> 你的 ahooks 版本多少？能否使用 codesandbox 提供一个可复现这个问题的在线 demo？ @zhouzhoucxy 感谢

https://codesandbox.io/s/stoic-tree-5fmuhv?file=/App.tsx
官网上面的例子,删除一个属性就会有问题了,代码是能执行成功的,但是在vscode里面启动项目编译会报错的

**Comment by liuyib** [comment]
你用了 TS 对吧？这属于类型问题，就算把 useResetState 换成 useState 也会存在这个问题。类型方面，1. 要么每次更新都全量 `setState((prev) => ({ ...prev, count: 1 }))` 2. 要么忽视类型 `setState({ count: 1 } as any)` 3. 要么给这个 state 的某些字段设置可选。

如果，还有问题的话，麻烦继续反馈。没问题的话就关了吧

**Comment by zhouzhoucxy** [comment]
> 你用了 TS 对吧？这属于类型问题，就算把 useResetState 换成 useState 也会存在这个问题。类型方面，1. 要么每次更新都全量 `setState((prev) => ({ ...prev, count: 1 }))` 2. 要么忽视类型 `setState({ count: 1 } as any)` 3. 要么给这个 state 的某些字段设置可选。
> 
> 如果，还有问题的话，麻烦继续反馈。没问题的话就关了吧

好的,我以为是和useSetState的setState一致的用法,抱歉.没问题了
