### ISSUE TITLE
useClickAway 在 CssTransition 包裹的节点中的问题

### ISSUE THREAD

**Issue by cuiliangl** [alibaba/hooks#2154]
代码：
<img width="678" alt="image" src="https://user-images.githubusercontent.com/25759364/231170763-b7c0ebc2-ed41-4bba-b94f-0ea0fb3bf0d3.png">

visible 为父组件传入的

问题：
当visible为true时，组件展示，useClickAway 就会执行一次。而不是点击ref节点之外的其他区域时触发。

**Comment by liuyib** [comment]
@cuiliangl  可以提供一个能够复现这个问题的在线 demo 吗（用 codesandbox、codepen、码上掘金 等都可以）？ 感谢

**Comment by cuiliangl** [comment]
>

**Comment by cuiliangl** [comment]
> @cuiliangl 可以提供一个能够复现这个问题的在线 demo 吗（用 codesandbox、codepen、码上掘金 等都可以）？ 感谢

写了个demo复现了下，https://codesandbox.io/s/practical-lichterman-xpc7kg?file=/src/Dialog/index.js

**Comment by liuyib** [comment]
@cuiliangl  我参考了你提供的在线 demo，目前来看代码逻辑本身是有问题的，我猜测你想实现：点击“打开 Dialog”按钮，弹出 Dialog 组件，点击遮罩或 Dialog 里的关闭按钮，则关闭 Dialog。如果是我猜测的这样，你应该这样用：https://codesandbox.io/s/ahooks-issue-2154-7fgjpd?file=/src/App.js

如果不是我猜测的这样，请继续反馈，你想实现什么样的功能效果？详细描述下。

**Comment by cuiliangl** [comment]
> @cuiliangl 我参考了你提供的在线 demo，目前来看代码逻辑本身是有问题的，我猜测你想实现：点击“打开 Dialog”按钮，弹出 Dialog 组件，点击遮罩或 Dialog 里的关闭按钮，则关闭 Dialog。如果是我猜测的这样，你应该这样用：https://codesandbox.io/s/ahooks-issue-2154-7fgjpd?file=/src/App.js
> 
> 如果不是我猜测的这样，请继续反馈，你想实现什么样的功能效果？详细描述下。

是的，我一开始也是想是不是我的使用方式有问题，但没想清楚问题在哪里。非常感谢。

**Comment by cuiliangl** [comment]
> @cuiliangl 我参考了你提供的在线 demo，目前来看代码逻辑本身是有问题的，我猜测你想实现：点击“打开 Dialog”按钮，弹出 Dialog 组件，点击遮罩或 Dialog 里的关闭按钮，则关闭 Dialog。如果是我猜测的这样，你应该这样用：https://codesandbox.io/s/ahooks-issue-2154-7fgjpd?file=/src/App.js
> 
> 如果不是我猜测的这样，请继续反馈，你想实现什么样的功能效果？详细描述下。

但是这种方式增加了使用成本，需要在每个使用到的地方调用useClickAway来控制点击mask是否可关闭。

**Comment by liuyib** [comment]
> > @cuiliangl 我参考了你提供的在线 demo，目前来看代码逻辑本身是有问题的，我猜测你想实现：点击“打开 Dialog”按钮，弹出 Dialog 组件，点击遮罩或 Dialog 里的关闭按钮，则关闭 Dialog。如果是我猜测的这样，你应该这样用：https://codesandbox.io/s/ahooks-issue-2154-7fgjpd?file=/src/App.js
> > 如果不是我猜测的这样，请继续反馈，你想实现什么样的功能效果？详细描述下。
> 
> 但是这种方式增加了使用成本，需要在每个使用到的地方调用useClickAway来控制点击mask是否可关闭。

 这样：https://codesandbox.io/s/ahooks-issue-2154-7fgjpd?file=/src/Dialog/index.js, 我修改了下 demo，应该可以解决你的困扰

封装一层，也就往里传一个 ref，不会造成太大的使用困难吧。还不行的话，再想想办法，示例 demo 只是演示，自己可以再思考思考怎么封装。
