### ISSUE TITLE
Update query-string dependency in useStateUrl

### ISSUE THREAD

**Issue by Gusis93** [alibaba/hooks#2155]
It seems like `useStateUrl` is using a version of `query-string` that has a dependency called `decode-uri-component` that has a vulnerability in version `0.2.0`.

Would be great if `query-string` version can be updated to fix this.

**Comment by liuyib** [comment]
We'll try to upgrade it later, thx

**Comment by liuyib** [comment]
这个升了之后，会报错：

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/38221479/232296280-1eec6e04-bbb4-4739-9a2f-b0dc409f61f6.png">

@miracles1919 @li-jia-nan 有空看下，咋解决呢？或者这个有必要升吗？

**Comment by luo3house** [comment]
~看起来有些依赖只分发es6了但是webpack仍然需要es5~ 搞错了 optional chaining 是 ES2020 的对于 webpack 来说太新了。试试让 Babel 额外转换一下它们
https://d.umijs.org/config#extrababelincludes

**Comment by liuyib** [comment]
> 看起来有些依赖只分发es6了但是webpack仍然需要es5 。试试让 Babel 额外转换一下它们 https://d.umijs.org/config#extrababelincludes

加了这个配置：`extraBabelIncludes: ['query-string']` 还是一样的报错 😂。

**Comment by luo3house** [comment]
> > 看起来有些依赖只分发es6了但是webpack仍然需要es5 。试试让 Babel 额外转换一下它们 https://d.umijs.org/config#extrababelincludes
> 
> 加了这个配置：`extraBabelIncludes: ['query-string']` 还是一样的报错 😂。

试试 filter-obj。应该是解析它的时候出现的

https://github.com/sindresorhus/filter-obj/issues/31

**Comment by liuyib** [comment]
> > > 看起来有些依赖只分发es6了但是webpack仍然需要es5 。试试让 Babel 额外转换一下它们 https://d.umijs.org/config#extrababelincludes
> > 
> > 
> > 加了这个配置：`extraBabelIncludes: ['query-string']` 还是一样的报错 😂。
> 
> 试试 filter-obj。应该是解析它的时候出现的

这个可以

**Comment by liuyib** [comment]
I have closed https://github.com/alibaba/hooks/pull/2160, because I can't resolve the build error. Anyone can help?

By the way, maybe `query-string` will be replaced with `qs` in v4: https://github.com/alibaba/hooks/issues/2205, so we don't have to upgrade `query-string`.
