### ISSUE TITLE
@ahooksjs/use-request@2.8.15 peer Dependencies

### ISSUE THREAD

**Issue by SongJuXin** [alibaba/hooks#2156]
我在使用`umi`,创建项目的时候报对等依赖冲突的错误。

定位了一下问题原因，发现`umi`同时依赖了`@ahooksjs/use-request`和`@testing-library/react`这两个库，这两个库分别对`react`存在对等依赖（peerDependencies），但两者的`react`这个库的对等依赖有冲突。
![image](https://user-images.githubusercontent.com/20874344/231483127-0ba249e8-f268-444b-b959-a080bee024d2.png)

尝试去umi那边，提了这个问题，给出需要更换`pnpm`包管理器。

但我使用的是`npm`，不太想换包管理器。

请问这边能兼容下`react`的对等依赖，将`react`版本提升至18版本吗？

@umijs/max:4.0.29
npm:8.19.3
node:v16.19.0
macOS:10.15.7

**Comment by liuyib** [comment]
从你的截图能看出 ahooks 还是 2.x 的版本，支持不了 react  18 的，目前 [ahooks^3.3.0](https://github.com/alibaba/hooks/commit/40a83e217d805512739fbbb8725bc9df05b5fda2) 的版本支持 react 18。

目前解决的办法，我能想到的：
1. 升级 ahooks （这个得让 umi 来升级吧，你这侧应该没办法）
2. 如你所述，更换 pnpm 包管理器

推荐你尝试更换 pnpm 包管理器，安装速度快、node_modules 体积小、不会有幽灵依赖问题等，很多好处。只要你安装后项目能跑起来，基本没啥问题。

**Comment by SongJuXin** [comment]
> 从你的截图能看出 ahooks 还是 2.x 的版本，支持不了 react 18 的，目前 [ahooks^3.3.0](https://github.com/alibaba/hooks/commit/40a83e217d805512739fbbb8725bc9df05b5fda2) 的版本支持 react 18。
> 
> 目前解决的办法，我能想到的：
> 
> 1. 升级 ahooks （这个得让 umi 来升级吧，你这侧应该没办法）
> 2. 如你所述，更换 pnpm 包管理器
> 
> 推荐你尝试更换 pnpm 包管理器，安装速度快、node_modules 体积小、不会有幽灵依赖问题等，很多好处。只要你安装后项目能跑起来，基本没啥问题。

感谢解答，想的简单了，以为`ahooks`只是忘记写`react`的版本，只需加个版本就行了。看来果真是与react18不兼容。
