### ISSUE TITLE
EventEmitter.  useSubscription does not throw any error

### ISSUE THREAD

**Issue by nailfar** [alibaba/hooks#2157]
const emiter = useEventEmitter();
 
emiter.useSubscription(()=>{
// Uncaught ReferenceError: b is not defined
  const v = b.text;
  console.log(v);
})

it should throw error `Uncaught ReferenceError: b is not defined` instead of nothing

**Comment by ch1ny** [comment]
Whether `ahooks` or `javascript`, I think this is the correct behavior. Because when you called `useSubscription()`, you only registered this callback in EventEmitter. Only when you **trigger** the registered callback through `emit()` will the code be executed and throw the error.

**Comment by crazylxr** [comment]
At this point, the callback function of useSubscription has not yet run, so no error will be reported.

**Comment by nailfar** [comment]
@ch1ny If an exception is caughted, it is difficult for developers to discover where the error is coming from.no warnings no errors
