### ISSUE TITLE
useExternal 是否可以在组件卸载时，不移除加载进来的js

### ISSUE THREAD

**Issue by liuyib** [alibaba/hooks#2164]
### Discussed in https://github.com/alibaba/hooks/discussions/2163

<div type='discussions-op-text'>

<sup>Originally posted by **candy4290** April 19, 2023</sup>
场景：我希望自从第一次加载了该资源后。不再移除该资源，这样在需要再次使用该资源时，也就不会重复加载这个资源。
有什么办法吗？</div>

**Comment by liuyib** [comment]
@candy4290

**Comment by candy4290** [comment]
好的，我已经尝试提交了一个PR @liuyib
