### ISSUE TITLE
ahooks中useRequest的参数`staleTime`失效

### ISSUE THREAD

**Issue by cgfeel** [alibaba/hooks#2169]
我设置缓存1小时，实际不到10分钟就失效了
```
  const { data, loading, run } = useRequest(getArticle, {
    manual: true,
    cacheKey: `setCache-demo=${id}`,
    staleTime: 3600000,
    onBefore: () => console.log(`request start: ${id} - time: ${Date.now()}`)
  });
```

演示代码：
https://codesandbox.io/s/naughty-tristan-ql3grt?file=/App.tsx

如何复现：

1. 打开演示地址，将4个tab分别点开，加载完第一遍并缓存
2. 过10分钟，点开任意tab，缓存失效，重新加载

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/578141/233829909-d83e373a-6c5d-4d1a-89e3-35c4c94f49aa.png">

**Comment by cgfeel** [comment]
根本不需要这么复杂的例子，直接拿官网的demo改一下，缓存1小时，实际不到10分钟，缓存就失效了
```
  const { data, loading } = useRequest(getArticle, {
    cacheKey,
    staleTime: 3600000,
    onBefore: () => console.log("request time: " + Date.now())
  });
```

演示地址：https://codesandbox.io/s/gallant-napier-5k51i0?file=/App.tsx

复现方法：

1. 点开按钮，进行第一次加载并缓存，再点一次按钮收起
2. 每隔5分钟重复点开一次按钮，总会发现缓存失效

ahooks版本：3.7.6
系统：osx
环境：codesandbox

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/578141/233882061-11933360-4e42-488c-8713-b4f343e2055e.png">

**Comment by hchlq** [comment]
原因：staleTime 依赖 cacheData，在默认的 5min 时间被清除后，就会发送请求。

影响：如果不设置 cacheTime，staleTime 默认只有 5 min 缓存，5 min 后就会过期

解决方案：将 cacheTime 设置为 staleTime 一样的时间

**Comment by cgfeel** [comment]
> 原因：staleTime 依赖 cacheData，在默认的 5min 时间被清除后，就会发送请求。
> 
> 影响：如果不设置 cacheTime，staleTime 默认只有 5 min 缓存，5 min 后就会过期
> 
> 解决方案：将 cacheTime 设置为 staleTime 一样的时间

好的，我也不知道为什么要两个参数
 - 设置cacheTime，不设置staleTime，就不缓存
 - 设置staleTime，不设置cacheTime，时间就不对

**Comment by zmm2tysu** [comment]
> 

<img width="706" alt="image" src="https://github.com/alibaba/hooks/assets/20849786/df1cc6f7-35c8-4cce-87a6-7d3ece68cb0a">
我这么设置也没生效啊，不会手动manual: true没法通过这两个参数控制吧

**Comment by hchlq** [comment]
跟 manual 没关系的，可以看看我这个 [例子](https://codesandbox.io/s/gifted-meadow-1oz30r?file=/App.tsx)

![20230531120506_rec_](https://github.com/alibaba/hooks/assets/60802048/255a11a4-8b7d-4bbc-9555-380c1c5768e7)

**Comment by zmm2tysu** [comment]
> 

找到问题了，好像是umi/max里的useRequest有问题，换成ahooks的就好了

**Comment by Deja-vuuu** [comment]
> > 原因：staleTime 依赖 cacheData，在默认的 5min 时间被清除后，就会发送请求。
> > 影响：如果不设置 cacheTime，staleTime 默认只有 5 min 缓存，5 min 后就会过期
> > 解决方案：将 cacheTime 设置为 staleTime 一样的时间
> 
> 好的，我也不知道为什么要两个参数
> 
> * 设置cacheTime，不设置staleTime，就不缓存
> * 设置staleTime，不设置cacheTime，时间就不对

第一次看文档准备用这个  愣是没看懂 staleTime cacheTime 这俩有啥区别  
看上去大多数场景下 staleTime cacheTime 应该是一样的
