### ISSUE TITLE
3.7.6版本 reset、refreshDeps 会被重置为defaultParams[0].current,不符合业务需求

### ISSUE THREAD

**Issue by xiaomoziyi** [alibaba/hooks#2172]
这个版本修复修出bug了。
![image](https://user-images.githubusercontent.com/32298068/233951239-19c24ca5-bc02-4944-857c-fa542a2e3a27.png)

如果reset要充值页码，应该用reset defaultPageSize, 而不是defaultParams，defaultParams是作为初次传参使用的。不然的话，refreshDeps的说明是refreshDeps 变化，会重置 current 到第一页，并重新发起请求。现在这个版本，会把current重置到defaultParams的current. 
希望尽快修复！！！！ @sorrycc

**Comment by hchlq** [comment]
相关 MR： https://github.com/alibaba/hooks/pull/2090

**Comment by hchlq** [comment]
@Ali-ovo

**Comment by Ali-ovo** [comment]
那如果 `defaultParams` 和 `defaultPageSize` 同时存在的话， reset 的时候 pageSize 属性需要以什么为准呢 
还是说这两个有个 `优先级` ？ @hchlq

**Comment by hchlq** [comment]
>个人感觉 defaultParams 中 pageSize 的权重会比 defaultPageSize 的权重高， 如有 defaultParams 你应当这么使用
>defaultParams:{
>    pageSize: xxx
>}
>而不是重复定义 defaultParams 和 defaultPageSize

我赞同这个说法，不要重复定义 pageSize，否则会产生歧义，默认优先级 defaultParams 中高一些

**Comment by hchlq** [comment]
@Ali-ovo 但是要兼容之前的版本，以前的版本是以 defaultPageSize 为准，你这边改的以 defaultParams 为准了，是个 break change，这个在 3.x 版本先不这么改，我先 revert 回去了，后续在 v4 再做调整哈

<img width="589" alt="image" src="https://user-images.githubusercontent.com/60802048/234742427-03322850-ed56-4ce8-ac32-28f92e6d50c6.png">

**Comment by Ali-ovo** [comment]
> @Ali-ovo 但是要兼容之前的版本，以前的版本是以 defaultPageSize 为准，你这边改的以 defaultParams 为准了，是个 break change，这个在 3.x 版本先不怎么改，我先 revert 回去了，后续在 v4 再做调整哈
> 
> <img alt="image" width="589" src="https://user-images.githubusercontent.com/60802048/234742427-03322850-ed56-4ce8-ac32-28f92e6d50c6.png">

好的没问题

**Comment by crazylxr** [comment]
已经修复发新版了，v3.3.7
