### ISSUE TITLE
useFullScreen 页面全屏自动退出

### ISSUE THREAD

**Issue by PiyAnEr** [alibaba/hooks#2184]
在页面全屏的前提下，更改全屏元素的类名，会自动退出全屏，并且不会触发 onExit 方法，isFullScreen 状态也不会改为 false

**Comment by candy4290** [comment]
能否来个复现链接啊？ @PiyAnEr

**Comment by liuyib** [comment]
> 在页面全屏的前提下，更改全屏元素的类名，会自动退出全屏，并且不会触发 onExit 方法，isFullScreen 状态也不会改为 false

目前页面全屏就是通过动态加类名实现的，改了类名样式当然就没了。能说下你具体的使用场景吗？什么情况下必须要改掉类名啊？

**Comment by PiyAnEr** [comment]
> 能否来个复现链接啊？ @PiyAnEr

本

**Comment by PiyAnEr** [comment]
> > 在页面全屏的前提下，更改全屏元素的类名，会自动退出全屏，并且不会触发 onExit 方法，isFullScreen 状态也不会改为 false
> 
> 目前页面全屏就是通过动态加类名实现的，改了类名样式当然就没了。能说下你具体的使用场景吗？什么情况下必须要改掉类名啊？

我知道是通过类名去实现的，我当时遇到的业务场景是，用户在页面全屏的状态下，可能里面的业务操作需要更改外层（也就是全屏元素的样式），我这边就会动态增删元素的类（不是更改实现全屏的类），发现实现全屏的类就会消失。然后我自己也是动态添加类名去实现了一下，没有这样的问题。顺带说一下，这个全屏功能不兼容 ie11  /(ㄒoㄒ)/~~。

**Comment by liuyib** [comment]
> 业务操作需要更改外层（也就是全屏元素的样式），我这边就会动态增删元素的类（不是更改实现全屏的类）

好的，感谢反馈，我后面细看下这点。

> 这个全屏功能不兼容 ie11

对于这点，你有好的兼容思路吗（太 Hack 就算了）？当时开发时确实没考虑 IE

**Comment by liuyib** [comment]
> 我这边就会动态增删元素的类（不是更改实现全屏的类），发现实现全屏的类就会消失

@PiyAnEr  麻烦给个在线 demo 吧，我这边没复现

**Comment by liuyib** [comment]
https://codesandbox.io/s/ahooks-issue-2184-p605kw?file=/App.tsx:359-832

这是我的 demo，没有出现你反馈的问题。麻烦给个能复现你问题的在线 demo？@PiyAnEr

**Comment by PiyAnEr** [comment]
> https://codesandbox.io/s/ahooks-issue-2184-p605kw?file=/App.tsx:359-832
> 
> 
> 
> 这是我的 demo，没有出现你反馈的问题。麻烦给个能复现你问题的在线 demo？@PiyAnEr

我就用你这个稍作修改就复现了
![Uploading 240462068...]()

**Comment by PiyAnEr** [comment]
> Hi, PiyAnEr.
> 
> It seems that this issue is a bit vague and lacks some necessary information. 
> 
> 看起来这条 issue 描述得有些模糊，缺少一些必要的信息。

我就用这个稍微调整就复现了
![image](https://user-images.githubusercontent.com/40418376/240462568-9f353b9b-28fb-448f-b047-6e4a00825339.png)

**Comment by PiyAnEr** [comment]
> https://codesandbox.io/s/ahooks-issue-2184-p605kw?file=/App.tsx:359-832
> 
> 
> 
> 这是我的 demo，没有出现你反馈的问题。麻烦给个能复现你问题的在线 demo？@PiyAnEr

我就用你这个稍作调整就复现了
![image](https://user-images.githubusercontent.com/40418376/240462984-9f0f67a5-b9db-4f84-a32c-f40970477543.png)

**Comment by liuyib** [comment]
> > https://codesandbox.io/s/ahooks-issue-2184-p605kw?file=/App.tsx:359-832
> > 这是我的 demo，没有出现你反馈的问题。麻烦给个能复现你问题的在线 demo？@PiyAnEr
> 
> 我就用你这个稍作调整就复现了 ![image](https://user-images.githubusercontent.com/40418376/240462984-9f0f67a5-b9db-4f84-a32c-f40970477543.png)

你已经完全控制 `className` 这个属性了，然后你更新时赋值了个新的类名，直接把 ahooks 加的类名覆盖掉了，肯定会引起这个问题，控制权都已经被你掌握了，需要用户自己承担掌握控制权带来的影响。

总不能说 ahooks 要一直监听全屏的 DOM，然后不管用户怎么更新样式类名，ahooks 始终都会把自带的类名牢牢地加上去，那这个行为就太诡异了。

几点建议：

1. 用 ref，通过 dom 方法更新样式类名： `ref.current?.classList.add('your-custom-class-name')`
2. 你控制 `className` 后，更新时考虑加上 dom 上原带有的类名：

  ```ts
  const generateNewClassName = (dom: HTMLElement | null, newClassName: string) => {
    if (!dom) return newClassName;
  
    return dom.classList.contains(newClassName) ? dom.className : `${dom.className} ${newClassName}`;
  };
  
  <button
    onClick={() => {
      setName(generateNewClassName(ref.current, 'your-custom-class-name'));
    }}
  >
    click
  </button>
  ```

---

如果有好的意见让 ahooks 来处理这点，可以提出来看看，这个 issue 先关了
