### ISSUE TITLE
defaultParams作为初始值，[{current: 2, pageSize: 5}, formParmas]，reset会重置为2，而不是1；formParams未被调用为表单初始值，在点击搜索时未生效

### ISSUE THREAD

**Issue by xiaomoziyi** [alibaba/hooks#2185]
![image](https://user-images.githubusercontent.com/32298068/236608178-2036910a-8ab9-4958-bc95-878bbabb4365.png)
问题如上图，上次的issuce为被真的解决，故重新提出。示例：https://ahooks.js.org/zh-CN/hooks/use-antd-table#%E5%88%9D%E5%A7%8B%E5%8C%96%E6%95%B0%E6%8D%AE

**Comment by xiaomoziyi** [comment]
`const reset = () => {
    if (form) {
      form.resetFields();
    }
    _submit(
      defaultParams?.[0] || {
        pageSize: options.defaultPageSize || 10,
        current: 1,
      },
    );
  };`  考虑把submit的 defaultParams?.[0]删除。
@sorrycc

**Comment by 1587315093** [comment]
貌似已经修了，我在`3.7.7 `版本看是好的

不过npm包都`3.7.7`了 为啥github的 `release tag` 和官网案例还是 `3.7.6 `的
![image](https://user-images.githubusercontent.com/77056991/237052433-8397cecc-1462-4675-ab05-c2b605906cf4.png)
![image](https://user-images.githubusercontent.com/77056991/237052529-3923fa4e-6706-4697-92e9-f5e0604fadcc.png)
![image](https://user-images.githubusercontent.com/77056991/237052632-b8e1168c-aa7c-4e7b-9b2e-4b3655d87e8b.png)

**Comment by liuyib** [comment]
github releases 慢于 npm 是因为先发的 npm，后面再发的 github releases，目前已更新。文档没及时更新这个我们再看下

**Comment by liuyib** [comment]
v3.7.7 中修好了，官方文档也更新了，issue 关了哈

**Comment by xiaomoziyi** [comment]
收到。
