### ISSUE TITLE
useRequest适用场景问题

### ISSUE THREAD

**Issue by Kevin2cqs** [alibaba/hooks#2188]
（1）useRequest目前只适用于函数式组件、或传统的组件中。无法在ts文件中使用，很多时候开发者会在store中获取数据并保存。
（2）无法解决同一个接口，同时多次请求的问题。例如：一个页面下有多个类似组件，每个组件中都会调用同一个接口，当进入该页面时，多个组件同时加载，这时候useRequest还并未生成缓存，所以会导致浏览器同时间多次请求同一个接口。

**Comment by abearxiong** [comment]
仅仅讨论的说：我感觉第一个问题：useRequset是hooks不是函数，本身目的就在函数里面写的，他对应的返回值loading，error，run什么，refresh不需要在store里面再存一遍。如果你要useRequet被store封装，那么对应的
```
const store = {
  query: () {
    return useRequest(this.services, this.options)
  }
}
```
然后query等同于hooks，然后在函数组建里面调用这个hooks（函数）就行了。


然后第二个问题，同一个接口多次请求，你的这个组件请求数据为啥不放到顶层，每一个接口做自己的事情，你多个请求肯定要发多次呗。肯定不是useRequset的问题
