### ISSUE TITLE
useReactive 通过 context 使用，无法触发视图更新

### ISSUE THREAD

**Issue by liuyib** [alibaba/hooks#2189]
复现 demo：https://codesandbox.io/s/ahooks-issue-2189-zs97r8?file=/App.tsx

**Comment by kongmoumou** [comment]
可以这样，防止 value 引用不变 bailout，但感觉在 react 中追求 mutable 还是怪怪的 😂

```diff
- <Context.Provider value={state}>
+ <Context.Provider value={{ state }}>
    {children}
  </Context.Provider>;
```

**Comment by liuyib** [comment]
> 感觉在 react 中追求 mutable 还是怪怪的

群里小伙伴反馈的，有人喜欢这样用 😂，可能更方便吧

**Comment by liuyib** [comment]
感觉这个问题让 useReactive 本身来解决有点麻烦，甚至解决不了。除了 context，还可能配合状态库（Mobx, Redux 等）用，都可能出问题吧。我后面再研究下，不好解决的话，就加个 FAQ，声明下这些使用场景。

**Comment by liuyib** [comment]
> ```diff
> - <Context.Provider value={state}>
> + <Context.Provider value={{ state }}>
>     {children}
>   </Context.Provider>
> ```

@yunsii 先这样用，可以解决你的问题。useReactive 本身貌似不太好处理

**Comment by yunsii** [comment]
> > ```diff
> > - <Context.Provider value={state}>
> > + <Context.Provider value={{ state }}>
> >     {children}
> >   </Context.Provider>
> > ```
> 
> @yunsii 先这样用，可以解决你的问题。useReactive 本身貌似不太好处理

好想法，那就先这么搞了

**Comment by yunsii** [comment]
https://codesandbox.io/s/throbbing-hooks-6lmspc?file=/App.tsx

又发现了问题，如果按这个逻辑放 shadow dom 里结合 useClickAway 还是有问题，佛了 😂

**Comment by yunsii** [comment]
很奇怪，在我的场景下，这种方式还是不是很稳定，有空再研究下怎么复现了，还是先用 useSetState 了

**Comment by liuyib** [comment]
> 在我的场景下，这种方式还是不是很稳定，有空再研究下怎么复现了

issue 我先关了，等你排查出通用的复现场景了辛苦再反馈下 ❤️

**Comment by lovelyJason** [comment]
我也遇到这个问题了， 我是context + useReactive结合使用。在proivder组件中userReactive后， 将生成的state上的某个属性传入provider中， 
```tsx
  const state = useReactive<any>({
    list: [{key1: 'any', key2: 'any'}]
  })

<Context.Provider value={{ list}} >
<Context.Provider/>
```

后代组件中通过直接操作ctx.list.push(...). 这个list其实是被改变了的，但是后代组件中依赖于这个list的UI没有得到更新，就是一个依赖于list的antd table

但是当我在provider的根组件中state.push(...)，根组件中依赖于list的UI是得到更新的
```tsx
{ JSON.stringify(state.deductionDeclareDetail) }
```

我想得到答案是什么原理
