### ISSUE TITLE
使用Taro开发支付宝小程序，无法使用ahooks

### ISSUE THREAD

**Issue by wuxu1230** [alibaba/hooks#2192]
使用Taro开发**支付宝小程序**，使用useRequest中会使用Date.now()，然而代码中是先获取root，然后使用root.Date.now()，导致报错，因为支付宝小程序中 root = {} 就是一个空对象，希望早日解决
![image](https://github.com/alibaba/hooks/assets/46241389/d9a592f1-d0cc-4edc-bf5a-6b083eacb46b)

**Comment by liuyib** [comment]
Related PR: https://github.com/alibaba/hooks/pull/1472
