### ISSUE TITLE
useLocalStorageState 在版本3.7.6和3.7.7中的ts提示不一致了

### ISSUE THREAD

**Issue by tangzijun** [alibaba/hooks#2197]
useLocalStorageState 在版本3.7.6和3.7.7中的ts提示不一致了，在3.7.7中value会undefined

![image](https://github.com/alibaba/hooks/assets/11813048/a5d29ded-6ce6-4ecd-ae44-d7e304a8f79a)

**Comment by liuyib** [comment]
这个问题的原因是：3.7.6 之前的版本中 `useLocalStorageState` 的类型没有完善好，导致代码和文档的 ts 类型不一致。文档中是有写明这个返回值可能为 `undefined` 的：

![image](https://github.com/alibaba/hooks/assets/38221479/5d5a2e27-fa10-4105-9546-cc226b0326c3)

应该按照文档的来，我们会对文档负责。

另外，抛开 ahooks 不谈，localStorage 数据是可能被清空的，业务代码中应该做判空。
