### ISSUE TITLE
useInterval 的 delay 是不是叫null 更合适？

### ISSUE THREAD

**Issue by 1587315093** [alibaba/hooks#2201]
两个语义不同 而null一般与定时器之类的清除定时器相关   而undefind可以被重写
![image](https://github.com/alibaba/hooks/assets/77056991/212b9bc6-bb62-4168-a201-12a7983a90f4)

**Comment by liuyib** [comment]
> null一般与定时器之类的清除定时器相关

这句话的依据是？

<img width="853" alt="image" src="https://github.com/alibaba/hooks/assets/38221479/b2f422f8-d737-4ec6-9205-6800255cc2ec">

**Comment by liuyib** [comment]
> undefind可以被重写

undefined 是可以被重写，如果真被重写了，恐怕不止是 ahooks 用不了，整个项目都可能出问题吧

**Comment by 1587315093** [comment]
> > null一般与定时器之类的清除定时器相关
> 
> 这句话的依据是？
> 
> <img alt="image" width="853" src="https://user-images.githubusercontent.com/38221479/240947143-b2f422f8-d737-4ec6-9205-6800255cc2ec.png">
因为平时 用setInterval  会 let 个 null 变量的关系，可能此处的undefind 就是想表示未定义吧，只是个疑问~

**Comment by liuyib** [comment]
> 因为平时 用setInterval 会 let 个 null 变量的关系，可能此处的undefind 就是想表示未定义吧，只是个疑问~

好的，这是个人习惯哈~，用定时器也可以 let 个undefined（或其他值）的初始变量。这个 issue 就关了哈~
