### ISSUE TITLE
useLocalStorageState 在版本3.7.7中的ts提示问题，与3.7.6不一致

### ISSUE THREAD

**Issue by tangzijun** [alibaba/hooks#2202]
3.7.7
![image](https://github.com/alibaba/hooks/assets/11813048/aec664a5-0992-4e11-a945-51eccd322e28)

3.7.6
![image](https://github.com/alibaba/hooks/assets/11813048/54032201-858d-49c4-b244-4f405314b54c)

认为3.7.6是正确的

**Comment by 1587315093** [comment]
3.7.7 应该正确的  从 storage 获取数据没有这个数据的话 ， 返回值当然可能为 undefined 
文档也说明可以额 setState(undefined)  这样就会兼容传递进来的泛型与 undefined 类型做出改变
![image](https://github.com/alibaba/hooks/assets/77056991/854f2d4f-d8c7-4f38-bd88-3b2b55cc7816)
![image](https://github.com/alibaba/hooks/assets/77056991/ab38f58c-581e-46c5-b30f-5a2d3cf03512)

**Comment by hchlq** [comment]
1 楼回答是对的
