### ISSUE TITLE
useInfiniteScroll 合并数据的时候，若后端返回的数据结构是 { list: null, ...rest } 类型，这里会抛出error，是否考虑catch一下

### ISSUE THREAD

**Issue by witcsmartian** [alibaba/hooks#2203]
https://github.com/alibaba/hooks/blob/a80979e100779148fbc159232f87577a4a2be59f/packages/hooks/src/useInfiniteScroll/index.tsx#L43

**Comment by liuyib** [comment]
@hchlq 看下呢

**Comment by hchlq** [comment]
一般来说需要业务自己去控制，但是为了更健壮，需要考虑的，需要加个判断哈
