### ISSUE TITLE
useInfiniteScroll 绑定的DOM元素，在display由none转化为block时，scrollHeight不准确，导出出现冗余请求

### ISSUE THREAD

**Issue by MeetzhDing** [alibaba/hooks#2204]
我在Popup中维护着一个 滚动加载更多的列表。这个 Popup 在隐藏时DOM不会被销毁，仅仅是将display 设置为了 none。

如果在Popup中，提前对列表内容进行微小的滚动，让元素的 scrollTop 值变为非0，再将Popup关闭，此时不会触发滚动事件。

再打开Popup, 进行显示的瞬间，由于元素还没有能够完全展示，此时元素的 scrollHeight 等同于 clientHeight，且scrollTop会被重设为0，导致单次的滚动行为。
导致计算等式 scrollHeight - scrollTop <= clientHeight + threshold 为 true

<img width="1318" alt="image" src="https://github.com/alibaba/hooks/assets/12808432/c690aba5-c78c-485f-a64b-ec3f2b3d8d9b">

---
对于display none-> block，且原本的 scollTop不为0 的这种情况，能够考虑使用 ResizeObserver 类的工具来进行监测？防止这种情况下的请求

或者还有一种方式，就是提供一种 mute 能力，允许外部传入让整个加载更多的功能先暂停住，这样外部可以通过一个微小的延迟，或者自定义一个监听器来实现类似的目的

**Comment by liuyib** [comment]
@hchlq  有空看下呢

**Comment by hchlq** [comment]
看描述好像更多是业务侧这边的问题呢，Popup 关闭时让元素销毁或者滚动回到顶部不就行了么，再打开时就不会使用缓存的滚动距离。而不是通过提供的那两个方案去 hack 解决~

**Comment by hchlq** [comment]
业务做调整，先不考虑这两个方案做调整哈
