### ISSUE TITLE
[useDynamicList]优化提议

### ISSUE THREAD

**Issue by xielin9527** [alibaba/hooks#2207]
能否给useDynamicList添加一个可选的onChange方法,在内部调用setList时调用onChange,
以避免出现像demo2利用useEffect更新state的情况,
我感觉这不是一个好的做法,而且会导致antd form.isFieldTouched()方法在用户尚未操作的情况下返回true
![image](https://github.com/alibaba/hooks/assets/70584642/ecf9a1ef-843c-41be-91d9-cc5fd1f9db40)

**Comment by liuyib** [comment]
@hchlq 程哥，有时间看下哈

**Comment by hchlq** [comment]
没太理解后面这句话指的具体是哪个问题? 和这个有啥关系呢

> 我感觉这不是一个好的做法,而且会导致antd form.isFieldTouched()方法在用户尚未操作的情况下返回true

**Comment by candy4290** [comment]
> 没太理解后面这句话指的具体是哪个问题? 和这个有啥关系呢
> 
> > 我感觉这不是一个好的做法,而且会导致antd form.isFieldTouched()方法在用户尚未操作的情况下返回true

感觉他的意思是，示例2中，这样写法，导致初始化“自定义表单项”值的时候就触发了表单项的onchange，从而导致了form.isFieldTouched(‘自定义表单项name’)为true。
其实和useDynamicList无关。只需要将demo2下图中useEffect改为使用useUpdateEffect，应该可以解决他的问题
![image](https://github.com/alibaba/hooks/assets/19907991/a38a724c-c569-4192-9f6b-11221d5cddbf)

就像这样： https://codesandbox.io/s/zai-antd-form-zhong-shi-yong-forked-hwdptq?file=/App.tsx:2099-2163

**Comment by xielin9527** [comment]
https://codesandbox.io/s/zai-antd-form-zhong-shi-yong-forked-9uq8w4?file=/App.tsx
可以看下这个示例,因为利用useEffect触发onChange,导致form在初始化的时候触发了onValuesChange,以及form.isFieldTouched()会返回true,
我觉得代码内的逻辑不应该触发onValuesChange,这个方法应该是由用户的手动操作才触发

**Comment by xielin9527** [comment]
我就是觉得更新state不该在useEffect里面,而是用户操作时手动调用onChange

**Comment by candy4290** [comment]
> 我就是觉得更新state不该在useEffect里面,而是用户操作时手动调用onChange
试试这样是否满足你的想法呢？
https://codesandbox.io/s/zai-antd-form-zhong-shi-yong-forked-9uq8w4?file=/App.tsx

**Comment by hchlq** [comment]
我理解你意思了

**Comment by hchlq** [comment]
@xielin9527 你这边先自己处理下吧，在操作的时候再调用 onChange，这个后续可以作为一个 feture

**Comment by xielin9527** [comment]
好的
