### ISSUE TITLE
useReactive结合context， 后代组件调用数组push方法，UI没有得到更新

### ISSUE THREAD

**Issue by lovelyJason** [alibaba/hooks#2215]
我是context + useReactive结合使用。在proivder组件中userReactive后， 将生成的state上的某个属性传入provider中， 
```tsx
  const state = useReactive<any>({
    list: [{key1: 'any', key2: 'any'}]
  })

<Context.Provider value={{ list}} >
<Context.Provider/>
```

文档上不是支持数组push的吗
后代组件中通过直接操作ctx.list.push(...). 这个list其实是被改变了的，但是后代组件中依赖于这个list的UI没有得到更新，就是一个依赖于list的antd table
```jsx
                <Table
                  className={styles['table-container']}
                  bordered
                  pagination={false}
                  columns={columns}
                  scroll={{ x: '100%', scrollToFirstRowOnChange: true }}
                  dataSource={ctx.list}
                />
```
但是当我在provider的根组件中state.list.push(...)，或者在后代组件中state.list.push(...),
根组件中依赖于list的UI是得到更新的,只是后代组件依赖于list的视图没有更新
```tsx
{ JSON.stringify(state.deductionDeclareDetail) }
```

我想得到答案是什么原理

我的想法是：
不同于Vue的设计理念， 在Vue2当中可以给子组件传递引用类型的props， 子组件的修改可以同步到父组件，而不必要传递一个修改值的回调函数。尽管这么做控制台会报一些警告， 但是尤大好像说过这种方式也是可以的。Vue3中就不知道能不能这么干了，传一个引用类型数据，被子组件修改

而在React中，其实都是推荐的单向数据流。貌似useReactive对state的直接赋值触发视图更新是不是只限制在当前组件？后代组件不生效。难道是要给后代组件传递setState的方法得到修改么？刚写react hooks不久

**Comment by liuyib** [comment]
related issue: https://github.com/alibaba/hooks/issues/2189

**Comment by liuyib** [comment]
> 后代组件中通过直接操作ctx.list.push(...). 这个list其实是被改变了的，但是后代组件中依赖于这个list的UI没有得到更新

在你 `ctx.list.push(...)` 这个操作的后代组件中，加上如下代码：

```tsx
import { useUpdate } from 'ahooks';

// ... 省略了你的代码
const update = useUpdate();
// ... 省略了你的代码

// ... 省略了你的代码
ctx.list.push(...)
update();
// ... 省略了你的代码
```

试试这样是不是可以解决你的问题 @lovelyJason

**Comment by lovelyJason** [comment]
> > 后代组件中通过直接操作ctx.list.push(...). 这个list其实是被改变了的，但是后代组件中依赖于这个list的UI没有得到更新
> 
> 在你 `ctx.list.push(...)` 这个操作的后代组件中，加上如下代码：
> 
> ```tsx
> import { useUpdate } from 'ahooks';
> 
> // ... 省略了你的代码
> const update = useUpdate();
> // ... 省略了你的代码
> 
> // ... 省略了你的代码
> ctx.list.push(...)
> update();
> // ... 省略了你的代码
> ```
> 
> 试试这样是不是可以解决你的问题 @lovelyJason



> 

其实我一开始的代码，list不在根属性上，是有嵌套的，嵌套了两层以以上，为了方便演示，我写了个伪代码。我现在改了下嵌套层级， 把list放在根属性上， 在任意组件调用list的push方法都没这个问题了， 视图更新了

晚点我在写个在线示例看看

**Comment by liuyib** [comment]
> 晚点我在写个在线示例看看

可以的，把之前你有问题的代码写个在线示例看看吧，看文字描述不太好确定具体代码。

**Comment by lovelyJason** [comment]
> > 晚点我在写个在线示例看看
> 
> 可以的，把之前你有问题的代码写个在线示例看看吧，看文字描述不太好确定具体代码。

[https://codesandbox.io/s/little-tree-rl5hyr?file=/src/App.tsx](https://codesandbox.io/s/little-tree-rl5hyr?file=/src/App.tsx)

我现在好像没发现什么问题， 不知道之前是怎么弄的

不过我发现写完这个示例以后， 觉得useReactive好强大哈哈。 双向绑定
