### ISSUE TITLE
[QUESTION] useSelections 如何支持跨页(保留选择)选择

### ISSUE THREAD

**Issue by xmsz** [alibaba/hooks#2217]
背景
- 有个分页列表
- 用户选择了一页的内容
- 用户想要选择跨页，比如第二页的内容

现在
- 一但切换到第二页useSelections，状态就不知道如何保留了

**Comment by liuyib** [comment]
我建议自己存下状态，把第一页选择的内容存起来，用户翻到其他页后，再把其他页选择的内容存起来，以此类推。当你想使用所有选择的内容时，把这些数据依次拼接起来就好了。这样能解决你的问题吗？ @xmsz

**Comment by liuyib** [comment]
看错 hook 了，刚才的回答删了

**Comment by liuyib** [comment]
![image](https://github.com/alibaba/hooks/assets/38221479/c16b58e7-2d4a-4e66-bfd3-b978ce5eea4c)

这样处理能满足你的需求吗？ @xmsz

**Comment by xmsz** [comment]
> ![image](https://user-images.githubusercontent.com/38221479/245085864-c16b58e7-2d4a-4e66-bfd3-b978ce5eea4c.png)
> 
> 这样处理能满足你的需求吗？ @xmsz

应该可以 我先试试

**Comment by liuyib** [comment]
> 应该可以 我先试试

怎么样呢？

**Comment by LiHaoGit** [comment]
目前是支持跨页选中的 https://stackblitz.com/edit/vitejs-vite-up54tt?file=src%2FApp.jsx
