### ISSUE TITLE
lodash-es 代替 lodash

### ISSUE THREAD

**Issue by The-End-Hero** [alibaba/hooks#2220]
rt

**Comment by crazylxr** [comment]
有什么参考文档么，为什么要用 lodash-es 来代替

**Comment by The-End-Hero** [comment]
> 有什么参考文档么，为什么要用 lodash-es 来代替

https://juejin.cn/s/lodash-es%20vs%20lodash

**Comment by liuyib** [comment]
@The-End-Hero 
<img width="1067" alt="image" src="https://github.com/alibaba/hooks/assets/38221479/386c72c2-9223-430e-a5d8-78fb6e84761c">

ahooks 代码里使用 lodash 都是这样用的：

```ts
import xxx from 'lodash/xxx';
```

等价于

```tsx
import { xxx } from 'lodash-es';
```

不会额外增大包体积。

见你提供的参考资料中也提到，用了打包工具两者是都可以的。只不过用 lodash-es 后导入时语法会简单些。

目前这个包的替换不是特别急迫的事，不换也没任何影响（只是开发时导入语法繁琐了点）

**Comment by liuyib** [comment]
不过我觉着可以来个 PR 优化下？应该替换下依赖和语法就可以 @The-End-Hero

**Comment by Ali-ovo** [comment]
我来吧

**Comment by fc1904** [comment]
项目的package使用了ahooks，rollup打包的时候报错.....
```
  error        Error: 'default' is not exported by ../node_modules/lodash/debounce.js, imported by ../node 
_modules/ahooks/es/useRequest/src/plugins/useDebouncePlugin.js
```
下一版啥时更啊...

**Comment by sxy-git** [comment]
![image](https://github.com/alibaba/hooks/assets/105066043/de688c46-2ed2-42eb-977b-fdb33acce70a)   build error
