### ISSUE TITLE
感觉ahooks可以把信号量整合进来，类似于@preact/signal中的几个方法

### ISSUE THREAD

**Issue by 1075488066** [alibaba/hooks#2221]
[@preact/signal](https://www.npmjs.com/package/@preact/signals-react)
[signal](https://github.com/preactjs/signals)

```javascript
import { useSignal, useComputed } from "@preact/signals-react";

function Counter() {
	const count = useSignal(0);
	const double = useComputed(() => count.value * 2);

	return (
		<button onClick={() => count.value++}>
			Value: {count.value}, value x 2 = {double.value}
		</button>
	);
}

```

**Comment by liuyib** [comment]
你是希望 preact 的 signal, signal.peek, computed, effect, batch 这些 hook 都整合进来？还是只整合某几个 hook？但是我看除了 useSignal 在 react 中都有与之对应的 hook 了呀。

想要使用与 useSignal 相同能力的 hook，可以使用 ahooks 的 useReactive，用法一致的。

有其他更好的整合进来的建议吗？感觉和 react 原生提供的 hook 能力都重复了 @1075488066

**Comment by 1075488066** [comment]
> 你是希望 preact 的 signal, signal.peek, computed, effect, batch 这些 hook 都整合进来？还是只整合某几个 hook？但是我看除了 useSignal 在 react 中都有与之对应的 hook 了呀。
> 
> 想要使用与 useSignal 相同能力的 hook，可以使用 ahooks 的 useReactive，用法一致的。
> 
> 有其他更好的整合进来的建议吗？感觉和 react 原生提供的 hook 能力都重复了 @1075488066 

只要和effect和peek也行，就是在使用watch功能时，不用自己添加依赖，还能控制那些依赖需要收集那些不需要。

**Comment by 1075488066** [comment]
主要是希望在写watch功能时不用自己手动添加依赖。

**Comment by liuyib** [comment]
> 主要是希望在写watch功能时不用自己手动添加依赖。

这个能力要寄希望于 react 官方来实现了，ahooks 作为一个 hook 库，实现不了

---

另外，把 useEffect 当成 watch 来用，不是特别好的 react 编码实践，不太推荐。

可以参考官方的文档：[You Might Not Need an Effect](https://react.dev/learn/you-might-not-need-an-effect) 把滥用 useEffect 的地方优化掉，然后你会发现，自己几乎不会再被什么 watch 不 watch 的心智负担所缠绕。
