### ISSUE TITLE
官网useWebSocket文档页示例接口错误

### ISSUE THREAD

**Issue by CNFeffery** [alibaba/hooks#2222]
文档中有关`useWebSocket`的页面（ https://ahooks.js.org/hooks/use-web-socket/ ），示例websocket接口失效：

![image](https://github.com/alibaba/hooks/assets/49147660/34b3c3f8-a3d5-475e-8cc6-c5cdb98657a2)

**Comment by liuyib** [comment]
已经在修了：https://github.com/alibaba/hooks/pull/2209

**Comment by CNFeffery** [comment]
@liuyib 接口失效了
![image](https://github.com/alibaba/hooks/assets/49147660/0c61ad61-b45d-46ed-a46d-2fa614bf4050)

**Comment by liuyib** [comment]
代码合入了，官网文档还没更新
