### ISSUE TITLE
useTextSelection 选中文本后，鼠标右键后选中的内容发生了变化

### ISSUE THREAD

**Issue by zhuhongyan** [alibaba/hooks#2223]
![image](https://github.com/alibaba/hooks/assets/20653605/37818ccc-e8ec-4da3-a8ce-075f644ac08a)
![image](https://github.com/alibaba/hooks/assets/20653605/8857b107-5d09-4dec-8c22-7d5091fae2db)
看其他的划词工具都不会这样

**Comment by Ali-ovo** [comment]
我来尝试修复一下吧
