### ISSUE TITLE
useAntdTable 返回的数据,可不可以先缓存一次?

### ISSUE THREAD

**Issue by xxi-arch** [alibaba/hooks#223]
第一次打开表格的时候  loading 一会从服务器加载  然后退出这个页面, 第二次打开表格的时候 显示上一次的数据   同时也会触发ajax的更新数据    这时候如果有新数据就重新渲染页面 没有就不渲染

**Comment by brickspert** [comment]
这个能力正在支持哦。可以尝鲜看看：https://github.com/umijs/use-api

目前正在集成到 umi hooks 进程中。

**Comment by brickspert** [comment]
v1.6.0 可以使用这个功能了。
