### ISSUE TITLE
useInfiniteScroll 加载第二页，返回的数据 是 二维数组，不再是一维数组了

### ISSUE THREAD

**Issue by Milk-Daisy** [alibaba/hooks#2234]
![image](https://github.com/alibaba/hooks/assets/136062551/c833717a-a5ec-45a5-b8d1-679194123f4e)
这是致命更改，我看官网也没有说这个功能的改动

**Comment by liuyib** [comment]
麻烦提供个来个可复现的在线 demo @Milk-Daisy

**Comment by hchlq** [comment]
useInfiniteScroll 最近没有破坏性更新，感觉应该是业务侧数据处理问题呢？

**Comment by hchlq** [comment]
官网的 demo 例子可以参考下，是没有问题的
