### ISSUE TITLE
useInfiniteScroll在遇到错误时能否停止滚动监听 

### ISSUE THREAD

**Issue by jc840031139** [alibaba/hooks#2235]
useInfiniteScroll在遇到错误时 我想让用户手动点击重试 但是现在reject之后 还是可以反复滚动

**Comment by hchlq** [comment]
建议通过其他方式去做避免哈。可以手动 loadMore 去手动的触发滚动加载，不通过无限滚动的方式

**Comment by xuqingkuang** [comment]
我碰到一样的问题了，但通过把 target 的 ref 置空暂时解决了。
