### ISSUE TITLE
useDebounceFn会丢失事件对象

### ISSUE THREAD

**Issue by ecnatsiDehTog** [alibaba/hooks#2245]
看生产环境编译后的代码，里面应该是包了setTimeout，在里面访问不到事件对象的属性

**Comment by ecnatsiDehTog** [comment]
<img width="1366" alt="image" src="https://github.com/alibaba/hooks/assets/48802425/80740c0a-84f4-4003-9dc7-f9a47acccec0">

**Comment by hchlq** [comment]
我试了下是可以的。可以看下这个 demo。

https://codesandbox.io/s/ji-chu-yong-fa-forked-2jntjc?file=/App.tsx
