### ISSUE TITLE
useRequest cacheKey改变后失去数据共享特性

### ISSUE THREAD

**Issue by h1260711589** [alibaba/hooks#2256]
<img width="820" alt="image" src="https://github.com/alibaba/hooks/assets/50660278/134e10c4-6894-4d2b-8e11-01cadd21a8fb">

在把两个article的key都更改到1后，他们不再保持数据同步共享变化了，这是符合预期的吗

**Comment by hchlq** [comment]
麻烦给个在线的 demo 看看哈

**Comment by hchlq** [comment]
符合预期的。改之前，两个组件都是共享同一个 key，点击更新，你只更新了一个组件的 key，另外一个组件还是用的之前的 key，因此不共享了

**Comment by h1260711589** [comment]
@hchlq  我两个组件都更新了呀，原来两个组件的key都是0，我两个都更新到1之后，他们也不共享

**Comment by hchlq** [comment]
我这边都是可以共享的，不知道你是怎么操作的呢

https://codesandbox.io/s/stupefied-leaf-dr4nv9?file=/App.tsx

**Comment by hchlq** [comment]
![20230718115541_rec_](https://github.com/alibaba/hooks/assets/60802048/b2ddc911-e436-4e6f-9574-34ee49465e8d)

**Comment by h1260711589** [comment]
@hchlq 就用你给的代码，一开始直接点两次更新key把两个组件的key都更新到1，然后点第一个组件的更新去更新文章内容，第二个组件的文章内容没有同步发生变化

**Comment by hchlq** [comment]
同时点击的情况，第一次点击更新后可能状态没同步，后续第二次就可以了。

一般也不会这么每个组件单独维护 cacheKey，最佳实践是抽取为公用的。

**Comment by h1260711589** [comment]
![userequest](https://github.com/alibaba/hooks/assets/50660278/9b6407a5-53e4-4cc7-a529-5ebf529b3fc9)

@hchlq 第二次后续也不行吧。。我看源码里似乎订阅key改变是在useCreation里，这个只会在一开始订阅一次初始的key，为什么不在每次key变化时重新订阅呢
