### ISSUE TITLE
useMemoizedFn中的 this 参数

### ISSUE THREAD

**Issue by wuxinhao02** [alibaba/hooks#2257]
```ts
if (!memoizedFn.current) {
    memoizedFn.current = function (this, ...args) {
      return fnRef.current.apply(this, args);
    };
  }
```
不太理解这段 `function (this, ...args) {}` 代码中 this 参数的用意，直接用 apply 不是已经可以传递 this 了吗，且一般情况下不是会出现 `Uncaught SyntaxError: Unexpected token 'this'` 的错误吗？求大佬解惑。
https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useMemoizedFn/index.ts

**Comment by liuyib** [comment]
> 不太理解这段 function (this, ...args) {} 代码中 this 参数的用意

这里是 TS 特有的一个处理逻辑，允许在函数参数中显示声明 this 的类型（JS 中不允许），参考资料：
https://www.typescriptlang.org/docs/handbook/2/functions.html#declaring-this-in-a-function

编译成 JS 后，这个 this 就没了，见：
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCy6QQDQoYBK6AZnAL5ylQQhwDkU6AhgMYwMDcAsAFD8YATzDo4AOwgQwcALxwAFDAAWwVAC44LcUIIA6AyygBzDVp0BtALoBKOQD5zQ3gL6lk4jsAjjCWHBDAAF7oACYAYuIAPAAqcOgAHjDo4qGoElJg9gqk4poxdgj8cHBsPqjwuSTk8mjo1bHZuTYuxXAA9O1wAO7KQhnw3VDAyXAABlVkemzIUMzi8PK5YwD8bZ1wyjAwYBqdxiPKyABG03TtLAA2wMcst+3KUgDWqO1qqMjorwDsAEwAHG1JqRprN5os-NhcAoFHZZI5cgQLLlbK0+CUyuIKnAQAFgmFInI-A0YtkWm1gOQFABCXG4fERcSguYpGCFNolOmBEKM5ngonuTwwby+JSqVD6QwmVDs9EleXMGCzXzAvmsvQsMBgS5CMVqAhGUzkuUlKgsdIxFym-htRXKnF4nmRNULFwUG18RKQWBwUJkFjIS7wOpQ7kE8RcIA
