### ISSUE TITLE
[BUG] `useVirtualList` When the originalList of useVirtualList is an empty array, it will cause the `Maximum update depth exceeded`

### ISSUE THREAD

**Issue by Woodii1998** [alibaba/hooks#2259]
<img width="1676" alt="image" src="https://github.com/alibaba/hooks/assets/33593572/6ca51667-ab2b-4d65-981f-b4c5a92b7410">

**Comment by Woodii1998** [comment]
This problem can be easily and consistently reproduced, I'd love to give you an example with codesandbox but when reproduced codesandbox crashes very quickly 😅

**Comment by hchlq** [comment]
Thank you for your feedback !
