### ISSUE TITLE
useAntdTable中tableProps中的内置的current 可以外部进行修改吗?

### ISSUE THREAD

**Issue by Linyccc** [alibaba/hooks#226]
场景：选择表格最后一页的所有信息进行删除，调refresh发现current还是请求原来的，现实场景应该是current-1 。
我尝试将tableProps里的pagination进行手动赋值，但是发现并不能改变current的值

**Comment by Linyccc** [comment]
我尝试将tableProps里的pagination进行手动赋值，但是发现并不能改变current的值。

**Comment by AlanCutFlim** [comment]
Hello，请问这个问题你解决了吗，求提供下思路，谢谢！

**Comment by wanliyunyan** [comment]
同问，这个问题，怎么解决？
