### ISSUE TITLE
下拉刷新为什么不把错误的状态暴露出来

### ISSUE THREAD

**Issue by 1075488066** [alibaba/hooks#2264]
第一次加载和加载更多的时候也有可能出错吧。

**Comment by crazylxr** [comment]
> 第一次加载和加载更多的时候也有可能出错吧。

你说的是 useInfiniteScroll 吗？

**Comment by 1075488066** [comment]
> > 第一次加载和加载更多的时候也有可能出错吧。
> 
> 你说的是 useInfiniteScroll 吗？

是的

**Comment by hchlq** [comment]
具体是什么错误呢？一般来说只有请求时错误，可以通过传入 onError 去处理

**Comment by 1075488066** [comment]
首次加载时错误，下拉加载更多时出错。很多app中这两种出错显示的效果都不一样吧。

**Comment by hchlq** [comment]
指的是请求错误还是渲染错误？

**Comment by hchlq** [comment]
麻烦给个在线 demo 看看哈

**Comment by 1075488066** [comment]
> 指的是请求错误还是渲染错误？

请求错误

**Comment by hchlq** [comment]
通过 onError 捕获不就行了吗

**Comment by 1075488066** [comment]
> 通过 onError 捕获不就行了吗
捕获不是还要自己处理吗，请求前还要自己清空。

**Comment by 1075488066** [comment]
> 通过 onError 捕获不就行了吗

捕获不是还要自己处理吗，请求前还要自己清空。我是说把错误当状态使用。

**Comment by hchlq** [comment]
就是说你的预期是要获取这些错误是吧，这个可以加上的，我补一下

```ts
const { error, ...} = useInfiniteScroll(service, {
  ...
});

```

**Comment by 1075488066** [comment]
> 就是说你的预期是要获取这些错误是吧，这个可以加上的，我补一下
> 
> ```ts
> const { error, ...} = useInfiniteScroll(service, {
>   ...
> });
> 
> ```

error和errorMore

**Comment by hchlq** [comment]
errorMore 是啥？

预期只加上 error，每次下拉请求都会生成一份（如果有错误）

**Comment by 1075488066** [comment]
> errorMore 是啥？

加载更多时出错，和loading和loadingMore对应。

**Comment by hchlq** [comment]
loading 和 loadingMore 是一个加载状态，error 不会区分这些，认为也没有太大必要，业务自行处理。
