### ISSUE TITLE
useRequest 为什么不在options中，加一个formatParams 方法呢？

### ISSUE THREAD

**Issue by rhydian0x** [alibaba/hooks#2267]
在请求发起前，希望能够对params做格式化等处理，这个formatParams处理结果并不影响到state.params的值。

state.params可能会被组件内部继续消费，和真正的与后端接收的参数可能依旧会有些差异。

**Comment by hchlq** [comment]
在传入的时候预先格式化不满足你的使用场景吗？

**Comment by rhydian0x** [comment]
@hchlq 
因为传入后就同步改变了state中的params, 如果提前格式化了，那么我就无法直接消费state.params数据，这样我需要维护两个params。相反如果我service请求时，有个formatParams回掉，我觉得更方便。

**Comment by cheungww** [comment]
我也遇到了这样的场景，在实际发起请求前，需要先 formatParams，如果 options 提供这个方法，感觉会方便很多

**Comment by crazylxr** [comment]
```javascsript
useReuqest((params) => {
   const _p = 处理(params)
   return  接口调用(_p)
}  )
```

建议的方式这样写，formatParams，formatResult 都很方便。
