### ISSUE TITLE
useLockFn输出不符合ahooks输出函数地址不变的规范

### ISSUE THREAD

**Issue by wpy2015** [alibaba/hooks#2269]
useLockFn中的输出使用useCallback包裹，能否换成useMemoizedFn?  ahooks设计规范 ：所有的输出函数，地址都是不会变化的。如果是useCallback，那么当入参fn改变，输出函数地址也会变。为什么不用useMemoized呢？是有其他的考量吗？

**Comment by liuyib** [comment]
> useLockFn中的输出使用useCallback包裹，能否换成useMemoizedFn? ahooks设计规范 ：所有的输出函数，地址都是不会变化的。如果是useCallback，那么当入参fn改变，输出函数地址也会变。为什么不用useMemoized呢？是有其他的考量吗？

来个 PR 优化下~

**Comment by wpy2015** [comment]
我懂了！

**Comment by liuyib** [comment]
这个函数比较特殊，输出函数不应该保持引用不变，具体见：https://github.com/alibaba/hooks/pull/2270#issuecomment-1658762166
