### ISSUE TITLE
useSelections的使用

### ISSUE THREAD

**Issue by ysl-ccc** [alibaba/hooks#2271]
useSelections只能绑定一个checkbox框，如果使用的全选框是多个的，每一个全选框管理自己的一部分内容，互相之间独立。并且全选框的个数不固定，它的个数从后台来。

**Comment by ysl-ccc** [comment]
相当于`
allSelected
`为数组，`allSelected[index]`，表明第index个的checkbox是否被全选

**Comment by liuyib** [comment]
> useSelections只能绑定一个checkbox框

文档里有 demo 绑定多个 checkbox 框。所以你这里应该没描述清楚，最好给出代码：目前怎样，期望怎样

**Comment by liuyib** [comment]
上代码吧，纯文本描述没太搞明白怎么用的 ~

**Comment by ysl-ccc** [comment]
https://codesandbox.io/s/quan-xuan-useselections-rkn8p3

![1](https://github.com/alibaba/hooks/assets/63445570/62550cee-1412-4391-96c1-0fa641096b0d)
有n个红色框这样的，是否就不可以使用useSelections了呢？
难道需要一个一个这样进行定义`const { allSelected, isSelected, toggle, toggleAll } = useSelections(list1);`

**Comment by liuyib** [comment]
> 有n个红色框这样的，是否就不可以使用useSelections了呢？
> 难道需要一个一个这样进行定义`const { allSelected, isSelected, toggle, toggleAll } = useSelections(list1);`

把上图**单个**红框部分封装到一个组件中，假设叫 CheckCmp，在 CheckCmp 中使用 useSelections，然后从服务端获取数据，遍历获取的数据传给 CheckCmp。

demo: https://codesandbox.io/s/ahooks-issue-2271-kc7xcr?file=/App.tsx

如果没问题了的话，issue 可以关了

**Comment by ysl-ccc** [comment]
好的
