### ISSUE TITLE
useMemoizedFn 持久后的函数不会继承函数本身的属性？

### ISSUE THREAD

**Issue by pokerboard** [alibaba/hooks#2273]
```
import { useMemoizedFn } from 'ahooks';
import { useCallback } from 'react';

const fn = () => {};

fn.childVar = 'childVar';
fn.childFn = () => {};

const Demo: React.FC = () => {
  console.dir(fn);
  console.dir(useMemoizedFn(fn));
  console.dir(useCallback(fn, []));

  return <></>;
};

export default Demo;
```

![image](https://github.com/alibaba/hooks/assets/130121019/078d22a0-c2c1-4e97-af51-7c450a2d8ec9)

**Comment by liuyib** [comment]
useMemoizedFn 返回的是与传入的 fn 完全不同的一个新函数（只是在这个新函数里调用了传入的 fn），并一直保持这个新函数的引用。

所以，经过 useMemoizedFn 包裹的 fn，就不再是原来的 fn 了。

**Comment by liuyib** [comment]
需要在函数上加一些自定义属性的话，这个场景 useMemoizedFn 目前满足不了，还是使用 useCallback 吧。

后面我在文档里说明这一点。
