### ISSUE TITLE
希望 useAntdTable 可以设置 搜索表单的默认值和边输入边搜索

### ISSUE THREAD

**Issue by GYxiaOZ** [alibaba/hooks#228]
### 问题描述

在很多场景下会遇到给列表管理页设置默认搜索条件的情况，还有我们公司这种管理页的模式都是边输入边搜索，不需要点一下搜索按钮

### 期望行为

增加表单默认值配置和提供优雅的边输入边搜索方案

### 补充信息

我现在是用表单的onChange去触发实现的边输边搜，但是这样写得在每一个表单项都写onChange，感觉很不优雅
![image](https://user-images.githubusercontent.com/15631279/72582981-8799e280-391f-11ea-9b36-5825812ae781.png)

**Comment by brickspert** [comment]
看看最新的 useFormTable 的第一个例子：https://hooks.umijs.org/zh-CN/antd/use-form-table#form-%E4%B8%8E-table-%E8%81%94%E5%8A%A8
