### ISSUE TITLE
useInfiniteScroll 的getScrollTop方法问题

### ISSUE THREAD

**Issue by LJJCherry** [alibaba/hooks#2283]
```javascript
const scrollMethod = () => {
    let el = getTargetElement(target);
    if (!el) {
      return;
    }

    el = el === document ? document.documentElement : el;

    const scrollTop = getScrollTop(el);
    const scrollHeight = getScrollHeight(el);
    const clientHeight = getClientHeight(el);

    if (scrollHeight - scrollTop <= clientHeight + threshold) {
      loadMore();
    }
  };
const getScrollTop = (el: Document | Element) => {
  if (el === document || el === document.body) {
    return Math.max(
      window.pageYOffset,
      document.documentElement.scrollTop,
      document.body.scrollTop,
    );
  }
  return (el as Element).scrollTop;
}
``` 
相关代码链接：https://github.com/alibaba/hooks/blob/65791303ff1fe4e35395aa7d481f44346d64eba8/packages/hooks/src/useInfiniteScroll/index.tsx#L90
导致el = document的时候，在某些安卓浏览器里面没有获取到scrollTop，getScrollTop应该改成
```javascript
const getScrollTop = (el: Document | Element) => {
  if (el === document.documentElement || el === document.body) {
    return Math.max(
      window.pageYOffset,
      document.documentElement.scrollTop,
      document.body.scrollTop,
    );
  }
  return (el as Element).scrollTop;
}
```

**Comment by hchlq** [comment]
不能直接这么改，会有 break change，应该是安卓浏览器不兼容的问题吗？

**Comment by hchlq** [comment]
安卓浏览器命中了 `el === document` 的时候，这三个没有一个是有值的吗

```ts
window.pageYOffset
document.documentElement.scrollTop
document.body.scrollTop,
```

**Comment by LJJCherry** [comment]
> 安卓浏览器命中了 `el === document` 的时候，这三个没有一个是有值的吗
> 
> ```ts
> window.pageYOffset
> document.documentElement.scrollTop
> document.body.scrollTop,
> ```

现在的代码当el等于document的时候走不到这个逻辑啊，在外面 el = el === document ? document.documentElement : el;
el被赋值为document.documentElement了，现在安卓的现象是
<img width="537" alt="7316bd65-eaf9-4441-a285-4c346e5bd001" src="https://github.com/alibaba/hooks/assets/12826705/79b07ed4-2199-4c96-9805-18c726a04eff">

**Comment by hchlq** [comment]
我了解了，感兴趣来个 PR 修一下不？

**Comment by hchlq** [comment]
应该是安卓下面的 `document.documentElement.scrollTop` 不兼容，是否可以换 el，之前修复的参考 #2119

**Comment by LJJCherry** [comment]
> 应该是安卓下面的 `document.documentElement.scrollTop` 不兼容，是否可以换 el，之前修复的参考 #2119

我的el用的就是document的，是因为ahooks里面这个逻辑导致的安卓有问题
<img width="626" alt="image" src="https://github.com/alibaba/hooks/assets/12826705/8439e41a-67ea-4981-9190-18a84b194b9b">

**Comment by hchlq** [comment]
正常情况下 document.documentElement.scrollTop 是有值的，是不是你所在的浏览器不兼容。可以看看上面提到之前修复一个问题的上下文

**Comment by hchlq** [comment]
问题上下文大概是，下面这段逻辑有问题，如果是 document，让其走 document.documentElement，不让进入这个分支

```ts
  if (el === document || el === document.body) {
    return Math.max(
      window.pageYOffset,
      document.documentElement.scrollTop,
      document.body.scrollTop,
    );
  }
```

**Comment by LJJCherry** [comment]
> 正常情况下 document.documentElement.scrollTop 是有值的，是不是你所在的浏览器不兼容。可以看看上面提到之前修复一个问题的上下文

目前的我们这边传的el是document的，3.7.8版本的ahooks，所有的安卓手机都无法自动实现滚动加载更多，我去看下你说的那个问题，我们目前只能锁死在3.7.5的版本，
<img width="617" alt="企业微信截图_deedcdfe-1d50-45c2-8335-7c84cf7ceb65" src="https://github.com/alibaba/hooks/assets/12826705/96a61326-fc22-4fe2-a492-95786fcb306d">
就是这次改动

**Comment by LJJCherry** [comment]
> 问题上下文大概是，下面这段逻辑有问题，如果是 document，让其走 document.documentElement，不让进入这个分支
> 
> ```ts
>   if (el === document || el === document.body) {
>     return Math.max(
>       window.pageYOffset,
>       document.documentElement.scrollTop,
>       document.body.scrollTop,
>     );
>   }
> ```

我看你提到的那个修复，是修复的getClientHeight的问题，但那个改动影响了document 的 getScrollTop的获取，

**Comment by LJJCherry** [comment]
> 应该是安卓下面的 `document.documentElement.scrollTop` 不兼容，是否可以换 el，之前修复的参考 #2119

el 应该换啥呢？本身 el 就是document，整个页面滚动到底部触发自动加载更多啊，呜呜呜～我其实尝试过用document.body，但 getClientheight又不对了

**Comment by hchlq** [comment]
不兼容这种情况比较少见，可能是安卓不兼容，你可以按照下面的方案来，应该是没问题的

```ts
  const el = useMemo(() => {
    const doc = document.documentElement;
    Reflect.defineProperty(doc, 'scrollTop', {
      get() {
        return Math.max(
          window.pageYOffset,
          document.documentElement.scrollTop,
          document.body.scrollTop,
        );
      },
    });
    Reflect.defineProperty(doc, 'scrollHeight', {
      get() {
        return document.documentElement.scrollHeight;
      },
    });
    Reflect.defineProperty(doc, 'clientHeight', {
      get() {
        return document.documentElement.clientHeight;
      },
    });

    return doc;
  }, []);
```

**Comment by LJJCherry** [comment]
我其实没有理解getClientHeight获取的有问题，为什么要更改getScrollTop兼容方法的获取逻辑？

**Comment by hchlq** [comment]
两者不可兼得吧，绝大部分都是兼容的，document.documentElement.scrollTop 不兼容的情况很少看见

**Comment by LJJCherry** [comment]
> 两者不可兼得吧，绝大部分都是兼容的，document.documentElement.scrollTop 不兼容的情况很少看见

<img width="1067" alt="image" src="https://github.com/alibaba/hooks/assets/12826705/143b0645-9a36-459a-b053-0cdb9e3798b4">
不能把这个逻辑移到getClientHeight里面吗？

**Comment by hchlq** [comment]
可以是可以，不过会出现获取一些信息元素不一致的情况，可能会存在其他场景的 badcase

**Comment by LJJCherry** [comment]
getScrollTop 这个方法我搜了一下只有 useInfiniteScroll 这个hook在用，目前 badcase 就在眼前啊，如果有demo的话可以试试安卓机

**Comment by hchlq** [comment]
其他场景指的是 document 获取 scrollTop 和 clientHeight 不一致的情况，不是指被引用情况

**Comment by hchlq** [comment]
想了一下，应该需要处理一下，可否来个 PR

**Comment by hchlq** [comment]
如果没时间提 PR 的话说下哈，后续我处理一下

**Comment by LJJCherry** [comment]
我提一个 PR 吧,https://github.com/alibaba/hooks/pull/2285

**Comment by hchlq** [comment]
这个方法可以解决你的问题吗

```ts
  const el = useMemo(() => {
    const doc = document.documentElement;
    Reflect.defineProperty(doc, 'scrollTop', {
      get() {
        return Math.max(
          window.pageYOffset,
          document.documentElement.scrollTop,
          document.body.scrollTop,
        );
      },
    });
    Reflect.defineProperty(doc, 'scrollHeight', {
      get() {
        return document.documentElement.scrollHeight;
      },
    });
    Reflect.defineProperty(doc, 'clientHeight', {
      get() {
        return document.documentElement.clientHeight;
      },
    });

    return doc;
  }, []);
```

**Comment by LJJCherry** [comment]
> ```ts
> Reflect.defineProperty(doc, 'scrollTop', {
>       get() {
>         return Math.max(
>           window.pageYOffset,
>           document.documentElement.scrollTop,
>           document.body.scrollTop,
>         );
>       },
>     });
> ```

<img width="530" alt="image" src="https://github.com/alibaba/hooks/assets/12826705/f1720c88-9855-46e6-a839-5dcbd6da06a5">
不太行

**Comment by LJJCherry** [comment]
> 这个方法可以解决你的问题吗
> 
> ```ts
>   const el = useMemo(() => {
>     const doc = document.documentElement;
>     Reflect.defineProperty(doc, 'scrollTop', {
>       get() {
>         return Math.max(
>           window.pageYOffset,
>           document.documentElement.scrollTop,
>           document.body.scrollTop,
>         );
>       },
>     });
>     Reflect.defineProperty(doc, 'scrollHeight', {
>       get() {
>         return document.documentElement.scrollHeight;
>       },
>     });
>     Reflect.defineProperty(doc, 'clientHeight', {
>       get() {
>         return document.documentElement.clientHeight;
>       },
>     });
> 
>     return doc;
>   }, []);
> ```

<img width="530" alt="image" src="https://github.com/alibaba/hooks/assets/12826705/fe10b7fb-2ce4-4704-9358-3c61041a834d">
不太行？

**Comment by hchlq** [comment]
@LJJCherry 改成这样即可

```ts
  const el = useMemo(() => {
    const doc = document.documentElement;
    Reflect.defineProperty(doc, 'scrollTop', {
      get() {
        return Math.max(
          window.pageYOffset,
          document.body.scrollTop,
        );
      },
    });
    Reflect.defineProperty(doc, 'scrollHeight', {
      get() {
        return document.documentElement.scrollHeight;
      },
    });
    Reflect.defineProperty(doc, 'clientHeight', {
      get() {
        return document.documentElement.clientHeight;
      },
    });

    return doc;
  }, []);
```

**Comment by LJJCherry** [comment]
> 

也还是不行，下面这行代码会报Maximum call stack size exceeded，屏蔽掉这个， 下面clineHeight也会报这个错，把这俩都屏蔽掉，不报错了，页面也无法滚动加载更多了
```typescript
Reflect.defineProperty(doc, 'scrollHeight', {
      get() {
        return document.documentElement.scrollHeight;
      },
    });
```

**Comment by hchlq** [comment]
把  `document.documentElement.scrollHeight` 和 `document.documentElement.clientHeight` 处理一下呢，提升一下，因为递归读取死循环了

**Comment by LJJCherry** [comment]
> 把 `document.documentElement.scrollHeight` 和 `document.documentElement.clientHeight` 处理一下呢，提升一下，因为递归读取死循环了

放弃，我直接先写死了3.7.5的版本号
