### ISSUE TITLE
useKeyPress中，keyFilter为['meta.uparrow.1'], 触发相应事件，没有调用回调 

### ISSUE THREAD

**Issue by DanielLeefu** [alibaba/hooks#2284]
mac电脑，meta对应command按键，代码如下，按下command，不会触发console

```ts
useKeyPress(
    ['meta.uparrow.1'],
    () => {
      console.log('done');
    },
 );
```

期望： 按下 ⌘ +↑+ 1 组合键后可以触发console.log

**Comment by liuyib** [comment]
这是浏览器的限制，目前原因不明。我测了下 Mac 系统中，Chrome、FireFox、Edge 浏览器都无法触发“Command + 数字键”。

你这里的快捷键 `meta.uparrow.1` 就命中了系统的这个限制。

可以自己用 JS 尝试下，可以验证原生就不支持：

```js
window.addEventListener('keydown', (e) => {
  console.log('e.key', e.key);
})
```

后面我会在文档里加上 FAQ 说明系统的这个限制。

---

相关 issue、PR：
- https://github.com/alibaba/hooks/issues/2044
- https://github.com/alibaba/hooks/pull/2058

以前发现 Mac 系统下对 `keyup` 事件的限制比较多，现在来看对 `keydown` 也会有限制
