### ISSUE TITLE
useAntdTable 如何和状态管理 lib 更好的结合在一起？

### ISSUE THREAD

**Issue by dongliang1993** [alibaba/hooks#229]
useAntdTable 这个 hook 是完全接管了 table 的数据，如果项目中使用了状态管理工具(ps: 比如 mobx)，我需要在 asyncFn 这个参数里面同时把 dataSource 放到自己的 store 上。这种情况有没有比较好的处理方法？

**Comment by brickspert** [comment]
> useAntdTable 这个 hook 是完全接管了 table 的数据，如果项目中使用了状态管理工具(ps: 比如 mobx)，我需要在 asyncFn 这个参数里面同时把 dataSource 放到自己的 store 上。这种情况有没有比较好的处理方法？

如果使用传统的 redux、mobx等，目前确实没有好的解决办法。但是新版的 useAntdTable 会有一个 OnSuccess 的函数，可以在这里去传值给 mobx 等。
新版的预计半个月发布。

另外，hooks 推荐使用新的数据流工具，比如 unstated-next，hox 等。这样可以直接把 useAntdTable 放到 store 里面去。美滋滋

**Comment by dongliang1993** [comment]
或者有没有可能允许在 option 参数里面加一些可选参数(比如 dataSource )，以受控的形式来控制这个 hook，因为其实大部分场景是想使用 useAntdTable 中一些属性和方法，如 onChange
主要是状态管理这一块团队内部还没有统一，有的人觉得  unstated-next 封装的过于简单，难免要自己在这个基础上再进行定制，有的人觉得 mobx-react-lite 配合 hooks 也比较直观，个人有个人的偏爱 🤣

**Comment by brickspert** [comment]
最新的  v1.6.0 的 [useRequst pagination ](https://hooks.umijs.org/zh-CN/async?anchor=%E5%88%86%E9%A1%B5) 支持了手动触发 pagination.
