### ISSUE TITLE
1

### ISSUE THREAD

**Issue by LK602** [alibaba/hooks#2290]
<img width="588" alt="image" src="https://github.com/alibaba/hooks/assets/140770528/7e04a225-9423-4612-a2dd-004a73589938">

**Comment by ZonghaoLi777** [comment]
useState支持初始值为一个函数，该函数会在useState这个hook初始化的时候执行一次。
官方文档:https://react.dev/reference/react/useState#avoiding-recreating-the-initial-state

**Comment by ZonghaoLi777** [comment]
> <img alt="image" width="588" src="https://user-images.githubusercontent.com/140770528/259696998-7e04a225-9423-4612-a2dd-004a73589938.png">
useState支持初始值为一个函数，该函数会在useState这个hook初始化的时候执行一次。
官方文档:https://react.dev/reference/react/useState#avoiding-recreating-the-initial-state
