### ISSUE TITLE
usePagination 缓存失效前，无法调用下一页数据？

### ISSUE THREAD

**Issue by zmm2tysu** [alibaba/hooks#2291]
```
import React from "react";
import { usePagination } from "ahooks";

const fetchMsgs = async ({ current }) => {
  console.log(`请求第${current}页数据`);
  return {
    list: [],
    total: 0
  };
};

export default () => {
  const { pagination, run } = usePagination(
    async ({ current }) => {
      console.log(current);
      return await fetchMsgs({ current });
    },
    {
      manual: true,
      staleTime: 1000 * 5,
      cacheTime: 1000 * 5,
      cacheKey: "chat-msg"
    }
  );

  return (
    <div>
      <a onClick={() => run({ current: pagination.current + 1, pageSize: 5 })}>
        加载更多
      </a>
    </div>
  );
};

```

https://codesandbox.io/s/demo-for-ahooks-forked-l24gcj

只有5秒过期后，才能调用下一页数据，多点几次，页码也变化了

**Comment by liuyib** [comment]
> 只有5秒过期后，才能调用下一页数据

参照文档：

[你可以通过 options.staleTime 设置数据保持新鲜时间，在该时间内，我们认为数据是新鲜的，不会重新发起请求](https://ahooks.js.org/zh-CN/hooks/use-request/cache/)

如果短期不需要重新请求数据，那么你可以使用 staleTime。你举的这个例子，我的理解，既然要加载更多，每次点击时都应该去重新获取数据，因此不应该使用 staleTime 参数。

> 多点几次，页码也变化了

对于这点，实际项目中应该通过禁用、loading、防抖或遮罩 等，来防止重复点击

**Comment by zmm2tysu** [comment]
> 如果短期不需要重新请求数据，那么你可以使用 staleTime。你举的这个例子，我的理解，既然要加载更多，每次点击时都应该去重新获取数据，因此不应该使用 staleTime 参数。

其实我的场景是聊天，左边能切换联系人，右边显示聊天记录。我想缓存下来请求过的聊天记录，同时可以加载更多新的聊天记录，通过现有的缓存策略能实现吗？

**Comment by liuyib** [comment]
> 其实我的场景是聊天，左边能切换联系人，右边显示聊天记录。我想缓存下来请求过的聊天记录，同时可以加载更多新的聊天记录，通过现有的缓存策略能实现吗？

现有缓存策略实现不了这个需求。

其实 useRequest/usePagination 的缓存能力只是“把上一次结果存起来，然后作为下一次请求前的 placeholder”，缓存的数据在下一次请求后会被替换成新的：

![image](https://github.com/alibaba/hooks/assets/38221479/9a975b63-dfd1-4f37-b4ee-15ddc443ce6d)

而你的需求，需要的缓存效果是“每次的请求结果**增量**存储起来，而不是 replace”。所以，只能自己把数据存起来了~

按照你的需要简单写了个 demo，实现了你说的效果，可以参考下：https://codesandbox.io/s/ahooks-issue-2291-4j3sgv?file=/src/App.js
