### ISSUE TITLE
使用useRequest的ready选项，可能存在参数类型问题

### ISSUE THREAD

**Issue by jiangjiu** [alibaba/hooks#2293]
```js

// 可能是undefined
const uid = user?.id 

 const { data, loading } = useRequest(
  // 这里的类型就会出问题，因为fetch请求对uid是必选项，不能是undefined
   () =>  fetchList({ userid: uid }),
   // uid有值才发请求
    { ready: !!uid },
  );
```

求问，这种情况下除了使用类型断言，强行安排` uid as string`，还有其他更好的办法吗

**Comment by jiangjiu** [comment]
useswr可以判断service函数是否是空，从而达到ready的效果

**Comment by liuyib** [comment]
`fetchList ` 是你自己定义的函数，类型的可选性你可以控制。

`ready` 参数，你也给出了，强制为布尔值 `!!uid` 我看着也没有类型问题。

所以哪里有问题呢？再细说下~

**Comment by jiangjiu** [comment]
> `fetchList ` 是你自己定义的函数，类型的可选性你可以控制。
> 
> `ready` 参数，你也给出了，强制为布尔值 `!!uid` 我看着也没有类型问题。
> 
> 所以哪里有问题呢？再细说下~

fetchList这个函数，需要uid必须有值，string类型，不能是undefined；他未必可控，可能是第三方提供的调用函数；

所以问题就是`()=>fetchList({userid: uid})`这一行，因为uid可能是undefined，所以类型编译就会报错。
常规一般是写一个类型保护分支，但是hooks又没法写在分支里，所以这里useRequest就需要写`()=>fetchList({userid: uid as string})` 才能避开编译问题

想请问下有没有更好的解法

**Comment by liuyib** [comment]
```diff
// 可能是undefined
const uid = user?.id 

 const { data, loading } = useRequest(
  // 这里的类型就会出问题，因为fetch请求对uid是必选项，不能是undefined
-   () =>  fetchList({ userid: uid }),
+   () =>  {
+      if (!uid) return;
+      return  fetchList({ userid: uid })
     },
   // uid有值才发请求
    { ready: !!uid },
  );
```

这样呢？

**Comment by jiangjiu** [comment]
> 
service的函数签名不允许直接return，需要这样写才能过typecheck：

`      if (!uid) return Promise.resolve(undefined);`

但是这样确实有点繁琐，最好是修改一下service的类型签名？按swr那样是最简单的了，service为空的时候达到ready的效果

**Comment by SignDawn** [comment]
加个 async 是否也可以直接 return 呢？
个人建议不要过度纠结 ts 的类型问题，如果你认为 uid 在此处一定存在，那你可以直接加个 ! 来跳过 null 检查。

具体可以看下下面这个 demo 
https://codesandbox.io/s/festive-keller-6g9skr?file=/src/App.tsx

**Comment by jiangjiu** [comment]
> 加个 async 是否也可以直接 return 呢？ 个人建议不要过度纠结 ts 的类型问题，如果你认为 uid 在此处一定存在，那你可以直接加个 ! 来跳过 null 检查。
> 
> 具体可以看下下面这个 demo https://codesandbox.io/s/festive-keller-6g9skr?file=/src/App.tsx

无论是加async套壳，还是用类型断言！/  as  ，本质是在糊这个需求了，useRequest需要提供更符合人体工学的接口哇。。。

是不是参照swr的设计就好了，swr的设计天然不存在这问题。

另外 ， 我司eslint不许用！，非常尴尬

**Comment by liuyib** [comment]
给 service 加 async 可以解决，并不像你说的加 async 是在糊需求。

useRequest 接收的 service 函数需要 Promise 类型的。你之前的例子中这样用：

```diff
 const { data, loading } = useRequest(
+   () =>  fetchList({ userid: uid }),
    { ready: !!uid },
  );
```

也只是在传了一个类型错误的 service 函数中，恰好返回了一个 Promise 的函数，导致 service 函数类型成了预期的 Promise。实际上你应该确保 service 为 Promise 类型的函数。

所以，这样用没什么大问题：

```diff
 const { data, loading } = useRequest(
-   () =>  fetchList({ userid: uid }),
+   async () =>  {
+      if (!uid) return;
+      return  fetchList({ userid: uid })
     },
    { ready: !!uid },
  );
```

---

另外，useSWR 的自定义请求函数 fetcher 也是异步函数，需要是 Promise 类型的：
![image](https://github.com/alibaba/hooks/assets/38221479/1ac1e9d8-e4e2-4bd6-ae30-97d7bd2b8c10)

怎么做到你说的：

> service为空的时候达到ready的效果

烦请给个在线 demo 解惑。 @jiangjiu

**Comment by jiangjiu** [comment]
> 怎么做到你说的：
> 
> > service为空的时候达到ready的效果
> 
> 烦请给个在线 demo 解惑。 @jiangjiu


```typescript

//  fetchList必须接收string参数，不能是undefined
function fetchList(uid: string) {
  return Promise.resolve(uid);
}

export const Footer = () => {
  
  const uid = undefined;
  // fetcher可以判空，返回null，这样swr就不会发起请求，起到useRequest里ready的效果了
  const { data } = useSWR(key, uid ? () => fetchList(uid) : null);

  return (
    <div>{data}</div>
  );
};
```

可以看上面，是可以过ts校验的，而且代码看起来很简洁；
swr可以给fetcher传null，useRequest目前不行，所以处理类型上就会需要用async报一下，然后在里面判断，是不是考虑和swr对齐

**Comment by liuyib** [comment]
按照你的代码改了下：

```tsx
// fetchList必须接收string参数，不能是undefined
function fetchList(uid: string) {
  return Promise.resolve(uid);
}

export const Footer = () => {
  const uid = undefined;
  const { data } = useRequest(async () => {
    if (!uid) return;
    return fetchList(uid);
  });

  return <div>{data}</div>;
};
```

没什么类型问题。多包一层 async 没什么不规范、不合法、不优雅的之处。

另外，useSWR 应该也可以这样（未实际测试）：

```tsx
const { data } = useSWR(key, async () => {
  if (!uid) return;
  fetchList(uid);
});
```

你提供的这种写法也是合法的：

```tsx
const { data } = useSWR(key, uid ? () => fetchList(uid) : null);
```

你用惯了这种写法无可厚非，但不要认为这就是真理，编程没有银弹。

以上，它们具有共性，都有通用的处理假值数据的做法。在**这个 issue 涉及的问题之内**，它们没有说谁不如谁一说，何谈向 useSWR 对齐。

---

最后，这种写法支持很简单：

```tsx
const { data } = useSWR(key, uid ? () => fetchList(uid) : null);
```

放到 useRequest 里允许 service 传假值就好了。可以做，但必要性不是特别大。

**Comment by jiangjiu** [comment]
> 
你说的用async套一层，如果只是这地方套一下，我觉得也还好，他和三元表达式确实没啥太大区别。

但是，对useRequest来说，**我还需要在options里声明ready这个属性，这就把同一个逻辑放两个地方表达了，而且是重复的逻辑**，所以才会有类型问题，而我提这个issue的目的其实也在这里，ahooks需要提供更好的接口。

可以这样想，如果是swr这种方式，我只要在一个地方写，无论是async function和三元表达式都可以，任君挑选；
如果是useRequest这样，我只能用async function，而且还要声明ready属性；
从这个角度看是不是有差别了呢。

**Comment by liuyib** [comment]
> 如果是useRequest这样，我只能用async function，而且还要声明ready属性；

确实如你所说，useRequest 需要下面这样用才能实现“在 uid 为假值时不发请求，为真值时才去发送请求”：

```tsx
const { data } = useRequest(
  async () => {
    if (!uid) return;
    return fetchList(uid);
  },
  {
    ready: !!uid,
    // 或
    // refreshDeps: [uid],
  },
);
```

但我看了下 useSWR，以你给的代码为例：

```tsx
const { data } = useSWR(key, uid ? () => fetchList(uid) : null);
```

我试了下，上面这行代码做不到“uid 为真值时才去发送请求”，只是做到了“在 uid 为假值时不发请求”。

我翻了翻 useSWR 的文档，想要实现“在 uid 为假值时不发请求，为真值时才去发送请求”，一样需要额外设置：

可在线体验：https://codesandbox.io/s/ahooks-issue-2293-9nc29c?file=/src/App.js

```tsx
// 方法 1
// 这种用法需要控制 url 和 fetcher，也就是第一个和第二个参数，麻烦程度和 useRequest 基本相同（都挺麻烦）
const { data, error, isLoading } = useSWR(
    ["https://api.github.com/repos/vercel/swr", uid],
    uid ? getUsername : null
);

// 或这样：
// 方法 2
// 第一个参数传 url 是 useSWR 的特有用法，useRequest 中没有这种用法，所以不予此作比较。这里代码仅做参考
const { data, error, isLoading } = useSWR(
    uid ? "https://api.github.com/repos/vercel/swr" : null,
    getUsername
);
```

综上，useSWR 能通过三元运算符控制第一个参数 url 来实现是否发送请求，这样确实很方便，但是 useRequest 里没有这种传 url 的用法，使用方式差距过大，因此不作考虑。除此之外，它们使用的麻烦程度看不出明显差异。

**Comment by jiangjiu** [comment]
> 我试了下，上面这行代码做不到“uid 为真值时才去发送请求”，只是做到了“在 uid 为假值时不发请求”。

> 我翻了翻 useSWR 的文档，想要实现“在 uid 为假值时不发请求，为真值时才去发送请求”，一样需要额外设置：

感谢您的认真回复~
但是上面这两句话没看太懂; 我上面那行swr的代码应该就可以实现uid为真才去发请求了呀，而且这个控制和key没啥关系，可以只关注fetcher

**Comment by liuyib** [comment]
> 我上面那行swr的代码应该就可以实现uid为真才去发请求了呀

你试下我给的在线 demo，只用你上面给的那行代码实现不了。要是能直接一句三元运算实现，那自然很方便。
