### ISSUE TITLE
useRequest 在jest 环境下报错

### ISSUE THREAD

**Issue by murrayee** [alibaba/hooks#2295]
请求库：Axios
mock：MSW
测试框架：jest  + @testing-library/react 
前端框架：UmiJs

在测试环境下会报错异常，无法正常返回msw拦截的数据。

**Comment by murrayee** [comment]
初步分析是因为在jest环境下，测试库render后卸载时机导致， 导致 useUnmount先执行了 cancel，currentCount!==this.count 然后返回异常

**Comment by murrayee** [comment]
可以加个控制吗？我发现页面应用其实也会遇到问题，当我全局loading 如果没跟着组件或者路由页面生命周期走的话，没有结束请求然后切换页面loading 状态会pending

**Comment by hchlq** [comment]
可以看看我们代码的测试用例，也是在 jest 环境下执行的，不太清楚你这边有什么不一样的吗

**Comment by murrayee** [comment]
> 可以看看我们代码的测试用例，也是在 jest 环境下执行的，不太清楚你这边有什么不一样的吗

我晚点弄个demo

**Comment by murrayee** [comment]
https://codesandbox.io/p/sandbox/billowing-hill-92xwvw?file=/test/App.test.js

**Comment by murrayee** [comment]
抱歉 ，根因大概是， jest环境下render组价完后会卸载，走进了useRequest的unmount，导致返回滞后

**Comment by murrayee** [comment]
> 抱歉 ，根因大概是， jest环境下render组价完后会卸载，走进了useRequest的unmount，导致返回滞后



> 可以看看我们代码的测试用例，也是在 jest 环境下执行的，不太清楚你这边有什么不一样的吗

demo是 hooks
