### ISSUE TITLE
引入umi-hooks,使用时就报regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Wuuuu** [alibaba/hooks#230]
在引入umi-hook的hooks时，会报这样的错误，请问如何解决。
Unhandled Rejection (ReferenceError): regeneratorRuntime is not defined
 "antd": "^3.9.0",
 "react": "^16.12.0",
 "react-dom": "^16.12.0",

**Comment by brickspert** [comment]
你用的 node 8 吧？
升级下 node 试试。

或者项目中依赖下 regenerator-runtime

见：https://github.com/umijs/hooks/issues/46

**Comment by Wuuuu** [comment]
> 你用的 node 8 吧？
> 升级下 node 试试。
> 
> 或者项目中依赖下 regenerator-runtime
> 
> 见：#46

node 版本为v10.16.2

**Comment by menzil** [comment]
> > 你用的 node 8 吧？
> > 升级下 node 试试。
> > 或者项目中依赖下 regenerator-runtime
> > 见：#46
> 
> node 版本为v10.16.2

我也出现了同样问题，项目中依赖下 regenerator-runtime安装，再次在使用的地方引入一下才能解决。import "regenerator-runtime/runtime";
