### ISSUE TITLE
useRequest 在使用 refreshDeps 时把传入函数的参数也缓存下来了

### ISSUE THREAD

**Issue by linzhipeng98** [alibaba/hooks#2300]
```
 // 大概伪代码如下：
 const { run } =  useRequest(
    async (params = 100) => {
      console.log(params)
    },
    {
      refreshDeps: [app],
    }
  )

// 页面加载完成后会触发 run，此时 params 取默认值 100，打印 100
// 代码里手动执行一下 run(1000)，打印 1000
// 通过触发 app 变化，执行 run，此时属于没有传 params，我理解应该打印 100，但是打印了 1000
```

复现地址
https://codesandbox.io/s/keen-smoke-jvkrkc?file=/App.tsx

**Comment by linzhipeng98** [comment]
这个 issue 没人看一下么，是描述不够清楚么
@liuyib

**Comment by liuyib** [comment]
这个行为是正常的，文档写的不够清晰，我回头改下。

首先，[依赖刷新](https://ahooks.js.org/zh-CN/hooks/use-request/refresy-deps)能力不是发起一个**全新的**请求，而是和[刷新（重复上一次请求）](https://ahooks.js.org/zh-CN/hooks/use-request/basic#%E5%88%B7%E6%96%B0%E9%87%8D%E5%A4%8D%E4%B8%8A%E4%B8%80%E6%AC%A1%E8%AF%B7%E6%B1%82)的行为一致，也就是依赖变化时，重新发起上一次请求，自然参数也是上一次的了。

如果这个行为满足不了你的需求，可以自定义这个刷新行为：传 `refreshDepsAction` 参数（这个参数文档上没写，我后面补上，可以通过类型提示看到），像这样：https://codesandbox.io/s/ahooks-issue-2300-vrjn8n?file=/App.tsx

**Comment by linzhipeng98** [comment]
@liuyib  感谢回复，我目前就是通过 refreshDepsAction 来解决的。

**Comment by Junlin-Zhu** [comment]
能否在refreshOnWindowFocus也加上这个行为么？同样是刷新能力支持定制？

**Comment by liuyib** [comment]
> 能否在refreshOnWindowFocus也加上这个行为么？同样是刷新能力支持定制？

可以考虑支持
