### ISSUE TITLE
useAntdTable

### ISSUE THREAD

**Issue by rankaifeng** [alibaba/hooks#2305]
我在react中使用useAntdTable 比如页面有三个按钮 每个按钮对应一个搜索条件 当我进入页面传入第一个搜索条件过后，后台返回2条数据，当我点击第二个按钮传入搜索条件过后，后台返回数据为空的，但是页面还是显示的上一次数据。我尝试在每点击一次按钮的时候调用rest()方法，但还是会出现这个问题。

**Comment by liuyib** [comment]
能否提供个可复现的在线 demo，获取数据可以模拟下
