### ISSUE TITLE
能否增加EventSource接口支持

### ISSUE THREAD

**Issue by Lind-pro** [alibaba/hooks#231]

**Comment by brickspert** [comment]
是否可以详细描述下问题呢？

**Comment by Lind-pro** [comment]
我们当前系统会有很多eventSource。请求此类接口代码大致如下
![image](https://user-images.githubusercontent.com/18098618/73804756-cecd1200-47ff-11ea-886b-5ce9ab93df1a.png)
希望能够增加对这种接口的支持

**Comment by xiexingen** [comment]
可以用pubsub

**Comment by awmleer** [comment]
这个问题似乎是需要一个工具函数来解，不在 umi hooks 的覆盖范围内～
