### ISSUE TITLE
`useAhooks`: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by kaitoukid-1412** [alibaba/hooks#2310]
```json
 "dependencies": {
    "ahooks": "^3.7.8",
    "next": "13.4.19",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  }
```

- `Pages Router`

![image](https://github.com/alibaba/hooks/assets/15698245/83c27189-0374-457b-bc41-38d73f196f46)

**Comment by liuyib** [comment]
我用 `npx create-next-app@latest` 新建一个项目，依赖版本和你的一致也复现不了。

这是 next.js 的问题，可以试试：https://github.com/alibaba/hooks/issues/2254#issuecomment-1630992225, 如果还是无法解决的话，目前无解。

最好能提供个可复现报错的在线 demo 看下。

类似 issues:

- https://github.com/alibaba/hooks/issues/2254
- https://github.com/alibaba/hooks/issues/2263

**Comment by kaitoukid-1412** [comment]
@liuyib 

- A `demo` app

```
https://www.mediafire.com/file/fpuubgnpec22cy3/my-app.rar/file
```

- Command

```
npm i
npm run dev
```

- file changes
```
src/pages/index.js
```

**Comment by liuyib** [comment]
首先感谢提供的 demo 项目，我试了，这个方法可以的 https://github.com/alibaba/hooks/issues/2254#issuecomment-1630992225, 你那边呢？ @shenlong616

**Comment by kaitoukid-1412** [comment]
> 首先感谢提供的 demo 项目，我试了，这个方法可以的 [#2254 (comment)](https://github.com/alibaba/hooks/issues/2254#issuecomment-1630992225), 你那边呢？ @shenlong616

okay, thank you for your support @liuyib
