### ISSUE TITLE
gulpfile.js中目前"es"命令是不是不需要过babel，是否考虑删除？

### ISSUE THREAD

**Issue by littletommytan** [alibaba/hooks#2312]
<img width="718" alt="image" src="https://github.com/alibaba/hooks/assets/32828677/7daf6dbc-9acb-4a40-b319-e3abdccec584">

**Comment by liuyib** [comment]
实测确实不需要，移除 `pipe(babel())` 后，产物只是代码格式化上有区别。提 PR 处理了

**Comment by crazylxr** [comment]
emm，为啥不需要了呢

**Comment by liuyib** [comment]
这个优化算了吧，没啥大的改进，关了哈~
