### ISSUE TITLE
 useVirtualList 处理后的list数据可能有重复且顺序也可能不正确

### ISSUE THREAD

**Issue by song-xiao-lin** [alibaba/hooks#2317]
后端返回的数据是确定不重复的

**Comment by song-xiao-lin** [comment]
"dependencies": {
    "ahooks": "^3.1.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }

**Comment by hchlq** [comment]
给一个在线 demo 看一下哈，mock 一下后端的数据
