### ISSUE TITLE
希望可以增加自动把Antd table的筛选项同步到url上的hook

### ISSUE THREAD

**Issue by YanYuanFE** [alibaba/hooks#232]
antd的table有不依赖后端的分页和筛选，希望可以把筛选项自动同步到URL，便于点击表格行到下一页，然后后退到表格页，能将URL上的参数再同步到table。

**Comment by brickspert** [comment]
good idea~ 我们支持下

**Comment by YanYuanFE** [comment]
棒！

**Comment by xiexingen** [comment]
+1

**Comment by xiexingen** [comment]
有没遇到过那种多tab，然后搜索条件是相同的，切换tab的时候新tab页的表格搜索条件还是之前tab的搜索条件

**Comment by brickspert** [comment]
> 有没遇到过那种多tab，然后搜索条件是相同的，切换tab的时候新tab页的表格搜索条件还是之前tab的搜索条件

试试 useRequest 的同步请求。

**Comment by xiexingen** [comment]
> > 有没遇到过那种多tab，然后搜索条件是相同的，切换tab的时候新tab页的表格搜索条件还是之前tab的搜索条件
> 
> 试试 useRequest 的同步请求。

![image](https://user-images.githubusercontent.com/7939085/74115356-da4a7f80-4be9-11ea-936b-8edca0273c69.png)
您说的同步请求是指通过refreshDeps来控制吗

**Comment by brickspert** [comment]
> > > 有没遇到过那种多tab，然后搜索条件是相同的，切换tab的时候新tab页的表格搜索条件还是之前tab的搜索条件
> > 
> > 
> > 试试 useRequest 的同步请求。
> 
> ![image](https://user-images.githubusercontent.com/7939085/74115356-da4a7f80-4be9-11ea-936b-8edca0273c69.png)
> 您说的同步请求是指通过refreshDeps来控制吗

这个试试：https://hooks.umijs.org/zh-CN/async?anchor=%E5%B9%B6%E8%A1%8C%E8%AF%B7%E6%B1%82

**Comment by xiexingen** [comment]
这个条件同步到url上的还打算支持吗

**Comment by YanYuanFE** [comment]
写了一个简略版的，勉强能用

```
// useQuery.js
import { useEffect, useState } from "react";
import { useHistory } from "react-router-dom";
import qs from "qs";

export const useQuery = (initQuery = {}) => {
  const history = useHistory();
  const url = history.location.search;
  const params = qs.parse(url.split("?")[1]);
  const [query, setQuery] = useState({
    offset: 0,
    ...initQuery,
    ...params
  });
  useEffect(() => {
    history.replace(`?${qs.stringify(query)}`);
  }, [query]);

  return [query, setQuery];
};

```

使用

```
import React, { useEffect, useState } from "react";
import { Layout, Button, Table, Input } from "antd";
import "./index.less";
import { doctorService } from "../../services/doctor.service";
import { useQuery } from "../../common/useQuery";

const { Search } = Input;

const DoctorList = () => {
  const [doctorList, setData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [query, setQuery] = useQuery({
    search: ""
  });

  const columns = [
    {
      title: "编号",
      dataIndex: "doctor_id",
      key: "id",
      defaultSortOrder: "descend",
      sorter: (a, b) => a.doctor_id - b.doctor_id
    },
    {
      title: "姓名",
      dataIndex: "name",
      key: "name"
    },
    {
      title: "医院",
      dataIndex: "hospital",
      key: "hospital"
    },
    {
      title: "地区",
      dataIndex: "zone",
      key: "zone"
    },
    {
      title: "销售",
      dataIndex: "sales",
      key: "sales"
    },
    {
      title: "操作",
      dataIndex: "action",
      key: "action",
      render: (_, record) => {
        return (
          <Button href={`#/doctor/${record.guid}${record.doctor_id}/patient`} type="primary">
            查看患者
          </Button>
        );
      }
    }
  ];

  useEffect(() => {
    setLoading(true);
    doctorService.getDoctorList({ company_id: 1 }).then(res => {
      setData(res ? res.doctor : []);
      setLoading(false);
    });
  }, []);

  return (
    <Layout>
      <div className="search">
        <Search
          defaultValue={query.search}
          placeholder="输入名字或者医院搜索"
          onSearch={val => {
            setQuery({
              ...query,
              search: val
            });
          }}
          style={{ width: 200 }}
        />
        <Button href="#/doctor/add" type="primary">
          添加医生
        </Button>
      </div>
      <Table
        loading={loading}
        dataSource={
          query.search
            ? doctorList.filter(
                item => new RegExp(query.search).test(item.name) || new RegExp(query.search).test(item.hospital)
              )
            : doctorList
        }
        columns={columns}
        rowKey="doctor_id"
        pagination={{ defaultPageSize: 20, current: Number(query.offset) }}
        onChange={(pagination, filters, sorter) => {
          setQuery({ ...query, offset: pagination.current });
        }}
      />
    </Layout>
  );
};

export default DoctorList;

```

**Comment by xiexingen** [comment]
> 写了一个简略版的，勉强能用
> 
> ```
> // useQuery.js
> import qs from "qs";
> 
> export const useQuery = (initQuery = {}) => {
>   const history = useHistory();
>   const url = history.location.search;
>   const params = qs.parse(url.split("?")[1]);
>   const [query, setQuery] = useState({
>     offset: 0,
>     ...initQuery,
>     ...params
>   });
>   useEffect(() => {
>     history.replace(`?${qs.stringify(query)}`);
>   }, [query]);
> 
>   return [query, setQuery];
> };
> ```
> 
> 使用
> 
> ```
> import React, { useEffect, useState } from "react";
> import { Layout, Button, Table, Input } from "antd";
> import "./index.less";
> import { doctorService } from "../../services/doctor.service";
> import { useQuery } from "../../common/useQuery";
> 
> const { Search } = Input;
> 
> const DoctorList = () => {
>   const [doctorList, setData] = useState([]);
>   const [loading, setLoading] = useState(false);
>   const [query, setQuery] = useQuery({
>     search: ""
>   });
> 
>   const columns = [
>     {
>       title: "编号",
>       dataIndex: "doctor_id",
>       key: "id",
>       defaultSortOrder: "descend",
>       sorter: (a, b) => a.doctor_id - b.doctor_id
>     },
>     {
>       title: "姓名",
>       dataIndex: "name",
>       key: "name"
>     },
>     {
>       title: "医院",
>       dataIndex: "hospital",
>       key: "hospital"
>     },
>     {
>       title: "地区",
>       dataIndex: "zone",
>       key: "zone"
>     },
>     {
>       title: "销售",
>       dataIndex: "sales",
>       key: "sales"
>     },
>     {
>       title: "操作",
>       dataIndex: "action",
>       key: "action",
>       render: (_, record) => {
>         return (
>           <Button href={`#/doctor/${record.guid}${record.doctor_id}/patient`} type="primary">
>             查看患者
>           </Button>
>         );
>       }
>     }
>   ];
> 
>   useEffect(() => {
>     setLoading(true);
>     doctorService.getDoctorList({ company_id: 1 }).then(res => {
>       setData(res ? res.doctor : []);
>       setLoading(false);
>     });
>   }, []);
> 
>   return (
>     <Layout>
>       <div className="search">
>         <Search
>           defaultValue={query.search}
>           placeholder="输入名字或者医院搜索"
>           onSearch={val => {
>             setQuery({
>               ...query,
>               search: val
>             });
>           }}
>           style={{ width: 200 }}
>         />
>         <Button href="#/doctor/add" type="primary">
>           添加医生
>         </Button>
>       </div>
>       <Table
>         loading={loading}
>         dataSource={
>           query.search
>             ? doctorList.filter(
>                 item => new RegExp(query.search).test(item.name) || new RegExp(query.search).test(item.hospital)
>               )
>             : doctorList
>         }
>         columns={columns}
>         rowKey="doctor_id"
>         pagination={{ defaultPageSize: 20, current: Number(query.offset) }}
>         onChange={(pagination, filters, sorter) => {
>           setQuery({ ...query, offset: pagination.current });
>         }}
>       />
>     </Layout>
>   );
> };
> 
> export default DoctorList;
> ```

点个赞
再提个目前遇到的几个场景
1.列表页面可能带了其他操作，比如编辑 ，编辑的打开方式是通过query的形式 有这个query的时候就弹窗一个编辑窗口(这种情况下可能map到url上的查询条件就受影响了)
2.列表页的编辑是跳转到了一个新的路由页面
2.1 用户可能通过浏览器的回退 这样能正常回到之前的查询状态(因为url上本身就有那些参数)
2.2 用户可能点的是编辑页面中用户放置的"返回"按钮 
  对于2.2这种情况 是不是额外考虑下 由用户定义存储到本地(比如sessionStorage) 然后用户返回的时候根据自己useFormTable时候提供的cacheKey去sessionStorage里面找到之前的值 再通过路由切换过去

这是我的想法，想听听大佬们的建议

**Comment by xiexingen** [comment]
useHistory()
哪来的

**Comment by YanYuanFE** [comment]
> useHistory()
> 哪来的

加上了
