### ISSUE TITLE
useSessionStorageState拿到的值是数字类型，导致内容错误

### ISSUE THREAD

**Issue by Leonw26** [alibaba/hooks#2330]
测试版本：
ahooks: 3.7.6
React: 18.2.0

使用useSessionStorageState读取一串数字字符串，则返回的值是数字类型，如果数字字符串太长，则返回内容不是期望的内容。

按理来说sessionStorage存储的是字符串，useSessionStorageState返回的值也应该是字符串才对。

[codesandbox demo](https://codesandbox.io/s/agitated-faraday-s5gmcv?file=/src/App.js)

**Comment by liuyib** [comment]
完全使用 `useSessionStorageState` 写和读，没有这个问题。你把原生的 `sessionStorage` 和 `useSessionStorageState` 混着用，可以按照文档来处理下序列化：

https://ahooks.js.org/zh-CN/hooks/use-local-storage-state/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BA%8F%E5%88%97%E5%8C%96%E5%92%8C%E5%8F%8D%E5%BA%8F%E5%88%97%E5%8C%96%E5%87%BD%E6%95%B0

![image](https://github.com/alibaba/hooks/assets/38221479/24e3c9eb-db5c-4185-ade5-cc63d66df109)

---

相关 issue: https://github.com/alibaba/hooks/issues/412

由于要支持对象类型的数据存取，所以，默认需要进行 stringify/parse，见：https://github.com/alibaba/hooks/issues/412#issuecomment-641006359

如果需要禁用这一行为，可以自定义序列化和反序列化的行为。

**Comment by liuyib** [comment]
我认为问题已经解了，有问题继续评论，issue 先关了~
