### ISSUE TITLE
feature: The throttle function should remove the default 1000 milliseconds to support the use of requestAnimationFrame

### ISSUE THREAD

**Issue by zhe-he** [alibaba/hooks#2331]
Hello, I have a requirement in my React project to throttle using requestAnimationFrame. I noticed that lodash natively supports it, but ahooks has added extra logic to set a default time of 1000 milliseconds. Here are the links to the two relevant source code sections:
1. [Lodash throttle source code](https://github.com/lodash/lodash/blob/main/src/debounce.ts#L78)
2. [ahooks source code](https://github.com/alibaba/hooks/blob/5412bb719de1666ff2e947dfa3e1d231b7f9746f/packages/hooks/src/useThrottleFn/index.ts#L20C16-L20C29)

**Comment by crazylxr** [comment]
你可以把 wait 设置为 0 来实现你的需求

**Comment by liuyib** [comment]
https://github.com/lodash/lodash/blob/main/src/debounce.ts#L77-L78

![image](https://github.com/alibaba/hooks/assets/38221479/e5fdc22c-546c-456d-88d1-238016e7c584)

@crazylxr 见哥，这里 wait 设置 0 恰好是绕过 requestAnimationFrame，需要 ahooks 支持用户设置 wait 为 undefined 来启用 requestAnimationFrame 的，你再看下呢~

**Comment by liuyib** [comment]
solved: https://github.com/alibaba/hooks/pull/2332
