### ISSUE TITLE
useWebSocket全局只创建一个实例，怎么在其他组件内发送接收消息？

### ISSUE THREAD

**Issue by chengshaohui** [alibaba/hooks#2338]
请教一下，我使用useWebSocket 在根组件创建一个实例，怎么在子组件内接收和发送消息？

把实例赋值给redux吗？ 还是在根组件通过 context 更新传递的数据？还是有其他什么办法？

**Comment by liuyib** [comment]
> 把实例赋值给redux吗？ 还是在根组件通过 context 更新传递的数据？

是这样，目前只能透传实例
