### ISSUE TITLE
useAntdTable的第2个demo“排序与筛选”有bug

### ISSUE THREAD

**Issue by GeraltX** [alibaba/hooks#234]
地址：
https://hooks.umijs.org/zh-cn/useAntdTable#%E6%8E%92%E5%BA%8F%E4%B8%8E%E7%AD%9B%E9%80%89

重现步骤：
1. 先点击phone排序，点3次，使它回到没排序的状态
2. 再点击第2页，此时在f12-network中可以看到还是请求第1页的数据

看了下是因为sorter一开始是{}，空对象，点击排序之后变成了有field字段的对象。
再点换页时，又变回了空对象，这时内部判断field变了，所以自动回到了第一页。

**Comment by hfuuss** [comment]
这个 貌似是 Table的 bug。 第三次置空的时候， sorter对象变成了{field: "phone", columnKey: "phone"} 。切换分页的时候，sorter对象变成了{ }，所以俩次 field不一样，导致重复了。

**Comment by brickspert** [comment]
v1.6.0 发布了最新的 [useRequest](https://hooks.umijs.org/zh-CN/async?anchor=%E5%88%86%E9%A1%B5) ，应该解决了这个问题。
