### ISSUE TITLE
功能问题， useRequesst 能不能暴露修改loading状态的方法 

### ISSUE THREAD

**Issue by PengQingYao** [alibaba/hooks#2342]
一个可编辑Table，使用useAntdTable,。 当前表格数据可以删除，我希望在删除某一行数据时（异步调用其他的接口）， 当前表格设置 loading状态。 但是loading状态外部没办法控制。 

有其他的办法吗？

**Comment by 2048920439** [comment]
可以自己加一个loading,然后loading = {loading || antdTable.loading} 就可以了啊

**Comment by crazylxr** [comment]
楼上正解
