### ISSUE TITLE
[useControllableValue]: defaultValue 有值,但是state 仍为undefined

### ISSUE THREAD

**Issue by vaynevayne** [alibaba/hooks#2349]
```jsx
  const [config, setConfig] = useControllableValue({
      value,
      onChange,
      defaultValue,
    })
```

ahooks: 3.7.4

<img width="1070" alt="image" src="https://github.com/alibaba/hooks/assets/124666577/8b0bb89d-1218-40f1-b09b-e0df89827194">

<img width="675" alt="image" src="https://github.com/alibaba/hooks/assets/124666577/4e9db93d-b563-4a47-91df-323d7168519c">

**Comment by liuyib** [comment]
你传入了 value，说明处于受控状态下，而你传入的 value 是 undefined，返回的自然也是 undefined:

![image](https://github.com/alibaba/hooks/assets/38221479/907e279b-01c7-4d7f-83c0-5a8cec5e6abf)

**Comment by vaynevayne** [comment]
`const isControl = value !== undefined `,这正好是非受控的标志啊, 这算是业界标准吧 
这个时候应该 是 config =  defaultValue

**Comment by liuyib** [comment]
> `const isControl = value !== undefined `,这正好是非受控的标志啊, 这算是业界标准吧

1. 你主动传了 value 参数，就说明你要控制组件，不会检测 undefined, null 的。

> 这个时候应该 是 config = defaultValue

2. 受控模式下，不会替用户处理数据，否则就不叫“受控”模式了，其次如果像你所说 `config = defaultValue` 又该有人说，为什么受控模式下还要替用户处理数据？

**Comment by vaynevayne** [comment]
你们这个 hook 怎么用? 

假设我想封装一个通用的组件, 内部使用你这个 hook , 那么我得封装两个组件?
  value 一个, defaultValue 一个?

**Comment by liuyib** [comment]
以你的截图代码来说，你用传的 defaultValue 处理下传的 value 不就解决 value 默认为 undefined 的问题了，然后 value 再传给 useControllableValue 就没问题了
