### ISSUE TITLE
容器的子元素进行双指放大缩小，导致该容器的useLongPress频繁触发

### ISSUE THREAD

**Issue by pzm666** [alibaba/hooks#2350]
移动端，我监听容器的长按事件，对容器里的内容进行双指放大操作，会频繁触发监听useLongPress

**Comment by liuyib** [comment]
麻烦给提供个可复现的在线 demo，我回头测试下

**Comment by pzm666** [comment]
> 麻烦给提供个可复现的在线 demo，我回头测试下

好的，等项目上线了，再来探讨下；目前我找了个临时的解决方案。

**Comment by crazylxr** [comment]
那这个 issue 先 close
