### ISSUE TITLE
在使用 useAntdTable时 打印 params 重复

### ISSUE THREAD

**Issue by BuyTmall** [alibaba/hooks#2363]
在使用 useAntdTable这个 hook的时候, 打印从 useAntdTable 结构出来的 params, 会重复打印好几次, 而且打印的结果是一样的, 我从网上找并没有这方面的解释, 是不是源码设计的问题, 我提一个疑惑

**Comment by BastKakrolot** [comment]
请提供一个最小可复现的codeSandBox，以供定位问题
