### ISSUE TITLE
useKeyPress hook should support a way to filter out input, textarea, contenteditable

### ISSUE THREAD

**Issue by websiddu** [alibaba/hooks#2364]
When implementing keyboard shortcuts for an App, we should filter keyboard events from input, textarea, contenteditable, select etc... 

Please provide an option to filter out this element.

**Comment by BastKakrolot** [comment]
I think filtering is not needed, but the return method is used to control the opening and closing of the response, which can be handled more flexibly.
what you think？

**Comment by liuyib** [comment]
Hi @websiddu , please see: https://github.com/alibaba/hooks/pull/2365, I think this is a more general way to solve your problem. Is that right?

**Comment by websiddu** [comment]
In my code today, 
```js
export const isInputElement = (el: any) => {
  if (!el) return false;

  const tagName = el.tagName.toLowerCase();
  const inputTypes = ["input", "textarea", "select"];
  if (inputTypes.includes(tagName)) return true;

  return false;
};
```

```js
useKeyPress("n", (e: any) => {
    if (isInputElement(e.target)) return;
    createNew();
  });
  
```
The above works for me. 

But I feel the default behavior should be that, when focused on a text input it shouldn't bubble the events, to parents unless its explicitly said so.  


And finally I'm curious on how will the `observe` prop going to help in my case?

**Comment by BastKakrolot** [comment]
I don't think this point of view is correct. For example, the editor has many shortcut keys. We should focus on the hooks themselves and should not bind them to the actual scene.

Therefore, I think we can deal with more scenarios by letting go of control and handing it over to users.

```jsx
const Demo = () => {
    const [observe,{setFalse,setTrue}] = useBoolean(true)
    useKeyPress("n", callback, {
        observe
    });
    return <Input onFocus={setFalse} onBlur={setTrue} />;
};
```

**Comment by liuyib** [comment]
@websiddu In your case, your code is more suitable and simple, but it seems to be solving a specific problem.

I imagined a similar case: "The engineer wants to set [Shift + v] to paste in some textarea and [Shift + w] not to be fire in textarea", In this situation, it is inappropriate to activate or deactivate hotkeys within the textarea.

So I'm sorry, the logic for filtering input elements won't be built into ahooks here. Do you have any other ideas? Please feel free to discuss them here.

---

By the way, your code can be simpler to solve your problem:

```tsx
useKeyPress("n", (e: any) => {
    if (document.querySelector(':focus')) return;
    createNew();
});
```

**Comment by websiddu** [comment]
That is totally cool. Thanks for your work here. 

`if (document.querySelector(':focus')) return; ` this seems to be an elegant solution. I will try it out.
