### ISSUE TITLE
在umi max 项目中使用ahooks 报错TypeError: Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by Lands-1203** [alibaba/hooks#2366]
![image](https://github.com/alibaba/hooks/assets/61341868/9dcfb1cb-dee5-4ffd-b247-550aa6bb40d6)
![image](https://github.com/alibaba/hooks/assets/61341868/e72b4408-301a-41da-a571-f55ea4836e58)
    "@ant-design/icons": "^4.8.1",
    "@ant-design/pro-components": "^2.6.35",
    "@ant-design/use-emotion-css": "1.0.4",
    "@huize/react-components": "^0.1.17",
    "@umijs/route-utils": "^2.2.2",
    "ahooks": "^3.7.8",
    "antd": "^5.11.1",
    "classnames": "^2.3.2",
    "dayjs": "^1.11.10",
    "lodash": "^4.17.21",
    "react": "^18.2.0",
    "react-cropper": "^2.3.3",
    "react-dev-inspector": "^1.9.0",
    "react-dom": "^18.2.0",
    "react-json-view": "^1.21.3"

**Comment by Lands-1203** [comment]
![image](https://github.com/alibaba/hooks/assets/61341868/cd98d2cb-3a6f-4245-a490-a2596e8fad9a)

**Comment by jinxiangqiang** [comment]
我也遇到这个问题了

**Comment by liuyib** [comment]
> 我也遇到这个问题了

试了下，没有复现。

这是我使用的依赖版本：

```json
"dependencies": {
    "@ant-design/icons": "^5.0.1",
    "@ant-design/pro-components": "^2.4.4",
    "@umijs/max": "^4.2.8",
    "ahooks": "^3.8.0",
    "antd": "^5.4.0"
  }
```

如果还有问题，麻烦提供个可复现的在线 demo @jinxiangqiang

**Comment by Lands-1203** [comment]
> > 我也遇到这个问题了
> 
> 试了下，没有复现。
> 
> 这是我使用的依赖版本：
> 
> ```json
> "dependencies": {
>     "@ant-design/icons": "^5.0.1",
>     "@ant-design/pro-components": "^2.4.4",
>     "@umijs/max": "^4.2.8",
>     "ahooks": "^3.8.0",
>     "antd": "^5.4.0"
>   }
> ```
> 
> 如果还有问题，麻烦提供个可复现的在线 demo @jinxiangqiang

试一下antd pro cli构建项目
可能是pro内部使用了ahooks导致的，之前我在没有导入ahooks的时候，可以从某个包导入某些方法
