### ISSUE TITLE
调用cancel无法中断axios请求，请问如何才能停止axios请求

### ISSUE THREAD

**Issue by xian107** [alibaba/hooks#2371]
当接口请求还没返回的时候，又执行了一次页面搜索，怎么取消先前的请求

**Comment by hchlq** [comment]
cancel 是无法中断 axios 请求的，他只能中断 promise 的请求。

useRequest 也只负责管理 promise 的请求，如果需要中断 axios 的请求，需要业务自己处理

**Comment by BoyXuanzai** [comment]
想问问楼主最后的解决方案是什么
