### ISSUE TITLE
useCountDown 在压后台时，不执行 onEnd 

### ISSUE THREAD

**Issue by JackGuiYang12** [alibaba/hooks#2374]
想了解一下 useCountDown 内部使用 setInterval 的原因是什么？因为在大部分时候，setInterval 的问题会比 setTimeout 多

**Comment by liuyib** [comment]
应该不是 setInterval 的问题，看了下内部剩余时间的计算函数，
https://github.com/alibaba/hooks/blob/978cb2289cb47f76f4744c3827c934ed6bd291d2/packages/hooks/src/useCountDown/index.ts#L23-L30

参数 `TDate` 的类型如下，

<img width="600" alt="image" src="https://github.com/alibaba/hooks/assets/38221479/64d81d2d-f7ce-4e10-b7f2-a33c12b0646d">

当输入无法转数字的字符串、null 时，`dayjs(target).valueOf()` 会得到结果 `NaN`，而结果等于 0 才会调用 onEnd：

https://github.com/alibaba/hooks/blob/978cb2289cb47f76f4744c3827c934ed6bd291d2/packages/hooks/src/useCountDown/index.ts#L70-L72

应该是 `calcLeft` 函数的计算结果出现 `NaN` 导致的。不过上述都是猜测，还是得复现才能准确定位问题。

你的问题能否复现呢？不复现的话，也没法做测试 @JackGuiYang12
