### ISSUE TITLE
useRequest 增加 ConfigProvider

### ISSUE THREAD

**Issue by LaamGinghong** [alibaba/hooks#2375]
可否增加一个全局通用配置呢？比方说平台所有请求都增加轮询这种 case。设计上不一定非要使用 Context 来做，放到一个全局 store 也可以

**Comment by conorzhong** [comment]
+1，类似 SWRConfig

**Comment by BastKakrolot** [comment]
这种情况应该自行封装一层useRequest,没有必要增加Provider

**Comment by crazylxr** [comment]
我目前赞成 @BastKakrolot 的说法，后面我拿出来大家投投票看看

**Comment by LaamGinghong** [comment]
@BastKakrolot @crazylxr 以 js 的角度没啥问题，但是考虑到 ts 类型的复杂度，封装的难度其实不低

**Comment by crazylxr** [comment]
> @BastKakrolot @crazylxr 以 js 的角度没啥问题，但是考虑到 ts 类型的复杂度，封装的难度其实不低

是的，这也是 v2 -> v3 的时候删除的原因。这个就增加了
