### ISSUE TITLE
The official website shows 503 Service Unavailable

### ISSUE THREAD

**Issue by SkyeYoung** [alibaba/hooks#2380]
<img width="462" alt="image" src="https://github.com/alibaba/hooks/assets/48400568/e2f91ee0-0c3d-406c-b889-0ff15fbe4b36">

**Comment by chiga0** [comment]
this site is available now.
https://ahooks.gitee.io/

**Comment by SkyeYoung** [comment]
Thx! https://ahooks.js.org/ looks like it's accessible as well
