### ISSUE TITLE
【useRequest】当设置` manual: true` 时，然后设置`refreshDeps` 不生效

### ISSUE THREAD

**Issue by chiga0** [alibaba/hooks#2381]
Demo地址：https://codesandbox.io/s/spring-cherry-6l65sx

在`useRequest` 或 `usePagination` 中，当开启`manual: true` 时，如果同时设置了 `refreshDeps: [xxx]` ，此时状态变化不会触发重新执行。

我的期望（我以为的）：
`manual: true`仅负责首次加载是否自动渲染，后续状态变化引起的重渲染应该生效才对。
另外，从文档中好像没看到这两个设置项是互斥的。

**Comment by Atw-Lee** [comment]
manual打开应该就是需要手动run、refresh吧。只能监听deps，然后手动refresh

**Comment by crazylxr** [comment]
楼上正解。

**Comment by chiga0** [comment]
嗯，之前确实没了解到，建议在`manual `属性文档中说明一下就更清楚了。

**Comment by liuyib** [comment]
> 嗯，之前确实没了解到，建议在`manual `属性文档中说明一下就更清楚了。

感谢建议，已发起 PR 处理了
