### ISSUE TITLE
useHover当hover状态展示一个输入框时，输入中文时会切换到展示非hover状态的元素

### ISSUE THREAD

**Issue by changjiah** [alibaba/hooks#2385]
useHover当hover状态展示的元素为一个输入框时，输入中文时会切换到展示非hover状态的元素。
我的理解是输入还没结束，不应该定位为取消hover状态。
我自己尝试用onMouseEnter和onMouseLeave来做hover效果时，也遇到了同样的情况，怀疑是onMouseLeave监听将中文输入时的字母间的间断视为失焦

**Comment by hchlq** [comment]
尝试了下，没有复现，可以看看这个 [demo](https://codesandbox.io/p/sandbox/chuan-ru-dom-yuan-su-forked-7pscp9?file=%2FApp.tsx%3A13%2C40)

**Comment by changjiah** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件已收到，我会尽快给您回复。

**Comment by changjiah** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件已收到，我会尽快给您回复。

**Comment by liuyib** [comment]
不建议用 hover 状态做复杂交互（如输入），antd 的 Popover 也有[这个问题](https://github.com/ant-design/ant-design/issues/46874#issuecomment-1884511199)，不处理哈~ 建议改成稳定的触发方式（click 触发 + 受控展示弹框）来做复杂交互
