### ISSUE TITLE
useAntdTable 设置默认分页大小后，切换分页大小，原来设置的pagesize被重置了

### ISSUE THREAD

**Issue by rxitaishen** [alibaba/hooks#2393]
# 重现
官网的demo就可以重现
<img width="1192" alt="image" src="https://github.com/alibaba/hooks/assets/60890238/cef631d1-36e8-40a3-8e46-b44a5a43c194">

点击10条每页

<img width="1195" alt="image" src="https://github.com/alibaba/hooks/assets/60890238/0b114675-8068-4fa5-bcfb-fd920bd38a73">

发现没有5条每页的选项了

**Comment by hchlq** [comment]
antd 默认就是这样的，不应该在我们这处理哈，可以看看这个 [demo](https://codesandbox.io/p/sandbox/geng-duo-antd-5-12-4-forked-lw8sdt?file=%2Fdemo.tsx%3A8%2C1)
