### ISSUE TITLE
useRequest的问题

### ISSUE THREAD

**Issue by xiexingen** [alibaba/hooks#240]
import { useRequest } from '@umijs/hooks';
这个useRequest在@umijs/hooks中是不存在的，实际是在@umijs/use-request，这个有必要单独拆成一个库吗

**Comment by brickspert** [comment]
存在的吧。你没升级吧？ v1.6.0

**Comment by xiexingen** [comment]
> 存在的吧。你没升级吧？ v1.6.0

哦 版本问题 是可以的
