### ISSUE TITLE
官网很卡！

### ISSUE THREAD

**Issue by duobancc** [alibaba/hooks#2400]
这个资源堵住了
![image](https://github.com/alibaba/hooks/assets/37232082/b63eb447-e5c4-4b48-adaf-e8ef013e226f)

**Comment by 1587315093** [comment]
试试国内镜像怎样
https://ahooks.gitee.io/zh-CN

**Comment by duobancc** [comment]
> 试试国内镜像怎样 https://ahooks.gitee.io/zh-CN
也是同样情况
![image](https://github.com/alibaba/hooks/assets/37232082/1d76b4bf-690a-45ba-a5f5-0c92cfb3c89a)

**Comment by crazylxr** [comment]
没遇到过这种情况，官网是国外的，最近有点不太稳，建议用 国内镜像
