### ISSUE TITLE
v2 官网文档样式错乱

### ISSUE THREAD

**Issue by zouwenhao03** [alibaba/hooks#2402]
![image](https://github.com/alibaba/hooks/assets/93810173/4f9cdbec-211c-4a78-aee1-899c3cd7e0b8)

**Comment by crazylxr** [comment]
没看懂什么问题？

**Comment by liuyib** [comment]
> 没看懂什么问题？

应该是指官网样式出问题了，文字覆盖在 header 上面了

**Comment by liuyib** [comment]
@zouwenhao03 能稳定复现吗？

如果不能复现，等 dumi 等级到 v2 吧，但是好奇怪，为什么 v1 文档这么久了才有人遇到？难道是被插件影响了？

**Comment by liuyib** [comment]
复现了，这是旧版官网：
![image](https://github.com/alibaba/hooks/assets/38221479/829f9535-3f66-4f80-980e-23e907657798)
https://ahooks-v2.js.org/zh-CN/

**Comment by liuyib** [comment]
@crazylxr v2 的官方样式错乱，还要处理吗？
