### ISSUE TITLE
I issued an error when I upgraded react-router-dom to 6.21.0

### ISSUE THREAD

**Issue by sixdjango** [alibaba/hooks#2413]
```js
// This is under the route component
import useUrlState from '@ahooksjs/use-url-state'

useUrlState()
```
error: useLocation() may be used only in the context of a <Router> component

ps: when I back to react-router-dom@6.20.1  It's work

**Comment by flasco** [comment]
https://github.com/remix-run/react-router/issues/11016  
because react-router have multiple version. lock version can solve it. it works for me.

![image](https://github.com/alibaba/hooks/assets/20221600/a3b09de5-fee7-423f-a579-a6f2c9dd7ef8)

**Comment by sixdjango** [comment]
Thinks bro，i will try later
