### ISSUE TITLE
网站崩溃了 返回503

### ISSUE THREAD

**Issue by Zmnortal** [alibaba/hooks#2414]
[
<img width="472" alt="截屏2023-12-21 09 59 37" src="https://github.com/alibaba/hooks/assets/49364497/40a731fa-056d-4ef2-875a-a00c5cf53e04">
](url)

如题
全站奔溃，大约9点半左右开始，之前虽然没有503但是访问也不稳定

**Comment by liuyib** [comment]
可以先访问 Gitee 镜像：https://ahooks.gitee.io/zh-CN

**Comment by Zmnortal** [comment]
> 可以先访问 Gitee 镜像：https://ahooks.gitee.io/zh-CN

帮大忙了 thanks

**Comment by wangyang-o** [comment]
崩溃了+1，12.22 10:00,还挂着

**Comment by hchlq** [comment]
已恢复。
<img width="1907" alt="image" src="https://github.com/alibaba/hooks/assets/60802048/5f8c4639-6214-49c6-b90a-c9adb0737628">
