### ISSUE TITLE
希望useRequest能够新增一个不需要useRequest帮我管理请求结果的选项

### ISSUE THREAD

**Issue by rhydian0x** [alibaba/hooks#2418]
useRequest针对service做了多层处理，如防抖、节流、延迟等，非常好用。
但当想结合全局状态管理比如zustand使用时，就需要维护两个状态，也会导致更新两次。
如果能够新增一个不需要useRequest帮我管理请求结果的选项，感觉非常妙，我可以自行选择在onsucess钩子或其他合适的钩子获取到结果自行管理数据

**Comment by liuyib** [comment]
上代码看看？展示下目前使用的代码方式 @Ivan-hl

**Comment by rhydian0x** [comment]
![image](https://github.com/alibaba/hooks/assets/42164477/ac79ce05-3520-47f3-baba-36752c4cff42)
目前是这样的，注释了@liuyib

**Comment by liuyib** [comment]
目前 useRequest 结合状态库是会有多余的 render，但感觉这不是痛点。“维护两个状态”指的是？示例代码看不出来多维护了状态

**Comment by rhydian0x** [comment]
比如有个点击事件需要调用后端接口，
我希望这个点击事件是被useRequest包装过的，
并且请求接口后返回的数据需要存在状态库进行管理。
那这个时候useRequest内部维护一个data,
状态库维护一个data,就会进行多次rerender @liuyib

**Comment by liuyib** [comment]
> 比如有个点击事件需要调用后端接口， 我希望这个点击事件是被useRequest包装过的， 并且请求接口后返回的数据需要存在状态库进行管理。 那这个时候useRequest内部维护一个data, 状态库维护一个data,就会进行多次rerender @liuyib

这个导致 rerender 的原因知道的，对于用户侧使用复杂度没影响，只是多 render 了一次。一般业务场景多 render 一次是没什么影响的，对于极致追求性能和 render 次数的场景，useRequest 确实做的没那么好，会有多余 rerender。

对于这里结合状态库的场景，想外部自己来控制状态的存储，对于 useRequest 内部更改可能就比较大了，会触发 render 的状态 hook 都不能用了，内部状态全部要用 ref 管理。

感谢反馈，这个 issue 先留着，后续看看其他人意见。

**Comment by FanetheDivine** [comment]
你的需求似乎并不需要使用帮你管理请求的工具，因为你的意图就是只执行一次。另外，我推荐你尝试useSWR管理全局状态或请求

**Comment by crazylxr** [comment]
> 比如有个点击事件需要调用后端接口， 我希望这个点击事件是被useRequest包装过的， 并且请求接口后返回的数据需要存在状态库进行管理。 那这个时候useRequest内部维护一个data, 状态库维护一个data,就会进行多次rerender @liuyib

如果你完全不需要 useRequest 的状态，为啥希望是被 useRequest 包装的呢？
