### ISSUE TITLE
去掉请求失败仍能放回上次的成功数据 

### ISSUE THREAD

**Issue by OShuxin** [alibaba/hooks#2422]
前面的请求成功，后面再次请求且失败时 为能将 data重置为undefined

**Comment by OShuxin** [comment]
是需要什么配置项么

**Comment by liuyib** [comment]
麻烦提供个可复现的在线 demo，或代码示例片段，感谢

**Comment by day-xue** [comment]
在onError 的时候 mutate(undefined)

**Comment by OShuxin** [comment]
是的 可以了 用mutate可以实现
