### ISSUE TITLE
在antdPro中使用ahooks报错Cannot read properties of null (reading 'useState')老师，求解

### ISSUE THREAD

**Issue by mayongkang1** [alibaba/hooks#2437]
![image](https://github.com/alibaba/hooks/assets/94114667/94b3b844-4dcf-4d2e-b241-ec695e6bb19f)
![image](https://github.com/alibaba/hooks/assets/94114667/037506ca-2bf8-4f14-8c47-8d01a2402ca2)
老师，求解

**Comment by coding-ice** [comment]
最好提供个复现仓库吧，不然不好排查

**Comment by crazylxr** [comment]
@mayongkang1 来个可复现的 demo

**Comment by liuyib** [comment]
读不到 React 上的方法，应该是依赖的问题，一般我会尝试以下几个步骤排查：
1. 删除 node_modules 重装、重启
2. 看报错截图，引用了 development 的 React，挺奇怪的，估计项目里存在多个 React 实例。打包工具中配置下 alias 指向同一个 React（你在调试 React 源码那另说）

	```js
	alias: {
	  react: path.resolve(process.cwd(), './node_modules/react'),
	  'react-dom': path.resolve(process.cwd(), './node_modules/react-dom'),
	},
	```

还不行的话，就不知道了，，需要排查

**Comment by mayongkang1** [comment]
> 读不到 React 上的方法，应该是依赖的问题，一般我会尝试以下几个步骤排查：
> 
> 1. 删除 node_modules 重装、重启
> 2. 看报错截图，引用了 development 的 React，挺奇怪的，估计项目里存在多个 React 实例。打包工具中配置下 alias 指向同一个 React（你在调试 React 源码那另说）
>    ```js
>    alias: {
>      react: path.resolve(process.cwd(), './node_modules/react'),
>      'react-dom': path.resolve(process.cwd(), './node_modules/react-dom'),
>    },
>    ```
> 
> 还不行的话，就不知道了，，需要排查

感谢大佬已经找到原因了，因为是使用了antdPro+umi，所以下载后的依赖可能没有即时更新，删除了.umi文件重新生成就可以了
