### ISSUE TITLE
what's the initialData option for useRequest in v3?

### ISSUE THREAD

**Issue by nathantew14** [alibaba/hooks#2440]
I see that v2 useRequest used to offer an initialData option:
https://ahooks-v2.js.org/hooks/async/#params

Is there something like that in v3?

Thanks.

**Comment by GetWebHB** [comment]
You can try this.
```tsx
const { data } = useRequest(getUserName)
const d = data ?? 'defaultData'
```

**Comment by letehaha** [comment]
If I got you correctly, you can just do it like that, when it comes to initial/default data. Works pretty much the same, cause useRequests returns exactly `ReturnType<T> | undefined`
```js
const { data = [] } = useRequest(...)
```

**Comment by nathantew14** [comment]
> If I got you correctly, you can just do it like that, when it comes to initial/default data. Works pretty much the same, cause useRequests returns exactly `ReturnType<T> | undefined`
> 
> ```js
> const { data = [] } = useRequest(...)
> ```

@letehaha i guess that works, thanks
