### ISSUE TITLE
useInViewport行为与文档不一致，期望更新小版本

### ISSUE THREAD

**Issue by evanryuu** [alibaba/hooks#2441]
**问题描述：**

复制文档的[监听内容滚动选中菜单](https://ahooks.js.org/zh-CN/hooks/use-in-viewport#%E7%9B%91%E5%90%AC%E5%86%85%E5%AE%B9%E6%BB%9A%E5%8A%A8%E9%80%89%E4%B8%AD%E8%8F%9C%E5%8D%95)源码到项目中，会报错 

`TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.`

且TS类型也有问题。

<img width="903" alt="image" src="https://github.com/alibaba/hooks/assets/55378595/07c57acd-c154-4e97-aab9-8d840891598f">

Reproduction: [CodeSandbox](https://codesandbox.io/p/devbox/xzvqnq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrc7ktec00063b6i1gup25f9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrc7ktec00023b6ijn8x9lpf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrc7ktec00033b6iu43wwrzf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrc7ktec00053b6i6l7tvm4l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrc7ktec00023b6ijn8x9lpf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrc7ktec00013b6igcwf8ken%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrc7ktec00023b6ijn8x9lpf%2522%252C%2522activeTabId%2522%253A%2522clrc7ktec00013b6igcwf8ken%2522%257D%252C%2522clrc7ktec00053b6i6l7tvm4l%2522%253A%257B%2522id%2522%253A%2522clrc7ktec00053b6i6l7tvm4l%2522%252C%2522activeTabId%2522%253A%2522clrc7n7r1008o3b6iy14ctphz%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clrc7n7r1008o3b6iy14ctphz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clrc7ktec00033b6iu43wwrzf%2522%253A%257B%2522id%2522%253A%2522clrc7ktec00033b6iu43wwrzf%2522%252C%2522activeTabId%2522%253A%2522clrc7lpfw00313b6icwnqowjn%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrc7lpfw00313b6icwnqowjn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrc7lpnt000megki3hrr8yvu%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clrc7n1g800623b6igpb0u3s6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

看了下这个PR #2061 是已经被合并了的，只不过目前还没发版，请问下最近有计划更新3.7.9吗？还是需要等到4.0一起更新呢😄

**期望效果：**

更新小版本，与文档一致。

**Comment by lq782655835** [comment]
+1，期望尽早发版

**Comment by crazylxr** [comment]
3.7.9 已发布
