### ISSUE TITLE
useDynamicList动态表单使用antd4.0 默认值无法生效

### ISSUE THREAD

**Issue by whatthehan** [alibaba/hooks#245]
代码复现地址：https://codesandbox.io/s/winter-morning-qon5s?fontsize=14&hidenavigation=1&theme=dark
问题说明：使用useDynamicList创建动态表单，不管是在Form，还是initialValue里声明了初始值都没有任何效果，不知道是我的写法问题还是与antd 4.0不兼容，辛苦大佬帮忙看一下啦[](url)

**Comment by ttys026** [comment]
antd 4 修改了动态表单的方法，官网上也增加了一个[例子](https://next.ant.design/components/form-cn/#components-form-demo-dynamic-form-item)

如果希望使用 useDynamicList，可以采用这种写法：
https://codesandbox.io/s/bitter-forest-iy6j6
