### ISSUE TITLE
[RFC] 感觉useFormTable里面使用cacheKey没什么实际用途

### ISSUE THREAD

**Issue by xiexingen** [alibaba/hooks#246]
感觉表格这种，一般缓存也是缓存搜索条件、页码、排序的列这些，当浏览器刷新或者从内部页面返回的时候可以恢复到之前的搜索页面；
看目前cacheKey是直接传给了useRequest，对api的数据进行了缓存；感觉这对table并没太大意义

**Comment by brickspert** [comment]
这块我们支持下搜索条件缓存。

**Comment by brickspert** [comment]
https://hooks.umijs.org/antd/use-form-table#data-caching

已经支持了 form 条件的缓存了呀。你看看这个例子。

**Comment by xiexingen** [comment]
> https://hooks.umijs.org/antd/use-form-table#data-caching
> 
> 已经支持了 form 条件的缓存了呀。你看看这个例子。

看到了，谢谢

**Comment by xiexingen** [comment]
想换成到sessionStorage 是不是替换那个变量那块就可以了
