### ISSUE TITLE
useCookieState: Missing option types

### ISSUE THREAD

**Issue by Snazzie** [alibaba/hooks#2462]
it looks like Option only has defaultValue.

React: 18.2.0
Typescript: 5.3.3

```js
  const [_, setToken] = useCookieState("token", {
    defaultValue: "",
    secure:true  // Error: Object literal may only specify known properties, and 'secure' does not exist in type 'Options'.ts(2353)
  });
```

also setToken.newOptions is not typed

![Code_siMHyrmq28](https://github.com/alibaba/hooks/assets/19627023/0d0e083e-29eb-4511-b493-7e5071998597)
![Code_eBEUI0XqwF](https://github.com/alibaba/hooks/assets/19627023/5adee801-13b5-443b-9a32-44c152618f77)

**Comment by crazylxr** [comment]
I have no problem here, please provide an example.   @Snazzie 

<img width="589" alt="image" src="https://github.com/alibaba/hooks/assets/16161407/e1b4be9f-6752-4304-a4c4-c11e189439b6">

**Comment by Glacier-Luo** [comment]
安装`@types/js-cookie`

**Comment by Snazzie** [comment]
> @types/js-cookie

This solved it. @crazylxr   might want to include that dependency with ahooks?
