### ISSUE TITLE
useCookieState SetCookie replaces spaces with %

### ISSUE THREAD

**Issue by Snazzie** [alibaba/hooks#2463]
When setting bearer token into cookies. the function replaces spaces with %

example 
`Bearer token.............................` becomes `Bearer%token.............................`

**Comment by dxsun97** [comment]
`useCookieState` and also it's updater takes two parameters, the second is the `js-cookie` options that you can pass to. As https://github.com/js-cookie/js-cookie?tab=readme-ov-file#encoding metions, it is the default behavior, you can change it.

**Comment by crazylxr** [comment]
@Snazzie 见楼上的回答即可
