### ISSUE TITLE
github actions -发现zeit-now这个actions404啦 部署文档站点的服务挂掉啦

### ISSUE THREAD

**Issue by xiexingen** [alibaba/hooks#248]
Current runner version: '2.164.0'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@master'
Download action repository 'actions/zeit-now@master'
##[warning]Failed to download action 'https://api.github.com/repos/actions/zeit-now/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 20.756 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/actions/zeit-now/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 17.746 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).

**Comment by brickspert** [comment]
你是执行了什么？

**Comment by xiexingen** [comment]
> 你是执行了什么？

不是，是你这个github actions里面的deploy site这个挂了，你可以看日志
