### ISSUE TITLE
Will debounced requests impact performance?

### ISSUE THREAD

**Issue by Orange-C** [alibaba/hooks#2480]
https://github.com/alibaba/hooks/blob/95409bebfa856b07f032f69cba0104f4b968336b/packages/hooks/src/useRequest/src/plugins/useDebouncePlugin.ts#L41

When we debounce requests and use runAsync, we created some ever-pending promises. So I am wondering if this behavior will impact performance when there are many pending promises?

**Comment by crazylxr** [comment]
No need to care
