### ISSUE TITLE
useMeomoizeFn缓存的debounce函数失效

### ISSUE THREAD

**Issue by fashen007** [alibaba/hooks#2484]
在使用 `useMeomoizeFn` 函数情况下，如 

```
const clickhandle = useMeomoizeFn(debounce(() => {//dosth }, 2000, {leading: true, training: false}))
// ... 其他多余的代码注释
return <div onclick= {clickhandle}> </div>
```

组件在重新渲染的过程中 ，onclick拿到的 函数引用确实是没有变化的，但是`memoizedFn.current` 中消费的 `fnRef.current` 导致`debounce`在每次一重新渲染中会被更新成新的引用

这个场景是不是一直都存在问题的

**Comment by crazylxr** [comment]
一直存在，这个 hook 就是这么设计的，仅用于缓存函数引用
