### ISSUE TITLE
useRequest  自定义刷新行为 搭配ready，ready时第一次的参数不生效。

### ISSUE THREAD

**Issue by mmmml-zhao** [alibaba/hooks#2490]
场景：开始没有用户id ，不请求用户信息，获得用户id后，ready为true，获取用户信息，然后切换用户id都会触发获取用户信息接口。
因为接口在多个页面使用，所以参数从run函数的参数里传递。

我能理解ready为true时，其实走的是hook的请求，不是 自定义刷新行为的请求，但是就很怪。感觉两边逻辑都不是特别对。

另外当从run函数传递参数的时候，感觉hook 只能手动触发，怎么怎么的别扭。

https://codesandbox.io/p/sandbox/zi-ding-yi-shua-xin-xing-wei-forked-zxqdhr?file=%2FApp.tsx%3A21%2C19-21%2C25

<img width="1000" alt="image" src="https://github.com/alibaba/hooks/assets/25151442/c087c951-b16b-4b56-9e1a-2523ad829f23">

**Comment by crazylxr** [comment]
你这个 case 我建议直接把 ready 干掉就行了。只用 refreshDeps 即可。当 userId 没有的时候因为没有发生变化，所以也不会请求。

**Comment by mmmml-zhao** [comment]
把ready干掉，则会自动执行一次（感觉是走的默认的自动触发），当userId变化，才会过refreshDepsAction。

https://codesandbox.io/p/sandbox/zi-ding-yi-shua-xin-xing-wei-forked-zxqdhr?file=%2FApp.tsx%3A21%2C27

<img width="1135" alt="image" src="https://github.com/alibaba/hooks/assets/25151442/6dab60f0-615c-49b4-b6ae-c5f1f788b2e7">

**Comment by liuyib** [comment]
@mmmml-zhao  

见 ready 参数文档：
https://ahooks.gitee.io/zh-CN/hooks/use-request/ready

![image](https://github.com/alibaba/hooks/assets/38221479/d044eef3-3293-4c39-b6b4-c71606c54cb5)

你这里没有设置 manual 参数，说明处于自动模式，ready false -> true 时会发起请求，**注意此时发起的请求携带的参数是 defaultParams**，你没传 defaultParams 所以 id 第一次为 undefined，表现正常。

你需要这样使用：

![image](https://github.com/alibaba/hooks/assets/38221479/b5f6ebec-36e1-4b29-971d-21ba4c19e6b5)

简单来说 ready 一般和 defaultParams 配合使用。

----

除了第一次发起请求由 ready 来控制，之后 userId 变动由 refreshDeps 控制，见上图下面的一组红框。

----

> 我能理解ready为true时，其实走的是hook的请求，不是 自定义刷新行为的请求，但是就很怪。感觉两边逻辑都不是特别对

自动模式下（manual: false），ready false -> true 会自动触发一次请求，refreshDeps 里的 userId 变动也会触发一次请求，那么第一次请求时，两者都触发一次请求，你感觉这正常吗？肯定只能触发一次的，否则有冗余请求。

> 另外当从run函数传递参数的时候，感觉hook 只能手动触发，怎么怎么的别扭

这句话，你可以把 run 放在任何想请求的地方，它本来就是提供给你**手动触发一次**的能力，你想通过 run 自动触发，包在 useEffect 里，或者怎么着都可以。

**Comment by mmmml-zhao** [comment]
> @mmmml-zhao
> 
> 见 ready 参数文档： https://ahooks.gitee.io/zh-CN/hooks/use-request/ready
> 
> ![image](https://private-user-images.githubusercontent.com/38221479/310030147-d044eef3-3293-4c39-b6b4-c71606c54cb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjY0NDYsIm5iZiI6MTcwOTYyNjE0NiwicGF0aCI6Ii8zODIyMTQ3OS8zMTAwMzAxNDctZDA0NGVlZjMtMzI5My00YzM5LWI2YjQtYzcxNjA2YzU0Y2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA4MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiZTlkOWZkNWQwN2MwMTczZjE4OGY2ZWRmZjdkNzhhNzk5MDMyYWRkMDE1Y2E2NzgwNmNmNzdlNWY3ZDE4ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CzeKFbcFZGrbW1BOYqSrsPRCARhDELrPcFkQGW4csns)
> 
> 你这里没有设置 manual 参数，说明处于自动模式，ready false -> true 时会发起请求，**注意此时发起的请求携带的参数是 defaultParams**，你没传 defaultParams 所以 id 第一次为 undefined，表现正常。
> 
> 你需要这样使用：
> 
> ![image](https://private-user-images.githubusercontent.com/38221479/310029806-b5f6ebec-36e1-4b29-971d-21ba4c19e6b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjY0NDYsIm5iZiI6MTcwOTYyNjE0NiwicGF0aCI6Ii8zODIyMTQ3OS8zMTAwMjk4MDYtYjVmNmViZWMtMzZlMS00YjI5LTk3MWQtMjFiYTRjMTllNmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA4MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMDVlYjliOGMxNTQxYmQwMzllYTQxYjNkNDk2ZDI2NzM3OTE0YjhiNTJmYmZiNGI1OWYyMjIxMzYxZTc3NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8NnSHEmf8lzgJVLB58aupZaDTbJVy8adp250detg3l0)
> 
> 简单来说 ready 一般和 defaultParams 配合使用。
> 
> 除了第一次发起请求由 ready 来控制，之后 userId 变动由 refreshDeps 控制，见上图下面的一组红框。
> 
> > 我能理解ready为true时，其实走的是hook的请求，不是 自定义刷新行为的请求，但是就很怪。感觉两边逻辑都不是特别对
> 
> 自动模式下（manual: false），ready false -> true 会自动触发一次请求，refreshDeps 里的 userId 变动也会触发一次请求，那么第一次请求时，两者都触发一次请求，你感觉这正常吗？肯定只能触发一次的，否则有冗余请求。
> 
> > 另外当从run函数传递参数的时候，感觉hook 只能手动触发，怎么怎么的别扭
> 
> 这句话，你可以把 run 放在任何想请求的地方，它本来就是提供给你**手动触发一次**的能力，你想通过 run 自动触发，包在 useEffect 里，或者怎么着都可以。

懂了，确实少了个`defaultParams `，这样感觉就通了，谢谢
