### ISSUE TITLE
Hydrating from useLocalStorageState

### ISSUE THREAD

**Issue by gabrielOttopia** [alibaba/hooks#2491]
If i am creating a multi screen application and i want them to share similar values, I may use your useLocalStorageState hook. It would be amazing if this hook had an option to "fetch" or update its state instead of only on reload.

**Comment by crazylxr** [comment]
This is a great idea, support for the next version.

**Comment by crazylxr** [comment]
https://github.com/alibaba/hooks/pull/2298

刚看到，已经有这个 PR 了
