### ISSUE TITLE
useVirtualList  与 useInfiniteScroll 结合使用时 调用 reload  VirtualList  没有自动滚动到 顶部

### ISSUE THREAD

**Issue by Jungley8** [alibaba/hooks#2492]
<img width="1154" alt="image" src="https://github.com/alibaba/hooks/assets/20501682/b0329666-dfae-495f-a4c3-312e9ba3ce67">

useVirtualList  与 useInfiniteScroll 结合使用时，如果存在 sticky 元素

滚动几页后， 搜索后 调用 reload 数据减少到 1-2条时， VirtualList  没有自动滚动到 顶部。  

手动 Call  scrollTo 也无效。

**Comment by liuyib** [comment]
麻烦提供个可复现的在线 demo

**Comment by Jungley8** [comment]
[useVirtualList + useInfiniteScroll  demo](https://codesandbox.io/p/sandbox/usevirtuallist-useinfinitescroll-demo-rp27fs)

找到问题了，demo 有说明。 3q

**Comment by CassielLee** [comment]
> [useVirtualList + useInfiniteScroll demo](https://codesandbox.io/p/sandbox/usevirtuallist-useinfinitescroll-demo-rp27fs)
> 
> 找到问题了，demo 有说明。 3q

你好，方便问下你useVirtualList + useInfiniteScroll是怎么结合用的吗？我最近也需要结合用，但是发现会无限出发loadMore，不知道是我哪里用的不对
