### ISSUE TITLE
useLatest是否属于渲染期间修改？

### ISSUE THREAD

**Issue by coding-ice** [alibaba/hooks#2495]
@liuyib 大佬请问一个问题
```
function useLatest(value) {
  const ref = useRef(value);
  ref.current = value;

  return ref;
}
```
https://react.docschina.org/reference/react/useRef#avoiding-recreating-the-ref-contents
通常情况下，在渲染过程中写入或读取 ref.current 是不允许的

允许做法
```
if (signal) {
  ref.current = value
}
```

**Comment by crazylxr** [comment]
合理，理论上可以增加一个变化检测再给 ref.current 赋值。
```javascript
function useLatest(value) {
  const ref = useRef(null);
  if(value !== ref.curent) {
       ref.current = value;
  }
  return ref;
}
```
这样可能更好一点。避免了每次渲染都赋值。

**Comment by coding-ice** [comment]
> 合理，理论上可以增加一个变化检测再给 ref.current 赋值。
> 
> ```js
> function useLatest(value) {
>   const ref = useRef(null);
>   if(value !== ref.curent) {
>        ref.current = value;
>   }
>   return ref;
> }
> ```
> 
> 这样可能更好一点。避免了每次渲染都赋值。

交给我吧，感谢～

**Comment by liuyib** [comment]
关于 React 官方文档里声明的 `Do not write or read ref.current during rendering.` 这个我确实思考了很久很久，说下个人的愚见吧。

原本一直以为一刀切的方式，绝对遵循这个原则就好了，但是业务逻辑中有很多不好绕过的闭包问题，需要 ref 穿透一下，这样做并发模式下可能存在问题，但也立竿见影地把闭包问题解决了，所以有时我们还离不开渲染阶段读写 ref 的操作。

为了拥抱 React 未来，拥抱并发模式，我们要遵循这个原则，但也不是要一刀切的方式去遵循，比如，官方自己也举例了**初始赋值时可以在渲染阶段读写 ref**：https://react.dev/reference/react/useRef#avoiding-recreating-the-ref-contents, 说明只要行为可控，是可以打破上述原则的。

首先，渲染阶段读写 ref 并**直接参与 DOM 渲染**是不允许的，因为函数不再是纯的：
<img width="824" alt="image" src="https://github.com/alibaba/hooks/assets/38221479/4f9d7a29-10b8-49f0-a59d-6123e44520aa">

其次，在“副作用”（side effects，`useEffect`、事件处理程序、定时器等）中读写 ref 是允许的：
<img width="642" alt="image" src="https://github.com/alibaba/hooks/assets/38221479/b469e935-b758-46b5-8cc3-4edca1850529">

所以我认为，**在渲染阶段“写 ref”来保存一个变量的最新引用，并在“副作用”中“读 ref”来穿透闭包，并没有导致不可控，也不会导致函数不纯，只要危险操作被收敛到了“副作用”区域，就是合法的**。

---

回到 `useLatest` 这个 hook，单从逻辑上看，它违背了最上面的原则。但是别忘了这个 hook 的能力定位，它是用来穿透闭包的（或者说绕过闭包问题），所以如果不乱用这个 hook，那么恰好符合了我上面认为的观点（`useLatest` 渲染阶段“写 ref”，我们用它穿透闭包“读 ref”）。举个反面例子：

```tsx
const [count] = useState(0);
// 渲染阶段“写 ref”了（useLatest 内部会写 ref）
const countRef = useLatest(count);

// 然后，又在渲染阶段“读 ref” 了
return <div>{countRef.current}</div>;
```

这个例子在渲染阶段既写 ref，又读 ref，危险操作被收敛到 DOM 上，导致函数不纯，这样肯定是不行的。

总之，`useLatest` 的设计初衷是为了解决闭包问题，并不希望直接参与 DOM 渲染，因此只要不乱用，并不会破坏读写 ref 的规则。

---

转 ahooks 作者大龙哥的建议：useLatest 存函数输入，useMemoizedFn 存函数输出。这样用没什么问题~ 

如果真有问题的话，那就水多了加面，面多了加水，没法一棒子打死。

**Comment by liuyib** [comment]
个人感觉目前 useLatest 的源码不太需要修改，主要是文档需要说明：useLatest 的返回值应该只用于在“副作用”区域解决闭包问题，**不能直接用于 DOM 渲染**。

**Comment by crazylxr** [comment]
额嗯 ,问题不大。这个可以先不改

**Comment by AciGo** [comment]
> 关于 React 官方文档里声明的 `Do not write or read ref.current during rendering.` 这个我确实思考了很久很久，说下个人的愚见吧。
> 
> 原本一直以为一刀切的方式，绝对遵循这个原则就好了，但是业务逻辑中有很多不好绕过的闭包问题，需要 ref 穿透一下，这样做并发模式下可能存在问题，但也立竿见影地把闭包问题解决了，所以有时我们还离不开渲染阶段读写 ref 的操作。
> 
> 为了拥抱 React 未来，拥抱并发模式，我们要遵循这个原则，但也不是要一刀切的方式去遵循，比如，官方自己也举例了**初始赋值时可以在渲染阶段读写 ref**：https://react.dev/reference/react/useRef#avoiding-recreating-the-ref-contents, 说明只要行为可控，是可以打破上述原则的。
> 
> 首先，渲染阶段读写 ref 并**直接参与 DOM 渲染**是不允许的，因为函数不再是纯的： <img alt="image" width="824" src="https://private-user-images.githubusercontent.com/38221479/311771215-4f9d7a29-10b8-49f0-a59d-6123e44520aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDg1OTA3NTcsIm5iZiI6MTc0ODU5MDQ1NywicGF0aCI6Ii8zODIyMTQ3OS8zMTE3NzEyMTUtNGY5ZDdhMjktMTBiOC00OWYwLWE1OWQtNjEyM2U0NDUyMGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTMwVDA3MzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OTc0MWJhNDI4OTdhYjI4N2NjOGRmM2ZkNDkxZTYyZDU5MjM2N2JkYzJkOGRmNzQ1OTA5NDk2YWE5N2YyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HbDlo9XCU3oI5RS29nQHbOahl1j4P3oQJkJsTmTvA24">
> 
> 其次，在“副作用”（side effects，`useEffect`、事件处理程序、定时器等）中读写 ref 是允许的： <img alt="image" width="642" src="https://private-user-images.githubusercontent.com/38221479/311772662-b469e935-b758-46b5-8cc3-4edca1850529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDg1OTA3NTcsIm5iZiI6MTc0ODU5MDQ1NywicGF0aCI6Ii8zODIyMTQ3OS8zMTE3NzI2NjItYjQ2OWU5MzUtYjc1OC00NmI1LThjYzMtNGVkY2ExODUwNTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTMwVDA3MzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYzY5OWUyNDhhMDg4ZWFjMWJmYjNlYWMxM2RkN2MwZjdkM2NlNjI2OTJhMDE0OWQ3NjgzYmQ0NGZmOTk4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9WdkYCsNAhSw64HSF9cZUbJaKbEQ9tSbmRv3gkMqaPU">
> 
> 所以我认为，**在渲染阶段“写 ref”来保存一个变量的最新引用，并在“副作用”中“读 ref”来穿透闭包，并没有导致不可控，也不会导致函数不纯，只要危险操作被收敛到了“副作用”区域，就是合法的**。
> 
> 回到 `useLatest` 这个 hook，单从逻辑上看，它违背了最上面的原则。但是别忘了这个 hook 的能力定位，它是用来穿透闭包的（或者说绕过闭包问题），所以如果不乱用这个 hook，那么恰好符合了我上面认为的观点（`useLatest` 渲染阶段“写 ref”，我们用它穿透闭包“读 ref”）。举个反面例子：
> 
> const [count] = useState(0);
> // 渲染阶段“写 ref”了（useLatest 内部会写 ref）
> const countRef = useLatest(count);
> 
> // 然后，又在渲染阶段“读 ref” 了
> return <div>{countRef.current}</div>;
> 这个例子在渲染阶段既写 ref，又读 ref，危险操作被收敛到 DOM 上，导致函数不纯，这样肯定是不行的。
> 
> 总之，`useLatest` 的设计初衷是为了解决闭包问题，并不希望直接参与 DOM 渲染，因此只要不乱用，并不会破坏读写 ref 的规则。
> 
> 转 ahooks 作者大龙哥的建议：useLatest 存函数输入，useMemoizedFn 存函数输出。这样用没什么问题~
> 
> 如果真有问题的话，那就水多了加面，面多了加水，没法一棒子打死。

@liuyib 大佬，为你的看法点赞，我想请教下，并发模式下会有什么问题（能够举例说明下），我在小伙伴的代码中看到大量的使用以下代码，感觉反模式，求解

```jsx
import React from 'react';

function Test() {
  const [count, setCount] = React.useState(0);
  const paramsRef = React.useRef({});
  paramsRef.current = {
    ...paramsRef.current,
    fun1,
    fun2,
    fun3,
  };

  function fun1() {
    setCount(count + 1);
  }

  function fun2() {
    setCount(count + 1);
  }

  function fun3() {
    setCount(count + 1);
  }

  React.useEffect(() => {
    paramsRef.current.fun1();
  }, []);

  React.useEffect(() => {
    paramsRef.current.fun2();
  }, []);

  React.useEffect(() => {
    paramsRef.current.fun3();
  }, []);

  return <div>{count}</div>;
}

export default Test;

```

上面的示例只是举例，小伙伴们主要是想使用 ref 来跳出 useEffect 的依赖传播，正常来说是使用 useCallback 包裹保持唯一的引用

**Comment by crazylxr** [comment]
别用  useCallback 了，还得写依赖，直接用 useMemoizedFn 包一下就好。

**Comment by AciGo** [comment]
> 别用 useCallback 了，还得写依赖，直接用 useMemoizedFn 包一下就好。

其实我想问这种写法有问题吗？在渲染期间又读又写
```
 const paramsRef = React.useRef({});
  paramsRef.current = {
    ...paramsRef.current,
    fun1,
    fun2,
    fun3,
  };
```

**Comment by liuyib** [comment]
> 其实我想问这种写法有问题吗？在渲染期间又读又写
> 
> ```
>  const paramsRef = React.useRef({});
>   paramsRef.current = {
>     ...paramsRef.current,
>     fun1,
>     fun2,
>     fun3,
>   };
> ```

你的小伙伴的代码原理其实和 useLatest/useMemoizedFn 内部做的原理一样，都是通过渲染期间又读又写 ref 实现保持最新的引用，同时避免触发useEffect。它们的共同限制都是一样的：**ref 引用的值不要直接用于渲染 DOM 就好了**（99%的人也不会这么干，我们基本都是为了穿透闭包/绕过useEffect的触发）。

至于并发模式下有什么问题，我是看了很多React核心团队的人写的 回答/文档/文章 得到的信息，他们说并发模式下有问题，具体例子他们也没给过，我也没试验过。
