### ISSUE TITLE
关于useSelections的一个想法

### ISSUE THREAD

**Issue by coder-xiaotian** [alibaba/hooks#2497]
项目中经常会有类似下面的列表选项，搜索条件变化后需要重新请求数据，我对useSelections做了一点改造以支持items变化后保持之前的选择项不变，代码如下：
![2024-03-08 16 06 03](https://github.com/alibaba/hooks/assets/22257014/06b90472-9c55-40a9-85b2-9863eda34d98)
```js
export default function (items, defaultSelected, itemKey) {
  const selections = useSelections(items, defaultSelected);
  useEffect(() => {
    if (!selections.selected.length) return;

    const list = [];
    if (itemKey) {
      items.forEach((o) => {
        if (selections.selected.find((s) => s[itemKey] === o[itemKey])) {
          list.push(o);
        }
      });
    } else {
      items.forEach((o) => {
        if (selections.selected.find((s) => s === o)) {
          list.push(o);
        }
      });
    }
    selections.setSelected(list);
  }, [items]);

  return selections;
}
```

## 问题
我能否提一个pr把这段代码加到ahooks中去，我觉得这种场景应该很常见。

**Comment by liuyib** [comment]
useSelections 一直都支持 items 动态变化后，仍然保持选中。官网的例子就是动态的 items: https://ahooks.js.org/zh-CN/hooks/use-selections#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95

你这里有这个问题，我猜是因为你使用了**对象数组**吧？目前 useSelections 是不支持对象数组的，已经有 PR 在处理支持对象数组了：https://github.com/alibaba/hooks/pull/2485

**Comment by coder-xiaotian** [comment]
> useSelections 一直都支持 items 动态变化后，仍然保持选中。官网的例子就是动态的 items: https://ahooks.js.org/zh-CN/hooks/use-selections#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95
> 
> 你这里有这个问题，我猜是因为你使用了**对象数组**吧？目前 useSelections 是不支持对象数组的，已经有 PR 在处理支持对象数组了：#2485

是的，我的数据结构就是对象数组，既然已经有了，那我就期待下🥰
