### ISSUE TITLE
[doc] doc挂的招人信息的邮箱好像是无效邮箱

### ISSUE THREAD

**Issue by JacobZyy** [alibaba/hooks#2499]
rt
<img width="743" alt="image" src="https://github.com/alibaba/hooks/assets/40699177/11b85d3e-874d-44d2-82e8-59ac5eae50ed">

**Comment by liuyib** [comment]
抱歉，v2 的官网文档不再维护，信息也已过时，请始终以最新的文档信息为准：https://ahooks.js.org/

**Comment by JacobZyy** [comment]
> 抱歉，v2 的官网文档不再维护，信息也已过时，请始终以最新的文档信息为准：https://ahooks.js.org/

尬住了、抱歉了、我看的原来一直都是v2的文档TAT
