### ISSUE TITLE
useRequest循环调用多次run, onSuccess只执行一次

### ISSUE THREAD

**Issue by kongchenglc** [alibaba/hooks#2513]
```
  const { loading, run } =
    useRequest((params) => getScoreDetail(params), {
      manual: true,
      onSuccess(data, params) {
        // 这里只执行一次
      },
      onFinally(params) {
         // 这里只执行一次
      },
    });

 //...
 for (const id of arr) {
    run({
      id,
    });
  }
```

**Comment by liuyib** [comment]
相关 issue: 
- https://github.com/alibaba/hooks/issues/1383
- https://github.com/alibaba/hooks/issues/1446

**Comment by kongchenglc** [comment]
这种接口调用场景确实不适用useRequest，需要直接调用手动来获取返回和维护loading状态等。

按照hooks的设计，能否将params理解为dependence，将返回结果映射到params上，在onSuccess中用户根据params自行处理数据？

**Comment by liuyib** [comment]
> 按照hooks的设计，能否将params理解为dependence，将返回结果映射到params上，在onSuccess中用户根据params自行处理数据？

可以这么理解

**Comment by kongchenglc** [comment]
> > 按照hooks的设计，能否将params理解为dependence，将返回结果映射到params上，在onSuccess中用户根据params自行处理数据？
> 
> 可以这么理解

那这样的话就可以多次触发onSuccess了，然后onSuccess 的参数可以获取到那次调用的 params。然后根据这个 params 用户自己来处理返回。这个可以提成一个需求给ahook吗？

**Comment by lcgash** [comment]
> ```
>   const { loading, run } =
>     useRequest((params) => getScoreDetail(params), {
>       manual: true,
>       onSuccess(data, params) {
>         // 这里只执行一次
>       },
>       onFinally(params) {
>          // 这里只执行一次
>       },
>     });
> 
>  //...
>  for (const id of arr) {
>     run({
>       id,
>     });
>   }
> ```

我目前遇到这种问题的做法通常是再把子元素进行封装，尽量保证一个 request 出现在一个元素里面，不然就会请求是出去了，但是好像只有最后一次是生效的

**Comment by crazylxr** [comment]
loading 只有一个，无法承载多个请求的 loading，你这种场景建议是 先做成一个 Promise 数组，然后传给 useRequest，伪代码如下：
```
  const { loading, run } =
    useRequest((params) => Promise.all((params) => arr.map(e =>  getScoreDetail(params))
    ，{
      manual: true,
      onSuccess(data, params) {
        // 这里只执行一次
      },
      onFinally(params) {
         // 这里只执行一次
      },
    });
 //...
```

**Comment by deng-x** [comment]
可以试试，在for或者Promise.all中，使用await run()

**Comment by deng-x** [comment]
> 可以试试，在For循环或者Promise.all中，使用await run()
