### ISSUE TITLE
Can I customize the handshake headers when using useWebSocket?

### ISSUE THREAD

**Issue by minhnhathoang** [alibaba/hooks#2515]

**Comment by liuyib** [comment]
Sorry, not supported yet. Welcome to contribute a PR to improve it, thx.

**Comment by goodjun** [comment]
😢 Sorry, the current JS WebSocket API does not support custom header functionality at the moment. The WHATWG is currently discussing this feature.

https://github.com/whatwg/websockets/issues/16

**Comment by liuyib** [comment]
Thanks for your reply @goodjun. We'll implement it once the standard supports custom WebSocket headers.
