### ISSUE TITLE
useLocalSorageState无法监听全局localStorage修改的事件

### ISSUE THREAD

**Issue by cwtuan** [alibaba/hooks#2516]
在两个View，都使用同样的key。

1. 第一个View修改的localStorage的值
2. 第二个View感知不到，没有重新渲染

看了代码，发现ahooks的实现，没有监听了全局的StorageEvent。

目前暂时改用另一个包[usehooks-ts](https://usehooks-ts.com/react-hook/use-local-storage)，这个包监听全局localStorage修改的事件。

```
const View1 = ()=>{
   const [state, setState] = useLocalSorageState('mykey')
   return (<Button onClick={()=>{setState('AAA')}}><Button>)
}

const View2 = ()=>{
   const [state, setState] = useLocalSorageState('mykey')
   console.log(state)
}
```

**Comment by liuyib** [comment]
在处理了：https://github.com/alibaba/hooks/pull/2298
耐心等待合并哈
