### ISSUE TITLE
useKeyPress: ["alt.c"] seems do not work

### ISSUE THREAD

**Issue by lqr131115** [alibaba/hooks#2517]
Something error with the hook `useKeyPress`  in `React18`  under `windows`   

Keyboard press `alt.c` seems do not work, both for `["alt.c"]` and `"alt.c"`

**Comment by lqr131115** [comment]
This seems to be a problem caused by the browser's default shortcut section.`alt.c` works fine in `Firefox`, but other shortcuts have used by Firefox, such as `alt.h`, do not work.

**Comment by liuyib** [comment]
I tested this issue on a Windows computer and couldn't reproduce it. It seems like the OS/browser has taken over the `alt.c` hotkey on your computer.

@lqr131115  Could you please test whether `alt` + another key works? If it does, then it's not a bug for ahooks. thx

**Comment by lqr131115** [comment]
@liuyib 
Thanks for your reply. 

> It seems to be a problem caused by the browser's default shortcut.

I try again in `Firefox`, and `alt.c` word fine.
