### ISSUE TITLE
useRequest 会考虑把  http status code 纳入处理过程么？

### ISSUE THREAD

**Issue by lcgash** [alibaba/hooks#2521]
目前的 onSuccess 在所有的 http status code 都会触发，但是大多数情况下，可能只有 <=300 的是属于业务正常，会不会考虑增加类似 onStatusSuccess 这样的钩子，对比 golang restry lib 库这种
![image](https://github.com/alibaba/hooks/assets/37072324/3d042c09-e4d0-43c1-8d07-b9878325f647)

**Comment by crazylxr** [comment]
useRequest 不感知 http 请求是否成功，只关心 传给 useRequest 的 Promise 返回的是否抛异常，没有抛异常就走 onSuccess，抛了就走 onError，所以没办法做这个事情。
