### ISSUE TITLE
useWebSocket 没有提供重置latestMessage的方法

### ISSUE THREAD

**Issue by husky-dot** [alibaba/hooks#2524]
当 useWebSocket作为 全局的，上一次接收到的latestMessage，在进入重新进入页面时，latestMessage还保留上一次接收到的值，导致触发 监听。

**Comment by crazylxr** [comment]
重新进入页面之后 socket 会重新连，latestMessage 没有做缓存，不理解为啥还保留了上一次的值，提供一个 demo 看下呢
