### ISSUE TITLE
useAntdTable 初始化请求执行2次

### ISSUE THREAD

**Issue by starry** [alibaba/hooks#2525]
antd ahooks 都是最新版本，麻烦大佬有空看一下，谢谢。

https://codesandbox.io/p/devbox/useantdtable-f4vh24?file=%2Fsrc%2FApp.tsx%3A3%2C39
![截图20240421153407](https://github.com/alibaba/hooks/assets/31642247/56b22e0b-4bb0-4875-8598-d31a4ef2172d)

**Comment by starry** [comment]
https://codesandbox.io/p/devbox/useantdtable-f4vh24?file=%2Fsrc%2FApp.tsx%3A3%2C39

使用的文档的例子

**Comment by crazylxr** [comment]
这个只有在开发环境才会执行两次，本质上是因为 在 react18 严格模式，useEffect 的回调会执行两次，具体的详见 react 官网：https://zh-hans.react.dev/reference/react/useEffect#my-effect-runs-twice-when-the-component-mounts
