### ISSUE TITLE
官网白屏

### ISSUE THREAD

**Issue by canyuegongzi** [alibaba/hooks#2540]
打开官网后触发了人机校验，校验通过后 白屏
<img width="1315" alt="image" src="https://github.com/alibaba/hooks/assets/32031360/12003354-8bae-4c30-bad6-4c5b1130a087">
<img width="1353" alt="image" src="https://github.com/alibaba/hooks/assets/32031360/22861f55-d901-468c-ba54-2f0569100360">
<img width="1393" alt="image" src="https://github.com/alibaba/hooks/assets/32031360/6a47d1a6-5251-40a4-ada1-c2f8e140635c">

**Comment by liuyib** [comment]
https://ahooks.js.org/ 依托于 surge 提供的免费服务，不太稳定。可以访问国内镜像：https://ahooks.gitee.io/
