### ISSUE TITLE
官网国内镜像打不开了

### ISSUE THREAD

**Issue by jin-benben** [alibaba/hooks#2546]

**Comment by liuyib** [comment]
Gitee Pages 下线了，恢复日期未知，ahooks 的文档后面会寻找其他更稳定的静态资源托管服务。

**Comment by liuyib** [comment]
ahooks 后续会将文档主要托管与 cloudflare 的静态资源服务中，地址（国内用户友好）：https://ahooks.pages.dev

https://ahooks.js.org/ 仍然可以继续使用，后续会将 ahooks.pages.dev CNAME 到 ahooks.js.org

**Comment by NoirVoider** [comment]
https://ahooks.js.org/ 503 Service Unavailable

**Comment by jacob-lcs** [comment]
@liuyib 新官网地址也无法打开 https://ahooks.pages.dev/

![Image](https://github.com/user-attachments/assets/68d8e963-33bd-4660-8836-2408179c5d27)

**Comment by Jsmond2016** [comment]
官网打不开 https://ahooks.js.org/

![Image](https://github.com/user-attachments/assets/989b320b-cf34-4384-a8a0-dda80497d5f2)

设备：Mac M1
IP：如图

![Image](https://github.com/user-attachments/assets/42c8c2fc-2e69-4440-9d12-d014b408be7a)

**Comment by kitety** [comment]
官网不稳定啊sad

![Image](https://github.com/user-attachments/assets/7ccf8435-1d2b-4d37-a7e7-63c1a01f9a9d)

**Comment by loveCHN** [comment]
实在不行就别干了

**Comment by guoshuangyang** [comment]
> 官网不稳定啊sad
> 
> ![Image](https://github.com/user-attachments/assets/7ccf8435-1d2b-4d37-a7e7-63c1a01f9a9d)

+1

来个GitHub pages ?

**Comment by taoliujun** [comment]
虽然开源不应该被乞讨，但是这么多人用了ahooks，起码维护下官网的稳定吧？

![image](https://github.com/user-attachments/assets/a344a46e-3409-4893-9896-c6d93ec2c2b5)

**Comment by zwmmm** [comment]
依旧访问不了

**Comment by 1pone** [comment]
有没有文档的仓库，想查文档官网挂了好急！

**Comment by lmsccc** [comment]
+1 现在没有地址可以访问ahooks文档了

**Comment by rizhaoyuanshan** [comment]
访问不了+1

**Comment by liuyib** [comment]
@NoirVoider @jacob-lcs @Jsmond2016 @kitety @guoshuangyang @taoliujun @zwmmm @1pone @lmsccc @rizhaoyuanshan 
各位，文档地址在我上面的评论中（刚更新的），目前有一个可以访问。

这里再附一下，哪个能用点哪个吧：

https://preview.ahooks.pages.dev/ （目前这个还可以用）
https://ahooks.pages.dev/
https://ahooks.js.org/

**Comment by liuyib** [comment]
> 虽然开源不应该被乞讨，但是这么多人用了ahooks，起码维护下官网的稳定吧？
> 

用的免费的第三方服务托管，没办法，特别是 ahooks.js.org 用的那个服务，现在估计是没营收快倒闭了，经常坏。目前看 Cloudflare  的静态资源服务中经常会提示钓鱼攻击风险页面，所以也不稳定。然后就剩一个测试文档地址这个独苗了：https://preview.ahooks.pages.dev/ （不知道访问的人多了，会不会再被 Cloudflare 提示钓鱼风险）

**Comment by taoliujun** [comment]
@liuyib 3个网址都访问不了。
ahooks好歹是阿里的，不跟kpi挂钩，连服务器托管，都不给个吗？

**Comment by crazylxr** [comment]
用 github pages 重新部署了一个备用的：  https://alibaba.github.io/hooks/

**Comment by zpc7** [comment]
![Image](https://github.com/user-attachments/assets/e59ad12b-e80a-41d0-8e06-c02ece1d8aa9)
又又打不开了

**Comment by liuyib** [comment]
> ![Image](https://github.com/user-attachments/assets/e59ad12b-e80a-41d0-8e06-c02ece1d8aa9) 又又打不开了

用github的地址：https://alibaba.github.io/hooks/，其他都不稳定

**Comment by sxei** [comment]
呵呵，这就是典型阿里员工的作风，靠着轮子晋升完了轮子维护力度就大不如前，连个稳定官方都不肯维护，还好意思说哪个稳定就用哪个，难道要每个人都跑到github issues里面来找官网地址？

**Comment by sxei** [comment]
和此类似的还有一个 lightproxy.org ，也是个晋升完连“脸”都不要的产品。

**Comment by jk4235** [comment]
阿里云连个服务器都舍不得给吗，还得耗免费的服务器资源

**Comment by lwglinux** [comment]
什么垃圾玩意

**Comment by lwglinux** [comment]
连个文档都弄不好，下线得了
