### ISSUE TITLE
本地运行start 路由问题

### ISSUE THREAD

**Issue by xiexingen** [alibaba/hooks#255]
![image](https://user-images.githubusercontent.com/7939085/75110204-43a8a480-5666-11ea-9d2d-0184abdd5865.png)
 拉的最新的master分支代码，跑起来后 路由怎么是这样的

**Comment by brickspert** [comment]
直接 tnpm run init & tnpm start 吗？

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/75110563-7e144080-566a-11ea-9a06-b15d14cf48ee.png)


你是 windows 吗？

**Comment by xiexingen** [comment]
> ![image](https://user-images.githubusercontent.com/12526493/75110563-7e144080-566a-11ea-9a06-b15d14cf48ee.png)
> 
> 你是 windows 吗？

是的 我是windows环境

**Comment by xiexingen** [comment]
这应该算father-doc的bug吧

**Comment by brickspert** [comment]
> 这应该算father-doc的bug吧

maybe，我找同学研究下。

**Comment by xiexingen** [comment]
> > 这应该算father-doc的bug吧
> 
> maybe，我找同学研究下。
最喜欢这种根这种不解决问题不罢休的人打交道

**Comment by brickspert** [comment]
> > > 这应该算father-doc的bug吧
> > 
> > 
> > maybe，我找同学研究下。
> > 最喜欢这种根这种不解决问题不罢休的人打交道

那投个简历吧。哈哈哈

**Comment by xiexingen** [comment]
> > > > 这应该算father-doc的bug吧
> > > 
> > > 
> > > maybe，我找同学研究下。
> > > 最喜欢这种根这种不解决问题不罢休的人打交道
> 
> 那投个简历吧。哈哈哈

不在杭州，在长沙哦 不然还是很愿意尝试下的

**Comment by brickspert** [comment]
> > > > > 这应该算father-doc的bug吧
> > > > 
> > > > 
> > > > maybe，我找同学研究下。
> > > > 最喜欢这种根这种不解决问题不罢休的人打交道
> > 
> > 
> > 那投个简历吧。哈哈哈
> 
> 不在杭州，在长沙哦 不然还是很愿意尝试下的

杭州，成都，上海 都可以选择。你可以把简历发给我 brickspert.fjl@antfin.com

或者你也可以在首页加我们的答疑群找我~~

我可以帮你评估简历以及跟踪进度。

**Comment by xiexingen** [comment]
@brickspert    
![image](https://user-images.githubusercontent.com/7939085/75145669-5b4e5e80-5734-11ea-924a-3f51ca5412b9.png)
发现执行这个会通不过

**Comment by brickspert** [comment]
删掉 package-lock.json ，然后重新 tnpm update 试试。

**Comment by xiexingen** [comment]
> 删掉 package-lock.json ，然后重新 tnpm update 试试。

没用，你们没遇到过这种吗

**Comment by xiexingen** [comment]
> 删掉 package-lock.json ，然后重新 tnpm update 试试。

![image](https://user-images.githubusercontent.com/7939085/75226161-e25c0f00-57e6-11ea-8e6a-d296afbde80d.png)
改成这样编译是可以过了

另外:开始提的生成的路由有问题 把father-doc升级到 ^1.0.0-beta.5也没问题了
