### ISSUE TITLE
 请求添加@types

### ISSUE THREAD

**Issue by LeoLeeTech** [alibaba/hooks#2566]
看不熟悉的hook, component时可以commnd + 单击, 进入node_modules中快速查看源码/注释

如果是我找的方式不对, 烦请指教??

next.js有n多版本
https://registry.npmjs.org/@types/next  

antd已用ts写了,可以直接点进去查看源码

但ahookszf'怎样都不行, 最后用翻tag发行包的方式才总算解决问题

<img width="634" alt="image-20240605171318290" src="https://github.com/alibaba/hooks/assets/44024086/9ec52312-9dba-4455-a4e2-7ebd9a664aa1">

**Comment by crazylxr** [comment]
ahooks 本来就是用 ts 写的，不需要增加 @types，理论上 commnd + 单击 进去就可以看的，如果不行的话，建议加一下钉钉群跟群友一起交流一下
