### ISSUE TITLE
请问createEffectWithTarget这个函数的设计考量是什么？

### ISSUE THREAD

**Issue by yiiiiiiiiiiiiiiiiii** [alibaba/hooks#2597]
根据源码，createEffectWithTarget这个函数的主要目的是将target的变化也变成副作用Hook的执行依据

我的疑问
target是从ref引用获取的，ref是传递给对应DOM节点的，一般情况下，这个引用获取的对应的DOM对象是不会变化的，那么为什么要把这个target的变化也考虑进去呢，什么应用场景下会使得这个target变化呢？

**Comment by cold72** [comment]
dom 对象在很多业务情况下都会发生改变吧？比如key值改变，条件渲染

**Comment by crazylxr** [comment]
DOM 发生变化很常见的哇，如楼上说的，如果你给列表里面的元素加了事件，列表发生了变化，比如删除了。

**Comment by yiiiiiiiiiiiiiiiiii** [comment]
感谢回答，之前觉得ref都是固定在对应jsx节点上，所以jsx对应的DOM不会变，忽略了DOM会从新创建的问题了。
