### ISSUE TITLE
useRequest能全局配置统一前缀,统一异常处理么

### ISSUE THREAD

**Issue by duwei54** [alibaba/hooks#260]
看了`useRequest`,确实很强大.不过有个疑问,能否全局配置统一前缀,统一异常处理呢?之前用的`umi-request`可以通过配置`prefix`和`errorHandler`.看了`useRequest`文档还是不知道怎么写.求指教

**Comment by brickspert** [comment]
useRequest 支持全局配置的哟：https://hooks.umijs.org/zh-CN/async?anchor=useapiprovider#%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE

**Comment by duwei54** [comment]
@brickspert 感谢回复,这个我看了,但是并没有找到一个全局配置的入口.莫非是要所有的layout组件全部包装一遍?

**Comment by brickspert** [comment]
> @brickspert 感谢回复,这个我看了,但是并没有找到一个全局配置的入口.莫非是要所有的layout组件全部包装一遍?

包裹在项目的最最最外层就可以了。

**Comment by duwei54** [comment]
@brickspert 不好意思啊,我用的antd pro.最外层好像是封装了的呢

**Comment by padeyao4** [comment]
@duwei54 你咋解决的
