### ISSUE TITLE
useEventEmitter emit() 方法是否支持返回一个 promise?

### ISSUE THREAD

**Issue by zxhlyh** [alibaba/hooks#2603]
emit 触发的函数里面可能有个异步操作，怎么才能知道这个异步操作完成？
再用一次 eventemitter 来订阅异步完成状态是可以实现，但总感觉有点繁琐。

**Comment by crazylxr** [comment]
再用一次 eventemitter 来订阅异步完成状态是正确的。 这是事件派发机制就是这么玩的，如果你需要用同步的写法，建议这个处理函数就不要通过监听事件的方式来写，而是直接在 emit 的地方直接调用这个事件处理函数

**Comment by zxhlyh** [comment]
> 再用一次 eventemitter 来订阅异步完成状态是正确的。 这是事件派发机制就是这么玩的，如果你需要用同步的写法，建议这个处理函数就不要通过监听事件的方式来写，而是直接在 emit 的地方直接调用这个事件处理函数

感谢回复。因为页面层级的问题，也只能用事件订阅了。
