### ISSUE TITLE
useFullscreen 使用在全屏模式下 top-layer 是否合理？

### ISSUE THREAD

**Issue by louhaojie99** [alibaba/hooks#2605]
在实际业务应用中，使用 ahooks 的 useFullscreen 钩子时，存在一个问题：一旦元素进入全屏状态，它会自动获得最高的层级显示（top-layer），导致诸如 Ant Design 的一些组件（如消息提示 message、模态框 Modal、工具提示 Tooltip 及弹出层 Popover 等，默认挂载在 body 上的元素）被该全屏元素遮挡，从而无法正常显示。

**Comment by liuyib** [comment]
这个行为是浏览器控制的，如果能修改层级麻烦提个 PR 支持下。如果你是用的页面级全屏，有参数可以改z-index
