### ISSUE TITLE
useRequest 新增滚动到视窗后自动请求的插件

### ISSUE THREAD

**Issue by guaijie** [alibaba/hooks#2607]
借助 IntersectionObserver，实现当目标出现在指定视窗后发起自动请求的功能

```ts
useRequest(getUserList, {
  target:   // 被监听的目标元素，设置 target 后将开启此功能
  root：
  rootMargin： 
})
```

**Comment by crazylxr** [comment]
这个可以自己通过 useInViewport + useRequest 封装一下，目前这个场景还不多，暂时不打算加入到官方的插件里面来

**Comment by guaijie** [comment]
> 这个可以自己通过 useInViewport + useRequest 封装一下，目前这个场景还不多，暂时不打算加入到官方的插件里面来

这种场景经常遇到吧，在要考虑性能优化时，会很容易考虑到这点

**Comment by crazylxr** [comment]
提一个 RFC 来看看呢
