### ISSUE TITLE
请问useFormTable如何设置分页组件的起始页码？

### ISSUE THREAD

**Issue by PeiTianHuang** [alibaba/hooks#261]

**Comment by brickspert** [comment]
暂时不支持默认设置。你可以这样用。

```
  const { tableProps, search, loading, run } = useFormTable(getTableData, {
    form: props.form,
    manual: true,
  });
 run({current: 5, pageSize: 10});
```

**Comment by PeiTianHuang** [comment]
> 暂时不支持默认设置。你可以这样用。
> 
> ```
>   const { tableProps, search, loading, run } = useFormTable(getTableData, {
>     form: props.form,
>     manual: true,
>   });
>  run({current: 5, pageSize: 10});
> ```

非常感谢，另外还想请教个问题，使用useFormTable时如何配置分页组件的属性哦？我目前是这样写的，有点别扭：
const { tableProps, search, run } = useFormTable(getTableData, {manual: true, form: props.form});
tableProps.pagination.showQuickJumper = true;
tableProps.pagination.showSizeChanger = true;

**Comment by brickspert** [comment]
> > 暂时不支持默认设置。你可以这样用。
> > ```
> >   const { tableProps, search, loading, run } = useFormTable(getTableData, {
> >     form: props.form,
> >     manual: true,
> >   });
> >  run({current: 5, pageSize: 10});
> > ```
> 
> 非常感谢，另外还想请教个问题，使用useFormTable时如何配置分页组件的属性哦？我目前是这样写的，有点别扭：
> const { tableProps, search, run } = useFormTable(getTableData, {manual: true, form: props.form});
> tableProps.pagination.showQuickJumper = true;
> tableProps.pagination.showSizeChanger = true;

我自己用的时候，是自己项目里面封装一次。把这些配置都封装到一个 Hooks 里面。
