### ISSUE TITLE
useUrlState 设置ts类型识别不到

### ISSUE THREAD

**Issue by aa-chen** [alibaba/hooks#2618]
declare const useUrlState: <S extends UrlState = UrlState>(initialState?: S | (() => S) | undefined, options?: Options) => readonly [Partial<{ [key in keyof S]: any; }>, (s: React.SetStateAction<Partial<{ [key in keyof S]: any; }>>) => void];

这泛型传递后，所有的参数的值都是any类型,应该改成下面这样的吧，不知道正不正确

declare const useUrlState: <S extends UrlState = UrlState>(initialState?: S | (() => S) | undefined, options?: Options) => readonly [Partial<{ [key in keyof S]: S[key]; }>, (s: React.SetStateAction<Partial<{ [key in keyof S]:  S[key]; }>>) => void];

**Comment by crazylxr** [comment]
怎么划线了，没问题了吗？

**Comment by aa-chen** [comment]
declare const useUrlState: (initialState?: S | (() => S) | undefined, options?: Options) => readonly [Partial<{ [key in keyof S]: any; }>, (s: React.SetStateAction<Partial<{ [key in keyof S]: any; }>>) => void];
这个是源码定义的类型，他识别不出来我传递参数的类型，因为他把value都设置层any了

**Comment by aa-chen** [comment]
这个hook希望setState添加第二个参数，可以设置navigateMode,
场景，当我进入一个页面后没有携带search参数，但是我会给默认的值，这时候navigateMode为replace，当我在这个页面做一些路由页面，指向改变search的时候 我希望是push
