### ISSUE TITLE
国内官网连上好慢……

### ISSUE THREAD

**Issue by wataru-c** [alibaba/hooks#263]
> 我一开始以为官网挂了

**Comment by brickspert** [comment]
没有挂，就是比较慢。。你这边是什么表现呢？

**Comment by wataru-c** [comment]
> 没有挂，就是比较慢。。你这边是什么表现呢？

没错，我刚刚又试了一下，确实是比较慢而已。关闭视频网站，然后等了一分钟就行……

![image](https://user-images.githubusercontent.com/13063376/75509623-4f5be880-5a23-11ea-802a-8ea474ff1d7f.png)

或者把代理pac关掉就好了。

嗯……将来能改善一下么？

**Comment by brickspert** [comment]
必须要改善下。

现在加了 PWA，第二次打开就是秒开了。

后面我们会做按需加载，将首页 js 尺寸降下来。

**Comment by poyiding** [comment]
> 必须要改善下。
> 
> 现在加了 PWA，第二次打开就是秒开了。
> 
> 后面我们会做按需加载，将首页 js 尺寸降下来。
之前也反映过这个[问题](https://github.com/umijs/hooks/issues/241)，建议可以重构一下文档

**Comment by brickspert** [comment]
嗯，我们现在基于最新的 dumi 生成新的文档了。【进行中】

**Comment by brickspert** [comment]
加了按需加载，现在快很多啦。
