### ISSUE TITLE
useControllableValue 的第一个参数，假如是null会直接报错

### ISSUE THREAD

**Issue by mmmml-zhao** [alibaba/hooks#2630]
背景：
在封装antd的table的rowSelection字段，该字段传 undefined || null 时 ，不显示 勾选，传对象（包括空对象）需要显示勾选。
准备用useControllableValue 控制 selectedRowKeys / onChange。
然后rowSelection传了null，发现这个hook报错了。

疑惑
1. 有点想知道 useControllableValue 不限制第一个值传null这个逻辑的思考
2. 需要ts限制一下第一个值不能传null吗

就感觉这个改也行（毕竟现在传null报错），不改也行（貌似是我使用逻辑问题，第一个要不传undefined 或者给个真的对象）。
![image](https://github.com/user-attachments/assets/bebda12a-c264-4f6a-adf4-625485720898)

**Comment by crazylxr** [comment]
第一点：确实应该处理一下，这个没做保护，欢迎 pr
第二点：ts 类型是限制了不能传 null 的，但是只是类型上限制了，你实际传了 null，也没办法。
