### ISSUE TITLE
usegetState的get函数返回值，不是我所预期的，在set函数执行后，应该在同步代码中得到最新的state变种（方便后面以最新state做判断等），可以用ref做，

### ISSUE THREAD

**Issue by huangnan20030709** [alibaba/hooks#2631]
![image](https://github.com/user-attachments/assets/015bfb33-9929-4300-94bd-e5b9e10e51df)

**Comment by pangao66** [comment]
同样的问题 , 希望能拿到期待的值

**Comment by pangao66** [comment]
看了源码用的useLast也是用的ref做的，但是ref也是在setState 中调用的，所以没法拿到最新值，我这里考虑可以在setState之前给ref赋值，这样就能同步获取到最新的值了，不知道用没有什么安全隐患
```ts
 const [state, setStatePrivate] = useState<S>(initialState);
  const currentStateRef = useRef(state);

  const setState = useCallback((patch: unknown) => {
    const newState = isFunction(patch) ? patch(state) : patch;
    setStatePrivate(newState);
    currentStateRef.current = newState;
  }, [state]);
  const getState = useCallback(() => currentStateRef.current, []);
```

**Comment by crazylxr** [comment]
这个问题我们在 v4 的 useProState 这个 hook 来解决。

**Comment by crazylxr** [comment]
> 看了源码用的useLast也是用的ref做的，但是ref也是在setState 中调用的，所以没法拿到最新值，我这里考虑可以在setState之前给ref赋值，这样就能同步获取到最新的值了，不知道用没有什么安全隐患
> 
> ```ts
>  const [state, setStatePrivate] = useState<S>(initialState);
>   const currentStateRef = useRef(state);
> 
>   const setState = useCallback((patch: unknown) => {
>     const newState = isFunction(patch) ? patch(state) : patch;
>     setStatePrivate(newState);
>     currentStateRef.current = newState;
>   }, [state]);
>   const getState = useCallback(() => currentStateRef.current, []);
> ```

临时解决可以参考 @huangnan20030709 提供的代码：https://github.com/alibaba/hooks/issues/2633
