### ISSUE TITLE
[FEATURE]CDN地址

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba/hooks#2632]
背景：
我现在有一个微前端的项目
如果我每个都把ahooks打包进去，那我对于configResponsive，每个项目也得配置一遍，很麻烦
如果我把ahooks用cdn引入，理论上我只要设置一遍就可以，会非常的方便

**Comment by crazylxr** [comment]
cdn 的话你的 ts 类型咋办呢

**Comment by xmsz-stu** [comment]
> cdn 的话你的 ts 类型咋办呢

正式的时候用cdn, 开发还是用包

**Comment by crazylxr** [comment]
如果你仅仅只是 configResponsive 的话，可以在主应用里面把 configResponsive 挂在 window，或者通过 props 的方式传给子应用就行了，

**Comment by xmsz-stu** [comment]
> 如果你仅仅只是 configResponsive 的话，可以在主应用里面把 configResponsive 挂在 window，或者通过 props 的方式传给子应用就行了，

ok
