### ISSUE TITLE
useDebounce 在传递函数参数时返回值类型有误

### ISSUE THREAD

**Issue by hutiliy** [alibaba/hooks#2634]
实际上下面的代码中的 doubleCount 是经过函数 `() => count*2` 运行后的结果，并不是一个 doubleCount 函数。useDebounce 错误的把它标注成了函数类型（这里实际是 number 类型）。
```ts
import { useState } from "react"
import {useDebounce} from "ahooks"

const [count] = useState(0)
const doubleCount = useDebounce(() => count*2, { wait: 1000 })

```

**Comment by crazylxr** [comment]
类型没有错，useDebounce ，是用来 debounce 值的，返回的类型跟 传入的第一个参数的类型一致。

如果你要用函数，建议用 useDebounceFn
