### ISSUE TITLE
useRequest 不调用run方法自动执行导致页面报错

### ISSUE THREAD

**Issue by leo2128** [alibaba/hooks#2656]
在react hooks项目组件中使用  const { data, run, loading } = useRequest(xxxApi) 方法， 进入页面会自动执行，我理解不应该是在调用run方法的时候才会执行吗？

**Comment by tchen-l** [comment]
看下文档，有参数的
```
const { loading, run } = useRequest(xxxApi, {
  manual: true
});
```

**Comment by crazylxr** [comment]
@leo2128 看下文档手动触发的那块
