### ISSUE TITLE
Bug：useWebSocket不断重新连接

### ISSUE THREAD

**Issue by dongmucat** [alibaba/hooks#2697]
function App() {
	return (
		<BrowserRouter>
				<Route
					path="/chat/:id"
					element={<Chat />}
				/>
			</Routes>
		</BrowserRouter>
	);
	
	}
	
	然后在Chat组件使用useWebSocket会一直不断的重新连接 ws，node20.9.0，"ahooks": "^3.8.4",

**Comment by dongmucat** [comment]
看了源码，可能是ws.onclose事件中不断调用重连

**Comment by crazylxr** [comment]
来个 demo 吧

**Comment by dongmucat** [comment]
我直接修改了源码，可以提PR吗？

**Comment by dongmucat** [comment]
> 来个 demo 吧

https://github.com/alibaba/hooks/pull/2698 ，提了PR @crazylxr
