### ISSUE TITLE
关于实践中的几个FAQ

### ISSUE THREAD

**Issue by poyiding** [alibaba/hooks#271]
**1. 页面同时发多个请求，如何获取data?**
目前实现：
第一种
```
 const result1 = useRequest('/api/a.json');
 const result2 = useRequest('/api/b.json');
 const getData1 = result1.data;
 const getData2 = result2.data;
```
第二种
```
  function query() {
    const fetch1 = request('/api/a.json').then(res =>res.data);
    const fetch2 = request('/api/b.json').then(res => res.data);
    return Promise.all([fetch1, fetch2]).then(res => res);
  }
  const test = useRequest(query);
```
原因是useRequest返回结果的参数是对象，不能同时取两个结果中的data，请问还有更好的实现吗。

**2. 如果页面中要实现比如增、删、改等异步请求，如何调用不同请求的 run() ?**
我看了一下react-query的 useMutation的api
是不是可以设计成：
```
const [run, result ] = useRequest(requestFun)
```
其他常见场景欢迎补充

**Comment by brickspert** [comment]
> 1. 页面同时发多个请求，如何获取data?

目前建议建议采用第一个方案。

> 如果页面中要实现比如增、删、改等异步请求，如何调用不同请求的 run() ?

这个不是很理解。是这个意思吗？

```javascript
const request1 = useRequest(requestFun)
const request2 = useRequest(requestFun2)

request1.run();
request2.runn();
```

**Comment by poyiding** [comment]
> > 1. 页面同时发多个请求，如何获取data?
> 
> 目前建议建议采用第一个方案。
> 
> > 如果页面中要实现比如增、删、改等异步请求，如何调用不同请求的 run() ?
> 
> 这个不是很理解。是这个意思吗？
> 
> ```js
> const request1 = useRequest(requestFun)
> const request2 = useRequest(requestFun2)
> 
> request1.run();
> request2.runn();
> ```

嗯，是的，现在好像要这样。
