### ISSUE TITLE
Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

### ISSUE THREAD

**Issue by sskcal** [alibaba/hooks#278]
在使用useDynamicList会出现此问题。。

Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
    in Cell
    in Cell (created by BodyRow)
    in tr (created by BodyRow)
    in BodyRow (created by Body)
    in tbody (created by Body)
    in Body (created by Table)
    in table (created by Table)
    in div (created by Table)
    in div (created by Table)
    in div (created by Table)
    in Table (created by Table)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Spin (created by Table)
    in div (created by Table)
    in Table (at Prices/index.jsx:239)
    in form (created by ForwardRef(Form))
    in ForwardRef(Form) (created by ForwardRef(InternalForm))
    in SizeContextProvider (created by ForwardRef(InternalForm))
    in ForwardRef(InternalForm) (at Prices/index.jsx:238)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Card (at Prices/index.jsx:221)
    in Unknown (at App.js:17)
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Content (at Main.jsx:99)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (at Main.jsx:89)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (at Main.jsx:76)
    in MainLayout (created by Context.Consumer)
    in withRouter(MainLayout) (at App.js:17)
    in Route (at App.js:17)
    in Switch (at App.js:36)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:35)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (at App.js:34)
    in Suspense (at App.js:33)
    in Provider (at App.js:32)
    in App (at src/index.js:7)

**Comment by brickspert** [comment]
具体是怎么复现的呢？能稍微详细点吗？官网 demo 并没有这个警告。

**Comment by sskcal** [comment]
录了一下屏，您方便的话能帮忙看看？录屏在附件。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"砖家"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 上午9:27
收件人:&nbsp;"umijs/hooks"<hooks@noreply.github.com&gt;;
抄送:&nbsp;"看看吧"<5546461@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/hooks] Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state. (#278)




具体是怎么复现的呢？能稍微详细点吗？官网 demo 并没有这个警告。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

屏幕录制2020-03-05上午10.16.00.mov (97.15M, 2020年04月04日 10:21 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=6333373084bd8ec0e992633040365116560007090203000f19520e53511b570850061a080001511455025309525752000c045355661463fff5f78cf2dae0a50b0401071d56054e0901faf8fe810753170505190056180e5642330a&t=exs_ftn_download&code=4370f6c9
