### ISSUE TITLE
README.MD 完善

### ISSUE THREAD

**Issue by brickspert** [alibaba/hooks#28]
默认英文，支持中文。参考社区优秀案例~

**Comment by brickspert** [comment]
默认英文，支持中文。参考社区优秀案例~

**Comment by brickspert** [comment]
需要包括 贡献指南，发布流程规范等

**Comment by yutingzhao1991** [comment]
编辑按钮和导航重合了

![image](https://user-images.githubusercontent.com/1061968/63239027-c39b1f80-c27b-11e9-8c8d-93a8a1b2f31f.png)

另外 https://umijs.github.io/hooks/ 这个显示 Page Not Found

**Comment by brickspert** [comment]
已经修复啦。
