### ISSUE TITLE
useFormTable 缓存可以指定只缓存 table 不缓存 form 吗？

### ISSUE THREAD

**Issue by dpyzo0o** [alibaba/hooks#280]
RT，有需求需要切换页面的时候，form 内的数据重置，可以通过配置做到吗？

**Comment by brickspert** [comment]
目前不支持的。

Table 展示的数据就是 form 筛选过的，为啥不需要缓存 form 呢？

**Comment by dpyzo0o** [comment]
> 目前不支持的。
> 
> Table 展示的数据就是 form 筛选过的，为啥不需要缓存 form 呢？

emm, 产品要求切换界面的时候不保留之前的查询条件。那这样看来只能都不缓存了，唯一的问题就是切换页面的时候会先闪一下没有数据的loading

**Comment by brickspert** [comment]
> > 目前不支持的。
> > Table 展示的数据就是 form 筛选过的，为啥不需要缓存 form 呢？
> 
> emm, 产品要求切换界面的时候不保留之前的查询条件。那这样看来只能都不缓存了，唯一的问题就是切换页面的时候会先闪一下没有数据的loading

嗯，按产品的需求应该就是不缓存的数据。

**Comment by dpyzo0o** [comment]
> > > 目前不支持的。
> > > Table 展示的数据就是 form 筛选过的，为啥不需要缓存 form 呢？
> > 
> > 
> > emm, 产品要求切换界面的时候不保留之前的查询条件。那这样看来只能都不缓存了，唯一的问题就是切换页面的时候会先闪一下没有数据的loading
> 
> 嗯，按产品的需求应该就是不缓存的数据。

我想的是如果能做到分开缓存，那么就算重置查询条件，也不用闪一下没有数据的loading，这样视觉上体验会好一点。

**Comment by dpyzo0o** [comment]
比如用 redux 的话，就可以做到切换页面的时候重置 form 数据，然后 table 数据先展示上次查询的数据，然后 loading 展示后面的数据

**Comment by brickspert** [comment]
> 比如用 redux 的话，就可以做到切换页面的时候重置 form 数据，然后 table 数据先展示上次查询的数据，然后 loading 展示后面的数据

对。是的。如果你用 hooks 类的数据流工具代替 redux，可以直接把 useFormTable 放到 model 里面~

**Comment by dpyzo0o** [comment]
> > 比如用 redux 的话，就可以做到切换页面的时候重置 form 数据，然后 table 数据先展示上次查询的数据，然后 loading 展示后面的数据
> 
> 对。是的。如果你用 hooks 类的数据流工具代替 redux，可以直接把 useFormTable 放到 model 里面~

useFormTable 放到 model 里是什么意思，没太懂，可以描述一下嘛 @brickspert

**Comment by brickspert** [comment]
> > > 比如用 redux 的话，就可以做到切换页面的时候重置 form 数据，然后 table 数据先展示上次查询的数据，然后 loading 展示后面的数据
> > 
> > 
> > 对。是的。如果你用 hooks 类的数据流工具代替 redux，可以直接把 useFormTable 放到 model 里面~
> 
> useFormTable 放到 model 里是什么意思，没太懂，可以描述一下嘛 @brickspert

https://github.com/umijs/hox
https://github.com/jamiebuilds/unstated-next
