### ISSUE TITLE
Please delete the depreciated useAntdTable folder under the lib folder 

### ISSUE THREAD

**Issue by Henryhehe** [alibaba/hooks#284]
Using this with typescript and next.js, however, when I build the typescript, it always gives me the error for 
```
ReferenceError: regeneratorRuntime is not defined
```
And it is coming from 
```
node_modules/@umijs/hooks/lib/useAntdTable/index.js:12:41
```

I have to manually delete the folder in order for it to build successfully.

Thank you!

**Comment by brickspert** [comment]
The fastest way is add `regenerator-runtime` ：https://hooks.umijs.org/docs/faq#when-i-use-umi-hooks-i-get-an-error-regeneratorruntime-is-not-defined-how-can-i-solve-it

And we will fix this as soon as possible.

Thank you for your feedback.
