### ISSUE TITLE
是否有Select控件的下拉分页demo

### ISSUE THREAD

**Issue by kcmeven** [alibaba/hooks#305]
是否有Select控件的下拉分页demo，
还是现在的分页可以搞定？怎么解决分页后之前的数据还要在？

**Comment by brickspert** [comment]
你可以使用 useRequest 的 [加载更多](https://hooks.umijs.org/zh-CN/async?anchor=%E5%8A%A0%E8%BD%BD%E6%9B%B4%E5%A4%9A#%E5%8A%A0%E8%BD%BD%E6%9B%B4%E5%A4%9A) 模式。

**Comment by kcmeven** [comment]
> 你可以使用 useRequest 的 [加载更多](https://hooks.umijs.org/zh-CN/async?anchor=%E5%8A%A0%E8%BD%BD%E6%9B%B4%E5%A4%9A#%E5%8A%A0%E8%BD%BD%E6%9B%B4%E5%A4%9A) 模式。

debounceInterval: 500,
    manual: true,
    loadMore: true,
    isNoMore: d => (d ? d.list.length >= d.total : false)

使用防抖加加载更多，
select  onSearch={run}  会报类型错误，
