### ISSUE TITLE
useRequest 怎么设置拦截器

### ISSUE THREAD

**Issue by wushizhan** [alibaba/hooks#310]
如题

**Comment by brickspert** [comment]
https://hooks.umijs.org/zh-CN/hooks/async#2-%E6%88%91%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8-umi-request-%E7%9A%84-use-errorhandler-%E7%AD%89%EF%BC%9F

**Comment by wushizhan** [comment]
@brickspert 哥们 那现在 就不用跟之前dva 单独写 service， 直接在组件里面写请求连接吗 或者能给个完整示例吗 感谢 是砖家大神啊 前几天还读了你的文章

**Comment by brickspert** [comment]
写 service，或者直接写请求连接都可以的。

**Comment by wushizhan** [comment]
@brickspert 再麻烦一下 如果通过
<UseAPIProvider value={{
  requestMethod: request,
}}> 全局设置了Request 那怎么写service 呢 之前写service 里面func已经使用了自定义的request

**Comment by wushizhan** [comment]
就是在service 里面不再直接使用request 而是封装成
(username) => ({
  url: '/api/changeUsername',
  method: 'post',
  data: { username }
这样的func是吗

**Comment by brickspert** [comment]
如果 service 自己是一个字符串或者 object，会走 requestMethod.
如果 service 自己是一个 Promise，不会走 requestMethod.

建议学习一下文档哟。
