### ISSUE TITLE
useRequest方法，当参数manual等于true时，解构出来的data值为空吗？

### ISSUE THREAD

**Issue by EdisonFan** [alibaba/hooks#314]
const submitPaper = useRequest(submit, { manual: true }

const submitClick = async () => {
    let res = await submitPaper.run();
    consolt.log(submitPaper.data)   // undifind
}
submitClick();

当参数manual等于 true时，data的值不会存返回值吗？

**Comment by brickspert** [comment]
你这个数据流用的不太对。

你直接 console.log(res.data) 吧

**Comment by EdisonFan** [comment]
没错，可以用 res.data
但是我很好奇，为什么当参数manual等于true时，submitPaper.data为空

**Comment by lizy0329** [comment]
run 能不能返回数据啊，现在 

run().then((res)=>{console.log(res)})

res 为 null

**Comment by brickspert** [comment]
> run 能不能返回数据啊，现在
> 
> run().then((res)=>{console.log(res)})
> 
> res 为 null

这个目前是支持的。

如果有问题，可以提供个复现~~ 新开个 issue

**Comment by lizy0329** [comment]
我看见有段源码：

```
run(...args: P) {
    if (this.debounceRun) {
      this.debounceRun(...args);
      // TODO 如果 options 存在 debounceInterval，或 throttleInterval，则 run 和 refresh 不会返回 Promise。 带类型需要修复后，此处变成 return;。
      return Promise.resolve(null as any);
    }
    if (this.throttleRun) {
      this.throttleRun(...args);
      return Promise.resolve(null as any);
    }
    return this._run(...args);
  }
```
明显就是写死了 null 的输出
如果没有 formatResult 现在只能通过 onSuccess 才能获取 res 的数据
但 onSuccess 这个回调并不符合现代开发的编写方式

**Comment by brickspert** [comment]
只有在 throttle 和 debounce 配置的情况下，run 是没有 then 的。

其它情况都有 then

**Comment by lizy0329** [comment]
难怪，原来我设置了 debounceInterval，但为什么要这么奇怪 debounceInterval，或 throttleInterval不返回 res 呢？ 是BUG吗？
