### ISSUE TITLE
Concurrent Request, pulling from multiple APIS

### ISSUE THREAD

**Issue by maidul98** [alibaba/hooks#317]
I am not sure how to do this, but I want to have Concurrent Requests to for example api1, api2 with each having its own data, loading and error state. How do I do that? What should I pass into the run function? The URL? Very new to this, so I would love some help!

**Comment by brickspert** [comment]
Maybe you should separate requests?

```
const firstRequest = useReqeust(service, {manual: true});
const secondRequest = useReqeust(service, {manual: true});

// firstRequest.run()
// secondRequest.run()

// firstRequest.loading
// firstRequest.data

// secondRequest.loading
// secondRequest.data

```
