### ISSUE TITLE
useRequest怎么给请求传递参数

### ISSUE THREAD

**Issue by victorWuxz** [alibaba/hooks#318]
因为每次点击查询查询按钮的时候参数都会改变，使用run传递不过去

**Comment by brickspert** [comment]
不是很理解你的意思？run 的参数会传递给 service 的。

**Comment by brickspert** [comment]
https://hooks.umijs.org/hooks/async#manual-trigger

**Comment by victorWuxz** [comment]
谢谢，一开始传入的请求函数有误，改正后就好了，谢谢
