### ISSUE TITLE
Question about your Docz setup

### ISSUE THREAD

**Issue by sorknes** [alibaba/hooks#319]
Hi,

This isn’t an issue, but a question.

How did you go about creating your Docz setup? Especially how did you manage to create your Guide and Hooks pages with the dynamic sidebar?

Do you have a repository I can look at?

Hope you can help me with this.

**Comment by brickspert** [comment]
Hei, man.

We don't use Docz，but [dumi](https://d.umijs.org/).

dumi is more beautiful and simple than docz.
