### ISSUE TITLE
compatible with preact?

### ISSUE THREAD

**Issue by milobluebell** [alibaba/hooks#321]
是否能够完美兼容preact?

**Comment by brickspert** [comment]
只要 hooks 用法一致，就没问题的。

不过 preact 没深入了解过。

**Comment by milobluebell** [comment]
👌我以为你们测试过，那我晚点自己测下。用法是一致的，一般react转preact，加个preact-compat就行。

**Comment by brickspert** [comment]
那应该问题不大的，感谢~

**Comment by milobluebell** [comment]
- 不客气
- 不知为啥screenfull这个东西经常install不进来。
- master有1个测试用例是failed的。
- uninstall react/react-dom，并且install preact和preact-compat后，start跑起来一切正常。
![analyz-with-preact](https://user-images.githubusercontent.com/11535146/77891635-d3fc8980-72a3-11ea-8338-cfccee0de5d1.png)
- 似乎只能说目测用着问题应该不大，但是没法写测试。react-testing-library不知道该怎么替换成测preact的，查了一下，有哥preact-testing-library，但是api差距好大。试了一下根本跑不动。
- 我preact项目先用着你们这个试试把，有问题再找你吧。

@brickspert
