### ISSUE TITLE
[question] useFormTable用法

### ISSUE THREAD

**Issue by MoChKa** [alibaba/hooks#322]
### 基于 [demo3](https://github.com/umijs/hooks/blob/master/packages/hooks/src/useFormTable/demo/demo3.tsx)
关于 `useFormTable` 的用法请教：
1. 如何自定义 `searchForm` 的 `onSearch` 方法，我将接口换成自己的之后，返回的数据类型名字肯定不是 `name`，那么如何自定义这个筛选方法？

**Comment by brickspert** [comment]
不是很理解你的意思？

**Comment by MoChKa** [comment]
```typescript
  const { tableProps, search } = useFormTable(getTableData, {
    defaultPageSize: 5,
    form,
  });
```
这里的 `search` 如何根据接口返回的数据自定义？

**Comment by brickspert** [comment]
> 这里的 `search` 如何根据接口返回的数据自定义？

search 会自动读取当前 form 的值，传递给后端。

和返回的数据有什么关系哩？不是很理解~~

**Comment by MoChKa** [comment]
原来会发起一次请求给后端，之前没有注意到这个是如何实现的，多谢解答
