### ISSUE TITLE
升级 antd 4.1.0 后使用 useFormTable 报错

### ISSUE THREAD

**Issue by dpyzo0o** [alibaba/hooks#323]
之前在 antd 4.0.3 一切正常，升级 4.1.0 后 ts 报错，错误信息如下

<img width="1427" alt="Screen Shot 2020-03-30 at 10 36 22" src="https://user-images.githubusercontent.com/24768249/77886962-57b27800-729c-11ea-8c4f-96b89ffcc17d.png">

看了下 antd 的 changelog，好像 table pagination 做了一些修改，是不是导致和 umi hooks 这边不一致了

umi hooks 版本 1.8.0

**Comment by MinJieLiu** [comment]
+1
 size 定义改掉了。这边没同步。

**Comment by brickspert** [comment]
fixed on v1.8.1
