### ISSUE TITLE
useRequest 分页模式 / useAntdTable 支持设置初始化排序和筛选参数

### ISSUE THREAD

**Issue by dengfuping** [alibaba/hooks#329]

**Comment by brickspert** [comment]
等 v1.9.0 发布后，加个 defaultParams 参数试试。

```
    defaultParams: [{
      current: 10,
      pageSize: 10,
      sorter: {
        column: {
          title: 'id',
          dataIndex: 'id',
          sorter: true,
          sortOrder: 'asc'
        },
        order: 'ascend',
        field: 'id',
        columnKey: 'id'
      }
    }]
```

**Comment by PeiTianHuang** [comment]
> 等 v1.9.0 发布后，加个 defaultParams 参数试试。
> 
> ```
>     defaultParams: [{
>       current: 10,
>       pageSize: 10,
>       sorter: {
>         column: {
>           title: 'id',
>           dataIndex: 'id',
>           sorter: true,
>           sortOrder: 'asc'
>         },
>         order: 'ascend',
>         field: 'id',
>         columnKey: 'id'
>       }
>     }]
> ```

![image](https://user-images.githubusercontent.com/17986764/78644797-097b2580-78e9-11ea-9c9b-3c4140e75ec0.png)
![image](https://user-images.githubusercontent.com/17986764/78644814-1435ba80-78e9-11ea-9ae7-00209966f95b.png)
![image](https://user-images.githubusercontent.com/17986764/78644839-1f88e600-78e9-11ea-84be-7e8ce51c2f6d.png)
这个defaultParams的使用存在其他前提条件吗？

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/78801772-a922db80-79ef-11ea-9372-d372e40ac3b3.png)

测试是可以使用的。
https://codesandbox.io/s/antd-table-iym63?file=/demo.tsx
