### ISSUE TITLE
react-native  使用useRequest cacheKey无法缓存

### ISSUE THREAD

**Issue by gao520sun** [alibaba/hooks#330]
Binaries:
    Node: 12.14.0
    Yarn: 1.21.1 
    npm: 6.13.4 
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
![image](https://user-images.githubusercontent.com/8372369/78429527-2fb18300-76a7-11ea-8524-fb2428590124.png)

**Comment by brickspert** [comment]
有没有尝试下在 web 上面同样的写法是不是生效了？
