### ISSUE TITLE
useScroll/监听组件的效能疑问

### ISSUE THREAD

**Issue by yeungc** [alibaba/hooks#331]
每次滚动页面 useScroll都会瞬间render很多次 请问这情况会影响效能吗? 有没有可能给它加个throttle 参数?
另外是useResponsive/useClickAway 虽然只有达到相应条件时才会render一次 但是如果页面有好几个这种监听事件 请问会不会也影响效能呢? 感谢

**Comment by brickspert** [comment]
useScroll 多次触发 render 是正常的，一般的组件不会有性能问题。
其实它的原理和就是监听滚动，然后触发 setState。

当然如果你的组件非常复杂，或者你不想对 scroll 的变化那么敏感，你可以自己实现一下呢~~

> 另外是useResponsive/useClickAway 虽然只有达到相应条件时才会render一次 但是如果页面有好几个这种监听事件 请问会不会也影响效能呢? 感谢

这个是不会有性能问题的呢。
