### ISSUE TITLE
1.9.0版本中useAntdTable的defaultParams参数似乎无效

### ISSUE THREAD

**Issue by PeiTianHuang** [alibaba/hooks#336]
![image](https://user-images.githubusercontent.com/17986764/78644797-097b2580-78e9-11ea-9c9b-3c4140e75ec0.png)
![image](https://user-images.githubusercontent.com/17986764/78644814-1435ba80-78e9-11ea-9ae7-00209966f95b.png)
![image](https://user-images.githubusercontent.com/17986764/78644839-1f88e600-78e9-11ea-84be-7e8ce51c2f6d.png)

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/78803874-19326100-79f2-11ea-89b5-ca95ed664fb6.png)

测试是可以使用的。
https://codesandbox.io/s/antd-table-iym63?file=/demo.tsx

**Comment by PeiTianHuang** [comment]
> ![image](https://user-images.githubusercontent.com/12526493/78803874-19326100-79f2-11ea-89b5-ca95ed664fb6.png)
> 
> 测试是可以使用的。
> https://codesandbox.io/s/antd-table-iym63?file=/demo.tsx

我上面表达有问题，useRequest是正常的，是useFormTable不行

**Comment by PeiTianHuang** [comment]
@brickspert
