### ISSUE TITLE
useRequest 支持条件请求

### ISSUE THREAD

**Issue by brickspert** [alibaba/hooks#337]

**Comment by xyj404** [comment]
有进展吗？现在参数是{defaultParams: pageNum, refreshDeps: [pageNum]}，改变pageNum时，请求的参数不会改变。

**Comment by uliian** [comment]
目前在编辑场景用的比较多：同一个组件，能新增，也能编辑
但是如果模式为编辑，id不为空，则需要请求一下详情，然后填充进表单，如果为新增模式，则不需要做请求~
对条件请求的需求很迫切

**Comment by chj-damon** [comment]
期待2.0版本早日发布

**Comment by awmleer** [comment]
ahooks 已经支持了：https://ahooks.js.org/zh-CN/hooks/async
