### ISSUE TITLE
useAntdTable 先排序后翻页传参错误

### ISSUE THREAD

**Issue by dengfuping** [alibaba/hooks#338]
- umi-hooks 版本: 1.8.1
- 重现链接(官网 demo): https://hooks.umijs.org/zh-CN/hooks/deprecated/use-antd-table#%E6%8E%92%E5%BA%8F%E4%B8%8E%E7%AD%9B%E9%80%89
- 重现步骤: 先对 `phone` 这一列做三次排序，然后切换到第二页，发现无法成功切换，且页码传参没有改变，仍然为 0

**Comment by brickspert** [comment]
暂时先用 useRequest 或 useFormTable 代替下。

**Comment by brickspert** [comment]
fixed: v1.9.1
