### ISSUE TITLE
No place to add responseType: 'arraybuffer',

### ISSUE THREAD

**Issue by maidul98** [alibaba/hooks#340]
Hello, I would like to set the responseType: 'arraybuffer', but it doesn't seem like you guys support this? Is this possible with the useRequest hook?

**Comment by brickspert** [comment]
useRequest only cares about Promise, don't care how to send request.

maybe you should manage request yourself?

```javascript
const result = useRequest(()=>{
     return requestMethod({ responseType: 'arraybuffer' });
});
```

**Comment by maidul98** [comment]
Awesome, thank you! For anyone else this is how you do it:

const downloadBulkSubmissions = useRequest(()=>{
        return fetch('URL', {
            method: 'POST', // *GET, POST, PUT, DELETE, etc.
            responseType: 'arraybuffer', // add this line 
            headers: {
              'Content-Type': 'application/json'
            },
            body: DATA HERE
        })
   }, {
    manual: true,
    onSuccess: (result, params) => {
        console.log(result)
    },
   });
