### ISSUE TITLE
建议  useFormTable 支持调用的时候传入初始值

### ISSUE THREAD

**Issue by xiexingen** [alibaba/hooks#342]
比如: 
const { tableProps, params, search, sorter } = useFormTable(getTableData, {
    defaultPageSize: 5,
    form,
    params:{} // 对应run(...params) 这个的params
  });
使用场景
1.通过自定义hooks记录当前搜索状态(查询条件、排序状态、页码)
2.当切换路由的时候 自己将这个搜索状态记录下来(比如：以当前路由为key，以搜索条件为值存储到sessionStorage)
3.当从其他页面返回的时候，如果需要还原搜索状态
 从sessionStorage获取搜索状态，然后调用useFormTable的时候，解析出条件 调用useFormTable

**Comment by PeiTianHuang** [comment]
useRequest有支持传入defaultParams，useFormTable不知为何目前不支持defaultParams

**Comment by brickspert** [comment]
是不是可以用 cacheKey 解决你的问题？

**Comment by brickspert** [comment]
另外 defaultParams 已经支持了，这两天发布下。

**Comment by xiexingen** [comment]
> 另外 defaultParams 已经支持了，这两天发布下。
已经发布了吗？我试试 如果支持指定传入初始参数，那那个缓存的问题可以以另外的方式解决

**Comment by xiexingen** [comment]
其实我的情况是这种
## 业务背景

浏览器刷新或者点编辑进入子页面，然后从子页面点返回 返回到列表页面的时候 列表页面需要按最后的搜索条件、页码、排序 这些条件来重新刷新一下列表数据

### 尝试过的解决方案
1.修改useFormTable ，使用cacheKey配置的时候(约定cacheKey使用当前route的pathname) 会把搜索条件存到当前sessionStorage；如果是页面刷新或者从详情页面返回的时候 将sessionStorage对应的key为pathname的数据标记为激活；这样返回列表页面重新请求的时候 如果sessionStorage中对应这个pathname的数据如果是激活状态，则使用这个条件来查询  --发现这种做法有点太牵强了 于是打算采用第二种方式
好处:感觉useFormTable里面的cacheKey是个鸡肋，所以想通过这个key来处理这种情况
2.如果useFormTable支持传入默认参数(查询条件、页码、排序等)；打算另外写一个useDestroy hooks 这个hooks会在组件销毁或者页面重新刷新(发现页面重新刷新不会进入销毁的回调)的时候将查询条件记录下来；当重新进入这个组件的时候 通过这个hooks获取到记录的值；传给useFormTable 
优点:不需要动useFormTable、灵活一些
缺点：多做了一个步骤

**Comment by brickspert** [comment]
fixed: 1.9.1
