### ISSUE TITLE
useRequest 文档没法看

### ISSUE THREAD

**Issue by fi3ework** [alibaba/hooks#344]
https://github.com/umijs/hooks/blob/master/packages/use-request/index.zh-CN.md

渲染出来是这样...

![image](https://user-images.githubusercontent.com/12322740/79066730-d4a60e80-7cec-11ea-95dd-a8cd83a421aa.png)

还有这样的... 😂

![image](https://user-images.githubusercontent.com/12322740/79066732-d5d73b80-7cec-11ea-89db-c2e7996e41ca.png)

**Comment by brickspert** [comment]
在这里看：https://hooks.umijs.org/zh-CN/hooks/async

**Comment by fi3ework** [comment]
这个文档我知道，但是这并没有解决这个问题，感觉也不应该 close 🤔

**Comment by brickspert** [comment]
没理解你的意思。。。你是要看源码？

![image](https://user-images.githubusercontent.com/12526493/79067002-c0fba780-7cee-11ea-8575-b17dbf418722.png)

**Comment by fi3ework** [comment]
我是意思是这是一个文档的 bug，不应该解决一下吗。如果有的人没看到 dumi 的链接直接在 GitHub 上看 README 不就瞎了 ...

**Comment by brickspert** [comment]
> 我是意思是这是一个文档的 bug，不应该解决一下吗。如果有的人没看到 dumi 的链接直接在 GitHub 上看 README 不就瞎了 ...

这个解决不了的，要不还要 dumi 干啥 0 0~~
