### ISSUE TITLE
按需加载相关

### ISSUE THREAD

**Issue by WeiShengv99** [alibaba/hooks#345]
![image](https://user-images.githubusercontent.com/35689628/79068796-230ed980-7cfc-11ea-93bf-9274716d7c09.png)
我在按需加载  useRequest 的时候，发现 hooks 文件夹内并没有 useRequset文件夹，但是在文档中所以关于 useRequset 的引入，看起来都是访问的 hooks 文件夹，这让人很疑惑

**Comment by brickspert** [comment]
useRequest 是在独立包中：`@umijs/use-request` 这个包里面。

hooks 做了一层代理~~

**Comment by brickspert** [comment]
先关了哈，有问题再开哈~~

**Comment by leohxj** [comment]
意思在按需加载的时候，
写法上直接用 `import useRequest, { UseRequestProvider } from '@ahooksjs/use-request';` 而不是 `import { useRequest } from 'ahooks'` 吧

**Comment by ycshill** [comment]
> 意思在按需加载的时候， 写法上直接用 `import useRequest, { UseRequestProvider } from '@ahooksjs/use-request';` 而不是 `import { useRequest } from 'ahooks'` 吧

同问

**Comment by ycshill** [comment]
> import useRequest, { UseRequestProvider } from '@ahooksjs/use-request';

没有

> useRequest 是在独立包中：`@umijs/use-request` 这个包里面。
> 
> hooks 做了一层代理~~

没有直接回答问题啊

**Comment by liuyib** [comment]
> > import useRequest, { UseRequestProvider } from '@ahooksjs/use-request';
> 
> 没有
> 
> > useRequest 是在独立包中：`@umijs/use-request` 这个包里面。
> > hooks 做了一层代理~~
> 
> 没有直接回答问题啊

这个 issue 时间太久远了。。。

@ycshill  你用的 ahooks 版本多少？
