### ISSUE TITLE
useFormTable使用useRef的方式的传入form实例时同时使用manual: true，会导致第一次查询时拿不到参数

### ISSUE THREAD

**Issue by juenanfeng** [alibaba/hooks#350]
详见以下例子：https://codesandbox.io/s/umijs-hooks-useformtable-with-ref-9u7sv?file=/src/test.js:873-885

**Comment by brickspert** [comment]
要解决这个问题的话，需要 `form` 支持接收 ref 类型，改动较大。如果后面有同类需求再改。
