### ISSUE TITLE
useFormTable的defaultType参数的作用是？

### ISSUE THREAD

**Issue by PeiTianHuang** [alibaba/hooks#359]
useFormTable和useRequest的api中没有找到对应的描述，不传则会报错

**Comment by brickspert** [comment]
能贴下错误信息啥的吗

**Comment by brickspert** [comment]
应该是 ts 类型写的有些问题。我们修正下。

**Comment by PeiTianHuang** [comment]
> 能贴下错误信息啥的吗

![image](https://user-images.githubusercontent.com/17986764/79710580-fceaca00-82f7-11ea-8472-8591ec19949d.png)
报错那个是ts的提示信息哈，defaultType要求必传，只是有点好奇这个参数的作用是什么

**Comment by brickspert** [comment]
fixed in v1.9.2
