### ISSUE TITLE
taro开发小程序使用umihook提示Cannot use 'in' operator to search for 'URLSearchParams' in undefined

### ISSUE THREAD

**Issue by birdycn** [alibaba/hooks#360]
Cannot use 'in' operator to search for 'URLSearchParams' in undefined
TypeError: Cannot use 'in' operator to search for 'URLSearchParams' in undefined
    at Module../node_modules/_whatwg-fetch@3.0.0@whatwg-fetch/fetch.js 

请问有什么解决办法吗

**Comment by brickspert** [comment]
贴一下用法？你是用了 useRequest 吗？看着像是 umi-request 依赖的底层库报错。

**Comment by brickspert** [comment]
你可以换个请求库试试：https://hooks.umijs.org/hooks/async#useapiprovider
