### ISSUE TITLE
子组件第一次渲染，报错Cannot call an event handler while rendering

### ISSUE THREAD

**Issue by biglemontree** [alibaba/hooks#361]
https://codesandbox.io/s/shoudonghongfa-hrz8u?file=/demo.tsx

在子组件demo渲染的同时，在useEffect手动调用run(),报错Cannot call an event handler while rendering. 这是不是一个bug呀  😭

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/79762379-46b5cd80-8355-11ea-8a83-cada5739435a.png)

这里写错了。改成我这样的语法。

**Comment by jialulu0829** [comment]
还是报错
