### ISSUE TITLE
使用 useRequest ，返回数据必须用data包裹？

### ISSUE THREAD

**Issue by linvva** [alibaba/hooks#368]
data不能直接获取到response.body吗？
这个对于老项目升级实在太不友好了

**Comment by brickspert** [comment]
默认的是 response.body

但是从 umi 中引用的 useRequest 必须用 data 包一次。

* 你可以配置一个 `formatResult: d=>d` 就可以。
* 或者这样引用 useRequest `import {useRequest} from '@umijs/hooks'`

**Comment by linvva** [comment]
> 默认的是 response.body
> 
> 但是从 umi 中引用的 useRequest 必须用 data 包一次。
> 
> * 你可以配置一个 `formatResult: d=>d` 就可以。
> * 或者这样引用 useRequest `import {useRequest} from '@umijs/hooks'`

理解了，我自己再另封装一个`useRequest`就可以了，可以在`@umijs/hook`的文档中提一下，方便我这种先看到`@umijs/hook`文档后看到[umi-plugin](https://umijs.org/plugins/plugin-request#userequest)的人，不然完全摸不到头绪😂
