### ISSUE TITLE
useRequest能否支持一开始自动请求初始数据,然后再手动调用

### ISSUE THREAD

**Issue by duwei54** [alibaba/hooks#372]
如题,
在动态搜索一些下拉选项时,希望初始的时候自动请求默认数据.
然后再根据搜索值手动触发run查询.
看了文档貌似不支持这种

**Comment by brickspert** [comment]
支持的。 run 在任何模式都可以调用。

**Comment by duwei54** [comment]
@brickspert 试了一下果然可以的.谢谢解惑 😄
