### ISSUE TITLE
useRequest在初始化渲染时请求接口，设置cacheKey没有缓存数据仍然请求接口

### ISSUE THREAD

**Issue by ISBN9527** [alibaba/hooks#376]
比如 A B 两个路由
A初始化渲染后，跳到B路由，然后返回，在这样的情况下怎么用useRequest缓存数据？

**Comment by ISBN9527** [comment]
@tli4 求大佬解答

**Comment by brickspert** [comment]
数据是缓存了。优先返回缓存的数据，然后在背后重新发起了一次请求。
机制设置的是这样子的。
后面可能会加个参数，阻止重新请求。

**Comment by brickspert** [comment]
重复： #373
