### ISSUE TITLE
useRequest，useFormTable 希望支持changePageSize后，page能置为1

### ISSUE THREAD

**Issue by biglemontree** [alibaba/hooks#379]
useFormTable 希望支持changePageSize后，page能置为1，就像submit搜索时，就自动置为第一页了
`<Table
        columns={columns}
        rowKey="userId"
        {...tableProps}
        onChange={(pag) => {
          console.log(pagination);
          if (pag.pageSize !== pagination.pageSize) {
            pagination.changePageSize(pag.pageSize);
            return submit();
          }
          pagination.changeCurrent(pag.current);
        }}
        pagination={{
          ...tableProps.pagination,
          showQuickJumper: true,
          showSizeChanger: true,
          // onShowSizeChange: (current, size) => reset(),
        }}`
上述达不到changePageSize时，重新请求第一页的目的

**Comment by biglemontree** [comment]
```
<Table 
columns={columns} 
rowKey="userId" {...tableProps} 
onChange={(pag) => { console.log(pagination); if (pag.pageSize !== pagination.pageSize) { pagination.changePageSize(pag.pageSize); return submit(); } 
pagination.changeCurrent(pag.current); }} 
pagination={{ ...tableProps.pagination, showQuickJumper: true, showSizeChanger: true, // onShowSizeChange: (current, size) => reset(), }}
```
贴图

**Comment by brickspert** [comment]
这个逻辑目前和 antd 保持一致的，应该不会的。

你可以这样做。

```
useFormTable(({current, pageSize})=>{
  if(pageSize !== lastPageSize){
     current = 1;
  }
  request();
});
```
