### ISSUE TITLE
hook: useDebounce 没有执行cancel 方法

### ISSUE THREAD

**Issue by 94zn** [alibaba/hooks#387]
useEffect(() => cancel, []);
此语句的目的貌似是首次进来时执行cancel函数吧，但是这样写并不会执行的

https://github.com/umijs/hooks/blob/e27e65ba7b9ea5f8a343f959b0f174b3e0ee7b59/packages/hooks/src/useDebounceFn/index.ts#L50

**Comment by brickspert** [comment]
这句的意思是，卸载的时候执行 cancel。
不是初始化的时候执行呢~
