### ISSUE TITLE
react-native: useMount causes "require cycle" warning

### ISSUE THREAD

**Issue by dsernst** [alibaba/hooks#388]
In a react-native project, if I add:

```tsx
import { useMount } from '@umijs/hooks'
```

and then call

```tsx
useMount(() => {
  console.log('foo')
})
```

within a function component, I get these warnings in my console every time the app reloads:

![image](https://user-images.githubusercontent.com/6340841/81490446-46fc0700-9237-11ea-92ec-cb317d7c0472.png)

Version info:

```
"@umijs/hooks": "^1.9.2",
"react": "16.11.0",
"react-native": "0.62.0",
```

**Comment by brickspert** [comment]
I don't think it is @umijs/hooks's problem...

useMount's source code is so simple, and the warning no keyword about @umijs/hooks~~

```typescript
import { useEffect } from 'react';
import usePersistFn from '../usePersistFn';

const useMount = (fn: any) => {
  const fnPersist = usePersistFn(fn);

  useEffect(() => {
    if (fnPersist && typeof fnPersist === 'function') {
      fnPersist();
    }
  }, [])
};

export default useMount;
```
