### ISSUE TITLE
initalData  data doesn't seem to be working

### ISSUE THREAD

**Issue by maidul98** [alibaba/hooks#389]
Say I have a request:

let getNames = useRequest('url', {
initalData:[]
})

then I expect getNames.data to be [] by default, but sometimes I get undefined. Why does this happen?

**Comment by brickspert** [comment]
https://codesandbox.io/s/use-default-umi-request-mzthz?file=/demo.tsx

I have try this, it work ok.

Can you give me a demo?

**Comment by maidul98** [comment]
My apologies, I had a typo. It is working.
