### ISSUE TITLE
useThrottleFn能否支持在节流前触发？

### ISSUE THREAD

**Issue by PeiTianHuang** [alibaba/hooks#391]
类似于lodash中throttle的leading参数

**Comment by brickspert** [comment]
我们支持下

**Comment by zongjie219** [comment]
能否支持一下 先触式防抖节流

**Comment by awmleer** [comment]
在 ahooks 中 `useThrottle` 和 `useDebounce` 系列的 Hooks 都进行了一次功能升级，底层也是依赖的 lodash ，所以已经可以实现各种高级配置了
详见：https://ahooks.js.org/zh-CN/hooks/side-effect/use-throttle-fn
