### ISSUE TITLE
onSuccess is triggred but response 401

### ISSUE THREAD

**Issue by maidul98** [alibaba/hooks#392]
I am using Fetch as my request handler. When the request is a 401, the Success is still triggered. Why is that?

**Comment by brickspert** [comment]
Best give a demo。

useRequest onSuccess will only trigger because Promise is resolved.

You should check your Promise status.

**Comment by maidul98** [comment]
Where should I check the status of the Promise? Thanks : )

**Comment by brickspert** [comment]
The first params of useRequest is Promise，you should check it's status~~

Or can you provide an online demo？
