### ISSUE TITLE
希望增加一个跨页面通信的hook(基于window. postMessage)

### ISSUE THREAD

**Issue by chenxiaolei** [alibaba/hooks#394]
类似这个: https://github.com/AvraamMavridis/react-window-communication-hook

**Comment by tiyunchen** [comment]
自己封装一个方法好了

**Comment by awmleer** [comment]
未来 umi hooks 会迁移到 [ahooks](https://github.com/alibaba/hooks) 仓库，如果有兴趣的话可以来提 RFC 哈
