### ISSUE TITLE
useRequest发送请求会使当前的函数组件执行三次，造成了不必要的渲染，是否支持配置不返回loading

### ISSUE THREAD

**Issue by mybraveheart** [alibaba/hooks#397]
执行三次，发现其中两次都是用来返回loading的状态的,最后一次才返回data数据，能否支持配置不返回loading，大概不返回loading就不会造成多次渲染吧，或者有没有好的解决方案，因为只需要拿到data的数据。

**Comment by wghglory** [comment]
这个问题我也发现了，怎么解决
