### ISSUE TITLE
为什么run返回的promise都得是resolved呀

### ISSUE THREAD

**Issue by taterboom** [alibaba/hooks#400]
https://github.com/umijs/hooks/blob/e27e65ba7b9ea5f8a343f959b0f174b3e0ee7b59/packages/use-request/src/useAsync.ts#L151

**Comment by Malarkey-Jhu** [comment]
求问 +1

**Comment by Malarkey-Jhu** [comment]
比如在一个event handler (function body)里面，想对run 返回的错误进行处理，如能返回reject就好了

**Comment by brickspert** [comment]
现在可以通过 `onError` 来处理。

**Comment by Malarkey-Jhu** [comment]
是这样的，handler里面，还有要根据run 的执行结果成功与否再进行其他事情，这种情况下onError没法暂停執行或抛出错误

**Comment by Malarkey-Jhu** [comment]
不过都返回resolved是有什么设计上面的考量吗 (好奇

**Comment by rojer95** [comment]
用`onError`岂不是又陷入回调地狱了。

**Comment by brickspert** [comment]
我记得最早是因为请求报错后，用户不希望自己 `catch` ，才改成 `return` 的。

如果改成了 `throw`，所有的 `run` 都需要用户自己去 `catch`，似乎不是很好。满屏都是

```
run().catch()
```

**Comment by brickspert** [comment]
我测试了下，给个最终的解释：如果改成 `throw`，则每个 run 都需要 catch，否则会出问题。

如下示例，如果改成 `throw`，不 `catch` 的情况下会白屏。

```javascript
function getNumber() {
  return Promise.reject(new Error('some error'));
}

export default () => {
  const { data, loading, run, error } = (() => getNumber(), { manual: true });

  return (
    <>
      <Spin spinning={loading}>Number: {data}</Spin>
      <Button onClick={run} style={{ marginTop: 16 }}>
        fetch
      </Button>
    </>
  );
};
```

![image](https://user-images.githubusercontent.com/12526493/83349670-4869ac80-a369-11ea-8b07-6537a4a5710f.png)

**Comment by douxc** [comment]
@brickspert 这样的话有个问题：
```request```的```responseInterceptors```中判断```status、code```，给出了统一的处理和错误提示（根据```业务code```决定），错误的时候会```reject```。手动```run```的时候，就要再次判断返回的值是否合法

**Comment by brickspert** [comment]
> @brickspert 这样的话有个问题：
> `request`的`responseInterceptors`中判断`status、code`，给出了统一的处理和错误提示（根据`业务code`决定），错误的时候会`reject`。手动`run`的时候，就要再次判断返回的值是否合法

我需要再处理下这里的逻辑，先打开问题。我想下~

**Comment by dumeng-chn** [comment]
刚刚被这个小小的坑了一下，觉得这里不太符合逻辑。

**Comment by douxc** [comment]
或许可以再加一个配置catcherror？默认情况抛出异常？

**Comment by brickspert** [comment]
> 或许可以再加一个配置catcherror？默认情况抛出异常？

现在有一个 `throwOnError` 配置，设置为 `true`，就会把异常抛出来。

**Comment by brickspert** [comment]
v2.1.0 已经修复了改问题。

* 默认报错不会触发 run().then() 了
* 通过配置 `throwOnError` 可以正常拿到异常。

**Comment by chqcose** [comment]
![image](https://user-images.githubusercontent.com/6848645/89014591-4e1f4680-d348-11ea-9c73-7173f7b254dd.png)
@brickspert 我觉得你前面说的有道理呀，满屏都是run().catch() 本身也是个问题。虽然只有 throwOnError=true才会抛异常，但返回Promise.reject()满控制台的Uncaught (in promise) 也是问题呀，还是认为异常没被手动处理。

但正常思维，如果我传了options.onError，应该视为出现的error在onError里处理好了吧。如你所说 promise.catch().then()肯定会执行

**Comment by Uyarn** [comment]
好尴尬 本来相同的业务请求想收口到一个customHook里面 现在好像还是得在具体业务逻辑各自catch?
