### ISSUE TITLE
useDocumentVisibility 在 Safari 下不能正确地更新状态

### ISSUE THREAD

**Issue by awmleer** [alibaba/hooks#401]

**Comment by chenbin92** [comment]
@awmleer 

不能正确的更新状态是指什么 ？

查了下 `VisibilityState` 兼容性 Safari 是正常的，测试如下：

![image](https://user-images.githubusercontent.com/3995814/86527957-6c735d00-bed6-11ea-8521-4ef641c5aca7.png)

**Comment by awmleer** [comment]
切换到其他 tab 下，状态会一直保持 `visible`，按理说应该变成 `hidden` 的
