### ISSUE TITLE
Using refreshDeps and run on useRequest 

### ISSUE THREAD

**Issue by Kol96** [alibaba/hooks#404]
使用useRequest时，我希望实现下面两个功能：
1、在userId变化时拿着缓存的params请求数据
2、在点击按钮后更新userId并且更新params 然后请求数据

问题：第二个功能，会导致两次请求，第一次由run触发，会使用过期的userId；第二次由userId触发。

代码如下
```
export default () => {
  const [userId, setUserId] = useState('1');
  const { data, loading } = useRequest((params) => getUserSchool(userId, params), {
    refreshDeps: [userId]
  });
  const handleClick = () => {
    setUserId('2')
    run("some params")
  }

  return <div>...</div>
}
```

**Comment by brickspert** [comment]
建议不要用 refreshDeps 了，自己通过 `run` 控制请求时机。

**Comment by Kol96** [comment]
把params也作为一个state 放在refreshDeps里 是不是也可行

**Comment by brickspert** [comment]
> 把params也作为一个state 放在refreshDeps里 是不是也可行

返回值有个 params 属性的，你可以拿出来自己做操作哦。

**Comment by dengfuping** [comment]
这样的设计很不方便，如果在 useEffect 里面手动去 run，那 refreshDeps 的意义就不大了。建议将 defaultParams 改为 params，且与 refreshDeps 进行联动。
