### ISSUE TITLE
useKeyPress在Mac系统下的谷歌浏览器失效

### ISSUE THREAD

**Issue by JustForLucky** [alibaba/hooks#405]
系统版本：macOS 10.15.4
浏览器版本：83.0.4103.61（正式版本）

`useKeyPress('ctrl.alt.c', () => {})`
`useKeyPress('ctrl.alt.space', () => {})`

以上代码都不起作用。
问题原因是对比event.key，但是在当前环境中event.key != key。

建议：对比event.keyCode。

**Comment by chenbin92** [comment]
试了下如下图所示 DEMO3 演示正常

![demo](https://user-images.githubusercontent.com/3995814/86528269-fcb2a180-bed8-11ea-9e7e-fe3d31f81e89.gif)

**Comment by brickspert** [comment]
同测试 ok，暂时关闭了哈？如果有进一步反馈再打开哈。
