### ISSUE TITLE
useFormTable这个函数可以同时更新dataSource和pageSize这两个字段吗

### ISSUE THREAD

**Issue by jiawei163com** [alibaba/hooks#407]
问题是这样的: 我使用useFormTable里面的onChange来切换table展示数量的时候, pageSize更新了,但是dataSource还没有更新, 这样就导致了dataSource长度大于pageSize长度
![pageSize](https://user-images.githubusercontent.com/48401444/83124728-283bb280-a109-11ea-89a2-b8eb81eb2024.png)

![image](https://user-images.githubusercontent.com/48401444/83124665-10fcc500-a109-11ea-8e90-c7c64e2a576c.png)
就是可否同时更新dataSource和pageSize

**Comment by brickspert** [comment]
理论上当你变更了 pageSize 之后，才去后端请求 dataSource，所以不能同时更新的。

你给 Table 加个 loading 试试？

**Comment by jiawei163com** [comment]
嗯好吧我试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 砖家 <notifications@github.com&gt;
发送时间: 2020年5月28日 20:28
收件人: umijs/hooks <hooks@noreply.github.com&gt;
抄送: Mr Chen <1541986022@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[umijs/hooks] useFormTable这个函数可以同时更新dataSource和pageSize这两个字段吗 (#407)





 
理论上当你变更了 pageSize 之后，才去后端请求 dataSource，所以不能同时更新的。
 
你给 Table 加个 loading 试试？
