### ISSUE TITLE
useInViewport 增加可见区域百分比

### ISSUE THREAD

**Issue by vanishcode** [alibaba/hooks#409]
目前实现了 useInViewport 返回第三个 元素可见部分百分比 的参数，原因是某些业务场景对于“真实展现”和“展现”有要求，需要区分。见下图

![](https://p3.ssl.qhimg.com/t01dbfcf63b397a9ad9.png)

![](https://p3.ssl.qhimg.com/t0182cc2371a45701ed.png)

有个问题在于 `IntersectionObserver` 调用是不太精确的所以返回的百分比也是不太精确的。下面是我的比较粗略的实现方式

```js
new IntersectionObserver(entries => { ... }, {
  threshold: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
})
```

如果可以接受的话我就补充一下测试用例提pr了

**Comment by brickspert** [comment]
我们正在开发 2.0，我们评估下，如果可以的话，我们集成到 2.0 中。

**Comment by brickspert** [comment]
可以贡献在这里：https://github.com/alibaba/hooks

但是基于 useInViewport 修改的话，是 breakchange 了。
1. 如果要基于 useInviewport 搞，需要考虑如何兼容。
2. 或者新开个 Hooks 也可以

**Comment by vanishcode** [comment]
> 可以贡献在这里：https://github.com/alibaba/hooks
> 
> 但是基于 useInViewport 修改的话，是 breakchange 了。
> 
> 1. 如果要基于 useInviewport 搞，需要考虑如何兼容。
> 2. 或者新开个 Hooks 也可以

好的，我新开个hooks
