### ISSUE TITLE
useSessionStorageState和useLocalStorageState直接保存字符串有问题

### ISSUE THREAD

**Issue by chj-damon** [alibaba/hooks#412]
```ts
const [message, setMessage] = useSessionStorageState('hello', 'Hello~~');

<Button onClick={() => setMessage('hahaha')}>保存</Button>
```
然后直接用`sessionStorage.getItem('hello')`，发现取出来的字符串是""hahaha""，被多包了一层。
localstorage也有同样的问题

**Comment by awmleer** [comment]
这个是预期行为，因为要支持 object 的存储，所以所有的值在 `setItem` 前都会先经过 `JSON.stringify`

**Comment by chj-damon** [comment]
？？？为什么要关掉？你想要支持object的存储，至少要先判断一下是不是object吧？typeof xxx === 'string'，如果是string的话，为什么还要走JSON.stringify

**Comment by awmleer** [comment]
虽然如你所说，存储数据的时候是可以判断出数据类型的，但是取数据的时候，并不知道数据的类型，所以需要对所有的数据都进行 JSON 的序列化和反序列化

**Comment by chj-damon** [comment]
关键是你这样做，对我用原生的`sessionStorage.getItem`写法造成影响了啊。这难道不是问题吗？

**Comment by awmleer** [comment]
的确是问题，会对你手动 `getItem` 造成一点影响，但是我觉得是可解的呀，在 getItem 之后手动 `JSON.parse` 一下，保持和 `useSessionStorageState` 的逻辑一致
如果你有更好的方案的话，也可以给我们提一个 PR～
