### ISSUE TITLE
useFormTable 建议返回一个refresh方法

### ISSUE THREAD

**Issue by xiexingen** [alibaba/hooks#418]
使用场景
1、先输入内容搜索
2、翻页，比如到第三页
3、修改数据(弹窗形式的)；修改完后 如果调用submit方法那页面就不在了
这种情况下应该是重新加载第三页的数据
看是不是在useFormTable的结果里面再返回一个refresh方法，调用这个方法就相当于用最后的查询条件重新查询一次

**Comment by brickspert** [comment]
有 `refresh` 的呢，可以直接用的。`useRequest` 的参数都可以用。
