### ISSUE TITLE
useRequest 触发重绘较多

### ISSUE THREAD

**Issue by nanxiaobei** [alibaba/hooks#419]
用 `create-react-app` 建了个全新项目，将 `App.jsx` 改为：

```jsx
import { useRequest } from "@umijs/hooks";

function App() {
  const { data } = useRequest(() => fetch("https://reqres.in/api/users?page=2"));
  console.log("data", data);
  ...
```
别的未做修改。

发现 useRequest 调用了 6 次，触发了 6 次 re-render。

![XU9Q4.png](https://s3.jpg.cm/2020/06/08/XU9Q4.png)

这个调用次数是否过多？

**Comment by awmleer** [comment]
这个是预期行为。。 @brickspert 评估一下要不要做优化？

**Comment by AnranS** [comment]
你把<React.StrictMode>去掉会少一半

**Comment by nanxiaobei** [comment]
@AnranS 好的我试试

**Comment by brickspert** [comment]
https://github.com/facebook/react/issues/15074

这是 React StrictMode 故意的行为

**Comment by meepo-it** [comment]
请问，去除React StrictMode，之后剩余的多次重渲染，是谁触发的呢？

**Comment by brickspert** [comment]
> 请问，去除React StrictMode，之后剩余的多次重渲染，是谁触发的呢？

剩余的就是 useRequest 触发的，不过应该不会存在浪费的渲染的，所有的渲染肯定都是状态变化了。
