### ISSUE TITLE
一个组件中构建多个useRequest，如何管理这些请求

### ISSUE THREAD

**Issue by mu1004** [alibaba/hooks#422]
Promise.all   相关操作怎么处理？

**Comment by brickspert** [comment]
https://hooks.umijs.org/zh-CN/hooks/async#1-%E6%88%91%E5%8F%AF%E4%BB%A5%E5%9C%A8%E4%B8%80%E4%B8%AA%E7%BB%84%E4%BB%B6%E4%B8%AD%E4%BD%BF%E7%94%A8%E5%A4%9A%E4%B8%AA-userequest-%E5%90%97%EF%BC%9F

```
const firstRequest = useRequest(service);
const secondRequest = useRequest(service);

// firstRequest.loading
// firstRequest.data

// secondRequest.loading
// secondRequest.data
```

**Comment by mu1004** [comment]
@brickspert  你好， 我可能没表述清楚， 一个组件多个request，怎么让他们同时发起请求呢？又怎么控制他们发起的顺序，比如请求A的数据依赖请求B

**Comment by brickspert** [comment]
> @brickspert 你好， 我可能没表述清楚， 一个组件多个request，怎么让他们同时发起请求呢？又怎么控制他们发起的顺序，比如请求A的数据依赖请求B

ahooks：https://ahooks.js.org/zh-CN/hooks/async#%E4%BE%9D%E8%B5%96%E8%AF%B7%E6%B1%82

我们发布了 v2 版本，新增了 ready 参数，可以升级下试试。
