### ISSUE TITLE
useFormTable ajax请求报没有finally函数的异常 antdpro2.2.1

### ISSUE THREAD

**Issue by lyqgit** [alibaba/hooks#426]
TypeError: this.service.apply(...).then(...).catch(...).finally is not a function

**Comment by lyqgit** [comment]
使用的fetch， firefox浏览器支持finally函数

**Comment by brickspert** [comment]
需要装一个 babel-polyfill

可以参考：https://lubyxu.github.io/2019/02/16/guide/

**Comment by x-ray-s** [comment]
作为一个可以单独使用的 lib 不提供 ES5 版本吗？`umi-request` 中引用的 `useAsync` 中代码需要 Polyfill，让使用者自己加？
`node_modules` 作为多数 `babel-loader` 的默认 `exclude` 配置，还要为了你这个单独加进去？
还是要在使用 `umi-request` 的地方首先要 `require('core-js/modules/es.promise.finally')` 放在代码最上面？
还是必须在我代码里用过 `Promise.prototype.finally` 来触发 `preset-env` ? 
如果是这样。麻烦写文档上，要么给一个 Browser Support 的列表，来告诉使用者就不支持。
如果用  `umi-request` 跟 `axios` 作为竞品，你看 axios 让你自己加 Polyfill 了吗？

**Comment by awmleer** [comment]
Documentation updated via #574 .

**Comment by SpiritQAQ** [comment]
半年过去了...

**Comment by turkyden** [comment]
@SpiritQAQ  项目还在吗？

**Comment by DevanXU** [comment]
这个问题烂尾了？

**Comment by victorWuxz** [comment]
遇到了同样的问题，浏览器是明显支持promise的，在console中可以打印，但就是报错
