### ISSUE TITLE
请问useVirtualList是否不支持一行有多个元素的情况哦？

### ISSUE THREAD

**Issue by PeiTianHuang** [alibaba/hooks#435]
目前的总高度是按单个的高度乘以总个数来算的，而我们网站有点像淘宝那种商品展示，一行会有多个商品，所以出现了大量的空白~

**Comment by chenbin92** [comment]
@PeiTianHuang  提供一下 demo

**Comment by PeiTianHuang** [comment]
> @PeiTianHuang 提供一下 demo

你好，在官方示例那里调整2行代码即可：
https://codesandbox.io/s/yymup?module=/demo.tsx&file=/demo.tsx
![image](https://user-images.githubusercontent.com/17986764/85189715-cd4e4300-b2e3-11ea-8b45-592e32f203a6.png)

**Comment by PeiTianHuang** [comment]
![image](https://user-images.githubusercontent.com/17986764/85196830-76f6f980-b30f-11ea-989b-ddb89acc2d79.png)
![image](https://user-images.githubusercontent.com/17986764/85196843-8d9d5080-b30f-11ea-823a-f12596a241ff.png)


https://codesandbox.io/s/yymup?module=/demo.tsx&file=/demo.tsx

可以在这个官方示例中修改三行代码进行重现（由于修改了itemHeight的值，所以空白问题暂时得到解决，但还是存在其他问题），改动后拉到70+左右，可看到向下滑动一点点距离时，有不定个项发生了变化（期望是整行一起出现或隐藏）

**Comment by PeiTianHuang** [comment]
此时的滚动效果异常，并没有正常的滚动，而只是小幅移动后刷新了数据，有那种一闪一闪的效果

**Comment by ttys026** [comment]
@PeiTianHuang 这个用样式进行多列的布局确实不是预期的用法，现在想到一个可行的办法是使用确定的每行的 item 个数（例如 3 个）封装成一个组件，然后用虚拟列表展示 总数量 / 3 行。

**Comment by PeiTianHuang** [comment]
> @PeiTianHuang 这个用样式进行多列的布局确实不是预期的用法，现在想到一个可行的办法是使用确定的每行的 item 个数（例如 3 个）封装成一个组件，然后用虚拟列表展示 总数量 / 3 行。

你好，目前因为需要实现的效果是一行摆放不下时才另起一行（子项为inline-block），所以每行的元素个数是不定的...

**Comment by ttys026** [comment]
目前这个 hook 的适用场景还覆盖不了复杂的情况，默认是支持单列多行的虚拟列表，这里提到的 masonry 的场景，可以参考 react-virtualized 的 demo：
https://bvaughn.github.io/react-virtualized/#/components/Masonry

**Comment by PeiTianHuang** [comment]
> masonry

非常感谢您的指点

**Comment by PeiTianHuang** [comment]
> 目前这个 hook 的适用场景还覆盖不了复杂的情况，默认是支持单列多行的虚拟列表，这里提到的 masonry 的场景，可以参考 react-virtualized 的 demo：
> https://bvaughn.github.io/react-virtualized/#/components/Masonry

非常感谢您的指点
