### ISSUE TITLE
RFC: useInterval

### ISSUE THREAD

**Issue by awmleer** [alibaba/hooks#437]
# API

```ts
function useInterval(fn: () => void, interval: number, options: {
  immediate?: boolean
})
```

- 当 `interval` 的单位为 ms，当其取值为 `null` 或 `undefined` 时，会禁用掉 interval 效果
- `immediate` 参数可以用来控制是否在首次渲染时立即执行 `fn`，默认为 `false`

# Demo

```jsx
useInterval(() => {
  console.log('hello')
}, 1000, {immediate: true})
```

**Comment by brickspert** [comment]
1. 是不是可以返回 `run` , `stop` 控制定时器的开始和停止？
2. 是不是可以加个 `manual` 控制定时器是否默认开启？

```
const { run, stop, running } = useInterval(()=>{}, 1000, {
  manual: true,
  immediate: false,
});
```

**Comment by awmleer** [comment]
定时器可以通过 `interval` 为 `null` 或 `undefined` 来禁用，`run` `stop` `running` `manual` 其实就是：

```js
const [running, { toggle, setTrue: run, setFalse: stop }] = useBoolean(!manual)
```

感觉可以通过组合使用的没有必要强耦合在一起，在文档上写一下这种配合使用的用法就可以了。。

**Comment by ttys026** [comment]
感觉还是需要 run, stop, running 这三个返回结果的，自己拼要多用个 hook，而且比较难理解。
另外如果 有 immediate 的概念的话，是不是要区分 startCountDown 和 executeOnceAndStartCountDown 两个概念

**Comment by brickspert** [comment]
> 感觉还是需要 run, stop, running 这三个返回结果的，自己拼要多用个 hook，而且比较难理解。
> 另外如果 有 immediate 的概念的话，是不是要区分 startCountDown 和 executeOnceAndStartCountDown 两个概念

同意有  run, stop, running 三个返回。

但 startCountDown 和 executeOnceAndStartCountDown 就没必要了吧，没场景需要把~

**Comment by awmleer** [comment]
> 是不是要区分 startCountDown 和 executeOnceAndStartCountDown 两个概念

immediate 就是 executeOnceAndStartCountDown 了，不启用 immediate 就是 startCountDown

**Comment by awmleer** [comment]
run stop running 我之所倾向于不加的原因：
1. 使用场景并不多
2. 既然加了这些控制状态，是不是还需要再加上 initialRunning 参数，是不是还要加上 toggle 方法？用户的各种具体使用场景无穷无尽，不可能满足所有人的需求

我觉得所有的 Hooks 都应该尽可能的细粒度，一方面是便于用户自由组合和扩展，另一方面也可以降低学习成本。如果用户需要 run stop running 这些东西的话，我觉得更应该是让用户自己去封装一个 custom Hook，就像 react-intl 的[做法](https://formatjs.io/docs/react-intl/api/#useintl-hook)，我们可以在文档上写出这样的 demo

**Comment by awmleer** [comment]
所以确定一个结论？要不我们先不加上这些额外的 feature？如果后面真的需要的话，也可以再加上，不会产生 break change。。 @brickspert

**Comment by brickspert** [comment]
> 所以确定一个结论？要不我们先不加上这些额外的 feature？如果后面真的需要的话，也可以再加上，不会产生 break change。。 @brickspert

可以。+1
