### ISSUE TITLE
如何让兄弟组件的 useRequest 进行 refresh?

### ISSUE THREAD

**Issue by dpyzo0o** [alibaba/hooks#440]
比如我有 A B 两个兄弟组件, A 组件内部有一个 useRequest, 我在 B 组件里面进行了某些操作，然后需要让 A 组件的 useRequest 进行刷新获取最新的数据, 有什么好的方法吗？

**Comment by dpyzo0o** [comment]
swr 可以通过 [Manually Revalidate](https://github.com/vercel/swr#manually-revalidate) 实现全局的任意一个 useSWR 进行刷新, useRequest 我在文档上没有看到类似的实现方案

**Comment by brickspert** [comment]
暂时不支持这个能力，需要新增。

**Comment by dpyzo0o** [comment]
> 暂时不支持这个能力，需要新增。

这种需求场景应该是很常见的，B组件里修改了服务器上的数据，然后A组件需要显示最新的数据。一般碰到这种场景都是怎么处理的呀

**Comment by dpyzo0o** [comment]
我想到的办法就是在父组件加个 state, 然后这个 state 放在 A 组件 useRequest 的 deps 里面, 然后在 B 组件去修改这个 state

**Comment by brickspert** [comment]
你可以使用状态管理器来管理外部的状态。比如 hox 等。

**Comment by xingming2020** [comment]
假设a是数据钩子，b是修改数据钩子，想要在请求b后刷新a。尝试封装为单独的hook文件，但是发现无法在b的onSuccess方法中调用a的refresh方法，报错Hooks can only be called inside the body of a function component.

useRequest现在是否支持类似react query的[Invalidation from Mutations](https://react-query.tanstack.com/guides/invalidations-from-mutations)或swr的[Revalidate](https://swr.vercel.app/docs/mutation#revalidate)对全局任意useRequest进行刷新，上面 @dpyzo0o 也提到过

目前的解决方案是在组件中使用b的runAsync发起修改数据请求，在其回调中调用a的refresh进行数据刷新，但是这部分逻辑应该直接封装在b钩子中而不是写在组件里。不知是否有其它方案实现，请教一下 @brickspert
