### ISSUE TITLE
useRequest loadingDelay不起作用

### ISSUE THREAD

**Issue by gwwnha** [alibaba/hooks#441]
请问你们可以么？我使用了没什么变化

**Comment by brickspert** [comment]
官方 demo 测试没问题。可以提供一下有问题的在线示例吗？

**Comment by brickspert** [comment]
暂时先关闭了，后续如果能复现的话再打开~

**Comment by uWydnA** [comment]
官方demo复现出了BUG：https://codesandbox.io/s/white-resonance-jsmxv?fontsize=14&hidenavigation=1&theme=dark

**Comment by luichooy** [comment]
我是用了也不起作用
