### ISSUE TITLE
Cannot call an event handler while rendering 问题探讨

### ISSUE THREAD

**Issue by nanxiaobei** [alibaba/hooks#443]
使用 `useRequest` 发现报错 "Cannot call an event handler while rendering"，

我的使用场景是，

```jsx
<A>
    <B />
</A>
```

在组件 A 中定义了一个手动触发的 request，然后通过 props 传给组件 B 内部使用，

两个组件执行顺序是：

```
↓  A int（定义 request）
↓  A render
↓          B init
↓          B render
↓          B useEffect（执行 request）
↓  A useEffect
```

看了下报错代码，`useRequest` 的 `utils/usePersistFn` 中存在代码如下：

![c6tKf.png](https://s3.jpg.cm/2020/06/21/c6tKf.png)

似乎是 A 中定义的 request，等到 A 的 `useEffect` 中才赋值，而在上面的场景中，还未走到 A 的 `useEffect` 就去执行，所以报错了。

以上，如果我没理解错的话 ... 继续以下，

想探讨一下，目前这种 useEffect 中再赋值，有没有到考虑上面这种父传子情况？

应该还是个挺常见的用例，而目前定义不能覆盖上面这种用例，

如果有考虑到，请问下是有什么原因，而没有去适配这种用例。

**Comment by brickspert** [comment]
useRequest 的 usePersistFn 写错了。正常应该是和下面代码一致的：

https://github.com/alibaba/hooks/blob/master/packages/hooks/src/usePersistFn/index.ts

我需要修正下 useRequest 的 usePersistFn 写法

```ts
import { useCallback, useRef } from 'react';

export type noop = (...args: any[]) => any;

function usePersistFn<T extends noop>(fn: T) {
  const ref = useRef<any>(() => {
    throw new Error('Cannot call function while rendering.');
  });

  ref.current = fn;

  const persistFn = useCallback(((...args) => ref.current(...args)) as T, [ref]);

  return persistFn;
}

export default usePersistFn;

```

**Comment by brickspert** [comment]
v2.0.1 已修复~
