### ISSUE TITLE
在umi-request的拦截器里面怎么抛异常可以在useRequest的onError里面拿到

### ISSUE THREAD

**Issue by chj-damon** [alibaba/hooks#450]
我用的umi-request，想要在response的拦截器里面对后端返回的数据做一些校验，如果校验不通过，抛出异常，然后在useRequest的onError里面把异常打印出来。但是实际上并没有走onError.

试过了throw new Error(errorText)，return Promise.reject(errorText),都没用。

想请教一下在拦截器里面抛异常的正确做法应该是什么样的？

**Comment by brickspert** [comment]
Maybe you should find the answer from [https://github.com/umijs/umi-request](https://github.com/umijs/umi-request).
Or you can refer to this [plugin-request](https://umijs.org/plugins/plugin-request), which have same logic.
