### ISSUE TITLE
useSize 参数中的 ref 与 React 类型不符合

### ISSUE THREAD

**Issue by MinJieLiu** [alibaba/hooks#451]
迁移之后
![image](https://user-images.githubusercontent.com/6167727/85390134-f3414500-b57a-11ea-9753-db2312702bb8.png)
加上 null 参数后
![image](https://user-images.githubusercontent.com/6167727/85390176-03f1bb00-b57b-11ea-94ef-989dd9eac17b.png)

**Comment by brickspert** [comment]
It's not hooks bug. you shuld add `null` for useRef

```
const ref = React.useRef<HTMLDiveElement>(null)
```

**Comment by MinJieLiu** [comment]
再仔细看看第一张图
就是你所推荐那样写的才报错的
```js
const ref = React.useRef<HTMLDiveElement>(null)
```

![image](https://user-images.githubusercontent.com/6167727/85939412-d2486d80-b947-11ea-879d-771b66a35592.png)

**Comment by brickspert** [comment]
> 就是你所推荐那样写的才报错的

最新的版本应该是没这个问题了吧？已经修复过一次了。

**Comment by MinJieLiu** [comment]
我是升级到 2.0.1 中出现的问题

**Comment by smajl** [comment]
@brickspert Still a problem with 2.1.0

**Comment by brickspert** [comment]
测试了下，这种用法没问题
```
  const ref = React.useRef<HTMLDivElement>()
  const state = useSize(ref);
```

加个 null 就不对了，还是不要加 null 了
```
  const ref = React.useRef<HTMLDivElement>(null)
  const state = useSize(ref);
```

**Comment by MinJieLiu** [comment]
@brickspert 

React 中 ref 的定义
```ts
interface RefObject<T> {
  readonly current: T | null;
}
```
不加 null 则会 `Type 'undefined' is not assignable to type 'HTMLDivElement | null'. `

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/88281383-27468c00-cd1a-11ea-96af-a5f55b10e839.png)

各种测试也没问题，要不老哥来个 PR？

**Comment by wocaatm** [comment]
我在用到useHover的时候也出现了这个问题，同样是类型不符

**Comment by brickspert** [comment]
> 我在用到useHover的时候也出现了这个问题，同样是类型不符

已经修复，下个版本发布~
