### ISSUE TITLE
useSessionStorageState useStorageState shouldn't use stringify

### ISSUE THREAD

**Issue by ycjcl868** [alibaba/hooks#453]
https://github.com/alibaba/hooks/blob/c423c89465fa69f78a78fb6dee68138001e4f50b/packages/hooks/src/useStorageState/index.ts#L46

if I just storage a string value, 

```
const [storeState, setStoreState] = useSessionStorageState('hello');

useEffect(() => {
   setStoreState('666');
}, [])
```

expected

```
hello  | 666
```

reality

```
hello | "666"
```

![image](https://user-images.githubusercontent.com/13595509/85668078-df1f5400-b6f0-11ea-9df1-dc0aa6f7b4f2.png)

**Comment by brickspert** [comment]
Duplicate: #412

**Comment by awmleer** [comment]
This is the expected behavior and I believe it has been fully discussed before. #412
