### ISSUE TITLE
useSelections测试用例问题

### ISSUE THREAD

**Issue by iamwelk** [alibaba/hooks#457]
useSelections测试用例无法通过测试

**Comment by ttys026** [comment]
github 上的 ci 和我本地都无法复现，是用的 master 最新的代码跑的测试吗？

**Comment by iamwelk** [comment]
```javascript
it('toggle should work correct', async () => {
      act(() => {
        hookUtils(hook).helper.toggle(1);
      });
      expect(hookUtils(hook).seleected).toEqual([1]);  // 比如这里，不应该是[]吗
      expect(hookUtils(hook).helper.isSelected(1)).toEqual(true); // false
      expect(hookUtils(hook).helper.allSelected).toEqual(false);
      act(() => {
        hookUtils(hook).helper.toggle(1);
      });
      expect(hookUtils(hook).seleected).toEqual([]); // [1]
      expect(hookUtils(hook).helper.isSelected(1)).toEqual(false); // true
      expect(hookUtils(hook).helper.allSelected).toEqual(false);
    });
```

**Comment by iamwelk** [comment]
> github 上的 ci 和我本地都无法复现，是用的 master 最新的代码跑的测试吗？

https://github.com/alibaba/hooks/issues/457#issuecomment-651046014

**Comment by brickspert** [comment]
> ```js
> it('toggle should work correct', async () => {
>       act(() => {
>         hookUtils(hook).helper.toggle(1);
>       });
>       expect(hookUtils(hook).seleected).toEqual([1]);  // 比如这里，不应该是[]吗
>       expect(hookUtils(hook).helper.isSelected(1)).toEqual(true); // false
>       expect(hookUtils(hook).helper.allSelected).toEqual(false);
>       act(() => {
>         hookUtils(hook).helper.toggle(1);
>       });
>       expect(hookUtils(hook).seleected).toEqual([]); // [1]
>       expect(hookUtils(hook).helper.isSelected(1)).toEqual(false); // true
>       expect(hookUtils(hook).helper.allSelected).toEqual(false);
>     });
> ```

测试用例看着没啥问题。你是怎么跑的测试用例？

**Comment by iamwelk** [comment]
> > ```js
> > it('toggle should work correct', async () => {
> >       act(() => {
> >         hookUtils(hook).helper.toggle(1);
> >       });
> >       expect(hookUtils(hook).seleected).toEqual([1]);  // 比如这里，不应该是[]吗
> >       expect(hookUtils(hook).helper.isSelected(1)).toEqual(true); // false
> >       expect(hookUtils(hook).helper.allSelected).toEqual(false);
> >       act(() => {
> >         hookUtils(hook).helper.toggle(1);
> >       });
> >       expect(hookUtils(hook).seleected).toEqual([]); // [1]
> >       expect(hookUtils(hook).helper.isSelected(1)).toEqual(false); // true
> >       expect(hookUtils(hook).helper.allSelected).toEqual(false);
> >     });
> > ```
> 
> 测试用例看着没啥问题。你是怎么跑的测试用例？

我这里截取的部分看起来是正常的，但是在实际的测试文件中，初始条件是[1]而不是[]
可以去原始的测试文件里面去看

**Comment by iamwelk** [comment]
不好意思，本地环境问题，打扰了

**Comment by iamwelk** [comment]
不过测试用例都依赖于同一个setup，下一个测试用例依赖上一个执行的结果，感觉不是太好。。
