### ISSUE TITLE
建议不要依赖 regenerator-runtime

### ISSUE THREAD

**Issue by yesmeck** [alibaba/hooks#46]
通常的做法应该是让项目自己去加。

现在的影响是 @umijs/hooks 没法在 remax 里用，因为 regenerator-runtime 0.13 版本用了 `Function`，小程序里不支持。

**Comment by brickspert** [comment]
好，收到。 之前是其他项目引用 umijs/hooks 后出错，才加了这个依赖，下个版本我们考虑删除掉，预计明天发新版本。

**Comment by brickspert** [comment]
已发布 v1.0.0

**Comment by G-WangZH** [comment]
没有引入regenerator-runtime报错，是什么原因

**Comment by brickspert** [comment]
> 没有引入regenerator-runtime报错，是什么原因

参考：https://github.com/umijs/hooks/issues/230
