### ISSUE TITLE
useDrag的拖拽input里的文字也会触发拖拽事件

### ISSUE THREAD

**Issue by urnotzane** [alibaba/hooks#461]
我想通过拖拽选中input里的文字，但是因为父级dom元素有用useDrag，所以无法选中，只能进行拖拽，可否给个方案解决这样的问题？
<img width="811" alt="BDC2CF8B-E3B8-4ACF-9AC2-453B05995A9A" src="https://user-images.githubusercontent.com/27631594/85994967-5fff8800-ba30-11ea-9529-462aad0974e3.png">

**Comment by ttys026** [comment]
https://codesandbox.io/s/divine-platform-jerue?file=/demo.tsx
写了一个 demo，可以在 focus 时禁止 drag
