### ISSUE TITLE
ready和refreshDeps配合时只会在第一次生效

### ISSUE THREAD

**Issue by chj-damon** [alibaba/hooks#468]
```js
useRequest(service, {
  ready: menus.length > 0,
  refreshDeps: [menus.length]
});
```
在如上的场景中，ready和refreshDeps都依赖了menus，当menus的长度发生变化时，比如清空menus，这时候refreshDeps会重新发请求，但是这时候的ready是false，按理说这个请求就应该被block掉。
实际上请求还是发出去了。
所以我认为这个地方是个bug，任何时候发请求都应该去看一下ready条件是否成立。

**Comment by we6288815** [comment]
同有这个需求，有计划修改吗？

**Comment by marsshen77** [comment]
+1

**Comment by s97712** [comment]
+1

**Comment by WangJM001** [comment]
+1

**Comment by lf-wxp** [comment]
+1

**Comment by wyl1201** [comment]
+1

**Comment by paradox010** [comment]
+1

**Comment by steveleeh** [comment]
+1

**Comment by linxianxi** [comment]
@brickspert  没有进展么，refreshDeps 和 ready 配合不行

**Comment by steveleeh** [comment]
比如依赖于商品id去查询，开始没有商品id也不请求这没问题，然后现在商品id从有值又变成空值状态了，这个时候refreshDeps还去请求空id就会报错。
这块即使改成了refreshDeps的时候去判断ready也会有问题，相当于你是空id，但是data是上一次请求的数据。这个时候业务可能是希望空id对应的数据是置空的。
所以我现在的解决办法就是自己监听id，来发判断请不请请求和数据操作，写起来挺繁琐的。

**Comment by weird94** [comment]
+1 +1 这个设计感觉真的有问题，感觉是个bug都不是feature了

**Comment by brickspert** [comment]
下个大版本修，在开发中了。https://www.yuque.com/dg9vsw/ig6de4/pqghdx

**Comment by brickspert** [comment]
related: https://github.com/alibaba/hooks/discussions/1291

可以来这里讨论 ready 的行为。

**Comment by fakership** [comment]
那2.0版本就啥解决方案么 @brickspert
