### ISSUE TITLE
useRequest和UseRequestProvider的onError都无法捕获umi-request的errorHandler抛出的异常

### ISSUE THREAD

**Issue by chj-damon** [alibaba/hooks#472]
重现最小仓库地址：
https://github.com/chj-damon/useRequestErrorReproduceDemo

**Comment by brickspert** [comment]
UseRequestProvider 要再往外面包一层。

useRequest 要在 UseRequestProvider 子组件中。

**Comment by chj-damon** [comment]
代码改了，把useRequest放到了UseRequestProvider里面，但是效果一样。onError还是捕获不了errorHandler抛出的error：
![image](https://user-images.githubusercontent.com/4902684/86548034-92980c00-bf6d-11ea-9ef6-3d9c1b8ee2fd.png)

**Comment by brickspert** [comment]
useRequest 是处理 promise 类型的 service 的。
如果 service 是 reject 的，就能捕获到。你先看看 service promise 是不是变成 reject 了。

**Comment by chj-damon** [comment]
终于搞明白了。原来errorHandler抛出的异常要自己catch一下，然后在catch里面用Promise.reject处理，才能够被useRequest的onError捕获。

**Comment by xianghongai** [comment]
在 Hooks 之前捕获和处理异常逻辑，决定是 401 还是发放到组件中；
流到 Hooks 中的异常，已经是需要“通知”给用户的偏“业务”的异常交互了。
