### ISSUE TITLE
useDynamicList antd v4 Form

### ISSUE THREAD

**Issue by tnduc** [alibaba/hooks#473]
I am using antd form v4, I am having problems with the input name:
[https://ahooks.js.org/hooks/ui/use-dynamic-list#dyanmic-tabledraggable](https://ahooks.js.org/hooks/ui/use-dynamic-list#dyanmic-tabledraggable)

e.g
```
render: (text: string, row: Item, index: number) => (
        <Form.Item name={`attributes[${getKey(index)}].name`}>
                  <Input />
        </Form.Item>
 ),
```

output: `attributes[0].name`

how to get the same result: `attributes: [{name: 'blabla']`

**Comment by ttys026** [comment]
We will add a more detailed demo later on.
For now you can refer to the csb for how to use with antd4.
https://codesandbox.io/s/fervent-maxwell-mu7lj?file=/demo.tsx
