### ISSUE TITLE
this.service.apply(...).then(...).catch(...).finally is not a function

### ISSUE THREAD

**Issue by Smi1e96** [alibaba/hooks#474]
# 在taro项目中使用ahook出现this.service.apply(...).then(...).catch(...).finally is not a function

在真机测试阶段就会出现下图
问题如下
![image](https://user-images.githubusercontent.com/31199247/86310549-f4e0cc00-bc50-11ea-9147-1f85f513bb39.png)

项目源码包
[taro3.zip](https://github.com/alibaba/hooks/files/4861704/taro3.zip)

**Comment by brickspert** [comment]
Duplicated: #426

**Comment by Smi1e96** [comment]
@brickspert  找到原因了 是小程序 ios版不支持Promise.finally :sweat:

**Comment by brickspert** [comment]
> @brickspert 找到原因了 是小程序 ios版不支持Promise.finally 😓

这个我们这边也要兼容下。

**Comment by Smi1e96** [comment]
@brickspert  我现在暂时的处理方法 在小程序 onload 里面运行 
```javascript
    new Promise(function() {
    }).then(function(){
    }).catch(function(){
    }).finally(function(){
    });
```
让他引入兼容包

**Comment by Smi1e96** [comment]
> > @brickspert找到原因了是小程序ios版不支持Promise.finally😓
> 
> 这个我们这边也要兼容下。

你好:smile: 近期的版本能兼容吗 因为core-js 2版本与3版本处理并不相同 

3版本 `require('core-js/modules/es.promise.finally')`是这样的

现阶段只能通过`require('promise-prototype-finally')`来处理 core-js 2与3之间区别 或者去修改Promise原型链
![image](https://user-images.githubusercontent.com/31199247/89005926-3049e580-d338-11ea-96be-be448cdf3ba9.png)

**Comment by brickspert** [comment]
关注下这个 issue：#426，我们跟进下。

**Comment by Smi1e96** [comment]
@brickspert   我一直在订阅这个:laughing:  静等2.4.0版本:heart:

**Comment by sengmitnick** [comment]
自己只能先这样子解决

(function () {
  if (typeof Promise.prototype.finally === 'function') {
    return
  }
  Promise.prototype.finally = function (fn) {
    return this
      .then(value => this.constructor.resolve(fn()).then(() => value))
      .catch(reason => this.constructor.resolve(fn()).then(() => { throw reason }))
  }
})()

**Comment by Thinking80s** [comment]
官方一直没有解决啊

**Comment by alanhe421** [comment]
在Mac-Chrome下也遇到这个报错，奇怪

## 环境信息
Mac OS 10.14.6 Mojave
Chrome 92.0.4515.131 最新版
WebKit 537.36
ahooks: v2.9.6


我理解既然Chrome是最新版，应该不会报错才对。

**Comment by brickspert** [comment]
> 在Mac-Chrome下也遇到这个报错，奇怪
> 
> ## 环境信息
> Mac OS 10.14.6 Mojave
> Chrome 92.0.4515.131 最新版
> WebKit 537.36
> ahooks: v2.9.6
> 
> 我理解既然Chrome是最新版，应该不会报错才对。

试试这个版本，修复了这个问题：2.10.10-beta

**Comment by alanhe421** [comment]
> > 在Mac-Chrome下也遇到这个报错，奇怪
> > ## 环境信息
> > Mac OS 10.14.6 Mojave
> > Chrome 92.0.4515.131 最新版
> > WebKit 537.36
> > ahooks: v2.9.6
> > 我理解既然Chrome是最新版，应该不会报错才对。
> 
> 试试这个版本，修复了这个问题：2.10.10-beta

好奇root cause？新版Chrome为什么会遇到这个问题，并且不易复现。

**Comment by generator2025** [comment]
> > 在Mac-Chrome下也遇到这个报错，奇怪
> > ## 环境信息
> > Mac OS 10.14.6 Mojave
> > Chrome 92.0.4515.131 最新版
> > WebKit 537.36
> > ahooks: v2.9.6
> > 我理解既然Chrome是最新版，应该不会报错才对。
> 
> 试试这个版本，修复了这个问题：2.10.10-beta

@brickspert win10 chrome107 也有遇到，升级到了 2.10.14 之后还是有收到这种报错，请问升级到 3 能解决吗？
