### ISSUE TITLE
useTextSelection从右选到左到头，则没有选择到内容，为空

### ISSUE THREAD

**Issue by kwooshung** [alibaba/hooks#477]
![image](https://user-images.githubusercontent.com/3413930/86324084-93c8f080-bc70-11ea-842b-ce7bafa2b04a.png)

如上图，如果是从右选到左到头，则没有选择到内容，为空

**Comment by brickspert** [comment]
其实这个问题是这样造成的：你鼠标 up 的时候，不在设置的 dom 区域内了，所以其实没有处理 mouseup 事件。

这个我需要优化下。

**Comment by brickspert** [comment]
demo 已经优化。
