### ISSUE TITLE
form 版本判断需要更改

### ISSUE THREAD

**Issue by crazyair** [alibaba/hooks#484]
antd 新版本 https://ant.design/changelog-cn
![image](https://user-images.githubusercontent.com/7971419/86430759-a2251400-bd25-11ea-805b-acd272c4988c.png)

这里判断明显要失败

![image](https://user-images.githubusercontent.com/7971419/86430779-ad783f80-bd25-11ea-8f10-abca0c004c95.png)

**Comment by crazyair** [comment]
用 import { version } from 'antd'; 这个判断得了。

**Comment by crazyair** [comment]
可以用传参，或者 hook 支持全局变量设置一次 antd 版本。

**Comment by brickspert** [comment]
我看一下，如果 antd4 的 getFieldInstance 和 antd3 行为一致，就没太大问题。

**Comment by crazyair** [comment]
> 我看一下，如果 antd4 的 getFieldInstance 和 antd3 行为一致，就没太大问题。

我这边是封装了 Form ，submit 想自己控制，主要是获取 values ，能放开吗？

**Comment by crazyair** [comment]
我这边开始出现问题是，本地开发模式没事，发布了之后 select、radio 选中值后点击搜索，是没有的。

**Comment by brickspert** [comment]
可以提供个你具体怎么封装的示例吗？submit 要怎么控制？

**Comment by crazyair** [comment]
> 可以提供个你具体怎么封装的示例吗？submit 要怎么控制？

form 我封装了个 getFormatFieldsValue 方法，提交需要执行这个。

**Comment by crazyair** [comment]
> 我这边开始出现问题是，本地开发模式没事，发布了之后 select、radio 选中值后点击搜索，是没有的。

这个问题我知道了， select，radio 是因为没有实例，所以被 v3 判断给 filter 了。

**Comment by brickspert** [comment]
> antd 新版本 https://ant.design/changelog-cn
> ![image](https://user-images.githubusercontent.com/7971419/86430759-a2251400-bd25-11ea-805b-acd272c4988c.png)
> 
> 这里判断明显要失败
> 
> ![image](https://user-images.githubusercontent.com/7971419/86430779-ad783f80-bd25-11ea-8f10-abca0c004c95.png)

测试了一下，antd4 最新版本没问题的。暂时先关了哈，有问题再开起来。

**Comment by crazyair** [comment]
实例的事情我是解决了，但是说的这个

form 我封装了个 getFormatFieldsValue 方法，提交需要执行这个。

你没看？
