### ISSUE TITLE
更新导致useRequest请求失败,需要手写catch处理异常。

### ISSUE THREAD

**Issue by hello-chinese** [alibaba/hooks#485]
### What problem does this feature solve?
描述:
文件 hooks/packages/use-request/src/useAsync.ts  172行
返回了Promise.reject, finally不会修改promise的状态,开发者需要自行.cath处理请求失败

问题：
现接口请求失败后，需要自行在项目代码中通过.catch做失败处理。
而之前请求失败，都是在.then中判断失败。

mater: 
``` javascript
      console.error(error);
      // eslint-disable-next-line prefer-promise-reject-errors
      return Promise.reject(
        'useRequest has caught the exception, if you need to handle the exception yourself, you can set options.throwOnError to true.',
      );
```
before:
``` javascript
       console.error(error);
```
### What does the proposed API look like?
不设置throwOnError为true时，返回的Promies，在then中判断请求是否成功

**Comment by brickspert** [comment]
#400  #415 
之前是一个 bug。
