### ISSUE TITLE
useAntdTable 设置showSizeChanger 为 true，当pageSize变化时会触发两次请求

### ISSUE THREAD

**Issue by kkelyi** [alibaba/hooks#488]
就在这个 demo中 修改tableProps.pagination.showSizeChanger = true 就能重现；
https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useAntdTable/demo/demo3.tsx

**Comment by brickspert** [comment]
这是一个 antd 的 bug，已经报告给 antd：https://github.com/ant-design/ant-design/issues/25434

**Comment by zhangwuyang-github** [comment]
请问这个问题的后续呢？实际还是没有解决吗？
