### ISSUE TITLE
useRequest的几个用法真的有用吗？

### ISSUE THREAD

**Issue by liujiayu10** [alibaba/hooks#492]
const { loading, run } = useRequest((username) => ({
  url: '/api/changeUsername',
  method: 'post',
  data: { username },
}), {
  manual: true,
});

我这样用了，出错：url MUST be a string

**Comment by brickspert** [comment]
你是不是配置了 requestMethod？使用了 `umi-request` ？

那你应该在 requestMethod 里面手动把 url 解析出来。

```
requestMethod({url, ...rest}){
  return request(url, rest);
}
```

**Comment by liujiayu10** [comment]
> 你是不是配置了 requestMethod？使用了 `umi-request` ？
> 
> 那你应该在 requestMethod 里面手动把 url 解析出来。
> 
> ```
> requestMethod({url, ...rest}){
>   return request(url, rest);
> }
> ```

谢谢，搞定了，参数那里要重构才行，示例是只要一个简单的参数就行了，其实是不全面的

**Comment by brickspert** [comment]
你应该是使用了 umi-request ~
