### ISSUE TITLE
useAntdTable 无法绑定 包含自定义表单项的表格

### ISSUE THREAD

**Issue by plightfield** [alibaba/hooks#496]
当表单包含自定义表单项时，
service 参数 中 form 始终为 {}
defaultParams 不起作用

getFieldInstance 也是 v4 的属性，可以通过 这个字段判断么？
``` 
 if (formRef.current.getFieldInstance) {
      // antd 3 需要判断字段是否存在，否则会抛警告
      const filterFiledsValue: Store = {};
      Object.keys(allFormData).forEach((key: string) => {
        if (formRef.current!.getFieldInstance ? formRef.current!.getFieldInstance(key) : true) {
          filterFiledsValue[key] = allFormData[key];
        }
      });
      formRef.current.setFieldsValue(filterFiledsValue);
    } else {
      // antd 4
      formRef.current.setFieldsValue(allFormData);
    }
```

**Comment by plightfield** [comment]
可以通过自定义组件加 forwardRef 解决，希望加上说明

**Comment by Sunshine168** [comment]
同样遇到了这个问题 ，我是自己拿 form.getFieldsValue 拿的值
getFieldInstance 这个判断有问题，用 getInternalHooks ？这个应该只有 v4 会有

**Comment by brickspert** [comment]
自定义表单项不生效吗？奇怪。能给个复现吗？

**Comment by Sunshine168** [comment]
https://codesandbox.io/s/old-sunset-ew04v?file=/src/App.tsx @brickspert

**Comment by brickspert** [comment]
在 antd 3 中，自定义的函数组件需要使用 `React.forwardRef` 来包裹。

```jsx
const CustomInput = React.forwardRef(({ value, onChange }, ref) => (
  <Input ref={ref} value={value} onChange={onChange} />
));
```

如果不包裹的话，antd 会报警告。

![image](https://user-images.githubusercontent.com/12526493/87439761-bc16fe80-c623-11ea-86b9-28844ad4e2a6.png)



经过测试，在 antd 4 中也需要包裹 `React.forwardRef`：https://codesandbox.io/s/focused-wave-8xnvl?file=/demo.tsx

**Comment by brickspert** [comment]
> 同样遇到了这个问题 ，我是自己拿 form.getFieldsValue 拿的值
> getFieldInstance 这个判断有问题，用 getInternalHooks ？这个应该只有 v4 会有

getFieldInstance 判断没问题，antd 4 提供了这个 API 之后，就不用区分 3 和 4 了其实~~

**Comment by rojer95** [comment]
radio.group 貌似拿不到数据
https://codesandbox.io/s/gallant-wu-hcvlk?file=/demo.tsx

@brickspert

**Comment by brickspert** [comment]
> radio.group 貌似拿不到数据
> https://codesandbox.io/s/gallant-wu-hcvlk?file=/demo.tsx
> 
> @brickspert

单独开个 issue 吧？~
