### ISSUE TITLE
[RFC] useWebSocket

### ISSUE THREAD

**Issue by zhaofinger** [alibaba/hooks#504]
#449 

### 代码演示

```tsx
import React, { useEffect } from 'react';
import { useWebSocket } from 'ahooks';
import { READY_STATE } from '../../../lib/useWebSocket';

export default () => {
  const {
    readyState,
    sendMessage,
    latestMessage,
    disconnectWebSocket,
    connectWebSocket,
  } = useWebSocket('ws://localhost:3000');

  return (
    <div>
      <button
        onClick={() => sendMessage && sendMessage(`${Date.now()}`)}
        disabled={readyState !== READY_STATE.open}
      >
        ✉️
      </button>
      &nbsp;&nbsp;
      <button
        onClick={() => disconnectWebSocket && disconnectWebSocket()}
        disabled={readyState !== READY_STATE.open}
      >
        ❌
      </button>
      &nbsp;&nbsp;
      <button
        onClick={() => connectWebSocket && connectWebSocket()}
        disabled={readyState === READY_STATE.open}
      >
        📞
      </button>
      <p>readyState: {readyState}</p>
      <p>latestMessage: {latestMessage?.data}</p>
    </div>
  );
};

```

### API
```tsx
export declare enum READY_STATE {
    connecting = 0,
    open = 1,
    closing = 2,
    closed = 3
}
export interface IUseWebSocketOptions {
    reconnectLimit?: number;
    reconnectInterval?: number;
    onOpen?: (event: WebSocketEventMap['open']) => void;
    onClose?: (event: WebSocketEventMap['close']) => void;
    onMessage?: (message: MessageEvent) => void;
    onError?: (event: WebSocketEventMap['error']) => void;
}
export interface IUseWebSocketReturn {
    latestMessage?: MessageEvent;
    sendMessage?: WebSocket['send'];
    disconnectWebSocket?: () => void;
    connectWebSocket?: () => void;
    readyState: READY_STATE;
    webSocketIns?: WebSocket;
}
export default function useWebSocket(socketUrl: string, options?: IUseWebSocketOptions): IUseWebSocketReturn;
```

**Comment by brickspert** [comment]
可以参考：https://github.com/robtaussig/react-use-websocket#readme

Options 应该有更多选项，比如 `onOpen` ，`onMessage` 等。

另外 API 应为为 `const result = useWebSocket(url, options?)`

**Comment by zhaofinger** [comment]
@brickspert 可以，但是有一个疑问 readyState 和 lastestMessage 已经可以覆盖到这些 callback，所以这些 callback 还有必要吗🤔️

**Comment by brickspert** [comment]
> @brickspert 可以，但是有一个疑问 readyState 和 lastestMessage 已经可以覆盖到这些 callback，所以这些 callback 还有必要吗🤔️

比如我想在收到消息的时候，触发个事件。就需要用到 onMesage 吧。

**Comment by zhaofinger** [comment]
> > @brickspert 可以，但是有一个疑问 readyState 和 lastestMessage 已经可以覆盖到这些 callback，所以这些 callback 还有必要吗🤔️
> 
> 
> 
> 比如我想在收到消息的时候，触发个事件。就需要用到 onMesage 吧。

我理解加上 useEffect 就可以做吧，虽然可能略显繁琐。

**Comment by brickspert** [comment]
> > > @brickspert 可以，但是有一个疑问 readyState 和 lastestMessage 已经可以覆盖到这些 callback，所以这些 callback 还有必要吗🤔️
> > 
> > 
> > 比如我想在收到消息的时候，触发个事件。就需要用到 onMesage 吧。
> 
> 我理解加上 useEffect 就可以做吧，虽然可能略显繁琐。

加上 useEffect 会有问题，比如两次同样的消息，就监听不到了。

**Comment by zhaofinger** [comment]
> > > > @brickspert 可以，但是有一个疑问 readyState 和 lastestMessage 已经可以覆盖到这些 callback，所以这些 callback 还有必要吗🤔️
> > > 
> > > 
> > > 比如我想在收到消息的时候，触发个事件。就需要用到 onMesage 吧。
> > 
> > 
> > 我理解加上 useEffect 就可以做吧，虽然可能略显繁琐。
> 
> 加上 useEffect 会有问题，比如两次同样的消息，就监听不到了。

这个倒不会，现在我想的是 latestMessage 直接返回 MessageEvent 类型，所以同样的消息不会有问题。

🤔️ 新的疑惑，latestMessage 是直接返回 MessageEvent 还是返回消息 data 比较合适呢？

**Comment by brickspert** [comment]
又来一个可以参考的：https://github.com/ecomfe/react-hooks/blob/master/packages/web-socket/README.md

**Comment by zhaofinger** [comment]
> 又来一个可以参考的：https://github.com/ecomfe/react-hooks/blob/master/packages/web-socket/README.md

ok, RFC 更新了下。
