### ISSUE TITLE
feature request: changing default pagination options in usePaginated

### ISSUE THREAD

**Issue by PoiScript** [alibaba/hooks#519]
In short, I'm trying to disable the size changer of a table. But there's no way to change the default props of pagination in hooks side which means I have to manually override it and results in something like:

```tsx
const { tableProps } = useRequest("/users/list", { paginated: true });

<Table
   rowId="id"
   columns={columns}
   {...tableProps}
   pagination={{ ...tableProps.pagination, showSizeChanger: false }}
/>
```

It's fine, but I actually hoping to get something less verbose (we currently have about 80 tables on our sites).

IMO, we can just add a new option named `paginationProps`:

```tsx
const { tableProps } = useRequest("/users/list", { paginated: true, paginationProps: { showSizeChanger: false } });

<Table rowId="id" columns={columns} {...tableProps} />
```

**Comment by brickspert** [comment]
I also have many such scenes，I create a custom hooks like this

```js
const usePagination = (url, options)=>{
  let result = useRequest(url, options);
  result.pagination. showSizeChanger = false;
  return result;
}

```
