### ISSUE TITLE
one question for useFullScreen

### ISSUE THREAD

**Issue by ZhengXingchi** [alibaba/hooks#521]
when i use the fullscrren in my editor component。the editor component contain a form(include file input), Popover and so on.when the component is fullscreen,then i click the file input ,the component will exit fullscrren.also when i use antd-popover,the popover cannot be see even i modify the z-index,how to solve it?thank you

**Comment by brickspert** [comment]
Can you provide an example ?

**Comment by ZhengXingchi** [comment]
[this is a demo](https://github.com/ZhengXingchi/usefullscreen-demo.git).you can read document to  reappeared the issue.thank you.

**Comment by brickspert** [comment]
first issue: https://stackoverflow.com/questions/61100567/how-to-stay-full-screen-when-trigger-upload-file

second issue: set getPopupContainer to popover
