### ISSUE TITLE
【RFC】useUrlState

### ISSUE THREAD

**Issue by ttys026** [alibaba/hooks#526]
## API

```typescript

const [state, setState] = useUrlState<T>(initialState, {
  type?: 'browser' | 'hash' | {
    getter: (url: string) => T
    setter: (state: T) => void
  },
  navigateMode: 'push' | 'replace',
})

```

## Demo (dummy code)
```typescript
const [ state, setState ] = useUrlState({ visible: 'false' }, { type: 'hash' });


```

## Demo using Context (dummy code)

```typescript

import { UrlStateProvider } from 'ahooks';

<UrlStateProvider config={{
  getter: (url: string) => {
    return queryString.parse(url.split('?')[1] || '')
  },
  setter: (state) => {
    history.push(`?${Object.entries(state).map(ele => ele.join('=')).join('&')}`)
  },
}}>
  {children}
</UrlStateProvider>

```

**Comment by brickspert** [comment]
建议加个参数，判断是 `push` 还是 `replace`。

getter 和 setter 来做这个太复杂了，这两个参数倒是可以来处理 memory 路由。

**Comment by daiwa233** [comment]
是否可以添加一个 option，在 url query -> state 这个过程做处理和加一些判断。因为 url query 里面的状态可能不符合预期。
例如：分页参数要转换成 number 类型，不满足 number 时使用 initialState 这样。
```ts
export interface Options {
  navigateMode?: 'push' | 'replace';
  transformer?: (queryFromUrl: Record<string, any>) => Record<string, any>;
}
```

**Comment by brickspert** [comment]
> 是否可以添加一个 option，在 url query -> state 这个过程做处理和加一些判断。因为 url query 里面的状态可能不符合预期。
> 例如：分页参数要转换成 number 类型，不满足 number 时使用 initialState 这样。
> 
> ```ts
> export interface Options {
>   navigateMode?: 'push' | 'replace';
>   transformer?: (queryFromUrl: Record<string, any>) => Record<string, any>;
> }
> ```

你可以这样写：

```ts
const [state, setState] = useUrlState({ page: 1, pageSize: 10 });
```

**Comment by daiwa233** [comment]
> > 是否可以添加一个 option，在 url query -> state 这个过程做处理和加一些判断。因为 url query 里面的状态可能不符合预期。
> > 例如：分页参数要转换成 number 类型，不满足 number 时使用 initialState 这样。
> > ```ts
> > export interface Options {
> >   navigateMode?: 'push' | 'replace';
> >   transformer?: (queryFromUrl: Record<string, any>) => Record<string, any>;
> > }
> > ```
> 
> 你可以这样写：
> 
> ```ts
> const [state, setState] = useUrlState({ page: 1, pageSize: 10 });
> ```
这样写我理解并不能在 url -> query 这个过程中保证 page 是 number 类型呀。
```ts
const queryFromUrl = useMemo(() => {
    return parse(location.search, parseConfig);
  }, [location.search]);

 const targetQuery: state = useMemo(
    () => ({
      ...initialStateRef.current,
      ...queryFromUrl,
    }),
    [queryFromUrl],
  );
```
得到的 state 即 targetQuery ，是从 url query 里面拿的，这在 url search 是` ?page=123abc` 时得到的 state 并不符合预期。而且有时候需要对 page 、pageSize 做限制，比如说 pageSize 可能只有几个取值，不满足这几个取值的时候，使用初始 state。这些可以交给 上面提到的 transformer 来控制

**Comment by brickspert** [comment]
了解你的诉求了，这个我想下~

**Comment by crazylxr** [comment]
@brickspert 现在这个是不是可以关了，现在我看都已经支持上面说的功能了
