### ISSUE TITLE
RFC: useTimeout

### ISSUE THREAD

**Issue by Qkxinq** [alibaba/hooks#527]
### API
```
function useTimeout(fn: () => void, delay: number, options: {
  immediate?: boolean
})
```

- 当 `delay` 的单位为 ms，当其取值更改时清除上一次的 `timeout` 重新设置 `timeout` ，当其值为 `null` 或 `undefined` 时不设置 `timeout`

- `immediate` 参数可以用来控制是否在首次渲染时立即执行 `fn`，默认为 `false`

### Demo
```
useTimeout(() => {
  console.log('hello')
}, 1000, {immediate: true})
```

**Comment by brickspert** [comment]
immediate 没用吧，useTimeout 不需要这个。

**Comment by awmleer** [comment]
> immediate 没用吧，useTimeout 不需要这个。

+1 整个 `options` 参数都可以去掉

**Comment by awmleer** [comment]
Implemented in pull request #570
