### ISSUE TITLE
useSize类型问题

### ISSUE THREAD

**Issue by zhanba** [alibaba/hooks#546]
```tsx
const App = () => {
  const ref = useRef<HTMLDivElement>(null);
  const size = useSize(ref)

 return <div ref={ref} />
}
```
- ref的类型不匹配报错
- size的类型为 `{width?: number, height?: number}`, 使用很不方便，要一直处理undefined；  建议改为` {width: number, height: number} | undefined `更合理

**Comment by brickspert** [comment]
* ref 已经修复，下个版本发布
* size 的类型不能做 break change

**Comment by zhanba** [comment]
如果设计有问题，为啥不能break change

**Comment by brickspert** [comment]
> 如果设计有问题，为啥不能break change

break change 之后，老用户都会报 error，一升级就挂。。😭

**Comment by zhanba** [comment]
> > 如果设计有问题，为啥不能break change
> 
> break change 之后，老用户都会报 error，一升级就挂。。😭

晚break不如早break啊，除非你打算永远不break；break说清楚不就行了吗，用户自己决定升级版本号啊

**Comment by brickspert** [comment]
> > > 如果设计有问题，为啥不能break change
> > 
> > 
> > break change 之后，老用户都会报 error，一升级就挂。。😭
> 
> 晚break不如早break啊，除非你打算永远不break；break说清楚不就行了吗，用户自己决定升级版本号啊

小版本会自动升级的呀，用户重新 tnpm update，页面就挂了。这不能接收的~

**Comment by zhanba** [comment]
npm version minor，有啥困难？
