### ISSUE TITLE
package 不同步了

### ISSUE THREAD

**Issue by HaveF** [alibaba/hooks#548]
taobao npm:
[Package - ahooks](https://developer.aliyun.com/mirror/npm/package/ahooks)
2.2.0

npmjs:
[ahooks - npm](https://www.npmjs.com/package/ahooks)
2.3.0

**Comment by brickspert** [comment]
在这里看到是最新的 2.3.0 ：https://registry.npm.taobao.org/ahooks

但是页面上看没同步，我估计是页面的问题吧~~

**Comment by HaveF** [comment]
ok, 之前是发现
`error Couldn't find any versions for "ahooks" that matches "2.3.0"`
其实也不太清楚是哪里的原因，随便猜了一个~~

现在好了
