### ISSUE TITLE
Object.values is not a function in ios 9

### ISSUE THREAD

**Issue by zhongsink** [alibaba/hooks#549]
### environment
ahook:  2.x
ios 9

### use
```
import { useRequest } from 'ahooks'
```

not polyfill,
i can resolve this problem with core-js@3
have any better way ?

![image](https://user-images.githubusercontent.com/12597344/88528641-77cb2b80-d031-11ea-8da2-88ccfbc6a4a5.png)

**Comment by awmleer** [comment]
如果需要兼容版本较低的浏览器，目前推荐的做法还是在项目中根据需要手动加 polyfill，可以参考这个 PR #574 

https://github.com/alibaba/hooks/pull/574/files
