### ISSUE TITLE
useFusionTable 使用ready配合defaultParams时，service传入的参数不满足需要

### ISSUE THREAD

**Issue by we6288815** [alibaba/hooks#551]
在使用useFusionTable时，使用ready配合defaultParams，defaultParams中的参数与ready中的参数相关，
理想情况下，应该是ready条件满足，才会使用defaultParams的参数进行请求，实际上却是useFusionTable提前设置了defaultParams的参数，导致ready条件满足后仍使用初始参数进行请求，从而未能正确获取数据。

实际想要的效果，defaultParams中的参数，能够根据ready的状态，去使用最新的数据。

相关代码如下：

const fetchGroupBoxData = (pagination, categoryId) => {
    let remoteURL = `/groupBoxes/${categoryId}/all`;
    return request.get(remoteURL, {
        params: {
            pageNum: pagination.current,
            pageSize: pagination.pageSize,
        }
    });
}

const { paginationProps, tableProps, loading, run } = useFusionTable(fetchGroupBoxData, {
        ready: categories && categories.length > 0,
        defaultParams: [
            { current: 1, pageSize: 2 },
            categories[0]?.categoryId
        ],
        formatResult: (res) => {
            return {
                list: res.data.list,
                total: res.data.pagination.total,
            }
        }
    });

**Comment by brickspert** [comment]
目前确实会有这个问题，这个我看下。

**Comment by brickspert** [comment]
related: https://github.com/alibaba/hooks/discussions/1291

可以来这里讨论 ready 的行为。
