### ISSUE TITLE
【RFC】useDebounceUpdateEffect

### ISSUE THREAD

**Issue by JoshOY** [alibaba/hooks#552]
A hook similar to `useDebounceEffect` but only executes after update.

**Comment by JoshOY** [comment]
See: https://github.com/alibaba/hooks/pull/553

**Comment by brickspert** [comment]
This can't be added, there are already enough related hooks, and the user is already confused.

**Comment by JoshOY** [comment]
@brickspert Okay, that makes sense, since implementing this hook is simple enough. I will close this MR.

P.S. Perhaps adding more use cases in the documentation may guide users to implement their desired functionalities easier.

**Comment by brickspert** [comment]
Thank you very much for your contribution and understanding, and look forward to more cooperation.
