### ISSUE TITLE
useFormTable无法支持自定义表单组件？

### ISSUE THREAD

**Issue by LittleSecretary** [alibaba/hooks#567]

**Comment by brickspert** [comment]
https://ahooks.js.org/zh-CN/hooks/table/use-antd-table#1-%E6%97%A0%E6%B3%95%E8%AF%BB%E5%8F%96%E6%88%96%E5%88%9D%E5%A7%8B%E5%8C%96%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E7%BB%84%E4%BB%B6%E7%9A%84%E5%80%BC

![image](https://user-images.githubusercontent.com/12526493/89612673-f38b6a80-d8b2-11ea-8437-28cb0447fb0c.png)

**Comment by LittleSecretary** [comment]
> https://ahooks.js.org/zh-CN/hooks/table/use-antd-table#1-%E6%97%A0%E6%B3%95%E8%AF%BB%E5%8F%96%E6%88%96%E5%88%9D%E5%A7%8B%E5%8C%96%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E7%BB%84%E4%BB%B6%E7%9A%84%E5%80%BC
> 
> ![image](https://user-images.githubusercontent.com/12526493/89612673-f38b6a80-d8b2-11ea-8437-28cb0447fb0c.png)

非常感谢，建议3x版本也加上
