### ISSUE TITLE
useAntdTable 同时设置form和defaultParams，defaultParams中formData无效，pagination正常

### ISSUE THREAD

**Issue by daiikaku** [alibaba/hooks#571]
useAntdTable 同时设置form和defaultParams，defaultParams中formData无效，pagination正常。
场景是希望将初始参数放到defaultParams的formData中，查询条件放到form中。

**Comment by brickspert** [comment]
可以给个复现？

https://ahooks.js.org/zh-CN/hooks/table/use-antd-table#%E5%88%9D%E5%A7%8B%E5%8C%96%E6%95%B0%E6%8D%AE

这个例子就是同时设置 form 和 defaultParams 的

**Comment by vvLu** [comment]
> useAntdTable 同时设置form和defaultParams，defaultParams中formData无效，pagination正常。
> 场景是希望将初始参数放到defaultParams的formData中，查询条件放到form中。

你好，问题解决了吗？

**Comment by chinyifei** [comment]
你设置的默认值字段，要在form表单的form.itm里面有对应的name值才可以。
