### ISSUE TITLE
Demo code syntax error

### ISSUE THREAD

**Issue by acmu** [alibaba/hooks#572]
![image](https://user-images.githubusercontent.com/35673748/89727128-aba44900-da54-11ea-95b3-f9f6c601f2c1.png)
Source code is correct, but demo code occur syntax error. It's weird.
https://ahooks.js.org/zh-CN/hooks/async#%E6%89%8B%E5%8A%A8%E8%A7%A6%E5%8F%91
![image](https://user-images.githubusercontent.com/35673748/89727188-0ccc1c80-da55-11ea-989f-63359ffe7b1f.png)

**Comment by awmleer** [comment]
Documentation site has been updated with this bug fixed.
