### ISSUE TITLE
[RFC] useCountDown Hooks

### ISSUE THREAD

**Issue by linbudu599** [alibaba/hooks#576]
场景适用：手机验证码点击后禁用x秒，或任意操作后禁用某个控件x秒
```typescript
import { useState, useEffect, Dispatch, SetStateAction } from 'react';

let countInterval: any = null;

type TUseCountDown = (
  start: number,
  end: number
) => [boolean, Dispatch<SetStateAction<boolean>>, number];

const useCountDown: TUseCountDown = (start, end) => {
  // TODO: start end大小检查
  // TODO: 是否需要用setTimeout模拟setInterval?
  const [count, setCount] = useState<number>(start);
  const [disabled, setDisabled] = useState<boolean>(false);

  const interval = () => {
    countInterval = setInterval(() => {
      if (count - 1 === end) {
        clearInterval(countInterval);
        return setDisabled(false);
      }
      setCount(count - 1);
    }, 1000);
  };

  useEffect(() => {
    disabled ? interval() : setCount(start);
    return () => clearInterval(countInterval);
  }, [count, disabled]);

  return [disabled, setDisabled, count];
};

export default useCountDown;
```

```typescript
import React from 'react';
import useCountDown from '../hooks/useCountdown';

const App: React.FC = () => {
  const [disabled, setDisabled, count] = useCountDown(5, 0);

  return (
    <>
      {!disabled ? (
        <button
          onClick={() => {
            setDisabled(true);
          }}
        >
          send verify code
        </button>
      ) : (
        <button>send again ({count})</button>
      )}
    </>
  );
};

export default App;
```

[Sandbox Demo](https://codesandbox.io/s/usecountdown-hook-9pb2x)

**Comment by brickspert** [comment]
useCountdown 应该能力更强大些

```ts
const [countdown, setTarget] = useCountdown(
  date: () => Date | string | number, // 目标时间
  options?: {
    intervalTime?: number // 更新间隔，默认为 1000ms
  }
);
```

## demo 1

```js
const [countdown] = useCountdown(new Date('2020-12-23 22:12:13'));
```

## demo 2

```js
const [countdown] = useCountdown(() => Date.now() + 60000); // 当前时间 + 60s
```

## demo 3

```js
const [countdown, setTarget] = useCountdown(); 
setTarget(Date.now() + 60000); // 手动触发
```

**Comment by brickspert** [comment]
setTimeout 模拟 setInterval 倒是没必要

**Comment by linbudu599** [comment]
对**setTarget以及定义时间间隔的能力**做了支持，直接调用`useCountDown()`而无入参下默认禁用时间为60s，间隔为1000ms，直接调用`setTarget()`的终止时间为计数器至0时，但对于这里开始时间的格式我不太理解：
我的理解是  不需要对时间戳做支持：
- 使用时只需要传入开始与结束的数字标识，都不传的话则是最通用的场景：发送验证码后禁用60秒。
- `setTarget(Date.now() + 60000)`的方式，实际上内部需要维护的是时间戳递增的逻辑，而现在的计数器是递减的逻辑。
- 我能想到的唯一一个需要使用时间戳的场景，比如在未来的某个时间段内禁用，但这种场景使用的应当是服务端下发的时间戳？
- 我觉得可以先加进去看看有没有用户有这个需求...

[CodeSandBox Demo地址](https://codesandbox.io/s/usecountdown-hook-9pb2x?file=/src/App.tsx)

```typescript
// useCountDown.ts
import { useState, useEffect } from 'react';

let countInterval: any = null;

type TUseCountDown = (
  start?: number,
  options?: {
    interval: number;
  }
) => [number, (end?: number) => void, boolean];

// TODO: 基于重载支持只传入选项的情况
const useCountDown: TUseCountDown = (start, options) => {
  const interval = options?.interval ?? 1000;
  const begin = start ?? 60;

  const [count, setCount] = useState<number>(begin);
  const [end, setEnd] = useState<number>(0);
  const [disabled, setDisabled] = useState<boolean>(false);

  const intervalCaller = () => {
    countInterval = setInterval(() => {
      if (count - 1 === end) {
        clearInterval(countInterval);
        return setDisabled(false);
      }
      setCount(count - 1);
    }, interval);
  };

  const setTarget = (end: number = 0): void => {
    setDisabled(true);
    setEnd(end);
  };

  useEffect(() => {
    disabled ? intervalCaller() : setCount(begin);
    return () => clearInterval(countInterval);
  }, [count, disabled]);

  return [count, setTarget, disabled];
};

export default useCountDown;

// app.tsx
import React from 'react';
import useCountDown from '../hooks/useCountdown';

const App: React.FC = () => {
  const [current, setTarget, status] = useCountDown(5);

  return (
    <>
      {!status ? (
        <button
          onClick={() => {
            setTarget();
          }}
        >
          send verify code
        </button>
      ) : (
        <button>send again ({current})</button>
      )}
    </>
  );
};

export default App;

```

**Comment by brickspert** [comment]
类似这个：https://github.com/bsonntag/react-use-countdown

不需要局限在“验证码”这个场景，我觉得 useCountdown 应该是管理到未来某个时间的倒计时的。

```js
const [countdown, setTarget] = useCountdown(); 
setTarget(Date.now() + 60000); // 开始计算到 60s 之后的倒计时
```

甚至可以加个 `format` 做这样的功能 `距离 xxx 时间剩余 16 天 12 小时 40 分钟 33 秒`

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/89861732-06ff4400-dbd9-11ea-85c2-195e976f0d13.png)

**Comment by linbudu599** [comment]
我尝试着实现了一下，感觉如果要实现到未来某个时间倒计时的效果，就没有必要去强行融入验证码的场景了。是否可以倒计时为一个`useCountDown`，验证码为一个`useVerifyCode`?  （我觉得后者的使用场景可能更广更下沉一些，因为的确网上能看到不少被hooks+验证码折腾的同学）

**Comment by brickspert** [comment]
> 我尝试着实现了一下，感觉如果要实现到未来某个时间倒计时的效果，就没有必要去强行融入验证码的场景了。是否可以倒计时为一个`useCountDown`，验证码为一个`useVerifyCode`? （我觉得后者的使用场景可能更广更下沉一些，因为的确网上能看到不少被hooks+验证码折腾的同学）

useVerifyCode 不必须吧？用 useCountDown 完全可以做的呀。

建议可以先把 useCountDown 做出来~

**Comment by linbudu599** [comment]
基于react-use-countdown先魔改了一个简单的demo出来，大概好像懂前辈意思了hhh
有点长就不放代码了，见[Demo](https://codesandbox.io/s/usecountdown-hook-wjcpn?file=/src/useCountDown.ts)

需要支持的能力还有哪些呢？

- 更多时间格式支持
-  英语支持
- 允许手动启用会造成**剩余时间文本的跳动** 这一能力是否是应该保留的？
- 是否允许暂停定时器
- 时间戳正负的处理
- 设定倒计时起点时间能力支持
- 复位功能，其实就相当于支持验证码那个场景了，这里我想的是如果已经到达（比如说之前固定的未来某个时间点）就始终为0，否则（比如说是当前时间戳+5000），就走一个五秒的计时。同时再加一个计时器结束的flag来做禁用控件的指示。

**Comment by we6288815** [comment]
强，点赞，啥时候能上版本，刚好需要倒计时控制的功能。加上就不能频繁点击同步了。
![image](https://user-images.githubusercontent.com/8169722/90106055-72801780-dd79-11ea-97d1-a16c63c48761.png)

**Comment by brickspert** [comment]
> 基于react-use-countdown先魔改了一个简单的demo出来，大概好像懂前辈意思了hhh
> 有点长就不放代码了，见[Demo](https://codesandbox.io/s/usecountdown-hook-wjcpn?file=/src/useCountDown.ts)
> 
> 需要支持的能力还有哪些呢？
> 
> * 更多时间格式支持
> * 英语支持
> * 允许手动启用会造成**剩余时间文本的跳动** 这一能力是否是应该保留的？
> * 是否允许暂停定时器
> * 时间戳正负的处理
> * 设定倒计时起点时间能力支持
> * 复位功能，其实就相当于支持验证码那个场景了，这里我想的是如果已经到达（比如说之前固定的未来某个时间点）就始终为0，否则（比如说是当前时间戳+5000），就走一个五秒的计时。同时再加一个计时器结束的flag来做禁用控件的指示。

我发表下个人的建议哈，我个人倾向的 API：

```js
const [countdown, setTargetDate] = useCountdown(
  targetDate:  Date | string | number | undefined | null, // 目标时间
  options?: {
    intervalTime?: number // 更新间隔，默认为 1000ms
    format?: (timestamp, formatted)=> any // 格式化
    dateFrom?: Date | string | number // 开始时间
  }
);
```

* 时间格式化我们提供一个 `options.format` 就行，把时间戳和计算后的时间 object 传出去

```js
const [countdown, setTargetDate] = useCountdown(undefined, {
  format: (_, formatted)=>{
       return `${formatted.day} 天 ${formatted.hour} 小时 ${formatted.minute} 分钟...`
  }
});
```

* `时间戳正负的处理` 我觉得默认到 0 后，就不用执行了，不需要负数。如果需要负数，后面我们再加个配置。

* 暂停复位的实现，参考 [useInterval](https://ahooks.js.org/hooks/side-effect/use-interval#advanced-usage)

```
setTargetDate( undefined ) // 暂停
setTargetDate(new Date() + 10000) // 开始 
```

**Comment by linbudu599** [comment]
「WIP」

**Comment by linbudu599** [comment]
[新的Demo](https://codesandbox.io/s/usecountdown-hook-wjcpn?file=/src/App.tsx)
可能还是有一部分边界情况没有照顾到，目前是按照建议的API实现的，我觉得建议的API可以，就是最好再加个定时器状态的指示器。比如上面那个需要倒计时控制的场景就需要使用计时器状态。

**Comment by linbudu599** [comment]
又，我还有个新的hooks的想法，由于觉得意义不大就没新开一个Issue了。`useMultiImperativeHandle`，用于多次合并对象到ref.current上，场景是我这边业务中遇到的：为列表中的每个子项挂载到同一个ref上，并在列表主页提交时，遍历这个ref去依次调用子组件的方法去校验子组件自身，通过校验结果来判断是否通过。
实现：
```typescript
import { useImperativeHandle, MutableRefObject, DependencyList } from 'react';

const useMultiImperativeHandle = <T, K extends Object>(
  originRef: MutableRefObject<T>,
  convertRefObj: K,
  deps?: DependencyList
): void =>
  useImperativeHandle(
    originRef,
    () => {
      return {
        ...originRef.current,
        ...convertRefObj,
      };
    },
    deps
  );

export default useMultiImperativeHandle;

```

还请尽龙老师帮忙看看是否有价值~

**Comment by brickspert** [comment]
> [新的Demo](https://codesandbox.io/s/usecountdown-hook-wjcpn?file=/src/App.tsx)
> 可能还是有一部分边界情况没有照顾到，目前是按照建议的API实现的，我觉得建议的API可以，就是最好再加个定时器状态的指示器。比如上面那个需要倒计时控制的场景就需要使用计时器状态。

没啥大问题，可以贡献一波了~

**Comment by brickspert** [comment]
> 又，我还有个新的hooks的想法，由于觉得意义不大就没新开一个Issue了。`useMultiImperativeHandle`，用于多次合并对象到ref.current上，场景是我这边业务中遇到的：为列表中的每个子项挂载到同一个ref上，并在列表主页提交时，遍历这个ref去依次调用子组件的方法去校验子组件自身，通过校验结果来判断是否通过。
> 实现：
> 
> ```ts
> import { useImperativeHandle, MutableRefObject, DependencyList } from 'react';
> 
> const useMultiImperativeHandle = <T, K extends Object>(
>   originRef: MutableRefObject<T>,
>   convertRefObj: K,
>   deps?: DependencyList
> ): void =>
>   useImperativeHandle(
>     originRef,
>     () => {
>       return {
>         ...originRef.current,
>         ...convertRefObj,
>       };
>     },
>     deps
>   );
> 
> export default useMultiImperativeHandle;
> ```
> 
> 还请尽龙老师帮忙看看是否有价值~

这个不太必要，使用场景太少了。

**Comment by linbudu599** [comment]
> > [新的Demo](https://codesandbox.io/s/usecountdown-hook-wjcpn?file=/src/App.tsx)
> > 可能还是有一部分边界情况没有照顾到，目前是按照建议的API实现的，我觉得建议的API可以，就是最好再加个定时器状态的指示器。比如上面那个需要倒计时控制的场景就需要使用计时器状态。
> 
> 没啥大问题，可以贡献一波了~

好的~ 这周先忙下答辩相关事情   预计周末再完善下和写好测试就提个PR~
