### ISSUE TITLE
useThrottle和useThrottleFn能不能支持指定调用在节流开始前的参数

### ISSUE THREAD

**Issue by yingxiaoqiang** [alibaba/hooks#577]
类似于lodash里面的_.throttle方法，支持在节流开始前调用，后面再根据节流时间来触发调用

**Comment by brickspert** [comment]
现在已经支持了呀：https://ahooks.js.org/hooks/side-effect/use-throttle

**Comment by yingxiaoqiang** [comment]
这是1.x的版本，但是为什么在2.x的版本里面被去掉了呢
![image](https://user-images.githubusercontent.com/16712872/89864074-e4235e80-dbdd-11ea-95ed-33c16d8d5504.png)
![image](https://user-images.githubusercontent.com/16712872/89864124-fbfae280-dbdd-11ea-9248-0e84e87cdc0e.png)

**Comment by awmleer** [comment]
@yingxiaoqiang 你是不是看反了。。右上角的那个链接表示的是跳转到**另一个**版本

**Comment by awmleer** [comment]
1.x 是没有这些 options 的，是 2.x 新增的
