### ISSUE TITLE
Demo页白屏

### ISSUE THREAD

**Issue by mfoonirlee** [alibaba/hooks#578]
先放地址：https://ahooks.js.org/zh-CN/hooks/state/use-history-travel
在demo中增加一个todo之后，操作inputNumber到-1，点击GO，页面白屏
报错如下：
![image](https://user-images.githubusercontent.com/6947182/89849110-5aae6500-dbba-11ea-9eea-ffdd439e317b.png)

**Comment by linbudu599** [comment]
可能是索引类型转换导致取不到值的问题，我确认一下具体代码段

**Comment by linbudu599** [comment]
是 [dumpIndex](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useHistoryTravel/index.ts#L9) 的问题：
```typescript
  let index =
      step > 0
        ? step - 1 // move forward
        : arr.length + step; // move backward
```

这一段中`step < 0`情况下拿到的index值是`1-1`这种，因为`step`被隐世转换了（2333虽然我也觉得很诡异），解决方式只要套个`Number(step)`就好了 @Straw94 @brickspert

**Comment by brickspert** [comment]
@linbudu599 确定不来个 pr 吗？😋

**Comment by linbudu599** [comment]
> @linbudu599 确定不来个 pr 吗？😋

好嘞 但公司电脑不太方便  我会在晚上提一个PR的 会顺便完善下测试用例和其他边界情况（如果有）的。

**Comment by brickspert** [comment]
> > @linbudu599 确定不来个 pr 吗？😋
> 
> 好嘞 但公司电脑不太方便 我会在晚上提一个PR的 会顺便完善下测试用例和其他边界情况（如果有）的。

万分感谢~

**Comment by linbudu599** [comment]
见 #582  @mfoonirlee
