### ISSUE TITLE
[RFC] useImperativeInterval Hook

### ISSUE THREAD

**Issue by linbudu599** [alibaba/hooks#583]
原本想重构已有的`useInterval`，但发现似乎会造成`break change`，并且有些功能不是太好实现。索性重写了一个：
- 暴露出计时器（当前）状态与手动清除方法
- `immediate`与`removeOnUnmount`选项
- 较好的保留了原`useInterval`的能力

[CodeSandBox Demo地址](https://codesandbox.io/s/useimperativeinterval-hook-jpb1i?file=/src/App.tsx)

```typescript
import { useEffect, useState, useRef } from 'react';

const defaultOpts = {
  immediate: false,
  removeOnUnmount: true
};

type Opts = Partial<typeof defaultOpts>;
type Func = (...args: any[]) => any;

// TODO: 重载支持
const useImperativeInterval = (
  fn: Func,
  delay?: number,
  options?: Opts
): [boolean, () => void] => {
  const interval = delay ?? 1000;
  const [survive, setSurvive] = useState<boolean>(true);
  const mergedOpts = { ...defaultOpts, ...(options ?? {}) };
  const { immediate, removeOnUnmount } = mergedOpts;

  const timerRef = useRef<any>();
  const fnRef = useRef<Func>(fn);

  fnRef.current = fn;

  const _clearTimer = (manual: boolean) => {
    if (timerRef.current) {
      clearInterval(timerRef.current);
    }

    if (manual) {
      setSurvive(false);
    }
  };

  const manualClear = () => {
    _clearTimer(true);
  };

  const autoClear = () => {
    _clearTimer(false);
  };

  useEffect(() => {
    if (immediate) {
      fnRef.current();
    }

    timerRef.current = setInterval(() => {
      fnRef.current();
    }, interval);

    return () => {
      autoClear();
    };
  }, [interval]);

  useEffect(() => {
    return () => {
      if (removeOnUnmount) {
        manualClear();
      }
    };
  }, []);

  return [survive, manualClear];
};

export default useImperativeInterval;

```

**Comment by awmleer** [comment]
`removeOnUnmount` 的使用场景是什么呢。。？

**Comment by awmleer** [comment]
`manualClear` 之后，如何再重新启用呢？

手动清除的能力现在的 `useInterval` 也是支持的，只需要把 `delay` 参数传成 `null` 或 `undefined` 即可，如果需要这个功能非常语义化的话，可以这样简单封装一下：

```js
function useManualInterval(fn, interval, options) {
  const [enable, setEnable] = useState(true)
  useInterval(
    fn,
    enable ? interval : null,
    options,
  )
  return [enable, setEnable]
}
```

**Comment by linbudu599** [comment]
> `removeOnUnmount` 的使用场景是什么呢。。？

在使用这个hook的组件被卸载后，将这个计时器从内存中清除？

**Comment by linbudu599** [comment]
> `manualClear` 之后，如何再重新启用呢？
> 
> 手动清除的能力现在的 `useInterval` 也是支持的，只需要把 `delay` 参数传成 `null` 或 `undefined` 即可，如果需要这个功能非常语义化的话，可以这样简单封装一下：
> 
> ```js
> function useManualInterval(fn, interval, options) {
>   const [enable, setEnable] = useState(true)
>   useInterval(
>     fn,
>     enable ? interval : null,
>     options,
>   )
>   return [enable, setEnable]
> }
> ```

好厉害TAT  我没想到这种  只是单纯的想把命令式与声明式的使用分开  那应该只要在文档里体现这种用法就好了还是新增一个`useManualInterval`?

**Comment by awmleer** [comment]
> 在使用这个hook的组件被卸载后，将这个计时器从内存中清除？

现在已经有清除的逻辑了呀

**Comment by awmleer** [comment]
> 好厉害TAT 我没想到这种 只是单纯的想把命令式与声明式的使用分开 那应该只要在文档里体现这种用法就好了还是新增一个`useManualInterval`?

我觉得可以文档里补充一下，但是新增一个 Hook 感觉没必要了。。因为即便封装了用户也不一定会按照这种方式去用

**Comment by linbudu599** [comment]
好嘞，那我到时候在文档加一下这个用法？

**Comment by awmleer** [comment]
> 好嘞，那我到时候在文档加一下这个用法？

嗯嗯好的
