### ISSUE TITLE
userRequest 错误拿不到

### ISSUE THREAD

**Issue by ysh35** [alibaba/hooks#585]
userAsync.js 中的

```
return Promise.reject('useRequest has caught the exception, if you need to handle the exception yourself, you can set options.throwOnError to true.');

```

拿不到 会引起 uncaught exception.

**Comment by brickspert** [comment]
试试配下 `options.throwOnError = true`

**Comment by masontin** [comment]
@brickspert 
```js
    const { data, loading } = useRequest(`http://localhost:33001/announcement/api/announcements/${id}`, {
        throwOnError: true,
    })
```
请问，在不用 `run`的场景下，我在哪里 `catch` 被抛出 `error`?

**Comment by brickspert** [comment]
> @brickspert
> 
> ```js
>     const { data, loading } = useRequest(`http://localhost:33001/announcement/api/announcements/${id}`, {
>         throwOnError: true,
>     })
> ```
> 
> 请问，在不用 `run`的场景下，我在哪里 `catch` 被抛出 `error`?

onError

**Comment by masontin** [comment]
@brickspert 大佬，这个我测试过的，我后台是一个正常的 状态码 404 ，json格式响应， 控制台是会打印这个 Error，但是我期望是拿到服务器响应的数据... 
```js
    let { data, loading } = useRequest(`${process.env.REACT_APP_BACKEND_ANNOUNCEMENT}/api/announcements/${id}`, { 
        throwOnError: true,
        onError: (error, params) => {
            console.error(error);
        }
    });
```
```
 Uncaught (in promise) Error: 
    fetchProxy index.js:112
    promise callback*fetchProxy index.js:107
    promiseService index.js:122
    persist usePersistFn.js:53
    node_modules 0.chunk.js:407
    node_modules 0.chunk.js:488
    run useAsync.js:438
    useAsync useAsync.js:481
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 4
    unstable_runWithPriority scheduler.development.js:653
    React 6
    js index.js:8
    Webpack 7
index.js:112
```
<img width="1280" alt="WX20200907-224507@2x" src="https://user-images.githubusercontent.com/46433259/92398823-d40a8a80-f15b-11ea-8664-5364e705ed3d.png">
<img width="1280" alt="WX20200907-224553@2x" src="https://user-images.githubusercontent.com/46433259/92398892-eedcff00-f15b-11ea-8594-07f661d69515.png">

**Comment by masontin** [comment]
主要是不知道在哪里 handle 这个 rejection.....， onError处理不了，还是我语法不对？

**Comment by masontin** [comment]
```js
    return fetch.apply(void 0, __spread(args)).then(function (res) {
      if (res.ok) {
        return res.json();
      }

      throw new Error(res.statusText);
    });
```
根据这段代码，看来我是拿不到了... 我是 404响应，这里 `res.ok() = false`  这里 throw 的 Error我也无法catch...

**Comment by masontin** [comment]
> 当接收到一个代表错误的 HTTP 状态码时，从 fetch() 返回的 Promise 不会被标记为 reject， 即使响应的 HTTP 状态码是 404 或 500。相反，它会将 Promise 状态标记为 resolve （但是会将 resolve 的返回值的 ok 属性设置为 false ），仅当网络故障时或请求被阻止时，才会标记为 reject。

[https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API/Using_Fetch](https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API/Using_Fetch)

我认为这里应该继续处理，直接抛Error，有点暴力了... 不然拿不到 非2xx 状态的 response body了...

**Comment by masontin** [comment]
**曲线救国了** - 我看到别的大佬的 [Pull Requests # 508](https://github.com/alibaba/hooks/pull/508) 了，等你们商量好了，我再重构...
@brickspert 谢谢

> [requestMethod](https://ahooks.js.org/hooks/async#integration-request-library#__next:~:text=requestMethod)

```js
        requestMethod:() => (fetch(`${process.env.REACT_APP_BACKEND_ANNOUNCEMENT}/api/announcements/${id}`).then( response => {
            if(response.ok){
                return response.json();
            }else if(response.status === 404){
                response.json().then( data => {
                    setErrorData(data)
                })
            }else {
                //TODO
            }
        }))
```

**Comment by lujjjh** [comment]
#456 这个改动很值得商榷，`useRequest` 的大多数使用场景都是消费 `loading`、`data` 和 `error`，少数场景才会使用 `{ manual: true }` 结合 `run`。

改动导致的问题是，在大多数使用场景下会造成满屏的 uncaught in promise 且无法很容易地捕获（唯一的办法是改用 `{ manual: true }` 结合 `run`）。无论 `throwOnError` 是否为 `true`，错误时都会抛异常，违背了这个属性设计的初衷（至少与这个属性表面上的含义不符）。

另外，在 `Promise#catch` 里 `return Promise.reject` 和 `throw` 理应是等价的，不知为何此处有两种风格共存。

**Comment by brickspert** [comment]
> #456 这个改动很值得商榷，`useRequest` 的大多数使用场景都是消费 `loading`、`data` 和 `error`，少数场景才会使用 `{ manual: true }` 结合 `run`。
> 
> 改动导致的问题是，在大多数使用场景下会造成满屏的 uncaught in promise 且无法很容易地捕获（唯一的办法是改用 `{ manual: true }` 结合 `run`）。无论 `throwOnError` 是否为 `true`，错误时都会抛异常，违背了这个属性设计的初衷（至少与这个属性表面上的含义不符）。
> 
> 另外，在 `Promise#catch` 里 `return Promise.reject` 和 `throw` 理应是等价的，不知为何此处有两种风格共存。

这个改动确实有问题，也想改回去，但是怕 break change 后会坑很多用户。

目前应该最好的改动就是 非 manual 场景下，不 throw error 了。

**Comment by imyelo** [comment]
> > #456 这个改动很值得商榷，`useRequest` 的大多数使用场景都是消费 `loading`、`data` 和 `error`，少数场景才会使用 `{ manual: true }` 结合 `run`。
> > 改动导致的问题是，在大多数使用场景下会造成满屏的 uncaught in promise 且无法很容易地捕获（唯一的办法是改用 `{ manual: true }` 结合 `run`）。无论 `throwOnError` 是否为 `true`，错误时都会抛异常，违背了这个属性设计的初衷（至少与这个属性表面上的含义不符）。
> > 另外，在 `Promise#catch` 里 `return Promise.reject` 和 `throw` 理应是等价的，不知为何此处有两种风格共存。
> 
> 这个改动确实有问题，也想改回去，但是怕 break change 后会坑很多用户。
> 
> 目前应该最好的改动就是 非 manual 场景下，不 throw error 了。

但目前的改动已经是 breaking change, 原本需要在 service 里 throw error 的场景无法平滑升级了
