### ISSUE TITLE
useRequest 错误发生时会重置 data

### ISSUE THREAD

**Issue by ysh35** [alibaba/hooks#586]
useAsync.js 中的
```javascript
        _this.setState({
          data: undefined,
          error: error,
          loading: false
        });
```
把data  重置了，导致上一次成功的数据被销毁
可否增加配置项使其在错误发生时不重置 data

**Comment by brickspert** [comment]
useRequest 应该不会加这个配置的，useRequest 最本质的是对 promise resolve/reject 的管理，data 使用上一次的，违背了最基础的准则。

**Comment by mayacger** [comment]
那也应该置成 initialData，本来initialData是 {}，是为防止报错，结果，又给置成 undefined。
