### ISSUE TITLE
有些 umi-hook 标记废弃了的 hook，ahooks 在文档标记废弃。

### ISSUE THREAD

**Issue by xiaorong61** [alibaba/hooks#588]
https://hooks.umijs.org/zh-CN/hooks/deprecated/use-antd-table
![image](https://user-images.githubusercontent.com/5251387/89974747-7c7d1a00-dc96-11ea-9a2f-ba7cdd0dd892.png)

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/90015717-8c6b1d00-dcdb-11ea-8d0d-a4f79cdb3fac.png)


其实是有个重命名了，可以看下文档：https://ahooks.js.org/zh-CN/docs/umi-hooks-to-ahooks#%E5%88%A0%E9%99%A4
