### ISSUE TITLE
@umijs/hooks 1.x的useFormTable有bug

### ISSUE THREAD

**Issue by henryzp** [alibaba/hooks#590]
它的第一个参数：getTableData，函数接收的formData有问题。

自定义组件的值没了，经过断点，发现逻辑是在这个函数里面：

https://github.com/alibaba/hooks/blob/1.x/packages/hooks/src/useFormTable/index.ts#L87

我这边用的是antd4，它会走
https://github.com/alibaba/hooks/blob/1.x/packages/hooks/src/useFormTable/index.ts#L93
这里面的逻辑，走了antd3？

然后过滤了部分的字段，就是我的那个组件刚好是一个自定义的组件，我自己处理了`value`和`onChange`的逻辑，但是该字段被过滤掉了。

如果是走
https://github.com/alibaba/hooks/blob/1.x/packages/hooks/src/useFormTable/index.ts#L103
的逻辑，是没有问题。

**Comment by brickspert** [comment]
建议用 ahooks 的 useAntdTable 代替下。。

**Comment by henryzp** [comment]
问题是我项目会改动很大，而且真的用ahooks就没这个问题了吗？

发自我的 iPad

**Comment by henryzp** [comment]
@brickspert ，翻了一下ahooks的代码：

https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useAntdTable/index.ts#L98

和1.x的逻辑相同，antd4的最新版本会进`antd3`的判断分支

**Comment by brickspert** [comment]
和这个没关系，这个是没问题的。

自定义组件看这个：https://ahooks.js.org/zh-CN/hooks/table/use-antd-table#1-%E6%97%A0%E6%B3%95%E8%AF%BB%E5%8F%96%E6%88%96%E5%88%9D%E5%A7%8B%E5%8C%96%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E7%BB%84%E4%BB%B6%E7%9A%84%E5%80%BC

![image](https://user-images.githubusercontent.com/12526493/90085147-cffc7000-dd49-11ea-833a-f6bc57b334f9.png)

**Comment by henryzp** [comment]
@brickspert ，好奇问一下，为什么antd3的那个分支要进行过滤的行为。。

另外如果antd3和ant4都会走上面的if分支，那其实下面的没有必要了

**Comment by brickspert** [comment]
> @brickspert ，好奇问一下，为什么antd3的那个分支要进行过滤的行为。。
> 
> 另外如果antd3和ant4都会走上面的if分支，那其实下面的没有必要了

历史原因，antd 4 的特性是慢慢补上来的，我们这边代码还没改。
