### ISSUE TITLE
useRequest 有计划支持 GraphQL 吗？

### ISSUE THREAD

**Issue by ghost** [alibaba/hooks#591]
请问会支持 GraphQL 吗？

像 Vercel 的 SWR https://swr.vercel.app/docs/data-fetching#graph-ql

**Comment by brickspert** [comment]
useRequest 是对 Promise 的管理，完全可以发送 GraphQL 请求的~

**Comment by linbudu599** [comment]
有需要的话我可以参考 [graphql-hooks](https://github.com/nearform/graphql-hooks) 和 apollo-hooks 开发个`useQuery` 和 `useMutation` 出来~

**Comment by codenoobforreal** [comment]
> 请问会支持 GraphQL 吗？
> 
> 像 Vercel 的 SWR https://swr.vercel.app/docs/data-fetching#graph-ql

@lodisy 
我在codesandbox上写了个使用了graphql和axios的简单例子
[useRequest with graphql and axios](https://codesandbox.io/s/userequest-hook-with-graphql-and-axios-ix57w?file=/src/index.js)
