### ISSUE TITLE
按需加载问题

### ISSUE THREAD

**Issue by Caoqingda** [alibaba/hooks#595]
![image](https://user-images.githubusercontent.com/41361873/90211808-57b6ad00-de24-11ea-91e6-185e816fe910.png)
配置.babelrc之后，别的hooks可以使用，但是useRequest未找到，请问怎么办？
![image](https://user-images.githubusercontent.com/41361873/90211825-656c3280-de24-11ea-9730-865ec5e0c5d8.png)

**Comment by brickspert** [comment]
useRequest 需要从另外一个包中导出

`import useRequest from "@ahooksjs/use-request"`
