### ISSUE TITLE
useRequest，data获取不到。（设置formatResult: (result) => result,之后可以获取）

### ISSUE THREAD

**Issue by baiDog** [alibaba/hooks#597]
版本 "@ahooksjs/use-request": "^2.3.0",

**Comment by brickspert** [comment]
你是从 umi 中导出的 useRequest 吗？

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/90406415-b48dbe00-e0d7-11ea-8aee-7fa3ba7bb2f1.png)

**Comment by baiDog** [comment]
问题解决了；
解决思路：request: {
    dataField: 'xxxx',
  }配置和formatResult同时设置及细节的问题。

**Comment by baiDog** [comment]
谢了，兄弟

**Comment by KellenHe** [comment]
@baiDog 兄弟，我是在import { useRequest } from 'umi';
返回的data一直是undefined啊。
请问怎么解决

**Comment by brickspert** [comment]
> @baiDog 兄弟，我是在import { useRequest } from 'umi';
> 返回的data一直是undefined啊。
> 请问怎么解决

要求返回的数据结构必须有一层 data ： { data: xxx}

或者你设置个 formatResult: x=>x

**Comment by enjoydiy** [comment]
构建时配置     request: {
        dataField: 'data',
    } 这个写在哪里啊，也没有很明确的说

**Comment by brickspert** [comment]
> 构建时配置 request: {
> dataField: 'data',
> } 这个写在哪里啊，也没有很明确的说

https://umijs.org/plugins/plugin-request#datafield

**Comment by hongjinchen** [comment]
请问 formatResult: x=>x是个什么格式呢？现在我在官网上看到的例子是下面这样的，我不是特别理解，希望得到回答！
![image](https://user-images.githubusercontent.com/71253179/127975263-ad52d119-abfc-4ddf-89ae-3bccc14eb24b.png)
