### ISSUE TITLE
为什么我用useRequest 的时候设置prefix不起作用？默认不是umi-request吗？应该可以配置这个参数啊

### ISSUE THREAD

**Issue by GGCarry** [alibaba/hooks#598]

**Comment by brickspert** [comment]
贴下代码？

**Comment by GGCarry** [comment]
![image](https://user-images.githubusercontent.com/17262032/90462718-d91b8180-e13b-11ea-9bc1-4b1e4732f0c7.png)
![image](https://user-images.githubusercontent.com/17262032/90462782-fc463100-e13b-11ea-9273-6fea93d49d00.png)
![image](https://user-images.githubusercontent.com/17262032/90462858-2a2b7580-e13c-11ea-8b19-f5cae2853cfe.png)

**Comment by GGCarry** [comment]
> 贴下代码？

是我写法有问题吗？

**Comment by brickspert** [comment]
直接把 host 拼接到 url 上呀，prefix 不是这么用的吧。

**Comment by GGCarry** [comment]
> 直接把 host 拼接到 url 上呀，prefix 不是这么用的吧。

umi-request 参数里面不是有个prefix吗？？？为什么不是这样用？？？既然service默认是umi-request，配置项里面的url，method不是就是配置umi-request参数吗？那为什么不能用prefix

**Comment by GGCarry** [comment]
> 直接把 host 拼接到 url 上呀，prefix 不是这么用的吧。

我不是很清楚，你们这个service，第一个参数可以配置点什么，文档也没有写

**Comment by GGCarry** [comment]
> 直接把 host 拼接到 url 上呀，prefix 不是这么用的吧。

我不是很清楚，你们这个useRequest第一个参数,service可以配置点什么，文档也没有写

**Comment by GGCarry** [comment]
> 直接把 host 拼接到 url 上呀，prefix 不是这么用的吧。

![image](https://user-images.githubusercontent.com/17262032/90501621-35ec5b80-e17f-11ea-85bb-4775c947269b.png)
这里的意思不就是可以配置umi-request里面有的参数吗

**Comment by GGCarry** [comment]
> 直接把 host 拼接到 url 上呀，prefix 不是这么用的吧。

大神如果有空可以

**Comment by GGCarry** [comment]
其实简单点说，我就想配置baseURL，在useRequest里面我要怎么写

难道我要
{
   url: `${baseURL} + /api/v1/xxx`
}
这样？？？？？？？？？？？？


为什么不能增加一个配置项，像axios那样可以配置baseURL呢

**Comment by brickspert** [comment]
你用的是 ahooks 还是 umi hooks 呢？

ahooks 集成的是 fetch
umi hooks 集成的是 umi-request

**Comment by GGCarry** [comment]
> 你用的是 ahooks 还是 umi hooks 呢？
> 
> ahooks 集成的是 fetch
> umi hooks 集成的是 umi-request

原来如此，我用的是ahooks，我以为是一样的...我看文档都几乎一样，还以为是同一个东西
