### ISSUE TITLE
useAsync

### ISSUE THREAD

**Issue by ttys026** [alibaba/hooks#6]
根据之前尽龙的需求：
![image](https://user-images.githubusercontent.com/19804057/61215577-e9457e00-a73d-11e9-8ffb-30053dd54989.png)
有的 service 会被封装成函数。useAPI 不适用的情况

目前初步的想法是用 useAsync 代替，dummyCode：
![carbon](https://user-images.githubusercontent.com/19804057/61215059-493b2500-a73c-11e9-9b2f-683ab6b603d9.png)

useAsync 接受三个参数：
func: 一个 async function，用于被执行。
dependencies?: 依赖数组，在依赖改变是，会重新执行函数(当 initExecute 为 true 时)
initExecute?: 布尔值，是否默认执行，如果不传此参数，则**会**默认执行，否则只有在运行 run() 时才会执行函数。

返回值：
data: promise 的 resolve 值.
loading: promise 是否在进行中.
error: promise 的 reject 值.
cancel: 如果在 loading，运行 cancel() 可以取消此次 promise
run: run() 可以无视 deps 立即执行函数，如果 initExecute 为 false，则只有先运行 run() 才会执行.

**Comment by brickspert** [comment]
initExecute 可以扩展下

```
options: {
   initExecute: Boolean; // 是否初始化执行
   pollingInterval: number;  // 支持轮询，传一个轮询的间隔毫秒。 参数名字再议。
}
```
