### ISSUE TITLE
useScroll - add 'shouldUpdate' fn as a second param 

### ISSUE THREAD

**Issue by MisaGu** [alibaba/hooks#603]
The idea is to have a way to prevent unnecessary re-render by preventing the call of the `setPosition`.

In [useScroll](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useScroll/index.ts):
**shouldUpdate** - Return true/false to run/avoid state changing as so re-render the component.
**[#10](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useScroll/index.ts#L10)** `export type ShouldUpdateFn = (val: Position) => boolean`
**[#11](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useScroll/index.ts#L11)** `useScroll(target?: Target, shouldUpdate: ShouldUpdateFn = (val) => true)` *
**[#34](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useScroll/index.ts#L34)** `if (shouldUpdate(newPosition)) setPosition(newPosition);`

*By default we always want to update

**Example 1**
 I want to listen document scoll for the first 200px and later ignore it (do not call setPosition).

```
const position = useScroll(document, myThrottleFn);
function myThrottleFn({ top }) {
  return top < 200;
}
```
Inline:
`const position = useScroll(document, (newPos) => newPos.top < 200);`

**Example 1**
 I want to listen document scoll in range in between 300px and 500px and ignore any over value (do not call setPosition).

```
const position = useScroll(document, myThrottleFn);
function myThrottleFn({ top }) {
  return top > 300 && top < 500;
}
```
Inline:
`const position = useScroll(document, (newPos) => newPos.top > 300 && newPos.top < 500);`

There are many use cases where to apply - I believe is nice to have some way to manipulate the component performance.

Regards

**Comment by linbudu599** [comment]
WIP
