### ISSUE TITLE
useRequest 可以支持通过location.params来进行数据渲染不

### ISSUE THREAD

**Issue by hazeFlame** [alibaba/hooks#605]
change的时候修改location 去进行request

**Comment by jin-benben** [comment]
不是可以设置refreshDeps字段的值吗

**Comment by brickspert** [comment]
需求可以描述清晰点，应该是可以的。

**Comment by hazeFlame** [comment]
![image](https://user-images.githubusercontent.com/21263459/91379385-27740300-e855-11ea-994d-e4e69e3b700a.png)
![image](https://user-images.githubusercontent.com/21263459/91379413-38247900-e855-11ea-9aaf-e6529d6fd14f.png)

就内置的这个params 可以直接使用location query

**Comment by brickspert** [comment]
感觉没问题的吧
