### ISSUE TITLE
给 useRequest 添加开始请求的钩子函数

### ISSUE THREAD

**Issue by mehwww** [alibaba/hooks#607]
比如我目前有一个需求，希望全局配置在 useRequest 请求发出时使用 nprogress 显示请求进度条，现在除了 patch 一下 useRequest 是不是没有什么别的办法可以实现？

**Comment by brickspert** [comment]
> 比如我目前有一个需求，希望全局配置在 useRequest 请求发出时使用 nprogress 显示请求进度条，现在除了 patch 一下 useRequest 是不是没有什么别的办法可以实现？

确实没有办法，你可以基于 useRequest 封装一层就可以。

**Comment by mehwww** [comment]
> 确实没有办法，你可以基于 useRequest 封装一层就可以。

是的，不过那样各种类型处理起来会相对麻烦。。所以还是希望可以内置这个钩子设置

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
