### ISSUE TITLE
[useRequest] 组件卸载后，轮询并没有真正的结束

### ISSUE THREAD

**Issue by dengfuping** [alibaba/hooks#609]
- 尤其是页面中有多个轮询组件，而且是卡在下一次轮询请求开始之前卸载，就会出现残留的轮询无法停止的问题。
- 业务上尝试在组件卸载前调用 `cancel` 方法，仍然会有这个问题，怀疑 `fetchesRef` 并不是最新:
https://github.com/alibaba/hooks/blob/49d4dab854d21c93e4bbaa5c09edafa6bdacbbcc/packages/use-request/src/useAsync.ts#L468-L473

**Comment by brickspert** [comment]
我写了一个在线例子：https://codesandbox.io/s/xenodochial-pine-82pfb?file=/App.tsx

没有复现出来不能卸载的情况。你看下如何复现？
