### ISSUE TITLE
useAntdTable中，submit重新请求接口怎么设置pageNumber

### ISSUE THREAD

**Issue by shiwuqi** [alibaba/hooks#613]
在useAntdTable中，submit重新请求接口怎么设置pageNumber

**Comment by milkyu** [comment]
怎么解决的？大神

**Comment by milkyu** [comment]
`const {tableProps, search} = useAntdTable(getTableData, {
        defaultParams: [
            {
                current: 1,
                pageSize: 10,
            },
        ],
    });
// 刷新 第8页
tableProps.onChange({...tableProps.pagination, current: 8});
`
