### ISSUE TITLE
[useMouse] 监听函数是否应该添加防抖？

### ISSUE THREAD

**Issue by summmmer** [alibaba/hooks#614]

**Comment by MinJieLiu** [comment]
是非常有必要，它导致的 render 次数太多了

**Comment by brickspert** [comment]
自己把函数用 useDebounceFn 包一下就可以。

useMouse 自己不会加的。~~

**Comment by MinJieLiu** [comment]
useMouse 会带来成堆的 setState，自己包一下也仅仅是使用的地方函数防抖，useMouse 带来的 re-render 怎么避免？有例子没 @brickspert ，若有例子建议加在文档中

**Comment by brickspert** [comment]
> useMouse 会带来成堆的 setState，自己包一下也仅仅是使用的地方函数防抖，useMouse 带来的 re-render 怎么避免？有例子没 @brickspert ，若有例子建议加在文档中

应该在一个独立的小组件中去使用 useMouse。如果我们加了防抖，那肯定导致实时监听鼠标位置 卡顿。防抖需要业务根据自己的情况去实现。

**Comment by xmsz-stu** [comment]
这个useMouse确实有点吓人 基本就是疯狂渲染
