### ISSUE TITLE
[RFC] useReactive & useMethods

### ISSUE THREAD

**Issue by wen-haoming** [alibaba/hooks#615]
应用场景:  我们可能在业务组件中写几个useState，还要定义各种类型，触发视图还要手动更新，代码冗余且啰嗦。

借助`vue3`的响应式模块来实现类似vue的属性修改自动触发视图更新的操作，这样就不需要写那么useState或者触发更新的setState了，另外还有一个useMethods，能够很好包裹函数引用，使之不会重复创建，详情可以查看 http://whm.zone/hooks/#/hooks/use-methods

当然不使用`vue3` 而且使用`mobx`也是能实现的

### useReactive

``` jsx
import React from 'react';
import { useReactive } from 'v-reactive-hooks';

export default () => {
  let state = useReactive({
    count: 0
})
  return (
    <div>
      <p>
        计数器 state.count：<span role="addCount">{state.count}</span>
      </p>
      <button role="addCountBtn" onClick={() => (state.count += 1)}>
        count++
      </button>
    </div>
  );
};

 
```

### useMethods

``` jsx
import React from 'react';
import { useMethods } from 'v-reactive-hooks';

export default () => {
  const [state, boundMethods] = useMethods(
    { count: 0 },
    {
      addCount() {
        state.count += 1;
      },
    },
  );
  return (
    <div>
      <p role="countVal">{state.count}</p>
      <button role="addCount" onClick={boundMethods.addCount}>
        count++
      </button>
    </div>
  );
};

```

**Comment by brickspert** [comment]
我们看下~

**Comment by awmleer** [comment]
有个小疑问：useMethod 除了让 methods 函数的引用不变之外，还有其他作用么？因为函数引用的问题我们更推荐让用户直接用 `useCallback` 解决

**Comment by awmleer** [comment]
此外，可以发一下源代码的链接么～文档点进去好像并没有源码的链接

**Comment by brickspert** [comment]
同求

**Comment by brickspert** [comment]
> 此外，可以发一下源代码的链接么～文档点进去好像并没有源码的链接

https://github.com/wen-haoming/v-reactive-hooks

**Comment by wen-haoming** [comment]
> 有个小疑问：useMethod 除了让 methods 函数的引用不变之外，还有其他作用么？因为函数引用的问题我们更推荐让用户直接用 `useCallback` 解决

 确实，状态少的话useCallback会比较合适，但是如果state是一个大对象的话使用`useMethods` 这种形式有点类似于面向对象，能够直接增删改查当前的状态，个人感觉就像写redux的reducer那样，而且在函数组件这种过程式的写法上，太多的useCallback可能增加负担和代码量~

**Comment by awmleer** [comment]
@wen-haoming  `useMethods` 强制让返回的函数引用不变的话，可能会导致闭包问题：

```jsx
const [step, setStep] = useState(10);
const [state, boundMethods] = useMethods(
  { count: 0 },
  {
    addCount() {
      state.count += step; // step 变化的时候，这里还是会调用旧的函数，导致 bug
    },
  },
);
```

所以，最合理的方式还是要让用户自己去 `useCallback`。（其实在大部分场景下，都是不需要用 `useCallback` 的）

**Comment by awmleer** [comment]
所以我觉得只需要保留一个 `useReactive` 就可以了～

**Comment by wen-haoming** [comment]
> 所以我觉得只需要保留一个 `useReactive` 就可以了～

嗯嗯 确实也是，那我现在可以就提`useReactive` 这个pr吗？

**Comment by awmleer** [comment]
> 嗯嗯 确实也是，那我现在可以就提`useReactive` 这个pr吗？

可以的，欢迎PR～
