### ISSUE TITLE
[useAntdTable] getActivetFieldValues 方法的问题

### ISSUE THREAD

**Issue by hzyhbk** [alibaba/hooks#621]
本地项目升级之前用的是 antd 4.3.1 ,getActivetFieldValues 走的是最后一个 return 没问题，但是升级了组件库到4.6.1，就获取不到某个FormItem的值。
调试发现 antd 4.4.0 之后支持 form.getFieldInstance 方法，但是如果子组件是函数式组件的话，就会获取不到实例，然后导致最终 submit 方法获取到的表单值不对。

**Comment by hzyhbk** [comment]
![image](https://user-images.githubusercontent.com/42671099/91679474-f9573180-eb7a-11ea-8409-ff28ef712f6f.png)
如图，appCode 对应的 FormItem 是自定义的函数式组件，在 tempAllFiledsValue 里是有的，最终在 filterFiledsValue 中却被过滤掉了。

**Comment by hzyhbk** [comment]
用 React.forwardRef 包一下能解决问题，能解释下 getActivetFieldValues 方法里为什么要过滤一层吗？

**Comment by brickspert** [comment]
antd 3 需要过滤
