### ISSUE TITLE
使用useRequest loadMore 第一次重复请求了

### ISSUE THREAD

**Issue by WangJM001** [alibaba/hooks#624]
第一次发送了2个相同的请求

![image](https://user-images.githubusercontent.com/20501316/91799104-f0d52880-ec58-11ea-99b6-d4249ea4ed22.png)
![image](https://user-images.githubusercontent.com/20501316/91799126-fcc0ea80-ec58-11ea-8b98-047acfdac31f.png)

**Comment by brickspert** [comment]
因为你的 activeDate 发生了变化呀，refreshDeps 就是在参数发生变化后，重新触发的。

**Comment by WangJM001** [comment]
是有变化，undefined => {year:2020,month:9},  undefined时ready是false按说应该不请求，变化后请求一次，不是这个逻辑么？为啥是2次

**Comment by brickspert** [comment]
> 是有变化，undefined => {year:2020,month:9}, undefined时ready是false按说应该不请求，变化后请求一次，不是这个逻辑么？为啥是2次

ready 和 activeDate 是相互独立的。

**Comment by WangJM001** [comment]
什么意思？ready为false不是不发请求么？
或者说像这个情况怎么只发一次请求，activeDate变化时重新请求，activeDate为空时不发出请求

**Comment by brickspert** [comment]
activeDate 不适合放到 refreshDeps 里面。

自己用 useEffect 来处理下~

**Comment by WangJM001** [comment]
好吧

**Comment by WangJM001** [comment]
@brickspert useEffect 处理有新问题了，手动run过后，data没变，分页的状态没有重置
![image](https://user-images.githubusercontent.com/20501316/92100042-df814d00-ee0d-11ea-9d11-09cb030e3b38.png)

**Comment by WangJM001** [comment]
改用reload好了
