### ISSUE TITLE
BUG:useVirtualList 使用 scrollTo 的BUG

### ISSUE THREAD

**Issue by hellokidder** [alibaba/hooks#628]
使用了动态渲染列表的高度，想做成类似antd 树形控件的效果
![image](https://user-images.githubusercontent.com/23077808/91978367-8d312500-ed56-11ea-82b0-67c40fabceb3.png)
当我使用scrollTo 这个方法的时候有时候会产生1个差值，比如当我输入100，它会跳到101，然后再次调用则会显示正确的结果

**Comment by brickspert** [comment]
最好给个在线复现

**Comment by hellokidder** [comment]
尝试复现，无法复现而且原本有问题的代码也好了
