### ISSUE TITLE
配置UseRequestProvider引起的BUG

### ISSUE THREAD

**Issue by XuJin186** [alibaba/hooks#629]
配置：
` <UseRequestProvider
      value={{
        manual: true,
        debounceInterval:500
      }}
    >
<App/>
</UseRequestProvider>`
使用:
`
  const { run: loginRun, loading: loginLoading } = useRequest(LoginRequest);
    let response= await loginRun(value.userName, value.password);

`

此时response为null

**Comment by XuJin186** [comment]
我想这也许是正确的  是否可以在文档中列出  以防后面的人踩坑

**Comment by brickspert** [comment]
是正确的，debounce 场景下 run 其实没有立即执行。

**Comment by XuJin186** [comment]
> 是正确的，debounce场景下run其实没有立即执行。

好的   感谢回复
