### ISSUE TITLE
useRequest 依赖变化请求两次

### ISSUE THREAD

**Issue by katteXu** [alibaba/hooks#630]
loadMore：true的时候 通过下拉加载多次数据后，改变依赖值的时候，会发起2次请求；
第一次是正常请求即清空列表数据 重新请求第一页
第二次是异常请求  请求了最后一次加载的下一页数据

**Comment by katteXu** [comment]
而且并不是必显的 只有下拉加载次数多了 才会出现，目前来看是加载了5次以上的数据

**Comment by brickspert** [comment]
最好能给个复现，谢谢~~

**Comment by katteXu** [comment]
import { useRequest } from 'ahooks';
import React, { useState, useRef } from 'react';
import axios from 'axios';
interface Item {
  id?: string;
  name: string;
}

const getData = (currentPage: number) => {
  // 请求接口
  const request = axios.get(
    '数据接口'
  ).then(res => res.data);
  return request.then(res => {
    if (res.status === 0) {
      return {
        total: res.result.count,
        list: res.result.data,
        currentPage: res.result.page,
      };
    }
  });
};

const LoadMoreComponent = () => {
  const [query, setQuery] = useState({ name: '' });
  const ref = useRef<HTMLDivElement>(null);
  const { data, loading, loadingMore } = useRequest((res: { currentPage: number }) => {
    return getData(res?.currentPage || 0);
  },
    {
      loadMore: true,
      ref,
      refreshDeps: [query],
      isNoMore: (res: any) => {
        return res.list.length === res.total;
      },
    },
  );

  const scrollBottom = () => {
    const dom = ref.current;

    const height = dom?.scrollHeight;
    if (dom) {
      dom.scrollTop = height || 0;
    }
  }


  return (
    <div>
      <button onClick={() => setQuery({ ...query, name: "123" })}>依赖修改</button>
      <button onClick={() => scrollBottom()}>滚动到底部</button>
      <div style={{ overflow: 'scroll', height: 300 }} ref={ref}>
        {loading ? (
          <p>loading</p>
        ) : (
            <ul style={{ listStyleType: 'none', margin: 0, padding: 0 }}>
              {data?.list?.map((item: any, index: number) => (
                <li key={index} style={{ background: '#efefef', margin: 10, padding: 10, fontSize: 14 }}>
                  <div style={{ fontSize: 16, fontWeight: 'bold' }}>{item.name}</div>
                  <div>发货地：{item.from_address}</div>
                  <div>收货地：{item.to_address}</div>
                  <div>
                    {JSON.stringify(item)}
                  </div>
                </li>
              ))}
            </ul>
          )}
      </div>
    </div>
  );
};

export default LoadMoreComponent

**Comment by katteXu** [comment]
`
import { useRequest } from 'ahooks';
import React, { useState, useRef } from 'react';
import axios from 'axios';
interface Item {
  id?: string;
  name: string;
}

const getData = (currentPage: number) => {
  // 请求接口
  const request = axios.get(
    '数据接口'
  ).then(res => res.data);
  return request.then(res => {
    if (res.status === 0) {
      return {
        total: res.result.count,
        list: res.result.data,
        currentPage: res.result.page,
      };
    }
  });
};

const LoadMoreComponent = () => {
  const [query, setQuery] = useState({ name: '' });
  const ref = useRef<HTMLDivElement>(null);
  const { data, loading, loadingMore } = useRequest((res: { currentPage: number }) => {
    return getData(res?.currentPage || 0);
  },
    {
      loadMore: true,
      ref,
      refreshDeps: [query],
      isNoMore: (res: any) => {
        return res.list.length === res.total;
      },
    },
  );

  const scrollBottom = () => {
    const dom = ref.current;

    const height = dom?.scrollHeight;
    if (dom) {
      dom.scrollTop = height || 0;
    }
  }


  return (
    <div>
      <button onClick={() => setQuery({ ...query, name: "123" })}>依赖修改</button>
      <button onClick={() => scrollBottom()}>滚动到底部</button>
      <div style={{ overflow: 'scroll', height: 300 }} ref={ref}>
        {loading ? (
          <p>loading</p>
        ) : (
            <ul style={{ listStyleType: 'none', margin: 0, padding: 0 }}>
              {data?.list?.map((item: any, index: number) => (
                <li key={index} style={{ background: '#efefef', margin: 10, padding: 10, fontSize: 14 }}>
                  <div style={{ fontSize: 16, fontWeight: 'bold' }}>{item.name}</div>
                  <div>发货地：{item.from_address}</div>
                  <div>收货地：{item.to_address}</div>
                  <div>
                    {JSON.stringify(item)}
                  </div>
                </li>
              ))}
            </ul>
          )}
      </div>
    </div>
  );
};

export default LoadMoreComponent
`

**Comment by katteXu** [comment]
`import { useRequest } from 'ahooks';
import React, { useState, useRef } from 'react';
import axios from 'axios';
interface Item {
  id?: string;
  name: string;
}

const getData = (currentPage: number) => {
  // 请求接口
  const request = axios.get(
    '数据接口'
  ).then(res => res.data);
  return request.then(res => {
    if (res.status === 0) {
      return {
        total: res.result.count,
        list: res.result.data,
        currentPage: res.result.page,
      };
    }
  });
};

const LoadMoreComponent = () => {
  const [query, setQuery] = useState({ name: '' });
  const ref = useRef<HTMLDivElement>(null);
  const { data, loading, loadingMore } = useRequest((res: { currentPage: number }) => {
    return getData(res?.currentPage || 0);
  },
    {
      loadMore: true,
      ref,
      refreshDeps: [query],
      isNoMore: (res: any) => {
        return res.list.length === res.total;
      },
    },
  );

  const scrollBottom = () => {
    const dom = ref.current;

    const height = dom?.scrollHeight;
    if (dom) {
      dom.scrollTop = height || 0;
    }
  }


  return (
    <div>
      <button onClick={() => setQuery({ ...query, name: "123" })}>依赖修改</button>
      <button onClick={() => scrollBottom()}>滚动到底部</button>
      <div style={{ overflow: 'scroll', height: 300 }} ref={ref}>
        {loading ? (
          <p>loading</p>
        ) : (
            <ul style={{ listStyleType: 'none', margin: 0, padding: 0 }}>
              {data?.list?.map((item: any, index: number) => (
                <li key={index} style={{ background: '#efefef', margin: 10, padding: 10, fontSize: 14 }}>
                  <div style={{ fontSize: 16, fontWeight: 'bold' }}>{item.name}</div>
                  <div>发货地：{item.from_address}</div>
                  <div>收货地：{item.to_address}</div>
                  <div>
                    {JSON.stringify(item)}
                  </div>
                </li>
              ))}
            </ul>
          )}
      </div>
    </div>
  );
};

export default LoadMoreComponent`

**Comment by katteXu** [comment]
经过测试发现，只有当下拉dom里的数据足够多才会出现该问题
这个多还不是数据条数 感觉应该是字节数量 ，如果单条内容很少 要加载好多条数据才会复现

**Comment by katteXu** [comment]
`import { useRequest } from 'ahooks'; `
`import React, { useState, useRef } from 'react'; `
`import axios from 'axios'; `

`const getData = (currentPage: number) => {`
  `// 请求接口`
  `const request = axios.get(`http://yourapi/list?page=${currentPage + 1}&limit=10`).then(res => res.data);`
  `return request.then(res => {`
  `  if (res.status === 0) {`
     ` return {`
       ` total: res.result.count,`
       ` list: res.result.data,`
       ` currentPage: res.result.page,`
      `};`
    `}`
 ` });`
`};`

`const LoadMoreComponent = () => {`
  `const [query, setQuery] = useState({ name: '' });`
  `const ref = useRef<HTMLDivElement>(null);`
  `const { data, loading, loadingMore } = useRequest((res: { currentPage: number }) => {`
   ` return getData(res?.currentPage || 0);`
 ` },`
   ` {`
      `loadMore: true,`
     ` ref,`
     ` refreshDeps: [query],`
      `isNoMore: (res: any) => {`
        `return res.list.length === res.total;`
      `},`
  `  },`
 ` );`

  `const scrollBottom = () => {`
    `const dom = ref.current;`

    `const height = dom?.scrollHeight;`
   ` if (dom) {`
     ` dom.scrollTop = height || 0;`
   ` }`
  `}`
  `return (`
    `<div>`
    `  <button onClick={() => setQuery({ ...query, name: "123" })}>依赖修改</button>`
   `   <button onClick={() => scrollBottom()}>滚动到底部</button>`
      `<div style={{ overflow: 'scroll', height: 300 }} ref={ref}>`
        `{loading ? (`
        `  <p>loading</p>`
       ` ) : (`
          `  <ul style={{ listStyleType: 'none', margin: 0, padding: 0 }}>`
             ` {data?.list?.map((item: any, index: number) => (`
               ` <li key={index} style={{ background: '#efefef', margin: 10, padding: 10, fontSize: 14 }}>`
               `   <div style={{ fontSize: 16, fontWeight: 'bold' }}>{item.name}</div>`
                `  <div>发货地：{item.from_address}</div>`
             `     <div>收货地：{item.to_address}</div>``
              `    <div>`
                 `   {JSON.stringify(item)}`
                  `</div>`
               ` </li>`
              `))}`
           ` </ul>`
         ` )}`
     `</div>`
    `</div>`
  `);`
`};`

`export default LoadMoreComponent`

**Comment by katteXu** [comment]
代码格式化大概就这些吧

**Comment by katteXu** [comment]
[在线地址](https://codesandbox.io/s/dark-platform-yxcdw)

**Comment by brickspert** [comment]
fix in 2.6.0
