### ISSUE TITLE
useAntdTable/useFormTable 和 antd@4 的 Form.List 联动时，获取不到 Form.List 属性的值 

### ISSUE THREAD

**Issue by brickspert** [alibaba/hooks#631]

**Comment by brickspert** [comment]
https://codesandbox.io/s/green-breeze-06ppd?file=/App.tsx

**Comment by jin-benben** [comment]
https://github.com/ant-design/ant-design/issues/26434

**Comment by zhiyan** [comment]
antd 4.4.0开始在form instance上增加了getFieldInstance方法， useAntdTable之前用这个来判断v3/v4, 导致的该问题
