### ISSUE TITLE
useAsync 在 onSuccess 里面操控父组件的 state 时候有警告

### ISSUE THREAD

**Issue by DiamondYuan** [alibaba/hooks#64]
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in DownloadButton (created by Page)
```

**Comment by DiamondYuan** [comment]
> ```
> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
>     in DownloadButton (created by Page)
> ```

@tli4  这样改 onError 同理

```
  if (runCount === count.current) {
          if (options.onSuccess) {
            options.onSuccess(data);
          }
          if (runCount === count.current) {
            set(s => ({ ...s, data, loading: false }));
          }
        }
```

**Comment by ttys026** [comment]
@DiamondYuan 
应该是 onSuccess 里做了页面跳转，hooks 被卸载掉了。
加了一个针对  hooks mount 状态的判断 #66

**Comment by ttys026** [comment]
> @DiamondYuan
> 应该是 onSuccess 里做了页面跳转，hooks 被卸载掉了。
> 加了一个针对 hooks mount 状态的判断 #66

这里用 runCount 也能实现一样的效果，不需要多定义一个 ref 了，应该更合适。会修改成 runCount 的
