### ISSUE TITLE
[RFC] useAsync 的 state 里面增加一个参数

### ISSUE THREAD

**Issue by DiamondYuan** [alibaba/hooks#65]
https://github.com/umijs/hooks/blob/1968b7ac6fd2ad9a5b819a0b8a351cf2ccdebaa9/src/useAsync/index.ts#L111

把请求参数存下来。

### 实际场景

列表中有10个元素，ID分别为 1-10.

```
const update = useAsync(
    (spuId: string, autoFill: boolean) => {
      return postUpdate({
        id,
        categoryId:props.categoryId
      });
    },
    [props.categoryId],
    {
      manual: true,
    }
  );
```

上面这个 hooks，是没办法知道那个元素应该 loading 的。只能知道整体是处于 loading 状态。

**Comment by ttys026** [comment]
不知道我理解的正确不正确，假如是编辑一列 10 行的表格，这个时候正在编辑/保存的是哪一列，应该是组件内部维护的状态，这个状态交给 useAsync 去维护并不太合适

**Comment by DiamondYuan** [comment]
> 不知道我理解的正确不正确，假如是编辑一列 10 行的表格，这个时候正在编辑/保存的是哪一列，应该是组件内部维护的状态，这个状态交给 useAsync 去维护并不太合适

useAsync 在父组件中，子组件的的 loading 代表在 loading ，由父组件传递
子组件的调用父组件的 run 函数，此时父组件只知道有子组件在 loading，并不知道具体是哪个一个在 loading。如果 args 暴露出来的话，父组件只需要写 loading={item.id === args[0] and loading}

**Comment by brickspert** [comment]
@DiamondYuan 
useAsync 返回的数据中增加一个字段 params，把当前的 params 输出？是这样的意思吗？

**Comment by DiamondYuan** [comment]
> @DiamondYuan
> useAsync 返回的数据中增加一个字段 params，把当前的 params 输出？是这样的意思吗？

对，就是这意思。这样在某些场景下很方便，也没有 break change。

**Comment by brickspert** [comment]
> > @DiamondYuan
> > useAsync 返回的数据中增加一个字段 params，把当前的 params 输出？是这样的意思吗？
> 
> 对，就是这意思。这样在某些场景下很方便，也没有 break change。

好，我们支持一下。
