### ISSUE TITLE
useRequest  怎么  拿 结果 ，什么时候setState ? 文档 能 详细一点吗？

### ISSUE THREAD

**Issue by RobinYang11** [alibaba/hooks#650]

**Comment by RobinYang11** [comment]
`
 const { data }  = useRequest( getNmae)
  console.log(data);  //结果为什么是 undefined 
`

**Comment by brickspert** [comment]
文档上不是有很多 demo 吗？

https://ahooks.js.org/hooks/async

**Comment by RobinYang11** [comment]
看到了 ，原来 loading 为false 时，才能拿到结果。 每次 loading 的变化 都会触发 组件重新渲染。useRequest内部管理 这个状态。
所以应该这样 用对吗? 
```javascript 
 const {data,loading } = useRequest(......);
 return (
  <div>
    {
      !loading ? data : null
     }
  </div>
  )
```
