### ISSUE TITLE
useAntdTable 获取不了 自定义 AutoComplete 下的值

### ISSUE THREAD

**Issue by zjy01** [alibaba/hooks#653]
基于`AutoComplete`简单封装了一个 `MyAutoComplete`;
```tsx
// example
const MyAutoComplete = (props) => <AutoComplete {...props}/>
```
useAntdTable 进到了 antd3 的判断分支。
而且对MyAutoComplete的 `form.getFieldInstance(key)`是`undefined`
![image](https://user-images.githubusercontent.com/9987291/93575731-919f4400-f9cc-11ea-974f-9e37597b62a1.png)

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/93589309-388cdb80-f9df-11ea-8515-45931deca8b2.png)

https://ahooks.js.org/zh-CN/hooks/table/use-antd-table
