### ISSUE TITLE
[useRequest] 轮训请求可否考虑增加间隔请求，而不是固定时间请求

### ISSUE THREAD

**Issue by baranwang** [alibaba/hooks#654]
可否增加参数，使轮训为保持两次网络请求中间的间隔，而不是固定一个时间请求，可以防止低网速的情况下，出现大量 pending 的情况

**Comment by brickspert** [comment]
> 可否增加参数，使轮训为保持两次网络请求中间的间隔，而不是固定一个时间请求，可以防止低网速的情况下，出现大量 pending 的情况

现在就是这样的机制呀，等上一次请求返回之后，才开始计时。
