### ISSUE TITLE
useRequest 当service 为 string 时， data 里面 一直 没有数据 。 实际请求是返回数据了的

### ISSUE THREAD

**Issue by RobinYang11** [alibaba/hooks#655]
## 
```javascript
 export default () => {

  const { data, loading } = useRequest({
    url: "/api/getTest",
    method: "GET"
  })

  if (!loading) {
    console.log(data)
  }

  return <>
    {
      !loading ? "YES" : "NO"
    }
  </>
}
```
## network 是有结果的
![image](https://user-images.githubusercontent.com/20513480/93607879-7ea46800-f9fc-11ea-86a4-8cc284326342.png)

## loading 已经为false了 ，但是 data 里面什么也没有 ,一直显示 undefined
![image](https://user-images.githubusercontent.com/20513480/93607952-9845af80-f9fc-11ea-821e-ceff8ba2f953.png)

**Comment by brickspert** [comment]
你的 useRequest 是从 umi 中导出的吗

**Comment by RobinYang11** [comment]
真是 没生过 孩子  ，不知道 b 疼的，一个请求 搞出这么多花样。 谁有真多世界，一会儿 看 umi 的useRequest，一会儿看ahooks 的useRequest， 那bigfish 里面的useRequest 用的那个？   能不能 开发 一个 类似react 框架 出来 我看看 。 造 轮子 是闲的的蛋疼 我看 。
