### ISSUE TITLE
ahooks 的声明在 vscode里有些奇怪

### ISSUE THREAD

**Issue by yuxino** [alibaba/hooks#656]
这个不是`bug` ... 更有可能是`vscode`或者`tsc`的问题，但是使用的时候感觉有点奇怪，这个问题应该是因为`tsc`生成的给每个文件都生成了`d.ts`，有个解决的办法可能是把这些`d.ts`合并之类的？

首先有些hook在编辑器里面会提示两次。

![image](https://user-images.githubusercontent.com/12481935/93716593-4db26780-fba3-11ea-940b-ab991c601475.png)

![image](https://user-images.githubusercontent.com/12481935/93716590-45f2c300-fba3-11ea-92dd-f7ab5625d959.png)

这个俩次推导感觉是无意义的，如果俩个推导有不同的作用那是可以接受的，比如

- 点第一个自动引入 `import { useTextSelection } from "ahooks"`
- 点第二个自动引入 `import useTextSelection from "ahooks/lib/useTextSelection"`
- 或者是 `import useTextSelection from "ahooks/es/useTextSelection"`

还有的甚至会推荐三次

![image](https://user-images.githubusercontent.com/12481935/93716107-302fce80-fba0-11ea-9e04-1cb776d364d1.png)

但是有的只提示一次比如 `useMouse`，但是这样也有点问题

![image](https://user-images.githubusercontent.com/12481935/93716230-3a9e9800-fba1-11ea-9c45-ef672b03ecb9.png)

按了回车并不会自动帮我`import`到项目里, 并不会变成`import { useMouse } from "ahooks"`。就按下`enter`后。。没反应，变成这样

![image](https://user-images.githubusercontent.com/12481935/93716282-881b0500-fba1-11ea-92d6-63e60d66a228.png)

需要手动点一下，才会`import`。

![image](https://user-images.githubusercontent.com/12481935/93716295-949f5d80-fba1-11ea-93db-5b9abae50e54.png)

看了一下[源码](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useMouse/index.ts#L21)。发现`useMouse`的写法是类似`export default () => {}`，默认导出一个箭头函数，最终编译的样子会是这样的

![image](https://user-images.githubusercontent.com/12481935/93716340-d203eb00-fba1-11ea-81e9-32221ab28dfa.png)

其他的大多数都是通过`export default function`之类的导出，导出以后就会有两次提示的问题。

useDrop有三次提示，感觉可能是因为生成的`dts`的确是声明了三次。一次在`index.d.ts`里还有一次是在`useDrop/index.d.ts`里，最后一次是在它自己的声明文件`useDrop/useDrop.d.ts`。

**Comment by yuxino** [comment]
匿名函数那个是[bug](https://github.com/microsoft/TypeScript/issues/40817)。其他的也算不上bug。能优化的话更好，但是不优化其实也不影响使用，普通用户一般感觉也不是特别在意这件事情。

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/117426851-f953d080-af56-11eb-893e-df1e66277b5a.png)

测了下，似乎是没啥问题了。
