### ISSUE TITLE
useAntdTable调用submit时能不能停留在本页而不重置current

### ISSUE THREAD

**Issue by Tianfer** [alibaba/hooks#660]
问题: 如果我此时在current=5页中，表单中的某一项数据更新时刷新列表调用submit，current重置为1
期望: submit能支持传参，来决定current的值

**Comment by xylin123** [comment]
守一个解决。

**Comment by baxtergu** [comment]
有同样的问题，期待submit能支持传入pagination的参数，走初始化的那套逻辑

**Comment by elmelloi** [comment]
useAntdTable返回了useRequest所有的方法，你可以试试其他方法能不能解决

**Comment by baxtergu** [comment]
> 有同样的问题，期待submit能支持传入pagination的参数，走初始化的那套逻辑

仔细看了一下源码，可以使用 useAntdTable 返回的 `refresh()` 方法来带参数（包括pagination参数）重新加载。

```javascript
  const { refresh } = useAntdTable(service, options);
```

`useRequest` 返回的 `result` 在 `useAntdTable` 里是全量解构返回的。抱歉没有仔细看代码，这个问题困扰了蛮久了。

**Comment by baxtergu** [comment]
@Tianfer @xylin123 两位可以看一下是否能够解决，这个 issue 我觉得可以关闭了。

建议在文档里或者 FAQ 里补充一下这个情况的解决方式，文档里的接口定义文档没有完整覆盖所有的可用返回。@brickspert
