### ISSUE TITLE
useRequest的loadMore无效

### ISSUE THREAD

**Issue by PeiTianHuang** [alibaba/hooks#661]
```
const abc: MutableRefObject<HTMLDivElement | null> = useRef(null);
  const { data, reload } = useRequest(getLoadMoreList, {
    loadMore: true,
    ref: abc,
    isNoMore: d => (d ? d.list.length >= d.total : false),
    refreshDeps: [state.keyword, state.sortType]
  });
```

```
<div ref={abc} style={{height: '20px', overflow: 'auto'}}>
      <div>dfsdfsdf</div>
      <div>dfsdfsdf</div>
      <div>dfsdfsdf</div>
      <div>dfsdfsdf</div>
      <div>dfsdfsdf</div>
      <div>dfsdfsdf</div>
      <div>dfsdfsdf</div>
      <div>dfsdfsdf</div>
      <div>dfsdfsdf</div>
    </div>
```

以上代码在使用ahooks 2.6.0 时，滚动到盒子底部无法触发数据加载，但用@umijs/hooks 1.9.3 则可以，看文档好像两者的使用方法一致，求大神指点

**Comment by brickspert** [comment]
老哥，你可以提供一个在线复现吗？

**Comment by PeiTianHuang** [comment]
> 老哥，你可以提供一个在线复现吗？

在官方示例（https://codesandbox.io/s/wbv6s?file=/App.tsx）中用个Modal包裹一下div即可重现
![image](https://user-images.githubusercontent.com/17986764/94096646-2c79a180-fe57-11ea-8bd2-2eff056fe09e.png)

**Comment by PeiTianHuang** [comment]
> 老哥，你可以提供一个在线复现吗？

用Modal或Drawer组件包裹后都能重现

**Comment by LanJamRom** [comment]
modal或者 drawer使用getContainer挂载在父节点下就不会出现这个问题

**Comment by LanJamRom** [comment]
我也遇到了这种情况，弹窗内loadMore无效

**Comment by jiahuijie** [comment]
> > 老哥，你可以提供一个在线复现吗？
> 
> 用Modal或Drawer组件包裹后都能重现

我也遇到这个问题了，目前解决方案是将 加载更多 的dom再封装一个组件，在Modal、Popover中传入该组件才能触发loadmore，

例如在Popover中使用Loadmore，将Loadmore内容封装到PopoverContent组件，然后如下写法即可

`<Popover
      content={(<PopoverContent />)}
    >
      {children}
    </Popover>`

**Comment by jiahuijie** [comment]
> 我也遇到了这种情况，弹窗内loadMore无效

> > 老哥，你可以提供一个在线复现吗？
> 
> 用Modal或Drawer组件包裹后都能重现

我也遇到这个问题了，目前解决方案是将 加载更多 的dom再封装一个组件，在Modal、Popover中传入该组件才能触发loadmore，

例如在Popover中使用Loadmore，将Loadmore内容封装到PopoverContent组件，然后如下写法即可

`<Popover
      content={(<PopoverContent />)}
    >
      {children}
    </Popover>`

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
