### ISSUE TITLE
loadMore模式，无法通过mutate修改之前页的数据

### ISSUE THREAD

**Issue by feibi** [alibaba/hooks#662]
mutate的参数只能操作本次请求的数据，之前的数据无法修改

**Comment by CodePirate7** [comment]
这个问题有进展吗？

**Comment by without-yy** [comment]
同样遇到了，有什么办法处理吗

**Comment by brickspert** [comment]
下个大版本修复

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

**Comment by feibi** [comment]
@brickspert nice，辛苦
