### ISSUE TITLE
[建议] useRequest抛错时不改变data的赋值

### ISSUE THREAD

**Issue by zjy01** [alibaba/hooks#666]
### 现状
useRequest 抛错时会将data设置未`undefined`, 导致页面需要添加很多处理逻辑。

### 需求
希望useRequest 抛错时能可控地保留data的原值。
比如，轮询查询一个东西的进度的时候，即使报错，也希望能使用上一次请求的值。
比如，一个普通的查询接口，即使报错了，也希望能使用默认值。

### 建议
添加一个配置，支持异步抛错任保留data值。
```ts
useRequest(service, {
  keepValueWhenError: true
})
```

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
