### ISSUE TITLE
useUrlState在同一个方法中多次setState不同值，结果不符合预期

### ISSUE THREAD

**Issue by WangJM001** [alibaba/hooks#671]
## 实际使用中有些参数会分开多次setState, 希往能合并处理
![image](https://user-images.githubusercontent.com/20501316/94583741-65c76c80-02b0-11eb-8d47-eb8031fe632c.png)
点击add后
`search = ?count2=3`

## 期望
`search = ?count=2&count2=3`

**Comment by brickspert** [comment]
这个是符合预期的，和 useState 的 setState 行为一致的。

setState 是异步的，不是同步的。

**Comment by WangJM001** [comment]
![image](https://user-images.githubusercontent.com/20501316/94638479-aead0e80-030c-11eb-82a9-a10a13673250.png)

这种情况了，不同组件要取url query不同的部分，设置也希望是各设各的
@brickspert

**Comment by jk4235** [comment]
> 这个是符合预期的，和 useState 的 setState 行为一致的。
> 
> setState 是异步的，不是同步的。

异步没问题，但是需要支持setState(s  =>  newS)这种方式来解决多次调用的问题吧
用个ref记一下我感觉就能解决这个问题

<img width="1142" alt="Image" src="https://github.com/user-attachments/assets/49cc0c74-6c74-44f4-a4ea-36971d870307" />
