### ISSUE TITLE
object doesn't support property or method 'finally'

### ISSUE THREAD

**Issue by ClenLu** [alibaba/hooks#682]
ie11 报错 object doesn't support property or method 'finally'   项目空白   生产环境了  @brickspert

**Comment by ClenLu** [comment]
![image](https://user-images.githubusercontent.com/17354771/95942587-1d628f80-0e16-11eb-9747-27fc4c1c7ffa.png)

**Comment by brickspert** [comment]
https://github.com/alibaba/hooks/issues/426
