### ISSUE TITLE
require cycle

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [alibaba/hooks#685]
![image](https://user-images.githubusercontent.com/5756752/96092062-ef0baf80-0efc-11eb-96b4-b02b788ba19a.png)

"ahooks": "^2.6.1",

**Comment by Darkhorse-Fraternity** [comment]
![image](https://user-images.githubusercontent.com/5756752/96092176-19f60380-0efd-11eb-8da7-61eda7444f4c.png)

**Comment by brickspert** [comment]
we have fixed in newst version~
