### ISSUE TITLE
[疑惑] @umijs/hooks 与 ahooks API用法为何有差异?

### ISSUE THREAD

**Issue by cc7gs** [alibaba/hooks#687]
## 描述
目前 @umijs/hooks官方github地址已经指向 ahooks了，但是他们有些API用法是完全不同的。

## 案例:
```ts
//@umijs/hooks 使用
const [ state, ref? ] = useSize(dom);

//ahooks使用
declare function useSize(target: BasicTarget): Size;
```
## 问题

之后通过 umi创建的使用该如何切换？ 还是两个库并存一直发展？

**Comment by brickspert** [comment]
ahooks 相当于 umi hooks v2.0 版本，1.0 版本不会长期维护了，建议升级到 ahooks。

升级文档：https://ahooks.js.org/zh-CN/docs/umi-hooks-to-ahooks

老的文档可以从这里看：
![image](https://user-images.githubusercontent.com/12526493/96210994-ba076780-0fa5-11eb-838c-c13024047954.png)

**Comment by cc7gs** [comment]
目前 umi@3.x 会自动引入 @umijs/hooks 包；该如何升级 2.x呢？ 需要手动 引入 ahooks？

**Comment by brickspert** [comment]
> 目前 [umi@3.x](mailto:umi@3.x) 会自动引入 @umijs/hooks 包；该如何升级 2.x呢？ 需要手动 引入 ahooks？

umi@3.x 没有内置 @umijs/hooks 呀，是不是搞错了？

**Comment by cc7gs** [comment]
> > 目前 [umi@3.x](mailto:umi@3.x) 会自动引入 @umijs/hooks 包；该如何升级 2.x呢？ 需要手动 引入 ahooks？
> 
> [umi@3.x](mailto:umi@3.x) 没有内置 @umijs/hooks 呀，是不是搞错了？

umi@3.x 没有内置，但不需要 package.json手动引入该依赖包(@umijs/hooks),会自动引入。
目前也没有途径去选择。所以只能通过手动引入 ahooks@2.x依赖包是这样吗？

**Comment by brickspert** [comment]
> > > 目前 [umi@3.x](mailto:umi@3.x) 会自动引入 @umijs/hooks 包；该如何升级 2.x呢？ 需要手动 引入 ahooks？
> > 
> > 
> > [umi@3.x](mailto:umi@3.x) 没有内置 @umijs/hooks 呀，是不是搞错了？
> 
> [umi@3.x](mailto:umi@3.x) 没有内置，但不需要 package.json手动引入该依赖包(@umijs/hooks),会自动引入。
> 目前也没有途径去选择。所以只能通过手动引入 [ahooks@2.x](mailto:ahooks@2.x)依赖包是这样吗？

嗯嗯，是的呢。
