### ISSUE TITLE
[讨论]useAsync 是否需要竞态处理

### ISSUE THREAD

**Issue by brickspert** [alibaba/hooks#69]
目前 useAsync 默认开启竞态处理，在有些场景下不太合适。

比如，一个列表页有 10 条数据，每一条都有自己单独的删除，当我同时删除好几条的时候，下一次请求总是会把上一次请求废弃掉，这样是不符合预期的。

个人建议是默认不开启竞态处理，可以提供个开启的开关。

**Comment by DiamondYuan** [comment]
> 目前 useAsync 默认开启竞态处理，在有些场景下不太合适。
> 
> 比如，一个列表页有 10 条数据，每一条都有自己单独的删除，当我同时删除好几条的时候，下一次请求总是会把上一次请求废弃掉，这样是不符合预期的。
> 
> 个人建议是默认不开启竞态处理，可以提供个开启的开关。

默认开启。否则就是 break change。原有其他项目都需要修改。

这个问题我也发现了，我觉得使用发布一个新的 hooks 会不会好一点。在 useAsync 的基础上封装一下。

我现在这个场景只出现了一次，所以在每条数据里面都写了 useAsync 。

**Comment by brickspert** [comment]
新建一个 Hooks 不是很好。

**Comment by brickspert** [comment]
可以考虑增加一个 配置项，可以关掉竞态处理。

**Comment by ttys026** [comment]
可以加一个 autoCancel 的配置项，default 是 true
