### ISSUE TITLE
useUrlState 在 codesandbox 中打开是会报错的

### ISSUE THREAD

**Issue by brickspert** [alibaba/hooks#693]
https://ahooks.js.org/zh-CN/hooks/state

**Comment by linbudu599** [comment]
需要包一下`Router`:
```typescript
// App.tsx
import React from "react";
import { Router, Route } from "react-router";
import { createMemoryHistory } from "history";

import useUrlState from "@ahooksjs/use-url-state";

const history = createMemoryHistory();

const App = () => {
  const [state, setState] = useUrlState({ count: "1" });

  return (
    <>
      <button
        style={{ marginRight: 8 }}
        type="button"
        onClick={() => setState({ count: Number(state.count || 0) + 1 })}
      >
        add
      </button>
      <button type="button" onClick={() => setState({ count: undefined })}>
        clear
      </button>
      <div>state: {state?.count}</div>
    </>
  );
};

export default () => {
  return (
    <>
      <Router history={history}>
        <Route component={App} />
      </Router>
    </>
  );
};
```

但是页面和内嵌iframe的URL不会变化，不确定是不是Sandbox这个虚拟环境导致的

**Comment by ttys026** [comment]
> 需要包一下`Router`:
> 
> ```ts
> // App.tsx
> import React from "react";
> import { Router, Route } from "react-router";
> import { createMemoryHistory } from "history";
> 
> import useUrlState from "@ahooksjs/use-url-state";
> 
> const history = createMemoryHistory();
> 
> const App = () => {
>   const [state, setState] = useUrlState({ count: "1" });
> 
>   return (
>     <>
>       <button
>         style={{ marginRight: 8 }}
>         type="button"
>         onClick={() => setState({ count: Number(state.count || 0) + 1 })}
>       >
>         add
>       </button>
>       <button type="button" onClick={() => setState({ count: undefined })}>
>         clear
>       </button>
>       <div>state: {state?.count}</div>
>     </>
>   );
> };
> 
> export default () => {
>   return (
>     <>
>       <Router history={history}>
>         <Route component={App} />
>       </Router>
>     </>
>   );
> };
> ```
> 
> 但是页面和内嵌iframe的URL不会变化，不确定是不是Sandbox这个虚拟环境导致的

This should work

```tsx
import React from 'react';
import useUrlState from '@ahooksjs/use-url-state';
import { Router, Route } from "react-router";
import { createBrowserHistory } from "history";

const history = createBrowserHistory();

const App = () => {
  const [state, setState] = useUrlState({ count: '1' });

  return (
    <>
      <button
        style={{ marginRight: 8 }}
        type="button"
        onClick={() => setState({ count: Number(state.count || 0) + 1 })}
      >
        add
      </button>
      <button type="button" onClick={() => setState({ count: undefined })}>
        clear
      </button>
      <div>state: {state?.count}</div>
    </>
  );
};

export default () => {
  return <Router history={history}>
  <Route component={App} />
</Router>
}

```
