### ISSUE TITLE
配合babel-plugin-import使用按需加载时报错：Module not found: Can't resolve 'ahooks/es/useDrag'

### ISSUE THREAD

**Issue by suiyi8760** [alibaba/hooks#694]
跳到`node_modules/ahooks`目录里找，useDrag是在useDrop里一起export的，可能被babel-plugin-import后转换的路径不正确？

**Comment by suiyi8760** [comment]
临时解决方案，手动引入 `import { useDrop, useDrag } from 'ahooks/es/useDrop'`

**Comment by brickspert** [comment]
这个确实会有问题，因为两个 Hooks 写到一起了。 @ttys026
