### ISSUE TITLE
usePersistFn no useCallback (possible optimization)

### ISSUE THREAD

**Issue by bruce965** [alibaba/hooks#697]
Hi, I think it would be possible to optimize [`usePersistFn`](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/usePersistFn/index.ts) to skip some allocations, and to completely omit using `useCallback`.

According to React [documentation](https://reactjs.org/docs/hooks-reference.html#usecallback), `useCallback(fn, deps)` is equivalent to `useMemo(() => fn, deps)`, and they suggest to _rely on `useMemo` as a performance optimization, not as a semantic guarantee,_ [because] _in the future, React may choose to “forget” some previously memoized values_.

I would change it to something like this:

```diff
-import { useCallback, useRef } from 'react';
+import { useRef } from 'react';

 export type noop = (...args: any[]) => any;

 function usePersistFn<T extends noop>(fn: T) {
-  const ref = useRef<any>(() => {
-    throw new Error('Cannot call function while rendering.');
-  });
+  const ref = useRef<any>();

+  if (ref.current == null) {
+    ref.current = {
+      persistFn: (...args) => ref.current.fn(...args)
+    };
+  }

-  ref.current = fn;
+  ref.current.fn = fn;

-  const persistFn = useCallback(((...args) => ref.current(...args)) as T, [ref]);

-  return persistFn;
+  return ref.current.persistFn;
 }

 export default usePersistFn;
```

I have an implementation ready, it passes al tests and seems to behave exactly as the original.
I also passed `this` to the wrapped function, assuming it could be useful in some cases.

https://github.com/bruce965/hooks/commit/93b0cfe0dce593013dbb44779ffc37d276cbe003

I'll open a pull request if you thing this could be valid.
Thanks!

**Comment by awmleer** [comment]
LGTM and PR welcomed!

I have some questions about the implementation detail and left some comments on this commit.

**Comment by bruce965** [comment]
Sorry for the delay, I replied to your comments on https://github.com/bruce965/hooks/commit/93b0cfe0dce593013dbb44779ffc37d276cbe003.

**Comment by awmleer** [comment]
Please feel free to open an PR.
