### ISSUE TITLE
useVirtualList 能否提供一个在配合antd table使用的案例

### ISSUE THREAD

**Issue by xiexingen** [alibaba/hooks#699]

**Comment by FunnyWolf** [comment]
同样需要一个案例,antdesign 提供的官方样例太复杂了
https://ant-design.gitee.io/components/table-cn/#components-table-demo-virtual-list

**Comment by brickspert** [comment]
antd v4 自带了虚拟滚动：https://ant.design/components/table-cn/#components-table-demo-virtual-list
