### ISSUE TITLE
useLoadMore

### ISSUE THREAD

**Issue by brickspert** [alibaba/hooks#7]
适用于在同一个列表中，点击加载更多，或者上拉加载更多的应用场景。

**我们假设，在加载更多场景中，一般是 page 一直是 1，而 pageSize 不断变大**

```
const {
  loading,
  loadMoreIng,
  data,
  reload，
  loadMore,
  noMore,
  total
} = useLoadMore(loadData, deps ,options: { filterData ,initPageSize, peerPageSize, ref});
```

**输入**

* loadData 一个 Promise 函数，接收参数为总的 pageSize
* deps 依赖数组，如果变化后，则触发 reload
* options
   - filterData 一个处理 loadData 返回数据的函数，我们需要通过这个函数，拿到总的 total, 以便知道是否还需要加载更多
   - initPageSize 第一页需要加载的数据数量，默认为 10
   - peerPageSize 加载更多时，每次加载更多的页数，默认等于 initPageSize
   - ref 滚动区域的 dom 节点，如果有 ref，在滚动到底部时，会自动触发 loadMore

**输出**

* loading 是否正在进行第一次加载
* loadMoreIng 是否正在加载更多
* data  loadData 返回的数据
* reload 触发重新加载
* loadMore 触发加载更多
* noMore 是否还有更多数据
* total 数据总量

**应用场景**

适用于 点击加载 更多的场景，另外一种 上拉加载 更多同理

```javascript
const Demo = (type) => {
  const loadData = pageSize => asyncGetList(pageSize);

  const {
    loading,
    loadMoreIng,
    data,
    loadMore,
    reload,
    noMore,
    total
  } = useLoadMore(loadData, [ type ], {
    filterData: data => data.total,
    initPageSize: 10,
    peerPageSize: 5
  });

  const renderLoadMore = () => {
    if (!noMore) {
      return '没有更多数据了'
    }
    if (loadMoreIng) {
      return '正在加载更多数据'
    }
    return <div onClick={loadMore}>点击加载更多</div>
  }

  return (
    <Spin spinning={loading}>
      总共有{total}条数据
      {/* 从 data 中拿到列表的数据 */}
      {data.result.map(i => <List data={i} key={i.id} />)}
      {/* 加载更多 */}
      {renderLoadMore()}
    </Spin>
  )
}
```

**Comment by brickspert** [comment]
有个问题：
在这个场景中，我们是假设在 加载更多 场景中，都是 page 不变，pageSize 一直变大。 好像不是非常合理。
但是使用其它方式如何避免数据重复的问题呢？

**Comment by xc1427** [comment]
我有个疑问，pageSize 这种字段非常强依赖于 API，这个怎么做到 loadMore 这个hook 不去感知？

**Comment by brickspert** [comment]
@xc1427 有个 filterData，需要告诉怎么拿到 pageSize
