### ISSUE TITLE
useKeyPress支持清除订阅事件

### ISSUE THREAD

**Issue by myywlc** [alibaba/hooks#705]
现在进入几次页面,触发方法就执行几次,事件没有清除

**Comment by brickspert** [comment]
确实有点问题：https://codesandbox.io/s/basic-usage-forked-8dmyj?file=/App.tsx

会触发两次

**Comment by brickspert** [comment]
我今天重新试了试，事件确实已经被卸载了，无法复现你的问题，你能给个复现么~
