### ISSUE TITLE
[useRequest] table分页管理 sort排序时页码重置

### ISSUE THREAD

**Issue by cc7gs** [alibaba/hooks#709]
# 仓库复现地址

https://codesandbox.io/s/antd-table-forked-lkwj2?file=/App.tsx

# 问题描述
 1. table 分页选择页数后，在点击 sort排序后 会默认充值到默认页数

# 复现步骤
![image](https://user-images.githubusercontent.com/36002392/98322346-25cb7600-2022-11eb-9259-1db30c46b3a6.png)
![image](https://user-images.githubusercontent.com/36002392/98322393-45fb3500-2022-11eb-9c8d-58e99487fd80.png)

# 疑惑？

 若将 `<Table/>`  `pagination={false}` 参数去除后sort排序可以正常

**Comment by brickspert** [comment]
这个其实是预期行为。。
