### ISSUE TITLE
useVirtualList

### ISSUE THREAD

**Issue by ttys026** [alibaba/hooks#71]
适用展示大量数据需要做虚拟列表做性能优化的场景。可以和 useLoadMore 结合，形成大量数据展示的最佳实践。

```
const {
  list,
  containerProps,
  getItemProps,
  getItemVisibility,
  isScrolling,
  noMore,
} = useVirtual(data, initialSize, incrementalSize, threshold);
```

**输入**

* data 原始的全量数据，
* initialSize 初始载入条目数
* incrementalSize 每次增加条目数
* threshold 距离底部多少条时开始加载

- [ ] 待讨论是否要把 loadMore 的 asyncFunction 也传进去，触及数据底部自动 append list

**输出**

* list 需要展示的部分数据,
* containerProps 滚动容器的 props, 包含部分 style 和 onScroll 之类属性,
* getItemProps 一个函数，getItemProps(index) => itemProps, 包含 style (position，height)
* getItemVisibility 一个函数，getItemVisibility(index) => visible, 是否在视区内, boolean
* isScrolling 当前是否在滚动，boolean，
* noMore 是否载入了全部数据，boolean,

**应用场景**

适用展示大量数据需要做虚拟列表做性能优化的场景。可以和 useLoadMore 结合，形成大量数据展示的最佳实践。

```javascript
const Demo = (type) => {

const {
  list,
  containerProps,
  getItemProps,
  getItemVisibility,
  isScrolling,
  noMore,
} = useVirtual([1,2,3, ..., 9999], 10, 10, 3);

  return (
    <>
        <div {...containerProps}>
            {list.map((ele, index)=>(<div {...getItemProps(index)}>{ele}</div>))}
        </div>
        {noMore && <>已经加载完毕</>}
    </>
  )
}
```

**Comment by ttys026** [comment]
不一定需要自己造轮子，可以复用现在成熟的虚拟列表库

**Comment by brickspert** [comment]
1. 改名为 useVirtualList
2. 参数改为 useVitrualList(data, options)， options 均是可选的，会提供默认值。

**Comment by ttys026** [comment]
see #75

**Comment by excellnn** [comment]
请问getItemVisibility这个函数为什么不提供了
