### ISSUE TITLE
能否支持中文输入法下的防抖，即我正在输入拼音的时候，不要执行

### ISSUE THREAD

**Issue by ghost** [alibaba/hooks#710]
链接：https://ahooks.js.org/zh-CN/hooks/life-cycle/use-debounce-effect

如图， 我中文还没有输入完毕，还在思考下一个输入什么拼音，这个方法已经帮我执行了

有办法 针对中文输入法做一些特殊处理吗。 

![image](https://user-images.githubusercontent.com/6580897/98331198-07bc4080-2037-11eb-9a73-eb11863e1366.png)

**Comment by brickspert** [comment]
参考：https://github.com/hanrenguang/notes/issues/10
