### ISSUE TITLE
是否可以支持 useRquest 修改配置？或者 某些配置 可以支持切换，比如轮询功能

### ISSUE THREAD

**Issue by linhf123** [alibaba/hooks#711]
希望 realtime 为 true 的时候开启轮询

![img](https://user-images.githubusercontent.com/32009993/98341802-69d27100-204a-11eb-8598-9fbac31d8871.png)

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
