### ISSUE TITLE
在 antd pro种 使用useRequest 网络错误后会闪屏

### ISSUE THREAD

**Issue by wavesbig** [alibaba/hooks#713]
使用了useRequest请求后组件会渲染一次。
![image](https://user-images.githubusercontent.com/34082148/98433654-ec6b3700-2103-11eb-8113-e34b6ddd99ba.png)
app.ts
![image](https://user-images.githubusercontent.com/34082148/98433657-f0975480-2103-11eb-87ab-0334a17f7aa0.png)

**Comment by brickspert** [comment]
组件重新渲染是正常的，React Hooks 在更新状态时会驱动组件重新执行。

**Comment by wavesbig** [comment]
> 组件重新渲染是正常的，React Hooks 在更新状态时会驱动组件重新执行。

有的地方使用会导致闪屏喃

**Comment by brickspert** [comment]
> > 组件重新渲染是正常的，React Hooks 在更新状态时会驱动组件重新执行。
> 
> 有的地方使用会导致闪屏喃

这个我理解是组件渲染逻辑的问题吧。在某些条件下，组件没有渲染东西。

**Comment by wavesbig** [comment]
> > > 组件重新渲染是正常的，React Hooks 在更新状态时会驱动组件重新执行。
> > 
> > 
> > 有的地方使用会导致闪屏喃
> 
> 这个我理解是组件渲染逻辑的问题吧。在某些条件下，组件没有渲染东西。

我在研究一下
