### ISSUE TITLE
为什么我在使用useRequest时拿不到数据?

### ISSUE THREAD

**Issue by Larva02** [alibaba/hooks#714]
我在学习使用useRequest使用集成请求库
https://codesandbox.io/s/3nb0z?file=/App.tsx
仿照后写的RN demo 请求fail,Why?
![image](https://user-images.githubusercontent.com/12692666/98532794-23387d00-22bd-11eb-9f4d-acd78d4946ec.png)

**Comment by Larva02** [comment]
import { useRequest } from 'ahooks';
import React from 'react';
import {Text} from "react-native";
export default () => {
    const { data, error, loading } = useRequest('https://helloacm.com/api/random/?n=8&x=4');

    if (error) {
        return <Text>failed to load</Text>;
    }
    if (loading) {
        return <Text>loading...</Text>;
    }
    return <Text>Number: {data}</Text>;
};

报错：
[Mon Nov 09 2020 18:53:44.393]  WARN     Require cycle: node_modules\ahooks\lib\index.js -> node_modules\ahooks\lib\useCookieState\index.js -> node_modules\ahooks\lib\index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Mon Nov 09 2020 18:53:44.396]  LOG      Running "RNTest" with {"rootTag":161}
[Mon Nov 09 2020 18:53:44.891]  ERROR    [Error]
[Mon Nov 09 2020 18:53:47.300]  WARN     Possible Unhandled Promise Rejection (id: 0):
"useRequest has caught the exception, if you need to handle the exception yourself, you can set options.throwOnError to true."

**Comment by hqylss111** [comment]
你解决了嘛 我也遇到了这个问题

**Comment by brickspert** [comment]
暂时先这样用下试试 `import useCookieState from 'ahooks/lib/useCookieState'`

**Comment by hqylss111** [comment]
import&nbsp;{&nbsp;useRequest&nbsp;}&nbsp;from&nbsp;'umi'; //这个result 就是undefined
import&nbsp;{&nbsp;useRequest&nbsp;}&nbsp;from&nbsp;'@umijs/hooks'; //这个是好的
import&nbsp;{&nbsp;Button,&nbsp;Input,&nbsp;message&nbsp;}&nbsp;from&nbsp;'antd';
import&nbsp;React,&nbsp;{&nbsp;useState&nbsp;}&nbsp;from&nbsp;'react';
function&nbsp;changeUsername(username:&nbsp;string):&nbsp;Promise<string&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;new&nbsp;Promise(resolve&nbsp;=&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setTimeout(()&nbsp;=&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resolve('111111');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},&nbsp;1000);
&nbsp;&nbsp;&nbsp;&nbsp;});
}
export&nbsp;default&nbsp;()&nbsp;=&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;[state,&nbsp;setState]&nbsp;=&nbsp;useState('');
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;{&nbsp;loading,&nbsp;run&nbsp;}&nbsp;=&nbsp;useRequest(changeUsername,&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;manual:&nbsp;true,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;onSuccess:&nbsp;(result,&nbsp;params)&nbsp;=&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;console.log(result,&nbsp;1,&nbsp;params)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;if&nbsp;(result?.success)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setState('');
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;message.success(`The&nbsp;username&nbsp;was&nbsp;changed&nbsp;to&nbsp;"${params[0]}"&nbsp;!`);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;});

&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<Input
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;onChange={e&nbsp;=&gt;&nbsp;setState(e.target.value)}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;value={state}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;placeholder="Please&nbsp;enter&nbsp;username"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;style={{&nbsp;width:&nbsp;240,&nbsp;marginRight:&nbsp;16&nbsp;}}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<Button&nbsp;onClick={()&nbsp;=&gt;&nbsp;run(state)}&nbsp;loading={loading}&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Edit
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</Button&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;);
};
使用umi引入的 useRequest&nbsp;result 一直是undefind  如果使用 @umijs/hooks 就没问题 这是为什么那？ 希望可以得到你的回复 谢谢了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "砖家"<notifications@github.com&gt;; 
发送时间: 2020年11月11日(星期三) 下午2:00
收件人: "alibaba/hooks"<hooks@noreply.github.com&gt;; 
抄送: "zzz"<www.1124965100@qq.COM&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [alibaba/hooks] 为什么我在使用useRequest时拿不到数据? (#714)





 
暂时先这样用下试试 import useCookieState from 'ahooks/lib/useCookieState'

**Comment by hqylss111** [comment]
> 暂时先这样用下试试 `import useCookieState from 'ahooks/lib/useCookieState'`

 还有一个问题 使用 umi 导出的useRequest 获取的 result 一直是undefined 但是使用 @@umijs/hooks 就没有问题 这是为什么那？

**Comment by brickspert** [comment]
> 还有一个问题 使用 umi 导出的useRequest 获取的 result 一直是undefined 但是使用 @@umijs/hooks 就没有问题 这是为什么那？

![image](https://user-images.githubusercontent.com/12526493/98778063-c22fb700-242c-11eb-9db8-759464f6e6c7.png)

**Comment by hqylss111** [comment]
好了谢谢你的回答。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "砖家"<notifications@github.com&gt;; 
发送时间: 2020年11月11日(星期三) 下午2:47
收件人: "alibaba/hooks"<hooks@noreply.github.com&gt;; 
抄送: "zzz"<www.1124965100@qq.COM&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [alibaba/hooks] 为什么我在使用useRequest时拿不到数据? (#714)





  
还有一个问题 使用 umi 导出的useRequest 获取的 result 一直是undefined 但是使用 @@umijs/hooks 就没有问题 这是为什么那？

**Comment by Larva02** [comment]
![image](https://user-images.githubusercontent.com/12692666/99038127-fd162400-25bf-11eb-9f90-8e5e8d68787c.png)


useCookieState 怎么用在这？
