### ISSUE TITLE
[RFC] useClipboard 复制至粘贴板

### ISSUE THREAD

**Issue by turkyden** [alibaba/hooks#715]
## 应用场景: 

React Hook 实现一个**复制至粘贴板**的功能，仅封装必要的 UI 状态逻辑，使组件更加灵活易用。

### useClipboard

```jsx
import { useClipboard } from 'ahooks';

export default () => {
  const { copied, copy, reset } = useClipboard(
    '需要复制到粘贴板的文本'
  )

  return <a onClick={copy}>{ copied === false ? 'Copy' : 'Copied' }</a>
}
```

#### useClipboard(text: string)

| 参数 |  类型     | 必须? | 描述                                                       |
| -------- | -------- | --------- | ----------------------------------------------------------------- |
| text     | `string` | Yes       | 点击时需要复制到粘贴板的文本 |

#### Returns { copied: string, copy:  () => void, reset: () => void }

| 名称 |  类型     | 描述                                                       |
| -------- | -------- | ----------------------------------------------------------------- |
| copied | `boolean` | 当前复制状态，已复制 `true`, 未复制 `false` |
| copy | `() => void` | 点击复制方法 |
| reset | `() => void` | 点击重置方法 |

**Comment by turkyden** [comment]
希望能够为 **ahooks** 作贡献，请问我可以提 PR 么 ？@brickspert

**Comment by brickspert** [comment]
感谢参与贡献，感谢。

不过这个 Hooks 的实用性不强，见 https://github.com/alibaba/hooks/issues/580

**Comment by turkyden** [comment]
噢噢，原来已经有 [RFC] 了，但是我实现的可能有点不一样。

#580 

```tsx
const [readText, writeText] = useClipBoard();
```

#715

```tsx
const { copied, copy, reset } = useClipboard( '需要复制到粘贴板的文本')
```

```tsx
<a onClick={copy}>{ copied === false ? 'Copy' : 'Copied' }</a>
```

理由如下：

1. 灵活，仅封装 `copy` 复制事件与 `reset` 重置事件，维护并返回当前 `copied` 状态
2. 体积小，不会使得 ahooks 变得臃肿
3. 区别于工具函数，无需用户维护状态

> 希望老师能够重新考虑一下？ @brickspert @awmleer

**Comment by awmleer** [comment]
我个人的看法是这样的哈：

从**封装成本**角度考虑的话，其实用户手动实现一个类似的逻辑并不复杂

```jsx
const [copied, setCopied] = useState(false)
function copy(content) {
  doCopy(content)
  setCopied(true)
}
function reset() {
  setCopied(false)
}
```

而从**通用性**的角度考虑的话，RFC 中的实现其实并不是很灵活很通用，比如用户需要复制的内容是动态的：

```jsx
const { copied, copy, reset } = useClipboard( '需要复制到粘贴板的文本')
users.map(user => (
  <button
    onClick={() => {
      copy(user.id) // 然而 RFC 中 copy 是不支持传参的
    }}
  >
    {user.name}
  </button>
))
```

所以整体看下来还是有些鸡肋的。。

**Comment by turkyden** [comment]
好的，感谢回复！

**Comment by turkyden** [comment]
这是我写的一个在线示例：

https://codesandbox.io/s/ahook-useclipboard-7xxjd?file=/src/App.tsx

[![Edit ahook-useClipboard](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ahook-useclipboard-7xxjd?fontsize=14&hidenavigation=1&theme=dark)

实现源码如下：

```tsx
function useClipboard(text: string) {
  const [copied, setCopied] = React.useState(false);
  const reset = React.useRef(() => setCopied(false));

  // 当传入文本改变时重置
  React.useEffect(() => reset.current, [text]);

  const copyToClipboard = (text: string) => {
    // 将内容放入 <span>
    const span = document.createElement("span");
    span.textContent = text;
    // 保留连续空格和新换行
    span.style.whiteSpace = "pre";
    // 页面中插入 <span>
    document.body.appendChild(span);
    // 生成一个表示用户选择的文本范围或光标的当前位置的 Selection 对象
    const selection = window.getSelection();
    if (!selection) return Promise.reject();
    const range = window.document.createRange();
    selection.removeAllRanges();
    range.selectNode(span);
    selection.addRange(range);
    // 复制文本到粘贴板
    try {
      window.document.execCommand("copy");
    } catch (err) {
      return Promise.reject();
    }
    // 清理 Dom 元素与选择对象
    selection.removeAllRanges();
    window.document.body.removeChild(span);
    return Promise.resolve();
  };

  return {
    copied,
    copy: React.useCallback(
      () =>
        copyToClipboard(text)
          .then(() => setCopied(true))
          .catch(() => setCopied((copied) => copied)),
      [text]
    ),
    reset: reset.current
  } as const;
}
```

@awmleer 水平有限，还请指教，**复制的内容动态传参**该如何设计呢 ？

**Comment by turkyden** [comment]
> 而从**通用性**的角度考虑的话，RFC 中的实现其实并不是很灵活很通用，比如用户需要复制的内容是动态的：
> 
> ```js-jsx
> const { copied, copy, reset } = useClipboard( '需要复制到粘贴板的文本')
> users.map(user => (
>   <button
>     onClick={() => {
>       copy(user.id) // 然而 RFC 中 copy 是不支持传参的
>     }}
>   >
>     {user.name}
>   </button>
> ))
> ```
> 
> 所以整体看下来还是有些鸡肋的。。

我暂时想到的解决办法是：

```tsx
import { useClipboard } from 'ahooks';

export default function () {
  const users = [
    { id: 0, name: "foo" },
    { id: 1, name: "bar" }
  ];

  const usersClipboard = Array.from(users, user => {
    return {
      ...user,
      ...useClipboard(user.id)
    };
  });

  return (
      <>
        {usersClipboard.map(user => (
          <button onClick={user.copy}>
            {user.copied === false ? "Copy" : "Copied"}
            ~
            {user.name}
          </button>
        ))}
    </>
  );
}
```

@awmleer @brickspert  不知道这样使用 hook 有没有问题。

示例：https://codesandbox.io/s/ahook-useclipboard-7xxjd?file=/src/ArrayClipboard.tsx

**Comment by awmleer** [comment]
```jsx
  const usersClipboard = Array.from(users, user => {
    return {
      ...user,
      ...useClipboard(user.id)
    };
  });
```

这样是违反 Hooks 的规则的：

> Don’t call Hooks inside loops, conditions, or nested functions.

https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level

**Comment by turkyden** [comment]
感谢指正，那我再改改，使得 ` copy`  支持传参，用于动态渲染。

**Comment by linbudu599** [comment]
[Clipboard API](https://developer.mozilla.org/zh-CN/docs/Web/API/Clipboard) @Turkyden

**Comment by ghost** [comment]
说实话，我觉得这个 支持 reset 很好 ，有些地方需要重复复制，重复提示复制状态， reset很实用
