### ISSUE TITLE
useRequest run 的以后 result 一直是undefined 

### ISSUE THREAD

**Issue by hqylss111** [alibaba/hooks#718]

**Comment by brickspert** [comment]
是不是用了 debounce 或者 throttle？

**Comment by hqylss111** [comment]
没有 
如果使用@umijs/hooks 导出的 useRequest  就没有问题 
如果使用 umi 导出的useRequest 获取的result一直都是undefined 
 不知道为什么希望得到你的回复

**Comment by brickspert** [comment]
参考：https://github.com/alibaba/hooks/issues/714#issuecomment-725236865
