### ISSUE TITLE
【BUG】usePersistFn不能兼容react devtool

### ISSUE THREAD

**Issue by xianjie-li** [alibaba/hooks#728]
## 复现步骤
1. 打开下方链接
<https://wjl37.csb.app/>

2. 点击任意按钮, 计数增加正常
![image](https://user-images.githubusercontent.com/34636376/99124509-49537980-263d-11eb-9b78-ba6798996d8d.png)

3. 打开react devtool, 并选中计数器所在组件, 点击新增按钮计数不再增加

<br>

组件代码如下，也可以点击实例页面右下角开sandbox：
```tsx
export default () => {
  const [count, setCount] = useState(0);

  const persistFn1 = usePersistFn(() => {
    console.log(1);
    setCount((prev) => {
      console.log(2);
      return prev + 1;
    });
  });

  const persistFn2 = usePersistFn(() => {
    console.log(3, count);
    setCount(count + 1);
  });

  return (
    <>
      <button type="button" onClick={persistFn1}>
        Add Count {count}
      </button>
      <button type="button" onClick={persistFn2}>
        Add Count {count}
      </button>
    </>
  );
};
```

<br>

源码进行如下修改可以修复，但是不确定是否会影响现有项目
```
fnRef.current = fn;

// =>
useEffect(() => {
   fnRef.current = fn;
});

// 或 =>
useMemo(() => {
    fnRef.current = fn;
});
```

**Comment by brickspert** [comment]
感谢反馈，这个 bug 可太奇怪了~

**Comment by gaowujie2004** [comment]
@brickspert 你好，请教一下这个问题，背后的原因是什么呢。

**Comment by gaowujie2004** [comment]
从代码上看，fnRef.current = useMemo(() => fn, [fn]);

在组件中这样调用：
useMemoizedFn( () => {  ....... } )

那么 fn 都是新的函数引用。据我所知 useMemo(callback, [...deps]) , 对于 callback 的调用是同步的。
那么 useMemo(() => fn, [fn]);   () => fn;  这个函数每一次重渲染都同步执行，实在是感觉没起多大作用哎，但就是能解决问题，哈哈。

**Comment by brickspert** [comment]
> @brickspert 你好，请教一下这个问题，背后的原因是什么呢。

背后的原因还不清楚

**Comment by joriewong** [comment]
```tsx
useLayoutEffect(() => {
    fnRef.current = fn;
});
```

**Comment by AnathanPham** [comment]
> ```tsx
> useLayoutEffect(() => {
>     fnRef.current = fn;
> });
> ```

讲道理，这个方法也不太行。
我觉得不使用并发模式的前提下，用当前版本的`useMemoizedFn `很香。

`useLayoutEffect`是 RFC给出的例子的实现。

 #### useEvent潜在的问题？
我的评论 https://github.com/reactjs/rfcs/pull/220#issuecomment-1140807623
 子组件 useLayoutEffect 无法获取最新的 方法。
 子组件的 useLayoutEffect 发生在 父组件 之前。如果在子组件的 useLayoutEffect 中执行 useEvent的返回的方法，将会访问旧的值。
想到这里，我觉得既然我们没有使用并发模式，那么用 useMemoizedFn 也没什么毛病甚至更好。

**Comment by youjiaqi421** [comment]
> @brickspert 你好，请教一下这个问题，背后的原因是什么呢。

这个产生了 什么问题吗

**Comment by youjiaqi421** [comment]
> 从代码上看，fnRef.current = useMemo(() => fn, [fn]);
> 
> 在组件中这样调用： useMemoizedFn( () => { ....... } )
> 
> 那么 fn 都是新的函数引用。据我所知 useMemo(callback, [...deps]) , 对于 callback 的调用是同步的。 那么 useMemo(() => fn, [fn]); () => fn; 这个函数每一次重渲染都同步执行，实在是感觉没起多大作用哎，但就是能解决问题，哈哈。

这个产生了什么问题吗？我复现了半天，没搞出来 ， 我现在用的版本是concurrent模式

**Comment by youjiaqi421** [comment]
> 从代码上看，fnRef.current = useMemo(() => fn, [fn]);
> 
> 在组件中这样调用： useMemoizedFn( () => { ....... } )
> 
> 那么 fn 都是新的函数引用。据我所知 useMemo(callback, [...deps]) , 对于 callback 的调用是同步的。 那么 useMemo(() => fn, [fn]); () => fn; 这个函数每一次重渲染都同步执行，实在是感觉没起多大作用哎，但就是能解决问题，哈哈。
我觉得可能是 ref赋值时机搞出来的这个问题

**Comment by kongmoumou** [comment]
@brickspert 
查了下资料，react devtool inspect 组件时会进行 shallow render，并且替换所有 hooks 为 mock hooks（用来获取 hook 信息，参考 [bvaughn 评论](https://github.com/facebook/react/issues/20394#:~:text=Now%20if%20DevTools%20runs%20your%20component%20to%20inspect%20it%2C%20the%20ref_count%20ref%20will%20be%20mutated%20(and%20stay%20mutated)%20to%20close%20over%20the%20stubbed%20out%20useState%20hook%2C%20which%20is%20why%20it%20will%20no%20longer%20do%20anything%20when%20called.)）。这就会导致在选中时，触发 render，并且因为在 render 中修改 ref，导致 `ref.current` 被替换成 devtool mock 的[空函数](https://github.com/facebook/react/blob/80f3d88190c07c2da11b5cac58a44c3b90fbc296/packages/react-debug-tools/src/ReactDebugHooks.js#L134)（无法触发更新）。但是用 useMemo 包一层，[mock useMemo](https://github.com/facebook/react/blob/80f3d88190c07c2da11b5cac58a44c3b90fbc296/packages/react-debug-tools/src/ReactDebugHooks.js#L249) 会始终返回组件正常 render 时的 memorized value，也就不会破坏原有的功能了 🤣

**Comment by dadazhouRenee** [comment]
那为啥 useInterval 中 fn 不需要用useMemo包呢

**Comment by suwu150** [comment]
> 那为啥 useInterval 中 fn 不需要用useMemo包呢

你的会有什么问题吗，在使用时

**Comment by Flcwl** [comment]
理论应该反馈给 react 解决

**Comment by hcjlxl** [comment]
> 理论应该反馈给 react 解决

他们讨论过了，需要按照 hooks的规则走，就是要将这个 ref 的修改放在useEffect 里面 不能直接在render中修改

**Comment by vaynevayne** [comment]
> > 理论应该反馈给 react 解决
> 
> 他们讨论过了，需要按照 hooks的规则走，就是要将这个 ref 的修改放在useEffect 里面 不能直接在render中修改

直接在 effect 里修改也会有问题,比如这个 hook,
我使用 
https://github.com/chakra-ui/chakra-ui/blob/main/packages/hooks/use-callback-ref/src/index.ts#L10
 这个 hook 会造成 setValue 中的 value 不是最新的, 而使用 ahook 的 useMemoizedFn 就可以解决这个问题,

**Comment by hcjlxl** [comment]
> 直接在 effect 里修改也会有问题,比如这个 hook, 我使用 https://github.com/chakra-ui/chakra-ui/blob/main/packages/hooks/use-callback-ref/src/index.ts#L10 这个 hook 会造成 setValue 中的 value 不是最新的, 而使用 ahook 的 useMemoizedFn 就可以解决这个问题,

你使用的chakra-ui里面这个hook写了依赖数组吗，他导出的useCallback 这个hook 支持依赖数组的

**Comment by vaynevayne** [comment]
> 

写了

**Comment by hcjlxl** [comment]
> > 
> 
> 写了

如果去掉会不会是正常的呢

**Comment by vaynevayne** [comment]
charkra-ui 的这个 hook 不能去掉依赖吧

```jsx
 const [config, setConfig] = useControlledImmer<ReportConfig>({
    value,
    onChange,
    defaultValue,
  })


```

```jsx
import { useCallbackRef } from '@chakra-ui/react-use-callback-ref'
import produce, { Draft, freeze } from 'immer'
import { useState } from 'react'





// 这是我自己实现的, 参考 charka-ui 的逻辑
export function useControlledImmer(
  props:
){
  const {
    value: valueProp,
    defaultValue,
    onChange,
    shouldUpdate = (prev, next) => prev !== next,
  } = props

  const onChangeProp = useCallbackRef(onChange)
  const shouldUpdateProp = useCallbackRef(shouldUpdate)

  const [uncontrolledState, setUncontrolledState] = useState(
    freeze(
      typeof defaultValue === 'function' ? defaultValue() : defaultValue,
      true
    )
  )
  const controlled = valueProp !== undefined
  const value = controlled ? valueProp : uncontrolledState

  const setValue = useCallbackRef(
    (updater) => {
      const nextValue =
        typeof updater === 'function'
          ? produce(value, updater)
          : freeze(updater)

      if (!shouldUpdateProp(value, nextValue)) {
        return
      }

      if (!controlled) {
        setUncontrolledState(nextValue)
      }

      onChangeProp(nextValue)
    },
    [controlled, onChangeProp, value, shouldUpdateProp]
  )

  return [value, setValue]
}

```

**Comment by fantasticsoul** [comment]
<img width="1049" alt="image" src="https://github.com/alibaba/hooks/assets/7334950/b242ae4d-f745-4796-b749-1f19f673fd21">

我仔细理解了这句话，在渲染期间直接修改了引用导致的，那么多包一层感觉能解决此问题（替代 useMemo），大体代码如下

```ts
function useMemoizedFn<T extends noop>(fn: T) {
  const fnRef = useRef<T>({fn});
  fnRef.current.fn = fn; // 此处没有对nRef.current 自身做任何改变

  const memoizedFn = useRef<PickFunction<T>>();
  if (!memoizedFn.current) {
    memoizedFn.current = { fn: function (this, ...args) {
      return fnRef.current.fn.apply(this, args);
    }};
  }

  return memoizedFn.current.fn;
}
```

**Comment by fantasticsoul** [comment]
见我的最新答复看看能否解决呢（除了 useMemo方式）

**Comment by awmleer** [comment]
@fantasticsoul 大概看了一眼感觉好像并没有效果诶？你说的多包了一层是指多套了一个 ref 么，`memoizedFn.current.fn` 看起来永远会调用最新的 `fnRef.current.fn`，而问题的关键是 `fnRef.current.fn` 在 devtools 的上下文环境里被修改成了一个错误的闭包环境下的 `fn`（说的有点绕，但是看你截图里贴的那个 issue，应该是这个意思），因此感觉并不能解决问题

不过我并没有实际写出来验证过，有兴趣的话要不简单搞个 CodeSandbox demo 试试？

**Comment by fantasticsoul** [comment]
哈哈试了不行所以我把建议删了，还是得 useMemo，我在[helux](https://github.com/Tencent/hel)里改进了下`useMemorizedFn`，进化为 [useStable](https://github.com/heluxjs/helux/blob/master/packages/helux-core/src/hooks/useStable.ts)了，可以传入多个函数集合、单个函数，或者其他任意值了

![image](https://github.com/alibaba/hooks/assets/7334950/f7d9060c-b333-46ed-a76e-6fe98e30aa8a)


CodeSandbox线上示例见[这里](https://codesandbox.io/s/helux-demo-ts-539scq?file=/src/demos/SignalAsync.tsx)

![image](https://github.com/alibaba/hooks/assets/7334950/0875afad-6cf7-4406-b2a7-0caa642ef47c)

**Comment by fantasticsoul** [comment]
> @fantasticsoul 大概看了一眼感觉好像并没有效果诶？你说的多包了一层是指多套了一个 ref 么，`memoizedFn.current.fn` 看起来永远会调用最新的 `fnRef.current.fn`，而问题的关键是 `fnRef.current.fn` 在 devtools 的上下文环境里被修改成了一个错误的闭包环境下的 `fn`（说的有点绕，但是看你截图里贴的那个 issue，应该是这个意思），因此感觉并不能解决问题
> 
> 不过我并没有实际写出来验证过，有兴趣的话要不简单搞个 CodeSandbox demo 试试？

还是`useMemo`最靠谱

**Comment by GuichiZhao** [comment]
通过 React 的原理盲猜一下吧，首先 React 一直强调 render 必须是**纯函数**，所谓纯函数就是调用一次和调用一万次没有任何区别，那么就从这个角度想一下有没有 useMemo 有没有可能产生影响
我们假设 React 无缘无故就是 render 多次次，那么有没有 useMemo 可能有区别：
如果没有 useMemo，就是以最后一次为准，如果有 useMemo，React 很有可能觉得他已经 memo 了，就不再考虑之后的值，当然如果 render 是用户触发的肯定没问题，如果是 React 的内部机制就没准啥样

而且可以参考官方说法

<img width="1192" alt="Image" src="https://github.com/user-attachments/assets/6b62ac9b-7e03-45ec-b49c-7bac642410d6" />

尤其注意红框的那两个地方

你们现在搞了个 useMemo 给人一种负负得正的感觉 @brickspert @awmleer @fantasticsoul

**Comment by GuichiZhao** [comment]
而且现在 React 官方已经有这个 hook 了
https://react.dev/reference/react/experimental_useEffectEvent

**Comment by Butcher1023** [comment]
2025年10月1号，useEffectEvent在react@19.2.0正式发布

**Comment by jmct123** [comment]
> 2025年10月1号，useEffectEvent在react@19.2.0正式发布

然而它只能在副作用hooks中使用，不能作为其他函数中来调用，还是没有解决这个问题
