### ISSUE TITLE
[疑问]：loadmore滚动到底部时，如何得到整个页面滚动到底部

### ISSUE THREAD

**Issue by fanhualei** [alibaba/hooks#730]
loadmore例子是一个DIV.  我用的是antDesign框架，怎么能得到整个页面的滚动轴滚到底部了。

```jsx
const containerRef = useRef<HTMLDivElement>(null);
<div ref={containerRef} style={{ height: 200, overflowY: 'auto' }}>

</div>
```

**Comment by brickspert** [comment]
和 antd 框架没关系，你需要具体描述下你的具体。

**Comment by fanhualei** [comment]
例子上 ref是加在一个div中的滚动轴上。 `<div ref={containerRef} style={{ height: 200, overflowY: 'auto' }}>` 

我想怎么能捕获整个Html页面的滚动轴，当整个html页面滚动轴发生变化时，就触发刷新事件。

**Comment by brickspert** [comment]
捕获整个 html 的貌似现在还不支持。后面支持下~
