### ISSUE TITLE
[需求]useAntdTable的search能否提供reload这样的方法？

### ISSUE THREAD

**Issue by wood3n** [alibaba/hooks#735]
例如需求场景是删除或者改变表格当前页的某行数据以后，需要刷新当前页表格数据，这时候就要带上`form`和`pagination`的参数来刷新，请问能否在`useAntdTable`返回的`search`方法中加上`reload`的方法呢？

**Comment by cixiangtao** [comment]
23年，同需要这个功能

**Comment by liuyib** [comment]
refresh 方法有的：https://github.com/alibaba/hooks/issues/1540

文档里有提到哦：

<img width="962" alt="image" src="https://github.com/alibaba/hooks/assets/38221479/72f20945-74d5-44d7-b375-d031baf42fb2">
