### ISSUE TITLE
useRequest能否支持动态配置options

### ISSUE THREAD

**Issue by XdyGoGo** [alibaba/hooks#736]
现在有这样一个需要，在使用轮询功能的时候，希望能根据后端返回的轮询时间动态的修改轮询时间

**Comment by XdyGoGo** [comment]
目前的想到的解决方案 - 响应的时间和上一次不一致就重新reload下页面

**Comment by brickspert** [comment]
目前还不支持动态配置 options，后面会考虑支持。
