### ISSUE TITLE
[Bug] useRequest请求数据后未更新视图.

### ISSUE THREAD

**Issue by KumaCool** [alibaba/hooks#750]
我在与antd的Tree组件一起使用时(其它组件未试).
在子组件内部调用`refresh`后数据有更新,但视图未重新渲染.调用第二次才会重新渲染视图.
使用普通的异步函数与hooks没有问题.
不知道是什么原因,目前我只能采用setTimeout的方式临时解决.

以下是问题demo
[https://codesandbox.io/s/userequesttree-test-ivz0x?file=/src/App.tsx](https://codesandbox.io/s/userequesttree-test-ivz0x?file=/src/App.tsx)

**Comment by brickspert** [comment]
没有看到 demo 里面有 useRequest 呀

**Comment by KumaCool** [comment]
抱歉,不太会用在线IDE...以更新链接.

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/100533291-bd953c00-323d-11eb-8fc2-42350be8090c.png)


你这里使用 treeData 很奇怪，你先打印看看这个 treeData 是不是符合预期。

**Comment by KumaCool** [comment]
是符合预期的,这个不是重点,它主要是在demo里模拟数据变动.避免干扰我已经把demo代码换了其它方式.
按道理来讲，请求结束，数据已经变更应该算是useRequest结束了，问题点应该是tree的事，但我换普通hooks及promise却是正常的。所以也定位不出到底是哪出了问题。

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/100560043-81221880-32ef-11eb-966f-32c268214375.png)

测试一切符合预期，还是不知道你是啥问题。。

**Comment by KumaCool** [comment]
![demo](https://user-images.githubusercontent.com/22438580/100838658-cf7d1600-34ad-11eb-895f-86573031b2aa.gif)
点击`修改`时数据已经清空了,但视图还是显示着数据,点击`更新`视图是最新状态.

**Comment by brickspert** [comment]
感觉很奇怪，明明 treeData 已经更新了，但是 tree 就是没更新。

**Comment by weipengzou** [comment]
我用useRequest的时候也是，例如登录功能。第一次请求返回的data是undefinded，第二次才有用户数据，不懂是什么问题...

**Comment by iNeedToCopy** [comment]
@brickspert useRequest偶尔返回的data为undefinded，一般出现在第二天第一次登陆系统的时候，登陆功能出现这个问题，排除了后端数据问题，已经定位到了onSuccess回调中的第一个参数为undefinded，无法100%复现，很蛋疼。。。。。

**Comment by brickspert** [comment]
> @brickspert useRequest偶尔返回的data为undefinded，一般出现在第二天第一次登陆系统的时候，登陆功能出现这个问题，排除了后端数据问题，已经定位到了onSuccess回调中的第一个参数为undefinded，无法100%复现，很蛋疼。。。。。

如果能提供个代码示例，能复现的话，会好解决点。。

**Comment by iNeedToCopy** [comment]
> > @brickspert useRequest偶尔返回的data为undefinded，一般出现在第二天第一次登陆系统的时候，登陆功能出现这个问题，排除了后端数据问题，已经定位到了onSuccess回调中的第一个参数为undefinded，无法100%复现，很蛋疼。。。。。
> 
> 如果能提供个代码示例，能复现的话，会好解决点。。

现在我发现一个问题：
![image](https://user-images.githubusercontent.com/29393634/117535147-0cce6c80-b027-11eb-9c66-d3a61da6c020.png)

这里的`getResponse: true`删除的话，需要另外包装一下`formatResult: (x) => x`才能拿到数据，
![image](https://user-images.githubusercontent.com/29393634/117535202-4010fb80-b027-11eb-9c6a-9b8efe5fb124.png)
能确定就是`getResponse: true`配置的问题吗？这里的配置为什么会影响到formatResult的配置呢？费解。。。。

**Comment by iNeedToCopy** [comment]
@brickspert 
我把getResponse和formatResult的配置都改了，但是第一次请求还是会返回undefined，这是什么情况啊。。。。后面的null忽视，第一次的这个undefined实在是不知道是因为什么原因导致的。。。。。

![image](https://user-images.githubusercontent.com/29393634/117536006-5b7e0580-b02b-11eb-9c9f-dc025c19007f.png)

![image](https://user-images.githubusercontent.com/29393634/117535989-4b662600-b02b-11eb-969b-05a156584125.png)

**Comment by brickspert** [comment]
> @brickspert
> 我把getResponse和formatResult的配置都改了，但是第一次请求还是会返回undefined，这是什么情况啊。。。。后面的null忽视，第一次的这个undefined实在是不知道是因为什么原因导致的。。。。。
> 
> ![image](https://user-images.githubusercontent.com/29393634/117536006-5b7e0580-b02b-11eb-9c9f-dc025c19007f.png)
> 
> ![image](https://user-images.githubusercontent.com/29393634/117535989-4b662600-b02b-11eb-969b-05a156584125.png)

你这个不是网络请求返回了 null 吗？和前端没啥关系呀。- -

**Comment by iNeedToCopy** [comment]
但是你看打印第一次请求返回的值，应该是null，但是却是undefined，这里有问题------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月8日(星期六) 晚上7:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/hooks] [Bug] useRequest请求数据后未更新视图. (#750)

**Comment by iNeedToCopy** [comment]
> 我用useRequest的时候也是，例如登录功能。第一次请求返回的data是undefinded，第二次才有用户数据，不懂是什么问题...

@weipengzou 兄弟，你找到原因了吗，我和你一样的问题，一直没办法解决，方便留个联系方式交流一下吗？

**Comment by brickspert** [comment]
> > 我用useRequest的时候也是，例如登录功能。第一次请求返回的data是undefinded，第二次才有用户数据，不懂是什么问题...
> 
> @weipengzou 兄弟，你找到原因了吗，我和你一样的问题，一直没办法解决，方便留个联系方式交流一下吗？

如果能提供一个复现代码就好了。 - -~~

**Comment by iNeedToCopy** [comment]
> > > 我用useRequest的时候也是，例如登录功能。第一次请求返回的data是undefinded，第二次才有用户数据，不懂是什么问题...
> > 
> > 
> > @weipengzou 兄弟，你找到原因了吗，我和你一样的问题，一直没办法解决，方便留个联系方式交流一下吗？
> 
> 如果能提供一个复现代码就好了。 - -~~

暂时确定是因为没有配置skipErrorHandler的原因，讲道理success为true的时候不应该拦截，只拦截success为false的情况，加上skipErrorHandler:true后，目前流程正确，但是不确定是不是这个原因，玄学

**Comment by iNeedToCopy** [comment]
@brickspert 破案了，是因为timeout设置时间太短了，到了timeout接口还没返回直接就返回undefined了，接口没有被cancel，在errorHandle里面增加了type=="Timeout"的提示，目前来看应该是这个原因。。。。。

**Comment by kopa-kongpan** [comment]
24年了, 还出现了这个问题, 具体怎么解决啊
