### ISSUE TITLE
Lazily connect with useWebSocket

### ISSUE THREAD

**Issue by acro5piano** [alibaba/hooks#751]
Hi, thank you for the great library.

Currently, `useWebSocket` connects immediately by invoking the hook. I have some use cases to connect manually, such as connecting to host triggers something in server side.

So my suggestion is to add `lazy` option to `useWebSocket`. The code would look like this:

```ts
// At this time, it does not start websocket
const { connect } = useWebSocket('wss://echo.websocket.org', {
  lazy: true,
})

return <button onClick={connect}>start web socket connection</button>
```

I took a look at the code and it can be implemented easily IMO. Can I submit a PR for this?

https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useWebSocket/index.ts#L128-L131

Thanks!!

**Comment by brickspert** [comment]
Sure, welcome to sumit a PR.

But `lazy` should be named to `manual`, be consistent with useRequest.

Thank you very much.
