### ISSUE TITLE
[建议]Uncaught (in promise) useRequest has caught the exception转成warning

### ISSUE THREAD

**Issue by zjy01** [alibaba/hooks#757]
```js
Uncaught (in promise) useRequest has caught the exception, if you need to handle the exception yourself, you can set options.throwOnError to true.
```
能不能把这一句提示转成`warning`。
作为报错是会触发一些其他上报的

**Comment by TotooriaHyperion** [comment]
1. 如果 useRequest 返回参数里支持了 error 那么就不应该 re-throw 因为【返回error】本身就是【handle exception】的行为。

2. 要么就压根不返回 error 用户自行 catch 。

3. 如果关闭 error 然后用户自行 catch 之后依然 re-throw 那么这种情况被上报也是正常的。

4. 如果用户自行 catch 之后上报，再 re-throw 并且返回 error 这种情形意味着开发者要自行上报，同时也要在页面反馈用户。

这4种情形都是符合常识的，而目前的实现不符合常识。

应该增加一个 rethrow: boolean 参数，默认为 false 被改为 true 时才再 throw

**Comment by Airkro** [comment]
有一个没解决就被关闭的类似问题：https://github.com/alibaba/hooks/issues/585 ，我整理了一下

主要矛盾点是 `throwOnError/onError/run.catch()` 的职责矛盾，目前：

- `onError` 只是单纯的钩子，无法将错误消化掉。
- `throwOnError` 无论是 `true/false` 都会抛出 `Uncaught (in promise)` 
- `throwOnError:false` 抛出的是内置提示
- `throwOnError:true` 抛出的是原始错误，可以用 `run.catch()` 处理。

也就是说用户要是不想触发 `Uncaught (in promise)` ，就必须使用以下代码：

```js
const { run } = useRequest(fetch, { manual: true, throwOnError: true });

run.catch(handle); // 如果使用 pollingInterval 的话，这招也会失效
```

这显然是得不偿失，有必要优化一下。

**Comment by Uyarn** [comment]
一堆错误上报都是因为它 简直了

**Comment by brickspert** [comment]
这个肯定是要改的，正如大家所说，确实存在问题。但现在怎么改都是 break change，所以我是打算在 3.0 中重新设计。

**Comment by mzvast** [comment]
I think just return at this line would work better. No one would like to catch these errors.
```
diff --git a/node_modules/@ahooksjs/use-request/es/useAsync.js b/node_modules/@ahooksjs/use-request/es/useAsync.js
index 9783cb8..fa15271 100644
--- a/node_modules/@ahooksjs/use-request/es/useAsync.js
+++ b/node_modules/@ahooksjs/use-request/es/useAsync.js
@@ -199,7 +199,7 @@ function () {
       }
 
       console.error(error); // eslint-disable-next-line prefer-promise-reject-errors
-
+      return;
       return Promise.reject('useRequest has caught the exception, if you need to handle the exception yourself, you can set options.throwOnError to true.');
     })["finally"](function () {
       if (currentCount === _this.count) {
diff --git a/node_modules/@ahooksjs/use-request/lib/useAsync.js b/node_modules/@ahooksjs/use-request/lib/useAsync.js
index 43ba293..91411e3 100644
--- a/node_modules/@ahooksjs/use-request/lib/useAsync.js
+++ b/node_modules/@ahooksjs/use-request/lib/useAsync.js
@@ -221,7 +221,7 @@ function () {
       }
 
       console.error(error); // eslint-disable-next-line prefer-promise-reject-errors
-
+      return;
       return Promise.reject('useRequest has caught the exception, if you need to handle the exception yourself, you can set options.throwOnError to true.');
     })["finally"](function () {
       if (currentCount === _this.count) {
```

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
