### ISSUE TITLE
[RFC] useExternal 加载外部资源

### ISSUE THREAD

**Issue by turkyden** [alibaba/hooks#758]
# useExternal

React Hook 实现一个**加载外部资源**的功能，返回加载状态，并提供外部资源动态（注入/移除） Action 方法。[Preview &rarr;](https://codesandbox.io/s/useexternal-q09v1?fontsize=14&hidenavigation=1&theme=dark)

![READMsssE5](https://user-images.githubusercontent.com/24560160/100818753-bf514080-3485-11eb-927e-29e789448fc9.gif)

### 1. Load external javascript

```tsx
import { useExternal } from "ahooks";

const Example = () => {
  const [ status, { toggle } ] = useExternal("foo.js", { async: true });
  return (
    <>
      <p>Response: {status}</p>
      <button type="button" onClick={() => toggle()}>
        { status === 'ready' ? 'remove' : 'load' }
      </button>
    </>
  );
};
```

```html
<body>
  <!-- load external javascript -->
  <script src="foo.js" async data-status="ready"></script>
</body>
```

### 2. Load external css

```tsx
const [ status, { toggle, load, unload } ] = useExternal("baz.css", { media: "all" });
// ...
```

```html
<head>
  <!-- load external css -->
  <link rel="stylesheet" href="baz.css" media="all" data-status="ready" />
</head>
```

### 3. Load external image

```tsx
const ref = useRef();
const [ status, { load, unload, toggle } ] = useExternal("icon.png", { target: ref });
// ...
<div id="wrapper" ref={ref }></div>
```

```html
<body>
  <div id="wrapper">
    <!-- load external image -->
    <img src="icon.png" data-status="ready" />
  </div>
</body>
```

#### useExternal(path: string, options?: Options)

| 参数 |  类型     | 必须? | 描述                                                       |
| -------- | -------- | --------- | ----------------------------------------------------------------- |
| path     | `string` | Yes       | 需要动态引入页面的外部资源地址 |
| options.async     | `boolean` | No       | 引入外链脚本的 `<script>` 的 async 属性 |
| options.media | `string` | No      | 引入外链样式表 `<link>` 的 media 属性  |
| options.target | `Ref` or  `DOM` | No      | 需引入外部图片 `<img>` 的父容器  |

#### Returns [ status, actions ]

| 名称 |  类型     | 描述                                                       |
| -------- | -------- | ----------------------------------------------------------------- |
| status | `string` | 外部资源加载状态，未设置 `unset`, 加载中 `loading`, 加载成功 `ready` , 加载失败 `error` |
| actions.load| `() => void` | 向页面（注入）外部资源的方法 |
| actions.unload| `() => void` | 向页面（移除）外部资源的方法 |
| actions.toggle | `() => void` | 向页面（注入/移除）外部资源的方法 |

## Demo

[![Edit useExternal](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/useexternal-q09v1?fontsize=14&hidenavigation=1&theme=dark)

**Comment by turkyden** [comment]
我可以提个 PR 么？@brickspert

**Comment by brickspert** [comment]
> 我可以提个 PR 么？@brickspert

可以的，谢谢。非常欢迎提 PR。
