### ISSUE TITLE
[建议] debounceInterval 的 loading 时机调整

### ISSUE THREAD

**Issue by JJVvV** [alibaba/hooks#759]
你好。

背景：
当添加 `debounceInterval` 参数时，`loading` 至少要等 `debounceInterval` 时间过后才会被设置未 `true`。以 ahooks 官方的例子为例 [https://codesandbox.io/s/qcxk8](https://codesandbox.io/s/qcxk8)，当用户快速连续不断的输入文字时，loading 将总是为 `false`，只有再最后停止输入时才变为 `true`，然后立马消失。所以在整个输入过程中，`loading` 仅仅出现了一瞬间，几乎没什么用，效果不够自然。

希望达到的效果：
在用户输入的时候就把 `loading` 设置为 `true`，而不是等待至少 `debounceInterval` 过后。

以下为希望达到的效果图：
![async](https://user-images.githubusercontent.com/5662407/100821655-caa76a80-348b-11eb-9f9b-7a6fb7be8d23.gif)

**Comment by brickspert** [comment]
这个我们考虑下，是否加这个特性。
