### ISSUE TITLE
useScroll中document.scrollingElement存在兼容性问题

### ISSUE THREAD

**Issue by MarphyDemon** [alibaba/hooks#767]
document.scrollingElement为undefined，使用document.body.scrollTop、document.body.scrollLeft获取

**Comment by brickspert** [comment]
啥环境可以复现呢？

**Comment by MarphyDemon** [comment]
android4下

**Comment by MarphyDemon** [comment]
MDN：当在怪异模式下， scrollingElement 属性返回 HTML body 元素（若不存在返回 null ）。这里也有提到，scrollingElement存在兼容问题参考：https://www.jianshu.com/p/fea15ca77a10

**Comment by susiwen8** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
