### ISSUE TITLE
[RFC]: useFixPage

### ISSUE THREAD

**Issue by susiwen8** [alibaba/hooks#774]
在项目中经常有弹层出现时，禁止页面滚动, 弹层消失页面又恢复滚动。建议增加一个 hook 实现这个功能。

如果觉得有这个必要。我可以贡献一个 PR.

In case of popup, page should not scroll when popup shows up and able to scroll after popup disappear. So I recommend to add `useFixPage` hook.

If you guys think this is necessary, I'm happy to submit a PR.

## Usage
```ts
const App: React.FC = () => {
  const [fixPage, setFixPage] = useFixPage();
  return (
    <div style={{ height: '200vh', width: '100vw' }}>
      <button
        onClick={() => {
          setFixPage(!fixPage);
        }}
      >
        {fixPage ? 'restore scroll' : 'disable scroll'}
      </button>
    </div>
  );
};
```

**Comment by susiwen8** [comment]
@brickspert @awmleer 这个 hook有必要加吗？

**Comment by brickspert** [comment]
感谢提案，不过经过我们讨论，这个 Hooks 目前看使用量比较少，暂时先不用加，再次感谢。
