### ISSUE TITLE
useRequest能否支持设置 Header 属性, 如用于设置授权信息Authorization

### ISSUE THREAD

**Issue by zelejs** [alibaba/hooks#776]

**Comment by brickspert** [comment]
这个应该是你用的 请求库设置的，比如 axios 等

**Comment by 81777268** [comment]
@zelejs  中间件或者拦截器里设置

**Comment by kunKun-tx** [comment]
https://github.com/umijs/umi-request/blob/6773ef1104d46417b14562072167edc0f54822d7/README.md#creating-an-instance
