### ISSUE TITLE
[RFC] Add useMeta

### ISSUE THREAD

**Issue by MisaGu** [alibaba/hooks#781]
Generate meta tag on a page.

```ts
import { useEffect } from 'react';
import useUnmount from '../useUnmount';

export interface Options {
  /* Specifies a name for the metadata */
  name?: 'application-name' | 'author' | 'description' | 'generator' | 'keywords' | 'viewport';
  /* Specifies the character encoding for the HTML document */
  charset?: string;
  /* Provides an HTTP header for the information/value of the content attribute */
  httpEquiv?: 'content-security-policy' | 'content-type' | 'default-style' | 'refresh';
  /* Turn your web pages into graph objects */
  ogTag?: 'title' | 'url' | 'image' | 'type' | 'description' | 'locale';
  content: string;
}

function useMeta(options: Options | Options[]) {
  const metas: HTMLMetaElement[] = [];

  // Try find meta of a provided type
  function getMeta(metaType: string) {
    const metas = document.getElementsByTagName("meta");

    for (let i = 0; i < metas.length; i++) {
      if (
        metas[i].getAttribute("name") === metaType ||
        metas[i].getAttribute("property") === "og:" + metaType
      ) {
        return metas[i];
      }
    }

    return null;
  }

  useEffect(() => {
    options = [].concat.apply([], [options as []]);

    options.forEach((opt) => {
      const existingMeta = opt.name
        ? getMeta(opt.name)
        : opt.ogTag
        ? getMeta("og:" + opt.ogTag)
        : null;
      const meta = existingMeta || document.createElement("meta");

      if (!existingMeta) {
        if (opt.name) meta.setAttribute("name", opt.name);
        if (opt.ogTag) meta.setAttribute("property", "og:" + opt.ogTag);
      }
      meta.content = opt.content;

      document.getElementsByTagName("head")[0].appendChild(meta);
      metas.push(meta);
    });
  }, [options]);

  useUnmount(() => {
    metas.forEach((linkNode) => linkNode?.parentNode?.removeChild(linkNode));
  });
}

export default typeof document !== 'undefined' ? useMeta : () => {};
```

Usage Examples: 
```ts
useMeta({name: 'Author', content; 'MisaGu'});
useMeta([
  {name: 'author', content; 'MisaGu'},
  {name: 'description', content; 'JS Dev'}
])
```

**Comment by awmleer** [comment]
Thanks for contributing. However, what's main advantages of `useMeta` comparing to [react-helmet](https://github.com/nfl/react-helmet)?

**Comment by MisaGu** [comment]
@awmleer, simplier, intended only for `<meta>`, complements **useTitle**, folllow ahooks vision/ideas 😊.

**Comment by youngyou** [comment]
> Generate meta tag on a page.
> 
> ```ts
> import { useEffect } from 'react';
> import useUnmount from '../useUnmount';
> 
> export interface Options {
>   /* Specifies a name for the metadata */
>   name?: 'application-name' | 'author' | 'description' | 'generator' | 'keywords' | 'viewport';
>   /* Specifies the character encoding for the HTML document */
>   charset?: string;
>   /* Provides an HTTP header for the information/value of the content attribute */
>   httpEquiv?: 'content-security-policy' | 'content-type' | 'default-style' | 'refresh';
>   /* Turn your web pages into graph objects */
>   ogTag?: 'title' | 'url' | 'image' | 'type' | 'description' | 'locale';
>   content: string;
> }
> 
> function useMeta(options: Options | Options[]) {
>   const metas: HTMLMetaElement[] = [];
> 
>   // Try find meta of a provided type
>   function getMeta(metaType: string) {
>     const metas = document.getElementsByTagName("meta");
> 
>     for (let i = 0; i < metas.length; i++) {
>       if (
>         metas[i].getAttribute("name") === metaType ||
>         metas[i].getAttribute("property") === "og:" + metaType
>       ) {
>         return metas[i];
>       }
>     }
> 
>     return null;
>   }
> 
>   useEffect(() => {
>     options = [].concat.apply([], [options as []]);
> 
>     options.forEach((opt) => {
>       const existingMeta = opt.name
>         ? getMeta(opt.name)
>         : opt.ogTag
>         ? getMeta("og:" + opt.ogTag)
>         : null;
>       const meta = existingMeta || document.createElement("meta");
> 
>       if (!existingMeta) {
>         if (opt.name) meta.setAttribute("name", opt.name);
>         if (opt.ogTag) meta.setAttribute("property", "og:" + opt.ogTag);
>       }
>       meta.content = opt.content;
> 
>       document.getElementsByTagName("head")[0].appendChild(meta);
>       metas.push(meta);
>     });
>   }, [options]);
> 
>   useUnmount(() => {
>     metas.forEach((linkNode) => linkNode?.parentNode?.removeChild(linkNode));
>   });
> }
> 
> export default typeof document !== 'undefined' ? useMeta : () => {};
> ```
> 
> Usage Examples:
> 
> ```ts
> useMeta({name: 'Author', content; 'MisaGu'});
> useMeta([
>   {name: 'author', content; 'MisaGu'},
>   {name: 'description', content; 'JS Dev'}
> ])
> ```

metas should be Ref, I think.
