### ISSUE TITLE
useRequest 的成功回调onSuccess 包含参数为什么只有data数据？

### ISSUE THREAD

**Issue by 81777268** [alibaba/hooks#787]
```js
code: 40012
data: "xxxxxxxx"
msg: "角色已存在"
```

现在onSuccess回调里面的两个参数 `result` 和`params` 其中`result`  只返回了我们 `api` 中的 `data` 部分，为什么这么设计，我想使用code怎么办？

**Comment by 81777268** [comment]
找到了 `formatResult` 方法 建议默认 `formatResult: (res) => res`

**Comment by brickspert** [comment]
你是从 umi 里面导出的 useRequest 吧？umi 那边封装了一下。。。

**Comment by 81777268** [comment]
> 你是从 umi 里面导出的 useRequest 吧？umi 那边封装了一下。。。

辛苦了你们

**Comment by ningliaoyuan** [comment]
umi这个封装太恶心了，包个了data层...
