### ISSUE TITLE
useRequest 这个hook 在第一次run()的时候返回undefinded，第二次run()才有返回的数据。为什么呢？

### ISSUE THREAD

**Issue by weipengzou** [alibaba/hooks#789]
``
let { run, data, loading } = useRequest(
    (val) => ({
      url: '/api/user/login',
      method: 'post',
      data: { ...val },
    }),
    { manual: true },
  );
await run(values);
    console.log(data);
``
实际上第一次run（）我mockjs就已经返回了数据了。

**Comment by weipengzou** [comment]
> `let { run, data, loading } = useRequest( (val) => ({ url: '/api/user/login', method: 'post', data: { ...val }, }), { manual: true }, );`
> 'await run(values); '
> 'console.log(data);'
> 实际上第一次run（）我mockjs就已经返回了数据了。

**Comment by brickspert** [comment]
await run(values); console.log(data);

这个用法不对

```
const res = await run(values);
console.log(res);
```

**Comment by tanwei0425** [comment]
> await run(values); console.log(data);
> 
> 这个用法不对
> 
> ```
> const res = await run(values);
> console.log(res);
> ```
 请问我想让run执行完成后在本函数中获取 res的值 怎么解？

**Comment by brickspert** [comment]
没理解你的意思~~，我写的那个用法，就能获取到 res~
