### ISSUE TITLE
useRequest 设置 debounceInterval 参数，首次请求也被延迟了

### ISSUE THREAD

**Issue by yejiajiehz** [alibaba/hooks#795]
场景描述：
1. table 默认展示所有数据
2. 有一个搜索的输入框，输入之后，重新查询

问题：
配置 debounceInterval 之后，首次请求也被延迟了  
同样的，手工执行 run 的时候，请求也被延迟了  

期望：
如果没有配置 manual，希望首次请求不要被延迟   
同样的，列表在增删改之后，也期望立刻能够更新

在实际场景中，debounce 一般都是处理频繁的输入，是否考虑能够提供新的参数，比如在 `refreshDeps` 中添加变化频率？  
或者能否提供一个新的，能够立刻执行的 run 函数？

环境版本
- @ahooksjs/use-request 2.8.1
- umi-request 1.3.5
- umi 3.2.28

示意代码
```typescript
const [searchValue, setSearchStr] = useState('');

// 首次请求被延迟了
const { run: getList, tableProps } = useRequest(() => service.getList({ name: searchValue }),
  {
    // 查询条件变动，自动搜索
    refreshDeps: [searchValue],
    debounceInterval: 5000,
  },
);

const { run: deleteItem } = useRequest(service,delete, { 
    manual: true,
    //  刷新也被延迟了
    onSuccess: () => getList(),
})

// tsx
<Input.Search value={searchValue} onChange={e => setSearchStr(e.target.value) />
<Table {...tableProps} columns={columns} />
```

目前的解决方案时去掉了  refreshDeps、debounceInterval 参数，使用 lodash 实现了 debounce

**Comment by liqi1111** [comment]
+10086,  希望可以把leading和trailing暴露出来呀

**Comment by brickspert** [comment]
一个比较好的解决办法就是目前的 `refresh` 函数，不走 `debounce`， 能满足这个场景的诉求。 下个版本支持。

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
