### ISSUE TITLE
扩展功能支持设置缓存时间

### ISSUE THREAD

**Issue by Farewing** [alibaba/hooks#8]
在 swr中 支持 设置 dedupingInterval (dedupe requests with the same key in this time span), 在时效内不重复发送请求。
期望 useRequest 能扩展该功能

**Comment by Straw94** [comment]
由于仓库升级，Issue地址迁移： https://github.com/umijs/hooks/issues/429

**Comment by Straw94** [comment]
由于仓库升级，Issue地址迁移： https://github.com/umijs/hooks/issues/429
