### ISSUE TITLE
全局化配置只能是UseRequestProvider 包裹子组件的形式吗

### ISSUE THREAD

**Issue by KellenHe** [alibaba/hooks#803]
能否配置完返回一个新对象，使用新对象发起请求
现在有很多组件，是平级的，并没有一个统一的父级。
使用UseRequestProvider不是很方便。

**Comment by KellenHe** [comment]
或者如何像umi那样内置 formatResult: res => res?.data

**Comment by ifibercc** [comment]
在 model 中并没有包裹组件, 也无法被设置

**Comment by brickspert** [comment]
> 或者如何像umi那样内置 formatResult: res => res?.data

内置肯定不行的，还有一个办法就是基于 useRequest，自己封装一个 Hooks，传递自己的需要的配置就行了。
