### ISSUE TITLE
useAntdTable中的formData读取不到Checkbox.Group的值

### ISSUE THREAD

**Issue by PeiTianHuang** [alibaba/hooks#806]
当前版本：
"ahooks": "^2.9.2",
"antd": "^4.9.4",

`
const [form] = Form.useForm();
const { tableProps, search, refresh } = useAntdTable(getTableData, {form});

function getTableData({ current, pageSize }: PaginatedParams[0], formData): Promise<Result> {
 // formData中读取不到Checkbox.Group的值，form.getFieldsValue()则可以读取到
}
`
![image](https://user-images.githubusercontent.com/17986764/103125659-bf301380-46c6-11eb-8439-4cc4454a2b66.png)
![image](https://user-images.githubusercontent.com/17986764/103125556-6f514c80-46c6-11eb-9c84-395395351009.png)
![image](https://user-images.githubusercontent.com/17986764/103125583-84c67680-46c6-11eb-8f59-4933e620a2a4.png)

把Checkbox.Group改成select多选组件则可以正常读取到

**Comment by DAOLIDEWONIU** [comment]
+1

**Comment by Caoqingda** [comment]
@brickspert 我也遇到这个问题了，请问有解决方法了吗

**Comment by Caoqingda** [comment]
我暂时先这么解决的
`const AsyncCheckbox = forwardRef(({ selectParams, value, onChange, ...props }, ref) => {
  return (
    <div ref={ref}>
      <Checkbox.Group
        value={value}     
        onChange={onChange}
        options={options}
        {...props}
      />
    </div>
  )
});`

**Comment by PeiTianHuang** [comment]
> 我暂时先这么解决的
> `const AsyncCheckbox = forwardRef(({ selectParams, value, onChange, ...props }, ref) => { return ( <div ref={ref}> <Checkbox.Group value={value} onChange={onChange} options={options} {...props} /> </div> ) });`

我是直接先用form.getFieldsValue()代替那个formData参数

**Comment by turkyden** [comment]
forwardRef 组件代理转发
