### ISSUE TITLE
How to do `useRequest` cache (without SWR)?

### ISSUE THREAD

**Issue by KrishnaPG** [alibaba/hooks#814]
I have a read-only data that need to be queried once and does not change. The cache of useRequest is the best choice to avoid multiple calls.

Is there a way to use just the cache, without doing SWR? That is, all further duplicate requests should fetch the local cache without actually making the server round trip. How to achieve this? Is there any setting that allows only cache and not SWR round trip?

**Comment by KrishnaPG** [comment]
Looks like setting `staleTime: -1` will avoid duplicate requests for a cached entry? Is that correct?

**Comment by brickspert** [comment]
> Looks like setting `staleTime: -1` will avoid duplicate requests for a cached entry? Is that correct?

yeah, staleTime is ok~
