### ISSUE TITLE
useRequest paginated: true 的时候，ready和refreshDeps同时使用触发两个请求

### ISSUE THREAD

**Issue by Mamba-working** [alibaba/hooks#816]
当refreshDeps和ready包含了同一个变量a, a发生变化后，会触发两次请求

可以看看例子: https://codesandbox.io/s/festive-kowalevski-541hv?file=/src/App.tsx

**Comment by shaodushu** [comment]
+1

**Comment by weird94** [comment]
+1

**Comment by binvb** [comment]
@brickspert 麻烦问下v3是哪个分支或者版本？正在用这个库，看下能不能帮忙处理一些bug

**Comment by brickspert** [comment]
> @brickspert 麻烦问下v3是哪个分支或者版本？正在用这个库，看下能不能帮忙处理一些bug

next 分支

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
