### ISSUE TITLE
useExternal无法加载高德地图js

### ISSUE THREAD

**Issue by ouzhou** [alibaba/hooks#819]
看了一下代码 用了正则判断URL后缀
但是比如高德他就不是返回的js文件URL，建议加个参数去判断是什么文件类型

```
https://webapi.amap.com/maps?v=2.0&key=xx
```
加载这样的脚本 傻掉了

**Comment by ouzhou** [comment]
https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useExternal/index.ts#L56

**Comment by awmleer** [comment]
`options` 增加一个 `type` 参数的话，应该可以解决这个问题……

**Comment by brickspert** [comment]
@Turkyden 确实，对一些不能识别的资源，支持传入 type

**Comment by turkyden** [comment]
OK，我来看下。

**Comment by turkyden** [comment]
> `options` 增加一个 `type` 参数的话，应该可以解决这个问题……

https://github.com/alibaba/hooks/pull/828
