### ISSUE TITLE
useExternal: cleanly remove all the script functions / variables

### ISSUE THREAD

**Issue by KrishnaPG** [alibaba/hooks#823]
`useExternal` work nicely in removing the script DOM node on unload. However, the code of the script is not removed from the memory and hence when loading again after a reload causes error as below:
![image](https://user-images.githubusercontent.com/4610831/103975303-cca2ce80-5199-11eb-9f87-5de8d278d506.png)

Steps to reproduce:

- Open the reproducible app https://yyk9t.csb.app/
- Open the console
- Click on 'load' and wait for 'ready'
- Click on 'unload'
- Then click on 'load' again
You will see in the console an error:
````
Uncaught SyntaxError: Identifier 'TEST_SCRIPT' has already been declared
````

The `useExternal` hook removes the script DOM node, but not the code or variables associated with it.

Removing all the functions and variables created by the script could be a difficult task, since we may not know what all variables and functions get loaded by the script. But if there is anyway all of these variables and functions are somehow associated with the DOM node so that when the DOM node gets deleted all the functions/variables also get deleted it would be great.

**Comment by brickspert** [comment]
@Turkyden

**Comment by turkyden** [comment]
OK, i wil check it.

**Comment by turkyden** [comment]
Thank you @KrishnaPG

In order to remove all the functions and variables created by the script, maybe we could set `TEST_SCRIPT = undefined` .  I will update the demo and add a hint at https://ahooks.js.org/hooks/dom/use-external#basic-usage

```diff
import React from 'react';
import { useExternal } from 'ahooks';

export default () => {
  const [status, { toggle, load, unload }] = useExternal('/useExternal/test-external-script.js', {
    async: false,
  });

  return (
    <>
      <p>
        Status: <b>{status}</b>
      </p>
      <p>
        Response: <i>{status === 'ready' ? TEST_SCRIPT?.start() : '-'}</i>
      </p>
      <button type="button" style={{ marginRight: 8 }} onClick={() => toggle()}>
        toggle
      </button>
      <button type="button" style={{ marginRight: 8 }} onClick={() => { 
        unload();
        // Maybe you wanna remove the global variables or functions after run unload()
+        TEST_SCRIPT = undefined;
      }}>
        unload
      </button>
      <button type="button" style={{ marginRight: 8 }} onClick={() => load()}>
        load
      </button>
    </>
  );
};
```
