### ISSUE TITLE
useFusionTable的reset如何保留特定的表单字段的value？

### ISSUE THREAD

**Issue by we6288815** [alibaba/hooks#830]
使用useFusionTable的reset，不管是在Field.useField({values: {name: 'value'}});指定初始值，还是设置defaultParams
在reset时，都会把所有字段的value清空，如何保留指定字段的value？

**Comment by brickspert** [comment]
@youluna

**Comment by bindoon** [comment]
有现成的 api resetToDefault()

**Comment by youluna** [comment]
https://fusion.alibaba-inc.com/pc/component/field?themeid=2#topath-container
