### ISSUE TITLE
请问 useRequest 可以直接在小程序环境中使用吗？

### ISSUE THREAD

**Issue by 23233** [alibaba/hooks#833]
使用的框架是remax~ 谢谢！

**Comment by 23233** [comment]
打扰了，经过实验证明只要不使用umi-request发起请求的模式，使用fly等支持小程序环境的请求库，就可以使用useRequest！！
但是仅支持hooks中的useRequest 其他库未测试！

**Comment by watsonhaw5566** [comment]
> 使用fly等支持小程序环境的请求库

您使用这个的具体是怎么操作的。
