### ISSUE TITLE
Persistent/disk-based offline cache in browser for useRequest

### ISSUE THREAD

**Issue by KrishnaPG** [alibaba/hooks#834]
Is it possible to use disk-based cache with the requests, such as indexDB or LocalStorage?

The `cacheKey` is a great feature that improves the page performance on the client. However, memory-based cache means the cache gets lost on page refresh.

When using in combination with `antV` for loading slightly large-scale data volumes (that are usually read-only historical data, such as time-series aggregations etc.) for charts, using persistent cache in combination with `staleTime=-1` on local browser is a great way boost client side chart loading performance.

Kindly consider adding support for disk based persistent offline cache support for `useRequest` hook. 

A `plugin`  style of cache that supports both memory-based and offline-storage packages such https://github.com/localForage/localForage would be a great feature.

**Comment by KrishnaPG** [comment]
BTW, `useRequest` hook is awesome :)

**Comment by brickspert** [comment]
We will support this feature in v3.

**Comment by brickspert** [comment]
related: #875
