### ISSUE TITLE
useReactive好像是同步的，那对应的视图更新是fiber异步的吗？

### ISSUE THREAD

**Issue by qinxukai** [alibaba/hooks#835]
react为了性能 ，useState连setState都是异步的，导致很多问题，比如有些场景拿不到实时的值、useEffect捕获过时变量。

useReactive好像没有上述问题，只是疑问useReactive的更新导致的视图更新会不会是fiber形式的

**Comment by qinxukai** [comment]
就是问useReactive可以完全替代useState使用吗？

**Comment by turkyden** [comment]
> 就是问useReactive可以完全替代useState使用吗？

不建议，理论上 useReactive 仅仅只是通过 `new Proxy()`  实现对象代理，返回一个可观察的 `observable` 对象，有点类似于 vue 和 mobx 中的响应式、双向绑定的概念。

建议看一下咱们 ahooks/useReactive 的源码，仅 43 行。

https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useReactive/index.ts#L14

**Comment by turkyden** [comment]
> react为了性能 ，useState连setState都是异步的，导致很多问题，比如有些场景拿不到实时的值、useEffect捕获过时变量。

要理解 `setState` 异步还是同步，你可以看看这道**送分题**：

```jsx
class Test extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0
    }
  }
    
  componentDidMount() {
    this.setState({ count: this.state.count + 1 });
    console.log(this.state.count); // => 0
    this.setState({ count: this.state.count + 1 });
    console.log(this.state.count); // => 0
    window.setTimeout(() => {
      this.setState({ count: this.state.count + 1 });
      console.log(this.state.count); // => 1 + 1 = 2
      this.setState({ count: this.state.count + 1 });
      console.log(this.state.count); // => 2 + 1 = 3
    }, 0)
  }
}
```

输出结果：

`0`  `0`  `2`  `3`

**Comment by turkyden** [comment]
> useReactive好像没有上述问题，只是疑问useReactive的更新导致的视图更新会不会是fiber形式的

至于你说的 fiber 是指的 Fiber Reconciler 异步调和吧？它是 React v16 之后，Facebook 推出的对之前 Stack Reconciler 栈调和的一种优化方案，它的核心设计是增量渲染（incremental rendering），也就是将渲染工作分割为多个区块，并将其分散到多个帧中去执行。它的设计初衷是提高 React 在动画、画布及手势等场景下的性能表现。

目前，Fiber Reconciler 还不是一个最终的完成品，其中并发模式并不是默认启用，还处于开发阶段，目前仍然是在同步模式下启用。

这貌似与你提到的 **「useState 和 setState 都是异步的」** 没有太大关系吧，仔细想一想，如果 setState 做成同步，让 React 去同步渲染，把浏览器锁死了，岂不是 ... 事实上，React 中也是有同步场景的，比如原生事件 `addEventListener`, `setTimeout` 都是要同步去运行的。

因此，是否异步与 Fiber Reconciler 无关的哦。

**Comment by qinxukai** [comment]
useReactive源码我看过了

_如果setState同步转换，让React去同步渲染，把浏览器锁死了，岂不是_

这句话我能理解，有时候并不仅仅是渲染页面，state可能是通过复杂计算得来的，这个时候就需要常规的变量，而不是不能实时获取值的state，**我觉得react完全可以把setState做成同步，但是渲染是异步**，比如监听state用防抖节流的方式去渲染，或者异步渲染、延时渲染

我想用useReactive仅仅是为了实时计算

**Comment by turkyden** [comment]
> react为了性能 ，useState连setState都是异步的，导致很多问题，比如有些场景拿不到实时的值、useEffect捕获过时变量。
> 
> useReactive好像没有上述问题，只是疑问useReactive的更新导致的视图更新会不会是fiber形式的

总结一下：

1. useReactive 的实现很简单，但绝对与 fiber 无关，仅仅是使用 js 原生代理对象 `new Proxy()` 实现；
2. 原生对象的事件在 react 中会和 setTimeout，addEventListener 一样同步执行，可以看上面的[题目](https://github.com/alibaba/hooks/issues/835#issuecomment-762984955)哈；
3. setState 看起来像是异步是因为 react 出于优化性能的考量，要一次性收集所有状态改变，然后统一去做 diff 渲染；

感谢反馈！

**Comment by gwl002** [comment]
> useReactive源码我看过了
> 
> _如果setState同步转换，让React去同步渲染，把浏览器锁死了，岂不是_
> 
> 这句话我能理解，有时候并不仅仅是渲染页面，state可能是通过复杂计算得来的，这个时候就需要常规的变量，而不是不能实时获取值的state，**我觉得react完全可以把setState做成同步，但是渲染是异步**，比如监听state用防抖节流的方式去渲染，或者异步渲染、延时渲染
> 
> 我想用useReactive仅仅是为了实时计算
就是为了对标vue和mobx的这种写法，能直接改变值触发更新而已，不用immutable了。想同步拿setstate后的值做其他事情，就用楼上说的把setstate包在settimeout之内。
