### ISSUE TITLE
useSize 传入函数时存在问题

### ISSUE THREAD

**Issue by Darcrandex** [alibaba/hooks#837]
引用官方的例子: https://codesandbox.io/s/jichuyongfa-forked-3gzd5?file=/App.tsx:85-392

```
export default () => {
  const ref = useRef();

 // ok的
 // 只在'resize'的时候打印一次
  const size = useSize(ref);
  useEffect(() => {
    console.log("resize", size);
  }, [size]);
  return (
    <div ref={ref}>
      try to resize the preview window <br />
      dimensions -- width: {size.width} px, height: {size.height} px
    </div>
  );
};
```

```
export default () => {
  const ref = useRef();

 // 以函数作为参数
 // 会一直打印, 死循环
  const size = useSize( ()=> window.document.documentElement );
  useEffect(() => {
    console.log("resize", size);
  }, [size]);
  return (
    <div ref={ref}>
      try to resize the preview window <br />
      dimensions -- width: {size.width} px, height: {size.height} px
    </div>
  );
};
```

**Comment by turkyden** [comment]
```js
export default () => {
  const getDocumentElement = useCallback(() => window.document.documentElement, []);
  const size = useSize(getDocumentElement);

  useEffect(() => {
    console.log("resize", size);
  }, [size]);

  return (
    <div>
      try to resize the preview window <br />
      dimensions -- width: {size.width} px, height: {size.height} px
    </div>
  );
};
```

因为使用箭头函数传参，每次执行都会产生新的引用，导致 `useSize` 的依赖一直在改变。

你可以考虑使用 `useCallback` 传入一个函数，来避免重复执行，下一版我们会修复这个问题，@Darcrandex

**Comment by Darcrandex** [comment]
> ```js
> export default () => {
>   const getDocumentElement = useCallback(() => window.document.documentElement, []);
>   const size = useSize(getDocumentElement);
> 
>   useEffect(() => {
>     console.log("resize", size);
>   }, [size]);
> 
>   return (
>     <div>
>       try to resize the preview window <br />
>       dimensions -- width: {size.width} px, height: {size.height} px
>     </div>
>   );
> };
> ```
> 
> 因为使用箭头函数传参，每次执行都会产生新的引用，导致 `useSize` 的依赖一直在改变。
> 
> 你可以考虑使用 `useCallback` 传入一个函数，来避免重复执行，下一版我们会修复这个问题，@Darcrandex

好的

**Comment by chanelnumberseven** [comment]
这个问题好像没有解决啊
