### ISSUE TITLE
useSize 在监听dom元素时的问题

### ISSUE THREAD

**Issue by oldturkey** [alibaba/hooks#838]
````
const toolDom = document.querySelector('.ant-pro-table-list-toolbar');
  const theadDom = document.querySelector('.ant-table-thead');
  const toolbarHeight = useSize(toolDom);
  const theadHeight = useSize(theadDom);
````

因为元素可能没加载，所以可能第一次useSize监听到的为null，后续不会继续监听

**Comment by brickspert** [comment]
给个复现？

**Comment by oldturkey** [comment]
> 给个复现？

这个就是监听的dom元素是子组件，可能还没渲染出来，所以第一次加载父组件的时候useSize接收到的参数是null，后续如果函数组件不重新执行，也就无法触发useSize了。。

**Comment by oldturkey** [comment]
[table例子](https://codesandbox.io/s/cold-currying-b0het?file=/App.tsx)

**Comment by oldturkey** [comment]
> 给个复现？

例子里面可以看到，如果首次渲染不刷新的话，是无法监听到到dom元素高度变化的

**Comment by oldturkey** [comment]
@brickspert brickspert 能给个答复么

**Comment by turkyden** [comment]
```diff
- const toolbarHeight = useSize(document.querySelector('.ant-pro-table-list-toolbar'));
+ const toolbarHeight = useSize(() => document.querySelector('.ant-pro-table-list-toolbar'));
```

你这样试试呢？@oldturkey

**Comment by oldturkey** [comment]
> ```diff
> - const toolbarHeight = useSize(document.querySelector('.ant-pro-table-list-toolbar'));
> + const toolbarHeight = useSize(() => document.querySelector('.ant-pro-table-list-toolbar'));
> ```
> 
> 你这样试试呢？@oldturkey

不可以，上面有贴例子地址哈

**Comment by Turkyden** [comment]
```js
import React, { useRef } from 'react';
import { useSize } from 'ahooks';
export default () => {
  const ref = useRef();
  const size = useSize(ref);
  return (
    <div ref={ref}>
      try to resize the preview window <br />
      dimensions -- width: {size.width} px, height: {size.height} px
    </div>
  );
};
```

这种情况的话，建议使用 `useRef`

**Comment by turkyden** [comment]
```js
import React, { useEffect, useState } from 'react';
import { useSize } from 'ahooks';

export default () => {
  const [loading, setLoading] = useState(true);
  const [dom, setDom] = useState(undefined);
  const size = useSize(dom);

  useEffect(() => {
    const timer = window.setTimeout(() => setLoading(false), 2000);
    return () => window.clearTimeout(timer)
  }, [])

  useEffect(() => {
    if(!loading){
      setDom(document.querySelector('#myDom'));
    }
  }, [loading])

  if(loading) {
    return <p>Loading ...</p>
  }
  
  return (
    <div id="myDom">
      try to resize the preview window <br />
      dimensions -- width: {size.width} px, height: {size.height} px
    </div>
  );
};
```

明白了，你通过 Dom API 取的节点是异步加载出来的，首先你要确保取到 DOM，再传入 `useSize` 即可。@oldturkey

**Comment by oldturkey** [comment]
> ```js
> import React, { useEffect, useState } from 'react';
> import { useSize } from 'ahooks';
> 
> export default () => {
>   const [loading, setLoading] = useState(true);
>   const [dom, setDom] = useState(undefined);
>   const size = useSize(dom);
> 
>   useEffect(() => {
>     const timer = window.setTimeout(() => setLoading(false), 2000);
>     return () => window.clearTimeout(timer)
>   }, [])
> 
>   useEffect(() => {
>     if(!loading){
>       setDom(document.querySelector('#myDom'));
>     }
>   }, [loading])
> 
>   if(loading) {
>     return <p>Loading ...</p>
>   }
>   
>   return (
>     <div id="myDom">
>       try to resize the preview window <br />
>       dimensions -- width: {size.width} px, height: {size.height} px
>     </div>
>   );
> };
> ```
> 
> 明白了，你通过 Dom API 取的节点是异步加载出来的，首先你要确保取到 DOM，再传入 `useSize` 即可。@oldturkey

这个和我🌰里的解决方式也差不多吧，确认加载这段逻辑看起来挺变扭

**Comment by oldturkey** [comment]
const [refresh, setRefresh] = useState(false);
    useEffect(() => {
      if (actionRef.current) {
        setRefresh(true);
      }
    }, [actionRef, refresh]);

**Comment by brickspert** [comment]
```js
  const searchDom = document.querySelector(
    ".ant-pro-table-search ant-pro-table-search-query-filter"
  );

  const searchHeight = useSize(searchDom)?.height || 0;
```

对于 useSize 来说，接收了一个 `null`，也就是 `useSize(null)`。  `null` 怎么来的，真的不知道。

解决方案如 @Turkyden 所说，需要在适当的时机，触发函数重新执行。
