### ISSUE TITLE
关于useDynamicList使用

### ISSUE THREAD

**Issue by zj-wukewei** [alibaba/hooks#84]
在 const {
      list,
      remove,
      getKey,
      push,
    } = useDynamicList(usersList);
中数据（usersList）如果是后台获取的，在获取成功时候list数据不会变化，是否能支持一下。

**Comment by brickspert** [comment]
有个 resetList 是满足你条件的。

**Comment by zj-wukewei** [comment]
为什么不加一个useEffect，比如以下代码：
  useEffect(() => {
    setList(() => {
     (initialValue || []).forEach((_, index) => {
      setKey(index);
    });
    return initialValue || [];
    });
  }, [initialValue])

**Comment by ttys026** [comment]
@zj-wukewei 这里当时考虑过去监听 initialValue 的变化，但主要的问题在于
有一种使用场景是直接写死的数据，此时 initialValue 用 dependency 原生的 Object.is 判断每次都是不一样的。这样会导致无限循环，keyList 会被一直清空，counter 会被一直重置。

如果转成 string 再去比较，考虑到初始值可能是个巨大的包含 object 的数组，甚至存在环形结构，性能可能会变差。

在你说的 API 返回数据的情况下，一般都有一个时机可以调用 resetList 的方法去更新 list，目前看来会更合适一点。
