### ISSUE TITLE
useRequest 轮询模式下，执行cancel的时候 报错：You should't call cancel when service not executed once.

### ISSUE THREAD

**Issue by chenqinyang1994** [alibaba/hooks#843]
**我在执行Modal.info的onOk回调里面调用轮询的cancel 报错You should't call cancel when service not executed once. 但轮询已经在执行了，为什么还报这个错呢？**
_期待您的回复，谢谢_

```
const { run: validWechatLoginStart, cancel: validWechatLoginCancel } = useRequest(
  codeValidWechatLogin,
  {
    manual: true,
    pollingInterval: 1000,
    onSuccess: (data) => {
      if (data) {
        validWechatLoginCancel();
      }
    },
    onError: () => {
      validWechatLoginCancel();
    },
  },
);

const { run: handleQrWechatLogin } = useRequest(
  () => {
    return codeQrWechatLogin({ uuid });
  },
  {
    manual: true,
    onSuccess: (data) => {
      const { qrCode, code } = data;
      QRCode.toCanvas(qrCode, { errorCorrectionLevel: 'H' }, (err: any, canvas: any) => {
        if (err) {
          throw err;
        }
        validWechatLoginStart({ uuid, code });
        Modal.info({
          title: '请扫描下方二维码登录',
          content: (
            <div style={{ textAlign: 'center', marginLeft: '-38px' }}>
              <img src={canvas.toDataURL()} alt="qrcode" />
            </div>
          ),
          okText: '关闭',
          onOk: () => {
            validWechatLoginCancel(); // 首次点击关闭按钮，执行这个cancel的时候报错！！
          },
        });
      });
    },
  },
);

```

**Comment by brickspert** [comment]
你的 useRequest 版本应该不是最新的，最新的已经不会报这个错误了。

**Comment by brickspert** [comment]
你的 useRequest 版本应该不是最新的，最新的这个是个 warning，不是 error。

是因为没有执行过 run，所以执行 cancel 没有意义。当然你可以不用 关心这个警告。

**Comment by kitety** [comment]
表示在@umijs/use-request 复现这个问题了，版本1.4.3

**Comment by wilsonyiyi** [comment]
> 你的 useRequest 版本应该不是最新的，最新的这个是个 warning，不是 error。
> 
> 是因为没有执行过 run，所以执行 cancel 没有意义。当然你可以不用 关心这个警告。

@brickspert 在组件卸载的时候需要去cancel，但我不喜欢这个warning，怎么判断当前请求是否run了？useRequest能否提供一个标记属性

**Comment by brickspert** [comment]
> > 你的 useRequest 版本应该不是最新的，最新的这个是个 warning，不是 error。
> > 是因为没有执行过 run，所以执行 cancel 没有意义。当然你可以不用 关心这个警告。
> 
> @brickspert 在组件卸载的时候需要去cancel，但我不喜欢这个warning，怎么判断当前请求是否run了？useRequest能否提供一个标记属性

组件卸载会自动 cancel 的，不需要手动 cancel。或者你也可以根据是否有 data 来判断是否请求过了。

**Comment by wilsonyiyi** [comment]
> > > 你的 useRequest 版本应该不是最新的，最新的这个是个 warning，不是 error。
> > > 是因为没有执行过 run，所以执行 cancel 没有意义。当然你可以不用 关心这个警告。
> > 
> > 
> > @brickspert 在组件卸载的时候需要去cancel，但我不喜欢这个warning，怎么判断当前请求是否run了？useRequest能否提供一个标记属性
> 
> 组件卸载会自动 cancel 的，不需要手动 cancel。或者你也可以根据是否有 data 来判断是否请求过了。

thx!!! 在文档里没看到组件卸载会自动cancel的说明。data判断不了吧，service error的时候data是undefined

**Comment by hp0912** [comment]
> > > 你的 useRequest 版本应该不是最新的，最新的这个是个 warning，不是 error。
> > > 是因为没有执行过 run，所以执行 cancel 没有意义。当然你可以不用 关心这个警告。
> > 
> > 
> > @brickspert 在组件卸载的时候需要去cancel，但我不喜欢这个warning，怎么判断当前请求是否run了？useRequest能否提供一个标记属性
> 
> 组件卸载会自动 cancel 的，不需要手动 cancel。或者你也可以根据是否有 data 来判断是否请求过了。

问题+1，已经在轮询了，调用cancel还是有这个警告。

**Comment by brickspert** [comment]
> 问题+1，已经在轮询了，调用cancel还是有这个警告。

可以提供下代码示例，应该是闭包问题。
