### ISSUE TITLE
请问ahook是umihook升级版吗？ahook官网打不开

### ISSUE THREAD

**Issue by birdycn** [alibaba/hooks#844]
目前umihook版本是1.6.5？ahook是2.X？所以现在ahook才是新版本吗

**Comment by turkyden** [comment]
https://ahooks.js.org/zh-CN/docs/umi-hooks-to-ahooks

@birdycn

**Comment by awmleer** [comment]
umi hooks 是 ahooks 的前身
官网如果打不开的话，可以用[国内镜像](https://ahooks.gitee.io/zh-CN)哈
