### ISSUE TITLE
run 方法直行可不可以有返回值

### ISSUE THREAD

**Issue by tanwei0425** [alibaba/hooks#849]
类似于  const data = run()   data中可以拿到run的直行结果。
现在我在子组件封装了一个方法，子组件直行方法后需要把结果返回到父组件，run在执行过程中，返回值就已经返回到父组件中了，所以有问题

**Comment by turkyden** [comment]
具体是哪个 hook 呢 ？

**Comment by tanwei0425** [comment]
> 具体是哪个 hook 呢 ？
useRequest

**Comment by tanwei0425** [comment]
![Uploading image.png…]()

**Comment by tanwei0425** [comment]
![image](https://user-images.githubusercontent.com/37789693/106376346-7e1ad580-63cf-11eb-8193-2ee8f31df42b.png)

**Comment by brickspert** [comment]
现在支持的呀。 

```
const data  = await run();
```

**Comment by tanwei0425** [comment]
> 现在支持的呀。
> 
> ```
> const data  = await run();
> ```

我的返回就是null  是因为我全局设置了 debounceInterval 的原因吗？
![image](https://user-images.githubusercontent.com/37789693/109410875-1c06bd80-79d9-11eb-80e2-cf86a8dcb0e4.png)
