### ISSUE TITLE
【疑问】非轮询的请求，使用useRequest的cancel无法取消调用

### ISSUE THREAD

**Issue by oliviaxtli** [alibaba/hooks#851]
请问，useRequest的cancel是否只能用在轮询的请求？
我有个只调一次的请求，希望在组件卸载的时候取消请求以避免内存泄漏问题，但是发现用cancel还是无法停止请求
```
const { run, cancel } = useRequest(request, { manual: true });

useEffect(()=>{
  return ()=>{
    cancel ();
  }
})
```

**Comment by brickspert** [comment]
取消的行为 useRequest 自己会做的，不会有内存泄漏的问题的。

**Comment by Kaijun** [comment]
> 取消的行为 useRequest 自己会做的，不会有内存泄漏的问题的。

请问如何 cancel http request？有类似 cancelToken 的实现吗？

**Comment by Ray1993** [comment]
> > 取消的行为 useRequest 自己会做的，不会有内存泄漏的问题的。
> 
> 请问如何 cancel http request？有类似 cancelToken 的实现吗？
 同问，http request 好像cancel不了
