### ISSUE TITLE
希望能够取消请求行为

### ISSUE THREAD

**Issue by raohong** [alibaba/hooks#862]
如题。

被丢弃掉的请求，能够自行一定方法去取消，比如 xhr.abort,  或者提供相关选项自己处理

**Comment by shaoqiwang-fe** [comment]
请问这个支持了吗

**Comment by yigexiaoairen** [comment]
Result.cancel 可以取消当前请求，看一下是不是你想要的api

api地址：https://ahooks.js.org/zh-CN/hooks/async#result

**Comment by xiexingen** [comment]
这种场景应该比较常见，比如列表查询 可能后端响应还没返回  用户切换了页面  这种情况下需要能吧之前请求cancel掉  类似axios的cancel

**Comment by eightHundreds** [comment]
希望有个配置，比如`cancelBeforeRun`，能让每次run执行前都自动cancel

**Comment by xiexingen** [comment]
我最后的实现思路是这样，可供参考
实现一个请求管理器，然后再全局拦截器里面请求开始的时候生成一个唯一id的map，在响应拦截里面再移除掉
如果是同一个请求的，请求拦截器里面把上一次的cancel掉了

**Comment by brickspert** [comment]
现在 useRequest 默认会废弃掉老的请求的响应，不需要做任何操作。

也就是每次调用 run，都会放弃之前发出去的请求。

**Comment by xiexingen** [comment]
> 现在 useRequest 默认会废弃掉老的请求的响应，不需要做任何操作。
> 
> 也就是每次调用 run，都会放弃之前发出去的请求。

看楼主的意思，应该是想在这个的基础上增加一个cancel的方法，可以自己去cancel，比如在组件销毁的时候调用cancel

**Comment by crazylxr** [comment]
v3 是有了 cancel 的方法可以取消的哈，但是取消的是 run 这个动作，而不能真正的取消请求是否发出去，如果你的请求库是用的 fetch ，发起的请求是没有办法取消的，axios 之前可以取消因为之前用的 xhr 做的，xhr 是可以取消的。
