### ISSUE TITLE
TS2339: Property 'query' does not exist on type 'Location '.

### ISSUE THREAD

**Issue by mdddj** [alibaba/hooks#864]
![image](https://user-images.githubusercontent.com/29020213/107150485-f7e72c00-6998-11eb-99fb-b42c5125a67a.png)

有没有办法取消这个报错,我有强迫症,虽然不影响使用

**Comment by headwindz** [comment]
useHistory是react-router-dom里的。跟ahooks没关系呀。。。

**Comment by awmleer** [comment]
这不是 ahooks 的问题哈
