### ISSUE TITLE
useRequest run()在useEffect中的依赖项问题

### ISSUE THREAD

**Issue by aspirantzhang** [alibaba/hooks#866]
useEffect依赖项数组中，包括函数时，函数也要加在依赖项中，所以当前文档中有关`useRequest`的`refreshDeps`的解释中有一段代码：
```
const [userId, setUserId] = useState('1');
const { data, run, loading } = useRequest(()=> getUserSchool(userId));
useEffect(() => {
  run();
}, [userId]);
```
是不对的，理论上应该是[userId, run]，但是明显这样做是不对的。

useRequest中提供了`refreshDeps`和`ready`两个api，如果这两个api无法满足要求时，我们还是要在useEffect中写run，例如
```
useEffect(() => {
    if (props.modalVisible === true) {
      run();
    } else {
      form.resetFields();
    }
}, [props.modalVisible]);
```
这种情况下，功能上完全满足要求，但eslint提示依赖项缺失，而我们又不可能写成`[props.modalVisible, run, form]`这样的代码。
请问这部分的话，`useRequest`有什么其它的处理方法，或建议。谢谢。

**Comment by zheeeng** [comment]
确实

```js
useEffect(() => {
  run();
}, [userId]);
```

是无法通过 dependencies check 的

**Comment by zheeeng** [comment]
@aspirantzhang 可以重新打开这个 issue 吗

**Comment by aspirantzhang** [comment]
> @aspirantzhang 可以重新打开这个 issue 吗

没有必要了，这个应该是不会解决的，之前已经几个月没有回复。我记得也曾在ant design里面看过有外国网友对这种类似设计的质疑，但是最终也是没有什么妥善的处理。我个人感觉，蚂蚁/阿里团队比较注重实用，对这种细节的规范并不是很在意。

**Comment by brickspert** [comment]
这个要解决只有一个办法。

```
const runRef = useRef(run);
runRef.current = run;

useEffect(() => {
  runRef.current(userId);
}, [userId]);
```
