### ISSUE TITLE
useSelections hooks are not memoized

### ISSUE THREAD

**Issue by apieceofbart** [alibaba/hooks#867]
Check this example for `toggle` method from `useSelections`: https://codesandbox.io/s/useselections-rerender-rkrme?file=/src/App.tsx

The problem is when running `toggle` you're looking at `selection` value that's outside of the function - because it will change the whole function will change. You could rewrite toggle to something like that:
```
  const toggleSelection = useCallback((item: T) => {
    setSelection((selection) => {
      const newSelection = new Set(selection);
      if (selection.has(item)) {
        newSelection.delete(item);
      } else {
        newSelection.add(item);
      }
      return Array.from(newSelection);
    });
  }, []);
```

Any reason you're not just using Set in instead of Array for selection?
Other methods have similar problem (select, unselect etc.)

**Comment by turkyden** [comment]
OK, i will check it.

**Comment by apieceofbart** [comment]
I am not saying this is a must - if you decide to keep it this way then fine. I am just pointing out that it might be something you're interested in improving.
