### ISSUE TITLE
useRequest 的 refreshDeps & cacheKey 同时使用时，缓存未生效

### ISSUE THREAD

**Issue by donaldshen** [alibaba/hooks#868]
https://codesandbox.io/s/huancun-swr-forked-czgqj?file=/App.tsx
demo 在此；每次 refreshDeps 变更时必定执行请求，尽管已经配置 cacheKey 了

**Comment by gitivon** [comment]
单独使用 cacheKey 都没用

**Comment by brickspert** [comment]
这个是期望行为。 目前 cacheKey 的行为是：先返回一个旧的数据，再重新去请求新数据。

**Comment by KeyGong** [comment]
遇到了同样的问题

**Comment by KeyGong** [comment]
怎么处理的

**Comment by brickspert** [comment]
可以配置 `staleTime=-1` 让数据保持永久新鲜。
