### ISSUE TITLE
useRequest 能否新加一个 params 参数配合 refreshDeps 使用

### ISSUE THREAD

**Issue by linhf123** [alibaba/hooks#874]
useRequest 能否新加一个 params 参数，在 refreshDeps 更新之后使用最新的值去进行请求，defaultParams 会一直使用第一次的值
```jsx
const { data, loading, refresh } = useRequest(SoftwarePackageController.listPackages, {
  ready: listPackages,
  defaultParams: [
    {
      type: typeList,
      withInstallationData,
    },
  ],
  refreshDeps: [typeList.join(','), withInstallationData, listPackages],
});

**Comment by linhf123** [comment]
@brickspert 可以接受这个 feature 嘛？

**Comment by sayjeyhi** [comment]
Any updates on this?
```js
defaultParams: [changedName],
refreshDeps: [changedName],
```

I want my service to be called with new `changedName` every time...

**Comment by linhf123** [comment]
@sayjeyhi ,You can write it like this
```
const { data, loading, refresh } = useRequest(() => SoftwarePackageController.listPackages( {
   changedName,
    }), {
  refreshDeps: [changedName],
});
```

**Comment by brickspert** [comment]
> @sayjeyhi ,You can write it like this
> 
> ```
> const { data, loading, refresh } = useRequest(() => SoftwarePackageController.listPackages( {
>    changedName,
>     }), {
>   refreshDeps: [changedName],
> });
> ```

这个用法可以解决 params 的问题 吧？如果有其它问题再 open 哈。
