### ISSUE TITLE
useRequest在ie11中formatResult返回结果为空值

### ISSUE THREAD

**Issue by yulongcs** [alibaba/hooks#877]
useRequest在ie11中formatResult返回结果为空值，Chrome和Firefox没有此问题，
ahooks版本： 2.9.6

**Comment by xu-Aurora** [comment]
我也碰到这个问题了，请问解决了嘛？

**Comment by brickspert** [comment]
能否给个 demo？应该不是 useRequest 自己的问题，感觉像是请求库的问题。

**Comment by brickspert** [comment]
Related #924
