### ISSUE TITLE
useRequest onError 如何拿到错误返回的信息，错误编码等。。

### ISSUE THREAD

**Issue by junchaohu** [alibaba/hooks#878]
`throwOnError: true,
  onError: ((error, params) => {
      console.log("error:", error);
    })`
这里的error只有res的错误文本，其它信息都没有，如何取到呢？

**Comment by brickspert** [comment]
onError 是 Promise 返回的东西，你得想想怎么把异常塞到 promise 中~

**Comment by kunKun-tx** [comment]
`error.data` 和 `error.response`

**Comment by junchaohu** [comment]
@kunKun-tx error对象中，并没有`error.data` 和`error.response`, 设置requestMethod定义axios集成库到是可以。

**Comment by kunKun-tx** [comment]
@junchaohu 嗯 你是对的 昨天半夜稀里糊涂 忘了加了这句 而且才看到`throwOnError: true,`
