### ISSUE TITLE
[useScroll]希望有触底回调

### ISSUE THREAD

**Issue by xmsz** [alibaba/hooks#880]
背景
- 需要监听一个滚动区域是否触底

需求
- useScroll能够支持触底回调
- 或者其他hooks来解决这个需求

**Comment by brickspert** [comment]
能提供下具体的业务经常吗？~~

* 也许 useRequest 的 loadMore 模式可以满足你的诉求？
* 或者也可以在滚动区底部增加一个 dom，然后通过监听这个 dom 是否展示来判断是否滚动到底部。

**Comment by xmsz** [comment]
> 能提供下具体的业务经常吗？~~
> 
> * 也许 useRequest 的 loadMore 模式可以满足你的诉求？
> * 或者也可以在滚动区底部增加一个 dom，然后通过监听这个 dom 是否展示来判断是否滚动到底部。

移动端的业务，记录类的会比较经常用到

现在是手动监听了滚动条的位置，然后进行判断
