### ISSUE TITLE
[useUrlState]类型疑问

### ISSUE THREAD

**Issue by xmsz** [alibaba/hooks#882]
```
 type state = Partial<{ [key in keyof S]: any }>;
```

这一句有些疑问

疑问一：为什么类型是any
理论上应该都是string

现在是any，导致业务代码里很容易写错
例如本来要传 {mode:''}，然后写的时候
```
const [query] = useUrlState();

function a(options: {mode: string}) {
}

// BAD
a(query.mode)

// GOOD
a({mode: query.mode})

```
很容易就尴尬了

疑问二：如果配置了initialState的话，不应该都是可选类型
理论上如果配置initialState，那在initialStaet的值应该是一定有的

现在因为所有都是可选类型，这个initialState形同虚设

希望可以完善一下类型判断

**Comment by ttys026** [comment]
关于疑问一
当初这么做是有两方面的考虑：
1. query 不一定是 string 类型，也有可能是 string[].
例如对于 search: `?name=1&name=2`; 遵循浏览器 URLSearchParams 的规则，会解析为 `{ name: ["1", "2"] }`;

但是如你所说，绝大多数情况下类型都是 string，如果我们返回类型是 `string | string[]`, 那么在使用的时候，都需要进行一次额外的 type assertion，会给使用带来较大的不便。

2. setState 的使用会有更多约束
例如 `setState({ count: 0 })`, `setState({ visible: true })`, 这些声明了 toString 方法的类型，都不能直接使用而需要一次额外的转换了。

当然这样做是损失了 ts 校验的严格性，换来了一些使用上的便捷，关于这个问题我们还可以再讨论。

关于疑问二
这个确实是之前没有考虑过，如果不加 Partial 来修饰类型，就需要在 generic type 中描述清晰哪些字段在初始值中始终存在，对使用者定义类型的要求会更高。而标示为可能为空，因为 optional chaing 的写法，可以在不影响代码补全的前提下，保证代码的健壮性。
