### ISSUE TITLE
useRequest clearCache method to force cache clear

### ISSUE THREAD

**Issue by sayjeyhi** [alibaba/hooks#884]
It could be so great if we have a method on `useRequest` hook to allow us clear the cache by cache key.
something like:
```js
const { run, clearCache, data } = useRequest(service, {
  manual: true,
  defaultLoading: !!id,
  cacheKey: `cache_${id}`
});

clearCache('cache_${id}');   // for example on component unmount
```

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/141466990-27aa1887-5e43-49e3-b475-a532d43b9c3c.png)

@Coco-rq

**Comment by brickspert** [comment]
added on v3.0.0-alpha.18
