### ISSUE TITLE
[peerDependencies] 请问是否可以安全的忽略 react17.x 的安装警告

### ISSUE THREAD

**Issue by ghost** [alibaba/hooks#887]
因为最近准备开发的新项目依赖包都采用最新版本。
降级react是一个不够友好的次选方案。

在使用 yarn install 安装 ahooks 时收到错误的对等依赖警告。
请问是否可以安全的忽略此警告或者说 ahooks 近期有无升级 peerDependencies 的计划？

**Comment by awmleer** [comment]
@codewangshuhao 嗯嗯下个版本我们会修复掉，预计一周内～

**Comment by ghost** [comment]
> @codewangshuhao 嗯嗯下个版本我们会修复掉，预计一周内～

了解了，非常感谢，哈哈没想到能够秒回。

**Comment by awmleer** [comment]
这个issue我暂时还是先保持open状态了哈，等修掉了我再close

**Comment by ghost** [comment]
> 这个issue我暂时还是先保持open状态了哈，等修掉了我再close

好的

**Comment by fkocovski** [comment]
Is this somehow related to the issue when trying to run `npm update`?

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: someapp@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from ahooks@2.9.6
npm ERR! node_modules/ahooks
npm ERR!   ahooks@"^2.9.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by pierre-H** [comment]
Same problem ...  😢 
Any news ?

**Comment by awmleer** [comment]
@pierre-H The [`v2.10.0`](https://github.com/alibaba/hooks/releases/tag/v2.10.0) release has fixed this problem. The related PR is #871.

**Comment by ghost** [comment]
> @pierre-H The [`v2.10.0`](https://github.com/alibaba/hooks/releases/tag/v2.10.0) release has fixed this problem. The related PR is #871.

似乎在此次版本发布中并未看到有关 package.json 文件的 peerDependencies 字段的变化啊，而且 yarn 的警告仍然存在，请检查分支合并过程中 commit 是否有遗漏。

[https://github.com/alibaba/hooks/compare/v2.10.0...master](https://github.com/alibaba/hooks/compare/v2.10.0...master)

**Comment by awmleer** [comment]
@codewangshuhao 噢……之前的PR改的是 `use-request` 这个package，`hooks` 没有一起调整掉，我去改下

**Comment by awmleer** [comment]
Fixed via fed493b

**Comment by fkocovski** [comment]
> Fixed via [fed493b](https://github.com/alibaba/hooks/commit/fed493bddc048bfbe60a148251dd108c6069a697)

I have `v2.10.0` installed but even if I run `rm -rf node_modules/ && rm -f package-lock.json && npm cache clean --force && npm install` I still get the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: someapp@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from ahooks@2.10.0
npm ERR! node_modules/ahooks
npm ERR!   ahooks@"2.10.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/someuser/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/someuser/.npm/_logs/2021-04-20T08_01_14_474Z-debug.log
```

**Comment by awmleer** [comment]
@fkocovski I have just released a new version [`v2.10.1`](https://github.com/alibaba/hooks/releases/tag/v2.10.1). This version should be working.
