### ISSUE TITLE
useUrlState 想删掉state中的某个值删不掉

### ISSUE THREAD

**Issue by xian107** [alibaba/hooks#890]
const [state,setState] = useUrlState({
        name:"sanzhang"，
        age:2
});
// 点击事件
cosnt onClickHandle = ()=>{
       setState({name:""})
}
设置name为空，state中的name还会是sanzhang

**Comment by brickspert** [comment]
用 undefined 代替 空字符串

**Comment by brickspert** [comment]
这里确实是删不掉，之前回复有问题。

我们在 3.0 版本修复这个问题。

**Comment by brickspert** [comment]
3.0 版本删除了 initialData，你可以这样用

```js
const {data = initialData} = ...
```

Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

**Comment by UGAROY** [comment]
看起来 3.0 版本仍然存在这个问题？

1. initialState 并没有被移除？
2. setState({xx: undefined})，状态会回到初始值
