### ISSUE TITLE
useDynamicList 中使用resetList时，数据没有更新

### ISSUE THREAD

**Issue by JSupot** [alibaba/hooks#893]
在使用resetList时，对应的表单域中的数据没有变，源码中好像在reset的时候，重置了key，这里感觉应该在现有key的基础上进行递增，不然表单域中的key没有变，数据不会更新

**Comment by ttys026** [comment]
你说的是对的，因为这个 hooks 开发的时间比较早, 当时配合 antd3 中 getFieldDecorator 不会有问题，因为 render props 的方式会强制重新渲染 children。这本来是 antd 的一个 bug，但是被当作 feature 在用。重置 key 反而可以让数组从 0 开始更具语义。

如果是配合 antd4 使用确实会导致无法重置内容的问题。修复 pr #920
