### ISSUE TITLE
useRequest 建议考虑兼容前端分页的情景

### ISSUE THREAD

**Issue by cyndra0** [alibaba/hooks#898]
我在前端分页的情况下使用 useAntdForm，搜索时页面回到第一页这些逻辑都一样，问题出在 table onChange 的时候会发送多余的请求（此时其实数据已全部加载，data.total === pagination.total，分页排序这些都不应重新请求了）~

不知是否会考虑或者是否有考虑过这种场景哈~看了下现在 useRequest 的实现，分页配置是来源于请求参数params的，而要改变 params 就必须 run fetch。
https://github.com/alibaba/hooks/blob/43088bb9a3fa6448b14cce7a5e6ebfe2ef3a8d4c/packages/use-request/src/usePaginated.ts#L106

**Comment by brickspert** [comment]
是不是前端分页，直接用 useRequest 就好了，直接一次性把数据拉出来。

用不到 useAntdForm 的吧~

**Comment by cyndra0** [comment]
> 是不是前端分页，直接用 useRequest 就好了，直接一次性把数据拉出来。
> 
> 用不到 useAntdForm 的吧~

因为搜索过滤还是在后端做的，然后有用到 form。
我目前用的是一个最简单的处理方式：在 onSuccess 里根据返回数据和分页参数更新一个表示是否是前端分页的 flag，来选择性地忽略 onChange 和 pagination 来让 table 自己管理分页，也是能比较偷懒地覆盖到这个场景的……

**Comment by brickspert** [comment]
其实你这样的用法是合理的。
