### ISSUE TITLE
useSearch

### ISSUE THREAD

**Issue by brickspert** [alibaba/hooks#9]
适用于边输入边查询的场景。内置了 防抖控制，请求时序控制，加载状态 等逻辑。

![image](https://user-images.githubusercontent.com/12526493/61294280-09417400-a808-11e9-9850-9690d8ac1a9a.png)

```
const {
  data,
  loading,
  bind: {onChange, value}
} = useSearch(loadData, deps);
```

**输入**

* loadData 一个 Promise 函数，接收参数为搜索文本
* deps 依赖数组，如果依赖变化，则 reload

**输出**

* data loadData 返回的数据
* loading 是否正在加载

**应用场景**

```
const Demo = (type) => {
  const loadData = searchText => asyncGetList(searchText);

  const { data, loading, bind } = useSearch(loadData, [type]);

  return (
    <div>
      <Input {...bind} />
      
      <Spin spinning={loading}>
        {/* 从 data 中拿到列表的数据 */}
        {data.result.map(i => <List data={i} key={i.id} />)}
      </Spin>
    </div>
  )
}
```

**Comment by brickspert** [comment]
疑问：onChange 和 value 适用于 Input 搜索。

但是 [Select](https://ant.design/components/select-cn/#components-select-demo-select-users) 是 onSearch 和 value。如何兼容两种情况呢？

**Comment by xc1427** [comment]
感觉这个放在 antd 下面比较好。因为要感知 Input 的 API。
