### ISSUE TITLE
不太理解 useSetState 为什么不加入置空数据的能力呢？

### ISSUE THREAD

**Issue by lwpersonal** [alibaba/hooks#900]
例如
```js
const [pageSta, setPageSta] = useSetState({
    a: 1,
    b: 2,
  });
```
某些情况下想要将 pageSta 改变为一个空对象 `{}`，目前看源码是无法实现的。

![image](https://user-images.githubusercontent.com/26055361/112573205-c3cfa980-8e26-11eb-8d83-256082d97600.png)

如果接收到的 patch 是一个函数，则直接设置最终的 state 为函数返回的结果。是出于什么考虑没有这么设置吗？

```js
const setMergeState = useCallback(patch => {
    if (isFunction(patch)) {
      setState(prevState => patch(prevState));
    } else {
      setState(prevState => ({
        ...prevState,
        ...patch,
      }));
    }
  }, []);
```

**Comment by kouchao** [comment]
同样的问题

**Comment by liuyib** [comment]
对标的设计不同。

useSetState 对标 class 组件的 this.setState。需要置空能力的话，用 useResetState
