### ISSUE TITLE
useRequest怎么实现无感刷新呢

### ISSUE THREAD

**Issue by weird94** [alibaba/hooks#912]
无感刷新
1. 不重置loading状态
2. 请求失败不重写data

**Comment by weird94** [comment]
感觉目前暴露出来的api无法分辨第一次请求和后续的刷新请求，用户貌似无法在当前api下实现这个需求

**Comment by brickspert** [comment]
> 1. 不重置loading

可以这样判断 `const finalLoading = !data && loading`

>2. 请求失败不重写data

这个可能需要加个配置项了

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
