### ISSUE TITLE
usePrevious 的一些问题

### ISSUE THREAD

**Issue by Col0ring** [alibaba/hooks#918]
## 问题
ahooks 的 usePrevious 目前发现有两个问题：
1.之前在 https://github.com/alibaba/hooks/issues/780 看到过相似的问题，在 StrictMode 时由于会 render 多次，造成了 usePrevious 内部多次执行，而 prevRef 的值实际在页面显示时与原值是相同的。
> 上面的问题在 react-use 或者官方的实例中能够得到解决：
```ts
import { useEffect, useRef } from "react";

export default function usePrevious<T>(state: T): T | undefined {
  const ref = useRef<T>();

  useEffect(() => {
    ref.current = state;
  });

  return ref.current;
}
```
但是这样做本质上是将 prevRef 的修改时间延后，也就是页面 render 后再修改值，当页面 forceUpdate 或者其他 state 改变时，由于再次 render，prevRef 在页面上还是会发生变化（不清楚是故意这样做的还是没考虑到相关情况）。

2.该问题和上一个问题中 react-use 的实现方式中遇到的问题一样，在非 StrictMode 时 forceUpdate 还是会执行 usePrevious，导致 prevRef 的值在二次 render 发生改变。
上面的问题具体可以看下：https://codesandbox.io/s/competent-bush-mdosk?file=/src/App.tsx 这个示例。

## 解决方案
目前对于上面两种情况想到一个解决方式：
```ts
import { useRef, useMemo } from "react";

type compareFunction<T> = (prev: T | undefined, next: T) => boolean;

// 对目前 ahooks 的实现做一下修改
function usePrevious<T>(state: T, compare?: compareFunction<T>): T | undefined {
  const prevRef = useRef<T>();
  const curRef = useRef<T>();
  const needUpdate = useMemo(
    () =>
      typeof compare === "function" ? compare(prevRef.current, state) : true,
    [compare, state]
  );
  // 在更新时额外判断  curRef.current 是否与当前 state 相等，避免二次渲染的时候修改 prevRef.current 的值
  if (needUpdate && curRef.current !== state) {
    prevRef.current = curRef.current;
  }
 //  curRef.current 单独提出，在二次渲染的时候实际是保存上一个状态
  curRef.current = state;

  return prevRef.current;
}

export type { compareFunction };
export default usePrevious;
```
运行结果同样可以在 https://codesandbox.io/s/competent-bush-mdosk?file=/src/App.tsx 查看。目前来说做了上面的修改就能达到预期了，可以看下能否适用。

**Comment by awmleer** [comment]
@Col0ring 感谢提供这么详细的说明和复现demo～
我测试下来发现这个问题其实可以归纳为 ahooks 的 `usePrevious` 在普通模式和严格模式下的行为不一致
你提供的这个解决方案虽然可以规避掉这个问题，但是改变了这个 Hook 的行为逻辑，所以是不能这样改的～

我目前调整成这样了，可以让普通模式下和严格模式下的行为保持一致
https://codesandbox.io/s/reverent-sanderson-quteu?file=/src/hooks/ahooks-usePervious.ts

也求 @brickspert @ttys026 帮忙一起看下

**Comment by Col0ring** [comment]
> @Col0ring 感谢提供这么详细的说明和复现demo～
> 我测试下来发现这个问题其实可以归纳为 ahooks 的 `usePrevious` 在普通模式和严格模式下的行为不一致
> 你提供的这个解决方案虽然可以规避掉这个问题，但是改变了这个 Hook 的行为逻辑，所以是不能这样改的～
> 
> 我目前调整成这样了，可以让普通模式下和严格模式下的行为保持一致
> https://codesandbox.io/s/reverent-sanderson-quteu?file=/src/hooks/ahooks-usePervious.ts
> 
> 也求 @brickspert @ttys026 帮忙一起看下

是的，我可能对于 usePrevious 的理解有误差，实际上该 hook 应该是记录的某个 state 上一次 render 时的状态，而不是记录上一次 state 的值改变时的状态。而我当时的需求实际上是为了保持上一个值的状态，无论有多少次 render 只要 value 值不变就永远为上一个值，或许我应该单独把它拿出来做一个`usePreviousValue`这种 hook 更合理一点吧，哈哈。

**Comment by brickspert** [comment]
1. 当前版本先修复第一个问题。第二个问题是个 break change，我们可以在下个大版本中改成这样。应该 @Col0ring 的建议是比较合理的。

2. 建议目前版本先修复第一个问题，这样改下

```ts
import { useRef, useEffect } from "react";

export type compareFunction<T> = (prev: T | undefined, next: T) => boolean;

function usePrevious<T>(state: T, compare?: compareFunction<T>): T | undefined {
  const prevRef = useRef<T>();

  useEffect(() => {
    const needUpdate =
      typeof compare === "function" ? compare(prevRef.current, state) : true;
    if (needUpdate) {
      prevRef.current = state;
    }
  });

  return prevRef.current;
}

export default usePrevious;

```

**Comment by awmleer** [comment]
Related #780

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
