### ISSUE TITLE
[discuss] what basic hooks should we use ?

### ISSUE THREAD

**Issue by luchx** [alibaba/hooks#92]
## basic hooks list
```
1. useDebounce
2. useThrottle
3. useBoolean
4. useToggle
5. useTimeout
6. useInterval
7. useUpdateEffect
8. useUpdateLayoutEffect
9. useTitle
10. useExpireStorage
```

**Comment by brickspert** [comment]
1. `useBoolean` is an alias for `useToggle`
2. `useLocalStorage ` and `useSessionsStorage` is useful，our `useLocalStorageValue` name is too long，i think it should rename to `useLocalStorage`. @awmleer 
3. `useTimeout ` and `useInterval `  maybe not used often.

```
1. useDebounce
2. useThrottle
3. useToggle
4. usePrevious(optional)
5. useLocalStorage
6. useSessionStorage
7. useExpireStorage(optional)
8. useUpdateEffect
9. useUpdateLayoutEffect(optional)
10. useTitle(optional)
11. useClickAway
12. useKeyPress
13. useMouse
14. useScroll(we have a pr about this)
```

**Comment by ttys026** [comment]
- [useDeepCompare](https://github.com/streamich/react-use/blob/master/docs/useDeepCompareEffect.md) seems useful in some cases.
- useTitle can be refactor to use [react-helmet](https://www.npmjs.com/package/react-helmet), so that we can use it to set some other metadata inside `<head>`

**Comment by luchx** [comment]
> 1. `useBoolean` is an alias for `useToggle`

what i think the `useToggle` is use like a switch, so you can set tow params not just true/false. @brickspert

**Comment by awmleer** [comment]
> useLocalStorage and useSessionsStorage is useful，our useLocalStorageValue name is too long，i think it should rename to useLocalStorage. @awmleer

OK.

**Comment by brickspert** [comment]
> > 1. `useBoolean` is an alias for `useToggle`
> 
> what i think the `useToggle` is use like a switch, so you can set tow params not just true/false. @brickspert

ok, your idea is right, my thoughts are limited by react-use.

**Comment by awmleer** [comment]
- [x] useDebounce @brickspert 
- [x] useThrottle @brickspert 
- [x] useToggle
- [x] useLocalStorage
- [x] useSessionStorage @awmleer
- [x] useUpdateEffect
- [x] useUpdateLayoutEffect @brickspert 
- [x] useClickAway @luchx 
- [x] useKeyPress @luchx 
- [x] useMouse @tli4 
- [x] useScroll @awmleer 
- [ ] useTitle @tli4 
- [x] usePrevious @tli4

**Comment by brickspert** [comment]
> useTitle can be refactor to use react-helmet, so that we can use it to set some other metadata inside <head>

**Comment by brickspert** [comment]
* [ ] [useDeepCompareEffect](https://github.com/streamich/react-use/blob/master/src/useDeepCompareEffect.ts) @brickspert 
* [x] [usefullscreen](https://streamich.github.io/react-use/?path=/story/ui-usefullscreen--demo)
