### ISSUE TITLE
useRequest在ie浏览器中获取不到响应数据

### ISSUE THREAD

**Issue by xu-Aurora** [alibaba/hooks#924]
在chrome上是正常的，但发布到线上之后，在ie上就拿不到接口响应的数据了，获取到的是null

**Comment by brickspert** [comment]
IE 11 吗？方便看下在 IE 上，官网的 demo 是否也不能正常工作~

**Comment by xu-Aurora** [comment]
是ie11，    官网ie都进不去。。。。。

**Comment by brickspert** [comment]
如群里沟通，是 umi-request 的问题。
