### ISSUE TITLE
[RFC] useSelect

### ISSUE THREAD

**Issue by DiamondYuan** [alibaba/hooks#93]
```
import { useState, useMemo } from 'react';

export default function useSelect<T>(items: T[], subItems?: T[]) {
  const [selected, setSelected] = useState<T[]>([]);

  const { subItemsMap, selectedMap, subMode, subSelectedSet } = useMemo(() => {
    const selectedMap = new Set<T>(selected);
    const subItemsMap = new Set<T>(subItems);
    const subMode = Array.isArray(subItems);
    const subSelectedSet = new Set<T>(selected.filter(o => subItemsMap.has(o)));
    return { subItemsMap, selectedMap, subMode, subSelectedSet };
  }, [items, subItems, selected]);

  function isSelected(item: T) {
    return selectedMap.has(item);
  }

  function selectItem(item: T, callback?: (s: T[]) => void) {
    selectedMap.add(item);
    setSelected(Array.from(selectedMap));
    if (callback && typeof callback === 'function') {
      callback(Array.from(selectedMap));
    }
  }

  function deleteItem(item: T, callback?: (s: T[]) => void) {
    selectedMap.delete(item);
    setSelected(Array.from(selectedMap));
    if (callback && typeof callback === 'function') {
      callback(Array.from(selectedMap));
    }
  }

  function selectAll(callback?: (s: T[]) => void) {
    if (subMode) {
      subItems.forEach(o => {
        selectedMap.add(o);
      });
    } else {
      items.forEach(o => {
        selectedMap.add(o);
      });
    }
    setSelected(Array.from(selectedMap));
    if (callback && typeof callback === 'function') {
      callback(Array.from(selectedMap));
    }
  }

  function removeAll(callback?: (s: T[]) => void) {
    let result = [];
    if (subMode) {
      result = selected.filter(o => !subItemsMap.has(o));
    }
    setSelected(result);
    if (callback && typeof callback === 'function') {
      callback(result);
    }
  }

  const noneSelected = subMode ? subSelectedSet.size === 0 : selectedMap.size === 0;

  const allSelected =
    (subMode ? subItems.every(o => subSelectedSet.has(o)) : items.every(o => selectedMap.has(o))) &&
    !noneSelected;

  const selectToggle = (o: T, callback?: (s: T[]) => void) => {
    if (!isSelected(o)) {
      return () => selectItem(o, callback);
    }
    return () => deleteItem(o, callback);
  };

  const toggleAll = (callback?: (s: T[]) => void) => {
    return allSelected ? removeAll(callback) : selectAll(callback);
  };

  const halfSelected = !noneSelected && !allSelected;

  const helper = {
    isSelected,
    selectAll,
    removeAll,
    selectItem,
    allSelected,
    noneSelected,
    deleteItem,
    selectToggle,
    toggleAll,
    halfSelected,
    setSelected,
  };

  return [selected, helper] as [typeof selected, typeof helper];
}
```

**Comment by DiamondYuan** [comment]
列表和子列表。支持 全选/反选，子列表全选/反选，以及全选与半选的状态。

**Comment by brickspert** [comment]
感谢提交 RFC，useSelect 是一个比较好的 hooks idea~

应该目标效果是类似 antd 这个 [全选](https://ant-design.gitee.io/components/checkbox-cn/#components-checkbox-demo-check-all) 例子吧？

我大概写了一下代码：

```javascript
import React from 'react';
import useSelect from './';
import { Checkbox } from 'antd';

const items = [1, 2, 3, 4, 5];

export default () => {

  const [selected, helper] = useSelect<number>(items);

  return (
    <div>
      <div>
        {/* 总 */}
        <Checkbox
          checked={helper.allSelected}
          indeterminate={helper.halfSelected}
          onChange={() => { helper.toggleAll }}
        />
      </div>
      <div>
        {/* 分 */}
        {items.map((item) => {
          <Checkbox
            checked={helper.isSelected(item)}
            onChange={() => { helper.selectToggle }}
          />
        })}
      </div>
    </div>
  )
}
```

有以下几点疑问：

1. 我理解只能支持一个总分结构，那为什么会有 items 和 subItems 呢？能给个例子吗？~
2. items 只支持简单数据类型(string, number)吗？
3. 名字叫 `useSelect` 不太好，建议叫 `useSelections` 或者其它更语义化的名字。
4. useSelect 的参数 items，应该只在初始化话的时候，初始一次，后面不会再动态变化了。类似 useState 的 initialValue。如果要改的话，建议提供一个 changeItems 的 API.
5. API 设计建议统一一下，比如 [useDynamicList](https://hooks.umijs.org/useDynamicList), 直接返回了一个 object.

**Comment by DiamondYuan** [comment]
> 感谢提交 RFC，useSelect 是一个比较好的 hooks idea~
> 
> 应该目标效果是类似 antd 这个 [全选](https://ant-design.gitee.io/components/checkbox-cn/#components-checkbox-demo-check-all) 例子吧？
> 
> 我大概写了一下代码：
> 
> ```js
> import React from 'react';
> import useSelect from './';
> import { Checkbox } from 'antd';
> 
> const items = [1, 2, 3, 4, 5];
> 
> export default () => {
> 
>   const [selected, helper] = useSelect<number>(items);
> 
>   return (
>     <div>
>       <div>
>         {/* 总 */}
>         <Checkbox
>           checked={helper.allSelected}
>           indeterminate={helper.halfSelected}
>           onChange={() => { helper.toggleAll }}
>         />
>       </div>
>       <div>
>         {/* 分 */}
>         {items.map((item) => {
>           <Checkbox
>             checked={helper.isSelected(item)}
>             onChange={() => { helper.selectToggle }}
>           />
>         })}
>       </div>
>     </div>
>   )
> }
> ```
> 
> 有以下几点疑问：
> 
> 1. 我理解只能支持一个总分结构，那为什么会有 items 和 subItems 呢？能给个例子吗？~
> 2. items 只支持简单数据类型(string, number)吗？
> 3. 名字叫 `useSelect` 不太好，建议叫 `useSelections` 或者其它更语义化的名字。
> 4. useSelect 的参数 items，应该只在初始化话的时候，初始一次，后面不会再动态变化了。类似 useState 的 initialValue。如果要改的话，建议提供一个 changeItems 的 API.
> 5. API 设计建议统一一下，比如 [useDynamicList](https://hooks.umijs.org/useDynamicList), 直接返回了一个 object.

api 的确需要统一命名，一边写需求一边加的。
1. subItems 的厂家来自于，例如有20个元素，筛选后变为10个元素。然后这10个元素需要全选和反选。而且去掉筛选以后，原有选择的保持不变。
2.复杂对象应该是支持的，但是只支持简单比较。
3.命名我没确定下来，useSelections挺好的。
4. 这个我没考虑过
5.数组方便重命名，返回数组我觉得挺好。数组第二个元素就是对象。

**Comment by brickspert** [comment]
1. 关于第一点，只用一个 items 应该就可以实现，像下面这样。

```javascript
/* 初始化的时候 */
const [ selected, helper ] = useSelect([1, 2, 3, 4, 5]);

/* 筛选触发  */
helper.changeItems( [1, 2, 3] );

/* 去掉筛选 */
helper.changeItems( [1, 2, 3, 4, 5] );
```

2. 关于返回数组还是对象：目前基本已有 hooks 均是返回的 object，建议保持统一，用户心智统一~


我觉得根据上述建议，可以提交个 PR 啦。👍
