### ISSUE TITLE
feat：通过context api实现服务端状态共享

### ISSUE THREAD

**Issue by YagamiNewLight** [alibaba/hooks#930]
建议像react-query一样，通过Context API把缓存的数据根据cacheKey存到ahooks全局实例中实现服务端状态共享，或者说，为什么不这么做呢

**Comment by brickspert** [comment]
useReqeust 的 cacheKey 也可以实现同样的能力吧~~ 同一个 cacheKey 共用一份数据。

**Comment by YagamiNewLight** [comment]
经过我测试之后发现并不是这样的。
这是ahook使用同一个cacheKey的例子 https://codesandbox.io/s/huancun-swr-forked-j0dx1?file=/App.tsx
这是react-query使用同一个cacheKey的例子 https://codesandbox.io/s/wild-forest-zs0o7?file=/src/index.js
在react-query的例子中refetch数据源组件能够实现订阅者组件的更新，但是ahooks中却做不到这一点
@brickspert

**Comment by brickspert** [comment]
OK 了解你的诉求了，这个我们支持一下。

**Comment by YagamiNewLight** [comment]
好的 谢谢+瑞思拜 @brickspert

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

**Comment by YagamiNewLight** [comment]
源码链接404了

**Comment by brickspert** [comment]
> 源码链接404了

切到 master 分支了：https://github.com/alibaba/hooks

**Comment by YagamiNewLight** [comment]
嗯好的 谢谢支持
