### ISSUE TITLE
关于嵌套路由中使用useRequest的相关疑问

### ISSUE THREAD

**Issue by XdyGoGo** [alibaba/hooks#937]
useRequest  data和loading都会触发re-render
假设我现在有列表页 -> 详情页的需求
结构上采用嵌套路由的形式来实现
列表页：/xxxx  
详情页：/xxxx/id

假设此时列表页请求用了useRequest
详情页会触发至少2次以上

解决的思路也有
1、详情页对传来的params.id去重，只处理一次
2、把嵌套路由改成同级路由，毕竟当我们在详情页的时候，理论上列表页是可以不存在的

疑问：
有没有遇到过同样场景的，有没有更优的解决方案

**Comment by brickspert** [comment]
* 列表页和详情页就应该是两个页面的。
* 还可以使用 React.memo 来自己控制子组件的渲染。
