### ISSUE TITLE
我用useRequest的时候，例如登录功能。第一次请求返回的data是undefinded，第二次才有用户数据，不懂是什么问题...

### ISSUE THREAD

**Issue by iNeedToCopy** [alibaba/hooks#941]
我用useRequest的时候也是，例如登录功能。第一次请求返回的data是undefinded，第二次才有用户数据，不懂是什么问题...

_Originally posted by @weipengzou in https://github.com/alibaba/hooks/issues/750#issuecomment-743724396_

**Comment by brickspert** [comment]
可以提供个示例代码吗？提供个复现~~

**Comment by iNeedToCopy** [comment]
破案了，是因为timeout设置时间太短了，到了timeout接口还没返回直接就返回undefined了，接口没有被cancel，在errorHandle里面增加了type=="Timeout"的提示，目前来看应该是这个原因。。。。。
