### ISSUE TITLE
react新手，问个问题，为什么useEffect里面接收不到useRequest的data

### ISSUE THREAD

**Issue by edcjian** [alibaba/hooks#944]
![UG5F411D`I~LB6XV38SGR8J](https://user-images.githubusercontent.com/48635933/117538648-c7676a80-b039-11eb-9c01-9f8170c9bc59.png)

**Comment by brickspert** [comment]
```js
useEffect(()=>{
    .....
}, [data]);
```

**Comment by edcjian** [comment]
啊，马虎了，谢谢
