### ISSUE TITLE
useInViewport 监听不到切换浏览器 Tab

### ISSUE THREAD

**Issue by gauseen** [alibaba/hooks#945]
useInViewport 用于判断 dom 元素是否在可视范围之内的 Hook，但是当用户切到其他浏览器 Tab 时，dom 是不可见状态，但是inViewPort 却没有变化

**Comment by brickspert** [comment]
useInViewport 是基于 [Intersection Observer API](https://developer.mozilla.org/zh-CN/docs/Web/API/Intersection_Observer_API) 的。

也许你是需要 useDocumentVisibility？
