### ISSUE TITLE
useRequest 设置了initialData值后，在发起请求之前，每次render都可能导致data更新

### ISSUE THREAD

**Issue by yigexiaoairen** [alibaba/hooks#947]
initialData 应该只在初始化时设置一次，不应该支持动态修改，动态修改可以使用Result. mutate 去更新；

```typescript
const { data } = useRequest(service, {
  manual: true,
  initialData: {name: '小明'}
});
useEffect(() => {
   console.log('data 更新');
}, [data])
```

上面这部分代码，在发起请求之前，每次render都会导致data更新;

**Comment by brickspert** [comment]
目前建议通过 useMemo 来处理下 initialData。 

这个 bug 我们修复下。

**Comment by brickspert** [comment]
3.0 版本删除了 initialData，你可以这样用

```js
const {data = initialData} = ...
```

Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
