### ISSUE TITLE
请求：useHistoryTravel是否可以加入一下优化方式

### ISSUE THREAD

**Issue by xmsz** [alibaba/hooks#948]
背景
- 目前来看，useHistoryTravel只是存储的将以往所有数据都储存下来
- 等到表单或列表大的时候消耗就很大

需求
- 能否加入一些类似https://github.com/gaoding-inc/stateshot的优化

**Comment by brickspert** [comment]
useHistoryTravel 可以接收任意类型，不只是复杂类型。

用户可以自己用 immer 来处理数据，然后 set 进来就能满足性能优化的需求。
