### ISSUE TITLE
疑问：useRequest 支持条件轮询吗？

### ISSUE THREAD

**Issue by superman66** [alibaba/hooks#949]
场景：当列表数据满足某个条件的时候，比如状态中包含“计算中”时，则开始轮询请求，直到条件不满足时，取消轮询。

不过查阅文档后，似乎没有找到支持条件下开启轮询的说明。不知道是不是我没有发现正确的用法，还是目前 useRquest 并不支持条件轮询？

本来是想通过一个变量来控制 `pollingInterval`，但也并不起作用。
```
const [polling, setPolling] = useState(true);
 const { data, loading } = useRequest(() => queryUsers(params), {
    refreshDeps: [params],
    pollingInterval: needPolling ? 5000 : undefined,
    pollingWhenHidden: true,
  });

useEffect(() => {
    // 在某些条件下，将 polling 设置为 true
    if(someCondition){
       setPolling(true)
    }
}, [])
```

**Comment by brickspert** [comment]
大概这样就可以

```
const [polling, setPolling] = useState(true);
 const { data, loading, run, cancel } = useRequest(() => queryUsers(params), {
    manual: true,
    refreshDeps: [params],
    pollingInterval: needPolling ? 5000 : undefined,
    pollingWhenHidden: true,
  });

const cancelRef = useRef(cancel);
cancelRef.current = cancel;

useEffect(() => {
    // 在某些条件下，将 polling 设置为 true
    if(someCondition){
       run(xxx)
    }else{
      cancelRef.current();
    }
}, [])
```

**Comment by Trigg3rZY** [comment]
> 大概这样就可以
> 
> ```
> const [polling, setPolling] = useState(true);
>  const { data, loading, run, cancel } = useRequest(() => queryUsers(params), {
>     manual: true,
>     refreshDeps: [params],
>     pollingInterval: needPolling ? 5000 : undefined,
>     pollingWhenHidden: true,
>   });
> 
> const cancelRef = useRef(cancel);
> cancelRef.current = cancel;
> 
> useEffect(() => {
>     // 在某些条件下，将 polling 设置为 true
>     if(someCondition){
>        run(xxx)
>     }else{
>       cancelRef.current();
>     }
> }, [])
> ```

我觉得应该把 cancel 和 reset 视为一次 run() 的副作用清除
```
useEffect(() => {
    if(someCondition){
        run(xxx)
        return () => {
            cancelRef.current?.();
        }
    }
}, [someCondition])
```
否则控制台会警告 'You should't call cancel when service not executed once.'
