### ISSUE TITLE
[问题]： useSafeState打包后报错

### ISSUE THREAD

**Issue by hemengke1997** [alibaba/hooks#959]
### 截图

![image](https://user-images.githubusercontent.com/49073282/119619289-69f35c00-be36-11eb-9b2a-ca298392147b.png)

### 使用方式

```
const [test, setTest] = useSafeState()
```

### 脚手架
antd-pro + umi + webpack5

请问作者大大们，这是什么原因呢？ 我反复检查了，并没有写错语法，且本地正常运行

**Comment by hemengke1997** [comment]
![image](https://user-images.githubusercontent.com/49073282/119622483-c6a44600-be39-11eb-9592-6bc8e9975212.png)

**Comment by hemengke1997** [comment]
看到上图的报错后，猜测是ahook的index中没export setSafeState
解决方法： 
把 `import { setSafeState } from 'ahooks' ` 改为 `import setSafeState from 'ahooks/lib/setSafeState '` or `import setSafeState from 'ahooks/es/setSafeState '`

**Comment by hemengke1997** [comment]
@brickspert  帅哥，我的问题虽然是解决了，但是不知道其他同学有没有遇到这种情况，

**Comment by brickspert** [comment]
你装的哪个版本。。 我看有导出的。
![image](https://user-images.githubusercontent.com/12526493/119625726-17696e00-be3d-11eb-912f-dc4a0293126b.png)

**Comment by hemengke1997** [comment]
> 你装的哪个版本。。 我看有导出的。

"ahooks": "^2.9.4",

我现在装最新的试试看哈。这个版本我确实没注意到，我刚才用了
```
yarn upgrade ahooks
```
然后我以为更新到最新了，就没管版本了。

**Comment by hemengke1997** [comment]
更新到最新版本后冇问题了
