### ISSUE TITLE
useLocalStorageState 的类型问题

### ISSUE THREAD

**Issue by areyouse7en** [alibaba/hooks#967]
最新版本中，useLocalStorageState 的类型定义中去掉了原有的重载函数，导致我现在就算给了默认值，但返回值还是undefined
查看了下历史
https://github.com/alibaba/hooks/pull/381
此前是加过的，但是后来又删了
https://github.com/alibaba/hooks/commit/1e417b33e0a7e90d47ca180ed6fc1129ba7b7816

为什么？

**Comment by awmleer** [comment]
Fixed via #969
