### ISSUE TITLE
useRequest轮询是否可以支持修改pollingInterval

### ISSUE THREAD

**Issue by xiaopohaier** [alibaba/hooks#970]
希望在useRequest轮询过程中，根据外部条件修改pollingInterval的值，从而修改轮询的时间间隔

demo如下：
https://codesandbox.io/s/optimistic-dream-2th4p?file=/src/App.js:428-443
预期在选中0.5倍速时，count累加速度变慢；2倍速时，count累加速度变快

**Comment by brickspert** [comment]
收到需求，我们考虑下。

**Comment by ida-fe** [comment]
这个功能有考虑支持吗？或者可以通过什么其他方式实现吗？

**Comment by brickspert** [comment]
> 这个功能有考虑支持吗？或者可以通过什么其他方式实现吗？

暂时不支持，下个大版本考虑支持。

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
