### ISSUE TITLE
useAntdTable的搜索项表单验证 在antd4中如何实现?

### ISSUE THREAD

**Issue by hudson-dong** [alibaba/hooks#974]
https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useAntdTable/demo/demo6.tsx
官网的这个例子用的 antd3.x的,
antd4的话是直接在onFinish里进去submit()操作吗

**Comment by brickspert** [comment]
```js
<Form.Item
        label="Username"
        name="username"
        rules={[{ required: true, message: 'Please input your username!' }]}
      >
        <Input />
</Form.Item>
```

表单项上正常配置 rules 即可。

**Comment by hudson-dong** [comment]
需要 onFinish里进去submit()操作吗 ,直接submit()发现没有走校验

**Comment by brickspert** [comment]
直接调用 search.submit() 可以的吧
