### ISSUE TITLE
ahook库解决的是什么问题

### ISSUE THREAD

**Issue by liyuanqing** [alibaba/hooks#976]
我之前一直用react类组件写法，最近刚接触hook,了解到了ahook库，想知道ahook解决的是什么痛点或问题而产生的，是怎么解决这写痛点或问题的。在官网和其他地方都没找到相关的描述，不知道是否可以增加相关文档，方便初学者了解ahook

**Comment by brickspert** [comment]
Umi Hooks - 助力拥抱 React Hooks：https://zhuanlan.zhihu.com/p/103150605
