### ISSUE TITLE
useRequest 所有请求是否能以 ready 参数为前提

### ISSUE THREAD

**Issue by raohong** [alibaba/hooks#977]
```
{
  ready: visible && !!id, 
  refreshDeps: [id]
}
```

如上配置，id  可能为空。
在某些时候请求是需要在某些特定时刻才能请求，比如传入了 id, 但同时 id 变化的时候要重新请求，这时候如果 id  为空，依照现有版本会触发刷新。但这里是否是先判断 `ready`  为真才进行请求比较好？

**Comment by brickspert** [comment]
related: https://github.com/alibaba/hooks/discussions/1291

可以来这里讨论 ready 的行为。
