### ISSUE TITLE
useRequest 是否支持请求队列

### ISSUE THREAD

**Issue by guoyunhe** [alibaba/hooks#980]
假设在一个轮询场景中，每隔 3 秒查询一次服务器状态，但后端接口的返回时间高度不确定，从几秒到几十秒不等。

在第 1 秒发送了请求 A，在第 9 秒收到了响应 A，触发状态变更。
在第 4 秒发送了请求 B，在第 6 秒收到了响应 B，触发状态变更。

从结果看，最终状态时响应 A 的。但是我们需要的是最新的状态，也就是响应 B 的结果。而且用一两秒的防抖或截留并不能解决这个问题。

我在实际项目里通常要给每个请求生成一个随机 token，然后记忆最后一个签发的 lastToken，在返回响应结果时去比对，如果不是 lastToken 则抛弃掉响应，不更改状态。

请问 ahooks 有没有对这种场景的解决方案？

**Comment by brickspert** [comment]
useRequest 的轮询是基于队列的，也就是会等 A 请求响应后，才会开始定时。

开始-请求A-A响应-等待 n 秒-请求B-B响应

**Comment by guoyunhe** [comment]
useRequest 不是我们目前需要的解决方案。我们需要的是不管 A 请求是否返回，都立即发送 B 请求，以最快响应用户输入。有点类似 UDP。
