### ISSUE TITLE
Move "react" and "react-dom" from "devDependencies" to "peerDependencies".

### ISSUE THREAD

**Issue by tsevdos** [alibaba/hooks#982]
Hello there,

I'd like to strongly suggest to move  "react" and "react-dom", from "devDependencies" to "peerDependencies". NPM 7 and above (I use 7.14.0), breaks the installation (`npm i`) when you try to install the module as it is. In order to succed in npm version 7 and above, is to run `npm i --force` which is not so great as you can understand.

The fix looks pretty easy, I can make a pull request in order to resolve this issue. Please let me know if you are ok in order to proceed.  

best regards,
John

**Comment by brickspert** [comment]
Hi man,

ahooks is based on lerna, The package.json that is actually used is in [packages/ahooks](https://github.com/alibaba/hooks/blob/master/packages/hooks/package.json)，It fits your description.

Thank you very much!
