### ISSUE TITLE
[疑问] useControllableValue 为什么要在有 props.value 的情况下将 props.value 同步到 state

### ISSUE THREAD

**Issue by kucinl** [alibaba/hooks#984]
https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useControllableValue/index.ts#L46
看起来在有 props.value 的情况下，是不会用到 stateValue 的，现在这种写法会导致value变化时，组件多渲染一次

**Comment by awmleer** [comment]
在极端情况下，用户可能会从受控模式切换到非受控模式

**Comment by kucinl** [comment]
这种情况可能直接判断是否由 受控模式切换到非受控模式 来进行值的判断更好？
某些组件对组件渲染次数比较敏感

**Comment by awmleer** [comment]
嗯嗯我们考虑一下，感谢

**Comment by brickspert** [comment]
这段代码确实可以删除，3.0 会优化这里~

**Comment by brickspert** [comment]
Hello：

这个问题我们已经在 v3.0 版本彻底修复，目前 v3.0 版本已经发布 alpha 版本。

欢迎试用。

文档：https://ahooks-next.surge.sh/
源码：https://github.com/alibaba/hooks/tree/next

安装最新分支
```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```

We have fixed this problem in the v3.0 version, and the alpha has been released. 

Welcome to try.

Doc：https://ahooks-next.surge.sh/
Source Code：https://github.com/alibaba/hooks/tree/next

Install v3.0

```
$ npm install --save ahooks@next
# or
$ yarn add ahooks@next
```
