### ISSUE TITLE
useScroll在antd中使用无效

### ISSUE THREAD

**Issue by strongyc** [alibaba/hooks#993]
useScroll在antd中使用无效，无论滚动条如何滚动，始终为0
![image](https://user-images.githubusercontent.com/51156342/122636027-ab1b1b00-d119-11eb-9d8c-c3b7d2a122de.png)

![image](https://user-images.githubusercontent.com/51156342/122636066-cdad3400-d119-11eb-9274-6780f55d6ae2.png)

**Comment by brickspert** [comment]
中间的滚动区域应该不是 document，可以审查元素看看。

**Comment by brickspert** [comment]
如果还有问题，reopen 哈。
