### ISSUE TITLE
useRequest第一个参数service，是object时，可以设置哪些属性

### ISSUE THREAD

**Issue by net027** [alibaba/hooks#994]
参考了umi-request的参数设置

想发送一个请求： 
GET http://localhost:5000/api/v1/data?month=2021-06

```javascript
const service={
    url:'/data',
    method: 'get',
    prefix:'http://localhost:5000/api/v1',
    params:{
        month: '2021-06'
    },
    headers:{
        "Authorization":"Bearer eyJhbGciOiJSUzI1NiIs..."
    }
}
```
按上面的参数设置，prefix和params没有起作用，headers 可以添加到requestHeader中

实际发送的请求地址：/data
requestheader:
Authorization: Bearer eyJhbGciOiJSUzI1NiIs...

不想手动拼接url的后的querystring，该怎么配置

**Comment by brickspert** [comment]
useRequest 默认是使用 fetch 发起的请求，支持 fetch 的参数。

如果你要用 umi-request，可以全局设置 requestMethod。
